export default {
  defAppViewId: 'web.welcome',
  defaultPage: true,
  accUserMode: 3,
  caption: 'quickstart',
  codeName: 'admin_index',
  appCounterRefs: [
    {
      appCounter: {
        codeName: 'Counter',
        counterType: 'DEDR',
        getAppDEActionId: 'get_counter_data',
        appDataEntityId: 'web.master',
        timer: 60000,
        uniqueTag: 'Counter',
        name: '计数器',
        id: 'web.counter',
      },
      tag: 'c08c472f59332aa507b4952a6d4e5c5f',
      uniqueTag: 'Counter',
      id: 'c08c472f59332aa507b4952a6d4e5c5f',
    },
  ],
  controls: [
    {
      layoutMode: 'TABLE_24COL',
      appCounterRefId: 'c08c472f59332aa507b4952a6d4e5c5f',
      appMenuItems: [
        {
          itemType: 'MENUITEM',
          appMenuItems: [
            {
              accUserMode: 3,
              itemType: 'MENUITEM',
              appFuncId: 'appfunc',
              layout: {
                columnCount: 24,
                layout: 'TABLE_24COL',
              },
              layoutPos: {
                colMD: 24,
                layout: 'TABLE_24COL',
              },
              valid: true,
              caption: 'CRUD',
              tooltip: 'CRUD',
              id: 'menuitem105',
            },
            {
              accUserMode: 3,
              itemType: 'MENUITEM',
              appFuncId: 'layout',
              layout: {
                columnCount: 24,
                layout: 'TABLE_24COL',
              },
              layoutPos: {
                colMD: 24,
                layout: 'TABLE_24COL',
              },
              valid: true,
              caption: '布局排版',
              tooltip: '布局排版',
              id: 'menuitem5',
            },
            {
              accUserMode: 3,
              itemType: 'MENUITEM',
              appFuncId: 'appfunc2',
              layout: {
                columnCount: 24,
                layout: 'TABLE_24COL',
              },
              layoutPos: {
                colMD: 24,
                layout: 'TABLE_24COL',
              },
              valid: true,
              caption: '导航视图',
              tooltip: '导航视图',
              id: 'menuitem6',
            },
          ],
          layout: {
            columnCount: 24,
            layout: 'TABLE_24COL',
          },
          layoutPos: {
            colMD: 24,
            layout: 'TABLE_24COL',
          },
          sysImage: {
            cssClass: 'fa fa-th-large',
            glyph: 'xf009@FontAwesome',
          },
          valid: true,
          caption: '基础',
          tooltip: '基础',
          id: 'menuitem3',
        },
        {
          itemType: 'MENUITEM',
          appMenuItems: [
            {
              accUserMode: 3,
              itemType: 'MENUITEM',
              appFuncId: 'usrappfunc0516176444',
              layout: {
                columnCount: 24,
                layout: 'TABLE_24COL',
              },
              layoutPos: {
                colMD: 24,
                layout: 'TABLE_24COL',
              },
              valid: true,
              caption: '面板',
              tooltip: '面板',
              id: 'menuitem62',
            },
            {
              accUserMode: 2,
              itemType: 'MENUITEM',
              appFuncId: 'appfunc58',
              layout: {
                columnCount: 24,
                layout: 'TABLE_24COL',
              },
              layoutPos: {
                colMD: 24,
                layout: 'TABLE_24COL',
              },
              valid: true,
              caption: '视图布局面板',
              tooltip: '视图布局面板',
              id: 'menuitem115',
            },
            {
              accUserMode: 3,
              itemType: 'MENUITEM',
              appFuncId: 'usrappfunc0513841565',
              layout: {
                columnCount: 24,
                layout: 'TABLE_24COL',
              },
              layoutPos: {
                colMD: 24,
                layout: 'TABLE_24COL',
              },
              valid: true,
              caption: '搜索栏',
              tooltip: '搜索栏',
              id: 'menuitem73',
            },
            {
              itemType: 'MENUITEM',
              appFuncId: 'top_menu',
              layout: {
                columnCount: 24,
                layout: 'TABLE_24COL',
              },
              layoutPos: {
                colMD: 24,
                layout: 'TABLE_24COL',
              },
              valid: true,
              caption: '菜单',
              tooltip: '菜单',
              id: 'menuitem11',
            },
            {
              accUserMode: 3,
              itemType: 'MENUITEM',
              appFuncId: 'search_form',
              layout: {
                columnCount: 24,
                layout: 'TABLE_24COL',
              },
              layoutPos: {
                colMD: 24,
                layout: 'TABLE_24COL',
              },
              valid: true,
              caption: '搜索表单',
              tooltip: '搜索表单',
              id: 'menuitem14',
            },
            {
              accUserMode: 3,
              itemType: 'MENUITEM',
              appFuncId: 'usrappfunc0513604403',
              layout: {
                columnCount: 24,
                layout: 'TABLE_24COL',
              },
              layoutPos: {
                colMD: 24,
                layout: 'TABLE_24COL',
              },
              valid: true,
              caption: '编辑表单',
              tooltip: '编辑表单',
              id: 'menuitem13',
            },
            {
              accUserMode: 3,
              itemType: 'MENUITEM',
              appFuncId: 'appfunc60',
              layout: {
                columnCount: 24,
                layout: 'TABLE_24COL',
              },
              layoutPos: {
                colMD: 24,
                layout: 'TABLE_24COL',
              },
              valid: true,
              caption: '数据关系分页',
              tooltip: '数据关系分页',
              id: 'menuitem117',
            },
            {
              accUserMode: 3,
              itemType: 'MENUITEM',
              appFuncId: 'appfunc61',
              layout: {
                columnCount: 24,
                layout: 'TABLE_24COL',
              },
              layoutPos: {
                colMD: 24,
                layout: 'TABLE_24COL',
              },
              valid: true,
              caption: '数据关系栏',
              tooltip: '数据关系栏',
              id: 'menuitem118',
            },
            {
              accUserMode: 3,
              itemType: 'MENUITEM',
              appFuncId: 'usrappfunc0513956708',
              layout: {
                columnCount: 24,
                layout: 'TABLE_24COL',
              },
              layoutPos: {
                colMD: 24,
                layout: 'TABLE_24COL',
              },
              valid: true,
              caption: '工具栏',
              tooltip: '工具栏',
              id: 'menuitem18',
            },
            {
              accUserMode: 3,
              itemType: 'MENUITEM',
              appFuncId: 'usrappfunc0513751340',
              layout: {
                columnCount: 24,
                layout: 'TABLE_24COL',
              },
              layoutPos: {
                colMD: 24,
                layout: 'TABLE_24COL',
              },
              valid: true,
              caption: '表格',
              tooltip: '表格',
              id: 'menuitem15',
            },
            {
              accUserMode: 3,
              itemType: 'MENUITEM',
              appFuncId: 'usrappfunc0513575201',
              layout: {
                columnCount: 24,
                layout: 'TABLE_24COL',
              },
              layoutPos: {
                colMD: 24,
                layout: 'TABLE_24COL',
              },
              valid: true,
              caption: '列表',
              tooltip: '列表',
              id: 'menuitem16',
            },
            {
              accUserMode: 3,
              itemType: 'MENUITEM',
              appFuncId: 'usrappfunc0513647185',
              layout: {
                columnCount: 24,
                layout: 'TABLE_24COL',
              },
              layoutPos: {
                colMD: 24,
                layout: 'TABLE_24COL',
              },
              valid: true,
              caption: '卡片',
              tooltip: '卡片',
              id: 'menuitem19',
            },
            {
              accUserMode: 3,
              itemType: 'MENUITEM',
              appFuncId: 'appfunc63',
              layout: {
                columnCount: 24,
                layout: 'TABLE_24COL',
              },
              layoutPos: {
                colMD: 24,
                layout: 'TABLE_24COL',
              },
              valid: true,
              caption: '分页导航面板',
              tooltip: '分页导航面板',
              id: 'menuitem120',
            },
            {
              accUserMode: 3,
              itemType: 'MENUITEM',
              appFuncId: 'usrappfunc0513354669',
              layout: {
                columnCount: 24,
                layout: 'TABLE_24COL',
              },
              layoutPos: {
                colMD: 24,
                layout: 'TABLE_24COL',
              },
              valid: true,
              caption: '树部件',
              tooltip: '树部件',
              id: 'menuitem17',
            },
            {
              accUserMode: 3,
              itemType: 'MENUITEM',
              appFuncId: 'appfunc64',
              layout: {
                columnCount: 24,
                layout: 'TABLE_24COL',
              },
              layoutPos: {
                colMD: 24,
                layout: 'TABLE_24COL',
              },
              valid: true,
              caption: '看板',
              tooltip: '看板',
              id: 'menuitem121',
            },
            {
              accUserMode: 3,
              itemType: 'MENUITEM',
              appFuncId: 'usrappfunc0514013432',
              layout: {
                columnCount: 24,
                layout: 'TABLE_24COL',
              },
              layoutPos: {
                colMD: 24,
                layout: 'TABLE_24COL',
              },
              valid: true,
              caption: '地图',
              tooltip: '地图',
              id: 'menuitem31',
            },
            {
              accUserMode: 3,
              itemType: 'MENUITEM',
              appFuncId: 'usrappfunc0513396006',
              layout: {
                columnCount: 24,
                layout: 'TABLE_24COL',
              },
              layoutPos: {
                colMD: 24,
                layout: 'TABLE_24COL',
              },
              valid: true,
              caption: '日历',
              tooltip: '日历',
              id: 'menuitem22',
            },
            {
              accUserMode: 3,
              itemType: 'MENUITEM',
              appFuncId: 'usrappfunc0513691235',
              layout: {
                columnCount: 24,
                layout: 'TABLE_24COL',
              },
              layoutPos: {
                colMD: 24,
                layout: 'TABLE_24COL',
              },
              valid: true,
              caption: '图表',
              tooltip: '图表',
              id: 'menuitem21',
            },
            {
              accUserMode: 2,
              itemType: 'MENUITEM',
              appFuncId: 'appfunc72',
              layout: {
                columnCount: 24,
                layout: 'TABLE_24COL',
              },
              layoutPos: {
                colMD: 24,
                layout: 'TABLE_24COL',
              },
              valid: true,
              caption: '树表格',
              tooltip: '树表格',
              id: 'menuitem129',
            },
            {
              accUserMode: 2,
              itemType: 'MENUITEM',
              appFuncId: 'appfunc62',
              layout: {
                columnCount: 24,
                layout: 'TABLE_24COL',
              },
              layoutPos: {
                colMD: 24,
                layout: 'TABLE_24COL',
              },
              valid: true,
              caption: '树视图增强',
              tooltip: '树视图增强',
              id: 'menuitem119',
            },
            {
              accUserMode: 3,
              itemType: 'MENUITEM',
              appFuncId: 'appfunc40',
              layout: {
                columnCount: 24,
                layout: 'TABLE_24COL',
              },
              layoutPos: {
                colMD: 24,
                layout: 'TABLE_24COL',
              },
              valid: true,
              caption: '甘特图',
              tooltip: '甘特图',
              id: 'menuitem109',
            },
            {
              accUserMode: 3,
              itemType: 'MENUITEM',
              appFuncId: 'usrappfunc0514396236',
              layout: {
                columnCount: 24,
                layout: 'TABLE_24COL',
              },
              layoutPos: {
                colMD: 24,
                layout: 'TABLE_24COL',
              },
              valid: true,
              caption: '数据看板',
              tooltip: '数据看板',
              id: 'menuitem23',
            },
            {
              accUserMode: 3,
              itemType: 'MENUITEM',
              appFuncId: 'appfunc65',
              layout: {
                columnCount: 24,
                layout: 'TABLE_24COL',
              },
              layoutPos: {
                colMD: 24,
                layout: 'TABLE_24COL',
              },
              valid: true,
              caption: '日历导航栏',
              tooltip: '日历导航栏',
              id: 'menuitem122',
            },
            {
              accUserMode: 3,
              itemType: 'MENUITEM',
              appFuncId: 'appfunc66',
              layout: {
                columnCount: 24,
                layout: 'TABLE_24COL',
              },
              layoutPos: {
                colMD: 24,
                layout: 'TABLE_24COL',
              },
              valid: true,
              caption: '图表导航栏',
              tooltip: '图表导航栏',
              id: 'menuitem123',
            },
            {
              accUserMode: 3,
              itemType: 'MENUITEM',
              appFuncId: 'appfunc67',
              layout: {
                columnCount: 24,
                layout: 'TABLE_24COL',
              },
              layoutPos: {
                colMD: 24,
                layout: 'TABLE_24COL',
              },
              valid: true,
              caption: '树导航栏',
              tooltip: '树导航栏',
              id: 'menuitem124',
            },
            {
              accUserMode: 3,
              itemType: 'MENUITEM',
              appFuncId: 'appfunc68',
              layout: {
                columnCount: 24,
                layout: 'TABLE_24COL',
              },
              layoutPos: {
                colMD: 24,
                layout: 'TABLE_24COL',
              },
              valid: true,
              caption: '列表导航栏',
              tooltip: '列表导航栏',
              id: 'menuitem125',
            },
            {
              accUserMode: 3,
              itemType: 'MENUITEM',
              appFuncId: 'appfunc69',
              layout: {
                columnCount: 24,
                layout: 'TABLE_24COL',
              },
              layoutPos: {
                colMD: 24,
                layout: 'TABLE_24COL',
              },
              valid: true,
              caption: '表格导航栏',
              tooltip: '表格导航栏',
              id: 'menuitem126',
            },
            {
              accUserMode: 3,
              itemType: 'MENUITEM',
              appFuncId: 'appfunc70',
              layout: {
                columnCount: 24,
                layout: 'TABLE_24COL',
              },
              layoutPos: {
                colMD: 24,
                layout: 'TABLE_24COL',
              },
              valid: true,
              caption: '数据卡片导航栏',
              tooltip: '数据卡片导航栏',
              id: 'menuitem127',
            },
            {
              accUserMode: 2,
              itemType: 'MENUITEM',
              appFuncId: 'appfunc59',
              layout: {
                columnCount: 24,
                layout: 'TABLE_24COL',
              },
              layoutPos: {
                colMD: 24,
                layout: 'TABLE_24COL',
              },
              valid: true,
              caption: '多编辑视图面板',
              tooltip: '多编辑视图面板',
              id: 'menuitem116',
            },
            {
              accUserMode: 3,
              itemType: 'MENUITEM',
              appFuncId: 'appfunc71',
              layout: {
                columnCount: 24,
                layout: 'TABLE_24COL',
              },
              layoutPos: {
                colMD: 24,
                layout: 'TABLE_24COL',
              },
              valid: true,
              caption: '选择视图面板',
              tooltip: '选择视图面板',
              id: 'menuitem128',
            },
            {
              accUserMode: 3,
              itemType: 'MENUITEM',
              appFuncId: 'appfunc74',
              layout: {
                columnCount: 24,
                layout: 'TABLE_24COL',
              },
              layoutPos: {
                colMD: 24,
                layout: 'TABLE_24COL',
              },
              valid: true,
              caption: '报表部件',
              tooltip: '报表部件',
              id: 'menuitem131',
            },
            {
              accUserMode: 3,
              itemType: 'MENUITEM',
              appFuncId: 'usrappfunc0513802612',
              layout: {
                columnCount: 24,
                layout: 'TABLE_24COL',
              },
              layoutPos: {
                colMD: 24,
                layout: 'TABLE_24COL',
              },
              valid: true,
              caption: '向导',
              tooltip: '向导',
              id: 'menuitem30',
            },
          ],
          layout: {
            columnCount: 24,
            layout: 'TABLE_24COL',
          },
          layoutPos: {
            colMD: 24,
            layout: 'TABLE_24COL',
          },
          sysImage: {
            cssClass: 'fa fa-th-large',
            glyph: 'xf009@FontAwesome',
          },
          valid: true,
          caption: '部件',
          tooltip: '部件',
          id: 'menuitem10',
        },
        {
          itemType: 'MENUITEM',
          appMenuItems: [
            {
              accUserMode: 3,
              itemType: 'MENUITEM',
              appFuncId: 'appfunc5',
              layout: {
                columnCount: 24,
                layout: 'TABLE_24COL',
              },
              layoutPos: {
                colMD: 24,
                layout: 'TABLE_24COL',
              },
              valid: true,
              caption: '标签',
              tooltip: '标签',
              id: 'menuitem58',
            },
            {
              accUserMode: 3,
              itemType: 'MENUITEM',
              appFuncId: 'appfunc6',
              layout: {
                columnCount: 24,
                layout: 'TABLE_24COL',
              },
              layoutPos: {
                colMD: 24,
                layout: 'TABLE_24COL',
              },
              valid: true,
              caption: '标签链接',
              tooltip: '标签链接',
              id: 'menuitem59',
            },
            {
              accUserMode: 3,
              itemType: 'MENUITEM',
              appFuncId: 'appfunc7',
              layout: {
                columnCount: 24,
                layout: 'TABLE_24COL',
              },
              layoutPos: {
                colMD: 24,
                layout: 'TABLE_24COL',
              },
              valid: true,
              caption: '直接内容',
              tooltip: '直接内容',
              id: 'menuitem60',
            },
            {
              accUserMode: 3,
              itemType: 'MENUITEM',
              appFuncId: 'appfunc8',
              layout: {
                columnCount: 24,
                layout: 'TABLE_24COL',
              },
              layoutPos: {
                colMD: 24,
                layout: 'TABLE_24COL',
              },
              valid: true,
              caption: '文本框',
              tooltip: '文本框',
              id: 'menuitem61',
            },
            {
              accUserMode: 3,
              itemType: 'MENUITEM',
              appFuncId: 'appfunc9',
              layout: {
                columnCount: 24,
                layout: 'TABLE_24COL',
              },
              layoutPos: {
                colMD: 24,
                layout: 'TABLE_24COL',
              },
              valid: true,
              caption: '数值框',
              tooltip: '数值框',
              id: 'menuitem63',
            },
            {
              accUserMode: 3,
              itemType: 'MENUITEM',
              appFuncId: 'appfunc10',
              layout: {
                columnCount: 24,
                layout: 'TABLE_24COL',
              },
              layoutPos: {
                colMD: 24,
                layout: 'TABLE_24COL',
              },
              valid: true,
              caption: 'IP地址输入框',
              tooltip: 'IP地址输入框',
              id: 'menuitem64',
            },
            {
              accUserMode: 3,
              itemType: 'MENUITEM',
              appFuncId: 'usrappfunc0516975076',
              layout: {
                columnCount: 24,
                layout: 'TABLE_24COL',
              },
              layoutPos: {
                colMD: 24,
                layout: 'TABLE_24COL',
              },
              valid: true,
              caption: '开关',
              tooltip: '开关',
              id: 'menuitem65',
            },
            {
              accUserMode: 3,
              itemType: 'MENUITEM',
              appFuncId: 'usrappfunc0516022219',
              layout: {
                columnCount: 24,
                layout: 'TABLE_24COL',
              },
              layoutPos: {
                colMD: 24,
                layout: 'TABLE_24COL',
              },
              valid: true,
              caption: '步进器',
              tooltip: '步进器',
              id: 'menuitem66',
            },
            {
              accUserMode: 3,
              itemType: 'MENUITEM',
              appFuncId: 'usrappfunc0516790226',
              layout: {
                columnCount: 24,
                layout: 'TABLE_24COL',
              },
              layoutPos: {
                colMD: 24,
                layout: 'TABLE_24COL',
              },
              valid: true,
              caption: '评分器',
              tooltip: '评分器',
              id: 'menuitem67',
            },
            {
              accUserMode: 3,
              itemType: 'MENUITEM',
              appFuncId: 'usrappfunc0516349482',
              layout: {
                columnCount: 24,
                layout: 'TABLE_24COL',
              },
              layoutPos: {
                colMD: 24,
                layout: 'TABLE_24COL',
              },
              valid: true,
              caption: '进度条',
              tooltip: '进度条',
              id: 'menuitem68',
            },
            {
              accUserMode: 3,
              itemType: 'MENUITEM',
              appFuncId: 'usrappfunc0516701853',
              layout: {
                columnCount: 24,
                layout: 'TABLE_24COL',
              },
              layoutPos: {
                colMD: 24,
                layout: 'TABLE_24COL',
              },
              valid: true,
              caption: '选项框',
              tooltip: '选项框',
              id: 'menuitem76',
            },
            {
              accUserMode: 3,
              itemType: 'MENUITEM',
              appFuncId: 'usrappfunc0516981648',
              layout: {
                columnCount: 24,
                layout: 'TABLE_24COL',
              },
              layoutPos: {
                colMD: 24,
                layout: 'TABLE_24COL',
              },
              valid: true,
              caption: '列表框',
              tooltip: '列表框',
              id: 'menuitem77',
            },
            {
              accUserMode: 3,
              itemType: 'MENUITEM',
              appFuncId: 'usrappfunc0516808972',
              layout: {
                columnCount: 24,
                layout: 'TABLE_24COL',
              },
              layoutPos: {
                colMD: 24,
                layout: 'TABLE_24COL',
              },
              valid: true,
              caption: '选项框列表',
              tooltip: '选项框列表',
              id: 'menuitem4',
            },
            {
              accUserMode: 3,
              itemType: 'MENUITEM',
              appFuncId: 'usrappfunc0516372702',
              layout: {
                columnCount: 24,
                layout: 'TABLE_24COL',
              },
              layoutPos: {
                colMD: 24,
                layout: 'TABLE_24COL',
              },
              valid: true,
              caption: '单选框列表',
              tooltip: '单选框列表',
              id: 'menuitem78',
            },
            {
              accUserMode: 3,
              itemType: 'MENUITEM',
              appFuncId: 'usrappfunc0516570337',
              layout: {
                columnCount: 24,
                layout: 'TABLE_24COL',
              },
              layoutPos: {
                colMD: 24,
                layout: 'TABLE_24COL',
              },
              valid: true,
              caption: '下拉列表框',
              tooltip: '下拉列表框',
              id: 'menuitem79',
            },
            {
              accUserMode: 3,
              itemType: 'MENUITEM',
              appFuncId: 'usrappfunc0516143021',
              layout: {
                columnCount: 24,
                layout: 'TABLE_24COL',
              },
              layoutPos: {
                colMD: 24,
                layout: 'TABLE_24COL',
              },
              valid: true,
              caption: '虚拟化选择器（扩展）',
              tooltip: '虚拟化选择器（扩展）',
              id: 'menuitem80',
            },
            {
              accUserMode: 3,
              itemType: 'MENUITEM',
              appFuncId: 'appfunc11',
              layout: {
                columnCount: 24,
                layout: 'TABLE_24COL',
              },
              layoutPos: {
                colMD: 24,
                layout: 'TABLE_24COL',
              },
              valid: true,
              caption: '表情下拉选择（扩展）',
              tooltip: '表情下拉选择（扩展）',
              id: 'menuitem82',
            },
            {
              accUserMode: 2,
              itemType: 'MENUITEM',
              appFuncId: 'appfunc79',
              layout: {
                columnCount: 24,
                layout: 'TABLE_24COL',
              },
              layoutPos: {
                colMD: 24,
                layout: 'TABLE_24COL',
              },
              valid: true,
              caption: '树形多选（扩展）',
              tooltip: '树形多选（扩展）',
              id: 'menuitem134',
            },
            {
              accUserMode: 3,
              itemType: 'MENUITEM',
              appFuncId: 'appfunc12',
              layout: {
                columnCount: 24,
                layout: 'TABLE_24COL',
              },
              layoutPos: {
                colMD: 24,
                layout: 'TABLE_24COL',
              },
              valid: true,
              caption: '级联选择器',
              tooltip: '级联选择器',
              id: 'menuitem83',
            },
            {
              accUserMode: 3,
              itemType: 'MENUITEM',
              appFuncId: 'appfunc13',
              layout: {
                columnCount: 24,
                layout: 'TABLE_24COL',
              },
              layoutPos: {
                colMD: 24,
                layout: 'TABLE_24COL',
              },
              valid: true,
              caption: '时间选择器',
              tooltip: '时间选择器',
              id: 'menuitem84',
            },
            {
              accUserMode: 3,
              itemType: 'MENUITEM',
              appFuncId: 'appfunc14',
              layout: {
                columnCount: 24,
                layout: 'TABLE_24COL',
              },
              layoutPos: {
                colMD: 24,
                layout: 'TABLE_24COL',
              },
              valid: true,
              caption: '时间范围选择',
              tooltip: '时间范围选择',
              id: 'menuitem85',
            },
            {
              accUserMode: 3,
              itemType: 'MENUITEM',
              appFuncId: 'appfunc15',
              layout: {
                columnCount: 24,
                layout: 'TABLE_24COL',
              },
              layoutPos: {
                colMD: 24,
                layout: 'TABLE_24COL',
              },
              valid: true,
              caption: '时间范围选择（扩展）',
              tooltip: '时间范围选择（扩展）',
              id: 'menuitem86',
            },
            {
              accUserMode: 3,
              itemType: 'MENUITEM',
              appFuncId: 'appfunc18',
              layout: {
                columnCount: 24,
                layout: 'TABLE_24COL',
              },
              layoutPos: {
                colMD: 24,
                layout: 'TABLE_24COL',
              },
              valid: true,
              caption: '自动填充',
              tooltip: '自动填充',
              id: 'menuitem87',
            },
            {
              accUserMode: 3,
              itemType: 'MENUITEM',
              appFuncId: 'appfunc21',
              layout: {
                columnCount: 24,
                layout: 'TABLE_24COL',
              },
              layoutPos: {
                colMD: 24,
                layout: 'TABLE_24COL',
              },
              valid: true,
              caption: '数据选择',
              tooltip: '数据选择',
              id: 'menuitem88',
            },
            {
              accUserMode: 3,
              itemType: 'MENUITEM',
              appFuncId: 'appfunc24',
              layout: {
                columnCount: 24,
                layout: 'TABLE_24COL',
              },
              layoutPos: {
                colMD: 24,
                layout: 'TABLE_24COL',
              },
              valid: true,
              caption: '数据链接',
              tooltip: '数据链接',
              id: 'menuitem91',
            },
            {
              accUserMode: 3,
              itemType: 'MENUITEM',
              appFuncId: 'appfunc22',
              layout: {
                columnCount: 24,
                layout: 'TABLE_24COL',
              },
              layoutPos: {
                colMD: 24,
                layout: 'TABLE_24COL',
              },
              valid: true,
              caption: '数据选择（下拉）',
              tooltip: '数据选择（下拉）',
              id: 'menuitem89',
            },
            {
              accUserMode: 3,
              itemType: 'MENUITEM',
              appFuncId: 'appfunc23',
              layout: {
                columnCount: 24,
                layout: 'TABLE_24COL',
              },
              layoutPos: {
                colMD: 24,
                layout: 'TABLE_24COL',
              },
              valid: true,
              caption: '数据选择（嵌入选择视图）',
              tooltip: '数据选择（嵌入选择视图）',
              id: 'menuitem90',
            },
            {
              accUserMode: 3,
              itemType: 'MENUITEM',
              appFuncId: 'appfunc25',
              layout: {
                columnCount: 24,
                layout: 'TABLE_24COL',
              },
              layoutPos: {
                colMD: 24,
                layout: 'TABLE_24COL',
              },
              valid: true,
              caption: '数据选择（下拉视图）',
              tooltip: '数据选择（下拉视图）',
              id: 'menuitem92',
            },
            {
              accUserMode: 3,
              itemType: 'MENUITEM',
              appFuncId: 'appfunc26',
              layout: {
                columnCount: 24,
                layout: 'TABLE_24COL',
              },
              layoutPos: {
                colMD: 24,
                layout: 'TABLE_24COL',
              },
              valid: true,
              caption: '地址框选择',
              tooltip: '地址框选择',
              id: 'menuitem93',
            },
            {
              accUserMode: 2,
              itemType: 'MENUITEM',
              appFuncId: 'appfunc80',
              layout: {
                columnCount: 24,
                layout: 'TABLE_24COL',
              },
              layoutPos: {
                colMD: 24,
                layout: 'TABLE_24COL',
              },
              valid: true,
              caption: '穿梭框选择（扩展）',
              tooltip: '穿梭框选择（扩展）',
              id: 'menuitem135',
            },
            {
              accUserMode: 3,
              itemType: 'MENUITEM',
              appFuncId: 'appfunc27',
              layout: {
                columnCount: 24,
                layout: 'TABLE_24COL',
              },
              layoutPos: {
                colMD: 24,
                layout: 'TABLE_24COL',
              },
              valid: true,
              caption: '颜色选择器',
              tooltip: '颜色选择器',
              id: 'menuitem94',
            },
            {
              accUserMode: 3,
              itemType: 'MENUITEM',
              appFuncId: 'appfunc28',
              layout: {
                columnCount: 24,
                layout: 'TABLE_24COL',
              },
              layoutPos: {
                colMD: 24,
                layout: 'TABLE_24COL',
              },
              valid: true,
              caption: '数值范围编辑框',
              tooltip: '数值范围编辑框',
              id: 'menuitem95',
            },
            {
              accUserMode: 3,
              itemType: 'MENUITEM',
              appFuncId: 'appfunc29',
              layout: {
                columnCount: 24,
                layout: 'TABLE_24COL',
              },
              layoutPos: {
                colMD: 24,
                layout: 'TABLE_24COL',
              },
              valid: true,
              caption: '数组数据编辑',
              tooltip: '数组数据编辑',
              id: 'menuitem96',
            },
            {
              accUserMode: 3,
              itemType: 'MENUITEM',
              appFuncId: 'appfunc30',
              layout: {
                columnCount: 24,
                layout: 'TABLE_24COL',
              },
              layoutPos: {
                colMD: 24,
                layout: 'TABLE_24COL',
              },
              valid: true,
              caption: '文件上传',
              tooltip: '文件上传',
              id: 'menuitem97',
            },
            {
              accUserMode: 3,
              itemType: 'MENUITEM',
              appFuncId: 'appfunc31',
              layout: {
                columnCount: 24,
                layout: 'TABLE_24COL',
              },
              layoutPos: {
                colMD: 24,
                layout: 'TABLE_24COL',
              },
              valid: true,
              caption: '图片裁剪上传',
              tooltip: '图片裁剪上传',
              id: 'menuitem98',
            },
            {
              accUserMode: 3,
              itemType: 'MENUITEM',
              appFuncId: 'appfunc32',
              layout: {
                columnCount: 24,
                layout: 'TABLE_24COL',
              },
              layoutPos: {
                colMD: 24,
                layout: 'TABLE_24COL',
              },
              valid: true,
              caption: '图片预览',
              tooltip: '图片预览',
              id: 'menuitem99',
            },
            {
              accUserMode: 3,
              itemType: 'MENUITEM',
              appFuncId: 'appfunc33',
              layout: {
                columnCount: 24,
                layout: 'TABLE_24COL',
              },
              layoutPos: {
                colMD: 24,
                layout: 'TABLE_24COL',
              },
              valid: true,
              caption: '图片上传',
              tooltip: '图片上传',
              id: 'menuitem100',
            },
            {
              accUserMode: 3,
              itemType: 'MENUITEM',
              appFuncId: 'appfunc34',
              layout: {
                columnCount: 24,
                layout: 'TABLE_24COL',
              },
              layoutPos: {
                colMD: 24,
                layout: 'TABLE_24COL',
              },
              valid: true,
              caption: 'HTML编辑框',
              tooltip: 'HTML编辑框',
              id: 'menuitem101',
            },
            {
              accUserMode: 3,
              itemType: 'MENUITEM',
              appFuncId: 'appfunc35',
              layout: {
                columnCount: 24,
                layout: 'TABLE_24COL',
              },
              layoutPos: {
                colMD: 24,
                layout: 'TABLE_24COL',
              },
              valid: true,
              caption: 'Markdown编辑框',
              tooltip: 'Markdown编辑框',
              id: 'menuitem102',
            },
            {
              accUserMode: 3,
              itemType: 'MENUITEM',
              appFuncId: 'appfunc36',
              layout: {
                columnCount: 24,
                layout: 'TABLE_24COL',
              },
              layoutPos: {
                colMD: 24,
                layout: 'TABLE_24COL',
              },
              valid: true,
              caption: '代码编辑',
              tooltip: '代码编辑',
              id: 'menuitem103',
            },
            {
              accUserMode: 3,
              itemType: 'MENUITEM',
              appFuncId: 'appfunc77',
              layout: {
                columnCount: 24,
                layout: 'TABLE_24COL',
              },
              layoutPos: {
                colMD: 24,
                layout: 'TABLE_24COL',
              },
              valid: true,
              caption: '运行时组件',
              tooltip: '运行时组件',
              id: 'menuitem114',
            },
            {
              accUserMode: 2,
              itemType: 'MENUITEM',
              appFuncId: 'appfunc78',
              layout: {
                columnCount: 24,
                layout: 'TABLE_24COL',
              },
              layoutPos: {
                colMD: 24,
                layout: 'TABLE_24COL',
              },
              valid: true,
              caption: '地图选择器',
              tooltip: '地图选择器',
              id: 'menuitem35',
            },
          ],
          layout: {
            columnCount: 24,
            layout: 'TABLE_24COL',
          },
          layoutPos: {
            colMD: 24,
            layout: 'TABLE_24COL',
          },
          sysImage: {
            cssClass: 'fa fa-th-large',
            glyph: 'xf009@FontAwesome',
          },
          valid: true,
          caption: '编辑器',
          tooltip: '编辑器',
          id: 'menuitem29',
        },
        {
          itemType: 'MENUITEM',
          appMenuItems: [
            {
              accUserMode: 3,
              itemType: 'MENUITEM',
              appFuncId: 'usrappfunc0516387433',
              layout: {
                columnCount: 24,
                layout: 'TABLE_24COL',
              },
              layoutPos: {
                colMD: 24,
                layout: 'TABLE_24COL',
              },
              valid: true,
              caption: '打开方式',
              tooltip: '打开方式',
              id: 'menuitem81',
            },
            {
              accUserMode: 2,
              itemType: 'MENUITEM',
              appFuncId: 'usrappfunc0513353562',
              layout: {
                columnCount: 24,
                layout: 'TABLE_24COL',
              },
              layoutPos: {
                colMD: 24,
                layout: 'TABLE_24COL',
              },
              valid: true,
              caption: '编辑视图',
              tooltip: '编辑视图',
              id: 'menuitem34',
            },
            {
              accUserMode: 3,
              itemType: 'MENUITEM',
              appFuncId: 'usrappfunc0513267307',
              layout: {
                columnCount: 24,
                layout: 'TABLE_24COL',
              },
              layoutPos: {
                colMD: 24,
                layout: 'TABLE_24COL',
              },
              valid: true,
              caption: '表格视图',
              tooltip: '表格视图',
              id: 'menuitem39',
            },
            {
              accUserMode: 3,
              itemType: 'MENUITEM',
              appFuncId: 'usrappfunc0513529208',
              layout: {
                columnCount: 24,
                layout: 'TABLE_24COL',
              },
              layoutPos: {
                colMD: 24,
                layout: 'TABLE_24COL',
              },
              valid: true,
              caption: '表格导航视图',
              tooltip: '表格导航视图',
              id: 'menuitem48',
            },
            {
              accUserMode: 2,
              itemType: 'MENUITEM',
              appFuncId: 'appfunc42',
              layout: {
                columnCount: 24,
                layout: 'TABLE_24COL',
              },
              layoutPos: {
                colMD: 24,
                layout: 'TABLE_24COL',
              },
              valid: true,
              caption: '树表格视图',
              tooltip: '树表格视图',
              id: 'menuitem111',
            },
            {
              accUserMode: 3,
              itemType: 'MENUITEM',
              appFuncId: 'usrappfunc0513883462',
              layout: {
                columnCount: 24,
                layout: 'TABLE_24COL',
              },
              layoutPos: {
                colMD: 24,
                layout: 'TABLE_24COL',
              },
              valid: true,
              caption: '列表视图',
              tooltip: '列表视图',
              id: 'menuitem40',
            },
            {
              accUserMode: 3,
              itemType: 'MENUITEM',
              appFuncId: 'usrappfunc0513000196',
              layout: {
                columnCount: 24,
                layout: 'TABLE_24COL',
              },
              layoutPos: {
                colMD: 24,
                layout: 'TABLE_24COL',
              },
              valid: true,
              caption: '列表导航',
              tooltip: '列表导航',
              id: 'menuitem47',
            },
            {
              accUserMode: 3,
              itemType: 'MENUITEM',
              appFuncId: 'usrappfunc0513647532',
              layout: {
                columnCount: 24,
                layout: 'TABLE_24COL',
              },
              layoutPos: {
                colMD: 24,
                layout: 'TABLE_24COL',
              },
              valid: true,
              caption: '看板视图',
              tooltip: '看板视图',
              id: 'menuitem41',
            },
            {
              accUserMode: 3,
              itemType: 'MENUITEM',
              appFuncId: 'usrappfunc0513329297',
              layout: {
                columnCount: 24,
                layout: 'TABLE_24COL',
              },
              layoutPos: {
                colMD: 24,
                layout: 'TABLE_24COL',
              },
              valid: true,
              caption: '多表单编辑视图',
              tooltip: '多表单编辑视图',
              id: 'menuitem42',
            },
            {
              accUserMode: 3,
              itemType: 'MENUITEM',
              appFuncId: 'usrappfunc0513634013',
              layout: {
                columnCount: 24,
                layout: 'TABLE_24COL',
              },
              layoutPos: {
                colMD: 24,
                layout: 'TABLE_24COL',
              },
              valid: true,
              caption: '日历视图',
              tooltip: '日历视图',
              id: 'menuitem43',
            },
            {
              accUserMode: 3,
              itemType: 'MENUITEM',
              appFuncId: 'usrappfunc0513180643',
              layout: {
                columnCount: 24,
                layout: 'TABLE_24COL',
              },
              layoutPos: {
                colMD: 24,
                layout: 'TABLE_24COL',
              },
              valid: true,
              caption: '日历导航视图',
              tooltip: '日历导航视图',
              id: 'menuitem49',
            },
            {
              accUserMode: 3,
              itemType: 'MENUITEM',
              appFuncId: 'usrappfunc0513647141',
              layout: {
                columnCount: 24,
                layout: 'TABLE_24COL',
              },
              layoutPos: {
                colMD: 24,
                layout: 'TABLE_24COL',
              },
              valid: true,
              caption: '地图视图',
              tooltip: '地图视图',
              id: 'menuitem44',
            },
            {
              accUserMode: 3,
              itemType: 'MENUITEM',
              appFuncId: 'usrappfunc0513173278',
              layout: {
                columnCount: 24,
                layout: 'TABLE_24COL',
              },
              layoutPos: {
                colMD: 24,
                layout: 'TABLE_24COL',
              },
              valid: true,
              caption: '地图导航视图',
              tooltip: '地图导航视图',
              id: 'menuitem50',
            },
            {
              accUserMode: 3,
              itemType: 'MENUITEM',
              appFuncId: 'usrappfunc0513306285',
              layout: {
                columnCount: 24,
                layout: 'TABLE_24COL',
              },
              layoutPos: {
                colMD: 24,
                layout: 'TABLE_24COL',
              },
              valid: true,
              caption: '分页导航视图',
              tooltip: '分页导航视图',
              id: 'menuitem45',
            },
            {
              accUserMode: 3,
              itemType: 'MENUITEM',
              appFuncId: 'appfunc45',
              layout: {
                columnCount: 24,
                layout: 'TABLE_24COL',
              },
              layoutPos: {
                colMD: 24,
                layout: 'TABLE_24COL',
              },
              valid: true,
              caption: '分页搜索视图',
              tooltip: '分页搜索视图',
              id: 'menuitem110',
            },
            {
              accUserMode: 3,
              itemType: 'MENUITEM',
              appFuncId: 'usrappfunc0513502451',
              layout: {
                columnCount: 24,
                layout: 'TABLE_24COL',
              },
              layoutPos: {
                colMD: 24,
                layout: 'TABLE_24COL',
              },
              valid: true,
              caption: '树导航视图',
              tooltip: '树导航视图',
              id: 'menuitem46',
            },
            {
              accUserMode: 3,
              itemType: 'MENUITEM',
              appFuncId: 'usrappfunc0513574103',
              layout: {
                columnCount: 24,
                layout: 'TABLE_24COL',
              },
              layoutPos: {
                colMD: 24,
                layout: 'TABLE_24COL',
              },
              valid: true,
              caption: '图表视图',
              tooltip: '图表视图',
              id: 'menuitem53',
            },
            {
              accUserMode: 3,
              itemType: 'MENUITEM',
              appFuncId: 'appfunc50',
              layout: {
                columnCount: 24,
                layout: 'TABLE_24COL',
              },
              layoutPos: {
                colMD: 24,
                layout: 'TABLE_24COL',
              },
              valid: true,
              caption: '图表导航视图',
              tooltip: '图表导航视图',
              id: 'menuitem106',
            },
            {
              accUserMode: 3,
              itemType: 'MENUITEM',
              appFuncId: 'appfunc44',
              layout: {
                columnCount: 24,
                layout: 'TABLE_24COL',
              },
              layoutPos: {
                colMD: 24,
                layout: 'TABLE_24COL',
              },
              valid: true,
              caption: '数据看板视图',
              tooltip: '数据看板视图',
              id: 'menuitem113',
            },
            {
              accUserMode: 3,
              itemType: 'MENUITEM',
              appFuncId: 'appfunc39',
              layout: {
                columnCount: 24,
                layout: 'TABLE_24COL',
              },
              layoutPos: {
                colMD: 24,
                layout: 'TABLE_24COL',
              },
              valid: true,
              caption: '卡片导航视图',
              tooltip: '卡片导航视图',
              id: 'menuitem107',
            },
            {
              accUserMode: 3,
              itemType: 'MENUITEM',
              appFuncId: 'usrappfunc0513392449',
              layout: {
                columnCount: 24,
                layout: 'TABLE_24COL',
              },
              layoutPos: {
                colMD: 24,
                layout: 'TABLE_24COL',
              },
              valid: true,
              caption: '向导视图',
              tooltip: '向导视图',
              id: 'menuitem38',
            },
            {
              accUserMode: 3,
              itemType: 'MENUITEM',
              appFuncId: 'appfunc40',
              layout: {
                columnCount: 24,
                layout: 'TABLE_24COL',
              },
              layoutPos: {
                colMD: 24,
                layout: 'TABLE_24COL',
              },
              valid: true,
              caption: '甘特视图',
              tooltip: '甘特视图',
              id: 'menuitem108',
            },
            {
              accUserMode: 3,
              itemType: 'MENUITEM',
              appFuncId: 'appfunc43',
              layout: {
                columnCount: 24,
                layout: 'TABLE_24COL',
              },
              layoutPos: {
                colMD: 24,
                layout: 'TABLE_24COL',
              },
              valid: true,
              caption: '甘特导航视图',
              tooltip: '甘特导航视图',
              id: 'menuitem112',
            },
            {
              accUserMode: 3,
              itemType: 'MENUITEM',
              appFuncId: 'appfunc19',
              layout: {
                columnCount: 24,
                layout: 'TABLE_24COL',
              },
              layoutPos: {
                colMD: 24,
                layout: 'TABLE_24COL',
              },
              valid: true,
              caption: '选择视图',
              tooltip: '选择视图',
              id: 'menuitem51',
            },
            {
              accUserMode: 3,
              itemType: 'MENUITEM',
              appFuncId: 'usrappfunc0513019494',
              layout: {
                columnCount: 24,
                layout: 'TABLE_24COL',
              },
              layoutPos: {
                colMD: 24,
                layout: 'TABLE_24COL',
              },
              valid: true,
              caption: 'HTML视图',
              tooltip: 'HTML视图',
              id: 'menuitem54',
            },
            {
              accUserMode: 3,
              itemType: 'MENUITEM',
              appFuncId: 'appfunc73',
              layout: {
                columnCount: 24,
                layout: 'TABLE_24COL',
              },
              layoutPos: {
                colMD: 24,
                layout: 'TABLE_24COL',
              },
              valid: true,
              caption: '报表视图',
              tooltip: '报表视图',
              id: 'menuitem130',
            },
          ],
          layout: {
            columnCount: 24,
            layout: 'TABLE_24COL',
          },
          layoutPos: {
            colMD: 24,
            layout: 'TABLE_24COL',
          },
          sysImage: {
            cssClass: 'fa fa-th-large',
            glyph: 'xf009@FontAwesome',
          },
          valid: true,
          caption: '页面',
          tooltip: '页面',
          id: 'menuitem33',
        },
        {
          itemType: 'MENUITEM',
          appMenuItems: [
            {
              accUserMode: 3,
              itemType: 'MENUITEM',
              appFuncId: 'appfunc16',
              layout: {
                columnCount: 24,
                layout: 'TABLE_24COL',
              },
              layoutPos: {
                colMD: 24,
                layout: 'TABLE_24COL',
              },
              valid: true,
              caption: 'UI插件',
              tooltip: 'UI插件',
              id: 'menuitem74',
            },
            {
              accUserMode: 3,
              itemType: 'MENUITEM',
              appFuncId: 'appfunc17',
              layout: {
                columnCount: 24,
                layout: 'TABLE_24COL',
              },
              layoutPos: {
                colMD: 24,
                layout: 'TABLE_24COL',
              },
              valid: true,
              caption: '逻辑插件',
              tooltip: '逻辑插件',
              id: 'menuitem75',
            },
            {
              accUserMode: 3,
              itemType: 'MENUITEM',
              appFuncId: 'appfunc3',
              layout: {
                columnCount: 24,
                layout: 'TABLE_24COL',
              },
              layoutPos: {
                colMD: 24,
                layout: 'TABLE_24COL',
              },
              valid: true,
              caption: '主题插件',
              tooltip: '主题插件',
              id: 'menuitem56',
            },
            {
              accUserMode: 3,
              itemType: 'MENUITEM',
              appFuncId: 'appfunc4',
              layout: {
                columnCount: 24,
                layout: 'TABLE_24COL',
              },
              layoutPos: {
                colMD: 24,
                layout: 'TABLE_24COL',
              },
              valid: true,
              caption: '全局插件',
              tooltip: '全局插件',
              id: 'menuitem57',
            },
          ],
          layout: {
            columnCount: 24,
            layout: 'TABLE_24COL',
          },
          layoutPos: {
            colMD: 24,
            layout: 'TABLE_24COL',
          },
          sysImage: {
            cssClass: 'fa fa-th-large',
            glyph: 'xf009@FontAwesome',
          },
          valid: true,
          caption: '插件',
          tooltip: '插件',
          id: 'menuitem55',
        },
        {
          itemType: 'MENUITEM',
          appMenuItems: [
            {
              accUserMode: 3,
              itemType: 'MENUITEM',
              appFuncId: 'usrappfunc0514674954',
              layout: {
                columnCount: 24,
                layout: 'TABLE_24COL',
              },
              layoutPos: {
                colMD: 24,
                layout: 'TABLE_24COL',
              },
              valid: true,
              caption: '界面行为',
              tooltip: '界面行为',
              id: 'menuitem69',
            },
            {
              accUserMode: 3,
              itemType: 'MENUITEM',
              appFuncId: 'usrappfunc0514600707',
              layout: {
                columnCount: 24,
                layout: 'TABLE_24COL',
              },
              layoutPos: {
                colMD: 24,
                layout: 'TABLE_24COL',
              },
              valid: true,
              caption: '界面逻辑',
              tooltip: '界面逻辑',
              id: 'menuitem70',
            },
            {
              accUserMode: 3,
              itemType: 'MENUITEM',
              appFuncId: 'usrappfunc0514105483',
              layout: {
                columnCount: 24,
                layout: 'TABLE_24COL',
              },
              layoutPos: {
                colMD: 24,
                layout: 'TABLE_24COL',
              },
              valid: true,
              caption: '视图消息',
              tooltip: '视图消息',
              id: 'menuitem71',
            },
            {
              accUserMode: 3,
              counterId: 'menu',
              itemType: 'MENUITEM',
              appFuncId: 'usrappfunc0514596330',
              layout: {
                columnCount: 24,
                layout: 'TABLE_24COL',
              },
              layoutPos: {
                colMD: 24,
                layout: 'TABLE_24COL',
              },
              valid: true,
              caption: '计数器',
              tooltip: '计数器',
              id: 'menuitem72',
            },
          ],
          layout: {
            columnCount: 24,
            layout: 'TABLE_24COL',
          },
          layoutPos: {
            colMD: 24,
            layout: 'TABLE_24COL',
          },
          sysImage: {
            cssClass: 'fa fa-th-large',
            glyph: 'xf009@FontAwesome',
          },
          valid: true,
          caption: '界面逻辑',
          tooltip: '界面逻辑',
          id: 'menuitem32',
        },
        {
          itemType: 'MENUITEM',
          appMenuItems: [
            {
              accUserMode: 2,
              itemType: 'MENUITEM',
              appFuncId: 'appfunc84',
              layout: {
                columnCount: 24,
                layout: 'TABLE_24COL',
              },
              layoutPos: {
                colMD: 24,
                layout: 'TABLE_24COL',
              },
              valid: true,
              caption: '动态维护',
              tooltip: '动态维护',
              id: 'menuitem140',
            },
            {
              itemType: 'MENUITEM',
              layout: {
                columnCount: 24,
                layout: 'TABLE_24COL',
              },
              layoutPos: {
                colMD: 24,
                layout: 'TABLE_24COL',
              },
              valid: true,
              caption: '动态表格',
              tooltip: '动态表格',
              id: 'menuitem37',
            },
            {
              itemType: 'MENUITEM',
              layout: {
                columnCount: 24,
                layout: 'TABLE_24COL',
              },
              layoutPos: {
                colMD: 24,
                layout: 'TABLE_24COL',
              },
              valid: true,
              caption: '动态表单',
              tooltip: '动态表单',
              id: 'menuitem136',
            },
            {
              accUserMode: 2,
              itemType: 'MENUITEM',
              appFuncId: 'appfunc82',
              layout: {
                columnCount: 24,
                layout: 'TABLE_24COL',
              },
              layoutPos: {
                colMD: 24,
                layout: 'TABLE_24COL',
              },
              valid: true,
              caption: '评论',
              tooltip: '评论',
              id: 'menuitem132',
            },
            {
              accUserMode: 2,
              itemType: 'MENUITEM',
              appFuncId: 'appfunc81',
              layout: {
                columnCount: 24,
                layout: 'TABLE_24COL',
              },
              layoutPos: {
                colMD: 24,
                layout: 'TABLE_24COL',
              },
              valid: true,
              caption: '活动',
              tooltip: '活动',
              id: 'menuitem133',
            },
          ],
          layout: {
            columnCount: 24,
            layout: 'TABLE_24COL',
          },
          layoutPos: {
            colMD: 24,
            layout: 'TABLE_24COL',
          },
          sysImage: {
            cssClass: 'fa fa-th-large',
            glyph: 'xf009@FontAwesome',
          },
          valid: true,
          caption: '高级组件',
          tooltip: '高级组件',
          id: 'menuitem36',
        },
        {
          itemType: 'MENUITEM',
          appMenuItems: [
            {
              itemType: 'MENUITEM',
              layout: {
                columnCount: 24,
                layout: 'TABLE_24COL',
              },
              layoutPos: {
                colMD: 24,
                layout: 'TABLE_24COL',
              },
              valid: true,
              caption: '通知',
              tooltip: '通知',
              id: 'menuitem138',
            },
            {
              accUserMode: 2,
              itemType: 'MENUITEM',
              appFuncId: 'appfunc83',
              layout: {
                columnCount: 24,
                layout: 'TABLE_24COL',
              },
              layoutPos: {
                colMD: 24,
                layout: 'TABLE_24COL',
              },
              valid: true,
              caption: '后台作业',
              tooltip: '后台作业',
              id: 'menuitem139',
            },
          ],
          layout: {
            columnCount: 24,
            layout: 'TABLE_24COL',
          },
          layoutPos: {
            colMD: 24,
            layout: 'TABLE_24COL',
          },
          sysImage: {
            cssClass: 'fa fa-th-large',
            glyph: 'xf009@FontAwesome',
          },
          valid: true,
          caption: '其他',
          tooltip: '其他',
          id: 'menuitem137',
        },
        {
          accUserMode: 2,
          itemType: 'MENUITEM',
          appFuncId: 'appfunc85',
          layout: {
            columnCount: 24,
            layout: 'TABLE_24COL',
          },
          layoutPos: {
            colMD: 24,
            layout: 'TABLE_24COL',
          },
          sysImage: {
            cssClass: 'fa fa-th-large',
            glyph: 'xf009@FontAwesome',
          },
          valid: true,
          caption: '应用管理',
          tooltip: '应用管理',
          id: 'menuitem141',
        },
        {
          appMenuItemState: 1,
          itemType: 'MENUITEM',
          appMenuItems: [
            {
              itemType: 'MENUITEM',
              layout: {
                columnCount: 24,
                layout: 'TABLE_24COL',
              },
              layoutPos: {
                colMD: 24,
                layout: 'TABLE_24COL',
              },
              valid: true,
              caption: '主应用占位菜单项',
              tooltip: '主应用占位菜单项',
              id: 'menuitem142',
            },
            {
              accUserMode: 2,
              itemType: 'MENUITEM',
              appFuncId: 'tab_ctrl_federation1',
              layout: {
                columnCount: 24,
                layout: 'TABLE_24COL',
              },
              layoutPos: {
                colMD: 24,
                layout: 'TABLE_24COL',
              },
              valid: true,
              caption: '数据关系部件融合',
              tooltip: '数据关系部件融合',
              id: 'menuitem143',
            },
            {
              accUserMode: 2,
              itemType: 'MENUITEM',
              appFuncId: 'tree_ctrl_federation',
              layout: {
                columnCount: 24,
                layout: 'TABLE_24COL',
              },
              layoutPos: {
                colMD: 24,
                layout: 'TABLE_24COL',
              },
              valid: true,
              caption: '树部件融合',
              tooltip: '树部件融合',
              id: 'menuitem144',
            },
            {
              accUserMode: 2,
              itemType: 'MENUITEM',
              appFuncId: 'actions_federation',
              layout: {
                columnCount: 24,
                layout: 'TABLE_24COL',
              },
              layoutPos: {
                colMD: 24,
                layout: 'TABLE_24COL',
              },
              valid: true,
              caption: '界面行为组融合',
              tooltip: '界面行为组融合',
              id: 'menuitem145',
            },
          ],
          layout: {
            columnCount: 24,
            layout: 'TABLE_24COL',
          },
          layoutPos: {
            colMD: 24,
            layout: 'TABLE_24COL',
          },
          sysImage: {
            cssClass: 'fa fa-puzzle-piece',
            glyph: 'xf12e@FontAwesome',
          },
          valid: true,
          caption: '多应用融合',
          tooltip: '多应用融合',
          id: 'app_federation',
        },
        {
          accUserMode: 2,
          itemType: 'MENUITEM',
          appFuncId: 'welcome',
          layout: {
            columnCount: 24,
            layout: 'TABLE_24COL',
          },
          layoutPos: {
            colMD: 24,
            layout: 'TABLE_24COL',
          },
          sysImage: {
            rawContent:
              '<?xml version="1.0" standalone="no"?><!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 1.1//EN" "http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd"><svg t="1724299754262" class="icon" viewBox="0 0 1024 1024" version="1.1" xmlns="http://www.w3.org/2000/svg" p-id="84488" xmlns:xlink="http://www.w3.org/1999/xlink" width="32" height="32"><path d="M540.134 484.819H344.195V316.872h-55.982v391.876h55.982V540.801h195.939v167.947h55.982V316.872h-55.982z" p-id="84489" fill="#ffffff"></path><path d="M680.09 428.837h55.982v279.912H680.09V428.837z" p-id="84490" fill="#ffffff"></path><path d="M680.09 316.872h55.982v83.973H680.09v-83.973z" p-id="84491" fill="#ffffff"></path><path d="M511.714 976.171c-255.88 0-464-208.12-464-464 0-255.879 208.12-464 464-464s464 208.121 464 464c0 255.88-208.12 464-464 464z m0.286-976C229.722 0.172 0.172 229.723 0.172 512S229.722 1023.829 512 1023.829c282.278 0 511.828-229.551 511.828-511.83C1023.828 229.723 794.163 0.173 512 0.173z" p-id="84492" fill="#ffffff"></path></svg>',
          },
          openDefault: true,
          valid: true,
          caption: 'Welcome',
          tooltip: 'Welcome',
          id: 'menuitem2',
        },
        {
          accUserMode: 2,
          itemType: 'MENUITEM',
          appFuncId: 'about',
          layout: {
            columnCount: 24,
            layout: 'TABLE_24COL',
          },
          layoutPos: {
            colMD: 24,
            layout: 'TABLE_24COL',
          },
          sysImage: {
            cssClass: 'fa fa-info-circle',
            glyph: 'xf05a@FontAwesome',
          },
          valid: true,
          caption: '关于',
          tooltip: '关于',
          id: 'menuitem1',
        },
      ],
      autoLoad: true,
      showBusyIndicator: true,
      codeName: 'main',
      controlType: 'APPMENU',
      logicName: '应用首页视图菜单',
      controlParam: {},
      modelId: 'e9961522de7c3fb96c9e53f76b3eba6e',
      modelType: 'PSAPPMENU',
      name: 'appmenu',
      id: 'main',
    },
    {
      caption: 'quickstart',
      codeName: 'captionbar',
      controlType: 'CAPTIONBAR',
      controlParam: {},
      id: 'captionbar',
    },
  ],
  viewLayoutPanel: {
    layoutBodyOnly: true,
    useDefaultLayout: true,
    layoutPanel: true,
    codeName: 'layoutpanel',
    controlStyle: 'APPINDEXVIEW',
    controlType: 'VIEWLAYOUTPANEL',
    controlParam: {},
    id: 'layoutpanel',
  },
  title: 'quickstart',
  viewStyle: 'DEFAULT',
  viewType: 'APPINDEXVIEW',
  enableDP: true,
  showCaptionBar: true,
  modelId: 'faa14160d2153b703f9a25d5fe08eebe',
  modelType: 'PSAPPINDEXVIEW',
  name: 'admin_index',
  id: 'web.admin_index',
};
