export default {
  gridRowActiveMode: 2,
  enableRowEdit: true,
  rowEditDefault: true,
  xdataControlName: 'grid',
  loadDefault: true,
  deviewCodeName: 'grid_edit',
  deviewId: '00272c905d4df3e991e245c6f02f1f68',
  accUserMode: 3,
  capLanguageRes: {
    lanResTag: 'DE.LNAME.MASTER',
  },
  caption: '表格_行编辑',
  codeName: 'master_grid_edit',
  appDataEntityId: 'web.master',
  appViewEngines: [
    {
      engineCat: 'VIEW',
      engineType: 'GridView',
      id: 'engine',
    },
  ],
  appViewLogics: [
    {
      logicTrigger: 'CUSTOM',
      logicType: 'APPUILOGIC',
      builtinAppUILogic: {
        actionAfterWizard: 'DEFAULT',
        newDataAppView: {
          openMode: 'POPUPMODAL',
          refAppViewId: 'web.master_edit_view',
        },
        appUILogicRefViews: [
          {
            openMode: 'POPUPMODAL',
            refAppViewId: 'web.master_edit_view',
          },
        ],
        builtinLogic: true,
        logicType: 'PREDEFINED',
        viewLogicType: 'APP_NEWDATA',
        id: '新建数据',
      },
      builtinLogic: true,
      id: 'newdata',
    },
    {
      logicTrigger: 'CUSTOM',
      logicType: 'APPUILOGIC',
      builtinAppUILogic: {
        openDataAppView: {
          openMode: 'POPUPMODAL',
          refAppViewId: 'web.master_edit_view',
        },
        editMode: true,
        appUILogicRefViews: [
          {
            openMode: 'POPUPMODAL',
            refAppViewId: 'web.master_edit_view',
          },
        ],
        builtinLogic: true,
        logicType: 'PREDEFINED',
        viewLogicType: 'APP_OPENDATA',
        id: '打开数据',
      },
      builtinLogic: true,
      id: 'opendata',
    },
  ],
  appViewMsgGroupId: 'grid_edit',
  appViewRefs: [
    {
      realOpenMode: 'POPUPMODAL',
      realTitle: '主数据编辑视图',
      refAppViewId: 'web.master_edit_view',
      name: 'NEWDATA',
      id: 'newdata',
    },
    {
      realOpenMode: 'POPUPMODAL',
      realTitle: '主数据编辑视图',
      refAppViewId: 'web.master_edit_view',
      name: 'EDITDATA',
      id: 'editdata',
    },
  ],
  controls: [
    {
      aggMode: 'NONE',
      columnEnableFilter: 2,
      columnEnableLink: 2,
      groupMode: 'NONE',
      groupStyle: 'DEFAULT',
      degridColumns: [
        {
          clconvertMode: 'FRONT',
          dataItemName: 'dropdownlist',
          excelCaption: '下拉列表框',
          appCodeListId: 'web.mock__cl_sample',
          appDEFieldId: 'dropdownlist',
          valueType: 'SIMPLE',
          enableRowEdit: true,
          aggMode: 'NONE',
          align: 'CENTER',
          caption: '下拉列表框',
          codeName: 'dropdownlist',
          columnType: 'DEFGRIDCOLUMN',
          noPrivDisplayMode: 1,
          width: 150,
          widthUnit: 'PX',
          id: 'dropdownlist',
        },
        {
          clconvertMode: 'FRONT',
          dataItemName: 'mdropdownlist',
          excelCaption: '下拉列表框（多选）',
          appCodeListId: 'web.mock__cl_sample',
          appDEFieldId: 'mdropdownlist',
          valueType: 'SIMPLE',
          enableRowEdit: true,
          aggMode: 'NONE',
          align: 'CENTER',
          caption: '下拉列表框（多选）',
          codeName: 'mdropdownlist',
          columnType: 'DEFGRIDCOLUMN',
          noPrivDisplayMode: 1,
          width: 200,
          widthUnit: 'PX',
          id: 'mdropdownlist',
        },
        {
          clconvertMode: 'FRONT',
          dataItemName: 'switchval',
          excelCaption: '开关部件',
          appCodeListId: 'web.yesno',
          appDEFieldId: 'switchval',
          valueType: 'SIMPLE',
          enableRowEdit: true,
          aggMode: 'NONE',
          align: 'CENTER',
          caption: '开关部件',
          codeName: 'switchval',
          columnType: 'DEFGRIDCOLUMN',
          noPrivDisplayMode: 1,
          width: 100,
          widthUnit: 'PX',
          id: 'switchval',
        },
        {
          clconvertMode: 'NONE',
          dataItemName: 'numberval',
          excelCaption: '数值框',
          appDEFieldId: 'numberval',
          valueType: 'SIMPLE',
          enableRowEdit: true,
          aggMode: 'NONE',
          align: 'CENTER',
          caption: '数值框',
          codeName: 'numberval',
          columnType: 'DEFGRIDCOLUMN',
          noPrivDisplayMode: 1,
          width: 100,
          widthUnit: 'PX',
          id: 'numberval',
        },
        {
          clconvertMode: 'NONE',
          dataItemName: 'textbox',
          excelCaption: '文本框',
          appDEFieldId: 'textbox',
          valueType: 'SIMPLE',
          enableRowEdit: true,
          aggMode: 'NONE',
          align: 'CENTER',
          caption: '文本框',
          codeName: 'textbox',
          columnType: 'DEFGRIDCOLUMN',
          noPrivDisplayMode: 1,
          width: 100,
          widthUnit: 'PX',
          id: 'textbox',
        },
        {
          clconvertMode: 'NONE',
          dataItemName: 'datepicker',
          excelCaption: '时间选择器',
          appDEFieldId: 'datepicker',
          valueFormat: 'YYYY-MM-DD HH:mm:ss',
          valueType: 'SIMPLE',
          enableRowEdit: true,
          aggMode: 'NONE',
          align: 'CENTER',
          caption: '时间选择器',
          codeName: 'datepicker',
          columnType: 'DEFGRIDCOLUMN',
          noPrivDisplayMode: 1,
          width: 150,
          widthUnit: 'PX',
          id: 'datepicker',
        },
        {
          clconvertMode: 'FRONT',
          dataItemName: 'checkbox',
          excelCaption: '选项框',
          appCodeListId: 'web.yesno',
          appDEFieldId: 'checkbox',
          valueType: 'SIMPLE',
          enableRowEdit: true,
          aggMode: 'NONE',
          align: 'CENTER',
          caption: '选项框',
          codeName: 'checkbox',
          columnType: 'DEFGRIDCOLUMN',
          noPrivDisplayMode: 1,
          width: 100,
          widthUnit: 'PX',
          id: 'checkbox',
        },
        {
          clconvertMode: 'NONE',
          dataItemName: 'stepper',
          excelCaption: '步进器',
          appDEFieldId: 'stepper',
          valueType: 'SIMPLE',
          enableRowEdit: true,
          aggMode: 'NONE',
          align: 'CENTER',
          caption: '步进器',
          codeName: 'stepper',
          columnType: 'DEFGRIDCOLUMN',
          noPrivDisplayMode: 1,
          width: 150,
          widthUnit: 'PX',
          id: 'stepper',
        },
        {
          clconvertMode: 'NONE',
          dataItemName: 'rating',
          excelCaption: '评分器',
          appDEFieldId: 'rating',
          valueType: 'SIMPLE',
          enableRowEdit: true,
          aggMode: 'NONE',
          align: 'CENTER',
          caption: '评分器',
          codeName: 'rating',
          columnType: 'DEFGRIDCOLUMN',
          noPrivDisplayMode: 1,
          width: 150,
          widthUnit: 'PX',
          id: 'rating',
        },
        {
          clconvertMode: 'NONE',
          dataItemName: 'ac',
          excelCaption: '自动填充',
          appDEFieldId: 'ac',
          valueType: 'SIMPLE',
          enableRowEdit: true,
          aggMode: 'NONE',
          align: 'CENTER',
          caption: '自动填充',
          codeName: 'ac',
          columnType: 'DEFGRIDCOLUMN',
          noPrivDisplayMode: 1,
          width: 100,
          widthUnit: 'PX',
          id: 'ac',
        },
      ],
      degridDataItems: [
        {
          appDEFieldId: 'dropdownlist',
          valueType: 'SIMPLE',
          dataType: 25,
          id: 'dropdownlist',
        },
        {
          appDEFieldId: 'mdropdownlist',
          valueType: 'SIMPLE',
          dataType: 25,
          id: 'mdropdownlist',
        },
        {
          appDEFieldId: 'switchval',
          valueType: 'SIMPLE',
          dataType: 9,
          id: 'switchval',
        },
        {
          appDEFieldId: 'numberval',
          valueType: 'SIMPLE',
          dataType: 6,
          id: 'numberval',
        },
        {
          appDEFieldId: 'textbox',
          valueType: 'SIMPLE',
          dataType: 25,
          id: 'textbox',
        },
        {
          format: 'YYYY-MM-DD HH:mm:ss',
          appDEFieldId: 'datepicker',
          valueType: 'SIMPLE',
          dataType: 5,
          id: 'datepicker',
        },
        {
          appDEFieldId: 'checkbox',
          valueType: 'SIMPLE',
          dataType: 9,
          id: 'checkbox',
        },
        {
          appDEFieldId: 'stepper',
          valueType: 'SIMPLE',
          dataType: 9,
          id: 'stepper',
        },
        {
          appDEFieldId: 'rating',
          valueType: 'SIMPLE',
          dataType: 9,
          id: 'rating',
        },
        {
          appDEFieldId: 'ac',
          valueType: 'SIMPLE',
          dataType: 25,
          id: 'ac',
        },
        {
          appDEFieldId: 'id',
          valueType: 'SIMPLE',
          dataType: 25,
          id: 'srfkey',
        },
        {
          appDEFieldId: 'id',
          valueType: 'SIMPLE',
          dataType: 25,
          id: 'srfdataaccaction',
        },
        {
          appDEFieldId: 'region_id',
          valueType: 'SIMPLE',
          dataType: 25,
          id: 'region_id',
        },
        {
          appDEFieldId: 'name',
          valueType: 'SIMPLE',
          dataType: 25,
          id: 'srfmajortext',
        },
      ],
      degridEditItems: [
        {
          caption: '下拉列表框',
          codeName: 'dropdownlist',
          enableCond: 3,
          appDEFieldId: 'dropdownlist',
          editor: {
            singleSelect: true,
            appCodeListId: 'web.mock__cl_sample',
            editorType: 'DROPDOWNLIST',
            valueType: 'SIMPLE',
            editable: true,
            id: 'dropdownlist',
          },
          allowEmpty: true,
          needCodeListConfig: true,
          id: 'dropdownlist',
        },
        {
          caption: '下拉列表框（多选）',
          codeName: 'mdropdownlist',
          enableCond: 3,
          appDEFieldId: 'mdropdownlist',
          editor: {
            appCodeListId: 'web.mock__cl_sample',
            editorType: 'MDROPDOWNLIST',
            valueType: 'SIMPLE',
            editable: true,
            id: 'mdropdownlist',
          },
          allowEmpty: true,
          needCodeListConfig: true,
          id: 'mdropdownlist',
        },
        {
          caption: '开关部件',
          codeName: 'switchval',
          enableCond: 3,
          appDEFieldId: 'switchval',
          editor: {
            editorType: 'SWITCH',
            valueType: 'SIMPLE',
            editable: true,
            id: 'switchval',
          },
          allowEmpty: true,
          id: 'switchval',
        },
        {
          caption: '数值框',
          codeName: 'numberval',
          enableCond: 3,
          appDEFieldId: 'numberval',
          editor: {
            editorType: 'TEXTBOX',
            valueType: 'SIMPLE',
            editable: true,
            id: 'numberval',
          },
          allowEmpty: true,
          id: 'numberval',
        },
        {
          caption: '文本框',
          codeName: 'textbox',
          enableCond: 3,
          appDEFieldId: 'textbox',
          editor: {
            maxLength: 100,
            editorType: 'TEXTBOX',
            valueType: 'SIMPLE',
            editable: true,
            id: 'textbox',
          },
          allowEmpty: true,
          id: 'textbox',
        },
        {
          caption: '时间选择器',
          codeName: 'datepicker',
          enableCond: 3,
          appDEFieldId: 'datepicker',
          editor: {
            dateTimeFormat: 'YYYY-MM-DD HH:mm:ss',
            editorParams: {
              TIMEFMT: 'YYYY-MM-DD HH:mm:ss',
            },
            editorType: 'DATEPICKER',
            valueType: 'SIMPLE',
            editable: true,
            id: 'datepicker',
          },
          allowEmpty: true,
          id: 'datepicker',
        },
        {
          caption: '选项框',
          codeName: 'checkbox',
          enableCond: 3,
          appDEFieldId: 'checkbox',
          editor: {
            editorType: 'CHECKBOX',
            valueType: 'SIMPLE',
            editable: true,
            id: 'checkbox',
          },
          allowEmpty: true,
          id: 'checkbox',
        },
        {
          caption: '步进器',
          codeName: 'stepper',
          enableCond: 3,
          appDEFieldId: 'stepper',
          editor: {
            stepValue: 1,
            editorType: 'STEPPER',
            valueType: 'SIMPLE',
            editable: true,
            id: 'stepper',
          },
          allowEmpty: true,
          id: 'stepper',
        },
        {
          caption: '评分器',
          codeName: 'rating',
          enableCond: 3,
          appDEFieldId: 'rating',
          editor: {
            stepValue: 1,
            maxValue: 5,
            editorType: 'RATING',
            valueType: 'SIMPLE',
            editable: true,
            id: 'rating',
          },
          allowEmpty: true,
          id: 'rating',
        },
        {
          caption: '自动填充',
          codeName: 'ac',
          enableCond: 3,
          appDEFieldId: 'ac',
          editor: {
            appDEACModeId: 'default',
            appDEDataSetId: 'fetch_default',
            appDataEntityId: 'web.region',
            enableAC: true,
            showTrigger: true,
            maxLength: 100,
            handlerType: 'AC',
            editorParams: {
              FORCESELECTION: 'FALSE',
              TRIGGER: 'TRUE',
            },
            editorType: 'AC',
            valueType: 'SIMPLE',
            editable: true,
            id: 'ac',
          },
          allowEmpty: true,
          id: 'ac',
        },
        {
          caption: '标识',
          codeName: 'srfkey',
          enableCond: 3,
          appDEFieldId: 'id',
          editor: {
            editorType: 'HIDDEN',
            valueType: 'SIMPLE',
            editable: true,
            id: 'srfkey',
          },
          allowEmpty: true,
          id: 'srfkey',
        },
      ],
      pagingMode: 1,
      pagingSize: 10,
      sortMode: 'REMOTE',
      enableCustomized: true,
      enablePagingBar: true,
      enableRowEdit: true,
      enableRowNew: true,
      navViewPos: 'NONE',
      createControlAction: {
        appDEMethodId: 'create',
        appDataEntityId: 'web.master',
        id: 'create',
      },
      fetchControlAction: {
        appDEMethodId: 'fetch_default',
        appDataEntityId: 'web.master',
        id: 'fetch',
      },
      getDraftControlAction: {
        appDEMethodId: 'get_draft',
        appDataEntityId: 'web.master',
        id: 'loaddraft',
      },
      getControlAction: {
        appDEMethodId: 'get',
        appDataEntityId: 'web.master',
        id: 'load',
      },
      removeControlAction: {
        appDEMethodId: 'remove',
        appDataEntityId: 'web.master',
        id: 'remove',
      },
      updateControlAction: {
        appDEMethodId: 'update',
        appDataEntityId: 'web.master',
        id: 'update',
      },
      autoLoad: true,
      showBusyIndicator: true,
      codeName: 'main6',
      controlType: 'GRID',
      logicName: '表格_行编辑_表格',
      appDataEntityId: 'web.master',
      controlParam: {
        ctrlParams: {
          EDITSHOWMODE: 'all',
        },
        id: 'grid',
      },
      modelId: 'a99cc9f5b8dc11cce664329390703d36',
      modelType: 'PSDEGRID',
      name: 'grid',
      id: 'web.master.main6',
    },
    {
      xdataControlName: 'grid',
      codeName: 'grid_edit_toolbar',
      controlType: 'TOOLBAR',
      logicName: '表格_行编辑_工具栏',
      appDataEntityId: 'web.master',
      controlParam: {
        id: 'toolbar',
      },
      modelId: 'bb465d8c08dea61a925bc05d38776806',
      modelType: 'PSDETOOLBAR',
      name: 'toolbar',
      id: 'grid_edit_toolbar',
    },
    {
      groupMode: 'SINGLE',
      controlType: 'SEARCHBAR',
      appDataEntityId: 'web.master',
      controlParam: {
        id: 'searchbar',
      },
      id: 'searchbar',
    },
    {
      capLanguageRes: {
        lanResTag: 'DE.LNAME.MASTER',
      },
      caption: '表格_行编辑',
      codeName: 'grid_edit_captionbar',
      controlType: 'CAPTIONBAR',
      appDataEntityId: 'web.master',
      controlParam: {},
      name: 'captionbar',
      id: 'grid_edit_captionbar',
    },
  ],
  viewLayoutPanel: {
    layoutBodyOnly: true,
    useDefaultLayout: true,
    layoutPanel: true,
    codeName: 'layoutpanel',
    controlStyle: 'APPDEGRIDVIEW',
    controlType: 'VIEWLAYOUTPANEL',
    appDataEntityId: 'web.master',
    controlParam: {},
    id: 'layoutpanel',
  },
  title: '表格_行编辑',
  viewStyle: 'DEFAULT',
  viewType: 'DEGRIDVIEW',
  enableDP: true,
  showCaptionBar: false,
  modelId: '3c4189eaab1d0d32257aafa364fb597d',
  modelType: 'PSAPPDEVIEW',
  name: 'MASTERgrid_edit',
  id: 'web.master_grid_edit',
};
