export default {
  sideBarLayout: 'LEFT',
  showDataInfoBar: true,
  loadDefault: true,
  deviewCodeName: 'map_exp_view',
  deviewId: 'c38a0878952d4c394ba62da9f1b8009e',
  accUserMode: 3,
  capLanguageRes: {
    lanResTag: 'DE.LNAME.MASTER',
  },
  caption: '地图导航视图',
  codeName: 'master_map_exp_view',
  appDataEntityId: 'web.master',
  appViewLogics: [
    {
      logicTrigger: 'CUSTOM',
      logicType: 'APPUILOGIC',
      builtinAppUILogic: {
        actionAfterWizard: 'DEFAULT',
        builtinLogic: true,
        logicType: 'PREDEFINED',
        viewLogicType: 'APP_NEWDATA',
        id: '新建数据',
      },
      builtinLogic: true,
      id: 'newdata',
    },
    {
      logicTrigger: 'CUSTOM',
      logicType: 'APPUILOGIC',
      builtinAppUILogic: {
        editMode: true,
        builtinLogic: true,
        logicType: 'PREDEFINED',
        viewLogicType: 'APP_OPENDATA',
        id: '打开数据',
      },
      builtinLogic: true,
      id: 'opendata',
    },
  ],
  appViewMsgGroupId: 'map_exp_view_group',
  controls: [
    {
      xdataControlName: 'mapexpbar_map',
      enableCounter: true,
      showTitleBar: true,
      autoLoad: true,
      showBusyIndicator: true,
      controls: [
        {
          legendPos: 'NONE',
          navViewPos: 'NONE',
          autoLoad: true,
          showBusyIndicator: true,
          codeName: 'map_exp_view_map_view',
          controlType: 'MAP',
          logicName: '地图导航视图_地图部件',
          appDataEntityId: 'web.master',
          controlLogics: [
            {
              eventNames: 'SELECTIONCHANGE',
              logicTag: 'mapexpbar_map',
              logicType: 'CUSTOM',
              triggerType: 'CTRLEVENT',
              id: 'mapexpbar_selectionchange',
            },
            {
              eventNames: 'LOAD',
              logicTag: 'mapexpbar_map',
              logicType: 'CUSTOM',
              triggerType: 'CTRLEVENT',
              id: 'mapexpbar_load',
            },
          ],
          controlParam: {
            id: 'mapexpbar_map',
          },
          modelId: '125dd3722cb98c4b23fb682ac882627b',
          modelType: 'PSSYSMAPVIEW',
          name: 'mapexpbar_map',
          id: 'web.master.map_exp_view_map_view',
        },
      ],
      codeName: 'map_exp_view_mapexpbar',
      controlType: 'MAPEXPBAR',
      appDataEntityId: 'web.master',
      controlParam: {
        id: 'mapexpbar',
      },
      modelId: 'd218ad07ee531a8f59c0121293e7b20a_mapexpbar',
      modelType: 'PSEXPBAR',
      name: 'mapexpbar',
      id: 'map_exp_view_mapexpbar',
    },
    {
      groupMode: 'SINGLE',
      quickSearchMode: 1,
      enableQuickSearch: true,
      controlType: 'SEARCHBAR',
      appDataEntityId: 'web.master',
      controlParam: {
        id: 'searchbar',
      },
      id: 'searchbar',
    },
    {
      capLanguageRes: {
        lanResTag: 'DE.LNAME.MASTER',
      },
      caption: '地图导航视图',
      codeName: 'map_exp_view_captionbar',
      controlType: 'CAPTIONBAR',
      appDataEntityId: 'web.master',
      controlParam: {},
      name: 'captionbar',
      id: 'map_exp_view_captionbar',
    },
  ],
  viewLayoutPanel: {
    layoutBodyOnly: true,
    useDefaultLayout: true,
    layoutPanel: true,
    codeName: 'layoutpanel',
    controlStyle: 'APPDEMAPEXPVIEW',
    controlType: 'VIEWLAYOUTPANEL',
    appDataEntityId: 'web.master',
    controlParam: {},
    id: 'layoutpanel',
  },
  title: '地图导航视图',
  viewStyle: 'DEFAULT',
  viewType: 'DEMAPEXPVIEW',
  enableDP: true,
  showCaptionBar: false,
  modelId: 'd218ad07ee531a8f59c0121293e7b20a',
  modelType: 'PSAPPDEVIEW',
  name: 'MASTERmap_exp_view',
  id: 'web.master_map_exp_view',
};
