export default {
  mdctrlActiveMode: 2,
  xdataControlName: 'dataview',
  loadDefault: true,
  deviewCodeName: 'card_format',
  deviewId: '5c7b675f28aeb62df763984371c9f498',
  accUserMode: 3,
  capLanguageRes: {
    lanResTag: 'DE.LNAME.MASTER',
  },
  caption: '值格式化',
  codeName: 'master_card_format',
  appDataEntityId: 'web.master',
  appViewEngines: [
    {
      engineCat: 'VIEW',
      engineType: 'DataView',
      id: 'engine',
    },
  ],
  appViewLogics: [
    {
      logicTrigger: 'CUSTOM',
      logicType: 'APPUILOGIC',
      builtinAppUILogic: {
        actionAfterWizard: 'DEFAULT',
        newDataAppView: {
          openMode: 'POPUPMODAL',
          refAppViewId: 'web.master_edit_view',
        },
        appUILogicRefViews: [
          {
            openMode: 'POPUPMODAL',
            refAppViewId: 'web.master_edit_view',
          },
        ],
        builtinLogic: true,
        logicType: 'PREDEFINED',
        viewLogicType: 'APP_NEWDATA',
        id: '新建数据',
      },
      builtinLogic: true,
      id: 'newdata',
    },
    {
      logicTrigger: 'CUSTOM',
      logicType: 'APPUILOGIC',
      builtinAppUILogic: {
        openDataAppView: {
          openMode: 'POPUPMODAL',
          refAppViewId: 'web.master_edit_view',
        },
        editMode: true,
        appUILogicRefViews: [
          {
            openMode: 'POPUPMODAL',
            refAppViewId: 'web.master_edit_view',
          },
        ],
        builtinLogic: true,
        logicType: 'PREDEFINED',
        viewLogicType: 'APP_OPENDATA',
        id: '打开数据',
      },
      builtinLogic: true,
      id: 'opendata',
    },
  ],
  appViewMsgGroupId: 'card_format',
  appViewRefs: [
    {
      realOpenMode: 'POPUPMODAL',
      realTitle: '主数据编辑视图',
      refAppViewId: 'web.master_edit_view',
      name: 'NEWDATA',
      id: 'newdata',
    },
    {
      realOpenMode: 'POPUPMODAL',
      realTitle: '主数据编辑视图',
      refAppViewId: 'web.master_edit_view',
      name: 'EDITDATA',
      id: 'editdata',
    },
  ],
  controls: [
    {
      groupMode: 'NONE',
      groupStyle: 'DEFAULT',
      itemLayoutPanel: {
        layoutMode: 'TABLE_24COL',
        layout: {
          columnCount: 24,
          layout: 'TABLE_24COL',
        },
        rootPanelItems: [
          {
            actionGroupExtractMode: 'ITEM',
            panelItems: [
              {
                editor: {
                  halign: 'LEFT',
                  renderMode: 'TEXT_DYNAMIC',
                  valign: 'MIDDLE',
                  wrapMode: 'NOWRAP',
                  editorType: 'SPAN',
                  predefinedType: 'FIELD_TEXT_DYNAMIC',
                  valueType: 'SIMPLE',
                  editable: true,
                  id: 'name',
                },
                valueFormat: '标签：@',
                viewFieldName: 'name',
                allowEmpty: true,
                caption: '文本(动态)',
                itemStyle: 'DEFAULT',
                itemType: 'FIELD',
                layoutPos: {
                  shrink: 1,
                  layout: 'FLEX',
                },
                id: 'name',
              },
              {
                editor: {
                  halign: 'LEFT',
                  renderMode: 'TEXT_DYNAMIC',
                  valign: 'MIDDLE',
                  wrapMode: 'NOWRAP',
                  editorType: 'SPAN',
                  predefinedType: 'FIELD_TEXT_DYNAMIC',
                  valueType: 'SIMPLE',
                  editable: true,
                  id: 'quantity',
                },
                valueFormat: '千分位数量：#,###',
                viewFieldName: 'quantity',
                allowEmpty: true,
                caption: '文本(动态)',
                itemStyle: 'DEFAULT',
                itemType: 'FIELD',
                layoutPos: {
                  shrink: 1,
                  layout: 'FLEX',
                },
                id: 'quantity',
              },
            ],
            layout: {
              dir: 'column',
              layout: 'FLEX',
            },
            dataRegionType: 'INHERIT',
            itemStyle: 'DEFAULT',
            itemType: 'CONTAINER',
            layoutPos: {
              colMD: 24,
              layout: 'TABLE_24COL',
            },
            id: 'page_container',
          },
        ],
        codeName: 'usr0516557712',
        controlType: 'PANEL',
        logicName: '卡片_值格式化_卡片视图_卡片面板',
        appDataEntityId: 'web.master',
        controlParam: {},
        modelId: 'a925190718c7b2652e3da39f3c8dc02a',
        modelType: 'PSSYSVIEWPANEL',
        name: 'itemlayoutpanel',
        id: 'web.master.usr0516557712',
      },
      dedataViewDataItems: [
        {
          appDEFieldId: 'id',
          dataType: 25,
          id: 'srfkey',
        },
        {
          appDEFieldId: 'name',
          dataType: 25,
          id: 'srfmajortext',
        },
        {
          appDEFieldId: 'region_id',
          dataType: 25,
          id: 'region_id',
        },
      ],
      pagingMode: 1,
      pagingSize: 10,
      appendDEItems: true,
      enablePagingBar: true,
      navViewPos: 'NONE',
      createControlAction: {
        appDEMethodId: 'create',
        appDataEntityId: 'web.master',
        id: 'create',
      },
      fetchControlAction: {
        appDEMethodId: 'fetch_default',
        appDataEntityId: 'web.master',
        id: 'fetch',
      },
      getControlAction: {
        appDEMethodId: 'get',
        appDataEntityId: 'web.master',
        id: 'load',
      },
      removeControlAction: {
        appDEMethodId: 'remove',
        appDataEntityId: 'web.master',
        id: 'remove',
      },
      updateControlAction: {
        appDEMethodId: 'update',
        appDataEntityId: 'web.master',
        id: 'update',
      },
      autoLoad: true,
      showBusyIndicator: true,
      codeName: 'card_format_data_view',
      controlType: 'DATAVIEW',
      logicName: '卡片_值格式化_卡片视图',
      appDataEntityId: 'web.master',
      controlParam: {
        id: 'dataview',
      },
      modelId: 'c6a2bee46abddae9bfff35e1c6cb22a0',
      modelType: 'PSDEDATAVIEW',
      name: 'dataview',
      id: 'web.master.card_format_data_view',
    },
    {
      groupMode: 'SINGLE',
      controlType: 'SEARCHBAR',
      appDataEntityId: 'web.master',
      controlParam: {
        id: 'searchbar',
      },
      id: 'searchbar',
    },
    {
      capLanguageRes: {
        lanResTag: 'DE.LNAME.MASTER',
      },
      caption: '值格式化',
      codeName: 'card_format_captionbar',
      controlType: 'CAPTIONBAR',
      appDataEntityId: 'web.master',
      controlParam: {},
      name: 'captionbar',
      id: 'card_format_captionbar',
    },
  ],
  viewLayoutPanel: {
    layoutBodyOnly: true,
    useDefaultLayout: true,
    layoutPanel: true,
    codeName: 'layoutpanel',
    controlStyle: 'APPDEDATAVIEW',
    controlType: 'VIEWLAYOUTPANEL',
    appDataEntityId: 'web.master',
    controlParam: {},
    id: 'layoutpanel',
  },
  title: '值格式化',
  viewStyle: 'DEFAULT',
  viewType: 'DEDATAVIEW',
  enableDP: true,
  showCaptionBar: false,
  modelId: 'c36913d0bcd0d4160079713edc4ade4c',
  modelType: 'PSAPPDEVIEW',
  name: 'MASTERcard_format',
  id: 'web.master_card_format',
};
