export default {
  enableDirtyChecking: true,
  showDataInfoBar: true,
  xdataControlName: 'form',
  loadDefault: true,
  deviewCodeName: 'comment_display',
  deviewId: 'c290337dc6cc78c952f4b4b571c08dd1',
  accUserMode: 2,
  capLanguageRes: {
    lanResTag: 'DE.LNAME.MASTER',
  },
  caption: '评论展示',
  codeName: 'master_comment_display',
  appDataEntityId: 'web.master',
  appViewNavContexts: [
    {
      rawValue: true,
      key: 'MASTER',
      value: 'sample',
      name: 'MASTER',
      id: 'master',
    },
  ],
  viewLayoutPanel: {
    layoutBodyOnly: true,
    viewProxyMode: true,
    layoutMode: 'FLEX',
    layout: {
      layout: 'FLEX',
    },
    rootPanelItems: [
      {
        actionGroupExtractMode: 'ITEM',
        panelItems: [
          {
            actionGroupExtractMode: 'ITEM',
            panelItems: [
              {
                actionGroupExtractMode: 'ITEM',
                panelItems: [
                  {
                    caption: '页面标题',
                    itemStyle: 'DEFAULT',
                    itemType: 'CTRLPOS',
                    layoutPos: {
                      shrink: 1,
                      layout: 'FLEX',
                    },
                    showCaption: true,
                    id: 'captionbar',
                  },
                ],
                layout: {
                  align: 'center',
                  layout: 'FLEX',
                },
                dataRegionType: 'INHERIT',
                caption: '容器',
                itemStyle: 'DEFAULT',
                itemType: 'CONTAINER',
                layoutPos: {
                  shrink: 1,
                  heightMode: 'FULL',
                  layout: 'FLEX',
                },
                id: 'view_captionbar',
              },
            ],
            layout: {
              layout: 'FLEX',
            },
            dataRegionType: 'INHERIT',
            caption: '容器',
            itemStyle: 'DEFAULT',
            itemType: 'CONTAINER',
            layoutPos: {
              shrink: 1,
              heightMode: 'FULL',
              layout: 'FLEX',
            },
            id: 'view_header_left',
          },
          {
            actionGroupExtractMode: 'ITEM',
            panelItems: [
              {
                actionGroupExtractMode: 'ITEM',
                panelItems: [
                  {
                    caption: '工具栏',
                    itemStyle: 'DEFAULT',
                    itemType: 'CTRLPOS',
                    layoutPos: {
                      shrink: 1,
                      layout: 'FLEX',
                    },
                    showCaption: true,
                    id: 'toolbar',
                  },
                ],
                layout: {
                  align: 'center',
                  layout: 'FLEX',
                },
                dataRegionType: 'INHERIT',
                caption: '容器',
                itemStyle: 'DEFAULT',
                itemType: 'CONTAINER',
                layoutPos: {
                  shrink: 1,
                  heightMode: 'FULL',
                  layout: 'FLEX',
                },
                id: 'view_toolbar',
              },
            ],
            layout: {
              layout: 'FLEX',
            },
            dataRegionType: 'INHERIT',
            caption: '容器',
            itemStyle: 'DEFAULT',
            itemType: 'CONTAINER',
            layoutPos: {
              shrink: 1,
              heightMode: 'FULL',
              layout: 'FLEX',
            },
            id: 'view_header_right',
          },
        ],
        predefinedType: 'VIEWHEADER',
        layout: {
          align: 'space-between',
          dir: 'row',
          layout: 'FLEX',
          valign: 'center',
        },
        dataRegionType: 'INHERIT',
        caption: '容器',
        itemStyle: 'DEFAULT',
        itemType: 'CONTAINER',
        layoutPos: {
          shrink: 0,
          layout: 'FLEX',
        },
        id: 'view_header',
      },
      {
        actionGroupExtractMode: 'ITEM',
        panelItems: [
          {
            caption: '表单',
            itemStyle: 'DEFAULT',
            itemType: 'CTRLPOS',
            layoutPos: {
              grow: 1,
              shrink: 1,
              layout: 'FLEX',
            },
            showCaption: true,
            id: 'form',
          },
        ],
        predefinedType: 'VIEWCONTENT',
        layout: {
          layout: 'FLEX',
        },
        dataRegionType: 'INHERIT',
        caption: '容器',
        itemStyle: 'DEFAULT',
        itemType: 'CONTAINER',
        layoutPos: {
          grow: 1,
          shrink: 1,
          layout: 'FLEX',
        },
        id: 'view_content',
      },
      {
        actionGroupExtractMode: 'ITEM',
        panelItems: [
          {
            actionGroupExtractMode: 'ITEM',
            panelItems: [
              {
                actionGroupExtractMode: 'ITEM',
                panelItems: [
                  {
                    actionGroupExtractMode: 'ITEM',
                    panelItems: [
                      {
                        actionGroupExtractMode: 'ITEM',
                        panelItems: [
                          {
                            editor: {
                              enableAC: true,
                              editorParams: {
                                LINKVIEWID:
                                  'plmweb.recent_custom_redirect_view',
                                AC: 'TRUE',
                              },
                              editorStyle: 'COMMENT',
                              editorType: 'HTMLEDITOR',
                              sysPFPluginId: 'comment',
                              predefinedType: 'FIELD_TEXT_DYNAMIC',
                              valueType: 'SIMPLE',
                              editable: true,
                              id: 'field_textbox',
                            },
                            allowEmpty: true,
                            caption: '文本(动态)',
                            itemStyle: 'DEFAULT',
                            itemType: 'FIELD',
                            layoutPos: {
                              grow: 10,
                              shrink: 1,
                              layout: 'FLEX',
                            },
                            id: 'field_textbox',
                          },
                          {
                            actionType: 'UIACTION',
                            buttonStyle: 'INFO',
                            buttonType: 'PANELBUTTON',
                            uiactionId: 'clear_comment@comment',
                            renderMode: 'BUTTON',
                            tooltip: '取消',
                            uiactionTarget: 'NONE',
                            caption: '取消',
                            dynaClass: "['ibiz-panel-button--comment__cancel']",
                            itemStyle: 'INFO',
                            itemType: 'BUTTON',
                            layoutPos: {
                              shrink: 0,
                              layout: 'FLEX',
                            },
                            panelItemGroupLogics: [
                              {
                                logicCat: 'PANELVISIBLE',
                                relatedItemNames: ['field_textbox'],
                                groupOP: 'AND',
                                panelItemLogics: [
                                  {
                                    condOp: 'ISNOTNULL',
                                    dstModelField: 'FIELD_TEXTBOX',
                                    logicType: 'SINGLE',
                                    id: '逻辑项',
                                  },
                                ],
                                logicType: 'GROUP',
                              },
                            ],
                            showCaption: true,
                            id: 'comment_cancel',
                          },
                          {
                            actionType: 'UIACTION',
                            buttonStyle: 'DEFAULT',
                            buttonType: 'PANELBUTTON',
                            uiactionId: 'send_comment@comment',
                            renderMode: 'BUTTON',
                            tooltip: '发送',
                            uiactionTarget: 'NONE',
                            caption: '发送',
                            dynaClass: "['ibiz-panel-button--comment__send']",
                            itemStyle: 'DEFAULT',
                            itemType: 'BUTTON',
                            layoutPos: {
                              shrink: 0,
                              layout: 'FLEX',
                            },
                            panelItemGroupLogics: [
                              {
                                logicCat: 'PANELVISIBLE',
                                relatedItemNames: ['field_textbox'],
                                groupOP: 'AND',
                                panelItemLogics: [
                                  {
                                    condOp: 'ISNOTNULL',
                                    dstModelField: 'FIELD_TEXTBOX',
                                    logicType: 'SINGLE',
                                    id: '逻辑项',
                                  },
                                ],
                                logicType: 'GROUP',
                              },
                            ],
                            showCaption: true,
                            id: 'comment_send',
                          },
                          {
                            rawItem: {
                              sysImage: {
                                cssClass: 'fa fa-arrow-circle-o-right',
                                glyph: 'xf18e@FontAwesome',
                              },
                              contentType: 'IMAGE',
                              dynaClass: "['ibiz-panel-button--comment__icon']",
                              sysCss: {
                                cssName: 'comment_icon',
                              },
                              predefinedType: 'STATIC_IMAGE',
                              rawItemHeight: 48,
                              id: 'comment_icon',
                            },
                            caption: '图片',
                            contentHeight: 48,
                            height: 48,
                            itemStyle: 'DEFAULT',
                            itemType: 'RAWITEM',
                            layoutPos: {
                              shrink: 0,
                              height: 48,
                              heightMode: 'PX',
                              layout: 'FLEX',
                            },
                            sysCss: {
                              cssName: 'comment_icon',
                            },
                            sysImage: {
                              cssClass: 'fa fa-arrow-circle-o-right',
                              glyph: 'xf18e@FontAwesome',
                            },
                            showCaption: true,
                            id: 'comment_icon',
                          },
                        ],
                        layout: {
                          dir: 'row',
                          layout: 'FLEX',
                          valign: 'flex-start',
                        },
                        dataRegionType: 'INHERIT',
                        caption: '容器',
                        itemStyle: 'DEFAULT',
                        itemType: 'CONTAINER',
                        layoutPos: {
                          shrink: 1,
                          heightMode: 'FULL',
                          layout: 'FLEX',
                          widthMode: 'FULL',
                        },
                        id: 'container_comment',
                      },
                    ],
                    layout: {
                      dir: 'column',
                      layout: 'FLEX',
                    },
                    dataRegionType: 'INHERIT',
                    itemStyle: 'DEFAULT',
                    itemType: 'CONTAINER',
                    layoutPos: {
                      colMD: 24,
                      heightMode: 'FULL',
                      layout: 'TABLE_24COL',
                      widthMode: 'FULL',
                    },
                    id: 'page_container',
                  },
                ],
                predefinedType: 'PANELPART',
                layout: {
                  columnCount: 24,
                  layout: 'TABLE_24COL',
                },
                dataRegionType: 'INHERIT',
                caption: '引用布局面板',
                itemStyle: 'DEFAULT',
                itemType: 'CONTAINER',
                layoutPos: {
                  colMD: 24,
                  layout: 'TABLE_24COL',
                },
                showCaption: true,
                id: 'panelpart',
              },
            ],
            layout: {
              columnCount: 24,
              layout: 'TABLE_24COL',
            },
            dataRegionType: 'INHERIT',
            caption: '面板容器',
            itemStyle: 'DEFAULT',
            itemType: 'CONTAINER',
            layoutPos: {
              grow: 12,
              shrink: 1,
              layout: 'SIMPLEFLEX',
            },
            id: 'container',
          },
        ],
        predefinedType: 'CONTAINER_GRID',
        layout: {
          layout: 'SIMPLEFLEX',
        },
        dataRegionType: 'INHERIT',
        caption: '栅格容器',
        itemStyle: 'DEFAULT',
        itemType: 'CONTAINER',
        layoutPos: {
          grow: 0,
          shrink: 0,
          layout: 'FLEX',
        },
        id: 'container_grid',
      },
    ],
    layoutPanel: true,
    appViewEngines: [
      {
        engineCat: 'VIEW',
        engineType: 'EditView',
        id: 'engine',
      },
    ],
    controls: [
      {
        xdataControlName: 'form',
        codeName: 'comment_display_toolbar',
        controlType: 'TOOLBAR',
        logicName: '评论展示_工具栏',
        appDataEntityId: 'web.master',
        controlParam: {
          id: 'toolbar',
        },
        modelId: '00f177b4d271e25eb8dcddbfa31a8148',
        modelType: 'PSDETOOLBAR',
        name: 'toolbar',
        id: 'comment_display_toolbar',
      },
      {
        createControlAction: {
          appDEMethodId: 'create',
          appDataEntityId: 'web.master',
          id: 'create',
        },
        getDraftFromControlAction: {
          appDataEntityId: 'web.master',
          id: 'loaddraftfrom',
        },
        getDraftControlAction: {
          appDEMethodId: 'get_sample_date',
          appDataEntityId: 'web.master',
          id: 'loaddraft',
        },
        getControlAction: {
          appDEMethodId: 'get',
          appDataEntityId: 'web.master',
          id: 'load',
        },
        removeControlAction: {
          appDEMethodId: 'remove',
          appDataEntityId: 'web.master',
          id: 'remove',
        },
        updateControlAction: {
          appDEMethodId: 'update',
          appDataEntityId: 'web.master',
          id: 'update',
        },
        deformPages: [
          {
            layout: {
              columnCount: 24,
              layout: 'TABLE_24COL',
            },
            deformDetails: [
              {
                layout: {
                  columnCount: 24,
                  layout: 'TABLE_24COL',
                },
                deformDetails: [
                  {
                    dataType: 25,
                    enableCond: 3,
                    labelPos: 'LEFT',
                    labelWidth: 130,
                    noPrivDisplayMode: 1,
                    appDEFieldId: 'name',
                    editor: {
                      maxLength: 200,
                      editorType: 'TEXTBOX',
                      valueType: 'SIMPLE',
                      editable: true,
                      id: 'name',
                    },
                    allowEmpty: true,
                    capLanguageRes: {
                      lanResTag: 'DEF.LNAME.MASTER.NAME',
                    },
                    caption: '名称',
                    codeName: 'name',
                    detailStyle: 'DEFAULT',
                    detailType: 'FORMITEM',
                    layoutPos: {
                      colMD: 24,
                      layout: 'TABLE_24COL',
                    },
                    showCaption: true,
                    id: 'name',
                  },
                ],
                caption: '主数据基本信息',
                codeName: 'group1',
                detailStyle: 'DEFAULT',
                detailType: 'GROUPPANEL',
                layoutPos: {
                  colMD: 24,
                  layout: 'TABLE_24COL',
                },
                showCaption: true,
                id: 'group1',
              },
              {
                layout: {
                  columnCount: 24,
                  layout: 'TABLE_24COL',
                },
                deformDetails: [
                  {
                    appViewId: 'web.comment_list_view',
                    parentDataJO: {
                      srfparentdename: 'MASTER',
                      SRFPARENTTYPE: 'CUSTOM',
                    },
                    codeName: 'druipart1',
                    detailStyle: 'DEFAULT',
                    detailType: 'DRUIPART',
                    layoutPos: {
                      colMD: 24,
                      layout: 'TABLE_24COL',
                    },
                    showCaption: true,
                    id: 'druipart1',
                  },
                ],
                caption: '评论',
                codeName: 'grouppanel1',
                detailStyle: 'DEFAULT',
                detailType: 'GROUPPANEL',
                layoutPos: {
                  colMD: 24,
                  layout: 'TABLE_24COL',
                },
                showCaption: true,
                id: 'grouppanel1',
              },
              {
                dataType: 25,
                enableCond: 3,
                labelPos: 'LEFT',
                labelWidth: 130,
                noPrivDisplayMode: 1,
                appDEFieldId: 'id',
                editor: {
                  editorType: 'HIDDEN',
                  valueType: 'SIMPLE',
                  editable: true,
                  id: 'id',
                },
                allowEmpty: true,
                hidden: true,
                capLanguageRes: {
                  lanResTag: 'DEF.LNAME.MASTER.ID',
                },
                caption: '标识',
                codeName: 'id',
                detailStyle: 'DEFAULT',
                detailType: 'FORMITEM',
                layoutPos: {
                  colMD: 24,
                  layout: 'TABLE_24COL',
                },
                id: 'id',
              },
            ],
            caption: '基本信息',
            codeName: 'formpage1',
            detailStyle: 'DEFAULT',
            detailType: 'FORMPAGE',
            id: 'formpage1',
          },
        ],
        layout: {
          columnCount: 24,
          layout: 'TABLE_24COL',
        },
        tabHeaderPos: 'TOP',
        noTabHeader: true,
        autoLoad: true,
        showBusyIndicator: true,
        codeName: 'main79',
        controlType: 'FORM',
        logicName: '评论展示_表单',
        appDataEntityId: 'web.master',
        controlParam: {
          id: 'form',
        },
        modelId: '2488ead5ed4760a81b785f011e095de7',
        modelType: 'PSDEFORM_EDITFORM',
        name: 'form',
        id: 'web.master.main79',
      },
      {
        codeName: 'comment_display_datainfobar',
        controlType: 'DATAINFOBAR',
        appDataEntityId: 'web.master',
        controlParam: {
          id: 'datainfobar',
        },
        name: 'datainfobar',
        id: 'comment_display_datainfobar',
      },
      {
        capLanguageRes: {
          lanResTag: 'DE.LNAME.MASTER',
        },
        caption: '评论展示',
        codeName: 'comment_display_captionbar',
        controlType: 'CAPTIONBAR',
        appDataEntityId: 'web.master',
        controlParam: {},
        name: 'captionbar',
        id: 'comment_display_captionbar',
      },
    ],
    codeName: 'ad5352692624d57ee43',
    controlType: 'VIEWLAYOUTPANEL',
    logicName: 'comment_display编辑视图布局面板',
    appDataEntityId: 'web.master',
    controlLogics: [
      {
        eventNames: 'onClick',
        itemName: 'COMMENT_SEND',
        logicTag: 'layoutpanel',
        logicType: 'SCRIPT',
        scriptCode:
          'const uiDomain = ibiz.uiDomainManager.get(context.srfsessionid);\r\nif (uiDomain) {\r\n    uiDomain.dataChangeCompleted()\r\n}',
        triggerType: 'CTRLEVENT',
        id: 'logic2',
      },
      {
        eventNames: 'onClick',
        itemName: 'COMMENT_CANCEL',
        logicTag: 'layoutpanel',
        logicType: 'SCRIPT',
        scriptCode:
          'const uiDomain = ibiz.uiDomainManager.get(context.srfsessionid);\r\nif (uiDomain) {\r\n    uiDomain.dataChangeCompleted()\r\n}',
        triggerType: 'CTRLEVENT',
        id: 'logic3',
      },
      {
        eventNames: 'onBlur',
        itemName: 'FIELD_TEXTBOX',
        logicTag: 'layoutpanel',
        logicType: 'APPDEUILOGIC',
        appDEUILogicId: 'comment_icon_hidden',
        appDataEntityId: 'web.comment',
        triggerType: 'CTRLEVENT',
        name: 'onBlur',
        id: 'onblur',
      },
      {
        eventNames: 'onChange',
        itemName: 'FIELD_TEXTBOX',
        logicTag: 'layoutpanel',
        logicType: 'SCRIPT',
        scriptCode:
          'const uiDomain = ibiz.uiDomainManager.get(context.srfsessionid);\r\nif (!uiDomain) {\r\n    return;\r\n}\r\n\r\nconst value = data[0].field_textbox;\r\nif (value) {\r\n    uiDomain.dataChange();\r\n} else {\r\n    uiDomain.dataChangeCompleted();\r\n}',
        triggerType: 'CTRLEVENT',
        name: 'onChange',
        id: 'onchange',
      },
      {
        eventNames: 'onFocus',
        itemName: 'FIELD_TEXTBOX',
        logicTag: 'layoutpanel',
        logicType: 'APPDEUILOGIC',
        appDEUILogicId: 'comment_icon_show',
        appDataEntityId: 'web.comment',
        triggerType: 'CTRLEVENT',
        name: 'onFocus',
        id: 'onfocus',
      },
    ],
    controlParam: {},
    modelId: '01ac0bddc9a53f912815790876863771',
    modelType: 'PSSYSVIEWLAYOUTPANEL',
    name: 'layoutpanel',
    id: 'ad5352692624d57ee43',
  },
  title: '评论展示',
  viewStyle: 'DEFAULT',
  viewType: 'DEEDITVIEW',
  enableDP: true,
  showCaptionBar: true,
  modelId: '81abe0eabd0f4d7bf273d208fcb53f5c',
  modelType: 'PSAPPDEVIEW',
  name: 'MASTERcomment_display',
  id: 'web.master_comment_display',
};
