export default {
  deviewCodeName: 'counter_tab_exp',
  deviewId: '2d7720305fcfe688768ad4f4a06763bd',
  accUserMode: 3,
  capLanguageRes: {
    lanResTag: 'DE.LNAME.MASTER',
  },
  caption: '计数器_分页导航',
  codeName: 'master_counter_tab_exp',
  appDataEntityId: 'web.master',
  appViewMsgGroupId: 'counter_tab_exp',
  viewLayoutPanel: {
    layoutBodyOnly: true,
    viewProxyMode: true,
    layoutMode: 'FLEX',
    layout: {
      layout: 'FLEX',
    },
    rootPanelItems: [
      {
        actionGroupExtractMode: 'ITEM',
        panelItems: [
          {
            caption: '关系分页部件',
            itemStyle: 'DEFAULT',
            itemType: 'CTRLPOS',
            layoutPos: {
              shrink: 1,
              layout: 'FLEX',
            },
            showCaption: true,
            id: 'drtab',
          },
        ],
        predefinedType: 'CONTAINER_GROUP',
        layout: {
          layout: 'FLEX',
        },
        dataRegionType: 'INHERIT',
        caption: '关系分页部件',
        itemStyle: 'DEFAULT',
        itemType: 'CONTAINER',
        layoutPos: {
          shrink: 1,
          layout: 'FLEX',
        },
        showCaption: true,
        id: 'container_group',
      },
      {
        actionGroupExtractMode: 'ITEM',
        panelItems: [
          {
            caption: '关系数据栏',
            itemStyle: 'DEFAULT',
            itemType: 'CTRLPOS',
            layoutPos: {
              shrink: 1,
              layout: 'FLEX',
            },
            showCaption: true,
            id: 'drbar',
          },
        ],
        predefinedType: 'CONTAINER_GROUP',
        layout: {
          layout: 'FLEX',
        },
        dataRegionType: 'INHERIT',
        caption: '关系数据栏',
        itemStyle: 'DEFAULT',
        itemType: 'CONTAINER',
        layoutPos: {
          shrink: 1,
          layout: 'FLEX',
        },
        showCaption: true,
        id: 'container_group1',
      },
    ],
    layoutPanel: true,
    controls: [
      {
        dedrtabPages: [
          {
            caption: '编辑表单',
            counterId: 'form',
            appViewId: 'web.master_counter_exp_form',
            id: 'form',
          },
          {
            caption: '表格',
            counterId: 'grid',
            appViewId: 'web.master_counter_exp_grid',
            id: 'grid',
          },
        ],
        dataRelationTag: 'counter_tab_exp_DR',
        editItemCapLanguageRes: {
          lanResTag: 'DE.LNAME.MASTER',
        },
        editItemCaption: '主数据',
        appCounterRefId: 'd0a6e348d1ed8a3141d3466137925bc7',
        uniqueTag: 'master_counter_tab_exp__drtab',
        autoLoad: true,
        showBusyIndicator: true,
        appCounterRefs: [
          {
            appCounter: {
              codeName: 'Counter',
              counterType: 'DEDR',
              getAppDEActionId: 'get_counter_data',
              appDataEntityId: 'web.master',
              timer: 60000,
              uniqueTag: 'Counter',
              name: '计数器',
              id: 'web.counter',
            },
            refMode: {
              srfdeid: 'MASTER',
            },
            tag: 'd0a6e348d1ed8a3141d3466137925bc7',
            uniqueTag: 'Counter',
            id: 'd0a6e348d1ed8a3141d3466137925bc7',
          },
        ],
        codeName: 'counter_tab_exp_dr',
        controlType: 'DRTAB',
        appDataEntityId: 'web.master',
        controlParam: {
          id: 'drtab',
        },
        modelId: 'b0773b4f07f717739d5eaa49b39f721c',
        modelType: 'PSDEDRTAB',
        name: 'drtab',
        id: 'counter_tab_exp_dr',
      },
      {
        dedrbarGroups: [
          {
            caption: '默认',
            name: '默认',
            id: 'a0aa99ad32515d58406',
          },
        ],
        showTitle: true,
        dataRelationTag: 'counter_tab_exp_DR',
        editItemCapLanguageRes: {
          lanResTag: 'DE.LNAME.MASTER',
        },
        editItemCaption: '主数据',
        appCounterRefId: 'd0a6e348d1ed8a3141d3466137925bc7',
        dedrctrlItems: [
          {
            dedrbarGroupId: 'a0aa99ad32515d58406',
            caption: '编辑表单',
            counterId: 'form',
            appViewId: 'web.master_counter_exp_form',
            id: 'form',
          },
          {
            dedrbarGroupId: 'a0aa99ad32515d58406',
            caption: '表格',
            counterId: 'grid',
            appViewId: 'web.master_counter_exp_grid',
            id: 'grid',
          },
        ],
        uniqueTag: 'master_counter_tab_exp__drbar',
        autoLoad: true,
        showBusyIndicator: true,
        appCounterRefs: [
          {
            appCounter: {
              codeName: 'Counter',
              counterType: 'DEDR',
              getAppDEActionId: 'get_counter_data',
              appDataEntityId: 'web.master',
              timer: 60000,
              uniqueTag: 'Counter',
              name: '计数器',
              id: 'web.counter',
            },
            refMode: {
              srfdeid: 'MASTER',
            },
            tag: 'd0a6e348d1ed8a3141d3466137925bc7',
            uniqueTag: 'Counter',
            id: 'd0a6e348d1ed8a3141d3466137925bc7',
          },
        ],
        codeName: 'counter_tab_exp_dr',
        controlType: 'DRBAR',
        appDataEntityId: 'web.master',
        controlParam: {
          id: 'drbar',
        },
        modelId: 'b0773b4f07f717739d5eaa49b39f721c',
        modelType: 'PSDEDRBAR',
        name: 'drbar',
        id: 'counter_tab_exp_dr',
      },
      {
        capLanguageRes: {
          lanResTag: 'DE.LNAME.MASTER',
        },
        caption: '计数器_分页导航',
        codeName: 'counter_tab_exp_captionbar',
        controlType: 'CAPTIONBAR',
        appDataEntityId: 'web.master',
        controlParam: {},
        name: 'captionbar',
        id: 'counter_tab_exp_captionbar',
      },
    ],
    codeName: 'ac87f82d8964aef313b',
    controlType: 'VIEWLAYOUTPANEL',
    logicName: 'counter_tab_exp',
    appDataEntityId: 'web.master',
    controlParam: {},
    modelId: '97ddde14c5c1fb9c9081ee44c93e4217',
    modelType: 'PSSYSVIEWLAYOUTPANEL',
    name: 'layoutpanel',
    id: 'ac87f82d8964aef313b',
  },
  title: '计数器_分页导航',
  viewStyle: 'DEFAULT',
  viewType: 'DECUSTOMVIEW',
  enableDP: true,
  showCaptionBar: false,
  modelId: '6da2fa801fca00e1495c64cc7b71fab7',
  modelType: 'PSAPPDEVIEW',
  name: 'MASTERcounter_tab_exp',
  id: 'web.master_counter_tab_exp',
};
