export default {
  enableDirtyChecking: true,
  showDataInfoBar: true,
  xdataControlName: 'form',
  loadDefault: true,
  deviewCodeName: 'Runtime_Components',
  deviewId: '40e95d4f05a1a7a6e6818b90dc20f152',
  accUserMode: 3,
  capLanguageRes: {
    lanResTag: 'DE.LNAME.MASTER',
  },
  caption: '编辑器_运行时组件',
  codeName: 'master_runtime_components',
  appDataEntityId: 'web.master',
  appViewMsgGroupId: 'runtime_components',
  viewLayoutPanel: {
    layoutBodyOnly: true,
    viewProxyMode: true,
    layoutMode: 'FLEX',
    layout: {
      layout: 'FLEX',
    },
    rootPanelItems: [
      {
        actionGroupExtractMode: 'ITEM',
        panelItems: [
          {
            actionGroupExtractMode: 'ITEM',
            panelItems: [
              {
                actionGroupExtractMode: 'ITEM',
                panelItems: [
                  {
                    caption: '页面标题',
                    itemStyle: 'DEFAULT',
                    itemType: 'CTRLPOS',
                    layoutPos: {
                      shrink: 1,
                      layout: 'FLEX',
                    },
                    showCaption: true,
                    id: 'captionbar',
                  },
                ],
                layout: {
                  align: 'center',
                  layout: 'FLEX',
                },
                dataRegionType: 'INHERIT',
                caption: '容器',
                itemStyle: 'DEFAULT',
                itemType: 'CONTAINER',
                layoutPos: {
                  shrink: 1,
                  heightMode: 'FULL',
                  layout: 'FLEX',
                },
                id: 'view_captionbar',
              },
            ],
            layout: {
              layout: 'FLEX',
            },
            dataRegionType: 'INHERIT',
            caption: '容器',
            itemStyle: 'DEFAULT',
            itemType: 'CONTAINER',
            layoutPos: {
              shrink: 1,
              heightMode: 'FULL',
              layout: 'FLEX',
            },
            id: 'view_header_left',
          },
          {
            actionGroupExtractMode: 'ITEM',
            panelItems: [
              {
                actionGroupExtractMode: 'ITEM',
                panelItems: [
                  {
                    caption: '工具栏',
                    itemStyle: 'DEFAULT',
                    itemType: 'CTRLPOS',
                    layoutPos: {
                      shrink: 1,
                      layout: 'FLEX',
                    },
                    showCaption: true,
                    id: 'toolbar',
                  },
                ],
                layout: {
                  align: 'center',
                  layout: 'FLEX',
                },
                dataRegionType: 'INHERIT',
                caption: '容器',
                itemStyle: 'DEFAULT',
                itemType: 'CONTAINER',
                layoutPos: {
                  shrink: 1,
                  heightMode: 'FULL',
                  layout: 'FLEX',
                },
                id: 'view_toolbar',
              },
            ],
            layout: {
              layout: 'FLEX',
            },
            dataRegionType: 'INHERIT',
            caption: '容器',
            itemStyle: 'DEFAULT',
            itemType: 'CONTAINER',
            layoutPos: {
              shrink: 1,
              heightMode: 'FULL',
              layout: 'FLEX',
            },
            id: 'view_header_right',
          },
        ],
        predefinedType: 'VIEWHEADER',
        layout: {
          align: 'space-between',
          dir: 'row',
          layout: 'FLEX',
          valign: 'center',
        },
        dataRegionType: 'INHERIT',
        caption: '容器',
        itemStyle: 'DEFAULT',
        itemType: 'CONTAINER',
        layoutPos: {
          shrink: 0,
          layout: 'FLEX',
        },
        id: 'view_header',
      },
      {
        actionGroupExtractMode: 'ITEM',
        panelItems: [
          {
            caption: '表单',
            itemStyle: 'DEFAULT',
            itemType: 'CTRLPOS',
            layoutPos: {
              grow: 1,
              shrink: 1,
              layout: 'FLEX',
            },
            showCaption: true,
            id: 'form',
          },
        ],
        predefinedType: 'VIEWCONTENT',
        layout: {
          layout: 'FLEX',
        },
        dataRegionType: 'INHERIT',
        caption: '容器',
        itemStyle: 'DEFAULT',
        itemType: 'CONTAINER',
        layoutPos: {
          grow: 1,
          shrink: 1,
          layout: 'FLEX',
        },
        id: 'view_content',
      },
    ],
    layoutPanel: true,
    appViewEngines: [
      {
        engineCat: 'VIEW',
        engineType: 'EditView',
        id: 'engine',
      },
    ],
    controls: [
      {
        createControlAction: {
          appDEMethodId: 'create',
          appDataEntityId: 'web.master',
          id: 'create',
        },
        getDraftFromControlAction: {
          appDataEntityId: 'web.master',
          id: 'loaddraftfrom',
        },
        getDraftControlAction: {
          appDEMethodId: 'get_draft',
          appDataEntityId: 'web.master',
          id: 'loaddraft',
        },
        getControlAction: {
          appDEMethodId: 'get',
          appDataEntityId: 'web.master',
          id: 'load',
        },
        removeControlAction: {
          appDEMethodId: 'remove',
          appDataEntityId: 'web.master',
          id: 'remove',
        },
        updateControlAction: {
          appDEMethodId: 'update',
          appDataEntityId: 'web.master',
          id: 'update',
        },
        deformPages: [
          {
            layout: {
              columnCount: 24,
              layout: 'TABLE_24COL',
            },
            deformDetails: [
              {
                layout: {
                  columnCount: 24,
                  layout: 'TABLE_24COL',
                },
                deformDetails: [
                  {
                    dataType: 25,
                    enableCond: 3,
                    labelPos: 'LEFT',
                    labelWidth: 130,
                    noPrivDisplayMode: 1,
                    editor: {
                      singleSelect: true,
                      enableAC: true,
                      forceSelection: true,
                      showTrigger: true,
                      editorParams: {
                        AC: 'TRUE',
                        TRIGGER: 'TRUE',
                        PICKUPVIEW: 'FALSE',
                      },
                      editorStyle: 'PERSONEL_SELECT',
                      editorType: 'PICKEREX_TRIGGER',
                      sysPFPluginId: 'person_select',
                      valueType: 'SIMPLE',
                      editable: true,
                      id: 'formitem',
                    },
                    allowEmpty: true,
                    codeName: 'formitem',
                    detailStyle: 'DEFAULT',
                    detailType: 'FORMITEM',
                    layoutPos: {
                      colMD: 24,
                      layout: 'TABLE_24COL',
                    },
                    showCaption: true,
                    id: 'formitem',
                  },
                  {
                    dataType: 25,
                    enableCond: 3,
                    labelPos: 'LEFT',
                    labelWidth: 130,
                    noPrivDisplayMode: 1,
                    editor: {
                      singleSelect: true,
                      enableAC: true,
                      forceSelection: true,
                      showTrigger: true,
                      editorParams: {
                        ISSHOWTAB: 'false',
                        'SRFNAVPARAM.size': '50',
                        CLEARFILTER: 'true',
                        AC: 'TRUE',
                        TRIGGER: 'TRUE',
                        URL: '/users/fetch_default',
                        PICKUPVIEW: 'FALSE',
                        'SRFNAVPARAM.page': '0',
                        SUFFIX: 'department_name',
                        USERMETHOD: 'post',
                        USERMAP: '{"id":"id","name":"display_name"}',
                      },
                      editorStyle: 'PERSONEL_SELECT_ALL',
                      editorType: 'PICKEREX_TRIGGER',
                      sysPFPluginId: 'person_select',
                      valueType: 'SIMPLE',
                      editable: true,
                      navigateParams: [
                        {
                          key: 'size',
                          value: '50',
                          rawValue: true,
                          id: 'size',
                        },
                        {
                          key: 'page',
                          value: '0',
                          rawValue: true,
                          id: 'page',
                        },
                      ],
                      id: 'formitem1',
                    },
                    allowEmpty: true,
                    codeName: 'formitem1',
                    detailStyle: 'DEFAULT',
                    detailType: 'FORMITEM',
                    layoutPos: {
                      colMD: 24,
                      layout: 'TABLE_24COL',
                    },
                    showCaption: true,
                    id: 'formitem1',
                  },
                ],
                caption: '运行时组件',
                codeName: 'group1',
                detailStyle: 'DEFAULT',
                detailType: 'GROUPPANEL',
                layoutPos: {
                  colMD: 24,
                  layout: 'TABLE_24COL',
                },
                showCaption: true,
                id: 'group1',
              },
              {
                dataType: 25,
                enableCond: 3,
                labelPos: 'LEFT',
                labelWidth: 130,
                noPrivDisplayMode: 1,
                appDEFieldId: 'id',
                editor: {
                  editorType: 'HIDDEN',
                  valueType: 'SIMPLE',
                  editable: true,
                  id: 'id',
                },
                allowEmpty: true,
                hidden: true,
                capLanguageRes: {
                  lanResTag: 'DEF.LNAME.MASTER.ID',
                },
                caption: '标识',
                codeName: 'id',
                detailStyle: 'DEFAULT',
                detailType: 'FORMITEM',
                layoutPos: {
                  colMD: 24,
                  layout: 'TABLE_24COL',
                },
                id: 'id',
              },
            ],
            caption: '运行时组件',
            codeName: 'formpage1',
            detailStyle: 'DEFAULT',
            detailType: 'FORMPAGE',
            id: 'formpage1',
          },
        ],
        layout: {
          columnCount: 24,
          layout: 'TABLE_24COL',
        },
        tabHeaderPos: 'TOP',
        noTabHeader: true,
        autoLoad: true,
        showBusyIndicator: true,
        codeName: 'main67',
        controlType: 'FORM',
        logicName: '编辑器_运行时组件_表单',
        appDataEntityId: 'web.master',
        controlParam: {
          id: 'form',
        },
        modelId: '24fca17698f3a12334c703815d99df13',
        modelType: 'PSDEFORM_EDITFORM',
        name: 'form',
        id: 'web.master.main67',
      },
      {
        xdataControlName: 'form',
        codeName: 'runtime_components_toolbar',
        controlType: 'TOOLBAR',
        logicName: '编辑器_运行时组件_工具栏',
        appDataEntityId: 'web.master',
        controlParam: {
          id: 'toolbar',
        },
        modelId: '66a85d893820ff6fe1c24fa36dbbda5c',
        modelType: 'PSDETOOLBAR',
        name: 'toolbar',
        id: 'runtime_components_toolbar',
      },
      {
        codeName: 'runtime_components_datainfobar',
        controlType: 'DATAINFOBAR',
        appDataEntityId: 'web.master',
        controlParam: {
          id: 'datainfobar',
        },
        name: 'datainfobar',
        id: 'runtime_components_datainfobar',
      },
      {
        capLanguageRes: {
          lanResTag: 'DE.LNAME.MASTER',
        },
        caption: '编辑器_运行时组件',
        codeName: 'runtime_components_captionbar',
        controlType: 'CAPTIONBAR',
        appDataEntityId: 'web.master',
        controlParam: {},
        name: 'captionbar',
        id: 'runtime_components_captionbar',
      },
    ],
    codeName: 'a6af108fc05f471a0b7',
    controlType: 'VIEWLAYOUTPANEL',
    logicName: 'Runtime_Components编辑视图布局面板',
    appDataEntityId: 'web.master',
    controlParam: {},
    modelId: '40b3e24f418b583ec1be865f98b87feb',
    modelType: 'PSSYSVIEWLAYOUTPANEL',
    name: 'layoutpanel',
    id: 'a6af108fc05f471a0b7',
  },
  title: '编辑器_运行时组件',
  viewStyle: 'DEFAULT',
  viewType: 'DEEDITVIEW',
  enableDP: true,
  showCaptionBar: false,
  modelId: '55516cb6ca69f69e116aa7473ffec8a1',
  modelType: 'PSAPPDEVIEW',
  name: 'MASTERRuntime_Components',
  id: 'web.master_runtime_components',
};
