export default {
  deviewCodeName: 'calendar_base',
  deviewId: '97b41486473c6bbc49e84846c0c97384',
  accUserMode: 3,
  capLanguageRes: {
    lanResTag: 'DE.LNAME.MASTER',
  },
  caption: '日历_基础',
  codeName: 'master_calendar_base',
  appDataEntityId: 'web.master',
  appViewMsgGroupId: 'calendar_base',
  viewLayoutPanel: {
    viewProxyMode: true,
    layoutMode: 'FLEX',
    layout: {
      layout: 'FLEX',
    },
    rootPanelItems: [
      {
        actionGroupExtractMode: 'ITEM',
        panelItems: [
          {
            actionGroupExtractMode: 'ITEM',
            panelItems: [
              {
                dataRegionType: 'INHERIT',
                panelTabPages: [
                  {
                    panelItems: [
                      {
                        caption: '日历',
                        itemStyle: 'DEFAULT',
                        itemType: 'CTRLPOS',
                        layoutPos: {
                          shrink: 1,
                          layout: 'FLEX',
                        },
                        showCaption: true,
                        id: 'calendar',
                      },
                    ],
                    layout: {
                      layout: 'FLEX',
                    },
                    dataRegionType: 'INHERIT',
                    caption: '天样式',
                    itemStyle: 'DEFAULT',
                    itemType: 'TABPAGE',
                    layoutPos: {
                      shrink: 1,
                      layout: 'FLEX',
                    },
                    showCaption: true,
                    id: 'tabpage',
                  },
                  {
                    panelItems: [
                      {
                        caption: '日历',
                        itemStyle: 'DEFAULT',
                        itemType: 'CTRLPOS',
                        layoutPos: {
                          shrink: 1,
                          layout: 'FLEX',
                        },
                        showCaption: true,
                        id: 'calendar1',
                      },
                    ],
                    layout: {
                      layout: 'FLEX',
                    },
                    dataRegionType: 'INHERIT',
                    caption: '周样式',
                    itemStyle: 'DEFAULT',
                    itemType: 'TABPAGE',
                    layoutPos: {
                      shrink: 1,
                      layout: 'FLEX',
                    },
                    showCaption: true,
                    id: 'tabpage1',
                  },
                  {
                    panelItems: [
                      {
                        caption: '日历',
                        itemStyle: 'DEFAULT',
                        itemType: 'CTRLPOS',
                        layoutPos: {
                          shrink: 1,
                          layout: 'FLEX',
                        },
                        showCaption: true,
                        id: 'calendar2',
                      },
                    ],
                    layout: {
                      layout: 'FLEX',
                    },
                    dataRegionType: 'INHERIT',
                    caption: '月样式',
                    itemStyle: 'DEFAULT',
                    itemType: 'TABPAGE',
                    layoutPos: {
                      shrink: 1,
                      layout: 'FLEX',
                    },
                    showCaption: true,
                    id: 'tabpage2',
                  },
                  {
                    panelItems: [
                      {
                        caption: '日历',
                        itemStyle: 'DEFAULT',
                        itemType: 'CTRLPOS',
                        layoutPos: {
                          shrink: 1,
                          layout: 'FLEX',
                        },
                        showCaption: true,
                        id: 'calendar3',
                      },
                    ],
                    layout: {
                      layout: 'FLEX',
                    },
                    dataRegionType: 'INHERIT',
                    caption: '时间轴样式',
                    itemStyle: 'DEFAULT',
                    itemType: 'TABPAGE',
                    layoutPos: {
                      shrink: 1,
                      layout: 'FLEX',
                    },
                    showCaption: true,
                    id: 'tabpage3',
                  },
                ],
                caption: '分页部件',
                itemStyle: 'DEFAULT',
                itemType: 'TABPANEL',
                layoutPos: {
                  layoutPos: 'CENTER',
                  layout: 'BORDER',
                  spacingLeft: 'OUTERMEDIUM',
                  spacingRight: 'OUTERMEDIUM',
                },
                id: 'tabpanel',
              },
            ],
            predefinedType: 'CONTAINER_SCROLL_MAIN',
            layout: {
              layout: 'BORDER',
            },
            dataRegionType: 'INHERIT',
            caption: '面板容器',
            itemStyle: 'DEFAULT',
            itemType: 'CONTAINER',
            layoutPos: {
              layoutPos: 'CENTER',
              layout: 'BORDER',
            },
            showCaption: true,
            id: 'container_scroll_main',
          },
        ],
        predefinedType: 'CONTAINER_SCROLL',
        layout: {
          layout: 'BORDER',
        },
        dataRegionType: 'INHERIT',
        caption: '滚动条容器',
        itemStyle: 'DEFAULT',
        itemType: 'CONTAINER',
        layoutPos: {
          shrink: 1,
          layout: 'FLEX',
        },
        id: 'container_scroll',
      },
    ],
    layoutPanel: true,
    controls: [
      {
        calendarStyle: 'DAY',
        groupMode: 'NONE',
        legendPos: 'NONE',
        sysCalendarItems: [
          {
            beginTimeAppDEFieldId: 'date',
            endTimeAppDEFieldId: 'date',
            idAppDEFieldId: 'id',
            itemStyle: 'DEFAULT',
            itemType: 'date',
            appDEDataSetId: 'fetch_default',
            textAppDEFieldId: 'name',
            appDataEntityId: 'web.master',
            id: 'date',
          },
        ],
        navViewPos: 'NONE',
        autoLoad: true,
        showBusyIndicator: true,
        codeName: 'calendar_base_day',
        controlType: 'CALENDAR',
        logicName: '日历_天',
        appDataEntityId: 'web.master',
        controlParam: {
          id: 'calendar',
        },
        modelId: 'bcd9547244a07e917ac9dc6054316a67',
        modelType: 'PSSYSCALENDAR',
        name: 'calendar',
        id: 'web.master.calendar_base_day',
      },
      {
        calendarStyle: 'WEEK',
        groupMode: 'NONE',
        legendPos: 'NONE',
        sysCalendarItems: [
          {
            beginTimeAppDEFieldId: 'date',
            endTimeAppDEFieldId: 'date',
            idAppDEFieldId: 'id',
            itemStyle: 'DEFAULT',
            itemType: 'sj',
            appDEDataSetId: 'fetch_default',
            textAppDEFieldId: 'name',
            appDataEntityId: 'web.master',
            id: 'sj',
          },
        ],
        navViewPos: 'NONE',
        autoLoad: true,
        showBusyIndicator: true,
        codeName: 'calendar_base_week',
        controlType: 'CALENDAR',
        logicName: '日历_周',
        appDataEntityId: 'web.master',
        controlParam: {
          id: 'calendar1',
        },
        modelId: '0cfda61193bba6e9ff986c2f0b19d7d6',
        modelType: 'PSSYSCALENDAR',
        name: 'calendar1',
        id: 'web.master.calendar_base_week',
      },
      {
        calendarStyle: 'MONTH',
        groupMode: 'NONE',
        legendPos: 'NONE',
        sysCalendarItems: [
          {
            beginTimeAppDEFieldId: 'date',
            endTimeAppDEFieldId: 'date',
            idAppDEFieldId: 'id',
            itemStyle: 'DEFAULT',
            itemType: 'sj',
            appDEDataSetId: 'fetch_default',
            textAppDEFieldId: 'name',
            appDataEntityId: 'web.master',
            id: 'sj',
          },
        ],
        navViewPos: 'NONE',
        autoLoad: true,
        showBusyIndicator: true,
        codeName: 'calendar_base_month',
        controlType: 'CALENDAR',
        logicName: '日历_月',
        appDataEntityId: 'web.master',
        controlParam: {
          id: 'calendar2',
        },
        modelId: '2a3e48da517fef07b578b85d29636d93',
        modelType: 'PSSYSCALENDAR',
        name: 'calendar2',
        id: 'web.master.calendar_base_month',
      },
      {
        calendarStyle: 'TIMELINE',
        groupMode: 'NONE',
        legendPos: 'NONE',
        sysCalendarItems: [
          {
            beginTimeAppDEFieldId: 'date',
            endTimeAppDEFieldId: 'date',
            idAppDEFieldId: 'id',
            itemStyle: 'DEFAULT',
            itemType: 'sj',
            appDEDataSetId: 'fetch_default',
            textAppDEFieldId: 'name',
            appDataEntityId: 'web.master',
            id: 'sj',
          },
        ],
        navViewPos: 'NONE',
        autoLoad: true,
        showBusyIndicator: true,
        codeName: 'calendar_base_timeaxis',
        controlType: 'CALENDAR',
        logicName: '日历_时间轴',
        appDataEntityId: 'web.master',
        controlParam: {
          id: 'calendar3',
        },
        modelId: 'c54d198aa4625ed7b7b2197cfa527a16',
        modelType: 'PSSYSCALENDAR',
        name: 'calendar3',
        id: 'web.master.calendar_base_timeaxis',
      },
      {
        capLanguageRes: {
          lanResTag: 'DE.LNAME.MASTER',
        },
        caption: '日历_基础',
        codeName: 'calendar_base_captionbar',
        controlType: 'CAPTIONBAR',
        appDataEntityId: 'web.master',
        controlParam: {},
        name: 'captionbar',
        id: 'calendar_base_captionbar',
      },
    ],
    codeName: 'usr0515376353',
    controlType: 'VIEWLAYOUTPANEL',
    logicName: '日历_基础布局面板',
    appDataEntityId: 'web.master',
    controlParam: {},
    modelId: '1b8a972ad52f565925ba5fe1d1c189e5',
    modelType: 'PSSYSVIEWLAYOUTPANEL',
    name: 'layoutpanel',
    id: 'usr0515376353',
  },
  title: '日历_基础',
  viewStyle: 'DEFAULT',
  viewType: 'DECUSTOMVIEW',
  enableDP: true,
  showCaptionBar: false,
  modelId: '399508903de567cc81f931fcfae71928',
  modelType: 'PSAPPDEVIEW',
  name: 'MASTERcalendar_base',
  id: 'web.master_calendar_base',
};
