export default {
  deviewCodeName: 'calendar_layout',
  deviewId: '12f9b8205a9d8ad628129c55a68d235a',
  accUserMode: 3,
  capLanguageRes: {
    lanResTag: 'DE.LNAME.MASTER',
  },
  caption: '日历_项布局',
  codeName: 'master_calendar_layout',
  appDataEntityId: 'web.master',
  appViewMsgGroupId: 'calendar_layout',
  viewLayoutPanel: {
    viewProxyMode: true,
    layoutMode: 'FLEX',
    layout: {
      layout: 'FLEX',
    },
    rootPanelItems: [
      {
        caption: '日历',
        itemStyle: 'DEFAULT',
        itemType: 'CTRLPOS',
        layoutPos: {
          shrink: 1,
          layout: 'FLEX',
        },
        showCaption: true,
        id: 'calendar',
      },
    ],
    layoutPanel: true,
    controls: [
      {
        calendarStyle: 'MONTH',
        groupMode: 'NONE',
        legendPos: 'NONE',
        sysCalendarItems: [
          {
            beginTimeAppDEFieldId: 'date',
            contentAppDEFieldId: 'name',
            endTimeAppDEFieldId: 'date',
            idAppDEFieldId: 'id',
            itemStyle: 'DEFAULT',
            itemType: 'date',
            appDEDataSetId: 'fetch_default',
            layoutPanel: {
              layoutMode: 'FLEX',
              layout: {
                layout: 'FLEX',
              },
              rootPanelItems: [
                {
                  actionGroupExtractMode: 'ITEM',
                  panelItems: [
                    {
                      actionGroupExtractMode: 'ITEM',
                      panelItems: [
                        {
                          editor: {
                            halign: 'LEFT',
                            renderMode: 'TEXT_DYNAMIC',
                            valign: 'MIDDLE',
                            wrapMode: 'NOWRAP',
                            editorType: 'SPAN',
                            predefinedType: 'FIELD_TEXT_DYNAMIC',
                            valueType: 'SIMPLE',
                            editable: true,
                            id: 'name',
                          },
                          viewFieldName: 'name',
                          allowEmpty: true,
                          caption: '文本(动态)',
                          itemStyle: 'DEFAULT',
                          itemType: 'FIELD',
                          layoutPos: {
                            shrink: 1,
                            layout: 'FLEX',
                          },
                          id: 'name',
                        },
                      ],
                      layout: {
                        layout: 'FLEX',
                      },
                      dataRegionType: 'INHERIT',
                      caption: '容器',
                      itemStyle: 'DEFAULT',
                      itemType: 'CONTAINER',
                      layoutPos: {
                        shrink: 1,
                        layout: 'FLEX',
                      },
                      id: 'container1',
                    },
                  ],
                  layout: {
                    layout: 'FLEX',
                  },
                  dataRegionType: 'INHERIT',
                  caption: '容器',
                  itemStyle: 'DEFAULT',
                  itemType: 'CONTAINER',
                  layoutPos: {
                    shrink: 1,
                    layout: 'FLEX',
                  },
                  id: 'container',
                },
              ],
              layoutPanel: true,
              codeName: 'usr0515490940',
              controlType: 'PANEL',
              logicName: '日历_项布局布局面板',
              appDataEntityId: 'web.master',
              controlParam: {},
              modelId: '46da009e9d82a2836d629283c646fc43',
              modelType: 'PSSYSVIEWPANEL',
              name: 'datelayoutpanel',
              id: 'web.master.usr0515490940',
            },
            textAppDEFieldId: 'name',
            appDataEntityId: 'web.master',
            id: 'date',
          },
        ],
        navViewPos: 'NONE',
        autoLoad: true,
        showBusyIndicator: true,
        codeName: 'calendar_layout',
        controlType: 'CALENDAR',
        logicName: '日历_项布局',
        appDataEntityId: 'web.master',
        controlParam: {
          id: 'calendar',
        },
        modelId: '12f9b8205a9d8ad628129c55a68d235a',
        modelType: 'PSSYSCALENDAR',
        name: 'calendar',
        id: 'web.master.calendar_layout',
      },
      {
        capLanguageRes: {
          lanResTag: 'DE.LNAME.MASTER',
        },
        caption: '日历_项布局',
        codeName: 'calendar_layout_captionbar',
        controlType: 'CAPTIONBAR',
        appDataEntityId: 'web.master',
        controlParam: {},
        name: 'captionbar',
        id: 'calendar_layout_captionbar',
      },
    ],
    codeName: 'auto41559174',
    controlType: 'VIEWLAYOUTPANEL',
    logicName: '日历_项布局视图布局面板',
    appDataEntityId: 'web.master',
    controlParam: {},
    modelId: '45b8a34650cd0b1e82cbb7dba805d39c',
    modelType: 'PSSYSVIEWLAYOUTPANEL',
    name: 'layoutpanel',
    id: 'auto41559174',
  },
  title: '日历_项布局',
  viewStyle: 'DEFAULT',
  viewType: 'DECUSTOMVIEW',
  enableDP: true,
  showCaptionBar: false,
  modelId: '168379768a77b050af8649bac226e4f0',
  modelType: 'PSAPPDEVIEW',
  name: 'MASTERcalendar_layout',
  id: 'web.master_calendar_layout',
};
