export default {
  sideBarLayout: 'LEFT',
  showDataInfoBar: true,
  loadDefault: true,
  deviewCodeName: 'calendar_exp_view',
  deviewId: '61e38e357dd4e3ba692649cad72d6e85',
  accUserMode: 3,
  capLanguageRes: {
    lanResTag: 'DE.LNAME.MASTER',
  },
  caption: '日历导航',
  codeName: 'master_calendar_exp_view',
  appDataEntityId: 'web.master',
  appViewEngines: [
    {
      engineCat: 'VIEW',
      engineType: 'CalendarExpView',
      id: 'engine',
    },
  ],
  appViewLogics: [
    {
      logicTrigger: 'CUSTOM',
      logicType: 'APPUILOGIC',
      builtinAppUILogic: {
        actionAfterWizard: 'DEFAULT',
        builtinLogic: true,
        logicType: 'PREDEFINED',
        viewLogicType: 'APP_NEWDATA',
        id: '新建数据',
      },
      builtinLogic: true,
      id: 'newdata',
    },
    {
      logicTrigger: 'CUSTOM',
      logicType: 'APPUILOGIC',
      builtinAppUILogic: {
        editMode: true,
        builtinLogic: true,
        logicType: 'PREDEFINED',
        viewLogicType: 'APP_OPENDATA',
        id: '打开数据',
      },
      builtinLogic: true,
      id: 'opendata',
    },
  ],
  appViewMsgGroupId: 'calendar_exp_view_group',
  controls: [
    {
      xdataControlName: 'calendarexpbar_calendar',
      enableCounter: true,
      showTitleBar: true,
      autoLoad: true,
      showBusyIndicator: true,
      appViewRefs: [
        {
          realTitle: '详细信息',
          refAppViewId: 'web.master_info_view',
          name: 'EXPITEM:master',
          id: 'expitem:master',
        },
      ],
      controls: [
        {
          calendarStyle: 'MONTH',
          groupMode: 'NONE',
          legendPos: 'NONE',
          sysCalendarItems: [
            {
              beginTimeAppDEFieldId: 'create_time',
              endTimeAppDEFieldId: 'create_time',
              idAppDEFieldId: 'id',
              itemStyle: 'DEFAULT',
              itemType: 'master',
              appDEDataSetId: 'fetch_default',
              textAppDEFieldId: 'name',
              appDataEntityId: 'web.master',
              navAppViewId: 'web.master_info_view',
              name: '主数据',
              id: 'master',
            },
          ],
          navViewPos: 'NONE',
          autoLoad: true,
          showBusyIndicator: true,
          codeName: 'calendar_exp_view_calendar',
          controlType: 'CALENDAR',
          logicName: '日历导航视图_日历部件',
          appDataEntityId: 'web.master',
          controlLogics: [
            {
              eventNames: 'SELECTIONCHANGE',
              logicTag: 'calendarexpbar_calendar',
              logicType: 'CUSTOM',
              triggerType: 'CTRLEVENT',
              id: 'calendarexpbar_selectionchange',
            },
            {
              eventNames: 'LOAD',
              logicTag: 'calendarexpbar_calendar',
              logicType: 'CUSTOM',
              triggerType: 'CTRLEVENT',
              id: 'calendarexpbar_load',
            },
          ],
          controlParam: {
            id: 'calendarexpbar_calendar',
          },
          modelId: '7f036ed411c792f20c9180850e73935d',
          modelType: 'PSSYSCALENDAR',
          name: 'calendarexpbar_calendar',
          id: 'web.master.calendar_exp_view_calendar',
        },
      ],
      codeName: 'calendar_exp_view_calendarexpbar',
      controlType: 'CALENDAREXPBAR',
      appDataEntityId: 'web.master',
      controlParam: {
        id: 'calendarexpbar',
      },
      modelId: '0e68d5926fba8df3896bda6e231986a2_calendarexpbar',
      modelType: 'PSEXPBAR',
      name: 'calendarexpbar',
      id: 'calendar_exp_view_calendarexpbar',
    },
    {
      groupMode: 'SINGLE',
      quickSearchMode: 1,
      enableQuickSearch: true,
      controlType: 'SEARCHBAR',
      appDataEntityId: 'web.master',
      controlParam: {
        id: 'searchbar',
      },
      id: 'searchbar',
    },
    {
      capLanguageRes: {
        lanResTag: 'DE.LNAME.MASTER',
      },
      caption: '日历导航',
      codeName: 'calendar_exp_view_captionbar',
      controlType: 'CAPTIONBAR',
      appDataEntityId: 'web.master',
      controlParam: {},
      name: 'captionbar',
      id: 'calendar_exp_view_captionbar',
    },
  ],
  viewLayoutPanel: {
    layoutBodyOnly: true,
    useDefaultLayout: true,
    layoutPanel: true,
    codeName: 'layoutpanel',
    controlStyle: 'APPDECALENDAREXPVIEW',
    controlType: 'VIEWLAYOUTPANEL',
    appDataEntityId: 'web.master',
    controlParam: {},
    id: 'layoutpanel',
  },
  title: '日历导航',
  viewStyle: 'DEFAULT',
  viewType: 'DECALENDAREXPVIEW',
  enableDP: true,
  showCaptionBar: false,
  modelId: '0e68d5926fba8df3896bda6e231986a2',
  modelType: 'PSAPPDEVIEW',
  name: 'MASTERcalendar_exp_view',
  id: 'web.master_calendar_exp_view',
};
