export default {
  mdctrlActiveMode: 2,
  xdataControlName: 'map',
  loadDefault: true,
  deviewCodeName: 'map_view',
  deviewId: '7cdccf9e40a7c8e90609e684bc98f927',
  accUserMode: 3,
  capLanguageRes: {
    lanResTag: 'DE.LNAME.MASTER',
  },
  caption: '地图视图',
  codeName: 'master_map_view',
  appDataEntityId: 'web.master',
  appViewLogics: [
    {
      logicTrigger: 'CUSTOM',
      logicType: 'APPUILOGIC',
      builtinAppUILogic: {
        actionAfterWizard: 'DEFAULT',
        newDataAppView: {
          openMode: 'POPUPMODAL',
          refAppViewId: 'web.master_edit_view',
        },
        appUILogicRefViews: [
          {
            openMode: 'POPUPMODAL',
            refAppViewId: 'web.master_edit_view',
          },
        ],
        builtinLogic: true,
        logicType: 'PREDEFINED',
        viewLogicType: 'APP_NEWDATA',
        id: '新建数据',
      },
      builtinLogic: true,
      id: 'newdata',
    },
    {
      logicTrigger: 'CUSTOM',
      logicType: 'APPUILOGIC',
      builtinAppUILogic: {
        openDataAppView: {
          openMode: 'POPUPMODAL',
          refAppViewId: 'web.master_edit_view',
        },
        editMode: true,
        appUILogicRefViews: [
          {
            openMode: 'POPUPMODAL',
            refAppViewId: 'web.master_edit_view',
          },
        ],
        builtinLogic: true,
        logicType: 'PREDEFINED',
        viewLogicType: 'APP_OPENDATA',
        id: '打开数据',
      },
      builtinLogic: true,
      id: 'opendata',
    },
  ],
  appViewMsgGroupId: 'map_view_group',
  appViewRefs: [
    {
      realOpenMode: 'POPUPMODAL',
      realTitle: '主数据编辑视图',
      refAppViewId: 'web.master_edit_view',
      name: 'NEWDATA',
      id: 'newdata',
    },
    {
      realOpenMode: 'POPUPMODAL',
      realTitle: '主数据编辑视图',
      refAppViewId: 'web.master_edit_view',
      name: 'EDITDATA',
      id: 'editdata',
    },
  ],
  controls: [
    {
      legendPos: 'NONE',
      sysMapItems: [
        {
          idAppDEFieldId: 'id',
          itemStyle: 'POINT',
          itemType: 'region',
          latitudeAppDEFieldId: 'latitude',
          longitudeAppDEFieldId: 'longitude',
          appDEDataSetId: 'fetch_default',
          appDataEntityId: 'web.region',
          textAppDEFieldId: 'name',
          name: '地区',
          id: 'region',
        },
      ],
      navViewPos: 'NONE',
      autoLoad: true,
      showBusyIndicator: true,
      codeName: 'map_view_map_view',
      controlType: 'MAP',
      logicName: '地图视图_地图部件',
      appDataEntityId: 'web.master',
      controlParam: {
        id: 'map',
      },
      modelId: 'a9ad47fc7fe97b4a9c8499d8f9dc5ccb',
      modelType: 'PSSYSMAPVIEW',
      name: 'map',
      id: 'web.master.map_view_map_view',
    },
    {
      groupMode: 'SINGLE',
      controlType: 'SEARCHBAR',
      appDataEntityId: 'web.master',
      controlParam: {
        id: 'searchbar',
      },
      id: 'searchbar',
    },
    {
      capLanguageRes: {
        lanResTag: 'DE.LNAME.MASTER',
      },
      caption: '地图视图',
      codeName: 'map_view_captionbar',
      controlType: 'CAPTIONBAR',
      appDataEntityId: 'web.master',
      controlParam: {},
      name: 'captionbar',
      id: 'map_view_captionbar',
    },
  ],
  viewLayoutPanel: {
    layoutBodyOnly: true,
    useDefaultLayout: true,
    layoutPanel: true,
    codeName: 'layoutpanel',
    controlStyle: 'APPDEMAPVIEW',
    controlType: 'VIEWLAYOUTPANEL',
    appDataEntityId: 'web.master',
    controlParam: {},
    id: 'layoutpanel',
  },
  title: '地图视图',
  viewStyle: 'DEFAULT',
  viewType: 'DEMAPVIEW',
  enableDP: true,
  showCaptionBar: false,
  modelId: '80dee9b3351c8887d2f1235f6bad9413',
  modelType: 'PSAPPDEVIEW',
  name: 'MASTERmap_view',
  id: 'web.master_map_view',
};
