export default {
  deviewCodeName: 'panel_logic',
  deviewId: '6ebc2c349479c61b6a8ea093f969ed3f',
  accUserMode: 3,
  capLanguageRes: {
    lanResTag: 'DE.LNAME.MASTER',
  },
  caption: '面板_逻辑',
  codeName: 'master_panel_logic',
  appDataEntityId: 'web.master',
  appViewMsgGroupId: 'panel_logic',
  viewLayoutPanel: {
    viewProxyMode: true,
    layoutMode: 'FLEX',
    layout: {
      layout: 'FLEX',
    },
    rootPanelItems: [
      {
        actionGroupExtractMode: 'ITEM',
        panelItems: [
          {
            actionGroupExtractMode: 'ITEM',
            panelItems: [
              {
                actionGroupExtractMode: 'ITEM',
                panelItems: [
                  {
                    actionGroupExtractMode: 'ITEM',
                    panelItems: [
                      {
                        actionGroupExtractMode: 'ITEM',
                        panelItems: [
                          {
                            rawItem: {
                              caption: '名称',
                              halign: 'LEFT',
                              renderMode: 'PARAGRAPH',
                              valign: 'MIDDLE',
                              wrapMode: 'NOWRAP',
                              contentType: 'RAW',
                              predefinedType: 'STATIC_LABEL',
                              rawItemWidth: 120,
                              id: 'static_label',
                            },
                            caption: '标签',
                            contentWidth: 120,
                            itemStyle: 'DEFAULT',
                            itemType: 'RAWITEM',
                            layoutPos: {
                              shrink: 1,
                              halignSelf: 'RIGHT',
                              layout: 'FLEX',
                              spacingRight: 'INNERSMALL',
                              width: 120,
                              widthMode: 'PX',
                            },
                            width: 120,
                            showCaption: true,
                            id: 'static_label',
                          },
                          {
                            editor: {
                              halign: 'LEFT',
                              renderMode: 'TEXT_DYNAMIC',
                              valign: 'MIDDLE',
                              wrapMode: 'NOWRAP',
                              editorType: 'SPAN',
                              predefinedType: 'FIELD_TEXT_DYNAMIC',
                              valueType: 'SIMPLE',
                              editable: true,
                              id: 'field_text_dynamic',
                            },
                            viewFieldName: 'name',
                            allowEmpty: true,
                            caption: '文本(动态)',
                            itemStyle: 'DEFAULT',
                            itemType: 'FIELD',
                            layoutPos: {
                              shrink: 1,
                              layout: 'FLEX',
                            },
                            panelItemGroupLogics: [
                              {
                                logicCat: 'PANELVISIBLE',
                                relatedItemNames: ['switch_show'],
                                groupOP: 'AND',
                                panelItemLogics: [
                                  {
                                    condOp: 'EQ',
                                    dstModelField: 'switch_show',
                                    value: '1',
                                    logicType: 'SINGLE',
                                    id: 'switch_show 等于(=) 1',
                                  },
                                ],
                                logicType: 'GROUP',
                              },
                            ],
                            id: 'field_text_dynamic',
                          },
                        ],
                        layout: {
                          dir: 'row',
                          layout: 'FLEX',
                          valign: 'center',
                        },
                        dataRegionType: 'INHERIT',
                        caption: '容器',
                        itemStyle: 'DEFAULT',
                        itemType: 'CONTAINER',
                        layoutPos: {
                          shrink: 1,
                          layout: 'FLEX',
                        },
                        id: 'container1',
                      },
                      {
                        actionGroupExtractMode: 'ITEM',
                        panelItems: [
                          {
                            rawItem: {
                              caption: '切换显示状态',
                              halign: 'LEFT',
                              renderMode: 'PARAGRAPH',
                              valign: 'MIDDLE',
                              wrapMode: 'NOWRAP',
                              contentType: 'RAW',
                              predefinedType: 'STATIC_LABEL',
                              rawItemWidth: 120,
                              id: 'static_label1',
                            },
                            caption: '标签',
                            contentWidth: 120,
                            itemStyle: 'DEFAULT',
                            itemType: 'RAWITEM',
                            layoutPos: {
                              shrink: 1,
                              halignSelf: 'RIGHT',
                              layout: 'FLEX',
                              spacingRight: 'INNERSMALL',
                              width: 120,
                              widthMode: 'PX',
                            },
                            width: 120,
                            showCaption: true,
                            id: 'static_label1',
                          },
                          {
                            editor: {
                              editorType: 'SWITCH',
                              predefinedType: 'FIELD_SWITCH',
                              valueType: 'SIMPLE',
                              editable: true,
                              id: 'switch_show',
                            },
                            viewFieldName: 'enable',
                            allowEmpty: true,
                            caption: '开关',
                            itemStyle: 'DEFAULT',
                            itemType: 'FIELD',
                            layoutPos: {
                              shrink: 1,
                              layout: 'FLEX',
                            },
                            id: 'switch_show',
                          },
                        ],
                        layout: {
                          dir: 'row',
                          layout: 'FLEX',
                          valign: 'center',
                        },
                        dataRegionType: 'INHERIT',
                        caption: '容器',
                        itemStyle: 'DEFAULT',
                        itemType: 'CONTAINER',
                        layoutPos: {
                          shrink: 1,
                          layout: 'FLEX',
                        },
                        id: 'container2',
                      },
                    ],
                    layout: {
                      align: 'flex-start',
                      dir: 'column',
                      layout: 'FLEX',
                    },
                    dataRegionType: 'INHERIT',
                    caption: '容器',
                    itemStyle: 'DEFAULT',
                    itemType: 'CONTAINER',
                    layoutPos: {
                      shrink: 1,
                      layout: 'FLEX',
                    },
                    id: 'container',
                  },
                ],
                predefinedType: 'CONTAINER_SINGLEDATA',
                layout: {
                  layout: 'FLEX',
                },
                dataRegionType: 'SINGLEDATA',
                dataSourceType: 'DEACTION',
                appDEMethodId: 'get_sample_date',
                appDataEntityId: 'web.master',
                caption: '单项数据容器',
                itemStyle: 'DEFAULT',
                itemType: 'CONTAINER',
                layoutPos: {
                  shrink: 1,
                  layout: 'FLEX',
                },
                id: 'container_singledata',
              },
            ],
            predefinedType: 'CONTAINER_GROUP',
            layout: {
              layout: 'FLEX',
            },
            dataRegionType: 'INHERIT',
            caption: '动态显示',
            itemStyle: 'DEFAULT',
            itemType: 'CONTAINER',
            layoutPos: {
              shrink: 1,
              layout: 'FLEX',
            },
            showCaption: true,
            id: 'container_group',
          },
          {
            actionGroupExtractMode: 'ITEM',
            panelItems: [
              {
                actionGroupExtractMode: 'ITEM',
                panelItems: [
                  {
                    actionGroupExtractMode: 'ITEM',
                    panelItems: [
                      {
                        actionGroupExtractMode: 'ITEM',
                        panelItems: [
                          {
                            rawItem: {
                              caption: '名称',
                              halign: 'LEFT',
                              renderMode: 'PARAGRAPH',
                              valign: 'MIDDLE',
                              wrapMode: 'NOWRAP',
                              contentType: 'RAW',
                              predefinedType: 'STATIC_LABEL',
                              rawItemWidth: 120,
                              id: 'static_label2',
                            },
                            caption: '标签',
                            contentWidth: 120,
                            itemStyle: 'DEFAULT',
                            itemType: 'RAWITEM',
                            layoutPos: {
                              shrink: 1,
                              halignSelf: 'RIGHT',
                              layout: 'FLEX',
                              spacingRight: 'INNERSMALL',
                              width: 120,
                              widthMode: 'PX',
                            },
                            width: 120,
                            showCaption: true,
                            id: 'static_label2',
                          },
                          {
                            editor: {
                              editorType: 'TEXTBOX',
                              predefinedType: 'FIELD_TEXTBOX',
                              valueType: 'SIMPLE',
                              editable: true,
                              id: 'field_textbox',
                            },
                            viewFieldName: 'name',
                            allowEmpty: true,
                            caption: '文本框',
                            itemStyle: 'DEFAULT',
                            itemType: 'FIELD',
                            layoutPos: {
                              shrink: 1,
                              layout: 'FLEX',
                            },
                            panelItemGroupLogics: [
                              {
                                logicCat: 'ITEMENABLE',
                                relatedItemNames: ['switch_enable'],
                                groupOP: 'AND',
                                panelItemLogics: [
                                  {
                                    condOp: 'EQ',
                                    dstModelField: 'switch_enable',
                                    value: '1',
                                    logicType: 'SINGLE',
                                    id: 'switch_enable 等于(=) 1',
                                  },
                                ],
                                logicType: 'GROUP',
                              },
                            ],
                            id: 'field_textbox',
                          },
                        ],
                        layout: {
                          dir: 'row',
                          layout: 'FLEX',
                          valign: 'center',
                        },
                        dataRegionType: 'INHERIT',
                        caption: '容器',
                        itemStyle: 'DEFAULT',
                        itemType: 'CONTAINER',
                        layoutPos: {
                          shrink: 1,
                          layout: 'FLEX',
                        },
                        id: 'container4',
                      },
                      {
                        actionGroupExtractMode: 'ITEM',
                        panelItems: [
                          {
                            rawItem: {
                              caption: '切换启用状态',
                              halign: 'LEFT',
                              renderMode: 'PARAGRAPH',
                              valign: 'MIDDLE',
                              wrapMode: 'NOWRAP',
                              contentType: 'RAW',
                              predefinedType: 'STATIC_LABEL',
                              rawItemWidth: 120,
                              id: 'static_label3',
                            },
                            caption: '标签',
                            contentWidth: 120,
                            itemStyle: 'DEFAULT',
                            itemType: 'RAWITEM',
                            layoutPos: {
                              shrink: 1,
                              halignSelf: 'RIGHT',
                              layout: 'FLEX',
                              spacingRight: 'INNERSMALL',
                              width: 120,
                              widthMode: 'PX',
                            },
                            width: 120,
                            showCaption: true,
                            id: 'static_label3',
                          },
                          {
                            editor: {
                              editorType: 'SWITCH',
                              predefinedType: 'FIELD_SWITCH',
                              valueType: 'SIMPLE',
                              editable: true,
                              id: 'switch_enable',
                            },
                            viewFieldName: 'enable',
                            allowEmpty: true,
                            caption: '开关',
                            itemStyle: 'DEFAULT',
                            itemType: 'FIELD',
                            layoutPos: {
                              shrink: 1,
                              layout: 'FLEX',
                            },
                            id: 'switch_enable',
                          },
                        ],
                        layout: {
                          dir: 'row',
                          layout: 'FLEX',
                          valign: 'center',
                        },
                        dataRegionType: 'INHERIT',
                        caption: '容器',
                        itemStyle: 'DEFAULT',
                        itemType: 'CONTAINER',
                        layoutPos: {
                          shrink: 1,
                          layout: 'FLEX',
                        },
                        id: 'container5',
                      },
                    ],
                    layout: {
                      align: 'flex-start',
                      dir: 'column',
                      layout: 'FLEX',
                    },
                    dataRegionType: 'INHERIT',
                    caption: '容器',
                    itemStyle: 'DEFAULT',
                    itemType: 'CONTAINER',
                    layoutPos: {
                      shrink: 1,
                      layout: 'FLEX',
                    },
                    id: 'container3',
                  },
                ],
                predefinedType: 'CONTAINER_SINGLEDATA',
                layout: {
                  layout: 'FLEX',
                },
                dataRegionType: 'SINGLEDATA',
                dataSourceType: 'DEACTION',
                appDEMethodId: 'get_sample_date',
                appDataEntityId: 'web.master',
                caption: '单项数据容器',
                itemStyle: 'DEFAULT',
                itemType: 'CONTAINER',
                layoutPos: {
                  shrink: 1,
                  layout: 'FLEX',
                },
                id: 'container_singledata1',
              },
            ],
            predefinedType: 'CONTAINER_GROUP',
            layout: {
              layout: 'FLEX',
            },
            dataRegionType: 'INHERIT',
            caption: '动态启用',
            itemStyle: 'DEFAULT',
            itemType: 'CONTAINER',
            layoutPos: {
              shrink: 1,
              layout: 'FLEX',
            },
            showCaption: true,
            id: 'container_group1',
          },
          {
            actionGroupExtractMode: 'ITEM',
            panelItems: [
              {
                actionGroupExtractMode: 'ITEM',
                panelItems: [
                  {
                    actionGroupExtractMode: 'ITEM',
                    panelItems: [
                      {
                        rawItem: {
                          caption: '名称',
                          halign: 'LEFT',
                          renderMode: 'PARAGRAPH',
                          valign: 'MIDDLE',
                          wrapMode: 'NOWRAP',
                          contentType: 'RAW',
                          predefinedType: 'STATIC_LABEL',
                          rawItemWidth: 120,
                          id: 'static_label4',
                        },
                        caption: '名称',
                        contentWidth: 120,
                        itemStyle: 'DEFAULT',
                        itemType: 'RAWITEM',
                        layoutPos: {
                          shrink: 1,
                          halignSelf: 'RIGHT',
                          layout: 'FLEX',
                          spacingRight: 'INNERSMALL',
                          width: 120,
                          widthMode: 'PX',
                        },
                        width: 120,
                        showCaption: true,
                        id: 'static_label4',
                      },
                      {
                        editor: {
                          editorType: 'TEXTBOX',
                          predefinedType: 'FIELD_TEXT_DYNAMIC',
                          valueType: 'SIMPLE',
                          editable: true,
                          id: 'field_text_dynamic1',
                        },
                        viewFieldName: 'name',
                        allowEmpty: true,
                        caption: '文本(动态)',
                        itemStyle: 'DEFAULT',
                        itemType: 'FIELD',
                        layoutPos: {
                          shrink: 1,
                          layout: 'FLEX',
                        },
                        panelItemGroupLogics: [
                          {
                            logicCat: 'ITEMBLANK',
                            relatedItemNames: ['switch_empty'],
                            groupOP: 'AND',
                            panelItemLogics: [
                              {
                                condOp: 'EQ',
                                dstModelField: 'switch_empty',
                                value: '1',
                                logicType: 'SINGLE',
                                id: 'switch_empty 等于(=) 1',
                              },
                            ],
                            logicType: 'GROUP',
                          },
                        ],
                        id: 'field_text_dynamic1',
                      },
                    ],
                    layout: {
                      dir: 'row',
                      layout: 'FLEX',
                      valign: 'center',
                    },
                    dataRegionType: 'INHERIT',
                    caption: '容器',
                    itemStyle: 'DEFAULT',
                    itemType: 'CONTAINER',
                    layoutPos: {
                      shrink: 1,
                      layout: 'FLEX',
                    },
                    id: 'container6',
                  },
                  {
                    actionGroupExtractMode: 'ITEM',
                    panelItems: [
                      {
                        rawItem: {
                          caption: '切换空输入状态',
                          halign: 'LEFT',
                          renderMode: 'PARAGRAPH',
                          valign: 'MIDDLE',
                          wrapMode: 'NOWRAP',
                          contentType: 'RAW',
                          predefinedType: 'STATIC_LABEL',
                          rawItemWidth: 120,
                          id: 'static_label5',
                        },
                        caption: '切换空输入状态',
                        contentWidth: 120,
                        itemStyle: 'DEFAULT',
                        itemType: 'RAWITEM',
                        layoutPos: {
                          shrink: 1,
                          halignSelf: 'RIGHT',
                          layout: 'FLEX',
                          spacingRight: 'INNERSMALL',
                          width: 120,
                          widthMode: 'PX',
                        },
                        width: 120,
                        showCaption: true,
                        id: 'static_label5',
                      },
                      {
                        editor: {
                          editorType: 'SWITCH',
                          predefinedType: 'FIELD_SWITCH',
                          valueType: 'SIMPLE',
                          editable: true,
                          id: 'switch_empty',
                        },
                        viewFieldName: 'enable',
                        allowEmpty: true,
                        caption: '开关',
                        itemStyle: 'DEFAULT',
                        itemType: 'FIELD',
                        layoutPos: {
                          shrink: 1,
                          layout: 'FLEX',
                        },
                        id: 'switch_empty',
                      },
                    ],
                    layout: {
                      dir: 'row',
                      layout: 'FLEX',
                      valign: 'center',
                    },
                    dataRegionType: 'INHERIT',
                    caption: '容器',
                    itemStyle: 'DEFAULT',
                    itemType: 'CONTAINER',
                    layoutPos: {
                      shrink: 1,
                      layout: 'FLEX',
                    },
                    id: 'container7',
                  },
                ],
                predefinedType: 'CONTAINER_SINGLEDATA',
                layout: {
                  layout: 'FLEX',
                },
                dataRegionType: 'SINGLEDATA',
                dataSourceType: 'DEACTION',
                appDEMethodId: 'get_sample_date',
                appDataEntityId: 'web.master',
                caption: '单项数据容器',
                itemStyle: 'DEFAULT',
                itemType: 'CONTAINER',
                layoutPos: {
                  shrink: 1,
                  layout: 'FLEX',
                },
                id: 'container_singledata2',
              },
            ],
            predefinedType: 'CONTAINER_GROUP',
            layout: {
              layout: 'FLEX',
            },
            dataRegionType: 'INHERIT',
            caption: '动态空输入',
            itemStyle: 'DEFAULT',
            itemType: 'CONTAINER',
            layoutPos: {
              shrink: 1,
              layout: 'FLEX',
            },
            showCaption: true,
            id: 'container_group2',
          },
        ],
        layout: {
          dir: 'column',
          layout: 'FLEX',
        },
        dataRegionType: 'INHERIT',
        itemStyle: 'DEFAULT',
        itemType: 'CONTAINER',
        layoutPos: {
          shrink: 1,
          layout: 'FLEX',
        },
        id: 'page_container',
      },
    ],
    layoutPanel: true,
    controls: [
      {
        capLanguageRes: {
          lanResTag: 'DE.LNAME.MASTER',
        },
        caption: '面板_逻辑',
        codeName: 'panel_logic_captionbar',
        controlType: 'CAPTIONBAR',
        appDataEntityId: 'web.master',
        controlParam: {},
        name: 'captionbar',
        id: 'panel_logic_captionbar',
      },
    ],
    codeName: 'usr0516516675',
    controlType: 'VIEWLAYOUTPANEL',
    logicName: '面板_逻辑布局面板',
    appDataEntityId: 'web.master',
    controlParam: {},
    modelId: 'b2894475e5363ff07cd3487c90b39216',
    modelType: 'PSSYSVIEWLAYOUTPANEL',
    name: 'layoutpanel',
    id: 'usr0516516675',
  },
  title: '面板_逻辑',
  viewStyle: 'DEFAULT',
  viewType: 'DECUSTOMVIEW',
  enableDP: true,
  showCaptionBar: false,
  modelId: '5c7e0c81446dff2b127c120abc9ae5a0',
  modelType: 'PSAPPDEVIEW',
  name: 'MASTERpanel_logic',
  id: 'web.master_panel_logic',
};
