export default {
  enableSearch: true,
  expandSearchForm: true,
  loadDefault: true,
  deviewCodeName: 'report_view',
  deviewId: '2ae385c088612f9b2cd2bc1b05f0734e',
  accUserMode: 3,
  capLanguageRes: {
    lanResTag: 'DE.LNAME.MASTER',
  },
  caption: '报表视图',
  codeName: 'master_report_view',
  appDataEntityId: 'web.master',
  controls: [
    {
      searchButtonStyle: 'DEFAULT',
      deformPages: [
        {
          layout: {
            columnCount: 24,
            layout: 'TABLE_24COL',
          },
          caption: '常规条件',
          codeName: 'formpage1',
          detailStyle: 'DEFAULT',
          detailType: 'FORMPAGE',
          id: 'formpage1',
        },
      ],
      layout: {
        columnCount: 24,
        layout: 'TABLE_24COL',
      },
      tabHeaderPos: 'TOP',
      noTabHeader: true,
      autoLoad: true,
      showBusyIndicator: true,
      codeName: 'report_view_search_form',
      controlType: 'SEARCHFORM',
      logicName: '报表视图_搜索表单',
      appDataEntityId: 'web.master',
      controlParam: {
        id: 'searchform',
      },
      modelId: '80f9671ab8916ad67e3dc9d9be230654',
      modelType: 'PSDEFORM_SEARCHFORM',
      name: 'searchform',
      id: 'web.master.report_view_search_form',
    },
    {
      appDEReport: {
        codeName: 'report_view_Report',
        reportType: 'MARKDOWN',
        appDEDataSetId: 'fetch_default',
        name: 'Report',
        id: 'report_view_report',
      },
      codeName: 'report_view_report',
      controlType: 'REPORTPANEL',
      logicName: 'Report',
      appDataEntityId: 'web.master',
      controlParam: {
        id: 'reportpanel',
      },
      modelId: 'ca19927e5a222f1e2bcb9a8799b7757b',
      modelType: 'PSDEREPORTPANEL',
      name: 'reportpanel',
      id: 'web.master.report_view_report',
    },
    {
      capLanguageRes: {
        lanResTag: 'DE.LNAME.MASTER',
      },
      caption: '报表视图',
      codeName: 'report_view_captionbar',
      controlType: 'CAPTIONBAR',
      appDataEntityId: 'web.master',
      controlParam: {},
      name: 'captionbar',
      id: 'report_view_captionbar',
    },
  ],
  viewLayoutPanel: {
    layoutBodyOnly: true,
    useDefaultLayout: true,
    layoutPanel: true,
    codeName: 'layoutpanel',
    controlStyle: 'APPDEREPORTVIEW',
    controlType: 'VIEWLAYOUTPANEL',
    appDataEntityId: 'web.master',
    controlParam: {},
    id: 'layoutpanel',
  },
  title: '报表视图',
  viewStyle: 'DEFAULT',
  viewType: 'DEREPORTVIEW',
  enableDP: true,
  showCaptionBar: true,
  modelId: '2d498270a8f7b49d8e05499a99a51296',
  modelType: 'PSAPPDEVIEW',
  name: 'MASTERreport_view',
  id: 'web.master_report_view',
};
