export default {
  deviewCodeName: 'toolbar_style',
  deviewId: 'c2dda65ef30e3c939e55e30449528316',
  accUserMode: 3,
  capLanguageRes: {
    lanResTag: 'DE.LNAME.MASTER',
  },
  caption: '工具栏_样式',
  codeName: 'master_toolbar_style',
  appDataEntityId: 'web.master',
  appViewMsgGroupId: 'toolbar_style',
  viewLayoutPanel: {
    viewProxyMode: true,
    layoutMode: 'FLEX',
    layout: {
      layout: 'FLEX',
    },
    rootPanelItems: [
      {
        actionGroupExtractMode: 'ITEM',
        panelItems: [
          {
            actionGroupExtractMode: 'ITEM',
            panelItems: [
              {
                actionGroupExtractMode: 'ITEM',
                panelItems: [
                  {
                    actionGroupExtractMode: 'ITEM',
                    panelItems: [
                      {
                        caption: '工具栏',
                        itemStyle: 'DEFAULT',
                        itemType: 'CTRLPOS',
                        layoutPos: {
                          shrink: 1,
                          layout: 'FLEX',
                        },
                        showCaption: true,
                        id: 'toolbar',
                      },
                    ],
                    layout: {
                      layout: 'FLEX',
                    },
                    dataRegionType: 'INHERIT',
                    caption: '容器',
                    itemStyle: 'DEFAULT',
                    itemType: 'CONTAINER',
                    layoutPos: {
                      shrink: 1,
                      layout: 'FLEX',
                    },
                    id: 'container',
                  },
                ],
                predefinedType: 'CONTAINER_GROUP',
                layout: {
                  layout: 'FLEX',
                },
                dataRegionType: 'INHERIT',
                caption: '样式',
                itemStyle: 'DEFAULT',
                itemType: 'CONTAINER',
                layoutPos: {
                  layoutPos: 'CENTER',
                  layout: 'BORDER',
                },
                showCaption: true,
                id: 'container_group',
              },
              {
                actionGroupExtractMode: 'ITEM',
                panelItems: [
                  {
                    actionGroupExtractMode: 'ITEM',
                    panelItems: [
                      {
                        caption: '工具栏',
                        itemStyle: 'DEFAULT',
                        itemType: 'CTRLPOS',
                        layoutPos: {
                          shrink: 1,
                          layout: 'FLEX',
                        },
                        showCaption: true,
                        id: 'toolbar1',
                      },
                    ],
                    layout: {
                      layout: 'FLEX',
                    },
                    dataRegionType: 'INHERIT',
                    caption: '容器',
                    itemStyle: 'DEFAULT',
                    itemType: 'CONTAINER',
                    layoutPos: {
                      shrink: 1,
                      layout: 'FLEX',
                    },
                    id: 'container1',
                  },
                ],
                predefinedType: 'CONTAINER_GROUP',
                layout: {
                  layout: 'FLEX',
                },
                dataRegionType: 'INHERIT',
                caption: '图标',
                itemStyle: 'DEFAULT',
                itemType: 'CONTAINER',
                layoutPos: {
                  layoutPos: 'CENTER',
                  layout: 'BORDER',
                },
                showCaption: true,
                id: 'container_group1',
              },
            ],
            predefinedType: 'CONTAINER_SCROLL_MAIN',
            layout: {
              layout: 'BORDER',
            },
            dataRegionType: 'INHERIT',
            caption: '面板容器',
            itemStyle: 'DEFAULT',
            itemType: 'CONTAINER',
            layoutPos: {
              layoutPos: 'CENTER',
              layout: 'BORDER',
            },
            showCaption: true,
            id: 'container_scroll_main',
          },
        ],
        predefinedType: 'CONTAINER_SCROLL',
        layout: {
          layout: 'BORDER',
        },
        dataRegionType: 'INHERIT',
        caption: '滚动条容器',
        itemStyle: 'DEFAULT',
        itemType: 'CONTAINER',
        layoutPos: {
          shrink: 1,
          layout: 'FLEX',
        },
        id: 'container_scroll',
      },
    ],
    layoutPanel: true,
    controls: [
      {
        detoolbarItems: [
          {
            actionLevel: 100,
            noPrivDisplayMode: 2,
            uiactionId: 'open_dialog@master',
            uiactionTarget: 'NONE',
            valid: true,
            caption: '界面行为1',
            itemType: 'DEUIACTION',
            tooltip: '界面行为1',
            showCaption: true,
            showIcon: true,
            id: 'deuiaction1',
          },
          {
            actionLevel: 100,
            noPrivDisplayMode: 2,
            uiactionId: 'open_dialog@master',
            uiactionTarget: 'NONE',
            valid: true,
            caption: '界面行为2',
            itemType: 'DEUIACTION',
            tooltip: '界面行为2',
            showCaption: true,
            showIcon: true,
            id: 'deuiaction2',
          },
          {
            actionLevel: 100,
            noPrivDisplayMode: 2,
            uiactionId: 'open_dialog@master',
            uiactionTarget: 'NONE',
            valid: true,
            caption: '界面行为3',
            itemType: 'DEUIACTION',
            tooltip: '界面行为3',
            showCaption: true,
            showIcon: true,
            id: 'deuiaction3',
          },
        ],
        toolbarStyle: 'TOOLBAR',
        codeName: 'toolbar_style_toolbar',
        controlType: 'TOOLBAR',
        logicName: '工具栏_样式',
        appDataEntityId: 'web.master',
        controlParam: {
          id: 'toolbar',
        },
        sysCss: {
          cssName: 'toolbar',
        },
        modelId: '3a30915e8265e1a756f808f309e77b41',
        modelType: 'PSDETOOLBAR',
        name: 'toolbar',
        id: 'toolbar_style_toolbar',
      },
      {
        detoolbarItems: [
          {
            actionLevel: 100,
            noPrivDisplayMode: 2,
            uiactionId: 'open_dialog@master',
            uiactionTarget: 'NONE',
            valid: true,
            caption: '短词',
            itemType: 'DEUIACTION',
            tooltip: '短词',
            showCaption: true,
            showIcon: true,
            id: 'deuiaction3',
          },
          {
            spanMode: true,
            itemType: 'SEPERATOR',
            id: 'seperator1',
          },
          {
            actionLevel: 100,
            noPrivDisplayMode: 2,
            uiactionId: 'open_dialog@master',
            uiactionTarget: 'NONE',
            valid: true,
            caption: '图标',
            itemType: 'DEUIACTION',
            sysImage: {
              cssClass: 'fa fa-puzzle-piece',
              glyph: 'xf12e@FontAwesome',
            },
            tooltip: '图标',
            showIcon: true,
            id: 'deuiaction1',
          },
          {
            spanMode: true,
            itemType: 'SEPERATOR',
            id: 'seperator2',
          },
          {
            actionLevel: 100,
            noPrivDisplayMode: 2,
            uiactionId: 'open_dialog@master',
            uiactionTarget: 'NONE',
            valid: true,
            caption: '图标+短词',
            itemType: 'DEUIACTION',
            sysImage: {
              cssClass: 'fa fa-soundcloud',
              glyph: 'xf1be@FontAwesome',
            },
            tooltip: '图标+短词',
            showCaption: true,
            showIcon: true,
            id: 'deuiaction2',
          },
        ],
        codeName: 'toolbar_style_toolbar1',
        controlType: 'TOOLBAR',
        logicName: '工具栏_图标',
        appDataEntityId: 'web.master',
        controlParam: {
          id: 'toolbar1',
        },
        modelId: '4ef7d724a61e96dd893ddfcb9e77b95b',
        modelType: 'PSDETOOLBAR',
        name: 'toolbar1',
        id: 'toolbar_style_toolbar1',
      },
      {
        capLanguageRes: {
          lanResTag: 'DE.LNAME.MASTER',
        },
        caption: '工具栏_样式',
        codeName: 'toolbar_style_captionbar',
        controlType: 'CAPTIONBAR',
        appDataEntityId: 'web.master',
        controlParam: {},
        name: 'captionbar',
        id: 'toolbar_style_captionbar',
      },
    ],
    codeName: 'usr0515450441',
    controlType: 'VIEWLAYOUTPANEL',
    logicName: '工具栏_样式布局面板',
    appDataEntityId: 'web.master',
    controlParam: {},
    modelId: '46d0ad4b6b3dbdf51979ade74efeac7e',
    modelType: 'PSSYSVIEWLAYOUTPANEL',
    name: 'layoutpanel',
    id: 'usr0515450441',
  },
  title: '工具栏_样式',
  viewStyle: 'DEFAULT',
  viewType: 'DECUSTOMVIEW',
  enableDP: true,
  showCaptionBar: false,
  modelId: '3b9dfba96d59664b7044545fde922dcc',
  modelType: 'PSAPPDEVIEW',
  name: 'MASTERtoolbar_style',
  id: 'web.master_toolbar_style',
};
