export default {
  mdctrlActiveMode: 2,
  xdataControlName: 'gantt',
  loadDefault: true,
  deviewCodeName: 'GanttView',
  deviewId: '6c2708f3b0e75fc4212a1155829a2f06',
  accUserMode: 3,
  capLanguageRes: {
    lanResTag: 'DE.LNAME.MASTER',
  },
  caption: '甘特视图',
  codeName: 'master_gantt_view',
  appDataEntityId: 'web.master',
  appViewMsgGroupId: 'ganttview',
  controls: [
    {
      beginDataItemName: 'begin',
      endDataItemName: 'end',
      finishDataItemName: 'finish',
      prevDataItemName: 'prev',
      sndataItemName: 'sn',
      totalDataItemName: 'total',
      detreeColumns: [
        {
          caption: '名称',
          codeName: 'name',
          columnType: 'DEFGRIDCOLUMN',
          width: 100,
          widthUnit: 'px',
          id: 'name',
        },
        {
          caption: '数量',
          codeName: 'quantity',
          columnType: 'DEFGRIDCOLUMN',
          width: 100,
          widthUnit: 'px',
          id: 'quantity',
        },
        {
          caption: '开始时间',
          codeName: 'begin',
          columnType: 'DEFGRIDCOLUMN',
          width: 200,
          widthUnit: 'px',
          id: 'begin',
        },
        {
          caption: '结束时间',
          codeName: 'end',
          columnType: 'DEFGRIDCOLUMN',
          width: 200,
          widthUnit: 'px',
          id: 'end',
        },
      ],
      detreeNodeRSs: [
        {
          childDETreeNodeId: 'node',
          parentDETreeNodeId: 'root',
          parentValueLevel: 1,
          searchMode: 3,
          name: '默认根节点（ROOT）-主数据（node）',
          id: '默认根节点（root）-主数据（node）',
        },
      ],
      detreeNodes: [
        {
          text: '默认根节点',
          nodeType: 'ROOT',
          treeNodeType: 'STATIC',
          hasDETreeNodeRSs: true,
          rootNode: true,
          name: '默认根节点',
          id: 'root',
        },
        {
          dataSourceType: 'DEDATASET',
          idAppDEFieldId: 'id',
          appDEDataSetId: 'fetch_default',
          textAppDEFieldId: 'name',
          nodeType: 'node',
          appDataEntityId: 'web.master',
          detreeNodeColumns: [
            {
              clconvertMode: 'NONE',
              dataItemName: 'end_time',
              appDEFieldId: 'end_time',
              valueFormat: 'YYYY-MM-DD HH:mm:ss',
              valueType: 'SIMPLE',
              codeName: 'end_time',
              columnType: 'DEFGRIDCOLUMN',
              noPrivDisplayMode: 1,
              detreeColumnId: 'end',
              id: 'end_time',
            },
            {
              clconvertMode: 'NONE',
              dataItemName: 'start_time',
              appDEFieldId: 'start_time',
              valueFormat: 'YYYY-MM-DD HH:mm:ss',
              valueType: 'SIMPLE',
              codeName: 'start_time',
              columnType: 'DEFGRIDCOLUMN',
              noPrivDisplayMode: 1,
              detreeColumnId: 'begin',
              id: 'start_time',
            },
          ],
          detreeNodeDataItems: [
            {
              clconvertMode: 'NONE',
              appDEFieldId: 'end_time',
              detreeColumnId: 'end',
              valueType: 'SIMPLE',
              dataType: 5,
              id: 'end_time',
            },
            {
              clconvertMode: 'NONE',
              appDEFieldId: 'start_time',
              detreeColumnId: 'begin',
              valueType: 'SIMPLE',
              dataType: 5,
              id: 'start_time',
            },
          ],
          treeNodeType: 'DE',
          name: '主数据',
          id: 'node',
        },
      ],
      treeGridMode: 2,
      outputIconDefault: true,
      navViewPos: 'NONE',
      autoLoad: true,
      showBusyIndicator: true,
      codeName: 'gantt',
      controlType: 'GANTT',
      logicName: '甘特图',
      appDataEntityId: 'web.master',
      controlParam: {
        id: 'gantt',
      },
      modelId: '72262ea6b0dd4024bbd81d25393de998',
      modelType: 'PSDEGANTT',
      name: 'gantt',
      id: 'web.master.gantt',
    },
    {
      groupMode: 'SINGLE',
      controlType: 'SEARCHBAR',
      appDataEntityId: 'web.master',
      controlParam: {
        id: 'searchbar',
      },
      id: 'searchbar',
    },
    {
      capLanguageRes: {
        lanResTag: 'DE.LNAME.MASTER',
      },
      caption: '甘特视图',
      codeName: 'gantt_view_captionbar',
      controlType: 'CAPTIONBAR',
      appDataEntityId: 'web.master',
      controlParam: {},
      name: 'captionbar',
      id: 'gantt_view_captionbar',
    },
  ],
  viewLayoutPanel: {
    layoutBodyOnly: true,
    useDefaultLayout: true,
    layoutPanel: true,
    codeName: 'layoutpanel',
    controlStyle: 'APPDEGANTTVIEW',
    controlType: 'VIEWLAYOUTPANEL',
    appDataEntityId: 'web.master',
    controlParam: {},
    id: 'layoutpanel',
  },
  title: '甘特视图',
  viewStyle: 'DEFAULT',
  viewType: 'DEGANTTVIEW',
  enableDP: true,
  showCaptionBar: false,
  modelId: '578110678d6d3aee942241183880320c',
  modelType: 'PSAPPDEVIEW',
  name: 'MASTERGanttView',
  id: 'web.master_gantt_view',
};
