export default {
  deviewCodeName: 'Tree_datasource',
  deviewId: 'c8130f89061bfb472654871ebc8e8d48',
  accUserMode: 3,
  capLanguageRes: {
    lanResTag: 'DE.LNAME.MASTER',
  },
  caption: '树视图_数据源高级',
  codeName: 'master_tree_datasource',
  appDataEntityId: 'web.master',
  appViewMsgGroupId: 'tree_datasource',
  viewLayoutPanel: {
    viewProxyMode: true,
    layoutMode: 'FLEX',
    layout: {
      layout: 'FLEX',
    },
    rootPanelItems: [
      {
        actionGroupExtractMode: 'ITEM',
        panelItems: [
          {
            actionGroupExtractMode: 'ITEM',
            panelItems: [
              {
                actionGroupExtractMode: 'ITEM',
                panelItems: [
                  {
                    caption: '树视图',
                    itemStyle: 'DEFAULT',
                    itemType: 'CTRLPOS',
                    layoutPos: {
                      shrink: 1,
                      layout: 'FLEX',
                    },
                    showCaption: true,
                    id: 'tree1',
                  },
                ],
                predefinedType: 'CONTAINER_GROUP',
                layout: {
                  layout: 'FLEX',
                },
                dataRegionType: 'INHERIT',
                caption: '实体节点-排序(更新时间降序)',
                itemStyle: 'DEFAULT',
                itemType: 'CONTAINER',
                layoutPos: {
                  layoutPos: 'CENTER',
                  layout: 'BORDER',
                },
                showCaption: true,
                id: 'container_group1',
              },
              {
                actionGroupExtractMode: 'ITEM',
                panelItems: [
                  {
                    caption: '树视图',
                    itemStyle: 'DEFAULT',
                    itemType: 'CTRLPOS',
                    layoutPos: {
                      shrink: 1,
                      layout: 'FLEX',
                    },
                    showCaption: true,
                    id: 'tree2',
                  },
                ],
                predefinedType: 'CONTAINER_GROUP',
                layout: {
                  layout: 'FLEX',
                },
                dataRegionType: 'INHERIT',
                caption: '实体节点-图标',
                itemStyle: 'DEFAULT',
                itemType: 'CONTAINER',
                layoutPos: {
                  layoutPos: 'CENTER',
                  layout: 'BORDER',
                },
                showCaption: true,
                id: 'container_group2',
              },
              {
                actionGroupExtractMode: 'ITEM',
                panelItems: [
                  {
                    caption: '树视图',
                    itemStyle: 'DEFAULT',
                    itemType: 'CTRLPOS',
                    layoutPos: {
                      shrink: 1,
                      layout: 'FLEX',
                    },
                    showCaption: true,
                    id: 'tree3',
                  },
                ],
                predefinedType: 'CONTAINER_GROUP',
                layout: {
                  layout: 'FLEX',
                },
                dataRegionType: 'INHERIT',
                caption: '实体节点-子节点计数',
                itemStyle: 'DEFAULT',
                itemType: 'CONTAINER',
                layoutPos: {
                  layoutPos: 'CENTER',
                  layout: 'BORDER',
                },
                showCaption: true,
                id: 'container_group3',
              },
              {
                actionGroupExtractMode: 'ITEM',
                panelItems: [
                  {
                    caption: '树视图',
                    itemStyle: 'DEFAULT',
                    itemType: 'CTRLPOS',
                    layoutPos: {
                      shrink: 1,
                      layout: 'FLEX',
                    },
                    showCaption: true,
                    id: 'tree4',
                  },
                ],
                predefinedType: 'CONTAINER_GROUP',
                layout: {
                  layout: 'FLEX',
                },
                dataRegionType: 'INHERIT',
                caption: '实体节点-叶子节点',
                itemStyle: 'DEFAULT',
                itemType: 'CONTAINER',
                layoutPos: {
                  layoutPos: 'CENTER',
                  layout: 'BORDER',
                },
                showCaption: true,
                id: 'container_group4',
              },
            ],
            predefinedType: 'CONTAINER_SCROLL_MAIN',
            layout: {
              layout: 'BORDER',
            },
            dataRegionType: 'INHERIT',
            caption: '面板容器',
            itemStyle: 'DEFAULT',
            itemType: 'CONTAINER',
            layoutPos: {
              layoutPos: 'CENTER',
              layout: 'BORDER',
            },
            showCaption: true,
            id: 'container_scroll_main',
          },
        ],
        predefinedType: 'CONTAINER_SCROLL',
        layout: {
          layout: 'BORDER',
        },
        dataRegionType: 'INHERIT',
        caption: '滚动条容器',
        itemStyle: 'DEFAULT',
        itemType: 'CONTAINER',
        layoutPos: {
          shrink: 1,
          layout: 'FLEX',
        },
        id: 'container_scroll',
      },
    ],
    layoutPanel: true,
    controls: [
      {
        detreeNodeRSs: [
          {
            childDETreeNodeId: 'node_1',
            parentDETreeNodeId: 'node',
            parentValueLevel: 1,
            searchMode: 3,
            id: '主数据（node）-名称（node_1）',
          },
          {
            childDETreeNodeId: 'node',
            parentDETreeNodeId: 'root',
            parentValueLevel: 1,
            searchMode: 3,
            name: '默认根节点（ROOT）-主数据（node）',
            id: '默认根节点（root）-主数据（node）',
          },
        ],
        detreeNodes: [
          {
            text: '默认根节点',
            nodeType: 'ROOT',
            treeNodeType: 'STATIC',
            hasDETreeNodeRSs: true,
            rootNode: true,
            name: '默认根节点',
            id: 'root',
          },
          {
            text: '主数据',
            nodeType: 'node',
            treeNodeType: 'STATIC',
            hasDETreeNodeRSs: true,
            name: '主数据',
            id: 'node',
          },
          {
            dataSourceType: 'DEDATASET',
            idAppDEFieldId: 'id',
            appDEDataSetId: 'fetch_default',
            textAppDEFieldId: 'name',
            appendCaption: true,
            nodeType: 'node_1',
            appDataEntityId: 'web.master',
            treeNodeType: 'DE',
            name: '名称',
            id: 'node_1',
          },
        ],
        outputIconDefault: true,
        navViewPos: 'NONE',
        createControlAction: {
          appDEMethodId: 'create',
          appDataEntityId: 'web.master',
          id: 'create',
        },
        fetchControlAction: {
          appDataEntityId: 'web.master',
          id: 'fetch',
        },
        getControlAction: {
          appDEMethodId: 'get',
          appDataEntityId: 'web.master',
          id: 'load',
        },
        removeControlAction: {
          appDEMethodId: 'remove',
          appDataEntityId: 'web.master',
          id: 'remove',
        },
        updateControlAction: {
          appDEMethodId: 'update',
          appDataEntityId: 'web.master',
          id: 'update',
        },
        autoLoad: true,
        showBusyIndicator: true,
        codeName: 'tree_datasource1',
        controlType: 'TREEVIEW',
        logicName: '树视图_数据源高级_附加标题',
        appDataEntityId: 'web.master',
        controlParam: {
          id: 'tree',
        },
        modelId: 'ae457a45cb35c84e8ad85e33834d81c6',
        modelType: 'PSDETREEVIEW',
        name: 'tree',
        id: 'web.master.tree_datasource1',
      },
      {
        detreeNodeRSs: [
          {
            childDETreeNodeId: 'node_1',
            parentDETreeNodeId: 'node',
            parentValueLevel: 1,
            searchMode: 3,
            id: '主数据（node）-名称（node_1）',
          },
          {
            childDETreeNodeId: 'node',
            parentDETreeNodeId: 'root',
            parentValueLevel: 1,
            searchMode: 3,
            name: '默认根节点（ROOT）-主数据（node）',
            id: '默认根节点（root）-主数据（node）',
          },
        ],
        detreeNodes: [
          {
            text: '默认根节点',
            nodeType: 'ROOT',
            treeNodeType: 'STATIC',
            hasDETreeNodeRSs: true,
            rootNode: true,
            name: '默认根节点',
            id: 'root',
          },
          {
            text: '主数据',
            nodeType: 'node',
            treeNodeType: 'STATIC',
            hasDETreeNodeRSs: true,
            name: '主数据',
            id: 'node',
          },
          {
            dataSourceType: 'DEDATASET',
            idAppDEFieldId: 'id',
            appDEDataSetId: 'fetch_default',
            sortDir: 'DESC',
            sortAppDEFieldId: 'update_time',
            textAppDEFieldId: 'name',
            appendCaption: true,
            nodeType: 'node_1',
            appDataEntityId: 'web.master',
            treeNodeType: 'DE',
            name: '名称',
            id: 'node_1',
          },
        ],
        outputIconDefault: true,
        navViewPos: 'NONE',
        createControlAction: {
          appDEMethodId: 'create',
          appDataEntityId: 'web.master',
          id: 'create',
        },
        fetchControlAction: {
          appDataEntityId: 'web.master',
          id: 'fetch',
        },
        getControlAction: {
          appDEMethodId: 'get',
          appDataEntityId: 'web.master',
          id: 'load',
        },
        removeControlAction: {
          appDEMethodId: 'remove',
          appDataEntityId: 'web.master',
          id: 'remove',
        },
        updateControlAction: {
          appDEMethodId: 'update',
          appDataEntityId: 'web.master',
          id: 'update',
        },
        autoLoad: true,
        showBusyIndicator: true,
        codeName: 'tree_datasource2',
        controlType: 'TREEVIEW',
        logicName: '树视图_数据源高级_排序',
        appDataEntityId: 'web.master',
        controlParam: {
          id: 'tree1',
        },
        modelId: 'c1bf149eba6d7f68b09c02fd69e68a70',
        modelType: 'PSDETREEVIEW',
        name: 'tree1',
        id: 'web.master.tree_datasource2',
      },
      {
        detreeNodeRSs: [
          {
            childDETreeNodeId: 'node_1',
            parentDETreeNodeId: 'node',
            parentValueLevel: 1,
            searchMode: 3,
            id: '主数据（node）-名称（node_1）',
          },
          {
            childDETreeNodeId: 'node',
            parentDETreeNodeId: 'root',
            parentValueLevel: 1,
            searchMode: 3,
            name: '默认根节点（ROOT）-主数据（node）',
            id: '默认根节点（root）-主数据（node）',
          },
        ],
        detreeNodes: [
          {
            text: '默认根节点',
            nodeType: 'ROOT',
            treeNodeType: 'STATIC',
            hasDETreeNodeRSs: true,
            rootNode: true,
            name: '默认根节点',
            id: 'root',
          },
          {
            text: '主数据',
            nodeType: 'node',
            treeNodeType: 'STATIC',
            hasDETreeNodeRSs: true,
            name: '主数据',
            id: 'node',
          },
          {
            dataSourceType: 'DEDATASET',
            iconAppDEFieldId: 'icon',
            idAppDEFieldId: 'id',
            appDEDataSetId: 'fetch_default',
            shapeClsAppDEFieldId: 'type',
            textAppDEFieldId: 'name',
            appendCaption: true,
            nodeType: 'node_1',
            appDataEntityId: 'web.master',
            treeNodeType: 'DE',
            name: '名称',
            id: 'node_1',
          },
        ],
        outputIconDefault: true,
        navViewPos: 'NONE',
        createControlAction: {
          appDEMethodId: 'create',
          appDataEntityId: 'web.master',
          id: 'create',
        },
        fetchControlAction: {
          appDataEntityId: 'web.master',
          id: 'fetch',
        },
        getControlAction: {
          appDEMethodId: 'get',
          appDataEntityId: 'web.master',
          id: 'load',
        },
        removeControlAction: {
          appDEMethodId: 'remove',
          appDataEntityId: 'web.master',
          id: 'remove',
        },
        updateControlAction: {
          appDEMethodId: 'update',
          appDataEntityId: 'web.master',
          id: 'update',
        },
        autoLoad: true,
        showBusyIndicator: true,
        codeName: 'tree_datasource3',
        controlType: 'TREEVIEW',
        logicName: '树视图_数据源高级_图标',
        appDataEntityId: 'web.master',
        controlParam: {
          id: 'tree2',
        },
        modelId: '6aaae3ecee29d50b4cc762b39fb9833f',
        modelType: 'PSDETREEVIEW',
        name: 'tree2',
        id: 'web.master.tree_datasource3',
      },
      {
        detreeNodeRSs: [
          {
            childDETreeNodeId: 'node_2',
            parentAppDEFieldId: 'parent_id',
            parentDER1N: {
              pickupDEFName: 'PARENT_ID',
              codeName: 'parent',
              dertype: 'DER1N',
              logicName: '上级区划',
              orderValue: 100,
              serviceCodeName: 'parent',
              name: 'DER1N_REGION_REGION_PARENT_ID',
              id: 'mock.region.der1n_region_region_parent_id',
            },
            parentDETreeNodeId: 'node_1',
            parentValueLevel: 1,
            searchMode: 3,
            id: '名称（node_1）-区划子数据（node_2）',
          },
          {
            childDETreeNodeId: 'node_1',
            parentDETreeNodeId: 'node',
            parentValueLevel: 1,
            searchMode: 3,
            id: '主数据（node）-名称（node_1）',
          },
          {
            childDETreeNodeId: 'node',
            parentDETreeNodeId: 'root',
            parentValueLevel: 1,
            searchMode: 3,
            name: '默认根节点（ROOT）-主数据（node）',
            id: '默认根节点（root）-主数据（node）',
          },
          {
            childDETreeNodeId: 'node_2',
            parentAppDEFieldId: 'parent_id',
            parentDER1N: {
              pickupDEFName: 'PARENT_ID',
              codeName: 'parent',
              dertype: 'DER1N',
              logicName: '上级区划',
              orderValue: 100,
              serviceCodeName: 'parent',
              name: 'DER1N_REGION_REGION_PARENT_ID',
              id: 'mock.region.der1n_region_region_parent_id',
            },
            parentDETreeNodeId: 'node_2',
            parentValueLevel: 1,
            searchMode: 3,
            id: '区划子数据（node_2）-区划子数据（node_2）',
          },
        ],
        detreeNodes: [
          {
            text: '默认根节点',
            nodeType: 'ROOT',
            treeNodeType: 'STATIC',
            hasDETreeNodeRSs: true,
            rootNode: true,
            name: '默认根节点',
            id: 'root',
          },
          {
            text: '区划',
            nodeType: 'node',
            treeNodeType: 'STATIC',
            hasDETreeNodeRSs: true,
            name: '区划',
            id: 'node',
          },
          {
            childCntAppDEFieldId: 'childcnt',
            dataSourceType: 'DEDATASET',
            idAppDEFieldId: 'id',
            appDEDataSetId: 'fetch_root',
            textAppDEFieldId: 'name',
            nodeType: 'node_1',
            appDataEntityId: 'web.region',
            treeNodeType: 'DE',
            hasDETreeNodeRSs: true,
            name: '区划数据',
            id: 'node_1',
          },
          {
            childCntAppDEFieldId: 'childcnt',
            dataSourceType: 'DEDATASET',
            idAppDEFieldId: 'id',
            appDEDataSetId: 'fetch_child',
            textAppDEFieldId: 'name',
            nodeType: 'node_2',
            appDataEntityId: 'web.region',
            treeNodeType: 'DE',
            hasDETreeNodeRSs: true,
            name: '区划子数据',
            id: 'node_2',
          },
        ],
        outputIconDefault: true,
        navViewPos: 'NONE',
        createControlAction: {
          appDEMethodId: 'create',
          appDataEntityId: 'web.master',
          id: 'create',
        },
        fetchControlAction: {
          appDataEntityId: 'web.master',
          id: 'fetch',
        },
        getControlAction: {
          appDEMethodId: 'get',
          appDataEntityId: 'web.master',
          id: 'load',
        },
        removeControlAction: {
          appDEMethodId: 'remove',
          appDataEntityId: 'web.master',
          id: 'remove',
        },
        updateControlAction: {
          appDEMethodId: 'update',
          appDataEntityId: 'web.master',
          id: 'update',
        },
        autoLoad: true,
        showBusyIndicator: true,
        codeName: 'tree_datasource4',
        controlType: 'TREEVIEW',
        logicName: '树视图_数据源高级_子节点计数',
        appDataEntityId: 'web.master',
        controlParam: {
          id: 'tree3',
        },
        modelId: 'ced1714573e2753c439153f3fcff9be0',
        modelType: 'PSDETREEVIEW',
        name: 'tree3',
        id: 'web.master.tree_datasource4',
      },
      {
        detreeNodeRSs: [
          {
            childDETreeNodeId: 'node_2',
            parentAppDEFieldId: 'parent_id',
            parentDER1N: {
              pickupDEFName: 'PARENT_ID',
              codeName: 'parent',
              dertype: 'DER1N',
              logicName: '上级区划',
              orderValue: 100,
              serviceCodeName: 'parent',
              name: 'DER1N_REGION_REGION_PARENT_ID',
              id: 'mock.region.der1n_region_region_parent_id',
            },
            parentDETreeNodeId: 'node_2',
            parentValueLevel: 1,
            searchMode: 3,
            id: '区划子数据（node_2）-区划子数据（node_2）',
          },
          {
            childDETreeNodeId: 'node_1',
            parentDETreeNodeId: 'node',
            parentValueLevel: 1,
            searchMode: 3,
            id: '主数据（node）-名称（node_1）',
          },
          {
            childDETreeNodeId: 'node',
            parentDETreeNodeId: 'root',
            parentValueLevel: 1,
            searchMode: 3,
            name: '默认根节点（ROOT）-主数据（node）',
            id: '默认根节点（root）-主数据（node）',
          },
          {
            childDETreeNodeId: 'node_2',
            parentAppDEFieldId: 'parent_id',
            parentDER1N: {
              pickupDEFName: 'PARENT_ID',
              codeName: 'parent',
              dertype: 'DER1N',
              logicName: '上级区划',
              orderValue: 100,
              serviceCodeName: 'parent',
              name: 'DER1N_REGION_REGION_PARENT_ID',
              id: 'mock.region.der1n_region_region_parent_id',
            },
            parentDETreeNodeId: 'node_1',
            parentValueLevel: 1,
            searchMode: 3,
            id: '区划数据（node_1）-区划子数据（node_2）',
          },
        ],
        detreeNodes: [
          {
            text: '默认根节点',
            nodeType: 'ROOT',
            treeNodeType: 'STATIC',
            hasDETreeNodeRSs: true,
            rootNode: true,
            name: '默认根节点',
            id: 'root',
          },
          {
            text: '区划',
            nodeType: 'node',
            treeNodeType: 'STATIC',
            hasDETreeNodeRSs: true,
            name: '区划',
            id: 'node',
          },
          {
            dataSourceType: 'DEDATASET',
            idAppDEFieldId: 'id',
            leafFlagAppDEFieldId: 'leaf',
            appDEDataSetId: 'fetch_root',
            textAppDEFieldId: 'name',
            nodeType: 'node_1',
            appDataEntityId: 'web.region',
            treeNodeType: 'DE',
            hasDETreeNodeRSs: true,
            name: '区划数据',
            id: 'node_1',
          },
          {
            dataSourceType: 'DEDATASET',
            idAppDEFieldId: 'id',
            leafFlagAppDEFieldId: 'leaf',
            appDEDataSetId: 'fetch_child',
            textAppDEFieldId: 'name',
            nodeType: 'node_2',
            appDataEntityId: 'web.region',
            treeNodeType: 'DE',
            hasDETreeNodeRSs: true,
            name: '区划子数据',
            id: 'node_2',
          },
        ],
        outputIconDefault: true,
        navViewPos: 'NONE',
        createControlAction: {
          appDEMethodId: 'create',
          appDataEntityId: 'web.master',
          id: 'create',
        },
        fetchControlAction: {
          appDataEntityId: 'web.master',
          id: 'fetch',
        },
        getControlAction: {
          appDEMethodId: 'get',
          appDataEntityId: 'web.master',
          id: 'load',
        },
        removeControlAction: {
          appDEMethodId: 'remove',
          appDataEntityId: 'web.master',
          id: 'remove',
        },
        updateControlAction: {
          appDEMethodId: 'update',
          appDataEntityId: 'web.master',
          id: 'update',
        },
        autoLoad: true,
        showBusyIndicator: true,
        codeName: 'tree_datasource5',
        controlType: 'TREEVIEW',
        logicName: '树视图_数据源高级_叶子节点',
        appDataEntityId: 'web.master',
        controlParam: {
          id: 'tree4',
        },
        modelId: '2e2a517ee3512016a00cf2fe7879435a',
        modelType: 'PSDETREEVIEW',
        name: 'tree4',
        id: 'web.master.tree_datasource5',
      },
      {
        capLanguageRes: {
          lanResTag: 'DE.LNAME.MASTER',
        },
        caption: '树视图_数据源高级',
        codeName: 'tree_datasource_captionbar',
        controlType: 'CAPTIONBAR',
        appDataEntityId: 'web.master',
        controlParam: {},
        name: 'captionbar',
        id: 'tree_datasource_captionbar',
      },
    ],
    codeName: 'a46c08f44ce216b380b',
    controlType: 'VIEWLAYOUTPANEL',
    logicName: '树视图_数据源高级布局面板',
    appDataEntityId: 'web.master',
    controlParam: {},
    modelId: '5ff952227b7ff08ca421d04226cf4201',
    modelType: 'PSSYSVIEWLAYOUTPANEL',
    name: 'layoutpanel',
    id: 'a46c08f44ce216b380b',
  },
  title: '树视图_数据源高级',
  viewStyle: 'DEFAULT',
  viewType: 'DECUSTOMVIEW',
  enableDP: true,
  showCaptionBar: false,
  modelId: 'baa2eceaafe05c766026ceb5ebaa15db',
  modelType: 'PSAPPDEVIEW',
  name: 'MASTERTree_datasource',
  id: 'web.master_tree_datasource',
};
