export default {
  enableDirtyChecking: true,
  showDataInfoBar: true,
  xdataControlName: 'form',
  loadDefault: true,
  deviewCodeName: 'counter_plugin',
  deviewId: '5cddda0f32b0d15395fed60dd3c9e254',
  accUserMode: 3,
  capLanguageRes: {
    lanResTag: 'DE.LNAME.MASTER',
  },
  caption: '计数器插件',
  codeName: 'master_counter_plugin',
  appDataEntityId: 'web.master',
  appViewEngines: [
    {
      engineCat: 'VIEW',
      engineType: 'EditView',
      id: 'engine',
    },
  ],
  appViewMsgGroupId: 'counter_plugin_group',
  controls: [
    {
      xdataControlName: 'form',
      codeName: 'counter_plugin_toolbar',
      controlType: 'TOOLBAR',
      logicName: '应用计数器插件_工具栏',
      appDataEntityId: 'web.master',
      controlParam: {
        id: 'toolbar',
      },
      modelId: '61de8c03f2892504e21c9b26d866c11b',
      modelType: 'PSDETOOLBAR',
      name: 'toolbar',
      id: 'counter_plugin_toolbar',
    },
    {
      createControlAction: {
        appDEMethodId: 'create',
        appDataEntityId: 'web.master',
        id: 'create',
      },
      getDraftFromControlAction: {
        appDataEntityId: 'web.master',
        id: 'loaddraftfrom',
      },
      getDraftControlAction: {
        appDEMethodId: 'de_action_plugin',
        appDataEntityId: 'web.master',
        id: 'loaddraft',
      },
      getControlAction: {
        appDEMethodId: 'get',
        appDataEntityId: 'web.master',
        id: 'load',
      },
      removeControlAction: {
        appDEMethodId: 'remove',
        appDataEntityId: 'web.master',
        id: 'remove',
      },
      updateControlAction: {
        appDEMethodId: 'update',
        appDataEntityId: 'web.master',
        id: 'update',
      },
      deformPages: [
        {
          layout: {
            columnCount: 24,
            layout: 'TABLE_24COL',
          },
          deformDetails: [
            {
              deformTabPages: [
                {
                  layout: {
                    columnCount: 24,
                    layout: 'TABLE_24COL',
                  },
                  deformDetails: [
                    {
                      maskMode: 0,
                      appViewId: 'web.master_grid_view',
                      parentDataJO: {
                        srfparentdename: 'MASTER',
                        SRFPARENTTYPE: 'CUSTOM',
                      },
                      codeName: 'tabpanel1_grid_druipart',
                      detailStyle: 'DEFAULT',
                      detailType: 'DRUIPART',
                      layoutPos: {
                        colMD: 24,
                        layout: 'TABLE_24COL',
                      },
                      showCaption: true,
                      id: 'tabpanel1_grid_druipart',
                    },
                  ],
                  caption: '表格',
                  codeName: 'tabpanel1_grid',
                  counterId: 'count1',
                  detailStyle: 'DEFAULT',
                  detailType: 'TABPAGE',
                  appCounterRefId: 'be17b923fd49b0c15c6f8bf83529cdff',
                  showCaption: true,
                  id: 'tabpanel1_grid',
                },
                {
                  layout: {
                    columnCount: 24,
                    layout: 'TABLE_24COL',
                  },
                  deformDetails: [
                    {
                      maskMode: 0,
                      appViewId: 'web.master_edit_view',
                      parentDataJO: {
                        srfparentdename: 'MASTER',
                        SRFPARENTTYPE: 'CUSTOM',
                      },
                      codeName: 'tabpanel1_form_druipart',
                      detailStyle: 'DEFAULT',
                      detailType: 'DRUIPART',
                      layoutPos: {
                        colMD: 24,
                        layout: 'TABLE_24COL',
                      },
                      showCaption: true,
                      id: 'tabpanel1_form_druipart',
                    },
                  ],
                  caption: '表单',
                  codeName: 'tabpanel1_form',
                  counterId: 'count2',
                  detailStyle: 'DEFAULT',
                  detailType: 'TABPAGE',
                  appCounterRefId: 'be17b923fd49b0c15c6f8bf83529cdff',
                  showCaption: true,
                  id: 'tabpanel1_form',
                },
              ],
              codeName: 'tabpanel1',
              detailStyle: 'DEFAULT',
              detailType: 'TABPANEL',
              layoutPos: {
                colMD: 24,
                layout: 'TABLE_24COL',
              },
              id: 'tabpanel1',
            },
            {
              dataType: 25,
              enableCond: 3,
              labelPos: 'LEFT',
              labelWidth: 130,
              noPrivDisplayMode: 1,
              appDEFieldId: 'id',
              editor: {
                editorType: 'HIDDEN',
                valueType: 'SIMPLE',
                editable: true,
                id: 'id',
              },
              allowEmpty: true,
              hidden: true,
              capLanguageRes: {
                lanResTag: 'DEF.LNAME.MASTER.ID',
              },
              caption: '标识',
              codeName: 'id',
              detailStyle: 'DEFAULT',
              detailType: 'FORMITEM',
              layoutPos: {
                colMD: 24,
                layout: 'TABLE_24COL',
              },
              id: 'id',
            },
          ],
          caption: '基本信息',
          codeName: 'formpage1',
          detailStyle: 'DEFAULT',
          detailType: 'FORMPAGE',
          id: 'formpage1',
        },
      ],
      layout: {
        columnCount: 24,
        layout: 'TABLE_24COL',
      },
      tabHeaderPos: 'TOP',
      noTabHeader: true,
      autoLoad: true,
      showBusyIndicator: true,
      appCounterRefs: [
        {
          appCounter: {
            codeName: 'CounterPlugin',
            counterType: 'CUSTOM',
            sysPFPluginId: 'r9counterpluginid',
            timer: 60000,
            uniqueTag: 'CounterPlugin',
            name: '应用计数器插件',
            id: 'web.counterplugin',
          },
          tag: 'be17b923fd49b0c15c6f8bf83529cdff',
          uniqueTag: 'CounterPlugin',
          id: 'be17b923fd49b0c15c6f8bf83529cdff',
        },
      ],
      codeName: 'main4',
      controlType: 'FORM',
      logicName: '应用计数器插件_表单',
      appDataEntityId: 'web.master',
      controlParam: {
        id: 'form',
      },
      modelId: '041da0bcd89f343a9585df3453cfd3c3',
      modelType: 'PSDEFORM_EDITFORM',
      name: 'form',
      id: 'web.master.main4',
    },
    {
      codeName: 'counter_plugin_datainfobar',
      controlType: 'DATAINFOBAR',
      appDataEntityId: 'web.master',
      controlParam: {
        id: 'datainfobar',
      },
      name: 'datainfobar',
      id: 'counter_plugin_datainfobar',
    },
    {
      capLanguageRes: {
        lanResTag: 'DE.LNAME.MASTER',
      },
      caption: '计数器插件',
      codeName: 'counter_plugin_captionbar',
      controlType: 'CAPTIONBAR',
      appDataEntityId: 'web.master',
      controlParam: {},
      name: 'captionbar',
      id: 'counter_plugin_captionbar',
    },
  ],
  viewLayoutPanel: {
    layoutBodyOnly: true,
    useDefaultLayout: true,
    layoutPanel: true,
    codeName: 'layoutpanel',
    controlStyle: 'APPDEEDITVIEW',
    controlType: 'VIEWLAYOUTPANEL',
    appDataEntityId: 'web.master',
    controlParam: {},
    id: 'layoutpanel',
  },
  title: '计数器插件',
  viewStyle: 'DEFAULT',
  viewType: 'DEEDITVIEW',
  enableDP: true,
  showCaptionBar: false,
  modelId: '37ac1b2e10cc2eb6eeb0a34b5c0bf653',
  modelType: 'PSAPPDEVIEW',
  name: 'MASTERcounter_plugin',
  id: 'web.master_counter_plugin',
};
