export default {
  mdctrlActiveMode: 2,
  xdataControlName: 'list',
  loadDefault: true,
  deviewCodeName: 'list_quicktoolbar',
  deviewId: 'aae082535838402ca046fdbfc9082d58',
  accUserMode: 3,
  capLanguageRes: {
    lanResTag: 'DE.LNAME.MASTER',
  },
  caption: '列表_快速操作工具栏',
  codeName: 'master_list_quicktoolbar',
  appDataEntityId: 'web.master',
  appViewEngines: [
    {
      engineCat: 'VIEW',
      engineType: 'ListView',
      id: 'engine',
    },
  ],
  appViewLogics: [
    {
      logicTrigger: 'CUSTOM',
      logicType: 'APPUILOGIC',
      builtinAppUILogic: {
        actionAfterWizard: 'DEFAULT',
        newDataAppView: {
          openMode: 'POPUPMODAL',
          refAppViewId: 'web.master_edit_view',
        },
        appUILogicRefViews: [
          {
            openMode: 'POPUPMODAL',
            refAppViewId: 'web.master_edit_view',
          },
        ],
        builtinLogic: true,
        logicType: 'PREDEFINED',
        viewLogicType: 'APP_NEWDATA',
        id: '新建数据',
      },
      builtinLogic: true,
      id: 'newdata',
    },
    {
      logicTrigger: 'CUSTOM',
      logicType: 'APPUILOGIC',
      builtinAppUILogic: {
        openDataAppView: {
          openMode: 'POPUPMODAL',
          refAppViewId: 'web.master_edit_view',
        },
        editMode: true,
        appUILogicRefViews: [
          {
            openMode: 'POPUPMODAL',
            refAppViewId: 'web.master_edit_view',
          },
        ],
        builtinLogic: true,
        logicType: 'PREDEFINED',
        viewLogicType: 'APP_OPENDATA',
        id: '打开数据',
      },
      builtinLogic: true,
      id: 'opendata',
    },
  ],
  appViewMsgGroupId: 'list_quicktoolbar',
  appViewRefs: [
    {
      realOpenMode: 'POPUPMODAL',
      realTitle: '主数据编辑视图',
      refAppViewId: 'web.master_edit_view',
      name: 'NEWDATA',
      id: 'newdata',
    },
    {
      realOpenMode: 'POPUPMODAL',
      realTitle: '主数据编辑视图',
      refAppViewId: 'web.master_edit_view',
      name: 'EDITDATA',
      id: 'editdata',
    },
  ],
  controls: [
    {
      groupMode: 'NONE',
      groupStyle: 'DEFAULT',
      delistDataItems: [
        {
          appDEFieldId: 'id',
          dataType: 25,
          id: 'srfkey',
        },
        {
          appDEFieldId: 'name',
          dataType: 25,
          id: 'srfmajortext',
        },
        {
          appDEFieldId: 'region_id',
          dataType: 25,
          id: 'region_id',
        },
      ],
      pagingSize: 1000,
      showHeader: true,
      navViewPos: 'NONE',
      createControlAction: {
        appDEMethodId: 'create',
        appDataEntityId: 'web.master',
        id: 'create',
      },
      fetchControlAction: {
        appDEMethodId: 'fetch_emptydata',
        appDataEntityId: 'web.master',
        id: 'fetch',
      },
      getControlAction: {
        appDEMethodId: 'get',
        appDataEntityId: 'web.master',
        id: 'load',
      },
      removeControlAction: {
        appDEMethodId: 'remove',
        appDataEntityId: 'web.master',
        id: 'remove',
      },
      updateControlAction: {
        appDEMethodId: 'update',
        appDataEntityId: 'web.master',
        id: 'update',
      },
      autoLoad: true,
      showBusyIndicator: true,
      controls: [
        {
          detoolbarItems: [
            {
              actionLevel: 100,
              noPrivDisplayMode: 2,
              uiactionId: 'gridview_newaction',
              valid: true,
              capLanguageRes: {
                lanResTag: 'TBB.TEXT.*.NEW',
              },
              caption: '新建',
              itemType: 'DEUIACTION',
              sysImage: {
                cssClass: 'fa fa-file-text-o',
                glyph: 'xf0f6@FontAwesome',
              },
              tooltip: '新建',
              tooltipLanguageRes: {
                lanResTag: 'TBB.TOOLTIP.*.NEW',
              },
              showCaption: true,
              showIcon: true,
              id: 'deuiaction1',
            },
            {
              actionLevel: 100,
              noPrivDisplayMode: 2,
              uiactionId: 'open_document@master',
              uiactionTarget: 'NONE',
              valid: true,
              caption: '打开文档',
              itemType: 'DEUIACTION',
              tooltip: '打开文档',
              showCaption: true,
              showIcon: true,
              id: 'deuiaction2',
            },
            {
              actionLevel: 100,
              noPrivDisplayMode: 2,
              uiactionId: 'open_about@master',
              uiactionTarget: 'NONE',
              valid: true,
              caption: '打开关于',
              itemType: 'DEUIACTION',
              sysImage: {
                cssClass: 'fa fa-info-circle',
                glyph: 'xf05a@FontAwesome',
              },
              tooltip: '打开关于',
              showCaption: true,
              showIcon: true,
              id: 'deuiaction3',
            },
          ],
          codeName: 'list_quicktoolbar_list_quicktoolbar',
          controlType: 'TOOLBAR',
          logicName: '多数据_快速操作工具栏',
          appDataEntityId: 'web.master',
          controlParam: {
            id: 'list_quicktoolbar',
          },
          modelId: '46eb8b3a2da98341c716809c847f4272',
          modelType: 'PSDETOOLBAR',
          name: 'list_quicktoolbar',
          id: 'list_quicktoolbar_list_quicktoolbar',
        },
      ],
      codeName: 'list_toolbar1',
      controlType: 'LIST',
      logicName: 'list_toolbar1',
      appDataEntityId: 'web.master',
      controlParam: {
        id: 'list',
      },
      modelId: '3cf22d33b53b9d8da186c171c4071666',
      modelType: 'PSDELIST',
      name: 'list',
      id: 'web.master.list_toolbar1',
    },
    {
      groupMode: 'SINGLE',
      controlType: 'SEARCHBAR',
      appDataEntityId: 'web.master',
      controlParam: {
        id: 'searchbar',
      },
      id: 'searchbar',
    },
    {
      capLanguageRes: {
        lanResTag: 'DE.LNAME.MASTER',
      },
      caption: '列表_快速操作工具栏',
      codeName: 'list_quicktoolbar_captionbar',
      controlType: 'CAPTIONBAR',
      appDataEntityId: 'web.master',
      controlParam: {},
      name: 'captionbar',
      id: 'list_quicktoolbar_captionbar',
    },
  ],
  viewLayoutPanel: {
    layoutBodyOnly: true,
    useDefaultLayout: true,
    layoutPanel: true,
    codeName: 'layoutpanel',
    controlStyle: 'APPDELISTVIEW',
    controlType: 'VIEWLAYOUTPANEL',
    appDataEntityId: 'web.master',
    controlParam: {},
    id: 'layoutpanel',
  },
  title: '列表_快速操作工具栏',
  viewStyle: 'DEFAULT',
  viewType: 'DELISTVIEW',
  enableDP: true,
  showCaptionBar: false,
  modelId: 'cbfb1f748b536acd43c6153881229c10',
  modelType: 'PSAPPDEVIEW',
  name: 'MASTERlist_quicktoolbar',
  id: 'web.master_list_quicktoolbar',
};
