export default {
  deviewCodeName: 'calendar_style_icon',
  deviewId: '85f8dfd2b6937e8ea3f920ba577a9b21',
  accUserMode: 3,
  capLanguageRes: {
    lanResTag: 'DE.LNAME.MASTER',
  },
  caption: '日历_界面样式及图标',
  codeName: 'master_calendar_style_icon',
  appDataEntityId: 'web.master',
  appViewMsgGroupId: 'calendar_style_icon',
  viewLayoutPanel: {
    viewProxyMode: true,
    layoutMode: 'FLEX',
    layout: {
      layout: 'FLEX',
    },
    rootPanelItems: [
      {
        actionGroupExtractMode: 'ITEM',
        panelItems: [
          {
            actionGroupExtractMode: 'ITEM',
            panelItems: [
              {
                actionGroupExtractMode: 'ITEM',
                panelItems: [
                  {
                    actionGroupExtractMode: 'ITEM',
                    panelItems: [
                      {
                        caption: '日历',
                        itemStyle: 'DEFAULT',
                        itemType: 'CTRLPOS',
                        layoutPos: {
                          shrink: 1,
                          layout: 'FLEX',
                        },
                        showCaption: true,
                        id: 'calendar',
                      },
                    ],
                    layout: {
                      layout: 'FLEX',
                    },
                    dataRegionType: 'INHERIT',
                    caption: '容器',
                    itemStyle: 'DEFAULT',
                    itemType: 'CONTAINER',
                    layoutPos: {
                      shrink: 1,
                      layout: 'FLEX',
                    },
                    id: 'container',
                  },
                ],
                predefinedType: 'CONTAINER_GROUP',
                layout: {
                  layout: 'FLEX',
                },
                dataRegionType: 'INHERIT',
                caption: '字体颜色',
                itemStyle: 'DEFAULT',
                itemType: 'CONTAINER',
                layoutPos: {
                  layoutPos: 'CENTER',
                  layout: 'BORDER',
                },
                showCaption: true,
                id: 'container_group',
              },
              {
                actionGroupExtractMode: 'ITEM',
                panelItems: [
                  {
                    actionGroupExtractMode: 'ITEM',
                    panelItems: [
                      {
                        caption: '日历',
                        itemStyle: 'DEFAULT',
                        itemType: 'CTRLPOS',
                        layoutPos: {
                          shrink: 1,
                          layout: 'FLEX',
                        },
                        showCaption: true,
                        id: 'calendar1',
                      },
                    ],
                    layout: {
                      layout: 'FLEX',
                    },
                    dataRegionType: 'INHERIT',
                    caption: '容器',
                    itemStyle: 'DEFAULT',
                    itemType: 'CONTAINER',
                    layoutPos: {
                      shrink: 1,
                      layout: 'FLEX',
                    },
                    id: 'container1',
                  },
                ],
                predefinedType: 'CONTAINER_GROUP',
                layout: {
                  layout: 'FLEX',
                },
                dataRegionType: 'INHERIT',
                caption: '背景颜色',
                itemStyle: 'DEFAULT',
                itemType: 'CONTAINER',
                layoutPos: {
                  layoutPos: 'CENTER',
                  layout: 'BORDER',
                },
                showCaption: true,
                id: 'container_group1',
              },
            ],
            predefinedType: 'CONTAINER_SCROLL_MAIN',
            layout: {
              layout: 'BORDER',
            },
            dataRegionType: 'INHERIT',
            caption: '面板容器',
            itemStyle: 'DEFAULT',
            itemType: 'CONTAINER',
            layoutPos: {
              layoutPos: 'CENTER',
              layout: 'BORDER',
            },
            showCaption: true,
            id: 'container_scroll_main',
          },
        ],
        predefinedType: 'CONTAINER_SCROLL',
        layout: {
          layout: 'BORDER',
        },
        dataRegionType: 'INHERIT',
        caption: '滚动条容器',
        itemStyle: 'DEFAULT',
        itemType: 'CONTAINER',
        layoutPos: {
          shrink: 1,
          layout: 'FLEX',
        },
        id: 'container_scroll',
      },
    ],
    layoutPanel: true,
    controls: [
      {
        calendarStyle: 'MONTH',
        groupMode: 'NONE',
        legendPos: 'NONE',
        sysCalendarItems: [
          {
            beginTimeAppDEFieldId: 'date',
            color: 'red',
            endTimeAppDEFieldId: 'date',
            idAppDEFieldId: 'id',
            itemStyle: 'DEFAULT',
            itemType: 'date',
            appDEDataSetId: 'fetch_default',
            textAppDEFieldId: 'name',
            appDataEntityId: 'web.master',
            id: 'date',
          },
        ],
        navViewPos: 'NONE',
        autoLoad: true,
        showBusyIndicator: true,
        codeName: 'calendar_style_fontcolor',
        controlType: 'CALENDAR',
        logicName: '日历_样式_字体颜色',
        appDataEntityId: 'web.master',
        controlParam: {
          id: 'calendar',
        },
        modelId: '4c90c8fc94aa33fe6dc29a4e1573a838',
        modelType: 'PSSYSCALENDAR',
        name: 'calendar',
        id: 'web.master.calendar_style_fontcolor',
      },
      {
        calendarStyle: 'MONTH',
        groupMode: 'NONE',
        legendPos: 'NONE',
        sysCalendarItems: [
          {
            bkcolor: '#c8e8fa',
            beginTimeAppDEFieldId: 'date',
            endTimeAppDEFieldId: 'date',
            idAppDEFieldId: 'id',
            itemStyle: 'DEFAULT',
            itemType: 'date',
            appDEDataSetId: 'fetch_default',
            textAppDEFieldId: 'name',
            appDataEntityId: 'web.master',
            id: 'date',
          },
        ],
        navViewPos: 'NONE',
        autoLoad: true,
        showBusyIndicator: true,
        codeName: 'calendar_style_backgroundcolor',
        controlType: 'CALENDAR',
        logicName: '日历_样式_背景颜色',
        appDataEntityId: 'web.master',
        controlParam: {
          id: 'calendar1',
        },
        modelId: 'd5538a08078d847362f163eb6b2c397a',
        modelType: 'PSSYSCALENDAR',
        name: 'calendar1',
        id: 'web.master.calendar_style_backgroundcolor',
      },
      {
        capLanguageRes: {
          lanResTag: 'DE.LNAME.MASTER',
        },
        caption: '日历_界面样式及图标',
        codeName: 'calendar_style_icon_captionbar',
        controlType: 'CAPTIONBAR',
        appDataEntityId: 'web.master',
        controlParam: {},
        name: 'captionbar',
        id: 'calendar_style_icon_captionbar',
      },
    ],
    codeName: 'usr0515952537',
    controlType: 'VIEWLAYOUTPANEL',
    logicName: '日历_界面样式及图标布局面板',
    appDataEntityId: 'web.master',
    controlParam: {},
    modelId: '2a2c5cb447b235964d7f5193a9d8fc58',
    modelType: 'PSSYSVIEWLAYOUTPANEL',
    name: 'layoutpanel',
    id: 'usr0515952537',
  },
  title: '日历_界面样式及图标',
  viewStyle: 'DEFAULT',
  viewType: 'DECUSTOMVIEW',
  enableDP: true,
  showCaptionBar: false,
  modelId: 'a067318ee9c153fd9016be2be1117b50',
  modelType: 'PSAPPDEVIEW',
  name: 'MASTERcalendar_style_icon',
  id: 'web.master_calendar_style_icon',
};
