export default {
  tabLayout: 'FLOW',
  loadDefault: true,
  showDataInfoBar: true,
  deviewCodeName: 'grid',
  deviewId: '359f56e3f825ee05782d8a7bf3dff989',
  accUserMode: 3,
  capLanguageRes: {
    lanResTag: 'DE.LNAME.MASTER',
  },
  caption: '表格',
  codeName: 'master_grid',
  appDataEntityId: 'web.master',
  appViewEngines: [
    {
      engineCat: 'VIEW',
      engineType: 'TabExpView',
      id: 'engine',
    },
  ],
  appViewMsgGroupId: 'grid',
  controls: [
    {
      dedrtabPages: [
        {
          caption: '基础',
          appViewId: 'web.master_grid_base',
          id: 'base',
        },
        {
          caption: '列过滤',
          appViewId: 'web.master_grid_filter',
          id: 'filter',
        },
        {
          caption: '布局',
          appViewId: 'web.master_grid_layout',
          id: 'layout',
        },
        {
          caption: '行编辑',
          appViewId: 'web.master_grid_edit',
          id: 'edit',
        },
        {
          caption: '排序',
          appViewId: 'web.master_grid_sort',
          id: 'sort',
        },
        {
          caption: '数据聚合',
          appViewId: 'web.master_grid_aggregation',
          id: 'aggregation',
        },
        {
          caption: '分组',
          appViewId: 'web.master_grid_group',
          id: 'group',
        },
        {
          caption: '内置工具栏',
          appViewId: 'web.master_grid_toolbar',
          id: 'toolbar',
        },
        {
          caption: '操作列',
          appViewId: 'web.master_grid_action_column',
          id: 'action_column',
        },
        {
          caption: '值显示',
          appViewId: 'web.master_grid_value_display',
          id: 'value_display',
        },
        {
          caption: '内置导航',
          appViewId: 'web.master_grid_built_in_nav',
          id: 'built_in_nav',
        },
        {
          caption: '界面样式及图标',
          appViewId: 'web.master_grid_css',
          id: 'css',
        },
        {
          caption: '合并行或列',
          appViewId: 'web.master_grid_span',
          id: 'span',
        },
        {
          caption: '透视表',
          appViewId: 'web.master_pivottable',
          id: 'pivottable',
        },
        {
          caption: '事件及调用',
          appViewId: 'web.master_grid_logic',
          id: 'event_and_call',
        },
      ],
      dataRelationTag: 'grid_DR',
      editItemCapLanguageRes: {
        lanResTag: 'DE.LNAME.MASTER',
      },
      editItemCaption: '主数据',
      uniqueTag: 'master_grid__tabexppanel',
      autoLoad: true,
      showBusyIndicator: true,
      codeName: 'grid_dr',
      controlType: 'DRTAB',
      appDataEntityId: 'web.master',
      controlParam: {
        id: 'tabexppanel',
      },
      modelId: '784e45943073fe37e6864bebef6d2472',
      modelType: 'PSDEDRTAB',
      name: 'tabexppanel',
      id: 'grid_dr',
    },
    {
      capLanguageRes: {
        lanResTag: 'DE.LNAME.MASTER',
      },
      caption: '表格',
      codeName: 'grid_captionbar',
      controlType: 'CAPTIONBAR',
      appDataEntityId: 'web.master',
      controlParam: {},
      name: 'captionbar',
      id: 'grid_captionbar',
    },
  ],
  viewLayoutPanel: {
    layoutBodyOnly: true,
    useDefaultLayout: true,
    layoutPanel: true,
    codeName: 'layoutpanel',
    controlStyle: 'APPDETABEXPVIEW',
    controlType: 'VIEWLAYOUTPANEL',
    appDataEntityId: 'web.master',
    controlParam: {},
    id: 'layoutpanel',
  },
  title: '表格',
  viewStyle: 'DEFAULT',
  viewType: 'DETABEXPVIEW',
  enableDP: true,
  showCaptionBar: false,
  modelId: '70b3789dfe72789d44024f665ad0b53d',
  modelType: 'PSAPPDEVIEW',
  name: 'MASTERgrid',
  id: 'web.master_grid',
};
