export default {
  gridRowActiveMode: 2,
  xdataControlName: 'grid',
  loadDefault: true,
  deviewCodeName: 'grid_toolbar',
  deviewId: 'b3ec4575f497e565cf8755841cdb1c9f',
  accUserMode: 3,
  capLanguageRes: {
    lanResTag: 'DE.LNAME.MASTER',
  },
  caption: '表格_内置工具栏',
  codeName: 'master_grid_toolbar',
  appDataEntityId: 'web.master',
  appViewEngines: [
    {
      engineCat: 'VIEW',
      engineType: 'GridView',
      id: 'engine',
    },
  ],
  appViewLogics: [
    {
      logicTrigger: 'CUSTOM',
      logicType: 'APPUILOGIC',
      builtinAppUILogic: {
        actionAfterWizard: 'DEFAULT',
        newDataAppView: {
          openMode: 'POPUPMODAL',
          refAppViewId: 'web.master_edit_view',
        },
        appUILogicRefViews: [
          {
            openMode: 'POPUPMODAL',
            refAppViewId: 'web.master_edit_view',
          },
        ],
        builtinLogic: true,
        logicType: 'PREDEFINED',
        viewLogicType: 'APP_NEWDATA',
        id: '新建数据',
      },
      builtinLogic: true,
      id: 'newdata',
    },
    {
      logicTrigger: 'CUSTOM',
      logicType: 'APPUILOGIC',
      builtinAppUILogic: {
        openDataAppView: {
          openMode: 'POPUPMODAL',
          refAppViewId: 'web.master_edit_view',
        },
        editMode: true,
        appUILogicRefViews: [
          {
            openMode: 'POPUPMODAL',
            refAppViewId: 'web.master_edit_view',
          },
        ],
        builtinLogic: true,
        logicType: 'PREDEFINED',
        viewLogicType: 'APP_OPENDATA',
        id: '打开数据',
      },
      builtinLogic: true,
      id: 'opendata',
    },
  ],
  appViewMsgGroupId: 'grid_toolbar',
  appViewRefs: [
    {
      realOpenMode: 'POPUPMODAL',
      realTitle: '主数据编辑视图',
      refAppViewId: 'web.master_edit_view',
      name: 'NEWDATA',
      id: 'newdata',
    },
    {
      realOpenMode: 'POPUPMODAL',
      realTitle: '主数据编辑视图',
      refAppViewId: 'web.master_edit_view',
      name: 'EDITDATA',
      id: 'editdata',
    },
  ],
  controls: [
    {
      aggMode: 'NONE',
      columnEnableFilter: 2,
      columnEnableLink: 2,
      groupMode: 'NONE',
      groupStyle: 'DEFAULT',
      degridColumns: [
        {
          clconvertMode: 'NONE',
          dataItemName: 'name',
          excelCaption: '列界面行为组',
          appDEFieldId: 'name',
          deuiactionGroup: {
            uiactionGroupDetails: [
              {
                actionLevel: 200,
                afterItemType: 'NONE',
                beforeItemType: 'NONE',
                buttonStyle: 'DEFAULT',
                caption: '查看详情',
                detailType: 'DEUIACTION',
                uiactionId: 'open_info@master',
                showCaption: true,
                showIcon: true,
                sysImage: {
                  cssClass: 'fa fa-eye',
                  glyph: 'xf06e@FontAwesome',
                },
                id: 'u154f1f9',
              },
              {
                actionLevel: 100,
                afterItemType: 'NONE',
                beforeItemType: 'NONE',
                buttonStyle: 'DEFAULT',
                caption: '打开弹窗',
                detailType: 'DEUIACTION',
                uiactionId: 'open_dialog@master',
                showCaption: true,
                showIcon: true,
                id: 'u3304070',
              },
            ],
            appDataEntityId: 'web.master',
            uniqueTag: 'master__A33d9492128a8fc0fad',
            name: '列界面行为组',
            id: 'a33d9492128a8fc0fad',
          },
          valueType: 'SIMPLE',
          aggMode: 'NONE',
          align: 'LEFT',
          capLanguageRes: {
            lanResTag: 'DEF.LNAME.MASTER.NAME',
          },
          caption: '列界面行为组',
          codeName: 'name',
          columnType: 'DEFGRIDCOLUMN',
          noPrivDisplayMode: 1,
          width: 350,
          widthUnit: 'PX',
          enableSort: true,
          id: 'name',
        },
        {
          clconvertMode: 'FRONT',
          dataItemName: 'type',
          excelCaption: '类型',
          appCodeListId: 'web.mock__cl_categories',
          appDEFieldId: 'type',
          valueType: 'SIMPLE',
          aggMode: 'NONE',
          align: 'LEFT',
          caption: '类型',
          codeName: 'type',
          columnType: 'DEFGRIDCOLUMN',
          noPrivDisplayMode: 1,
          width: 100,
          widthUnit: 'PX',
          enableSort: true,
          id: 'type',
        },
        {
          clconvertMode: 'NONE',
          dataItemName: 'quantity',
          excelCaption: '数量',
          appDEFieldId: 'quantity',
          valueType: 'SIMPLE',
          aggMode: 'NONE',
          align: 'LEFT',
          caption: '数量',
          codeName: 'quantity',
          columnType: 'DEFGRIDCOLUMN',
          noPrivDisplayMode: 1,
          width: 100,
          widthUnit: 'PX',
          enableSort: true,
          id: 'quantity',
        },
      ],
      degridDataItems: [
        {
          appDEFieldId: 'name',
          valueType: 'SIMPLE',
          dataType: 25,
          id: 'name',
        },
        {
          appDEFieldId: 'type',
          valueType: 'SIMPLE',
          dataType: 25,
          id: 'type',
        },
        {
          appDEFieldId: 'quantity',
          valueType: 'SIMPLE',
          dataType: 6,
          id: 'quantity',
        },
        {
          appDEFieldId: 'id',
          valueType: 'SIMPLE',
          dataType: 25,
          id: 'srfkey',
        },
        {
          appDEFieldId: 'id',
          valueType: 'SIMPLE',
          dataType: 25,
          id: 'srfdataaccaction',
        },
        {
          appDEFieldId: 'region_id',
          valueType: 'SIMPLE',
          dataType: 25,
          id: 'region_id',
        },
        {
          appDEFieldId: 'name',
          valueType: 'SIMPLE',
          dataType: 25,
          id: 'srfmajortext',
        },
      ],
      degridEditItems: [
        {
          caption: '标识',
          codeName: 'srfkey',
          enableCond: 3,
          appDEFieldId: 'id',
          editor: {
            editorType: 'HIDDEN',
            valueType: 'SIMPLE',
            editable: true,
            id: 'srfkey',
          },
          allowEmpty: true,
          id: 'srfkey',
        },
      ],
      pagingMode: 1,
      pagingSize: 10,
      sortMode: 'REMOTE',
      enableCustomized: true,
      enablePagingBar: true,
      navViewPos: 'NONE',
      fetchControlAction: {
        appDEMethodId: 'fetch_default',
        appDataEntityId: 'web.master',
        id: 'fetch',
      },
      removeControlAction: {
        appDEMethodId: 'remove',
        appDataEntityId: 'web.master',
        id: 'remove',
      },
      autoLoad: true,
      showBusyIndicator: true,
      controls: [
        {
          detoolbarItems: [
            {
              actionLevel: 100,
              noPrivDisplayMode: 2,
              uiactionId: 'gridview_newaction',
              valid: true,
              capLanguageRes: {
                lanResTag: 'TBB.TEXT.*.NEW',
              },
              caption: '新建',
              itemType: 'DEUIACTION',
              sysImage: {
                cssClass: 'fa fa-file-text-o',
                glyph: 'xf0f6@FontAwesome',
              },
              tooltip: '新建',
              tooltipLanguageRes: {
                lanResTag: 'TBB.TOOLTIP.*.NEW',
              },
              showCaption: true,
              showIcon: true,
              id: 'deuiaction1',
            },
          ],
          codeName: 'grid_toolbar_grid_quicktoolbar',
          controlType: 'TOOLBAR',
          logicName: '快速新建工具栏',
          appDataEntityId: 'web.master',
          controlParam: {
            id: 'grid_quicktoolbar',
          },
          modelId: '58fc08492a7557e91b37e663b09f7dbb',
          modelType: 'PSDETOOLBAR',
          name: 'grid_quicktoolbar',
          id: 'grid_toolbar_grid_quicktoolbar',
        },
        {
          detoolbarItems: [
            {
              actionLevel: 100,
              noPrivDisplayMode: 2,
              uiactionId: 'open_dialog@master',
              uiactionTarget: 'NONE',
              valid: true,
              caption: '打开弹窗',
              itemType: 'DEUIACTION',
              tooltip: '打开弹窗',
              showCaption: true,
              showIcon: true,
              id: 'deuiaction1',
            },
          ],
          codeName: 'grid_toolbar_grid_batchtoolbar',
          controlType: 'TOOLBAR',
          logicName: '批操作工具栏',
          appDataEntityId: 'web.master',
          controlParam: {
            id: 'grid_batchtoolbar',
          },
          modelId: 'a27c6354e5a33f02d8a71c96263bc017',
          modelType: 'PSDETOOLBAR',
          name: 'grid_batchtoolbar',
          id: 'grid_toolbar_grid_batchtoolbar',
        },
      ],
      codeName: 'main8',
      controlType: 'GRID',
      logicName: '表格_内置工具栏_表格',
      appDataEntityId: 'web.master',
      controlParam: {
        id: 'grid',
      },
      modelId: 'a3ca1e820b56e85d2cc87af5ec6b7b57',
      modelType: 'PSDEGRID',
      name: 'grid',
      id: 'web.master.main8',
    },
    {
      searchButtonStyle: 'DEFAULT',
      deformPages: [
        {
          layout: {
            columnCount: 24,
            layout: 'TABLE_24COL',
          },
          caption: '常规条件',
          codeName: 'formpage1',
          detailStyle: 'DEFAULT',
          detailType: 'FORMPAGE',
          id: 'formpage1',
        },
      ],
      layout: {
        columnCount: 24,
        layout: 'TABLE_24COL',
      },
      tabHeaderPos: 'TOP',
      noTabHeader: true,
      autoLoad: true,
      showBusyIndicator: true,
      codeName: 'main24',
      controlType: 'SEARCHFORM',
      logicName: '表格_内置工具栏_搜索表单',
      appDataEntityId: 'web.master',
      controlParam: {
        id: 'searchform',
      },
      modelId: 'ab08aff1393a5adfd014107d6f9de523',
      modelType: 'PSDEFORM_SEARCHFORM',
      name: 'searchform',
      id: 'web.master.main24',
    },
    {
      xdataControlName: 'grid',
      codeName: 'grid_toolbar_toolbar',
      controlType: 'TOOLBAR',
      logicName: '表格_内置工具栏_工具栏',
      appDataEntityId: 'web.master',
      controlParam: {
        id: 'toolbar',
      },
      modelId: '257e0f506bf587dcc0fead5417898802',
      modelType: 'PSDETOOLBAR',
      name: 'toolbar',
      id: 'grid_toolbar_toolbar',
    },
    {
      groupMode: 'SINGLE',
      controlType: 'SEARCHBAR',
      appDataEntityId: 'web.master',
      controlParam: {
        id: 'searchbar',
      },
      id: 'searchbar',
    },
    {
      capLanguageRes: {
        lanResTag: 'DE.LNAME.MASTER',
      },
      caption: '表格_内置工具栏',
      codeName: 'grid_toolbar_captionbar',
      controlType: 'CAPTIONBAR',
      appDataEntityId: 'web.master',
      controlParam: {},
      name: 'captionbar',
      id: 'grid_toolbar_captionbar',
    },
  ],
  viewLayoutPanel: {
    layoutBodyOnly: true,
    useDefaultLayout: true,
    layoutPanel: true,
    codeName: 'layoutpanel',
    controlStyle: 'APPDEGRIDVIEW',
    controlType: 'VIEWLAYOUTPANEL',
    appDataEntityId: 'web.master',
    controlParam: {},
    id: 'layoutpanel',
  },
  title: '表格_内置工具栏',
  viewStyle: 'DEFAULT',
  viewType: 'DEGRIDVIEW',
  enableDP: true,
  showCaptionBar: false,
  modelId: '9d55f533b7ebf993d4882edd8a8c2915',
  modelType: 'PSAPPDEVIEW',
  name: 'MASTERgrid_toolbar',
  id: 'web.master_grid_toolbar',
};
