export default {
  deviewCodeName: 'grid_built_in_nav',
  deviewId: '3f0c04d4955ddfe46051d450b38b2dca',
  accUserMode: 3,
  capLanguageRes: {
    lanResTag: 'DE.LNAME.MASTER',
  },
  caption: '表格_内置导航',
  codeName: 'master_grid_built_in_nav',
  appDataEntityId: 'web.master',
  appViewMsgGroupId: 'grid_built_in_nav',
  viewLayoutPanel: {
    layoutBodyOnly: true,
    viewProxyMode: true,
    layoutMode: 'FLEX',
    layout: {
      layout: 'FLEX',
    },
    rootPanelItems: [
      {
        actionGroupExtractMode: 'ITEM',
        panelItems: [
          {
            actionGroupExtractMode: 'ITEM',
            panelItems: [
              {
                dataRegionType: 'INHERIT',
                panelTabPages: [
                  {
                    panelItems: [
                      {
                        caption: '表格',
                        itemStyle: 'DEFAULT',
                        itemType: 'CTRLPOS',
                        layoutPos: {
                          shrink: 1,
                          layout: 'FLEX',
                        },
                        showCaption: true,
                        id: 'grid',
                      },
                    ],
                    layout: {
                      layout: 'FLEX',
                    },
                    dataRegionType: 'INHERIT',
                    caption: '右侧',
                    itemStyle: 'DEFAULT',
                    itemType: 'TABPAGE',
                    layoutPos: {
                      shrink: 1,
                      layout: 'FLEX',
                    },
                    showCaption: true,
                    id: 'tabpage',
                  },
                  {
                    panelItems: [
                      {
                        caption: '表格',
                        contentHeight: 800,
                        height: 800,
                        itemStyle: 'DEFAULT',
                        itemType: 'CTRLPOS',
                        layoutPos: {
                          shrink: 1,
                          height: 800,
                          heightMode: 'PX',
                          layout: 'FLEX',
                        },
                        showCaption: true,
                        id: 'grid1',
                      },
                    ],
                    layout: {
                      layout: 'FLEX',
                    },
                    dataRegionType: 'INHERIT',
                    caption: '下侧',
                    itemStyle: 'DEFAULT',
                    itemType: 'TABPAGE',
                    layoutPos: {
                      shrink: 1,
                      layout: 'FLEX',
                    },
                    showCaption: true,
                    id: 'tabpage1',
                  },
                  {
                    panelItems: [
                      {
                        caption: '表格',
                        itemStyle: 'DEFAULT',
                        itemType: 'CTRLPOS',
                        layoutPos: {
                          shrink: 1,
                          layout: 'FLEX',
                        },
                        showCaption: true,
                        id: 'grid2',
                      },
                    ],
                    layout: {
                      layout: 'FLEX',
                    },
                    dataRegionType: 'INHERIT',
                    caption: '行明细区',
                    itemStyle: 'DEFAULT',
                    itemType: 'TABPAGE',
                    layoutPos: {
                      shrink: 1,
                      layout: 'FLEX',
                    },
                    showCaption: true,
                    id: 'tabpage2',
                  },
                ],
                caption: '分页部件',
                itemStyle: 'DEFAULT',
                itemType: 'TABPANEL',
                layoutPos: {
                  layoutPos: 'CENTER',
                  layout: 'BORDER',
                  spacingLeft: 'OUTERMEDIUM',
                  spacingRight: 'OUTERMEDIUM',
                },
                id: 'tabpanel',
              },
            ],
            predefinedType: 'CONTAINER_SCROLL_MAIN',
            layout: {
              layout: 'BORDER',
            },
            dataRegionType: 'INHERIT',
            caption: '面板容器',
            itemStyle: 'DEFAULT',
            itemType: 'CONTAINER',
            layoutPos: {
              layoutPos: 'CENTER',
              layout: 'BORDER',
            },
            showCaption: true,
            id: 'container_scroll_main',
          },
        ],
        predefinedType: 'CONTAINER_SCROLL',
        layout: {
          layout: 'BORDER',
        },
        dataRegionType: 'INHERIT',
        caption: '滚动条容器',
        itemStyle: 'DEFAULT',
        itemType: 'CONTAINER',
        layoutPos: {
          shrink: 1,
          layout: 'FLEX',
        },
        id: 'container_scroll',
      },
    ],
    layoutPanel: true,
    controls: [
      {
        aggMode: 'NONE',
        columnEnableFilter: 2,
        columnEnableLink: 2,
        groupMode: 'NONE',
        groupStyle: 'DEFAULT',
        degridColumns: [
          {
            clconvertMode: 'NONE',
            dataItemName: 'name',
            excelCaption: '名称',
            appDEFieldId: 'name',
            valueType: 'SIMPLE',
            aggMode: 'NONE',
            align: 'LEFT',
            capLanguageRes: {
              lanResTag: 'DEF.LNAME.MASTER.NAME',
            },
            caption: '名称',
            codeName: 'name',
            columnType: 'DEFGRIDCOLUMN',
            noPrivDisplayMode: 1,
            width: 150,
            widthUnit: 'PX',
            enableSort: true,
            id: 'name',
          },
        ],
        degridDataItems: [
          {
            appDEFieldId: 'name',
            valueType: 'SIMPLE',
            dataType: 25,
            id: 'name',
          },
          {
            appDEFieldId: 'id',
            valueType: 'SIMPLE',
            dataType: 25,
            id: 'srfkey',
          },
          {
            appDEFieldId: 'id',
            valueType: 'SIMPLE',
            dataType: 25,
            id: 'srfdataaccaction',
          },
          {
            appDEFieldId: 'region_id',
            valueType: 'SIMPLE',
            dataType: 25,
            id: 'region_id',
          },
          {
            appDEFieldId: 'name',
            valueType: 'SIMPLE',
            dataType: 25,
            id: 'srfmajortext',
          },
        ],
        degridEditItems: [
          {
            caption: '标识',
            codeName: 'srfkey',
            enableCond: 3,
            appDEFieldId: 'id',
            editor: {
              editorType: 'HIDDEN',
              valueType: 'SIMPLE',
              editable: true,
              id: 'srfkey',
            },
            allowEmpty: true,
            id: 'srfkey',
          },
        ],
        pagingMode: 1,
        pagingSize: 10,
        sortMode: 'REMOTE',
        enableCustomized: true,
        enablePagingBar: true,
        navAppViewId: 'web.master_info_view',
        navViewHeight: 300,
        navViewPos: 'BOTTOM',
        fetchControlAction: {
          appDEMethodId: 'fetch_default',
          appDataEntityId: 'web.master',
          id: 'fetch',
        },
        removeControlAction: {
          appDEMethodId: 'remove',
          appDataEntityId: 'web.master',
          id: 'remove',
        },
        autoLoad: true,
        showBusyIndicator: true,
        codeName: 'grid_base15',
        controlType: 'GRID',
        logicName: '表格_内置导航_下方',
        appDataEntityId: 'web.master',
        controlParam: {
          id: 'grid1',
        },
        modelId: 'fffcc1ffb79bbe7b00d24e311cd47698',
        modelType: 'PSDEGRID',
        name: 'grid1',
        id: 'web.master.grid_base15',
      },
      {
        aggMode: 'NONE',
        columnEnableFilter: 2,
        columnEnableLink: 2,
        groupMode: 'NONE',
        groupStyle: 'DEFAULT',
        degridColumns: [
          {
            clconvertMode: 'NONE',
            dataItemName: 'name',
            excelCaption: '名称',
            appDEFieldId: 'name',
            valueType: 'SIMPLE',
            aggMode: 'NONE',
            align: 'LEFT',
            capLanguageRes: {
              lanResTag: 'DEF.LNAME.MASTER.NAME',
            },
            caption: '名称',
            codeName: 'name',
            columnType: 'DEFGRIDCOLUMN',
            noPrivDisplayMode: 1,
            width: 150,
            widthUnit: 'PX',
            enableSort: true,
            id: 'name',
          },
        ],
        degridDataItems: [
          {
            appDEFieldId: 'name',
            valueType: 'SIMPLE',
            dataType: 25,
            id: 'name',
          },
          {
            appDEFieldId: 'id',
            valueType: 'SIMPLE',
            dataType: 25,
            id: 'srfkey',
          },
          {
            appDEFieldId: 'id',
            valueType: 'SIMPLE',
            dataType: 25,
            id: 'srfdataaccaction',
          },
          {
            appDEFieldId: 'region_id',
            valueType: 'SIMPLE',
            dataType: 25,
            id: 'region_id',
          },
          {
            appDEFieldId: 'name',
            valueType: 'SIMPLE',
            dataType: 25,
            id: 'srfmajortext',
          },
        ],
        degridEditItems: [
          {
            caption: '标识',
            codeName: 'srfkey',
            enableCond: 3,
            appDEFieldId: 'id',
            editor: {
              editorType: 'HIDDEN',
              valueType: 'SIMPLE',
              editable: true,
              id: 'srfkey',
            },
            allowEmpty: true,
            id: 'srfkey',
          },
        ],
        pagingMode: 1,
        pagingSize: 10,
        sortMode: 'REMOTE',
        enableCustomized: true,
        enablePagingBar: true,
        navAppViewId: 'web.master_info_view',
        navViewPos: 'RIGHT',
        fetchControlAction: {
          appDEMethodId: 'fetch_default',
          appDataEntityId: 'web.master',
          id: 'fetch',
        },
        removeControlAction: {
          appDEMethodId: 'remove',
          appDataEntityId: 'web.master',
          id: 'remove',
        },
        autoLoad: true,
        showBusyIndicator: true,
        codeName: 'grid_base14',
        controlType: 'GRID',
        logicName: '表格_内置导航_右方',
        appDataEntityId: 'web.master',
        controlParam: {
          id: 'grid',
        },
        modelId: '0ed2dc7ccf83cee17c6ee3d3461749ee',
        modelType: 'PSDEGRID',
        name: 'grid',
        id: 'web.master.grid_base14',
      },
      {
        aggMode: 'NONE',
        columnEnableFilter: 2,
        columnEnableLink: 2,
        groupMode: 'NONE',
        groupStyle: 'DEFAULT',
        degridColumns: [
          {
            clconvertMode: 'NONE',
            dataItemName: 'name',
            excelCaption: '名称',
            appDEFieldId: 'name',
            valueType: 'SIMPLE',
            aggMode: 'NONE',
            align: 'LEFT',
            capLanguageRes: {
              lanResTag: 'DEF.LNAME.MASTER.NAME',
            },
            caption: '名称',
            codeName: 'name',
            columnType: 'DEFGRIDCOLUMN',
            noPrivDisplayMode: 1,
            width: 150,
            widthUnit: 'PX',
            enableSort: true,
            id: 'name',
          },
        ],
        degridDataItems: [
          {
            appDEFieldId: 'name',
            valueType: 'SIMPLE',
            dataType: 25,
            id: 'name',
          },
          {
            appDEFieldId: 'id',
            valueType: 'SIMPLE',
            dataType: 25,
            id: 'srfkey',
          },
          {
            appDEFieldId: 'id',
            valueType: 'SIMPLE',
            dataType: 25,
            id: 'srfdataaccaction',
          },
          {
            appDEFieldId: 'region_id',
            valueType: 'SIMPLE',
            dataType: 25,
            id: 'region_id',
          },
          {
            appDEFieldId: 'name',
            valueType: 'SIMPLE',
            dataType: 25,
            id: 'srfmajortext',
          },
        ],
        degridEditItems: [
          {
            caption: '标识',
            codeName: 'srfkey',
            enableCond: 3,
            appDEFieldId: 'id',
            editor: {
              editorType: 'HIDDEN',
              valueType: 'SIMPLE',
              editable: true,
              id: 'srfkey',
            },
            allowEmpty: true,
            id: 'srfkey',
          },
        ],
        pagingMode: 1,
        pagingSize: 10,
        sortMode: 'REMOTE',
        enableCustomized: true,
        enablePagingBar: true,
        navAppViewId: 'web.master_info_view',
        navViewPos: 'ROWDETAIL',
        fetchControlAction: {
          appDEMethodId: 'fetch_default',
          appDataEntityId: 'web.master',
          id: 'fetch',
        },
        removeControlAction: {
          appDEMethodId: 'remove',
          appDataEntityId: 'web.master',
          id: 'remove',
        },
        autoLoad: true,
        showBusyIndicator: true,
        codeName: 'grid_base16',
        controlType: 'GRID',
        logicName: '表格_内置导航_行明细区',
        appDataEntityId: 'web.master',
        controlParam: {
          id: 'grid2',
        },
        modelId: '5116b3288f555cad57e4820df5d90b08',
        modelType: 'PSDEGRID',
        name: 'grid2',
        id: 'web.master.grid_base16',
      },
      {
        capLanguageRes: {
          lanResTag: 'DE.LNAME.MASTER',
        },
        caption: '表格_内置导航',
        codeName: 'grid_built_in_nav_captionbar',
        controlType: 'CAPTIONBAR',
        appDataEntityId: 'web.master',
        controlParam: {},
        name: 'captionbar',
        id: 'grid_built_in_nav_captionbar',
      },
    ],
    codeName: 'a9750515d3fdc635771',
    controlType: 'VIEWLAYOUTPANEL',
    logicName: 'grid_built_in_nav',
    appDataEntityId: 'web.master',
    controlParam: {},
    modelId: '484c664638cd2898639d75497446cf3b',
    modelType: 'PSSYSVIEWLAYOUTPANEL',
    name: 'layoutpanel',
    id: 'a9750515d3fdc635771',
  },
  title: '表格_内置导航',
  viewStyle: 'DEFAULT',
  viewType: 'DECUSTOMVIEW',
  enableDP: true,
  showCaptionBar: false,
  modelId: '64ea22bc892472f142b414148dcb8978',
  modelType: 'PSAPPDEVIEW',
  name: 'MASTERgrid_built_in_nav',
  id: 'web.master_grid_built_in_nav',
};
