export default {
  enableDirtyChecking: true,
  showDataInfoBar: true,
  xdataControlName: 'form',
  loadDefault: true,
  deviewCodeName: 'editor_date_picker',
  deviewId: 'bda36e3dbb1f37602aa8537a2b14df0c',
  accUserMode: 3,
  capLanguageRes: {
    lanResTag: 'DE.LNAME.MASTER',
  },
  caption: '编辑器_时间选择器',
  codeName: 'master_editor_date_picker',
  appDataEntityId: 'web.master',
  appViewEngines: [
    {
      engineCat: 'VIEW',
      engineType: 'EditView',
      id: 'engine',
    },
  ],
  appViewMsgGroupId: 'editor_date_picker',
  controls: [
    {
      xdataControlName: 'form',
      codeName: 'editor_date_picker_toolbar',
      controlType: 'TOOLBAR',
      logicName: '编辑器_时间选择器_工具栏',
      appDataEntityId: 'web.master',
      controlParam: {
        id: 'toolbar',
      },
      modelId: '8976f75b701a1dcc28c91ac256e933c9',
      modelType: 'PSDETOOLBAR',
      name: 'toolbar',
      id: 'editor_date_picker_toolbar',
    },
    {
      createControlAction: {
        appDEMethodId: 'create',
        appDataEntityId: 'web.master',
        id: 'create',
      },
      getDraftFromControlAction: {
        appDataEntityId: 'web.master',
        id: 'loaddraftfrom',
      },
      getDraftControlAction: {
        appDEMethodId: 'get_draft',
        appDataEntityId: 'web.master',
        id: 'loaddraft',
      },
      getControlAction: {
        appDEMethodId: 'get',
        appDataEntityId: 'web.master',
        id: 'load',
      },
      removeControlAction: {
        appDEMethodId: 'remove',
        appDataEntityId: 'web.master',
        id: 'remove',
      },
      updateControlAction: {
        appDEMethodId: 'update',
        appDataEntityId: 'web.master',
        id: 'update',
      },
      deformPages: [
        {
          layout: {
            columnCount: 24,
            layout: 'TABLE_24COL',
          },
          deformDetails: [
            {
              layout: {
                columnCount: 24,
                layout: 'TABLE_24COL',
              },
              deformDetails: [
                {
                  dataType: 25,
                  enableCond: 3,
                  itemWidth: 160,
                  labelPos: 'NONE',
                  noPrivDisplayMode: 1,
                  editor: {
                    dateTimeFormat: 'YYYY-MM-DD HH:mm:ss',
                    editorParams: {
                      TIMEFMT: 'YYYY-MM-DD HH:mm:ss',
                    },
                    editorType: 'DATEPICKER',
                    editorWidth: 160,
                    valueType: 'SIMPLE',
                    editable: true,
                    id: 'formitem',
                  },
                  allowEmpty: true,
                  caption: '时间选择器',
                  codeName: 'formitem',
                  detailStyle: 'DEFAULT',
                  detailType: 'FORMITEM',
                  layoutPos: {
                    colMD: 24,
                    layout: 'TABLE_24COL',
                  },
                  id: 'formitem',
                },
              ],
              caption: '时间选择器',
              codeName: 'group1',
              detailStyle: 'DEFAULT',
              detailType: 'GROUPPANEL',
              layoutPos: {
                colMD: 24,
                layout: 'TABLE_24COL',
              },
              showCaption: true,
              id: 'group1',
            },
            {
              layout: {
                columnCount: 24,
                layout: 'TABLE_24COL',
              },
              deformDetails: [
                {
                  dataType: 25,
                  enableCond: 3,
                  itemWidth: 100,
                  labelPos: 'NONE',
                  noPrivDisplayMode: 1,
                  editor: {
                    dateTimeFormat: 'YYYY-MM-DD',
                    editorParams: {
                      TIMEFMT: 'YYYY-MM-DD',
                    },
                    editorType: 'DATEPICKEREX_NOTIME',
                    editorWidth: 100,
                    valueType: 'SIMPLE',
                    editable: true,
                    id: 'formitem1',
                  },
                  allowEmpty: true,
                  caption: '时间选择器（YYYY-MM-DD）',
                  codeName: 'formitem1',
                  detailStyle: 'DEFAULT',
                  detailType: 'FORMITEM',
                  layoutPos: {
                    colMD: 24,
                    layout: 'TABLE_24COL',
                  },
                  id: 'formitem1',
                },
              ],
              caption: '时间选择器（YYYY-MM-DD）',
              codeName: 'grouppanel1',
              detailStyle: 'DEFAULT',
              detailType: 'GROUPPANEL',
              layoutPos: {
                colMD: 24,
                layout: 'TABLE_24COL',
              },
              showCaption: true,
              id: 'grouppanel1',
            },
            {
              layout: {
                columnCount: 24,
                layout: 'TABLE_24COL',
              },
              deformDetails: [
                {
                  dataType: 25,
                  enableCond: 3,
                  itemWidth: 120,
                  labelPos: 'NONE',
                  noPrivDisplayMode: 1,
                  editor: {
                    dateTimeFormat: 'YYYY-MM-DD HH',
                    editorParams: {
                      TIMEFMT: 'YYYY-MM-DD HH',
                    },
                    editorType: 'DATEPICKEREX_HOUR',
                    editorWidth: 120,
                    valueType: 'SIMPLE',
                    editable: true,
                    id: 'formitem3',
                  },
                  allowEmpty: true,
                  caption: '时间选择器（YYYY-MM-DD、HH）',
                  codeName: 'formitem3',
                  detailStyle: 'DEFAULT',
                  detailType: 'FORMITEM',
                  layoutPos: {
                    colMD: 24,
                    layout: 'TABLE_24COL',
                  },
                  id: 'formitem3',
                },
              ],
              caption: '时间选择器（YYYY-MM-DD、HH）',
              codeName: 'grouppanel3',
              detailStyle: 'DEFAULT',
              detailType: 'GROUPPANEL',
              layoutPos: {
                colMD: 24,
                layout: 'TABLE_24COL',
              },
              showCaption: true,
              id: 'grouppanel3',
            },
            {
              layout: {
                columnCount: 24,
                layout: 'TABLE_24COL',
              },
              deformDetails: [
                {
                  dataType: 25,
                  enableCond: 3,
                  itemWidth: 140,
                  labelPos: 'NONE',
                  noPrivDisplayMode: 1,
                  editor: {
                    dateTimeFormat: 'YYYY-MM-DD HH:mm',
                    editorParams: {
                      TIMEFMT: 'YYYY-MM-DD HH:mm',
                    },
                    editorType: 'DATEPICKEREX_MINUTE',
                    editorWidth: 140,
                    valueType: 'SIMPLE',
                    editable: true,
                    id: 'formitem4',
                  },
                  allowEmpty: true,
                  caption: '时间选择器（YYYY-MM-DD、HH:mm）',
                  codeName: 'formitem4',
                  detailStyle: 'DEFAULT',
                  detailType: 'FORMITEM',
                  layoutPos: {
                    colMD: 24,
                    layout: 'TABLE_24COL',
                  },
                  id: 'formitem4',
                },
              ],
              caption: '时间选择器（YYYY-MM-DD、HH:mm）',
              codeName: 'grouppanel4',
              detailStyle: 'DEFAULT',
              detailType: 'GROUPPANEL',
              layoutPos: {
                colMD: 24,
                layout: 'TABLE_24COL',
              },
              showCaption: true,
              id: 'grouppanel4',
            },
            {
              layout: {
                columnCount: 24,
                layout: 'TABLE_24COL',
              },
              deformDetails: [
                {
                  dataType: 25,
                  enableCond: 3,
                  itemWidth: 160,
                  labelPos: 'NONE',
                  noPrivDisplayMode: 1,
                  editor: {
                    dateTimeFormat: 'YYYY-MM-DD HH:mm:ss',
                    editorParams: {
                      TIMEFMT: 'YYYY-MM-DD HH:mm:ss',
                    },
                    editorType: 'DATEPICKEREX_SECOND',
                    editorWidth: 160,
                    valueType: 'SIMPLE',
                    editable: true,
                    id: 'formitem5',
                  },
                  allowEmpty: true,
                  caption: '时间选择器（YYYY-MM-DD、HH:mm:ss）',
                  codeName: 'formitem5',
                  detailStyle: 'DEFAULT',
                  detailType: 'FORMITEM',
                  layoutPos: {
                    colMD: 24,
                    layout: 'TABLE_24COL',
                  },
                  id: 'formitem5',
                },
              ],
              caption: '时间选择器（YYYY-MM-DD、HH:mm:ss）',
              codeName: 'grouppanel5',
              detailStyle: 'DEFAULT',
              detailType: 'GROUPPANEL',
              layoutPos: {
                colMD: 24,
                layout: 'TABLE_24COL',
              },
              showCaption: true,
              id: 'grouppanel5',
            },
            {
              layout: {
                columnCount: 24,
                layout: 'TABLE_24COL',
              },
              deformDetails: [
                {
                  dataType: 25,
                  enableCond: 3,
                  itemWidth: 90,
                  labelPos: 'NONE',
                  noPrivDisplayMode: 1,
                  editor: {
                    dateTimeFormat: 'HH:mm:ss',
                    editorParams: {
                      TIMEFMT: 'HH:mm:ss',
                    },
                    editorType: 'DATEPICKEREX_NODAY',
                    editorWidth: 90,
                    valueType: 'SIMPLE',
                    editable: true,
                    id: 'formitem6',
                  },
                  allowEmpty: true,
                  caption: '时间选择器（HH:mm:ss）',
                  codeName: 'formitem6',
                  detailStyle: 'DEFAULT',
                  detailType: 'FORMITEM',
                  layoutPos: {
                    colMD: 24,
                    layout: 'TABLE_24COL',
                  },
                  id: 'formitem6',
                },
              ],
              caption: '时间选择器（HH:mm:ss）',
              codeName: 'grouppanel6',
              detailStyle: 'DEFAULT',
              detailType: 'GROUPPANEL',
              layoutPos: {
                colMD: 24,
                layout: 'TABLE_24COL',
              },
              showCaption: true,
              id: 'grouppanel6',
            },
            {
              layout: {
                columnCount: 24,
                layout: 'TABLE_24COL',
              },
              deformDetails: [
                {
                  dataType: 25,
                  enableCond: 3,
                  itemWidth: 70,
                  labelPos: 'NONE',
                  noPrivDisplayMode: 1,
                  editor: {
                    dateTimeFormat: 'HH:mm',
                    editorParams: {
                      TIMEFMT: 'HH:mm',
                    },
                    editorType: 'DATEPICKEREX_NODAY_NOSECOND',
                    editorWidth: 70,
                    valueType: 'SIMPLE',
                    editable: true,
                    id: 'formitem7',
                  },
                  allowEmpty: true,
                  caption: '时间选择器（HH:mm）',
                  codeName: 'formitem7',
                  detailStyle: 'DEFAULT',
                  detailType: 'FORMITEM',
                  layoutPos: {
                    colMD: 24,
                    layout: 'TABLE_24COL',
                  },
                  id: 'formitem7',
                },
              ],
              caption: '时间选择器（HH:mm）',
              codeName: 'grouppanel7',
              detailStyle: 'DEFAULT',
              detailType: 'GROUPPANEL',
              layoutPos: {
                colMD: 24,
                layout: 'TABLE_24COL',
              },
              showCaption: true,
              id: 'grouppanel7',
            },
            {
              layout: {
                columnCount: 24,
                layout: 'TABLE_24COL',
              },
              deformDetails: [
                {
                  dataType: 25,
                  enableCond: 3,
                  itemWidth: 160,
                  labelPos: 'NONE',
                  noPrivDisplayMode: 1,
                  editor: {
                    dateTimeFormat: 'YYYY-MM-DD HH:mm:ss',
                    editorParams: {
                      TIMEFMT: 'YYYY-MM-DD HH:mm:ss',
                    },
                    editorType: 'DATEPICKER',
                    editorWidth: 160,
                    valueType: 'SIMPLE',
                    editable: true,
                    id: 'dateyyyymm',
                  },
                  allowEmpty: true,
                  caption: '时间选择器（年月）',
                  codeName: 'dateyyyymm',
                  detailStyle: 'DEFAULT',
                  detailType: 'FORMITEM',
                  controlAttributes: [
                    {
                      attrName: 'valueFormat',
                      attrValue: "'YYYY-MM'",
                      name: 'dateyyyymm_valueFormat',
                      id: 'dateyyyymm_valueformat',
                    },
                    {
                      attrName: 'type',
                      attrValue: "'month'",
                      id: 'dateyyyymm_type',
                    },
                    {
                      attrName: 'format',
                      attrValue: "'YYYY-MM'",
                      id: 'dateyyyymm_format',
                    },
                  ],
                  layoutPos: {
                    colMD: 24,
                    layout: 'TABLE_24COL',
                  },
                  id: 'dateyyyymm',
                },
              ],
              caption: '时间选择器（年月）',
              codeName: 'grouppanel8',
              detailStyle: 'DEFAULT',
              detailType: 'GROUPPANEL',
              layoutPos: {
                colMD: 24,
                layout: 'TABLE_24COL',
              },
              showCaption: true,
              id: 'grouppanel8',
            },
            {
              dataType: 25,
              enableCond: 3,
              labelPos: 'LEFT',
              labelWidth: 130,
              noPrivDisplayMode: 1,
              appDEFieldId: 'id',
              editor: {
                editorType: 'HIDDEN',
                valueType: 'SIMPLE',
                editable: true,
                id: 'id',
              },
              allowEmpty: true,
              hidden: true,
              capLanguageRes: {
                lanResTag: 'DEF.LNAME.MASTER.ID',
              },
              caption: '标识',
              codeName: 'id',
              detailStyle: 'DEFAULT',
              detailType: 'FORMITEM',
              layoutPos: {
                colMD: 24,
                layout: 'TABLE_24COL',
              },
              id: 'id',
            },
          ],
          caption: '时间选择器',
          codeName: 'formpage1',
          detailStyle: 'DEFAULT',
          detailType: 'FORMPAGE',
          id: 'formpage1',
        },
      ],
      layout: {
        columnCount: 24,
        layout: 'TABLE_24COL',
      },
      tabHeaderPos: 'TOP',
      noTabHeader: true,
      autoLoad: true,
      showBusyIndicator: true,
      codeName: 'main39',
      controlType: 'FORM',
      logicName: '编辑器_时间选择器_表单',
      appDataEntityId: 'web.master',
      controlParam: {
        id: 'form',
      },
      modelId: 'e7f23ffe5c5df9f291a1273b3d5ff72a',
      modelType: 'PSDEFORM_EDITFORM',
      name: 'form',
      id: 'web.master.main39',
    },
    {
      codeName: 'editor_date_picker_datainfobar',
      controlType: 'DATAINFOBAR',
      appDataEntityId: 'web.master',
      controlParam: {
        id: 'datainfobar',
      },
      name: 'datainfobar',
      id: 'editor_date_picker_datainfobar',
    },
    {
      capLanguageRes: {
        lanResTag: 'DE.LNAME.MASTER',
      },
      caption: '编辑器_时间选择器',
      codeName: 'editor_date_picker_captionbar',
      controlType: 'CAPTIONBAR',
      appDataEntityId: 'web.master',
      controlParam: {},
      name: 'captionbar',
      id: 'editor_date_picker_captionbar',
    },
  ],
  viewLayoutPanel: {
    layoutBodyOnly: true,
    useDefaultLayout: true,
    layoutPanel: true,
    codeName: 'layoutpanel',
    controlStyle: 'APPDEEDITVIEW',
    controlType: 'VIEWLAYOUTPANEL',
    appDataEntityId: 'web.master',
    controlParam: {},
    id: 'layoutpanel',
  },
  title: '编辑器_时间选择器',
  viewStyle: 'DEFAULT',
  viewType: 'DEEDITVIEW',
  enableDP: true,
  showCaptionBar: false,
  modelId: '3344df8121ee6a2834e636f7d5dfa135',
  modelType: 'PSAPPDEVIEW',
  name: 'MASTEReditor_date_picker',
  id: 'web.master_editor_date_picker',
};
