export default {
  tabLayout: 'TOP',
  loadDefault: true,
  showDataInfoBar: true,
  deviewCodeName: 'tab_ctrl_federation2',
  deviewId: '21fa9d811823403849dbb02b85b08274',
  accUserMode: 2,
  capLanguageRes: {
    lanResTag: 'DE.LNAME.MASTER',
  },
  caption: '数据关系部件融合视图2',
  codeName: 'master_tab_ctrl_federation2',
  appDataEntityId: 'web.master',
  appViewEngines: [
    {
      engineCat: 'VIEW',
      engineType: 'TabExpView',
      id: 'engine',
    },
  ],
  controls: [
    {
      dedrtabPages: [
        {
          caption: '表格_基础',
          appViewId: 'web.master_grid_base',
          id: 'pitem1',
        },
        {
          caption: '主应用分页1',
          appViewId: 'web.master_list_base',
          id: 'pitem2',
        },
      ],
      dataRelationTag: 'DataRelation7',
      editItemCapLanguageRes: {
        lanResTag: 'DE.LNAME.MASTER',
      },
      editItemCaption: '主数据',
      uniqueTag: 'master_tab_ctrl_federation2__tabexppanel',
      autoLoad: true,
      showBusyIndicator: true,
      codeName: 'data_relation7',
      controlType: 'DRTAB',
      appDataEntityId: 'web.master',
      controlParam: {
        id: 'tabexppanel',
      },
      modelId: '6d8a7e4b6d6927dceac4532aa68fce07',
      modelType: 'PSDEDRTAB',
      name: 'tabexppanel',
      id: 'data_relation7',
    },
    {
      capLanguageRes: {
        lanResTag: 'DE.LNAME.MASTER',
      },
      caption: '数据关系部件融合视图2',
      codeName: 'tab_ctrl_federation2_captionbar',
      controlType: 'CAPTIONBAR',
      appDataEntityId: 'web.master',
      controlParam: {},
      name: 'captionbar',
      id: 'tab_ctrl_federation2_captionbar',
    },
  ],
  viewLayoutPanel: {
    layoutBodyOnly: true,
    useDefaultLayout: true,
    layoutPanel: true,
    codeName: 'layoutpanel',
    controlStyle: 'APPDETABEXPVIEW',
    controlType: 'VIEWLAYOUTPANEL',
    appDataEntityId: 'web.master',
    controlParam: {},
    id: 'layoutpanel',
  },
  title: '数据关系部件融合视图2',
  viewStyle: 'DEFAULT',
  viewType: 'DETABEXPVIEW',
  enableDP: true,
  showCaptionBar: false,
  modelId: 'ef8e1eb7bb95c31e3a303766d69cb725',
  modelType: 'PSAPPDEVIEW',
  name: 'MASTERtab_ctrl_federation2',
  id: 'web.master_tab_ctrl_federation2',
};
