export default {
  tabLayout: 'FLOW',
  loadDefault: true,
  showDataInfoBar: true,
  deviewCodeName: 'ui_action',
  deviewId: 'b4938c96f30f51ed13ce8404628cc06f',
  accUserMode: 3,
  capLanguageRes: {
    lanResTag: 'DE.LNAME.MASTER',
  },
  caption: '界面行为',
  codeName: 'master_ui_action',
  appDataEntityId: 'web.master',
  appViewEngines: [
    {
      engineCat: 'VIEW',
      engineType: 'TabExpView',
      id: 'engine',
    },
  ],
  appViewMsgGroupId: 'ui_action',
  controls: [
    {
      dedrtabPages: [
        {
          caption: '常规',
          appViewId: 'web.master_ui_action_base',
          id: 'base',
        },
        {
          caption: '样式及图标',
          appViewId: 'web.master_ui_action_cssandicon',
          id: 'css',
        },
        {
          caption: '行为参数',
          appViewId: 'web.master_ui_action_parameter',
          id: 'parameter',
        },
        {
          caption: '逻辑',
          appViewId: 'web.master_ui_action_logic',
          id: 'logic',
        },
      ],
      dataRelationTag: 'ui_action_DR',
      editItemCapLanguageRes: {
        lanResTag: 'DE.LNAME.MASTER',
      },
      editItemCaption: '主数据',
      uniqueTag: 'master_ui_action__tabexppanel',
      autoLoad: true,
      showBusyIndicator: true,
      codeName: 'ui_action_dr',
      controlType: 'DRTAB',
      appDataEntityId: 'web.master',
      controlParam: {
        id: 'tabexppanel',
      },
      modelId: 'ebf9f61bd13d4992406b66f4bd75158c',
      modelType: 'PSDEDRTAB',
      name: 'tabexppanel',
      id: 'ui_action_dr',
    },
    {
      capLanguageRes: {
        lanResTag: 'DE.LNAME.MASTER',
      },
      caption: '界面行为',
      codeName: 'ui_action_captionbar',
      controlType: 'CAPTIONBAR',
      appDataEntityId: 'web.master',
      controlParam: {},
      name: 'captionbar',
      id: 'ui_action_captionbar',
    },
  ],
  viewLayoutPanel: {
    layoutBodyOnly: true,
    useDefaultLayout: true,
    layoutPanel: true,
    codeName: 'layoutpanel',
    controlStyle: 'APPDETABEXPVIEW',
    controlType: 'VIEWLAYOUTPANEL',
    appDataEntityId: 'web.master',
    controlParam: {},
    id: 'layoutpanel',
  },
  title: '界面行为',
  viewStyle: 'DEFAULT',
  viewType: 'DETABEXPVIEW',
  enableDP: true,
  showCaptionBar: false,
  modelId: '2615e864566b940be8478de82e4ee637',
  modelType: 'PSAPPDEVIEW',
  name: 'MASTERui_action',
  id: 'web.master_ui_action',
};
