export default {
  tabLayout: 'TOP',
  loadDefault: true,
  showDataInfoBar: true,
  deviewCodeName: 'tab_exp_view',
  deviewId: '38f9339d019047d58889ef30d33cc897',
  accUserMode: 3,
  capLanguageRes: {
    lanResTag: 'DE.LNAME.MASTER',
  },
  caption: '分页导航视图',
  codeName: 'master_tab_exp_view',
  appDataEntityId: 'web.master',
  appViewEngines: [
    {
      engineCat: 'VIEW',
      engineType: 'TabExpView',
      id: 'engine',
    },
  ],
  appViewMsgGroupId: 'tab_exp_view_group',
  controls: [
    {
      dedrtabPages: [
        {
          caption: '分页1-区划',
          appViewId: 'web.region_grid_view',
          id: 'region',
        },
        {
          caption: '分页2-分类',
          appViewId: 'web.category_grid_view',
          id: 'category',
        },
        {
          caption: '分页3-主数据',
          appViewId: 'web.master_grid_view',
          id: 'master',
        },
      ],
      dataRelationTag: 'tab_exp_view_DR',
      editItemCapLanguageRes: {
        lanResTag: 'DE.LNAME.MASTER',
      },
      editItemCaption: '主数据',
      uniqueTag: 'master_tab_exp_view__tabexppanel',
      autoLoad: true,
      showBusyIndicator: true,
      codeName: 'tab_exp_view_dr',
      controlType: 'DRTAB',
      appDataEntityId: 'web.master',
      controlParam: {
        id: 'tabexppanel',
      },
      modelId: '99d608efdd112d331096ea395dbcd20e',
      modelType: 'PSDEDRTAB',
      name: 'tabexppanel',
      id: 'tab_exp_view_dr',
    },
    {
      capLanguageRes: {
        lanResTag: 'DE.LNAME.MASTER',
      },
      caption: '分页导航视图',
      codeName: 'tab_exp_view_captionbar',
      controlType: 'CAPTIONBAR',
      appDataEntityId: 'web.master',
      controlParam: {},
      name: 'captionbar',
      id: 'tab_exp_view_captionbar',
    },
  ],
  viewLayoutPanel: {
    layoutBodyOnly: true,
    useDefaultLayout: true,
    layoutPanel: true,
    codeName: 'layoutpanel',
    controlStyle: 'APPDETABEXPVIEW',
    controlType: 'VIEWLAYOUTPANEL',
    appDataEntityId: 'web.master',
    controlParam: {},
    id: 'layoutpanel',
  },
  title: '分页导航视图',
  viewStyle: 'DEFAULT',
  viewType: 'DETABEXPVIEW',
  enableDP: true,
  showCaptionBar: false,
  modelId: '298bdba26661d9b6487d366c898c2531',
  modelType: 'PSAPPDEVIEW',
  name: 'MASTERtab_exp_view',
  id: 'web.master_tab_exp_view',
};
