export default {
  enableDirtyChecking: true,
  showDataInfoBar: true,
  xdataControlName: 'form',
  loadDefault: true,
  deviewCodeName: 'upload_image_preview',
  deviewId: '829c3c1afb6d36a53f252ddcdc09b7e1',
  accUserMode: 3,
  capLanguageRes: {
    lanResTag: 'DE.LNAME.MASTER',
  },
  caption: '编辑器_图片预览',
  codeName: 'master_upload_image_preview',
  appDataEntityId: 'web.master',
  appViewEngines: [
    {
      engineCat: 'VIEW',
      engineType: 'EditView',
      id: 'engine',
    },
  ],
  appViewMsgGroupId: 'upload_image_preview',
  controls: [
    {
      xdataControlName: 'form',
      codeName: 'upload_image_preview_toolbar',
      controlType: 'TOOLBAR',
      logicName: '编辑器_图片预览_工具栏',
      appDataEntityId: 'web.master',
      controlParam: {
        id: 'toolbar',
      },
      modelId: 'c7f7bd793309dcbe8308e0d7fced3d54',
      modelType: 'PSDETOOLBAR',
      name: 'toolbar',
      id: 'upload_image_preview_toolbar',
    },
    {
      createControlAction: {
        appDEMethodId: 'create',
        appDataEntityId: 'web.master',
        id: 'create',
      },
      getDraftFromControlAction: {
        appDataEntityId: 'web.master',
        id: 'loaddraftfrom',
      },
      getDraftControlAction: {
        appDEMethodId: 'get_draft',
        appDataEntityId: 'web.master',
        id: 'loaddraft',
      },
      getControlAction: {
        appDEMethodId: 'get',
        appDataEntityId: 'web.master',
        id: 'load',
      },
      removeControlAction: {
        appDEMethodId: 'remove',
        appDataEntityId: 'web.master',
        id: 'remove',
      },
      updateControlAction: {
        appDEMethodId: 'update',
        appDataEntityId: 'web.master',
        id: 'update',
      },
      deformPages: [
        {
          layout: {
            columnCount: 24,
            layout: 'TABLE_24COL',
          },
          deformDetails: [
            {
              layout: {
                columnCount: 24,
                layout: 'TABLE_24COL',
              },
              deformDetails: [
                {
                  createDV:
                    'https://open.ibizlab.cn/quickstart/assets/images/user-avatar.png',
                  dataType: 25,
                  enableCond: 3,
                  labelPos: 'NONE',
                  noPrivDisplayMode: 1,
                  appDEFieldId: 'image',
                  editor: {
                    editorParams: {
                      RAWCONTENT: 'TRUE',
                      MAXCOUNT: '1',
                    },
                    editorType: 'PICTURE_ONE_RAW',
                    valueType: 'SIMPLE',
                    editable: true,
                    id: 'formitem',
                  },
                  updateDV:
                    'https://open.ibizlab.cn/quickstart/assets/images/user-avatar.png',
                  allowEmpty: true,
                  caption: '图片预览_表单',
                  codeName: 'formitem',
                  contentHeight: 400,
                  contentWidth: 400,
                  detailStyle: 'DEFAULT',
                  detailType: 'FORMITEM',
                  height: 400,
                  layoutPos: {
                    colMD: 24,
                    height: 400,
                    heightMode: 'PX',
                    layout: 'TABLE_24COL',
                    width: 400,
                    widthMode: 'PX',
                  },
                  width: 400,
                  id: 'formitem',
                },
              ],
              caption: '图片预览_表单',
              codeName: 'group1',
              detailStyle: 'DEFAULT',
              detailType: 'GROUPPANEL',
              layoutPos: {
                colMD: 24,
                layout: 'TABLE_24COL',
              },
              showCaption: true,
              id: 'group1',
            },
            {
              dataType: 25,
              enableCond: 3,
              labelPos: 'LEFT',
              labelWidth: 130,
              noPrivDisplayMode: 1,
              appDEFieldId: 'id',
              editor: {
                editorType: 'HIDDEN',
                valueType: 'SIMPLE',
                editable: true,
                id: 'id',
              },
              allowEmpty: true,
              hidden: true,
              capLanguageRes: {
                lanResTag: 'DEF.LNAME.MASTER.ID',
              },
              caption: '标识',
              codeName: 'id',
              detailStyle: 'DEFAULT',
              detailType: 'FORMITEM',
              layoutPos: {
                colMD: 24,
                layout: 'TABLE_24COL',
              },
              id: 'id',
            },
          ],
          caption: '编辑器_图片预览',
          codeName: 'formpage1',
          detailStyle: 'DEFAULT',
          detailType: 'FORMPAGE',
          id: 'formpage1',
        },
      ],
      layout: {
        columnCount: 24,
        layout: 'TABLE_24COL',
      },
      tabHeaderPos: 'TOP',
      noTabHeader: true,
      autoLoad: true,
      showBusyIndicator: true,
      codeName: 'main54',
      controlType: 'FORM',
      logicName: '图片预览_表单',
      appDataEntityId: 'web.master',
      controlParam: {
        id: 'form',
      },
      modelId: 'dc06a4c695b8c1690d6029a3991cfb4a',
      modelType: 'PSDEFORM_EDITFORM',
      name: 'form',
      id: 'web.master.main54',
    },
    {
      codeName: 'upload_image_preview_datainfobar',
      controlType: 'DATAINFOBAR',
      appDataEntityId: 'web.master',
      controlParam: {
        id: 'datainfobar',
      },
      name: 'datainfobar',
      id: 'upload_image_preview_datainfobar',
    },
    {
      capLanguageRes: {
        lanResTag: 'DE.LNAME.MASTER',
      },
      caption: '编辑器_图片预览',
      codeName: 'upload_image_preview_captionbar',
      controlType: 'CAPTIONBAR',
      appDataEntityId: 'web.master',
      controlParam: {},
      name: 'captionbar',
      id: 'upload_image_preview_captionbar',
    },
  ],
  viewLayoutPanel: {
    layoutBodyOnly: true,
    useDefaultLayout: true,
    layoutPanel: true,
    codeName: 'layoutpanel',
    controlStyle: 'APPDEEDITVIEW',
    controlType: 'VIEWLAYOUTPANEL',
    appDataEntityId: 'web.master',
    controlParam: {},
    id: 'layoutpanel',
  },
  title: '编辑器_图片预览',
  viewStyle: 'DEFAULT',
  viewType: 'DEEDITVIEW',
  enableDP: true,
  showCaptionBar: false,
  modelId: '24d2687ac446bbf92b5c164a791570fe',
  modelType: 'PSAPPDEVIEW',
  name: 'MASTERupload_image_preview',
  id: 'web.master_upload_image_preview',
};
