export default {
  enableDirtyChecking: true,
  showDataInfoBar: true,
  xdataControlName: 'form',
  loadDefault: true,
  deviewCodeName: 'upload_image_cropping',
  deviewId: '0ba3cf11885b67fb2e6ceee00db56136',
  accUserMode: 3,
  capLanguageRes: {
    lanResTag: 'DE.LNAME.MASTER',
  },
  caption: '编辑器_图片裁剪上传',
  codeName: 'master_upload_image_cropping',
  appDataEntityId: 'web.master',
  appViewEngines: [
    {
      engineCat: 'VIEW',
      engineType: 'EditView',
      id: 'engine',
    },
  ],
  appViewMsgGroupId: 'upload_image_cropping',
  controls: [
    {
      xdataControlName: 'form',
      codeName: 'upload_image_cropping_toolbar',
      controlType: 'TOOLBAR',
      logicName: '编辑器_图片裁剪上传_工具栏',
      appDataEntityId: 'web.master',
      controlParam: {
        id: 'toolbar',
      },
      modelId: '09a8c781f3230fa6d96160627a99c21b',
      modelType: 'PSDETOOLBAR',
      name: 'toolbar',
      id: 'upload_image_cropping_toolbar',
    },
    {
      createControlAction: {
        appDEMethodId: 'create',
        appDataEntityId: 'web.master',
        id: 'create',
      },
      getDraftFromControlAction: {
        appDataEntityId: 'web.master',
        id: 'loaddraftfrom',
      },
      getDraftControlAction: {
        appDEMethodId: 'get_draft',
        appDataEntityId: 'web.master',
        id: 'loaddraft',
      },
      getControlAction: {
        appDEMethodId: 'get',
        appDataEntityId: 'web.master',
        id: 'load',
      },
      removeControlAction: {
        appDEMethodId: 'remove',
        appDataEntityId: 'web.master',
        id: 'remove',
      },
      updateControlAction: {
        appDEMethodId: 'update',
        appDataEntityId: 'web.master',
        id: 'update',
      },
      deformPages: [
        {
          layout: {
            columnCount: 24,
            layout: 'TABLE_24COL',
          },
          deformDetails: [
            {
              layout: {
                columnCount: 24,
                layout: 'TABLE_24COL',
              },
              deformDetails: [
                {
                  dataType: 25,
                  enableCond: 3,
                  labelPos: 'NONE',
                  noPrivDisplayMode: 1,
                  editor: {
                    editorStyle: 'CROPPING',
                    editorType: 'PICTURE',
                    valueType: 'SIMPLE',
                    editable: true,
                    id: 'formitem',
                  },
                  allowEmpty: true,
                  caption: '图片裁剪上传',
                  codeName: 'formitem',
                  detailStyle: 'DEFAULT',
                  detailType: 'FORMITEM',
                  layoutPos: {
                    colMD: 24,
                    layout: 'TABLE_24COL',
                  },
                  id: 'formitem',
                },
              ],
              caption: '图片裁剪上传',
              codeName: 'group1',
              detailStyle: 'DEFAULT',
              detailType: 'GROUPPANEL',
              layoutPos: {
                colMD: 24,
                layout: 'TABLE_24COL',
              },
              showCaption: true,
              id: 'group1',
            },
            {
              dataType: 25,
              enableCond: 3,
              labelPos: 'LEFT',
              labelWidth: 130,
              noPrivDisplayMode: 1,
              appDEFieldId: 'id',
              editor: {
                editorType: 'HIDDEN',
                valueType: 'SIMPLE',
                editable: true,
                id: 'id',
              },
              allowEmpty: true,
              hidden: true,
              capLanguageRes: {
                lanResTag: 'DEF.LNAME.MASTER.ID',
              },
              caption: '标识',
              codeName: 'id',
              detailStyle: 'DEFAULT',
              detailType: 'FORMITEM',
              layoutPos: {
                colMD: 24,
                layout: 'TABLE_24COL',
              },
              id: 'id',
            },
          ],
          caption: '图片裁剪上传',
          codeName: 'formpage1',
          detailStyle: 'DEFAULT',
          detailType: 'FORMPAGE',
          id: 'formpage1',
        },
      ],
      layout: {
        columnCount: 24,
        layout: 'TABLE_24COL',
      },
      tabHeaderPos: 'TOP',
      noTabHeader: true,
      autoLoad: true,
      showBusyIndicator: true,
      codeName: 'main53',
      controlType: 'FORM',
      logicName: '编辑器_图片裁剪上传_表单',
      appDataEntityId: 'web.master',
      controlParam: {
        id: 'form',
      },
      modelId: '8cc1b2e1a64734bc26dc8d6a7a1a4f89',
      modelType: 'PSDEFORM_EDITFORM',
      name: 'form',
      id: 'web.master.main53',
    },
    {
      codeName: 'upload_image_cropping_datainfobar',
      controlType: 'DATAINFOBAR',
      appDataEntityId: 'web.master',
      controlParam: {
        id: 'datainfobar',
      },
      name: 'datainfobar',
      id: 'upload_image_cropping_datainfobar',
    },
    {
      capLanguageRes: {
        lanResTag: 'DE.LNAME.MASTER',
      },
      caption: '编辑器_图片裁剪上传',
      codeName: 'upload_image_cropping_captionbar',
      controlType: 'CAPTIONBAR',
      appDataEntityId: 'web.master',
      controlParam: {},
      name: 'captionbar',
      id: 'upload_image_cropping_captionbar',
    },
  ],
  viewLayoutPanel: {
    layoutBodyOnly: true,
    useDefaultLayout: true,
    layoutPanel: true,
    codeName: 'layoutpanel',
    controlStyle: 'APPDEEDITVIEW',
    controlType: 'VIEWLAYOUTPANEL',
    appDataEntityId: 'web.master',
    controlParam: {},
    id: 'layoutpanel',
  },
  title: '编辑器_图片裁剪上传',
  viewStyle: 'DEFAULT',
  viewType: 'DEEDITVIEW',
  enableDP: true,
  showCaptionBar: false,
  modelId: '7f9c9d002760cf45c605f5a2c04d523f',
  modelType: 'PSAPPDEVIEW',
  name: 'MASTERupload_image_cropping',
  id: 'web.master_upload_image_cropping',
};
