export default {
  tabLayout: 'FLOW',
  loadDefault: true,
  showDataInfoBar: true,
  deviewCodeName: 'search_form',
  deviewId: 'a27eceff290518f2edc1638686cbcf5e',
  accUserMode: 3,
  capLanguageRes: {
    lanResTag: 'DE.LNAME.MASTER',
  },
  caption: '搜索表单',
  codeName: 'master_search_form',
  appDataEntityId: 'web.master',
  appViewEngines: [
    {
      engineCat: 'VIEW',
      engineType: 'TabExpView',
      id: 'engine',
    },
  ],
  appViewMsgGroupId: 'search_form',
  controls: [
    {
      dedrtabPages: [
        {
          caption: '布局',
          appViewId: 'web.master_searchform_layout',
          id: 'layout',
        },
        {
          caption: '按钮样式',
          appViewId: 'web.master_searchform_btncss',
          id: 'btncss',
        },
        {
          caption: '过滤',
          appViewId: 'web.master_searchform_filter',
          id: 'filter',
        },
        {
          caption: '自动搜索',
          appViewId: 'web.master_searchform_auto',
          id: 'auto_search',
        },
        {
          caption: '高级搜索',
          appViewId: 'web.master_searchform_advanced',
          id: 'advanced_search',
        },
      ],
      dataRelationTag: 'search_form_DR',
      editItemCapLanguageRes: {
        lanResTag: 'DE.LNAME.MASTER',
      },
      editItemCaption: '主数据',
      uniqueTag: 'master_search_form__tabexppanel',
      autoLoad: true,
      showBusyIndicator: true,
      codeName: 'search_form_dr',
      controlType: 'DRTAB',
      appDataEntityId: 'web.master',
      controlParam: {
        id: 'tabexppanel',
      },
      modelId: '3f4452cf8baff5b7e6989f1df991c7b4',
      modelType: 'PSDEDRTAB',
      name: 'tabexppanel',
      id: 'search_form_dr',
    },
    {
      capLanguageRes: {
        lanResTag: 'DE.LNAME.MASTER',
      },
      caption: '搜索表单',
      codeName: 'search_form_captionbar',
      controlType: 'CAPTIONBAR',
      appDataEntityId: 'web.master',
      controlParam: {},
      name: 'captionbar',
      id: 'search_form_captionbar',
    },
  ],
  viewLayoutPanel: {
    layoutBodyOnly: true,
    useDefaultLayout: true,
    layoutPanel: true,
    codeName: 'layoutpanel',
    controlStyle: 'APPDETABEXPVIEW',
    controlType: 'VIEWLAYOUTPANEL',
    appDataEntityId: 'web.master',
    controlParam: {},
    id: 'layoutpanel',
  },
  title: '搜索表单',
  viewStyle: 'DEFAULT',
  viewType: 'DETABEXPVIEW',
  enableDP: true,
  showCaptionBar: false,
  modelId: 'b5c48e4029b3def45d5da4749879fb94',
  modelType: 'PSAPPDEVIEW',
  name: 'MASTERsearch_form',
  id: 'web.master_search_form',
};
