export default {
  deviewCodeName: 'counter_dr',
  deviewId: '89c902893bf15d245af8898d52e9079b',
  accUserMode: 3,
  capLanguageRes: {
    lanResTag: 'DE.LNAME.MASTER',
  },
  caption: '计数器_关系界面组',
  codeName: 'master_counter_dr',
  appDataEntityId: 'web.master',
  appViewMsgGroupId: 'counter_dr',
  viewLayoutPanel: {
    layoutBodyOnly: true,
    viewProxyMode: true,
    layoutMode: 'FLEX',
    layout: {
      layout: 'FLEX',
    },
    rootPanelItems: [
      {
        actionGroupExtractMode: 'ITEM',
        panelItems: [
          {
            caption: '关系分页部件',
            itemStyle: 'DEFAULT',
            itemType: 'CTRLPOS',
            layoutPos: {
              shrink: 1,
              layout: 'FLEX',
            },
            showCaption: true,
            id: 'drtab',
          },
        ],
        predefinedType: 'CONTAINER_GROUP',
        layout: {
          layout: 'FLEX',
        },
        dataRegionType: 'INHERIT',
        caption: '关系分页部件',
        itemStyle: 'DEFAULT',
        itemType: 'CONTAINER',
        layoutPos: {
          shrink: 1,
          layout: 'FLEX',
        },
        showCaption: true,
        id: 'container_group',
      },
      {
        actionGroupExtractMode: 'ITEM',
        panelItems: [
          {
            caption: '关系数据栏',
            itemStyle: 'DEFAULT',
            itemType: 'CTRLPOS',
            layoutPos: {
              shrink: 1,
              layout: 'FLEX',
            },
            showCaption: true,
            id: 'drbar',
          },
        ],
        predefinedType: 'CONTAINER_GROUP',
        layout: {
          layout: 'FLEX',
        },
        dataRegionType: 'INHERIT',
        caption: '关系数据栏',
        itemStyle: 'DEFAULT',
        itemType: 'CONTAINER',
        layoutPos: {
          shrink: 1,
          layout: 'FLEX',
        },
        showCaption: true,
        id: 'container_group1',
      },
    ],
    layoutPanel: true,
    controls: [
      {
        dedrtabPages: [
          {
            caption: '表单',
            counterId: 'dr_form',
            appViewId: 'web.master_counter_exp_form',
            id: 'dr_form',
          },
          {
            caption: '表格',
            counterId: 'dr_grid',
            appViewId: 'web.master_counter_exp_grid',
            id: 'dr_grid',
          },
        ],
        dataRelationTag: 'counter_dr_DR',
        editItemCapLanguageRes: {
          lanResTag: 'DE.LNAME.MASTER',
        },
        editItemCaption: '主数据',
        appCounterRefId: 'd0a6e348d1ed8a3141d3466137925bc7',
        uniqueTag: 'master_counter_dr__drtab',
        autoLoad: true,
        showBusyIndicator: true,
        appCounterRefs: [
          {
            appCounter: {
              codeName: 'Counter',
              counterType: 'DEDR',
              getAppDEActionId: 'get_counter_data',
              appDataEntityId: 'web.master',
              timer: 60000,
              uniqueTag: 'Counter',
              name: '计数器',
              id: 'web.counter',
            },
            refMode: {
              srfdeid: 'MASTER',
            },
            tag: 'd0a6e348d1ed8a3141d3466137925bc7',
            uniqueTag: 'Counter',
            id: 'd0a6e348d1ed8a3141d3466137925bc7',
          },
        ],
        codeName: 'counter_dr_dr',
        controlType: 'DRTAB',
        appDataEntityId: 'web.master',
        controlParam: {
          id: 'drtab',
        },
        modelId: 'ef272b4ef522be293075b97f48fd415f',
        modelType: 'PSDEDRTAB',
        name: 'drtab',
        id: 'counter_dr_dr',
      },
      {
        dedrbarGroups: [
          {
            caption: '默认',
            name: '默认',
            id: 'a0aa99ad32515d58406',
          },
        ],
        showTitle: true,
        dataRelationTag: 'counter_dr_DR',
        editItemCapLanguageRes: {
          lanResTag: 'DE.LNAME.MASTER',
        },
        editItemCaption: '主数据',
        appCounterRefId: 'd0a6e348d1ed8a3141d3466137925bc7',
        dedrctrlItems: [
          {
            dedrbarGroupId: 'a0aa99ad32515d58406',
            caption: '表单',
            counterId: 'dr_form',
            appViewId: 'web.master_counter_exp_form',
            id: 'dr_form',
          },
          {
            dedrbarGroupId: 'a0aa99ad32515d58406',
            caption: '表格',
            counterId: 'dr_grid',
            appViewId: 'web.master_counter_exp_grid',
            id: 'dr_grid',
          },
        ],
        uniqueTag: 'master_counter_dr__drbar',
        autoLoad: true,
        showBusyIndicator: true,
        appCounterRefs: [
          {
            appCounter: {
              codeName: 'Counter',
              counterType: 'DEDR',
              getAppDEActionId: 'get_counter_data',
              appDataEntityId: 'web.master',
              timer: 60000,
              uniqueTag: 'Counter',
              name: '计数器',
              id: 'web.counter',
            },
            refMode: {
              srfdeid: 'MASTER',
            },
            tag: 'd0a6e348d1ed8a3141d3466137925bc7',
            uniqueTag: 'Counter',
            id: 'd0a6e348d1ed8a3141d3466137925bc7',
          },
        ],
        codeName: 'counter_dr_dr',
        controlType: 'DRBAR',
        appDataEntityId: 'web.master',
        controlParam: {
          id: 'drbar',
        },
        modelId: 'ef272b4ef522be293075b97f48fd415f',
        modelType: 'PSDEDRBAR',
        name: 'drbar',
        id: 'counter_dr_dr',
      },
      {
        capLanguageRes: {
          lanResTag: 'DE.LNAME.MASTER',
        },
        caption: '计数器_关系界面组',
        codeName: 'counter_dr_captionbar',
        controlType: 'CAPTIONBAR',
        appDataEntityId: 'web.master',
        controlParam: {},
        name: 'captionbar',
        id: 'counter_dr_captionbar',
      },
    ],
    codeName: 'af9a4735a234168a52a',
    controlType: 'VIEWLAYOUTPANEL',
    logicName: 'counter_dr',
    appDataEntityId: 'web.master',
    controlParam: {},
    modelId: '9a684a7f59762f3d49ba14a9670fe086',
    modelType: 'PSSYSVIEWLAYOUTPANEL',
    name: 'layoutpanel',
    id: 'af9a4735a234168a52a',
  },
  title: '计数器_关系界面组',
  viewStyle: 'DEFAULT',
  viewType: 'DECUSTOMVIEW',
  enableDP: true,
  showCaptionBar: false,
  modelId: '077af58c59e2b2bdcc5b33389a2b738d',
  modelType: 'PSAPPDEVIEW',
  name: 'MASTERcounter_dr',
  id: 'web.master_counter_dr',
};
