export default {
  tabLayout: 'FLOW',
  loadDefault: true,
  showDataInfoBar: true,
  deviewCodeName: 'panel',
  deviewId: 'a3d63e14ace78a76399dd3ff4a1bfad1',
  accUserMode: 3,
  capLanguageRes: {
    lanResTag: 'DE.LNAME.MASTER',
  },
  caption: '面板',
  codeName: 'master_panel',
  appDataEntityId: 'web.master',
  appViewEngines: [
    {
      engineCat: 'VIEW',
      engineType: 'TabExpView',
      id: 'engine',
    },
  ],
  appViewMsgGroupId: 'panel',
  controls: [
    {
      dedrtabPages: [
        {
          caption: '常规',
          appViewId: 'web.master_panel_base',
          id: 'base',
        },
        {
          caption: '逻辑',
          appViewId: 'web.master_panel_logic',
          id: 'logic',
        },
        {
          caption: '值显示',
          appViewId: 'web.master_panel_format',
          id: 'format',
        },
        {
          caption: '界面样式及图标',
          appViewId: 'web.master_panel_cssandicon',
          id: 'cssandicon',
        },
        {
          caption: '事件及调用',
          appViewId: 'web.master_panel_event',
          id: 'event',
        },
      ],
      dataRelationTag: 'panel_DR',
      editItemCapLanguageRes: {
        lanResTag: 'DE.LNAME.MASTER',
      },
      editItemCaption: '主数据',
      uniqueTag: 'master_panel__tabexppanel',
      autoLoad: true,
      showBusyIndicator: true,
      codeName: 'panel_dr',
      controlType: 'DRTAB',
      appDataEntityId: 'web.master',
      controlParam: {
        id: 'tabexppanel',
      },
      modelId: 'dc85f546f397f43ec68f9bda4d40d666',
      modelType: 'PSDEDRTAB',
      name: 'tabexppanel',
      id: 'panel_dr',
    },
    {
      capLanguageRes: {
        lanResTag: 'DE.LNAME.MASTER',
      },
      caption: '面板',
      codeName: 'panel_captionbar',
      controlType: 'CAPTIONBAR',
      appDataEntityId: 'web.master',
      controlParam: {},
      name: 'captionbar',
      id: 'panel_captionbar',
    },
  ],
  viewLayoutPanel: {
    layoutBodyOnly: true,
    useDefaultLayout: true,
    layoutPanel: true,
    codeName: 'layoutpanel',
    controlStyle: 'APPDETABEXPVIEW',
    controlType: 'VIEWLAYOUTPANEL',
    appDataEntityId: 'web.master',
    controlParam: {},
    id: 'layoutpanel',
  },
  title: '面板',
  viewStyle: 'DEFAULT',
  viewType: 'DETABEXPVIEW',
  enableDP: true,
  showCaptionBar: false,
  modelId: '1da17601759eb9e07603613e9323d209',
  modelType: 'PSAPPDEVIEW',
  name: 'MASTERpanel',
  id: 'web.master_panel',
};
