export default {
  deviewCodeName: 'panel_format',
  deviewId: '331cb97ebb3372f3eebd7e549abb4392',
  accUserMode: 3,
  capLanguageRes: {
    lanResTag: 'DE.LNAME.MASTER',
  },
  caption: '面板_值格式化',
  codeName: 'master_panel_format',
  appDataEntityId: 'web.master',
  appViewMsgGroupId: 'panel_format',
  viewLayoutPanel: {
    viewProxyMode: true,
    layoutMode: 'FLEX',
    layout: {
      layout: 'FLEX',
    },
    rootPanelItems: [
      {
        actionGroupExtractMode: 'ITEM',
        panelItems: [
          {
            actionGroupExtractMode: 'ITEM',
            panelItems: [
              {
                actionGroupExtractMode: 'ITEM',
                panelItems: [
                  {
                    editor: {
                      halign: 'LEFT',
                      renderMode: 'TEXT_DYNAMIC',
                      valign: 'MIDDLE',
                      wrapMode: 'NOWRAP',
                      editorType: 'SPAN',
                      predefinedType: 'FIELD_TEXT_DYNAMIC',
                      valueType: 'SIMPLE',
                      editable: true,
                      id: 'name',
                    },
                    valueFormat: '名称：@',
                    viewFieldName: 'name',
                    allowEmpty: true,
                    caption: '文本(动态)',
                    itemStyle: 'DEFAULT',
                    itemType: 'FIELD',
                    layoutPos: {
                      shrink: 1,
                      layout: 'FLEX',
                      spacingBottom: 'OUTERLARGE',
                    },
                    id: 'name',
                  },
                  {
                    editor: {
                      halign: 'LEFT',
                      renderMode: 'TEXT_DYNAMIC',
                      valign: 'MIDDLE',
                      wrapMode: 'NOWRAP',
                      editorType: 'SPAN',
                      predefinedType: 'FIELD_TEXT_DYNAMIC',
                      valueType: 'SIMPLE',
                      editable: true,
                      id: 'quantity',
                    },
                    valueFormat: '数量（显示千分位）: #,###',
                    viewFieldName: 'quantity',
                    allowEmpty: true,
                    caption: '文本(动态)',
                    itemStyle: 'DEFAULT',
                    itemType: 'FIELD',
                    layoutPos: {
                      shrink: 1,
                      layout: 'FLEX',
                    },
                    id: 'quantity',
                  },
                ],
                layout: {
                  layout: 'FLEX',
                },
                dataRegionType: 'INHERIT',
                caption: '容器',
                itemStyle: 'DEFAULT',
                itemType: 'CONTAINER',
                layoutPos: {
                  shrink: 1,
                  layout: 'FLEX',
                },
                id: 'container',
              },
            ],
            predefinedType: 'CONTAINER_SINGLEDATA',
            layout: {
              layout: 'FLEX',
            },
            dataRegionType: 'SINGLEDATA',
            dataSourceType: 'DEACTION',
            appDEMethodId: 'get_sample_date',
            appDataEntityId: 'web.master',
            caption: '单项数据容器',
            itemStyle: 'DEFAULT',
            itemType: 'CONTAINER',
            layoutPos: {
              shrink: 1,
              layout: 'FLEX',
            },
            id: 'container_singledata',
          },
        ],
        layout: {
          dir: 'column',
          layout: 'FLEX',
        },
        dataRegionType: 'INHERIT',
        itemStyle: 'DEFAULT',
        itemType: 'CONTAINER',
        layoutPos: {
          shrink: 1,
          layout: 'FLEX',
          spacingBottom: 'OUTERLARGE',
          spacingLeft: 'OUTERLARGE',
          spacingRight: 'OUTERLARGE',
          spacingTop: 'OUTERLARGE',
        },
        id: 'page_container',
      },
    ],
    layoutPanel: true,
    controls: [
      {
        capLanguageRes: {
          lanResTag: 'DE.LNAME.MASTER',
        },
        caption: '面板_值格式化',
        codeName: 'panel_format_captionbar',
        controlType: 'CAPTIONBAR',
        appDataEntityId: 'web.master',
        controlParam: {},
        name: 'captionbar',
        id: 'panel_format_captionbar',
      },
    ],
    codeName: 'usr0516324682',
    controlType: 'VIEWLAYOUTPANEL',
    logicName: '面板_值格式化布局面板',
    appDataEntityId: 'web.master',
    controlParam: {},
    modelId: '6470f4402fab6018a3a1a013ea1975cd',
    modelType: 'PSSYSVIEWLAYOUTPANEL',
    name: 'layoutpanel',
    id: 'usr0516324682',
  },
  title: '面板_值格式化',
  viewStyle: 'DEFAULT',
  viewType: 'DECUSTOMVIEW',
  enableDP: true,
  showCaptionBar: false,
  modelId: 'd3d5ca9ef2ca557ef8775c39a60cea0f',
  modelType: 'PSAPPDEVIEW',
  name: 'MASTERpanel_format',
  id: 'web.master_panel_format',
};
