export default {
  tabLayout: 'FLOW',
  loadDefault: true,
  showDataInfoBar: true,
  deviewCodeName: 'wizard',
  deviewId: '1c939bfde0efb7bfd9829b49f616d658',
  accUserMode: 3,
  capLanguageRes: {
    lanResTag: 'DE.LNAME.MASTER',
  },
  caption: '向导',
  codeName: 'master_wizard',
  appDataEntityId: 'web.master',
  appViewEngines: [
    {
      engineCat: 'VIEW',
      engineType: 'TabExpView',
      id: 'engine',
    },
  ],
  appViewMsgGroupId: 'wizard',
  controls: [
    {
      dedrtabPages: [
        {
          caption: '常规',
          appViewId: 'web.master_wizard_base',
          id: 'base',
        },
        {
          caption: '逻辑',
          appViewId: 'web.master_wizard_view_logic',
          id: 'logic',
        },
        {
          caption: '界面样式及图标',
          appViewId: 'web.master_wizard_view_style',
          id: 'css',
        },
      ],
      dataRelationTag: 'wizard_DR',
      editItemCapLanguageRes: {
        lanResTag: 'DE.LNAME.MASTER',
      },
      editItemCaption: '主数据',
      uniqueTag: 'master_wizard__tabexppanel',
      autoLoad: true,
      showBusyIndicator: true,
      codeName: 'wizard_dr',
      controlType: 'DRTAB',
      appDataEntityId: 'web.master',
      controlParam: {
        id: 'tabexppanel',
      },
      modelId: '62f44bef2c8fd76222763c7519255e5e',
      modelType: 'PSDEDRTAB',
      name: 'tabexppanel',
      id: 'wizard_dr',
    },
    {
      capLanguageRes: {
        lanResTag: 'DE.LNAME.MASTER',
      },
      caption: '向导',
      codeName: 'wizard_captionbar',
      controlType: 'CAPTIONBAR',
      appDataEntityId: 'web.master',
      controlParam: {},
      name: 'captionbar',
      id: 'wizard_captionbar',
    },
  ],
  viewLayoutPanel: {
    layoutBodyOnly: true,
    useDefaultLayout: true,
    layoutPanel: true,
    codeName: 'layoutpanel',
    controlStyle: 'APPDETABEXPVIEW',
    controlType: 'VIEWLAYOUTPANEL',
    appDataEntityId: 'web.master',
    controlParam: {},
    id: 'layoutpanel',
  },
  title: '向导',
  viewStyle: 'DEFAULT',
  viewType: 'DETABEXPVIEW',
  enableDP: true,
  showCaptionBar: false,
  modelId: '26f67a7cf891af2f73ea49eb1acf659c',
  modelType: 'PSAPPDEVIEW',
  name: 'MASTERwizard',
  id: 'web.master_wizard',
};
