export default {
  deviewCodeName: 'WizardView_logic',
  deviewId: '500aaaf885ba4cd350ea50835b39f396',
  accUserMode: 3,
  capLanguageRes: {
    lanResTag: 'DE.LNAME.MASTER',
  },
  caption: '逻辑',
  codeName: 'master_wizard_view_logic',
  appDataEntityId: 'web.master',
  appViewMsgGroupId: 'wizardview_logic',
  viewLayoutPanel: {
    viewProxyMode: true,
    layoutMode: 'FLEX',
    layout: {
      layout: 'FLEX',
    },
    rootPanelItems: [
      {
        actionGroupExtractMode: 'ITEM',
        panelItems: [
          {
            actionGroupExtractMode: 'ITEM',
            panelItems: [
              {
                caption: '向导面板',
                contentHeight: 100,
                height: 100,
                itemStyle: 'DEFAULT',
                itemType: 'CTRLPOS',
                layoutPos: {
                  shrink: 1,
                  height: 100,
                  heightMode: 'PERCENTAGE',
                  layout: 'FLEX',
                },
                showCaption: true,
                id: 'wizardpanel',
              },
            ],
            predefinedType: 'CONTAINER_GROUP',
            layout: {
              layout: 'FLEX',
            },
            dataRegionType: 'INHERIT',
            caption: '下一步提示信息、步骤启用逻辑',
            itemStyle: 'DEFAULT',
            itemType: 'CONTAINER',
            layoutPos: {
              shrink: 1,
              layout: 'FLEX',
            },
            showCaption: true,
            id: 'container_group',
          },
        ],
        predefinedType: 'VIEWCONTENT',
        layout: {
          layout: 'FLEX',
        },
        dataRegionType: 'INHERIT',
        caption: '容器',
        itemStyle: 'DEFAULT',
        itemType: 'CONTAINER',
        layoutPos: {
          grow: 1,
          shrink: 1,
          layout: 'FLEX',
        },
        id: 'view_content',
      },
    ],
    layoutPanel: true,
    appViewEngines: [
      {
        engineCat: 'VIEW',
        engineType: 'WizardView',
        id: 'engine',
      },
    ],
    controls: [
      {
        finishControlAction: {
          appDEMethodId: 'get',
          appDataEntityId: 'web.master',
          id: 'finish',
        },
        deeditForms: [
          {
            getControlAction: {
              appDEMethodId: 'get',
              appDataEntityId: 'web.master',
              id: 'load',
            },
            updateControlAction: {
              appDEMethodId: 'get',
              appDataEntityId: 'web.master',
              id: 'update',
            },
            dewizardForm: {
              confirmMsg: '确认进入下一步？',
              confirmMsg2: '确认进入下一步？',
              formTag: 'step1',
              deformName: '向导步骤1',
              dewizardStepId: 'step1',
              stepActions: ['NEXT'],
              stepTag: 'step1',
              firstForm: true,
              id: 'step1',
            },
            formFuncMode: 'WIZARDFORM',
            deformPages: [
              {
                layout: {
                  columnCount: 24,
                  layout: 'TABLE_24COL',
                },
                deformDetails: [
                  {
                    layout: {
                      columnCount: 24,
                      layout: 'TABLE_24COL',
                    },
                    deformDetails: [
                      {
                        dataType: 25,
                        enableCond: 3,
                        labelPos: 'LEFT',
                        labelWidth: 130,
                        noPrivDisplayMode: 1,
                        appDEFieldId: 'name',
                        editor: {
                          maxLength: 200,
                          editorType: 'TEXTBOX',
                          valueType: 'SIMPLE',
                          editable: true,
                          id: 'name',
                        },
                        capLanguageRes: {
                          lanResTag: 'DEF.LNAME.MASTER.NAME',
                        },
                        caption: '名称',
                        codeName: 'name',
                        detailStyle: 'DEFAULT',
                        detailType: 'FORMITEM',
                        layoutPos: {
                          colMD: 24,
                          layout: 'TABLE_24COL',
                        },
                        showCaption: true,
                        id: 'name',
                      },
                    ],
                    caption: '主数据基本信息',
                    codeName: 'group1',
                    detailStyle: 'DEFAULT',
                    detailType: 'GROUPPANEL',
                    layoutPos: {
                      colMD: 24,
                      layout: 'TABLE_24COL',
                    },
                    showCaption: true,
                    id: 'group1',
                  },
                  {
                    dataType: 25,
                    enableCond: 3,
                    labelPos: 'LEFT',
                    labelWidth: 130,
                    noPrivDisplayMode: 1,
                    appDEFieldId: 'id',
                    editor: {
                      editorType: 'HIDDEN',
                      valueType: 'SIMPLE',
                      editable: true,
                      id: 'id',
                    },
                    allowEmpty: true,
                    hidden: true,
                    capLanguageRes: {
                      lanResTag: 'DEF.LNAME.MASTER.ID',
                    },
                    caption: '标识',
                    codeName: 'id',
                    detailStyle: 'DEFAULT',
                    detailType: 'FORMITEM',
                    layoutPos: {
                      colMD: 24,
                      layout: 'TABLE_24COL',
                    },
                    id: 'id',
                  },
                ],
                caption: '基本信息',
                codeName: 'formpage1',
                detailStyle: 'DEFAULT',
                detailType: 'FORMPAGE',
                id: 'formpage1',
              },
            ],
            layout: {
              columnCount: 24,
              layout: 'TABLE_24COL',
            },
            tabHeaderPos: 'TOP',
            noTabHeader: true,
            autoLoad: true,
            showBusyIndicator: true,
            codeName: 'step1',
            controlType: 'FORM',
            logicName: '向导步骤1',
            appDataEntityId: 'web.master',
            controlLogics: [
              {
                eventNames: 'SAVE',
                logicTag: 'wizardpanel_form_step1',
                logicType: 'CUSTOM',
                triggerType: 'CTRLEVENT',
                id: 'wizardpanel_formsave',
              },
              {
                eventNames: 'LOAD',
                logicTag: 'wizardpanel_form_step1',
                logicType: 'CUSTOM',
                triggerType: 'CTRLEVENT',
                id: 'wizardpanel_formload',
              },
            ],
            controlParam: {
              id: 'wizardpanel_form_step1',
            },
            modelId: '184ab3aa393db620ed0a377292471483',
            modelType: 'PSDEFORM_EDITFORM',
            name: 'wizardpanel_form_step1',
            id: 'web.master.step1',
          },
          {
            getControlAction: {
              appDEMethodId: 'get',
              appDataEntityId: 'web.master',
              id: 'load',
            },
            updateControlAction: {
              appDEMethodId: 'get',
              appDataEntityId: 'web.master',
              id: 'update',
            },
            dewizardForm: {
              confirmMsg: '确认进入下一步？',
              confirmMsg2: '确认进入下一步？',
              formTag: 'step2',
              goNextEnableScriptCode: "data.name == '1'",
              deformName: '向导步骤2（启用条件）',
              dewizardStepId: 'step2',
              stepActions: ['PREV', 'NEXT'],
              stepTag: 'step2',
              id: 'step2',
            },
            formFuncMode: 'WIZARDFORM',
            deformPages: [
              {
                layout: {
                  columnCount: 24,
                  layout: 'TABLE_24COL',
                },
                deformDetails: [
                  {
                    layout: {
                      columnCount: 24,
                      layout: 'TABLE_24COL',
                    },
                    deformDetails: [
                      {
                        dataType: 25,
                        enableCond: 3,
                        labelPos: 'LEFT',
                        labelWidth: 130,
                        noPrivDisplayMode: 1,
                        appDEFieldId: 'name',
                        editor: {
                          maxLength: 200,
                          editorType: 'TEXTBOX',
                          placeHolder: '值=1时可进入下一步',
                          valueType: 'SIMPLE',
                          editable: true,
                          id: 'name',
                        },
                        capLanguageRes: {
                          lanResTag: 'DEF.LNAME.MASTER.NAME',
                        },
                        caption: '名称',
                        codeName: 'name',
                        detailStyle: 'DEFAULT',
                        detailType: 'FORMITEM',
                        layoutPos: {
                          colMD: 24,
                          layout: 'TABLE_24COL',
                        },
                        showCaption: true,
                        id: 'name',
                      },
                    ],
                    caption: '主数据基本信息',
                    codeName: 'group1',
                    detailStyle: 'DEFAULT',
                    detailType: 'GROUPPANEL',
                    layoutPos: {
                      colMD: 24,
                      layout: 'TABLE_24COL',
                    },
                    showCaption: true,
                    id: 'group1',
                  },
                  {
                    dataType: 25,
                    enableCond: 3,
                    labelPos: 'LEFT',
                    labelWidth: 130,
                    noPrivDisplayMode: 1,
                    appDEFieldId: 'id',
                    editor: {
                      editorType: 'HIDDEN',
                      valueType: 'SIMPLE',
                      editable: true,
                      id: 'id',
                    },
                    allowEmpty: true,
                    hidden: true,
                    capLanguageRes: {
                      lanResTag: 'DEF.LNAME.MASTER.ID',
                    },
                    caption: '标识',
                    codeName: 'id',
                    detailStyle: 'DEFAULT',
                    detailType: 'FORMITEM',
                    layoutPos: {
                      colMD: 24,
                      layout: 'TABLE_24COL',
                    },
                    id: 'id',
                  },
                ],
                caption: '基本信息',
                codeName: 'formpage1',
                detailStyle: 'DEFAULT',
                detailType: 'FORMPAGE',
                id: 'formpage1',
              },
            ],
            layout: {
              columnCount: 24,
              layout: 'TABLE_24COL',
            },
            tabHeaderPos: 'TOP',
            noTabHeader: true,
            autoLoad: true,
            showBusyIndicator: true,
            codeName: 'step2_with_condition',
            controlType: 'FORM',
            logicName: '向导步骤2（启用条件）',
            appDataEntityId: 'web.master',
            controlLogics: [
              {
                eventNames: 'SAVE',
                logicTag: 'wizardpanel_form_step2',
                logicType: 'CUSTOM',
                triggerType: 'CTRLEVENT',
                id: 'wizardpanel_formsave',
              },
              {
                eventNames: 'LOAD',
                logicTag: 'wizardpanel_form_step2',
                logicType: 'CUSTOM',
                triggerType: 'CTRLEVENT',
                id: 'wizardpanel_formload',
              },
            ],
            controlParam: {
              id: 'wizardpanel_form_step2',
            },
            modelId: '62f0e05b727a22fd11273f78bd8980b1',
            modelType: 'PSDEFORM_EDITFORM',
            name: 'wizardpanel_form_step2',
            id: 'web.master.step2_with_condition',
          },
          {
            getControlAction: {
              appDEMethodId: 'get',
              appDataEntityId: 'web.master',
              id: 'load',
            },
            updateControlAction: {
              appDEMethodId: 'get',
              appDataEntityId: 'web.master',
              id: 'update',
            },
            dewizardForm: {
              confirmMsg: '确认完成？',
              confirmMsg2: '确认完成？',
              formTag: 'step3',
              goFinishEnableScriptCode:
                "view.getController('form') && (view.getController('form').state.data.name = \"1\")",
              deformName: '向导步骤3',
              dewizardStepId: 'step3',
              stepActions: ['PREV', 'FINISH'],
              stepTag: 'step3',
              id: 'step3',
            },
            formFuncMode: 'WIZARDFORM',
            deformPages: [
              {
                layout: {
                  columnCount: 24,
                  layout: 'TABLE_24COL',
                },
                deformDetails: [
                  {
                    layout: {
                      columnCount: 24,
                      layout: 'TABLE_24COL',
                    },
                    deformDetails: [
                      {
                        dataType: 25,
                        enableCond: 3,
                        labelPos: 'LEFT',
                        labelWidth: 130,
                        noPrivDisplayMode: 1,
                        appDEFieldId: 'name',
                        editor: {
                          maxLength: 200,
                          editorType: 'TEXTBOX',
                          valueType: 'SIMPLE',
                          editable: true,
                          id: 'name',
                        },
                        capLanguageRes: {
                          lanResTag: 'DEF.LNAME.MASTER.NAME',
                        },
                        caption: '名称',
                        codeName: 'name',
                        detailStyle: 'DEFAULT',
                        detailType: 'FORMITEM',
                        layoutPos: {
                          colMD: 24,
                          layout: 'TABLE_24COL',
                        },
                        showCaption: true,
                        id: 'name',
                      },
                    ],
                    caption: '主数据基本信息',
                    codeName: 'group1',
                    detailStyle: 'DEFAULT',
                    detailType: 'GROUPPANEL',
                    layoutPos: {
                      colMD: 24,
                      layout: 'TABLE_24COL',
                    },
                    showCaption: true,
                    id: 'group1',
                  },
                  {
                    dataType: 25,
                    enableCond: 3,
                    labelPos: 'LEFT',
                    labelWidth: 130,
                    noPrivDisplayMode: 1,
                    appDEFieldId: 'id',
                    editor: {
                      editorType: 'HIDDEN',
                      valueType: 'SIMPLE',
                      editable: true,
                      id: 'id',
                    },
                    allowEmpty: true,
                    hidden: true,
                    capLanguageRes: {
                      lanResTag: 'DEF.LNAME.MASTER.ID',
                    },
                    caption: '标识',
                    codeName: 'id',
                    detailStyle: 'DEFAULT',
                    detailType: 'FORMITEM',
                    layoutPos: {
                      colMD: 24,
                      layout: 'TABLE_24COL',
                    },
                    id: 'id',
                  },
                ],
                caption: '基本信息',
                codeName: 'formpage1',
                detailStyle: 'DEFAULT',
                detailType: 'FORMPAGE',
                id: 'formpage1',
              },
            ],
            layout: {
              columnCount: 24,
              layout: 'TABLE_24COL',
            },
            tabHeaderPos: 'TOP',
            noTabHeader: true,
            autoLoad: true,
            showBusyIndicator: true,
            codeName: 'step3',
            controlType: 'FORM',
            logicName: '向导步骤3',
            appDataEntityId: 'web.master',
            controlLogics: [
              {
                eventNames: 'SAVE',
                logicTag: 'wizardpanel_form_step3',
                logicType: 'CUSTOM',
                triggerType: 'CTRLEVENT',
                id: 'wizardpanel_formsave',
              },
              {
                eventNames: 'LOAD',
                logicTag: 'wizardpanel_form_step3',
                logicType: 'CUSTOM',
                triggerType: 'CTRLEVENT',
                id: 'wizardpanel_formload',
              },
            ],
            controlParam: {
              id: 'wizardpanel_form_step3',
            },
            modelId: '8b8bc6f3b6d56856518c42151fc8adc9',
            modelType: 'PSDEFORM_EDITFORM',
            name: 'wizardpanel_form_step3',
            id: 'web.master.step3',
          },
        ],
        dewizard: {
          codeName: 'wizard_confirm',
          firstDEWizardFormId: 'step1',
          dewizardForms: [
            {
              confirmMsg: '确认进入下一步？',
              confirmMsg2: '确认进入下一步？',
              formTag: 'step1',
              deformName: '向导步骤1',
              dewizardStepId: 'step1',
              stepActions: ['NEXT'],
              stepTag: 'step1',
              firstForm: true,
              id: 'step1',
            },
            {
              confirmMsg: '确认进入下一步？',
              confirmMsg2: '确认进入下一步？',
              formTag: 'step2',
              goNextEnableScriptCode: "data.name == '1'",
              deformName: '向导步骤2（启用条件）',
              dewizardStepId: 'step2',
              stepActions: ['PREV', 'NEXT'],
              stepTag: 'step2',
              id: 'step2',
            },
            {
              confirmMsg: '确认完成？',
              confirmMsg2: '确认完成？',
              formTag: 'step3',
              goFinishEnableScriptCode:
                "view.getController('form') && (view.getController('form').state.data.name = \"1\")",
              deformName: '向导步骤3',
              dewizardStepId: 'step3',
              stepActions: ['PREV', 'FINISH'],
              stepTag: 'step3',
              id: 'step3',
            },
          ],
          dewizardSteps: [
            {
              stepTag: 'step1',
              title: 'step1',
              id: 'step1',
            },
            {
              stepTag: 'step2',
              title: 'step2',
              id: 'step2',
            },
            {
              stepTag: 'step3',
              title: 'step3',
              id: 'step3',
            },
          ],
          wizardStyle: 'DEFAULT',
          name: '向导_下一步确认信息',
          id: 'mock.master.wizard_confirm',
        },
        wizardStyle: 'DEFAULT',
        showActionBar: true,
        showStepBar: true,
        autoLoad: true,
        showBusyIndicator: true,
        codeName: 'wizard_confirm',
        controlType: 'WIZARDPANEL',
        logicName: '向导_下一步确认信息',
        appDataEntityId: 'web.master',
        controlParam: {
          id: 'wizardpanel',
        },
        modelId: 'f2ceaf332bbfce49751fbb7fd55a540c',
        modelType: 'PSDEWIZARDPANEL',
        name: 'wizardpanel',
        id: 'web.master.wizard_confirm',
      },
      {
        capLanguageRes: {
          lanResTag: 'DE.LNAME.MASTER',
        },
        caption: '逻辑',
        codeName: 'wizard_view_logic_captionbar',
        controlType: 'CAPTIONBAR',
        appDataEntityId: 'web.master',
        controlParam: {},
        name: 'captionbar',
        id: 'wizard_view_logic_captionbar',
      },
    ],
    codeName: 'usr0516896362',
    controlType: 'VIEWLAYOUTPANEL',
    logicName: 'WizardView_logic向导视图布局面板',
    appDataEntityId: 'web.master',
    controlParam: {},
    modelId: 'a1200a1291f9d90c250f1f54295d6bf0',
    modelType: 'PSSYSVIEWLAYOUTPANEL',
    name: 'layoutpanel',
    id: 'usr0516896362',
  },
  title: '向导_逻辑_向导视图',
  viewStyle: 'DEFAULT',
  viewType: 'DEWIZARDVIEW',
  enableDP: true,
  showCaptionBar: false,
  modelId: '9846b02928fab21d9c29ef25c33195ab',
  modelType: 'PSAPPDEVIEW',
  name: 'MASTERWizardView_logic',
  id: 'web.master_wizard_view_logic',
};
