export default {
  gridRowActiveMode: 2,
  xdataControlName: 'grid',
  loadDefault: true,
  deviewCodeName: 'searchbar_base',
  deviewId: '39f3f839f7d3882c173e622f61de0c6e',
  accUserMode: 3,
  capLanguageRes: {
    lanResTag: 'DE.LNAME.MASTER',
  },
  caption: '搜索栏_基础',
  codeName: 'master_searchbar_base',
  appDataEntityId: 'web.master',
  appViewMsgGroupId: 'searchbar_base',
  viewLayoutPanel: {
    viewProxyMode: true,
    layoutMode: 'FLEX',
    layout: {
      layout: 'FLEX',
    },
    rootPanelItems: [
      {
        actionGroupExtractMode: 'ITEM',
        panelItems: [
          {
            actionGroupExtractMode: 'ITEM',
            panelItems: [
              {
                actionGroupExtractMode: 'ITEM',
                panelItems: [
                  {
                    caption: '页面标题',
                    itemStyle: 'DEFAULT',
                    itemType: 'CTRLPOS',
                    layoutPos: {
                      shrink: 1,
                      layout: 'FLEX',
                    },
                    showCaption: true,
                    id: 'captionbar',
                  },
                ],
                layout: {
                  align: 'center',
                  layout: 'FLEX',
                },
                dataRegionType: 'INHERIT',
                caption: '容器',
                itemStyle: 'DEFAULT',
                itemType: 'CONTAINER',
                layoutPos: {
                  shrink: 1,
                  heightMode: 'FULL',
                  layout: 'FLEX',
                },
                id: 'view_captionbar',
              },
            ],
            layout: {
              layout: 'FLEX',
            },
            dataRegionType: 'INHERIT',
            caption: '容器',
            itemStyle: 'DEFAULT',
            itemType: 'CONTAINER',
            layoutPos: {
              shrink: 1,
              heightMode: 'FULL',
              layout: 'FLEX',
            },
            id: 'view_header_left',
          },
          {
            caption: '搜索栏',
            itemStyle: 'DEFAULT',
            itemType: 'CTRLPOS',
            layoutPos: {
              shrink: 1,
              layout: 'FLEX',
            },
            showCaption: true,
            id: 'searchbar',
          },
          {
            actionGroupExtractMode: 'ITEM',
            panelItems: [
              {
                actionGroupExtractMode: 'ITEM',
                panelItems: [
                  {
                    caption: '工具栏',
                    itemStyle: 'DEFAULT',
                    itemType: 'CTRLPOS',
                    layoutPos: {
                      shrink: 1,
                      layout: 'FLEX',
                    },
                    showCaption: true,
                    id: 'toolbar',
                  },
                ],
                layout: {
                  align: 'center',
                  layout: 'FLEX',
                },
                dataRegionType: 'INHERIT',
                caption: '容器',
                itemStyle: 'DEFAULT',
                itemType: 'CONTAINER',
                layoutPos: {
                  shrink: 1,
                  heightMode: 'FULL',
                  layout: 'FLEX',
                },
                id: 'view_toolbar',
              },
            ],
            layout: {
              layout: 'FLEX',
            },
            dataRegionType: 'INHERIT',
            caption: '容器',
            itemStyle: 'DEFAULT',
            itemType: 'CONTAINER',
            layoutPos: {
              shrink: 1,
              heightMode: 'FULL',
              layout: 'FLEX',
            },
            id: 'view_header_right',
          },
        ],
        predefinedType: 'VIEWHEADER',
        layout: {
          align: 'space-between',
          dir: 'row',
          layout: 'FLEX',
          valign: 'center',
        },
        dataRegionType: 'INHERIT',
        caption: '容器',
        itemStyle: 'DEFAULT',
        itemType: 'CONTAINER',
        layoutPos: {
          shrink: 0,
          layout: 'FLEX',
        },
        id: 'view_header',
      },
      {
        actionGroupExtractMode: 'ITEM',
        panelItems: [
          {
            caption: '表格',
            itemStyle: 'DEFAULT',
            itemType: 'CTRLPOS',
            layoutPos: {
              grow: 1,
              shrink: 1,
              layout: 'FLEX',
            },
            showCaption: true,
            id: 'grid',
          },
        ],
        predefinedType: 'VIEWCONTENT',
        layout: {
          layout: 'FLEX',
        },
        dataRegionType: 'INHERIT',
        caption: '容器',
        itemStyle: 'DEFAULT',
        itemType: 'CONTAINER',
        layoutPos: {
          grow: 1,
          shrink: 1,
          layout: 'FLEX',
        },
        id: 'view_content',
      },
    ],
    layoutPanel: true,
    appViewEngines: [
      {
        engineCat: 'VIEW',
        engineType: 'GridView',
        id: 'engine',
      },
    ],
    appViewLogics: [
      {
        logicTrigger: 'CUSTOM',
        logicType: 'APPUILOGIC',
        builtinAppUILogic: {
          actionAfterWizard: 'DEFAULT',
          newDataAppView: {
            openMode: 'POPUPMODAL',
            refAppViewId: 'web.master_edit_view',
          },
          appUILogicRefViews: [
            {
              openMode: 'POPUPMODAL',
              refAppViewId: 'web.master_edit_view',
            },
          ],
          builtinLogic: true,
          logicType: 'PREDEFINED',
          viewLogicType: 'APP_NEWDATA',
          id: '新建数据',
        },
        builtinLogic: true,
        id: 'newdata',
      },
      {
        logicTrigger: 'CUSTOM',
        logicType: 'APPUILOGIC',
        builtinAppUILogic: {
          openDataAppView: {
            refAppViewId: 'web.master_redirect_view',
          },
          editMode: true,
          appUILogicRefViews: [
            {
              refAppViewId: 'web.master_redirect_view',
            },
          ],
          builtinLogic: true,
          logicType: 'PREDEFINED',
          viewLogicType: 'APP_OPENDATA',
          id: '打开数据',
        },
        builtinLogic: true,
        id: 'opendata',
      },
    ],
    appViewRefs: [
      {
        realOpenMode: 'POPUPMODAL',
        realTitle: '主数据编辑视图',
        refAppViewId: 'web.master_edit_view',
        name: 'NEWDATA',
        id: 'newdata',
      },
      {
        realTitle: '主数据数据重定向视图',
        refAppViewId: 'web.master_redirect_view',
        name: 'EDITDATA',
        id: 'editdata',
      },
    ],
    controls: [
      {
        aggMode: 'NONE',
        columnEnableFilter: 2,
        columnEnableLink: 2,
        groupMode: 'NONE',
        groupStyle: 'DEFAULT',
        degridColumns: [
          {
            clconvertMode: 'NONE',
            dataItemName: 'name',
            excelCaption: '名称',
            appDEFieldId: 'name',
            valueType: 'SIMPLE',
            enableRowEdit: true,
            aggMode: 'NONE',
            align: 'LEFT',
            capLanguageRes: {
              lanResTag: 'DEF.LNAME.MASTER.NAME',
            },
            caption: '名称',
            codeName: 'name',
            columnType: 'DEFGRIDCOLUMN',
            noPrivDisplayMode: 1,
            width: 150,
            widthUnit: 'PX',
            enableSort: true,
            id: 'name',
          },
          {
            clconvertMode: 'NONE',
            dataItemName: 'quantity',
            excelCaption: '数量',
            appDEFieldId: 'quantity',
            valueType: 'SIMPLE',
            aggMode: 'NONE',
            align: 'LEFT',
            caption: '数量',
            codeName: 'quantity',
            columnType: 'DEFGRIDCOLUMN',
            noPrivDisplayMode: 1,
            width: 150,
            widthUnit: 'PX',
            enableSort: true,
            id: 'quantity',
          },
          {
            clconvertMode: 'FRONT',
            dataItemName: 'status',
            excelCaption: '状态',
            appCodeListId: 'web.mock__cl_status',
            appDEFieldId: 'status',
            valueType: 'SIMPLE',
            aggMode: 'NONE',
            align: 'LEFT',
            caption: '状态',
            codeName: 'status',
            columnType: 'DEFGRIDCOLUMN',
            noPrivDisplayMode: 1,
            width: 150,
            widthUnit: 'PX',
            enableSort: true,
            id: 'status',
          },
        ],
        degridDataItems: [
          {
            appDEFieldId: 'name',
            valueType: 'SIMPLE',
            dataType: 25,
            id: 'name',
          },
          {
            appDEFieldId: 'quantity',
            valueType: 'SIMPLE',
            dataType: 6,
            id: 'quantity',
          },
          {
            appDEFieldId: 'status',
            valueType: 'SIMPLE',
            dataType: 9,
            id: 'status',
          },
          {
            appDEFieldId: 'id',
            valueType: 'SIMPLE',
            dataType: 25,
            id: 'srfkey',
          },
          {
            appDEFieldId: 'id',
            valueType: 'SIMPLE',
            dataType: 25,
            id: 'srfdataaccaction',
          },
          {
            appDEFieldId: 'region_id',
            valueType: 'SIMPLE',
            dataType: 25,
            id: 'region_id',
          },
          {
            appDEFieldId: 'name',
            valueType: 'SIMPLE',
            dataType: 25,
            id: 'srfmajortext',
          },
        ],
        degridEditItems: [
          {
            caption: '名称',
            codeName: 'name',
            enableCond: 3,
            appDEFieldId: 'name',
            editor: {
              maxLength: 200,
              editorType: 'TEXTBOX',
              editorItems: [
                {
                  id: 'name',
                },
              ],
              valueType: 'SIMPLE',
              editable: true,
              id: 'name',
            },
            allowEmpty: true,
            id: 'name',
          },
          {
            caption: '标识',
            codeName: 'srfkey',
            enableCond: 3,
            appDEFieldId: 'id',
            editor: {
              editorType: 'HIDDEN',
              valueType: 'SIMPLE',
              editable: true,
              id: 'srfkey',
            },
            allowEmpty: true,
            id: 'srfkey',
          },
        ],
        pagingMode: 1,
        pagingSize: 10,
        sortMode: 'REMOTE',
        enableCustomized: true,
        enablePagingBar: true,
        navViewPos: 'NONE',
        fetchControlAction: {
          appDEMethodId: 'fetch_default',
          appDataEntityId: 'web.master',
          id: 'fetch',
        },
        removeControlAction: {
          appDEMethodId: 'remove',
          appDataEntityId: 'web.master',
          id: 'remove',
        },
        autoLoad: true,
        showBusyIndicator: true,
        codeName: 'searchbar_base_grid',
        controlType: 'GRID',
        logicName: '搜索栏_基础_表格',
        appDataEntityId: 'web.master',
        controlParam: {
          id: 'grid',
        },
        modelId: '37d59451c194db1b1ee65d7ef8e755d4',
        modelType: 'PSDEGRID',
        name: 'grid',
        id: 'web.master.searchbar_base_grid',
      },
      {
        groupMode: 'SINGLE',
        groupMoreText: '更多',
        searchBarFilters: [
          {
            dataType: 25,
            labelPos: 'NONE',
            defsearchMode: {
              codeName: 'N_TYPE_EQ',
              stdDataType: 25,
              valueOP: 'EQ',
              name: 'N_TYPE_EQ',
              id: 'n_type_eq',
            },
            editor: {
              singleSelect: true,
              appCodeListId: 'web.mock__cl_categories',
              editorType: 'DROPDOWNLIST',
              valueType: 'SIMPLE',
              editable: true,
              id: 'n_type_eq',
            },
            allowEmpty: true,
            needCodeListConfig: true,
            caption: '类型',
            itemType: 'FILTER',
            appDEFieldId: 'type',
            id: 'n_type_eq',
          },
          {
            dataType: 6,
            labelPos: 'NONE',
            defsearchMode: {
              codeName: 'N_QUANTITY_LT',
              stdDataType: 6,
              valueOP: 'LT',
              name: 'N_QUANTITY_LT',
              id: 'n_quantity_lt',
            },
            editor: {
              editorType: 'TEXTBOX',
              valueType: 'SIMPLE',
              editable: true,
              id: 'n_quantity_lt',
            },
            allowEmpty: true,
            caption: '数量',
            itemType: 'FILTER',
            appDEFieldId: 'quantity',
            id: 'n_quantity_lt',
          },
          {
            dataType: 6,
            labelPos: 'NONE',
            defsearchMode: {
              codeName: 'N_QUANTITY_GT',
              stdDataType: 6,
              valueOP: 'GT',
              name: 'N_QUANTITY_GT',
              id: 'n_quantity_gt',
            },
            editor: {
              editorType: 'TEXTBOX',
              valueType: 'SIMPLE',
              editable: true,
              id: 'n_quantity_gt',
            },
            allowEmpty: true,
            caption: '数量',
            itemType: 'FILTER',
            appDEFieldId: 'quantity',
            id: 'n_quantity_gt',
          },
        ],
        searchBarGroups: [
          {
            caption: '全部',
            itemType: 'GROUP',
            id: 'all',
          },
          {
            caption: '正常',
            data: '{"theme_model":{"searchconds":[{"condtype":"GROUP","condop":"AND","bnotmode":false,"searchconds":[{"condtype":"DEFIELD","fieldname":"status","condop":"EQ","value":"1"}]}]}}',
            itemType: 'GROUP',
            appDEFieldId: 'status',
            id: 'status_1',
          },
          {
            caption: '停用',
            data: '{"theme_model":{"searchconds":[{"condtype":"GROUP","condop":"AND","bnotmode":false,"searchconds":[{"condtype":"DEFIELD","fieldname":"status","condop":"EQ","value":"0"}]}]}}',
            itemType: 'GROUP',
            appDEFieldId: 'status',
            id: 'status_0',
          },
        ],
        quickGroupCount: 3,
        quickSearchMode: 2,
        quickSearchWidth: 300,
        searchBarStyle: 'SEARCHBAR2',
        enableFilter: true,
        enableGroup: true,
        enableQuickSearch: true,
        codeName: 'usr0516231784',
        controlType: 'SEARCHBAR',
        logicName: '搜索栏_基础',
        appDataEntityId: 'web.master',
        controlParam: {
          id: 'searchbar',
        },
        modelId: '25b03ee8f0b49425146e6610d381d52d',
        modelType: 'PSSYSSEARCHBAR',
        name: 'searchbar',
        id: 'web.master.usr0516231784',
      },
      {
        capLanguageRes: {
          lanResTag: 'DE.LNAME.MASTER',
        },
        caption: '搜索栏_基础',
        codeName: 'searchbar_base_captionbar',
        controlType: 'CAPTIONBAR',
        appDataEntityId: 'web.master',
        controlParam: {},
        name: 'captionbar',
        id: 'searchbar_base_captionbar',
      },
    ],
    codeName: 'usr0516011278',
    controlType: 'VIEWLAYOUTPANEL',
    logicName: 'searchbar_base表格视图布局',
    appDataEntityId: 'web.master',
    controlParam: {},
    modelId: '175c8d9c6f0a88119b20a304b893a7a8',
    modelType: 'PSSYSVIEWLAYOUTPANEL',
    name: 'layoutpanel',
    id: 'usr0516011278',
  },
  title: '搜索栏_基础',
  viewStyle: 'DEFAULT',
  viewType: 'DEGRIDVIEW',
  enableDP: true,
  showCaptionBar: false,
  modelId: 'a798fc5b4864e1e62ef1f0fa1dea33cd',
  modelType: 'PSAPPDEVIEW',
  name: 'MASTERsearchbar_base',
  id: 'web.master_searchbar_base',
};
