export default {
  enableSearch: true,
  loadDefault: true,
  deviewCodeName: 'Chart_line',
  deviewId: '5cf22d839468d097cf75b9fc5364539b',
  accUserMode: 3,
  capLanguageRes: {
    lanResTag: 'DE.LNAME.MASTER',
  },
  caption: '图表_折线图',
  codeName: 'master_chart_line',
  appDataEntityId: 'web.master',
  appViewEngines: [
    {
      engineCat: 'VIEW',
      engineType: 'ChartView',
      id: 'engine',
    },
  ],
  appViewMsgGroupId: 'chart_line',
  controls: [
    {
      searchButtonStyle: 'DEFAULT',
      deformPages: [
        {
          layout: {
            columnCount: 24,
            layout: 'TABLE_24COL',
          },
          caption: '常规条件',
          codeName: 'formpage1',
          detailStyle: 'DEFAULT',
          detailType: 'FORMPAGE',
          id: 'formpage1',
        },
      ],
      layout: {
        columnCount: 24,
        layout: 'TABLE_24COL',
      },
      tabHeaderPos: 'TOP',
      noTabHeader: true,
      autoLoad: true,
      showBusyIndicator: true,
      codeName: 'master_chart_line_search_form',
      controlType: 'SEARCHFORM',
      logicName: '图表_折线图_搜索表单',
      appDataEntityId: 'web.master',
      controlParam: {
        id: 'searchform',
      },
      modelId: 'bd9f470712028ab2c973dff489ab1472',
      modelType: 'PSDEFORM_SEARCHFORM',
      name: 'searchform',
      id: 'web.master.master_chart_line_search_form',
    },
    {
      coordinateSystem: 'XY',
      chartCoordinateSystems: [
        {
          chartGrid: {
            chartGridXAxis0Id: '0',
            chartGridYAxis0Id: '0',
            chartCoordinateSystemId: '0',
            type: 'grid',
            name: '[line_0]直角坐标系[0]',
            id: '0',
          },
          echartsType: 'cartesian2d',
          type: 'XY',
          name: '[line_0]直角坐标系[0]',
          id: '0',
        },
      ],
      dechartDataGrid: {
        id: '0',
      },
      dechartLegend: {
        legendPos: 'BOTTOM',
        showLegend: true,
        id: '0',
      },
      dechartSerieses: [
        {
          catalogField: 'DATE',
          echartsType: 'line',
          chartCoordinateSystemId: '0',
          chartDataSetId: '0',
          chartSeriesEncode: {
            chartXAxisId: '0',
            chartYAxisId: '0',
            x: ['DATE'],
            y: ['QUANTITY'],
            type: 'XY',
            name: '坐标系编码',
            id: '0',
          },
          seriesLayoutBy: 'column',
          seriesType: 'line',
          valueField: 'QUANTITY',
          enableChartDataSet: true,
          userParam: {
            'EC.lineStyle': '{"color":"#29939A"}',
          },
          id: 'line_0',
        },
      ],
      dechartTitle: {
        title: '折线图',
        titlePos: 'LEFT',
        id: '0',
      },
      chartDataSetGroups: [
        {
          appDEDataSetId: 'fetch_default',
          appDataEntityId: 'web.master',
          name: 'DEFAULT',
          id: '0',
        },
      ],
      chartDataSets: [
        {
          chartDataSetFields: [
            {
              groupField: true,
              name: 'DATE',
              id: '0',
            },
            {
              index: 1,
              name: 'QUANTITY',
              id: '1',
            },
          ],
          name: 'line_0-DEFAULT',
          id: '0',
        },
      ],
      chartGrids: [
        {
          chartGridXAxis0Id: '0',
          chartGridYAxis0Id: '0',
          chartCoordinateSystemId: '0',
          type: 'grid',
          name: '[line_0]直角坐标系[0]',
          id: '0',
        },
      ],
      chartXAxises: [
        {
          echartsPos: 'xAxis',
          echartsType: 'category',
          position: 'bottom',
          type: 'category',
          name: 'axis_xAxis_0',
          id: '0',
        },
      ],
      chartYAxises: [
        {
          echartsPos: 'yAxis',
          echartsType: 'value',
          position: 'left',
          type: 'numeric',
          name: 'axis_yAxis_0',
          id: '0',
        },
      ],
      navViewPos: 'NONE',
      fetchControlAction: {
        appDEMethodId: 'fetch_default',
        appDataEntityId: 'web.master',
        id: 'fetch',
      },
      readOnly: true,
      autoLoad: true,
      showBusyIndicator: true,
      codeName: 'master_chart_line_chart',
      controlType: 'CHART',
      height: 300,
      logicName: 'Chart2',
      appDataEntityId: 'web.master',
      controlParam: {
        id: 'chart',
      },
      modelId: '5ed9a01573da5b7a69f5fed84d809be5',
      modelType: 'PSDECHART',
      userParam: {
        'EC.color':
          '["#5470c6","#91cc75","#fac858","#ee6666","#73c0de","#3ba272","#fc8452","#9a60b4","#ea7ccc","#5470c6","#91cc75"]',
      },
      name: 'chart',
      id: 'web.master.master_chart_line_chart',
    },
    {
      capLanguageRes: {
        lanResTag: 'DE.LNAME.MASTER',
      },
      caption: '图表_折线图',
      codeName: 'chart_line_captionbar',
      controlType: 'CAPTIONBAR',
      appDataEntityId: 'web.master',
      controlParam: {},
      name: 'captionbar',
      id: 'chart_line_captionbar',
    },
  ],
  viewLayoutPanel: {
    layoutBodyOnly: true,
    useDefaultLayout: true,
    layoutPanel: true,
    codeName: 'layoutpanel',
    controlStyle: 'APPDECHARTVIEW',
    controlType: 'VIEWLAYOUTPANEL',
    appDataEntityId: 'web.master',
    controlParam: {},
    id: 'layoutpanel',
  },
  title: '图表_折线图',
  viewStyle: 'DEFAULT',
  viewType: 'DECHARTVIEW',
  enableDP: true,
  showCaptionBar: false,
  modelId: 'f3fc5ca03c8f7719d311ff942d25636a',
  modelType: 'PSAPPDEVIEW',
  name: 'MASTERChart_line',
  id: 'web.master_chart_line',
};
