export default {
  enableDirtyChecking: true,
  showDataInfoBar: true,
  xdataControlName: 'form',
  loadDefault: true,
  deviewCodeName: 'form_defiupdate',
  deviewId: '97231492b3b82046bdf981dbb7f58116',
  accUserMode: 2,
  capLanguageRes: {
    lanResTag: 'DE.LNAME.MASTER',
  },
  caption: '编辑表单_表单项更新',
  codeName: 'master_form_defiupdate',
  appDataEntityId: 'web.master',
  appViewEngines: [
    {
      engineCat: 'VIEW',
      engineType: 'EditView',
      id: 'engine',
    },
  ],
  controls: [
    {
      xdataControlName: 'form',
      codeName: 'form_defiupdate_toolbar',
      controlType: 'TOOLBAR',
      logicName: '编辑表单_表单项更新_工具栏',
      appDataEntityId: 'web.master',
      controlParam: {
        id: 'toolbar',
      },
      modelId: '6bebd995bf1bb0a3aa27b77e42ed6374',
      modelType: 'PSDETOOLBAR',
      name: 'toolbar',
      id: 'form_defiupdate_toolbar',
    },
    {
      createControlAction: {
        appDEMethodId: 'create',
        appDataEntityId: 'web.master',
        id: 'create',
      },
      getDraftFromControlAction: {
        appDataEntityId: 'web.master',
        id: 'loaddraftfrom',
      },
      getDraftControlAction: {
        appDEMethodId: 'get_draft',
        appDataEntityId: 'web.master',
        id: 'loaddraft',
      },
      getControlAction: {
        appDEMethodId: 'get',
        appDataEntityId: 'web.master',
        id: 'load',
      },
      removeControlAction: {
        appDEMethodId: 'remove',
        appDataEntityId: 'web.master',
        id: 'remove',
      },
      updateControlAction: {
        appDEMethodId: 'update',
        appDataEntityId: 'web.master',
        id: 'update',
      },
      deformItemUpdates: [
        {
          codeName: 'fillRegionCode',
          appDEMethodId: 'fill_region_code',
          defiupdateDetails: [
            {
              id: 'code',
            },
          ],
          showBusyIndicator: true,
          name: '填充区划信息',
          id: 'fillregioncode',
        },
        {
          codeName: 'calTotal',
          defiupdateDetails: [
            {
              id: 'total',
            },
          ],
          scriptCode:
            'if (data.quantity != null) {\r\n    return {total:data.quantity * data.unit_price};\r\n}',
          customCode: true,
          showBusyIndicator: true,
          name: '计算合计',
          id: 'caltotal',
        },
      ],
      deformPages: [
        {
          layout: {
            columnCount: 24,
            layout: 'TABLE_24COL',
          },
          deformDetails: [
            {
              layout: {
                columnCount: 24,
                layout: 'TABLE_24COL',
              },
              deformDetails: [
                {
                  layout: {
                    columnCount: 24,
                    layout: 'TABLE_24COL',
                  },
                  deformDetails: [
                    {
                      dataType: 25,
                      enableCond: 3,
                      labelPos: 'LEFT',
                      labelWidth: 130,
                      noPrivDisplayMode: 1,
                      deformItemUpdateId: 'caltotal',
                      editor: {
                        editorType: 'NUMBER',
                        valueType: 'SIMPLE',
                        editable: true,
                        id: 'quantity',
                      },
                      allowEmpty: true,
                      caption: '数量',
                      codeName: 'quantity',
                      detailStyle: 'DEFAULT',
                      detailType: 'FORMITEM',
                      layoutPos: {
                        colMD: 24,
                        layout: 'TABLE_24COL',
                      },
                      showCaption: true,
                      id: 'quantity',
                    },
                    {
                      dataType: 25,
                      enableCond: 3,
                      labelPos: 'LEFT',
                      labelWidth: 130,
                      noPrivDisplayMode: 1,
                      deformItemUpdateId: 'caltotal',
                      editor: {
                        editorType: 'NUMBER',
                        valueType: 'SIMPLE',
                        editable: true,
                        id: 'unit_price',
                      },
                      allowEmpty: true,
                      caption: '单价',
                      codeName: 'unit_price',
                      detailStyle: 'DEFAULT',
                      detailType: 'FORMITEM',
                      layoutPos: {
                        colMD: 24,
                        layout: 'TABLE_24COL',
                      },
                      showCaption: true,
                      id: 'unit_price',
                    },
                    {
                      dataType: 25,
                      enableCond: 3,
                      labelPos: 'LEFT',
                      labelWidth: 130,
                      noPrivDisplayMode: 1,
                      editor: {
                        editorType: 'NUMBER',
                        valueType: 'SIMPLE',
                        editable: true,
                        id: 'total',
                      },
                      allowEmpty: true,
                      caption: '合计',
                      codeName: 'total',
                      detailStyle: 'DEFAULT',
                      detailType: 'FORMITEM',
                      layoutPos: {
                        colMD: 24,
                        layout: 'TABLE_24COL',
                      },
                      showCaption: true,
                      id: 'total',
                    },
                  ],
                  codeName: 'grouppanel2',
                  detailStyle: 'DEFAULT',
                  detailType: 'GROUPPANEL',
                  layoutPos: {
                    colLG: 8,
                    colMD: 8,
                    layout: 'TABLE_24COL',
                  },
                  id: 'grouppanel2',
                },
                {
                  rawItem: {
                    caption: '修改数量或单价后，计算合计',
                    halign: 'LEFT',
                    valign: 'MIDDLE',
                    wrapMode: 'NOWRAP',
                    contentType: 'RAW',
                    id: 'rawitem1',
                  },
                  codeName: 'rawitem1',
                  detailStyle: 'DEFAULT',
                  detailType: 'RAWITEM',
                  layoutPos: {
                    colLG: 16,
                    colMD: 16,
                    layout: 'TABLE_24COL',
                  },
                  showCaption: true,
                  id: 'rawitem1',
                },
              ],
              caption: '前端脚本模式',
              codeName: 'group1',
              detailStyle: 'DEFAULT',
              detailType: 'GROUPPANEL',
              layoutPos: {
                colMD: 24,
                layout: 'TABLE_24COL',
              },
              showCaption: true,
              id: 'group1',
            },
            {
              layout: {
                columnCount: 24,
                layout: 'TABLE_24COL',
              },
              deformDetails: [
                {
                  layout: {
                    columnCount: 24,
                    layout: 'TABLE_24COL',
                  },
                  deformDetails: [
                    {
                      dataType: 25,
                      enableCond: 3,
                      labelPos: 'LEFT',
                      labelWidth: 130,
                      noPrivDisplayMode: 1,
                      deformItemUpdateId: 'fillregioncode',
                      editor: {
                        singleSelect: true,
                        appDEACModeId: 'default',
                        appDEDataSetId: 'fetch_default',
                        appDataEntityId: 'web.region',
                        enableAC: true,
                        forceSelection: true,
                        showTrigger: true,
                        valueItemName: 'region_id',
                        editorParams: {
                          AC: 'TRUE',
                          TRIGGER: 'TRUE',
                          PICKUPVIEW: 'FALSE',
                        },
                        editorType: 'PICKEREX_TRIGGER',
                        editorItems: [
                          {
                            id: 'region_id',
                          },
                        ],
                        valueType: 'SIMPLE',
                        editable: true,
                        id: 'region_name',
                      },
                      allowEmpty: true,
                      caption: '区划名称',
                      codeName: 'region_name',
                      detailStyle: 'DEFAULT',
                      detailType: 'FORMITEM',
                      layoutPos: {
                        colMD: 24,
                        layout: 'TABLE_24COL',
                      },
                      showCaption: true,
                      id: 'region_name',
                    },
                    {
                      dataType: 25,
                      enableCond: 3,
                      labelPos: 'LEFT',
                      labelWidth: 130,
                      noPrivDisplayMode: 1,
                      editor: {
                        editorType: 'TEXTBOX',
                        valueType: 'SIMPLE',
                        editable: true,
                        id: 'code',
                      },
                      allowEmpty: true,
                      caption: '编号',
                      codeName: 'code',
                      detailStyle: 'DEFAULT',
                      detailType: 'FORMITEM',
                      layoutPos: {
                        colMD: 24,
                        layout: 'TABLE_24COL',
                      },
                      showCaption: true,
                      id: 'code',
                    },
                  ],
                  codeName: 'grouppanel3',
                  detailStyle: 'DEFAULT',
                  detailType: 'GROUPPANEL',
                  layoutPos: {
                    colLG: 8,
                    colMD: 8,
                    layout: 'TABLE_24COL',
                  },
                  id: 'grouppanel3',
                },
                {
                  rawItem: {
                    caption: '通过选择的区划，调用接口查询并回填区划的编号',
                    halign: 'LEFT',
                    valign: 'MIDDLE',
                    wrapMode: 'NOWRAP',
                    contentType: 'RAW',
                    id: 'rawitem2',
                  },
                  codeName: 'rawitem2',
                  detailStyle: 'DEFAULT',
                  detailType: 'RAWITEM',
                  layoutPos: {
                    colLG: 16,
                    colMD: 16,
                    layout: 'TABLE_24COL',
                  },
                  showCaption: true,
                  id: 'rawitem2',
                },
                {
                  dataType: 25,
                  enableCond: 3,
                  labelPos: 'LEFT',
                  labelWidth: 130,
                  noPrivDisplayMode: 1,
                  appDEFieldId: 'region_id',
                  editor: {
                    editorType: 'HIDDEN',
                    valueType: 'SIMPLE',
                    editable: true,
                    id: 'region_id',
                  },
                  allowEmpty: true,
                  hidden: true,
                  caption: '区划标识',
                  codeName: 'region_id',
                  detailStyle: 'DEFAULT',
                  detailType: 'FORMITEM',
                  layoutPos: {
                    colMD: 24,
                    layout: 'TABLE_24COL',
                  },
                  id: 'region_id',
                },
              ],
              caption: '服务接口模式',
              codeName: 'grouppanel1',
              detailStyle: 'DEFAULT',
              detailType: 'GROUPPANEL',
              layoutPos: {
                colMD: 24,
                layout: 'TABLE_24COL',
              },
              showCaption: true,
              id: 'grouppanel1',
            },
            {
              dataType: 25,
              enableCond: 3,
              labelPos: 'LEFT',
              labelWidth: 130,
              noPrivDisplayMode: 1,
              appDEFieldId: 'id',
              editor: {
                editorType: 'HIDDEN',
                valueType: 'SIMPLE',
                editable: true,
                id: 'id',
              },
              allowEmpty: true,
              hidden: true,
              capLanguageRes: {
                lanResTag: 'DEF.LNAME.MASTER.ID',
              },
              caption: '标识',
              codeName: 'id',
              detailStyle: 'DEFAULT',
              detailType: 'FORMITEM',
              layoutPos: {
                colMD: 24,
                layout: 'TABLE_24COL',
              },
              id: 'id',
            },
          ],
          caption: '基本信息',
          codeName: 'formpage1',
          detailStyle: 'DEFAULT',
          detailType: 'FORMPAGE',
          id: 'formpage1',
        },
      ],
      layout: {
        columnCount: 24,
        layout: 'TABLE_24COL',
      },
      tabHeaderPos: 'TOP',
      noTabHeader: true,
      autoLoad: true,
      showBusyIndicator: true,
      codeName: 'main74',
      controlType: 'FORM',
      logicName: '编辑表单_表单项更新_表单',
      appDataEntityId: 'web.master',
      controlParam: {
        id: 'form',
      },
      modelId: '45ca0d850a8b81cb95643ec3608d60c4',
      modelType: 'PSDEFORM_EDITFORM',
      name: 'form',
      id: 'web.master.main74',
    },
    {
      codeName: 'form_defiupdate_datainfobar',
      controlType: 'DATAINFOBAR',
      appDataEntityId: 'web.master',
      controlParam: {
        id: 'datainfobar',
      },
      name: 'datainfobar',
      id: 'form_defiupdate_datainfobar',
    },
    {
      capLanguageRes: {
        lanResTag: 'DE.LNAME.MASTER',
      },
      caption: '编辑表单_表单项更新',
      codeName: 'form_defiupdate_captionbar',
      controlType: 'CAPTIONBAR',
      appDataEntityId: 'web.master',
      controlParam: {},
      name: 'captionbar',
      id: 'form_defiupdate_captionbar',
    },
  ],
  viewLayoutPanel: {
    layoutBodyOnly: true,
    useDefaultLayout: true,
    layoutPanel: true,
    codeName: 'layoutpanel',
    controlStyle: 'APPDEEDITVIEW',
    controlType: 'VIEWLAYOUTPANEL',
    appDataEntityId: 'web.master',
    controlParam: {},
    id: 'layoutpanel',
  },
  title: '编辑表单_表单项更新',
  viewStyle: 'DEFAULT',
  viewType: 'DEEDITVIEW',
  enableDP: true,
  showCaptionBar: false,
  modelId: '5a3c24a7bc32bf0b782303447b03429b',
  modelType: 'PSAPPDEVIEW',
  name: 'MASTERform_defiupdate',
  id: 'web.master_form_defiupdate',
};
