export default {
  tabLayout: 'FLOW',
  loadDefault: true,
  showDataInfoBar: true,
  deviewCodeName: 'form',
  deviewId: '0b3d9dc7cc8909b14e53de252fde4691',
  accUserMode: 3,
  capLanguageRes: {
    lanResTag: 'DE.LNAME.MASTER',
  },
  caption: '编辑表单',
  codeName: 'master_form',
  appDataEntityId: 'web.master',
  appViewEngines: [
    {
      engineCat: 'VIEW',
      engineType: 'TabExpView',
      id: 'engine',
    },
  ],
  appViewMsgGroupId: 'form',
  controls: [
    {
      dedrtabPages: [
        {
          caption: '基础',
          appViewId: 'web.master_form_base',
          id: 'base',
        },
        {
          caption: '信息表单',
          appViewId: 'web.master_form_info',
          id: 'info',
        },
        {
          caption: '编辑表单_hover',
          appViewId: 'web.master_form_hover',
          id: 'hover',
        },
        {
          caption: '编辑表单_多数据部件',
          appViewId: 'web.master_form_mctrl',
          id: 'mctrl',
        },
        {
          caption: '布局',
          appViewId: 'web.master_form_layout',
          id: 'layout',
        },
        {
          caption: '逻辑',
          appViewId: 'web.master_form_logic',
          id: 'logic',
        },
        {
          caption: '表单项更新',
          appViewId: 'web.master_form_defiupdate',
          id: 'defiupdate',
        },
        {
          caption: '界面样式及图标',
          appViewId: 'web.master_form_css',
          id: 'css',
        },
        {
          caption: '值显示',
          appViewId: 'web.master_form_value_display',
          id: 'value_display',
        },
      ],
      dataRelationTag: 'form_DR',
      editItemCapLanguageRes: {
        lanResTag: 'DE.LNAME.MASTER',
      },
      editItemCaption: '主数据',
      uniqueTag: 'master_form__tabexppanel',
      autoLoad: true,
      showBusyIndicator: true,
      codeName: 'form_dr',
      controlType: 'DRTAB',
      appDataEntityId: 'web.master',
      controlParam: {
        id: 'tabexppanel',
      },
      modelId: '321342bb968392d634609ce38f261bf3',
      modelType: 'PSDEDRTAB',
      name: 'tabexppanel',
      id: 'form_dr',
    },
    {
      capLanguageRes: {
        lanResTag: 'DE.LNAME.MASTER',
      },
      caption: '编辑表单',
      codeName: 'form_captionbar',
      controlType: 'CAPTIONBAR',
      appDataEntityId: 'web.master',
      controlParam: {},
      name: 'captionbar',
      id: 'form_captionbar',
    },
  ],
  viewLayoutPanel: {
    layoutBodyOnly: true,
    useDefaultLayout: true,
    layoutPanel: true,
    codeName: 'layoutpanel',
    controlStyle: 'APPDETABEXPVIEW',
    controlType: 'VIEWLAYOUTPANEL',
    appDataEntityId: 'web.master',
    controlParam: {},
    id: 'layoutpanel',
  },
  title: '编辑表单',
  viewStyle: 'DEFAULT',
  viewType: 'DETABEXPVIEW',
  enableDP: true,
  showCaptionBar: false,
  modelId: 'e698baa2b53893d3c03bddbfdf0c3824',
  modelType: 'PSAPPDEVIEW',
  name: 'MASTERform',
  id: 'web.master_form',
};
