export default {
  enableDirtyChecking: true,
  showDataInfoBar: true,
  xdataControlName: 'form',
  loadDefault: true,
  deviewCodeName: 'form_css',
  deviewId: '58889d5be3395f02219066ff33af257c',
  accUserMode: 3,
  capLanguageRes: {
    lanResTag: 'DE.LNAME.MASTER',
  },
  caption: '编辑表单_界面样式及图标',
  codeName: 'master_form_css',
  appDataEntityId: 'web.master',
  appViewEngines: [
    {
      engineCat: 'VIEW',
      engineType: 'EditView',
      id: 'engine',
    },
  ],
  appViewMsgGroupId: 'form_css',
  appViewNavContexts: [
    {
      rawValue: true,
      key: 'MASTER',
      value: 'sample',
      name: 'MASTER',
      id: 'master',
    },
  ],
  controls: [
    {
      createControlAction: {
        appDEMethodId: 'create',
        appDataEntityId: 'web.master',
        id: 'create',
      },
      getDraftFromControlAction: {
        appDataEntityId: 'web.master',
        id: 'loaddraftfrom',
      },
      getDraftControlAction: {
        appDEMethodId: 'get_draft',
        appDataEntityId: 'web.master',
        id: 'loaddraft',
      },
      getControlAction: {
        appDEMethodId: 'get_sample_date',
        appDataEntityId: 'web.master',
        id: 'load',
      },
      removeControlAction: {
        appDEMethodId: 'remove',
        appDataEntityId: 'web.master',
        id: 'remove',
      },
      updateControlAction: {
        appDEMethodId: 'update',
        appDataEntityId: 'web.master',
        id: 'update',
      },
      deformPages: [
        {
          layout: {
            columnCount: 24,
            layout: 'TABLE_24COL',
          },
          deformDetails: [
            {
              rawItem: {
                caption:
                  '表单样式表分为：容器样式表、标题样式表、编辑器样式；作用优先级采用就近原则',
                halign: 'LEFT',
                valign: 'MIDDLE',
                wrapMode: 'NOWRAP',
                contentType: 'RAW',
                sysCss: {
                  cssName: 'el-alert el-alert--info is-light',
                },
                id: 'rawitem1',
              },
              codeName: 'rawitem1',
              detailStyle: 'DEFAULT',
              detailType: 'RAWITEM',
              layoutPos: {
                colMD: 24,
                layout: 'TABLE_24COL',
              },
              sysCss: {
                cssName: 'el-alert el-alert--info is-light',
              },
              showCaption: true,
              id: 'rawitem1',
            },
            {
              layout: {
                columnCount: 24,
                layout: 'TABLE_24COL',
              },
              deformDetails: [
                {
                  dataType: 25,
                  enableCond: 3,
                  labelPos: 'LEFT',
                  labelWidth: 130,
                  noPrivDisplayMode: 1,
                  editor: {
                    editorType: 'TEXTBOX',
                    valueType: 'SIMPLE',
                    editable: true,
                    id: 'formitem',
                  },
                  allowEmpty: true,
                  caption: '收文单位',
                  codeName: 'formitem',
                  detailStyle: 'DEFAULT',
                  detailType: 'FORMITEM',
                  labelSysCss: {
                    cssName: 'editor-css-noborder',
                  },
                  layoutPos: {
                    colLG: 12,
                    colMD: 24,
                    layout: 'TABLE_24COL',
                  },
                  showCaption: true,
                  id: 'formitem',
                },
                {
                  dataType: 25,
                  enableCond: 3,
                  labelPos: 'LEFT',
                  labelWidth: 130,
                  noPrivDisplayMode: 1,
                  editor: {
                    editorType: 'TEXTBOX',
                    valueType: 'SIMPLE',
                    editable: true,
                    id: 'formitem1',
                  },
                  allowEmpty: true,
                  caption: '收文编号',
                  codeName: 'formitem1',
                  detailStyle: 'DEFAULT',
                  detailType: 'FORMITEM',
                  labelSysCss: {
                    cssName: 'editor-css-noborder',
                  },
                  layoutPos: {
                    colLG: 12,
                    colMD: 24,
                    layout: 'TABLE_24COL',
                  },
                  showCaption: true,
                  id: 'formitem1',
                },
                {
                  dataType: 25,
                  enableCond: 3,
                  labelPos: 'LEFT',
                  labelWidth: 130,
                  noPrivDisplayMode: 1,
                  editor: {
                    showMaxLength: true,
                    editorType: 'TEXTAREA',
                    valueType: 'SIMPLE',
                    editable: true,
                    id: 'formitem2',
                  },
                  allowEmpty: true,
                  caption: '收文内容',
                  codeName: 'formitem2',
                  detailStyle: 'DEFAULT',
                  detailType: 'FORMITEM',
                  labelSysCss: {
                    cssName: 'editor-css-noborder',
                  },
                  layoutPos: {
                    colLG: 24,
                    colMD: 24,
                    layout: 'TABLE_24COL',
                  },
                  showCaption: true,
                  id: 'formitem2',
                },
              ],
              caption: '收文样式',
              codeName: 'group1',
              detailStyle: 'DEFAULT',
              detailType: 'GROUPPANEL',
              labelSysCss: {
                cssName: 'formgroup-bold-center',
              },
              layoutPos: {
                colMD: 24,
                layout: 'TABLE_24COL',
              },
              showCaption: true,
              id: 'group1',
            },
            {
              rawItem: {
                caption:
                  '表单中的分组和表单项标签都可以设置图标，编辑器样式则可以定义编辑器的绘制',
                halign: 'LEFT',
                valign: 'MIDDLE',
                wrapMode: 'NOWRAP',
                contentType: 'RAW',
                sysCss: {
                  cssName: 'el-alert el-alert--info is-light',
                },
                id: 'rawitem2',
              },
              codeName: 'rawitem2',
              detailStyle: 'DEFAULT',
              detailType: 'RAWITEM',
              layoutPos: {
                colMD: 24,
                layout: 'TABLE_24COL',
              },
              sysCss: {
                cssName: 'el-alert el-alert--info is-light',
              },
              showCaption: true,
              id: 'rawitem2',
            },
            {
              layout: {
                columnCount: 24,
                layout: 'TABLE_24COL',
              },
              deformDetails: [
                {
                  dataType: 25,
                  enableCond: 3,
                  labelPos: 'LEFT',
                  labelWidth: 130,
                  noPrivDisplayMode: 1,
                  editor: {
                    editorType: 'TEXTBOX',
                    valueType: 'SIMPLE',
                    editable: true,
                    id: 'formitem3',
                  },
                  allowEmpty: true,
                  caption: '标签图标',
                  codeName: 'formitem3',
                  detailStyle: 'DEFAULT',
                  detailType: 'FORMITEM',
                  labelSysCss: {
                    cssName: 'blue-span',
                  },
                  layoutPos: {
                    colMD: 24,
                    layout: 'TABLE_24COL',
                  },
                  showCaption: true,
                  id: 'formitem3',
                },
                {
                  dataType: 25,
                  enableCond: 3,
                  labelPos: 'LEFT',
                  labelWidth: 130,
                  noPrivDisplayMode: 1,
                  editor: {
                    editorType: 'TEXTBOX',
                    valueType: 'SIMPLE',
                    editable: true,
                    id: 'formitem4',
                  },
                  allowEmpty: true,
                  caption: '无边框浅蓝背景',
                  codeName: 'formitem4',
                  detailStyle: 'DEFAULT',
                  detailType: 'FORMITEM',
                  labelSysCss: {
                    cssName: 'editor-css-noborder',
                  },
                  layoutPos: {
                    colMD: 24,
                    layout: 'TABLE_24COL',
                  },
                  showCaption: true,
                  id: 'formitem4',
                },
              ],
              caption: '分组图标',
              codeName: 'grouppanel1',
              detailStyle: 'DEFAULT',
              detailType: 'GROUPPANEL',
              layoutPos: {
                colMD: 24,
                layout: 'TABLE_24COL',
              },
              showCaption: true,
              id: 'grouppanel1',
            },
            {
              dataType: 25,
              enableCond: 3,
              labelPos: 'LEFT',
              labelWidth: 130,
              noPrivDisplayMode: 1,
              appDEFieldId: 'id',
              editor: {
                editorType: 'HIDDEN',
                valueType: 'SIMPLE',
                editable: true,
                id: 'id',
              },
              allowEmpty: true,
              hidden: true,
              capLanguageRes: {
                lanResTag: 'DEF.LNAME.MASTER.ID',
              },
              caption: '标识',
              codeName: 'id',
              detailStyle: 'DEFAULT',
              detailType: 'FORMITEM',
              layoutPos: {
                colMD: 24,
                layout: 'TABLE_24COL',
              },
              id: 'id',
            },
          ],
          caption: '基本信息',
          codeName: 'formpage1',
          detailStyle: 'DEFAULT',
          detailType: 'FORMPAGE',
          id: 'formpage1',
        },
      ],
      layout: {
        columnCount: 24,
        layout: 'TABLE_24COL',
      },
      tabHeaderPos: 'TOP',
      noTabHeader: true,
      autoLoad: true,
      showBusyIndicator: true,
      codeName: 'main18',
      controlType: 'FORM',
      logicName: '编辑表单_界面样式及图标_表单',
      appDataEntityId: 'web.master',
      controlParam: {
        id: 'form',
      },
      modelId: '0920702c22fbd4b05e55ac9215e5f91e',
      modelType: 'PSDEFORM_EDITFORM',
      name: 'form',
      id: 'web.master.main18',
    },
    {
      xdataControlName: 'form',
      codeName: 'form_css_toolbar',
      controlType: 'TOOLBAR',
      logicName: '编辑表单_界面样式及图标_工具栏',
      appDataEntityId: 'web.master',
      controlParam: {
        id: 'toolbar',
      },
      modelId: '3d60c862a3a52ad88ad5b0e7fa34e1a4',
      modelType: 'PSDETOOLBAR',
      name: 'toolbar',
      id: 'form_css_toolbar',
    },
    {
      codeName: 'form_css_datainfobar',
      controlType: 'DATAINFOBAR',
      appDataEntityId: 'web.master',
      controlParam: {
        id: 'datainfobar',
      },
      name: 'datainfobar',
      id: 'form_css_datainfobar',
    },
    {
      capLanguageRes: {
        lanResTag: 'DE.LNAME.MASTER',
      },
      caption: '编辑表单_界面样式及图标',
      codeName: 'form_css_captionbar',
      controlType: 'CAPTIONBAR',
      appDataEntityId: 'web.master',
      controlParam: {},
      name: 'captionbar',
      id: 'form_css_captionbar',
    },
  ],
  viewLayoutPanel: {
    layoutBodyOnly: true,
    useDefaultLayout: true,
    layoutPanel: true,
    codeName: 'layoutpanel',
    controlStyle: 'APPDEEDITVIEW',
    controlType: 'VIEWLAYOUTPANEL',
    appDataEntityId: 'web.master',
    controlParam: {},
    id: 'layoutpanel',
  },
  title: '编辑表单_界面样式及图标',
  viewStyle: 'DEFAULT',
  viewType: 'DEEDITVIEW',
  enableDP: true,
  showCaptionBar: false,
  modelId: 'f718d17266f1a0b036332b88857ed3c7',
  modelType: 'PSAPPDEVIEW',
  name: 'MASTERform_css',
  id: 'web.master_form_css',
};
