export default {
  deviewCodeName: 'grid_base',
  deviewId: '534f48c2a2963b071689fdd11c189f3f',
  accUserMode: 3,
  capLanguageRes: {
    lanResTag: 'DE.LNAME.MASTER',
  },
  caption: '表格_基础',
  codeName: 'master_grid_base',
  appDataEntityId: 'web.master',
  appViewMsgGroupId: 'grid_base',
  viewLayoutPanel: {
    viewProxyMode: true,
    layoutMode: 'FLEX',
    layout: {
      layout: 'FLEX',
    },
    rootPanelItems: [
      {
        actionGroupExtractMode: 'ITEM',
        panelItems: [
          {
            actionGroupExtractMode: 'ITEM',
            panelItems: [
              {
                dataRegionType: 'INHERIT',
                panelTabPages: [
                  {
                    panelItems: [
                      {
                        caption: '表格',
                        itemStyle: 'DEFAULT',
                        itemType: 'CTRLPOS',
                        layoutPos: {
                          shrink: 1,
                          layout: 'FLEX',
                        },
                        showCaption: true,
                        id: 'grid7',
                      },
                    ],
                    layout: {
                      layout: 'FLEX',
                    },
                    dataRegionType: 'INHERIT',
                    caption: '基础表格',
                    itemStyle: 'DEFAULT',
                    itemType: 'TABPAGE',
                    layoutPos: {
                      shrink: 1,
                      layout: 'FLEX',
                    },
                    showCaption: true,
                    id: 'tabpage6',
                  },
                  {
                    panelItems: [
                      {
                        caption: '表格',
                        itemStyle: 'DEFAULT',
                        itemType: 'CTRLPOS',
                        layoutPos: {
                          shrink: 1,
                          layout: 'FLEX',
                        },
                        showCaption: true,
                        id: 'grid',
                      },
                    ],
                    layout: {
                      layout: 'FLEX',
                    },
                    dataRegionType: 'INHERIT',
                    caption: '无值显示内容',
                    itemStyle: 'DEFAULT',
                    itemType: 'TABPAGE',
                    layoutPos: {
                      shrink: 1,
                      layout: 'FLEX',
                    },
                    showCaption: true,
                    id: 'tabpage',
                  },
                  {
                    panelItems: [
                      {
                        caption: '表格',
                        itemStyle: 'DEFAULT',
                        itemType: 'CTRLPOS',
                        layoutPos: {
                          shrink: 1,
                          layout: 'FLEX',
                        },
                        showCaption: true,
                        id: 'grid2',
                      },
                    ],
                    layout: {
                      layout: 'FLEX',
                    },
                    dataRegionType: 'INHERIT',
                    caption: '不显示头部',
                    itemStyle: 'DEFAULT',
                    itemType: 'TABPAGE',
                    layoutPos: {
                      shrink: 1,
                      layout: 'FLEX',
                    },
                    showCaption: true,
                    id: 'tabpage1',
                  },
                  {
                    panelItems: [
                      {
                        caption: '表格',
                        itemStyle: 'DEFAULT',
                        itemType: 'CTRLPOS',
                        layoutPos: {
                          shrink: 1,
                          layout: 'FLEX',
                        },
                        showCaption: true,
                        id: 'grid3',
                      },
                    ],
                    layout: {
                      layout: 'FLEX',
                    },
                    dataRegionType: 'INHERIT',
                    caption: '表头分组',
                    itemStyle: 'DEFAULT',
                    itemType: 'TABPAGE',
                    layoutPos: {
                      shrink: 1,
                      layout: 'FLEX',
                    },
                    showCaption: true,
                    id: 'tabpage2',
                  },
                  {
                    layout: {
                      layout: 'FLEX',
                    },
                    dataRegionType: 'INHERIT',
                    caption: '支持多选',
                    itemStyle: 'DEFAULT',
                    itemType: 'TABPAGE',
                    layoutPos: {
                      shrink: 1,
                      layout: 'FLEX',
                    },
                    showCaption: true,
                    id: 'tabpage3',
                  },
                  {
                    panelItems: [
                      {
                        actionGroupExtractMode: 'ITEM',
                        panelItems: [
                          {
                            caption: '表格',
                            itemStyle: 'DEFAULT',
                            itemType: 'CTRLPOS',
                            layoutPos: {
                              shrink: 1,
                              layout: 'FLEX',
                            },
                            showCaption: true,
                            id: 'grid4',
                          },
                        ],
                        predefinedType: 'CONTAINER_GROUP',
                        layout: {
                          layout: 'FLEX',
                        },
                        dataRegionType: 'INHERIT',
                        caption: '启用',
                        itemStyle: 'DEFAULT',
                        itemType: 'CONTAINER',
                        layoutPos: {
                          shrink: 1,
                          layout: 'FLEX',
                        },
                        showCaption: true,
                        id: 'container_group10',
                      },
                      {
                        actionGroupExtractMode: 'ITEM',
                        panelItems: [
                          {
                            caption: '表格',
                            itemStyle: 'DEFAULT',
                            itemType: 'CTRLPOS',
                            layoutPos: {
                              shrink: 1,
                              layout: 'FLEX',
                            },
                            showCaption: true,
                            id: 'grid5',
                          },
                        ],
                        predefinedType: 'CONTAINER_GROUP',
                        layout: {
                          layout: 'FLEX',
                        },
                        dataRegionType: 'INHERIT',
                        caption: '关闭',
                        itemStyle: 'DEFAULT',
                        itemType: 'CONTAINER',
                        layoutPos: {
                          shrink: 1,
                          layout: 'FLEX',
                        },
                        showCaption: true,
                        id: 'container_group11',
                      },
                    ],
                    layout: {
                      layout: 'FLEX',
                    },
                    dataRegionType: 'INHERIT',
                    caption: '分页与数量',
                    itemStyle: 'DEFAULT',
                    itemType: 'TABPAGE',
                    layoutPos: {
                      shrink: 1,
                      layout: 'FLEX',
                    },
                    showCaption: true,
                    id: 'tabpage4',
                  },
                  {
                    panelItems: [
                      {
                        caption: '表格',
                        itemStyle: 'DEFAULT',
                        itemType: 'CTRLPOS',
                        layoutPos: {
                          shrink: 1,
                          layout: 'FLEX',
                        },
                        showCaption: true,
                        id: 'grid6',
                      },
                    ],
                    layout: {
                      layout: 'FLEX',
                    },
                    dataRegionType: 'INHERIT',
                    caption: '适应屏宽',
                    itemStyle: 'DEFAULT',
                    itemType: 'TABPAGE',
                    layoutPos: {
                      shrink: 1,
                      layout: 'FLEX',
                    },
                    showCaption: true,
                    id: 'tabpage5',
                  },
                ],
                caption: '分页部件',
                itemStyle: 'DEFAULT',
                itemType: 'TABPANEL',
                layoutPos: {
                  layoutPos: 'CENTER',
                  layout: 'BORDER',
                  spacingLeft: 'OUTERMEDIUM',
                  spacingRight: 'OUTERMEDIUM',
                },
                id: 'tabpanel',
              },
            ],
            predefinedType: 'CONTAINER_SCROLL_MAIN',
            layout: {
              layout: 'BORDER',
            },
            dataRegionType: 'INHERIT',
            caption: '面板容器',
            itemStyle: 'DEFAULT',
            itemType: 'CONTAINER',
            layoutPos: {
              layoutPos: 'CENTER',
              layout: 'BORDER',
            },
            showCaption: true,
            id: 'container_scroll_main',
          },
        ],
        predefinedType: 'CONTAINER_SCROLL',
        layout: {
          layout: 'BORDER',
        },
        dataRegionType: 'INHERIT',
        caption: '滚动条容器',
        itemStyle: 'DEFAULT',
        itemType: 'CONTAINER',
        layoutPos: {
          grow: 1,
          shrink: 1,
          heightMode: 'FULL',
          layout: 'FLEX',
        },
        id: 'container_scroll',
      },
    ],
    layoutPanel: true,
    controls: [
      {
        aggMode: 'NONE',
        columnEnableFilter: 2,
        columnEnableLink: 2,
        emptyText: '当前不存在数据',
        groupMode: 'NONE',
        groupStyle: 'DEFAULT',
        degridColumns: [
          {
            clconvertMode: 'NONE',
            dataItemName: 'name',
            excelCaption: '名称',
            appDEFieldId: 'name',
            valueType: 'SIMPLE',
            aggMode: 'NONE',
            align: 'LEFT',
            capLanguageRes: {
              lanResTag: 'DEF.LNAME.MASTER.NAME',
            },
            caption: '名称',
            codeName: 'name',
            columnType: 'DEFGRIDCOLUMN',
            noPrivDisplayMode: 1,
            width: 150,
            widthUnit: 'PX',
            enableSort: true,
            id: 'name',
          },
        ],
        degridDataItems: [
          {
            appDEFieldId: 'name',
            valueType: 'SIMPLE',
            dataType: 25,
            id: 'name',
          },
          {
            appDEFieldId: 'id',
            valueType: 'SIMPLE',
            dataType: 25,
            id: 'srfkey',
          },
          {
            appDEFieldId: 'id',
            valueType: 'SIMPLE',
            dataType: 25,
            id: 'srfdataaccaction',
          },
          {
            appDEFieldId: 'region_id',
            valueType: 'SIMPLE',
            dataType: 25,
            id: 'region_id',
          },
          {
            appDEFieldId: 'name',
            valueType: 'SIMPLE',
            dataType: 25,
            id: 'srfmajortext',
          },
        ],
        degridEditItems: [
          {
            caption: '标识',
            codeName: 'srfkey',
            enableCond: 3,
            appDEFieldId: 'id',
            editor: {
              editorType: 'HIDDEN',
              valueType: 'SIMPLE',
              editable: true,
              id: 'srfkey',
            },
            allowEmpty: true,
            id: 'srfkey',
          },
        ],
        pagingMode: 1,
        pagingSize: 10,
        sortMode: 'REMOTE',
        enableCustomized: true,
        enablePagingBar: true,
        navViewPos: 'NONE',
        fetchControlAction: {
          appDEMethodId: 'fetch_emptydata',
          appDataEntityId: 'web.master',
          id: 'fetch',
        },
        removeControlAction: {
          appDEMethodId: 'remove',
          appDataEntityId: 'web.master',
          id: 'remove',
        },
        autoLoad: true,
        showBusyIndicator: true,
        codeName: 'grid_base1',
        controlType: 'GRID',
        logicName: '表格_基础_无值显示内容',
        appDataEntityId: 'web.master',
        controlParam: {
          id: 'grid',
        },
        modelId: '67eef23f4e666a05e7254977e78951a5',
        modelType: 'PSDEGRID',
        name: 'grid',
        id: 'web.master.grid_base1',
      },
      {
        aggMode: 'NONE',
        columnEnableFilter: 2,
        columnEnableLink: 2,
        groupMode: 'NONE',
        groupStyle: 'DEFAULT',
        degridColumns: [
          {
            clconvertMode: 'NONE',
            dataItemName: 'name',
            excelCaption: '名称',
            appDEFieldId: 'name',
            valueType: 'SIMPLE',
            aggMode: 'NONE',
            align: 'LEFT',
            capLanguageRes: {
              lanResTag: 'DEF.LNAME.MASTER.NAME',
            },
            caption: '名称',
            codeName: 'name',
            columnType: 'DEFGRIDCOLUMN',
            noPrivDisplayMode: 1,
            width: 150,
            widthUnit: 'PX',
            enableSort: true,
            id: 'name',
          },
        ],
        degridDataItems: [
          {
            appDEFieldId: 'name',
            valueType: 'SIMPLE',
            dataType: 25,
            id: 'name',
          },
          {
            appDEFieldId: 'id',
            valueType: 'SIMPLE',
            dataType: 25,
            id: 'srfkey',
          },
          {
            appDEFieldId: 'id',
            valueType: 'SIMPLE',
            dataType: 25,
            id: 'srfdataaccaction',
          },
          {
            appDEFieldId: 'region_id',
            valueType: 'SIMPLE',
            dataType: 25,
            id: 'region_id',
          },
          {
            appDEFieldId: 'name',
            valueType: 'SIMPLE',
            dataType: 25,
            id: 'srfmajortext',
          },
        ],
        degridEditItems: [
          {
            caption: '标识',
            codeName: 'srfkey',
            enableCond: 3,
            appDEFieldId: 'id',
            editor: {
              editorType: 'HIDDEN',
              valueType: 'SIMPLE',
              editable: true,
              id: 'srfkey',
            },
            allowEmpty: true,
            id: 'srfkey',
          },
        ],
        pagingMode: 1,
        pagingSize: 10,
        sortMode: 'REMOTE',
        enableCustomized: true,
        enablePagingBar: true,
        navViewPos: 'NONE',
        fetchControlAction: {
          appDEMethodId: 'fetch_default',
          appDataEntityId: 'web.master',
          id: 'fetch',
        },
        removeControlAction: {
          appDEMethodId: 'remove',
          appDataEntityId: 'web.master',
          id: 'remove',
        },
        autoLoad: true,
        showBusyIndicator: true,
        codeName: 'grid_base2',
        controlType: 'GRID',
        logicName: '表格_基础_显示表头',
        appDataEntityId: 'web.master',
        controlParam: {
          id: 'grid1',
        },
        modelId: 'edb288c093c0c88e3d773ecbb855df44',
        modelType: 'PSDEGRID',
        name: 'grid1',
        id: 'web.master.grid_base2',
      },
      {
        aggMode: 'NONE',
        columnEnableFilter: 2,
        columnEnableLink: 2,
        groupMode: 'NONE',
        groupStyle: 'DEFAULT',
        degridColumns: [
          {
            degridColumns: [
              {
                clconvertMode: 'NONE',
                dataItemName: 'name',
                excelCaption: '名称',
                appDEFieldId: 'name',
                valueType: 'SIMPLE',
                enableCond: 3,
                allowEmpty: true,
                aggMode: 'NONE',
                align: 'LEFT',
                capLanguageRes: {
                  lanResTag: 'DEF.LNAME.MASTER.NAME',
                },
                caption: '名称',
                codeName: 'name',
                columnType: 'DEFGRIDCOLUMN',
                noPrivDisplayMode: 1,
                width: 150,
                widthUnit: 'PX',
                enableSort: true,
                id: 'name',
              },
              {
                clconvertMode: 'NONE',
                dataItemName: 'date',
                excelCaption: '日期',
                appDEFieldId: 'date',
                valueFormat: 'YYYY-MM-DD',
                valueType: 'SIMPLE',
                enableCond: 3,
                allowEmpty: true,
                aggMode: 'NONE',
                align: 'LEFT',
                caption: '日期',
                codeName: 'date',
                columnType: 'DEFGRIDCOLUMN',
                noPrivDisplayMode: 1,
                width: 100,
                widthUnit: 'PX',
                enableSort: true,
                id: 'date',
              },
              {
                clconvertMode: 'NONE',
                dataItemName: 'quantity',
                excelCaption: '数量',
                appDEFieldId: 'quantity',
                valueType: 'SIMPLE',
                enableCond: 3,
                allowEmpty: true,
                aggMode: 'NONE',
                align: 'LEFT',
                caption: '数量',
                codeName: 'quantity',
                columnType: 'DEFGRIDCOLUMN',
                noPrivDisplayMode: 1,
                width: 100,
                widthUnit: 'PX',
                enableSort: true,
                id: 'quantity',
              },
              {
                clconvertMode: 'FRONT',
                dataItemName: 'type',
                excelCaption: '类型',
                appCodeListId: 'web.mock__cl_categories',
                appDEFieldId: 'type',
                valueType: 'SIMPLE',
                enableCond: 3,
                allowEmpty: true,
                aggMode: 'NONE',
                align: 'LEFT',
                caption: '类型',
                codeName: 'type',
                columnType: 'DEFGRIDCOLUMN',
                noPrivDisplayMode: 1,
                width: 100,
                widthUnit: 'PX',
                enableSort: true,
                id: 'type',
              },
              {
                clconvertMode: 'NONE',
                dataItemName: 'description',
                excelCaption: '描述',
                appDEFieldId: 'description',
                valueType: 'SIMPLE',
                enableCond: 3,
                allowEmpty: true,
                aggMode: 'NONE',
                align: 'LEFT',
                caption: '描述',
                codeName: 'description',
                columnType: 'DEFGRIDCOLUMN',
                noPrivDisplayMode: 1,
                width: 100,
                widthUnit: 'PX',
                enableSort: true,
                id: 'description',
              },
            ],
            aggMode: 'NONE',
            caption: '基本信息',
            codeName: 'groupgridcolumn1',
            columnType: 'GROUPGRIDCOLUMN',
            noPrivDisplayMode: 1,
            width: 100,
            widthUnit: 'PX',
            id: 'groupgridcolumn1',
          },
          {
            degridColumns: [
              {
                degridColumns: [
                  {
                    clconvertMode: 'NONE',
                    dataItemName: 'create_time',
                    excelCaption: '创建时间',
                    appDEFieldId: 'create_time',
                    valueFormat: 'YYYY-MM-DD HH:mm:ss',
                    valueType: 'SIMPLE',
                    enableCond: 3,
                    allowEmpty: true,
                    aggMode: 'NONE',
                    align: 'LEFT',
                    capLanguageRes: {
                      lanResTag: 'DEF.LNAME.MASTER.CREATE_TIME',
                    },
                    caption: '创建时间',
                    codeName: 'create_time',
                    columnType: 'DEFGRIDCOLUMN',
                    noPrivDisplayMode: 1,
                    width: 100,
                    widthUnit: 'PX',
                    enableSort: true,
                    id: 'create_time',
                  },
                ],
                aggMode: 'NONE',
                caption: '创建信息',
                codeName: 'groupgridcolumn3',
                columnType: 'GROUPGRIDCOLUMN',
                noPrivDisplayMode: 1,
                width: 100,
                widthUnit: 'PX',
                id: 'groupgridcolumn3',
              },
              {
                degridColumns: [
                  {
                    clconvertMode: 'NONE',
                    dataItemName: 'update_time',
                    excelCaption: '更新时间',
                    appDEFieldId: 'update_time',
                    valueFormat: 'YYYY-MM-DD HH:mm:ss',
                    valueType: 'SIMPLE',
                    enableCond: 3,
                    allowEmpty: true,
                    aggMode: 'NONE',
                    align: 'LEFT',
                    capLanguageRes: {
                      lanResTag: 'DEF.LNAME.UPDATE_TIME',
                    },
                    caption: '更新时间',
                    codeName: 'update_time',
                    columnType: 'DEFGRIDCOLUMN',
                    noPrivDisplayMode: 1,
                    width: 100,
                    widthUnit: 'PX',
                    enableSort: true,
                    id: 'update_time',
                  },
                ],
                aggMode: 'NONE',
                caption: '更新信息',
                codeName: 'groupgridcolumn4',
                columnType: 'GROUPGRIDCOLUMN',
                noPrivDisplayMode: 1,
                width: 100,
                widthUnit: 'PX',
                id: 'groupgridcolumn4',
              },
            ],
            aggMode: 'NONE',
            caption: '操作信息',
            codeName: 'groupgridcolumn2',
            columnType: 'GROUPGRIDCOLUMN',
            noPrivDisplayMode: 1,
            width: 100,
            widthUnit: 'PX',
            id: 'groupgridcolumn2',
          },
        ],
        degridDataItems: [
          {
            appDEFieldId: 'name',
            valueType: 'SIMPLE',
            dataType: 25,
            id: 'name',
          },
          {
            format: 'YYYY-MM-DD',
            appDEFieldId: 'date',
            valueType: 'SIMPLE',
            dataType: 5,
            id: 'date',
          },
          {
            appDEFieldId: 'quantity',
            valueType: 'SIMPLE',
            dataType: 6,
            id: 'quantity',
          },
          {
            appDEFieldId: 'type',
            valueType: 'SIMPLE',
            dataType: 25,
            id: 'type',
          },
          {
            appDEFieldId: 'description',
            valueType: 'SIMPLE',
            dataType: 25,
            id: 'description',
          },
          {
            format: 'YYYY-MM-DD HH:mm:ss',
            appDEFieldId: 'create_time',
            valueType: 'SIMPLE',
            dataType: 5,
            id: 'create_time',
          },
          {
            format: 'YYYY-MM-DD HH:mm:ss',
            appDEFieldId: 'update_time',
            valueType: 'SIMPLE',
            dataType: 5,
            id: 'update_time',
          },
          {
            appDEFieldId: 'id',
            valueType: 'SIMPLE',
            dataType: 25,
            id: 'srfkey',
          },
          {
            appDEFieldId: 'id',
            valueType: 'SIMPLE',
            dataType: 25,
            id: 'srfdataaccaction',
          },
          {
            appDEFieldId: 'region_id',
            valueType: 'SIMPLE',
            dataType: 25,
            id: 'region_id',
          },
          {
            appDEFieldId: 'name',
            valueType: 'SIMPLE',
            dataType: 25,
            id: 'srfmajortext',
          },
        ],
        degridEditItems: [
          {
            caption: '标识',
            codeName: 'srfkey',
            enableCond: 3,
            appDEFieldId: 'id',
            editor: {
              editorType: 'HIDDEN',
              valueType: 'SIMPLE',
              editable: true,
              id: 'srfkey',
            },
            allowEmpty: true,
            id: 'srfkey',
          },
        ],
        pagingMode: 1,
        pagingSize: 10,
        sortMode: 'REMOTE',
        enableCustomized: true,
        enablePagingBar: true,
        navViewPos: 'NONE',
        fetchControlAction: {
          appDEMethodId: 'fetch_default',
          appDataEntityId: 'web.master',
          id: 'fetch',
        },
        removeControlAction: {
          appDEMethodId: 'remove',
          appDataEntityId: 'web.master',
          id: 'remove',
        },
        autoLoad: true,
        showBusyIndicator: true,
        codeName: 'grid_base4',
        controlType: 'GRID',
        logicName: '表格_基础_表头分组',
        appDataEntityId: 'web.master',
        controlParam: {
          id: 'grid3',
        },
        modelId: '6a8bf202b4f6007e162e2516f860e6e9',
        modelType: 'PSDEGRID',
        name: 'grid3',
        id: 'web.master.grid_base4',
      },
      {
        aggMode: 'NONE',
        columnEnableFilter: 2,
        columnEnableLink: 2,
        groupMode: 'NONE',
        groupStyle: 'DEFAULT',
        degridColumns: [
          {
            clconvertMode: 'NONE',
            dataItemName: 'name',
            excelCaption: '名称',
            appDEFieldId: 'name',
            valueType: 'SIMPLE',
            aggMode: 'NONE',
            align: 'LEFT',
            capLanguageRes: {
              lanResTag: 'DEF.LNAME.MASTER.NAME',
            },
            caption: '名称',
            codeName: 'name',
            columnType: 'DEFGRIDCOLUMN',
            noPrivDisplayMode: 1,
            width: 150,
            widthUnit: 'PX',
            enableSort: true,
            id: 'name',
          },
        ],
        degridDataItems: [
          {
            appDEFieldId: 'name',
            valueType: 'SIMPLE',
            dataType: 25,
            id: 'name',
          },
          {
            appDEFieldId: 'id',
            valueType: 'SIMPLE',
            dataType: 25,
            id: 'srfkey',
          },
          {
            appDEFieldId: 'id',
            valueType: 'SIMPLE',
            dataType: 25,
            id: 'srfdataaccaction',
          },
          {
            appDEFieldId: 'region_id',
            valueType: 'SIMPLE',
            dataType: 25,
            id: 'region_id',
          },
          {
            appDEFieldId: 'name',
            valueType: 'SIMPLE',
            dataType: 25,
            id: 'srfmajortext',
          },
        ],
        degridEditItems: [
          {
            caption: '标识',
            codeName: 'srfkey',
            enableCond: 3,
            appDEFieldId: 'id',
            editor: {
              editorType: 'HIDDEN',
              valueType: 'SIMPLE',
              editable: true,
              id: 'srfkey',
            },
            allowEmpty: true,
            id: 'srfkey',
          },
        ],
        pagingMode: 1,
        pagingSize: 10,
        sortMode: 'REMOTE',
        enableCustomized: true,
        enablePagingBar: true,
        navViewPos: 'NONE',
        fetchControlAction: {
          appDEMethodId: 'fetch_default',
          appDataEntityId: 'web.master',
          id: 'fetch',
        },
        removeControlAction: {
          appDEMethodId: 'remove',
          appDataEntityId: 'web.master',
          id: 'remove',
        },
        autoLoad: true,
        showBusyIndicator: true,
        codeName: 'grid_base5',
        controlType: 'GRID',
        logicName: '表格_基础_支持分页',
        appDataEntityId: 'web.master',
        controlParam: {
          id: 'grid4',
        },
        modelId: 'a68b533d660dfdf08d3e1fbfbe8081a6',
        modelType: 'PSDEGRID',
        name: 'grid4',
        id: 'web.master.grid_base5',
      },
      {
        aggMode: 'NONE',
        columnEnableFilter: 2,
        columnEnableLink: 2,
        groupMode: 'NONE',
        groupStyle: 'DEFAULT',
        degridColumns: [
          {
            clconvertMode: 'NONE',
            dataItemName: 'name',
            excelCaption: '名称',
            appDEFieldId: 'name',
            valueType: 'SIMPLE',
            aggMode: 'NONE',
            align: 'LEFT',
            capLanguageRes: {
              lanResTag: 'DEF.LNAME.MASTER.NAME',
            },
            caption: '名称',
            codeName: 'name',
            columnType: 'DEFGRIDCOLUMN',
            noPrivDisplayMode: 1,
            width: 150,
            widthUnit: 'PX',
            enableSort: true,
            id: 'name',
          },
        ],
        degridDataItems: [
          {
            appDEFieldId: 'name',
            valueType: 'SIMPLE',
            dataType: 25,
            id: 'name',
          },
          {
            appDEFieldId: 'id',
            valueType: 'SIMPLE',
            dataType: 25,
            id: 'srfkey',
          },
          {
            appDEFieldId: 'id',
            valueType: 'SIMPLE',
            dataType: 25,
            id: 'srfdataaccaction',
          },
          {
            appDEFieldId: 'region_id',
            valueType: 'SIMPLE',
            dataType: 25,
            id: 'region_id',
          },
          {
            appDEFieldId: 'name',
            valueType: 'SIMPLE',
            dataType: 25,
            id: 'srfmajortext',
          },
        ],
        degridEditItems: [
          {
            caption: '标识',
            codeName: 'srfkey',
            enableCond: 3,
            appDEFieldId: 'id',
            editor: {
              editorType: 'HIDDEN',
              valueType: 'SIMPLE',
              editable: true,
              id: 'srfkey',
            },
            allowEmpty: true,
            id: 'srfkey',
          },
        ],
        pagingSize: 10,
        sortMode: 'REMOTE',
        enableCustomized: true,
        navViewPos: 'NONE',
        fetchControlAction: {
          appDEMethodId: 'fetch_default',
          appDataEntityId: 'web.master',
          id: 'fetch',
        },
        removeControlAction: {
          appDEMethodId: 'remove',
          appDataEntityId: 'web.master',
          id: 'remove',
        },
        autoLoad: true,
        showBusyIndicator: true,
        codeName: 'grid_base6',
        controlType: 'GRID',
        logicName: '表格_基础_不支持分页',
        appDataEntityId: 'web.master',
        controlParam: {
          id: 'grid5',
        },
        modelId: 'f83e79d2fdcb86d329bfbdfed278a5ed',
        modelType: 'PSDEGRID',
        name: 'grid5',
        id: 'web.master.grid_base6',
      },
      {
        aggMode: 'NONE',
        columnEnableFilter: 2,
        columnEnableLink: 2,
        groupMode: 'NONE',
        groupStyle: 'DEFAULT',
        degridColumns: [
          {
            clconvertMode: 'NONE',
            dataItemName: 'name',
            excelCaption: '名称',
            appDEFieldId: 'name',
            valueType: 'SIMPLE',
            aggMode: 'NONE',
            align: 'LEFT',
            capLanguageRes: {
              lanResTag: 'DEF.LNAME.MASTER.NAME',
            },
            caption: '名称',
            codeName: 'name',
            columnType: 'DEFGRIDCOLUMN',
            noPrivDisplayMode: 1,
            width: 150,
            widthUnit: 'PX',
            enableSort: true,
            id: 'name',
          },
        ],
        degridDataItems: [
          {
            appDEFieldId: 'name',
            valueType: 'SIMPLE',
            dataType: 25,
            id: 'name',
          },
          {
            appDEFieldId: 'id',
            valueType: 'SIMPLE',
            dataType: 25,
            id: 'srfkey',
          },
          {
            appDEFieldId: 'id',
            valueType: 'SIMPLE',
            dataType: 25,
            id: 'srfdataaccaction',
          },
          {
            appDEFieldId: 'region_id',
            valueType: 'SIMPLE',
            dataType: 25,
            id: 'region_id',
          },
          {
            appDEFieldId: 'name',
            valueType: 'SIMPLE',
            dataType: 25,
            id: 'srfmajortext',
          },
        ],
        degridEditItems: [
          {
            caption: '标识',
            codeName: 'srfkey',
            enableCond: 3,
            appDEFieldId: 'id',
            editor: {
              editorType: 'HIDDEN',
              valueType: 'SIMPLE',
              editable: true,
              id: 'srfkey',
            },
            allowEmpty: true,
            id: 'srfkey',
          },
        ],
        pagingMode: 1,
        pagingSize: 10,
        sortMode: 'REMOTE',
        enableCustomized: true,
        enablePagingBar: true,
        hideHeader: true,
        navViewPos: 'NONE',
        fetchControlAction: {
          appDEMethodId: 'fetch_default',
          appDataEntityId: 'web.master',
          id: 'fetch',
        },
        removeControlAction: {
          appDEMethodId: 'remove',
          appDataEntityId: 'web.master',
          id: 'remove',
        },
        autoLoad: true,
        showBusyIndicator: true,
        codeName: 'grid_base3',
        controlType: 'GRID',
        logicName: '表格_基础_不显示表头',
        appDataEntityId: 'web.master',
        controlParam: {
          id: 'grid2',
        },
        modelId: '0715a1b5273bf5f4fec7e6cb54e039c7',
        modelType: 'PSDEGRID',
        name: 'grid2',
        id: 'web.master.grid_base3',
      },
      {
        aggMode: 'NONE',
        columnEnableFilter: 2,
        columnEnableLink: 2,
        groupMode: 'NONE',
        groupStyle: 'DEFAULT',
        degridColumns: [
          {
            clconvertMode: 'NONE',
            dataItemName: 'name',
            excelCaption: '名称',
            appDEFieldId: 'name',
            valueType: 'SIMPLE',
            aggMode: 'NONE',
            align: 'LEFT',
            capLanguageRes: {
              lanResTag: 'DEF.LNAME.MASTER.NAME',
            },
            caption: '名称',
            codeName: 'name',
            columnType: 'DEFGRIDCOLUMN',
            noPrivDisplayMode: 1,
            width: 150,
            widthUnit: 'PX',
            enableSort: true,
            id: 'name',
          },
          {
            clconvertMode: 'NONE',
            dataItemName: 'quantity',
            excelCaption: '数量',
            appDEFieldId: 'quantity',
            valueType: 'SIMPLE',
            aggMode: 'NONE',
            align: 'LEFT',
            caption: '数量',
            codeName: 'quantity',
            columnType: 'DEFGRIDCOLUMN',
            noPrivDisplayMode: 1,
            width: 150,
            widthUnit: 'PX',
            enableSort: true,
            id: 'quantity',
          },
          {
            clconvertMode: 'NONE',
            dataItemName: 'date',
            excelCaption: '日期',
            appDEFieldId: 'date',
            valueFormat: 'YYYY-MM-DD',
            valueType: 'SIMPLE',
            aggMode: 'NONE',
            align: 'LEFT',
            caption: '日期',
            codeName: 'date',
            columnType: 'DEFGRIDCOLUMN',
            noPrivDisplayMode: 1,
            width: 150,
            widthUnit: 'PX',
            enableSort: true,
            id: 'date',
          },
          {
            clconvertMode: 'FRONT',
            dataItemName: 'status',
            excelCaption: '状态',
            appCodeListId: 'web.mock__cl_status',
            appDEFieldId: 'status',
            valueType: 'SIMPLE',
            aggMode: 'NONE',
            align: 'LEFT',
            caption: '状态',
            codeName: 'status',
            columnType: 'DEFGRIDCOLUMN',
            noPrivDisplayMode: 1,
            width: 150,
            widthUnit: 'PX',
            enableSort: true,
            id: 'status',
          },
        ],
        degridDataItems: [
          {
            appDEFieldId: 'name',
            valueType: 'SIMPLE',
            dataType: 25,
            id: 'name',
          },
          {
            appDEFieldId: 'quantity',
            valueType: 'SIMPLE',
            dataType: 6,
            id: 'quantity',
          },
          {
            format: 'YYYY-MM-DD',
            appDEFieldId: 'date',
            valueType: 'SIMPLE',
            dataType: 5,
            id: 'date',
          },
          {
            appDEFieldId: 'status',
            valueType: 'SIMPLE',
            dataType: 9,
            id: 'status',
          },
          {
            appDEFieldId: 'id',
            valueType: 'SIMPLE',
            dataType: 25,
            id: 'srfkey',
          },
          {
            appDEFieldId: 'id',
            valueType: 'SIMPLE',
            dataType: 25,
            id: 'srfdataaccaction',
          },
          {
            appDEFieldId: 'region_id',
            valueType: 'SIMPLE',
            dataType: 25,
            id: 'region_id',
          },
          {
            appDEFieldId: 'name',
            valueType: 'SIMPLE',
            dataType: 25,
            id: 'srfmajortext',
          },
        ],
        degridEditItems: [
          {
            caption: '标识',
            codeName: 'srfkey',
            enableCond: 3,
            appDEFieldId: 'id',
            editor: {
              editorType: 'HIDDEN',
              valueType: 'SIMPLE',
              editable: true,
              id: 'srfkey',
            },
            allowEmpty: true,
            id: 'srfkey',
          },
        ],
        pagingMode: 1,
        pagingSize: 10,
        sortMode: 'REMOTE',
        enableCustomized: true,
        enablePagingBar: true,
        navViewPos: 'NONE',
        fetchControlAction: {
          appDEMethodId: 'fetch_default',
          appDataEntityId: 'web.master',
          id: 'fetch',
        },
        removeControlAction: {
          appDEMethodId: 'remove',
          appDataEntityId: 'web.master',
          id: 'remove',
        },
        autoLoad: true,
        showBusyIndicator: true,
        codeName: 'grid_base17',
        controlType: 'GRID',
        logicName: '表格_基础_适应屏宽',
        appDataEntityId: 'web.master',
        controlParam: {
          id: 'grid6',
        },
        modelId: 'db17be41a76429d2b5a25db2dbd9d0e5',
        modelType: 'PSDEGRID',
        name: 'grid6',
        id: 'web.master.grid_base17',
      },
      {
        aggMode: 'NONE',
        columnEnableFilter: 2,
        columnEnableLink: 2,
        frozenLastColumn: 1,
        gridStyle: 'TREEGRID',
        groupMode: 'NONE',
        groupStyle: 'DEFAULT',
        minorSortDir: 'ASC',
        minorSortAppDEFieldId: 'sort',
        degridColumns: [
          {
            clconvertMode: 'NONE',
            dataItemName: 'code',
            excelCaption: '编码',
            appDEFieldId: 'code',
            valueType: 'SIMPLE',
            aggMode: 'NONE',
            align: 'LEFT',
            caption: '编码',
            codeName: 'code',
            columnType: 'DEFGRIDCOLUMN',
            noPrivDisplayMode: 1,
            width: 150,
            widthUnit: 'PX',
            enableSort: true,
            id: 'code',
          },
          {
            clconvertMode: 'NONE',
            dataItemName: 'name',
            excelCaption: '名称',
            appDEFieldId: 'name',
            treeColumnMode: 1,
            valueType: 'SIMPLE',
            enableRowEdit: true,
            aggMode: 'NONE',
            align: 'LEFT',
            capLanguageRes: {
              lanResTag: 'DEF.LNAME.REGION.NAME',
            },
            caption: '名称',
            codeName: 'name',
            columnType: 'DEFGRIDCOLUMN',
            noPrivDisplayMode: 1,
            width: 200,
            widthUnit: 'PX',
            enableSort: true,
            id: 'name',
          },
          {
            clconvertMode: 'NONE',
            dataItemName: 'parent_name',
            excelCaption: '上级区划',
            linkAppViewId: 'web.region_redirect_view',
            linkValueItem: 'parent_id',
            appDEFieldId: 'parent_name',
            treeColumnMode: 8,
            valueType: 'SIMPLE',
            enableLinkView: true,
            enableRowEdit: true,
            aggMode: 'NONE',
            align: 'LEFT',
            caption: '上级区划',
            codeName: 'parent_name',
            columnType: 'DEFGRIDCOLUMN',
            noPrivDisplayMode: 1,
            width: 200,
            widthUnit: 'PX',
            enableSort: true,
            id: 'parent_name',
          },
          {
            clconvertMode: 'NONE',
            dataItemName: 'level',
            excelCaption: '级别',
            appDEFieldId: 'level',
            valueType: 'SIMPLE',
            enableRowEdit: true,
            aggMode: 'NONE',
            align: 'LEFT',
            caption: '级别',
            codeName: 'level',
            columnType: 'DEFGRIDCOLUMN',
            noPrivDisplayMode: 1,
            width: 100,
            widthUnit: 'PX',
            enableSort: true,
            id: 'level',
          },
          {
            clconvertMode: 'FRONT',
            dataItemName: 'status',
            excelCaption: '状态',
            appCodeListId: 'web.mock__cl_status',
            appDEFieldId: 'status',
            valueType: 'SIMPLE',
            enableRowEdit: true,
            aggMode: 'NONE',
            align: 'LEFT',
            caption: '状态',
            codeName: 'status',
            columnType: 'DEFGRIDCOLUMN',
            noPrivDisplayMode: 1,
            width: 150,
            widthUnit: 'PX',
            enableSort: true,
            id: 'status',
          },
          {
            clconvertMode: 'NONE',
            dataItemName: 'path',
            excelCaption: '全路径',
            appDEFieldId: 'path',
            valueType: 'SIMPLE',
            enableRowEdit: true,
            aggMode: 'NONE',
            align: 'LEFT',
            caption: '全路径',
            codeName: 'path',
            columnType: 'DEFGRIDCOLUMN',
            noPrivDisplayMode: 1,
            width: 500,
            widthUnit: 'STAR',
            enableSort: true,
            id: 'path',
          },
          {
            clconvertMode: 'NONE',
            dataItemName: 'sort',
            excelCaption: '排序',
            appDEFieldId: 'sort',
            valueType: 'SIMPLE',
            enableRowEdit: true,
            aggMode: 'NONE',
            align: 'LEFT',
            caption: '排序',
            codeName: 'sort',
            columnType: 'DEFGRIDCOLUMN',
            noPrivDisplayMode: 1,
            width: 100,
            widthUnit: 'PX',
            enableSort: true,
            id: 'sort',
          },
          {
            clconvertMode: 'NONE',
            dataItemName: 'longitude',
            excelCaption: '经度',
            appDEFieldId: 'longitude',
            valueType: 'SIMPLE',
            enableRowEdit: true,
            aggMode: 'NONE',
            align: 'LEFT',
            caption: '经度',
            codeName: 'longitude',
            columnType: 'DEFGRIDCOLUMN',
            noPrivDisplayMode: 1,
            width: 100,
            widthUnit: 'PX',
            enableSort: true,
            id: 'longitude',
          },
          {
            clconvertMode: 'NONE',
            dataItemName: 'latitude',
            excelCaption: '纬度',
            appDEFieldId: 'latitude',
            valueType: 'SIMPLE',
            enableRowEdit: true,
            aggMode: 'NONE',
            align: 'LEFT',
            caption: '纬度',
            codeName: 'latitude',
            columnType: 'DEFGRIDCOLUMN',
            noPrivDisplayMode: 1,
            width: 100,
            widthUnit: 'PX',
            enableSort: true,
            id: 'latitude',
          },
          {
            clconvertMode: 'NONE',
            dataItemName: 'update_time',
            excelCaption: '更新时间',
            appDEFieldId: 'update_time',
            valueFormat: 'YYYY-MM-DD HH:mm:ss',
            valueType: 'SIMPLE',
            aggMode: 'NONE',
            align: 'LEFT',
            capLanguageRes: {
              lanResTag: 'DEF.LNAME.UPDATE_TIME',
            },
            caption: '更新时间',
            codeName: 'update_time',
            columnType: 'DEFGRIDCOLUMN',
            noPrivDisplayMode: 1,
            width: 200,
            widthUnit: 'PX',
            enableSort: true,
            id: 'update_time',
          },
          {
            clconvertMode: 'NONE',
            dataItemName: 'create_time',
            excelCaption: '创建时间',
            appDEFieldId: 'create_time',
            valueFormat: 'YYYY-MM-DD HH:mm:ss',
            valueType: 'SIMPLE',
            aggMode: 'NONE',
            align: 'LEFT',
            capLanguageRes: {
              lanResTag: 'DEF.LNAME.REGION.CREATE_TIME',
            },
            caption: '创建时间',
            codeName: 'create_time',
            columnType: 'DEFGRIDCOLUMN',
            noPrivDisplayMode: 1,
            width: 200,
            widthUnit: 'PX',
            enableSort: true,
            id: 'create_time',
          },
          {
            deuiactionGroup: {
              uiactionGroupDetails: [
                {
                  actionLevel: 100,
                  afterItemType: 'NONE',
                  beforeItemType: 'NONE',
                  buttonStyle: 'DEFAULT',
                  caption: '查看',
                  detailType: 'DEUIACTION',
                  uiactionId: 'view@region',
                  showCaption: true,
                  showIcon: true,
                  sysImage: {
                    cssClass: 'fa fa-file-text',
                    glyph: 'xf15c@FontAwesome',
                  },
                  id: 'u988f5c7',
                },
                {
                  actionLevel: 100,
                  afterItemType: 'NONE',
                  beforeItemType: 'NONE',
                  buttonStyle: 'DEFAULT',
                  caption: '编辑',
                  detailType: 'DEUIACTION',
                  uiactionId: 'edit@region',
                  showCaption: true,
                  showIcon: true,
                  sysImage: {
                    cssClass: 'fa fa-edit',
                    glyph: 'xf044@FontAwesome',
                  },
                  id: 'ubfba42f',
                },
                {
                  actionLevel: 100,
                  afterItemType: 'NONE',
                  beforeItemType: 'NONE',
                  buttonStyle: 'DEFAULT',
                  caption: '删除',
                  detailType: 'DEUIACTION',
                  uiactionId: 'remove@region',
                  showCaption: true,
                  showIcon: true,
                  sysImage: {
                    cssClass: 'fa fa-trash',
                    glyph: 'xf1f8@FontAwesome',
                  },
                  id: 'u662706e',
                },
              ],
              appDataEntityId: 'web.region',
              uniqueTag: 'region__Aa191c5fc4defabcf44',
              name: '表格操作列',
              id: 'aa191c5fc4defabcf44',
            },
            aggMode: 'NONE',
            align: 'CENTER',
            caption: '操作',
            codeName: 'uagridcolumn1',
            columnType: 'UAGRIDCOLUMN',
            noPrivDisplayMode: 1,
            width: 200,
            widthUnit: 'PX',
            id: 'uagridcolumn1',
          },
        ],
        degridDataItems: [
          {
            appDEFieldId: 'code',
            valueType: 'SIMPLE',
            dataType: 25,
            id: 'code',
          },
          {
            appDEFieldId: 'name',
            valueType: 'SIMPLE',
            dataType: 25,
            id: 'name',
          },
          {
            appDEFieldId: 'parent_name',
            valueType: 'SIMPLE',
            dataType: 25,
            id: 'parent_name',
          },
          {
            appDEFieldId: 'level',
            valueType: 'SIMPLE',
            dataType: 9,
            id: 'level',
          },
          {
            appDEFieldId: 'status',
            valueType: 'SIMPLE',
            dataType: 9,
            id: 'status',
          },
          {
            appDEFieldId: 'path',
            valueType: 'SIMPLE',
            dataType: 25,
            id: 'path',
          },
          {
            appDEFieldId: 'sort',
            valueType: 'SIMPLE',
            dataType: 9,
            id: 'sort',
          },
          {
            appDEFieldId: 'longitude',
            valueType: 'SIMPLE',
            dataType: 29,
            id: 'longitude',
          },
          {
            appDEFieldId: 'latitude',
            valueType: 'SIMPLE',
            dataType: 29,
            id: 'latitude',
          },
          {
            format: 'YYYY-MM-DD HH:mm:ss',
            appDEFieldId: 'update_time',
            valueType: 'SIMPLE',
            dataType: 5,
            id: 'update_time',
          },
          {
            format: 'YYYY-MM-DD HH:mm:ss',
            appDEFieldId: 'create_time',
            valueType: 'SIMPLE',
            dataType: 5,
            id: 'create_time',
          },
          {
            appDEFieldId: 'id',
            valueType: 'SIMPLE',
            dataType: 25,
            id: 'id',
          },
          {
            appDEFieldId: 'parent_id',
            valueType: 'SIMPLE',
            dataType: 25,
            id: 'parent_id',
          },
          {
            appDEFieldId: 'id',
            valueType: 'SIMPLE',
            dataType: 25,
            id: 'srfkey',
          },
          {
            appDEFieldId: 'id',
            valueType: 'SIMPLE',
            dataType: 25,
            id: 'srfdataaccaction',
          },
          {
            appDEFieldId: 'name',
            valueType: 'SIMPLE',
            dataType: 25,
            id: 'srfmajortext',
          },
        ],
        degridEditItems: [
          {
            caption: '名称',
            codeName: 'name',
            enableCond: 3,
            appDEFieldId: 'name',
            editor: {
              maxLength: 200,
              editorType: 'TEXTBOX',
              valueType: 'SIMPLE',
              editable: true,
              id: 'name',
            },
            allowEmpty: true,
            id: 'name',
          },
          {
            caption: '上级区划',
            codeName: 'parent_name',
            enableCond: 3,
            appDEFieldId: 'parent_name',
            editor: {
              enablePickupView: true,
              singleSelect: true,
              pickupAppViewId: 'web.region_pickup_view',
              handlerType: 'PickupText',
              appDEACModeId: 'default',
              appDEDataSetId: 'fetch_default',
              appDataEntityId: 'web.region',
              enableAC: true,
              forceSelection: true,
              showTrigger: true,
              valueItemName: 'parent_id',
              editorParams: {
                AC: 'TRUE',
                PICKUPVIEW: 'TRUE',
              },
              editorType: 'PICKER',
              editorItems: [{}],
              valueType: 'SIMPLE',
              editable: true,
              id: 'parent_name',
            },
            allowEmpty: true,
            id: 'parent_name',
          },
          {
            caption: '级别',
            codeName: 'level',
            enableCond: 3,
            appDEFieldId: 'level',
            editor: {
              editorType: 'TEXTBOX',
              valueType: 'SIMPLE',
              editable: true,
              id: 'level',
            },
            allowEmpty: true,
            id: 'level',
          },
          {
            caption: '状态',
            codeName: 'status',
            enableCond: 3,
            appDEFieldId: 'status',
            editor: {
              singleSelect: true,
              appCodeListId: 'web.mock__cl_status',
              editorType: 'DROPDOWNLIST',
              valueType: 'SIMPLE',
              editable: true,
              id: 'status',
            },
            allowEmpty: true,
            needCodeListConfig: true,
            id: 'status',
          },
          {
            caption: '全路径',
            codeName: 'path',
            enableCond: 3,
            appDEFieldId: 'path',
            editor: {
              maxLength: 500,
              editorType: 'TEXTBOX',
              valueType: 'SIMPLE',
              editable: true,
              id: 'path',
            },
            allowEmpty: true,
            id: 'path',
          },
          {
            caption: '排序',
            codeName: 'sort',
            enableCond: 3,
            appDEFieldId: 'sort',
            editor: {
              editorType: 'TEXTBOX',
              valueType: 'SIMPLE',
              editable: true,
              id: 'sort',
            },
            allowEmpty: true,
            id: 'sort',
          },
          {
            caption: '经度',
            codeName: 'longitude',
            enableCond: 3,
            appDEFieldId: 'longitude',
            editor: {
              editorType: 'TEXTBOX',
              valueType: 'SIMPLE',
              editable: true,
              id: 'longitude',
            },
            allowEmpty: true,
            id: 'longitude',
          },
          {
            caption: '纬度',
            codeName: 'latitude',
            enableCond: 3,
            appDEFieldId: 'latitude',
            editor: {
              editorType: 'TEXTBOX',
              valueType: 'SIMPLE',
              editable: true,
              id: 'latitude',
            },
            allowEmpty: true,
            id: 'latitude',
          },
          {
            caption: '标识',
            codeName: 'srfkey',
            enableCond: 3,
            appDEFieldId: 'id',
            editor: {
              editorType: 'HIDDEN',
              valueType: 'SIMPLE',
              editable: true,
              id: 'srfkey',
            },
            allowEmpty: true,
            id: 'srfkey',
          },
          {
            enableCond: 3,
            appDEFieldId: 'parent_id',
            editor: {
              editorType: 'HIDDEN',
              valueType: 'SIMPLE',
              editable: true,
            },
            allowEmpty: true,
            id: 'parent_id',
          },
        ],
        pagingMode: 1,
        pagingSize: 100,
        sortMode: 'REMOTE',
        enableCustomized: true,
        enablePagingBar: true,
        enableRowEdit: true,
        enableRowNew: true,
        navViewPos: 'NONE',
        createControlAction: {
          appDEMethodId: 'create',
          appDataEntityId: 'web.region',
          id: 'create',
        },
        fetchControlAction: {
          appDEMethodId: 'fetch_default',
          appDataEntityId: 'web.region',
          id: 'fetch',
        },
        getDraftControlAction: {
          appDEMethodId: 'get_draft',
          appDataEntityId: 'web.region',
          id: 'loaddraft',
        },
        getControlAction: {
          appDEMethodId: 'get',
          appDataEntityId: 'web.region',
          id: 'load',
        },
        removeControlAction: {
          appDEMethodId: 'remove',
          appDataEntityId: 'web.region',
          id: 'remove',
        },
        updateControlAction: {
          appDEMethodId: 'update',
          appDataEntityId: 'web.region',
          id: 'update',
        },
        autoLoad: true,
        showBusyIndicator: true,
        codeName: 'main',
        controlType: 'GRID',
        logicName: '主表格',
        appDataEntityId: 'web.region',
        controlParam: {
          id: 'grid7',
        },
        modelId: '714462b8e2e4d033523b2f10cf3ea4c9',
        modelType: 'PSDEGRID',
        name: 'grid7',
        id: 'web.region.main',
      },
      {
        capLanguageRes: {
          lanResTag: 'DE.LNAME.MASTER',
        },
        caption: '表格_基础',
        codeName: 'grid_base_captionbar',
        controlType: 'CAPTIONBAR',
        appDataEntityId: 'web.master',
        controlParam: {},
        name: 'captionbar',
        id: 'grid_base_captionbar',
      },
    ],
    codeName: 'usr0514280004',
    controlType: 'VIEWLAYOUTPANEL',
    logicName: '表格_基础布局面板',
    appDataEntityId: 'web.master',
    controlParam: {},
    modelId: '9a7ecf0a67a4a5f2f77f8f399ad758cd',
    modelType: 'PSSYSVIEWLAYOUTPANEL',
    name: 'layoutpanel',
    id: 'usr0514280004',
  },
  title: '表格_基础',
  viewStyle: 'DEFAULT',
  viewType: 'DECUSTOMVIEW',
  enableDP: true,
  showCaptionBar: false,
  modelId: 'a88ebfcf9bbbab3ed81a20a0a894fc99',
  modelType: 'PSAPPDEVIEW',
  name: 'MASTERgrid_base',
  id: 'web.master_grid_base',
};
