export default {
  deviewCodeName: 'treeview_navparams',
  deviewId: '0137b817af501b294f88e4f4eb32fb1c',
  accUserMode: 3,
  capLanguageRes: {
    lanResTag: 'DE.LNAME.MASTER',
  },
  caption: '树视图_导航传参',
  codeName: 'master_treeview_navparams',
  appDataEntityId: 'web.master',
  appViewMsgGroupId: 'treeview_navparams',
  viewLayoutPanel: {
    viewProxyMode: true,
    layoutMode: 'FLEX',
    layout: {
      layout: 'FLEX',
    },
    rootPanelItems: [
      {
        actionGroupExtractMode: 'ITEM',
        panelItems: [
          {
            actionGroupExtractMode: 'ITEM',
            panelItems: [
              {
                actionGroupExtractMode: 'ITEM',
                panelItems: [
                  {
                    caption: '树视图',
                    itemStyle: 'DEFAULT',
                    itemType: 'CTRLPOS',
                    layoutPos: {
                      shrink: 1,
                      layout: 'FLEX',
                    },
                    showCaption: true,
                    id: 'tree',
                  },
                ],
                predefinedType: 'CONTAINER_GROUP',
                layout: {
                  layout: 'FLEX',
                },
                dataRegionType: 'INHERIT',
                caption: '上下级节点传参',
                itemStyle: 'DEFAULT',
                itemType: 'CONTAINER',
                layoutPos: {
                  layoutPos: 'CENTER',
                  layout: 'BORDER',
                },
                showCaption: true,
                id: 'container_group',
              },
              {
                actionGroupExtractMode: 'ITEM',
                panelItems: [
                  {
                    caption: '树视图',
                    itemStyle: 'DEFAULT',
                    itemType: 'CTRLPOS',
                    layoutPos: {
                      shrink: 1,
                      layout: 'FLEX',
                    },
                    showCaption: true,
                    id: 'tree1',
                  },
                ],
                predefinedType: 'CONTAINER_GROUP',
                layout: {
                  layout: 'FLEX',
                },
                dataRegionType: 'INHERIT',
                caption: '节点视图传参',
                itemStyle: 'DEFAULT',
                itemType: 'CONTAINER',
                layoutPos: {
                  layoutPos: 'CENTER',
                  layout: 'BORDER',
                },
                showCaption: true,
                id: 'container_group1',
              },
            ],
            predefinedType: 'CONTAINER_SCROLL_MAIN',
            layout: {
              layout: 'BORDER',
            },
            dataRegionType: 'INHERIT',
            caption: '面板容器',
            itemStyle: 'DEFAULT',
            itemType: 'CONTAINER',
            layoutPos: {
              layoutPos: 'CENTER',
              layout: 'BORDER',
            },
            showCaption: true,
            id: 'container_scroll_main',
          },
        ],
        predefinedType: 'CONTAINER_SCROLL',
        layout: {
          layout: 'BORDER',
        },
        dataRegionType: 'INHERIT',
        caption: '滚动条容器',
        itemStyle: 'DEFAULT',
        itemType: 'CONTAINER',
        layoutPos: {
          shrink: 1,
          layout: 'FLEX',
        },
        id: 'container_scroll',
      },
    ],
    layoutPanel: true,
    controls: [
      {
        detreeNodeRSs: [
          {
            childDETreeNodeId: 'node',
            parentDETreeNodeId: 'root',
            parentValueLevel: 1,
            searchMode: 3,
            id: 'null - null',
          },
          {
            childDETreeNodeId: 'node_2',
            parentAppDEFieldId: 'parent_id',
            parentDER1N: {
              pickupDEFName: 'PARENT_ID',
              codeName: 'parent',
              dertype: 'DER1N',
              logicName: '上级区划',
              orderValue: 100,
              serviceCodeName: 'parent',
              name: 'DER1N_REGION_REGION_PARENT_ID',
              id: 'mock.region.der1n_region_region_parent_id',
            },
            parentDETreeNodeId: 'node_1',
            parentValueLevel: 1,
            searchMode: 3,
            id: 'null - null',
          },
          {
            childDETreeNodeId: 'node_1',
            parentDETreeNodeId: 'node',
            parentValueLevel: 1,
            searchMode: 3,
            id: 'null - null',
          },
          {
            childDETreeNodeId: 'node_2',
            parentAppDEFieldId: 'parent_id',
            parentDER1N: {
              pickupDEFName: 'PARENT_ID',
              codeName: 'parent',
              dertype: 'DER1N',
              logicName: '上级区划',
              orderValue: 100,
              serviceCodeName: 'parent',
              name: 'DER1N_REGION_REGION_PARENT_ID',
              id: 'mock.region.der1n_region_region_parent_id',
            },
            parentDETreeNodeId: 'node_2',
            parentValueLevel: 1,
            searchMode: 3,
            id: 'null - null',
          },
        ],
        detreeNodes: [
          {
            text: '默认根节点',
            nodeType: 'ROOT',
            treeNodeType: 'STATIC',
            hasDETreeNodeRSs: true,
            rootNode: true,
            name: '默认根节点',
            id: 'root',
          },
          {
            text: '区划',
            nodeType: 'node',
            treeNodeType: 'STATIC',
            hasDETreeNodeRSs: true,
            name: '区划',
            id: 'node',
          },
          {
            dataSourceType: 'DEDATASET',
            idAppDEFieldId: 'id',
            leafFlagAppDEFieldId: 'leaf',
            appDEDataSetId: 'fetch_root',
            textAppDEFieldId: 'name',
            nodeType: 'node_1',
            appDataEntityId: 'web.region',
            treeNodeType: 'DE',
            hasDETreeNodeRSs: true,
            name: '区划数据',
            id: 'node_1',
          },
          {
            childCntAppDEFieldId: 'leaf',
            dataSourceType: 'DEDATASET',
            idAppDEFieldId: 'id',
            appDEDataSetId: 'fetch_default',
            textAppDEFieldId: 'name',
            nodeType: 'node_2',
            appDataEntityId: 'web.region',
            treeNodeType: 'DE',
            hasDETreeNodeRSs: true,
            name: '区划子数据',
            id: 'node_2',
          },
        ],
        outputIconDefault: true,
        navViewPos: 'NONE',
        createControlAction: {
          appDEMethodId: 'create',
          appDataEntityId: 'web.master',
          id: 'create',
        },
        fetchControlAction: {
          appDataEntityId: 'web.master',
          id: 'fetch',
        },
        getControlAction: {
          appDEMethodId: 'get',
          appDataEntityId: 'web.master',
          id: 'load',
        },
        removeControlAction: {
          appDEMethodId: 'remove',
          appDataEntityId: 'web.master',
          id: 'remove',
        },
        updateControlAction: {
          appDEMethodId: 'update',
          appDataEntityId: 'web.master',
          id: 'update',
        },
        autoLoad: true,
        showBusyIndicator: true,
        codeName: 'tree_navparams1',
        controlType: 'TREEVIEW',
        logicName: '树视图_上下级节点传参',
        appDataEntityId: 'web.master',
        controlLogics: [
          {
            eventNames: 'onSelectionChange',
            logicTag: 'tree',
            logicType: 'SCRIPT',
            scriptCode:
              "console.log('测试树节点选择');\r\n\r\nif (Array.isArray(data) && data.length > 0) {\r\n    util.message.info(data[0].srfnodeid);\r\n}",
            triggerType: 'CTRLEVENT',
            id: 'logic',
          },
        ],
        controlParam: {
          id: 'tree',
        },
        modelId: '8f47766820acc0f6e5a7aa3721cdc9df',
        modelType: 'PSDETREEVIEW',
        name: 'tree',
        id: 'web.master.tree_navparams1',
      },
      {
        detreeNodeRSs: [
          {
            childDETreeNodeId: 'node_1',
            parentDETreeNodeId: 'root',
            parentValueLevel: 1,
            searchMode: 3,
            name: '默认根节点（ROOT）-区划数据（node_1）',
            id: '默认根节点（root）-区划数据（node_1）',
          },
          {
            childDETreeNodeId: 'node_2',
            parentAppDEFieldId: 'parent_id',
            parentDER1N: {
              pickupDEFName: 'PARENT_ID',
              codeName: 'parent',
              dertype: 'DER1N',
              logicName: '上级区划',
              orderValue: 100,
              serviceCodeName: 'parent',
              name: 'DER1N_REGION_REGION_PARENT_ID',
              id: 'mock.region.der1n_region_region_parent_id',
            },
            parentDETreeNodeId: 'node_2',
            parentValueLevel: 1,
            searchMode: 3,
            id: '区划子数据（node_2）-区划子数据（node_2）',
          },
          {
            childDETreeNodeId: 'node_2',
            parentAppDEFieldId: 'parent_id',
            parentDER1N: {
              pickupDEFName: 'PARENT_ID',
              codeName: 'parent',
              dertype: 'DER1N',
              logicName: '上级区划',
              orderValue: 100,
              serviceCodeName: 'parent',
              name: 'DER1N_REGION_REGION_PARENT_ID',
              id: 'mock.region.der1n_region_region_parent_id',
            },
            parentDETreeNodeId: 'node_1',
            parentValueLevel: 1,
            searchMode: 3,
            id: '区划数据（node_1）-区划子数据（node_2）',
          },
        ],
        detreeNodes: [
          {
            text: '默认根节点',
            nodeType: 'ROOT',
            treeNodeType: 'STATIC',
            hasDETreeNodeRSs: true,
            rootNode: true,
            name: '默认根节点',
            id: 'root',
          },
          {
            dataSourceType: 'DEDATASET',
            idAppDEFieldId: 'id',
            leafFlagAppDEFieldId: 'leaf',
            appDEDataSetId: 'fetch_root',
            textAppDEFieldId: 'name',
            navAppViewId: 'web.region_info_view',
            nodeType: 'node_1',
            appDataEntityId: 'web.region',
            navigateParams: [
              {
                key: 'name',
                value: 'name',
                id: 'name',
              },
              {
                key: 'parent_name',
                value: 'parent_name',
                id: 'parent_name',
              },
            ],
            treeNodeType: 'DE',
            hasDETreeNodeRSs: true,
            name: '区划数据',
            id: 'node_1',
          },
          {
            dataSourceType: 'DEDATASET',
            idAppDEFieldId: 'id',
            leafFlagAppDEFieldId: 'leaf',
            appDEDataSetId: 'fetch_child',
            textAppDEFieldId: 'name',
            navAppViewId: 'web.region_info_view',
            nodeType: 'node_2',
            appDataEntityId: 'web.region',
            navigateParams: [
              {
                key: 'name',
                value: 'name',
                id: 'name',
              },
              {
                key: 'parent_name',
                value: 'parent_name',
                id: 'parent_name',
              },
            ],
            treeNodeType: 'DE',
            hasDETreeNodeRSs: true,
            name: '区划子数据',
            id: 'node_2',
          },
        ],
        outputIconDefault: true,
        navViewPos: 'RIGHT',
        navViewWidth: 800,
        createControlAction: {
          appDEMethodId: 'create',
          appDataEntityId: 'web.master',
          id: 'create',
        },
        fetchControlAction: {
          appDataEntityId: 'web.master',
          id: 'fetch',
        },
        getControlAction: {
          appDEMethodId: 'get',
          appDataEntityId: 'web.master',
          id: 'load',
        },
        removeControlAction: {
          appDEMethodId: 'remove',
          appDataEntityId: 'web.master',
          id: 'remove',
        },
        updateControlAction: {
          appDEMethodId: 'update',
          appDataEntityId: 'web.master',
          id: 'update',
        },
        autoLoad: true,
        showBusyIndicator: true,
        codeName: 'tree_navparams2',
        controlType: 'TREEVIEW',
        logicName: '树视图_节点视图传参',
        appDataEntityId: 'web.master',
        controlLogics: [
          {
            eventNames: 'onChange',
            itemName: '区划子数据',
            logicTag: 'tree1',
            logicType: 'SCRIPT',
            scriptCode:
              'console.log(data);\r\nuitl.message.info("现在选中的是："data);',
            triggerType: 'CTRLEVENT',
            id: 'logic2',
          },
        ],
        controlParam: {
          id: 'tree1',
        },
        modelId: 'fa4c38ac3a95394770643a98c92ff426',
        modelType: 'PSDETREEVIEW',
        name: 'tree1',
        id: 'web.master.tree_navparams2',
      },
      {
        capLanguageRes: {
          lanResTag: 'DE.LNAME.MASTER',
        },
        caption: '树视图_导航传参',
        codeName: 'treeview_navparams_captionbar',
        controlType: 'CAPTIONBAR',
        appDataEntityId: 'web.master',
        controlParam: {},
        name: 'captionbar',
        id: 'treeview_navparams_captionbar',
      },
    ],
    codeName: 'a729931958199a65a54',
    controlType: 'VIEWLAYOUTPANEL',
    logicName: '树视图_导航传参布局面板',
    appDataEntityId: 'web.master',
    controlParam: {},
    modelId: '78fb689415cc5afad59194caac1f1752',
    modelType: 'PSSYSVIEWLAYOUTPANEL',
    name: 'layoutpanel',
    id: 'a729931958199a65a54',
  },
  title: '树视图_导航传参',
  viewStyle: 'DEFAULT',
  viewType: 'DECUSTOMVIEW',
  enableDP: true,
  showCaptionBar: false,
  modelId: 'a9cdeccef4ffe085e65244740c19d0a4',
  modelType: 'PSAPPDEVIEW',
  name: 'MASTERtreeview_navparams',
  id: 'web.master_treeview_navparams',
};
