export default {
  enableDirtyChecking: true,
  showDataInfoBar: true,
  xdataControlName: 'form',
  loadDefault: true,
  deviewCodeName: 'upload_file_upload',
  deviewId: '31dc0707c17390d1130d394511fa4c4d',
  accUserMode: 3,
  capLanguageRes: {
    lanResTag: 'DE.LNAME.MASTER',
  },
  caption: '编辑器_文件上传',
  codeName: 'master_upload_file_upload',
  appDataEntityId: 'web.master',
  appViewEngines: [
    {
      engineCat: 'VIEW',
      engineType: 'EditView',
      id: 'engine',
    },
  ],
  appViewMsgGroupId: 'upload_file_upload',
  controls: [
    {
      xdataControlName: 'form',
      codeName: 'upload_file_upload_toolbar',
      controlType: 'TOOLBAR',
      logicName: '编辑器_文件上传_工具栏',
      appDataEntityId: 'web.master',
      controlParam: {
        id: 'toolbar',
      },
      modelId: '40aad0a03ea611e3e13a65ec58a0ec87',
      modelType: 'PSDETOOLBAR',
      name: 'toolbar',
      id: 'upload_file_upload_toolbar',
    },
    {
      createControlAction: {
        appDEMethodId: 'create',
        appDataEntityId: 'web.master',
        id: 'create',
      },
      getDraftFromControlAction: {
        appDataEntityId: 'web.master',
        id: 'loaddraftfrom',
      },
      getDraftControlAction: {
        appDEMethodId: 'get_draft',
        appDataEntityId: 'web.master',
        id: 'loaddraft',
      },
      getControlAction: {
        appDEMethodId: 'get',
        appDataEntityId: 'web.master',
        id: 'load',
      },
      removeControlAction: {
        appDEMethodId: 'remove',
        appDataEntityId: 'web.master',
        id: 'remove',
      },
      updateControlAction: {
        appDEMethodId: 'update',
        appDataEntityId: 'web.master',
        id: 'update',
      },
      deformPages: [
        {
          layout: {
            columnCount: 24,
            layout: 'TABLE_24COL',
          },
          deformDetails: [
            {
              layout: {
                columnCount: 24,
                layout: 'TABLE_24COL',
              },
              deformDetails: [
                {
                  dataType: 25,
                  enableCond: 3,
                  labelPos: 'NONE',
                  noPrivDisplayMode: 1,
                  editor: {
                    editorParams: {
                      FILEEXTS: '',
                      MAXFILESIZE: '',
                      MINFILECNT: '',
                      MAXFILECNT: '',
                    },
                    editorType: 'FILEUPLOADER',
                    valueType: 'SIMPLE',
                    editable: true,
                    id: 'formitem',
                  },
                  allowEmpty: true,
                  caption: '文件控件',
                  codeName: 'formitem',
                  detailStyle: 'DEFAULT',
                  detailType: 'FORMITEM',
                  defdgroupLogics: [
                    {
                      logicCat: 'SCRIPTCODE_CHANGE',
                      groupOP: 'AND',
                      defdlogics: [
                        {
                          value: 'util.message.info(data.formitem);',
                          logicType: 'SINGLE',
                          id: ' util.message.info(data.formitem);',
                        },
                      ],
                      logicType: 'GROUP',
                    },
                  ],
                  layoutPos: {
                    colMD: 24,
                    layout: 'TABLE_24COL',
                  },
                  id: 'formitem',
                },
              ],
              caption: '文件上传',
              codeName: 'group1',
              detailStyle: 'DEFAULT',
              detailType: 'GROUPPANEL',
              layoutPos: {
                colMD: 24,
                layout: 'TABLE_24COL',
              },
              showCaption: true,
              id: 'group1',
            },
            {
              layout: {
                columnCount: 24,
                layout: 'TABLE_24COL',
              },
              deformDetails: [
                {
                  dataType: 25,
                  enableCond: 3,
                  labelPos: 'NONE',
                  noPrivDisplayMode: 1,
                  editor: {
                    editorParams: {
                      MAXFILECNT: '1',
                    },
                    editorType: 'FILEUPLOADER_ONE',
                    valueType: 'SIMPLE',
                    editable: true,
                    id: 'formitem1',
                  },
                  allowEmpty: true,
                  caption: '文件控件（单项）',
                  codeName: 'formitem1',
                  detailStyle: 'DEFAULT',
                  detailType: 'FORMITEM',
                  layoutPos: {
                    colMD: 24,
                    layout: 'TABLE_24COL',
                  },
                  id: 'formitem1',
                },
              ],
              caption: '文件控件（单项）',
              codeName: 'grouppanel1',
              detailStyle: 'DEFAULT',
              detailType: 'GROUPPANEL',
              layoutPos: {
                colMD: 24,
                layout: 'TABLE_24COL',
              },
              showCaption: true,
              id: 'grouppanel1',
            },
            {
              actionGroupExtractMode: 'ITEM',
              uiactionGroup: {
                uiactionGroupDetails: [
                  {
                    actionLevel: 100,
                    afterItemType: 'NONE',
                    beforeItemType: 'NONE',
                    buttonStyle: 'DEFAULT',
                    caption: '添加附件',
                    detailType: 'DEUIACTION',
                    uiactionId: 'add_attachments@master',
                    showCaption: true,
                    showIcon: true,
                    sysImage: {
                      cssClass: 'fa fa-plus',
                      glyph: 'xf067@FontAwesome',
                    },
                    id: 'ucd4510f',
                  },
                ],
                appDataEntityId: 'web.master',
                uniqueTag: 'master__Usr0102014691',
                name: '新建附件',
                id: 'usr0102014691',
              },
              layout: {
                columnCount: 24,
                layout: 'TABLE_24COL',
              },
              deformDetails: [
                {
                  contentControl: {
                    aggMode: 'NONE',
                    columnEnableFilter: 2,
                    columnEnableLink: 2,
                    groupMode: 'NONE',
                    groupStyle: 'DEFAULT',
                    degridColumns: [
                      {
                        clconvertMode: 'NONE',
                        dataItemName: 'name',
                        excelCaption: '名称',
                        appDEFieldId: 'name',
                        deuiactionId: 'attachment_preview@attachment',
                        valueType: 'SIMPLE',
                        aggMode: 'NONE',
                        align: 'LEFT',
                        caption: '名称',
                        codeName: 'name',
                        columnType: 'DEFGRIDCOLUMN',
                        noPrivDisplayMode: 1,
                        width: 250,
                        widthUnit: 'STAR',
                        enableSort: true,
                        id: 'name',
                      },
                      {
                        clconvertMode: 'NONE',
                        dataItemName: 'create_time',
                        excelCaption: '上传时间',
                        appDEFieldId: 'create_time',
                        valueFormat: 'YYYY-MM-DD HH:mm:ss',
                        valueType: 'SIMPLE',
                        aggMode: 'NONE',
                        align: 'LEFT',
                        caption: '上传时间',
                        codeName: 'create_time',
                        columnType: 'DEFGRIDCOLUMN',
                        noPrivDisplayMode: 1,
                        width: 200,
                        widthUnit: 'PX',
                        enableSort: true,
                        id: 'create_time',
                      },
                      {
                        clconvertMode: 'NONE',
                        dataItemName: 'owner_id',
                        excelCaption: '所属数据标识',
                        appDEFieldId: 'owner_id',
                        valueType: 'SIMPLE',
                        aggMode: 'NONE',
                        align: 'LEFT',
                        caption: '所属数据标识',
                        codeName: 'owner_id',
                        columnType: 'DEFGRIDCOLUMN',
                        hideMode: 1,
                        noPrivDisplayMode: 1,
                        width: 100,
                        widthUnit: 'PX',
                        enableSort: true,
                        hideDefault: true,
                        id: 'owner_id',
                      },
                      {
                        deuiactionGroup: {
                          uiactionGroupDetails: [
                            {
                              actionLevel: 250,
                              afterItemType: 'NONE',
                              beforeItemType: 'NONE',
                              buttonStyle: 'DEFAULT',
                              detailType: 'DEUIACTION',
                              uiactionId: 'download@attachment',
                              tooltip: '下载当前附件',
                              showIcon: true,
                              sysImage: {
                                cssClass: 'fa fa-download',
                                glyph: 'xf019@FontAwesome',
                              },
                              id: 'u3f91aed',
                            },
                            {
                              actionLevel: 100,
                              afterItemType: 'NONE',
                              beforeItemType: 'NONE',
                              buttonStyle: 'DEFAULT',
                              caption: '删除',
                              detailType: 'DEUIACTION',
                              uiactionId: 'delete@attachment',
                              tooltip: '删除',
                              showCaption: true,
                              showIcon: true,
                              sysImage: {
                                cssClass: 'fa fa-trash-o',
                                glyph: 'xf014@FontAwesome',
                              },
                              id: 'u9f7d084',
                            },
                          ],
                          appDataEntityId: 'web.attachment',
                          uniqueTag: 'attachment__Usr0103721999',
                          name: '附件表格操作列',
                          id: 'usr0103721999',
                        },
                        aggMode: 'NONE',
                        align: 'RIGHT',
                        caption: '操作',
                        codeName: 'uagridcolumn1',
                        columnType: 'UAGRIDCOLUMN',
                        noPrivDisplayMode: 1,
                        width: 100,
                        widthUnit: 'PX',
                        id: 'uagridcolumn1',
                      },
                    ],
                    degridDataItems: [
                      {
                        appDEFieldId: 'name',
                        valueType: 'SIMPLE',
                        dataType: 25,
                        id: 'name',
                      },
                      {
                        format: 'YYYY-MM-DD HH:mm:ss',
                        appDEFieldId: 'create_time',
                        valueType: 'SIMPLE',
                        dataType: 5,
                        id: 'create_time',
                      },
                      {
                        appDEFieldId: 'owner_id',
                        valueType: 'SIMPLE',
                        dataType: 25,
                        id: 'owner_id',
                      },
                      {
                        appDEFieldId: 'file_id',
                        valueType: 'SIMPLE',
                        dataType: 25,
                        id: 'file_id',
                      },
                      {
                        appDEFieldId: 'id',
                        valueType: 'SIMPLE',
                        dataType: 25,
                        id: 'srfkey',
                      },
                      {
                        appDEFieldId: 'id',
                        valueType: 'SIMPLE',
                        dataType: 25,
                        id: 'srfdataaccaction',
                      },
                      {
                        appDEFieldId: 'name',
                        valueType: 'SIMPLE',
                        dataType: 25,
                        id: 'srfmajortext',
                      },
                    ],
                    degridEditItems: [
                      {
                        caption: '标识',
                        codeName: 'srfkey',
                        enableCond: 3,
                        appDEFieldId: 'id',
                        editor: {
                          editorType: 'HIDDEN',
                          valueType: 'SIMPLE',
                          editable: true,
                          id: 'srfkey',
                        },
                        allowEmpty: true,
                        id: 'srfkey',
                      },
                    ],
                    pagingSize: 20,
                    sortMode: 'REMOTE',
                    enableRowEdit: true,
                    enableRowNew: true,
                    singleSelect: true,
                    navViewPos: 'NONE',
                    createControlAction: {
                      appDEMethodId: 'create',
                      appDataEntityId: 'web.attachment',
                      id: 'create',
                    },
                    fetchControlAction: {
                      appDEMethodId: 'fetch_default',
                      appDataEntityId: 'web.attachment',
                      id: 'fetch',
                    },
                    getDraftControlAction: {
                      appDEMethodId: 'get_draft',
                      appDataEntityId: 'web.attachment',
                      id: 'loaddraft',
                    },
                    getControlAction: {
                      appDEMethodId: 'get',
                      appDataEntityId: 'web.attachment',
                      id: 'load',
                    },
                    removeControlAction: {
                      appDEMethodId: 'remove',
                      appDataEntityId: 'web.attachment',
                      id: 'remove',
                    },
                    updateControlAction: {
                      appDEMethodId: 'update',
                      appDataEntityId: 'web.attachment',
                      id: 'update',
                    },
                    autoLoad: true,
                    showBusyIndicator: true,
                    codeName: 'attach',
                    controlStyle: 'ATTACHMENT_GRID',
                    controlType: 'GRID',
                    logicName: '附件表格',
                    appDataEntityId: 'web.attachment',
                    controlLogics: [
                      {
                        eventNames: 'onLoadSuccess',
                        logicTag: 'attachments_grid',
                        logicType: 'APPDEUILOGIC',
                        appDEUILogicId: 'calc_attachment_hidden',
                        appDataEntityId: 'web.attachment',
                        triggerType: 'CTRLEVENT',
                        id: 'logic2',
                      },
                    ],
                    controlParam: {},
                    sysPFPluginId: 'attachment_grid',
                    modelId: '0a109435fff80754feb0da5154907b7a',
                    modelType: 'PSDEGRID',
                    name: 'attachments_grid',
                    id: 'web.attachment.attach',
                  },
                  contentType: 'GRID',
                  appDEFieldId: 'attachments',
                  layout: {
                    columnCount: 24,
                    layout: 'TABLE_24COL',
                  },
                  codeName: 'attachments',
                  detailStyle: 'DEFAULT',
                  detailType: 'MDCTRL',
                  layoutPos: {
                    colMD: 24,
                    layout: 'TABLE_24COL',
                  },
                  showCaption: true,
                  id: 'attachments',
                },
              ],
              caption: '多数据部件',
              codeName: 'grouppanel2',
              detailStyle: 'DEFAULT',
              detailType: 'GROUPPANEL',
              layoutPos: {
                colMD: 24,
                layout: 'TABLE_24COL',
              },
              showCaption: true,
              id: 'grouppanel2',
            },
            {
              dataType: 25,
              enableCond: 3,
              labelPos: 'LEFT',
              labelWidth: 130,
              noPrivDisplayMode: 1,
              appDEFieldId: 'id',
              editor: {
                editorType: 'HIDDEN',
                valueType: 'SIMPLE',
                editable: true,
                id: 'id',
              },
              allowEmpty: true,
              hidden: true,
              capLanguageRes: {
                lanResTag: 'DEF.LNAME.MASTER.ID',
              },
              caption: '标识',
              codeName: 'id',
              detailStyle: 'DEFAULT',
              detailType: 'FORMITEM',
              layoutPos: {
                colMD: 24,
                layout: 'TABLE_24COL',
              },
              id: 'id',
            },
          ],
          caption: '文件上传',
          codeName: 'formpage1',
          detailStyle: 'DEFAULT',
          detailType: 'FORMPAGE',
          id: 'formpage1',
        },
      ],
      layout: {
        columnCount: 24,
        layout: 'TABLE_24COL',
      },
      tabHeaderPos: 'TOP',
      noTabHeader: true,
      autoLoad: true,
      showBusyIndicator: true,
      codeName: 'main52',
      controlType: 'FORM',
      logicName: '编辑器_文件上传_表单',
      appDataEntityId: 'web.master',
      controlParam: {
        id: 'form',
      },
      modelId: '0ce6f432a3a12358d0a06bb3b459d9fa',
      modelType: 'PSDEFORM_EDITFORM',
      name: 'form',
      id: 'web.master.main52',
    },
    {
      codeName: 'upload_file_upload_datainfobar',
      controlType: 'DATAINFOBAR',
      appDataEntityId: 'web.master',
      controlParam: {
        id: 'datainfobar',
      },
      name: 'datainfobar',
      id: 'upload_file_upload_datainfobar',
    },
    {
      capLanguageRes: {
        lanResTag: 'DE.LNAME.MASTER',
      },
      caption: '编辑器_文件上传',
      codeName: 'upload_file_upload_captionbar',
      controlType: 'CAPTIONBAR',
      appDataEntityId: 'web.master',
      controlParam: {},
      name: 'captionbar',
      id: 'upload_file_upload_captionbar',
    },
  ],
  viewLayoutPanel: {
    layoutBodyOnly: true,
    useDefaultLayout: true,
    layoutPanel: true,
    codeName: 'layoutpanel',
    controlStyle: 'APPDEEDITVIEW',
    controlType: 'VIEWLAYOUTPANEL',
    appDataEntityId: 'web.master',
    controlParam: {},
    id: 'layoutpanel',
  },
  title: '编辑器_文件上传',
  viewStyle: 'DEFAULT',
  viewType: 'DEEDITVIEW',
  enableDP: true,
  showCaptionBar: false,
  modelId: 'a76850044de5729bd9dbea86b21a65aa',
  modelType: 'PSAPPDEVIEW',
  name: 'MASTERupload_file_upload',
  id: 'web.master_upload_file_upload',
};
