export default {
  tabLayout: 'FLOW',
  loadDefault: true,
  showDataInfoBar: true,
  deviewCodeName: 'chart',
  deviewId: '3774628b5cc0b4121a1682558a946e55',
  accUserMode: 3,
  capLanguageRes: {
    lanResTag: 'DE.LNAME.MASTER',
  },
  caption: '图表',
  codeName: 'master_chart',
  appDataEntityId: 'web.master',
  appViewEngines: [
    {
      engineCat: 'VIEW',
      engineType: 'TabExpView',
      id: 'engine',
    },
  ],
  appViewMsgGroupId: 'chart',
  controls: [
    {
      dedrtabPages: [
        {
          caption: '基础',
          appViewId: 'web.master_chart_base',
          id: 'base',
        },
        {
          caption: '折线图',
          appViewId: 'web.master_chart_line',
          id: 'line',
        },
        {
          caption: '饼图',
          appViewId: 'web.master_chart_pie',
          id: 'pie',
        },
        {
          caption: '环形图',
          appViewId: 'web.master_chart_annular',
          id: 'doughnut',
        },
        {
          caption: '柱状图',
          appViewId: 'web.master_chart_bar',
          id: 'bar',
        },
        {
          caption: '分组柱状图',
          appViewId: 'web.master_chart_groupbar',
          id: 'grouped_bar',
        },
        {
          caption: '堆叠柱状图',
          appViewId: 'web.master_chart_stacked_column',
          id: 'stacked_bar',
        },
        {
          caption: '漏斗图',
          appViewId: 'web.master_chart_funnel_plot',
          id: 'funnel',
        },
        {
          caption: '区域图',
          appViewId: 'web.master_chart_regional',
          id: 'area',
        },
        {
          caption: 'K线图',
          appViewId: 'web.master_chart_candlestick',
          id: 'candlestick',
        },
        {
          caption: '雷达图',
          appViewId: 'web.master_chart_radar',
          id: 'radar',
        },
        {
          caption: '仪表图',
          appViewId: 'web.master_chart_instrument',
          id: 'gauge',
        },
        {
          caption: '散点图',
          appViewId: 'web.master_chart_scatter',
          id: 'scatter',
        },
        {
          caption: '地图',
          appViewId: 'web.master_chart_map',
          id: 'map',
        },
        {
          caption: '多序列',
          appViewId: 'web.master_chart_multiple_sequences',
          id: 'multiple_sequences',
        },
      ],
      dataRelationTag: 'chart_DR',
      editItemCapLanguageRes: {
        lanResTag: 'DE.LNAME.MASTER',
      },
      editItemCaption: '主数据',
      uniqueTag: 'master_chart__tabexppanel',
      autoLoad: true,
      showBusyIndicator: true,
      codeName: 'chart_dr',
      controlType: 'DRTAB',
      appDataEntityId: 'web.master',
      controlParam: {
        id: 'tabexppanel',
      },
      modelId: '64a7138ce6ac693525cf09103b8323bd',
      modelType: 'PSDEDRTAB',
      name: 'tabexppanel',
      id: 'chart_dr',
    },
    {
      capLanguageRes: {
        lanResTag: 'DE.LNAME.MASTER',
      },
      caption: '图表',
      codeName: 'chart_captionbar',
      controlType: 'CAPTIONBAR',
      appDataEntityId: 'web.master',
      controlParam: {},
      name: 'captionbar',
      id: 'chart_captionbar',
    },
  ],
  viewLayoutPanel: {
    layoutBodyOnly: true,
    useDefaultLayout: true,
    layoutPanel: true,
    codeName: 'layoutpanel',
    controlStyle: 'APPDETABEXPVIEW',
    controlType: 'VIEWLAYOUTPANEL',
    appDataEntityId: 'web.master',
    controlParam: {},
    id: 'layoutpanel',
  },
  title: '图表',
  viewStyle: 'DEFAULT',
  viewType: 'DETABEXPVIEW',
  enableDP: true,
  showCaptionBar: false,
  modelId: '53f6c06b64ba5b55e9e9aebe393075d5',
  modelType: 'PSAPPDEVIEW',
  name: 'MASTERchart',
  id: 'web.master_chart',
};
