export default {
  mdctrlActiveMode: 2,
  xdataControlName: 'tree',
  loadDefault: true,
  deviewCodeName: 'Tree_search',
  deviewId: '478fb0860033e2531957608d1e26d221',
  accUserMode: 3,
  capLanguageRes: {
    lanResTag: 'DE.LNAME.MASTER',
  },
  caption: '树视图_搜索',
  codeName: 'master_tree_search',
  appDataEntityId: 'web.master',
  appViewEngines: [
    {
      engineCat: 'VIEW',
      engineType: 'TreeView',
      id: 'engine',
    },
  ],
  appViewMsgGroupId: 'tree_search',
  controls: [
    {
      detreeNodeRSs: [
        {
          childDETreeNodeId: 'node_1',
          parentDETreeNodeId: 'node',
          parentValueLevel: 1,
          searchMode: 3,
          id: '主数据（node）-名称（node_1）',
        },
        {
          childDETreeNodeId: 'node',
          parentDETreeNodeId: 'root',
          parentValueLevel: 1,
          searchMode: 3,
          name: '默认根节点（ROOT）-主数据（node）',
          id: '默认根节点（root）-主数据（node）',
        },
      ],
      detreeNodes: [
        {
          text: '默认根节点',
          nodeType: 'ROOT',
          treeNodeType: 'STATIC',
          hasDETreeNodeRSs: true,
          enableQuickSearch: true,
          rootNode: true,
          name: '默认根节点',
          id: 'root',
        },
        {
          text: '主数据',
          nodeType: 'node',
          treeNodeType: 'STATIC',
          hasDETreeNodeRSs: true,
          enableQuickSearch: true,
          name: '主数据',
          id: 'node',
        },
        {
          dataSourceType: 'DEDATASET',
          idAppDEFieldId: 'id',
          appDEDataSetId: 'fetch_default',
          textAppDEFieldId: 'name',
          nodeType: 'node_1',
          appDataEntityId: 'web.master',
          treeNodeType: 'DE',
          enableQuickSearch: true,
          name: '名称',
          id: 'node_1',
        },
      ],
      outputIconDefault: true,
      navViewPos: 'NONE',
      createControlAction: {
        appDEMethodId: 'create',
        appDataEntityId: 'web.master',
        id: 'create',
      },
      fetchControlAction: {
        appDataEntityId: 'web.master',
        id: 'fetch',
      },
      getControlAction: {
        appDEMethodId: 'get',
        appDataEntityId: 'web.master',
        id: 'load',
      },
      removeControlAction: {
        appDEMethodId: 'remove',
        appDataEntityId: 'web.master',
        id: 'remove',
      },
      updateControlAction: {
        appDEMethodId: 'update',
        appDataEntityId: 'web.master',
        id: 'update',
      },
      autoLoad: true,
      showBusyIndicator: true,
      codeName: 'tree_search_tree_view',
      controlType: 'TREEVIEW',
      logicName: '树视图_搜索_树视图',
      appDataEntityId: 'web.master',
      controlParam: {
        id: 'tree',
      },
      modelId: '72b971924bcbe684f99a432c8a361019',
      modelType: 'PSDETREEVIEW',
      name: 'tree',
      id: 'web.master.tree_search_tree_view',
    },
    {
      groupMode: 'SINGLE',
      controlType: 'SEARCHBAR',
      appDataEntityId: 'web.master',
      controlParam: {
        id: 'searchbar',
      },
      id: 'searchbar',
    },
    {
      capLanguageRes: {
        lanResTag: 'DE.LNAME.MASTER',
      },
      caption: '树视图_搜索',
      codeName: 'tree_search_captionbar',
      controlType: 'CAPTIONBAR',
      appDataEntityId: 'web.master',
      controlParam: {},
      name: 'captionbar',
      id: 'tree_search_captionbar',
    },
  ],
  viewLayoutPanel: {
    layoutBodyOnly: true,
    useDefaultLayout: true,
    layoutPanel: true,
    codeName: 'layoutpanel',
    controlStyle: 'APPDETREEVIEW',
    controlType: 'VIEWLAYOUTPANEL',
    appDataEntityId: 'web.master',
    controlParam: {},
    id: 'layoutpanel',
  },
  title: '树视图_搜索',
  viewStyle: 'DEFAULT',
  viewType: 'DETREEVIEW',
  enableDP: true,
  showCaptionBar: false,
  modelId: '4abb197e90734f81225906dded70987d',
  modelType: 'PSAPPDEVIEW',
  name: 'MASTERTree_search',
  id: 'web.master_tree_search',
};
