export default {
  deviewCodeName: 'searchform_layout',
  deviewId: 'af0a1890a61c4576095086ecb2697c96',
  accUserMode: 3,
  capLanguageRes: {
    lanResTag: 'DE.LNAME.MASTER',
  },
  caption: '搜索表单_布局',
  codeName: 'master_searchform_layout',
  appDataEntityId: 'web.master',
  appViewMsgGroupId: 'searchform_layout',
  viewLayoutPanel: {
    layoutBodyOnly: true,
    viewProxyMode: true,
    layoutMode: 'FLEX',
    layout: {
      layout: 'FLEX',
    },
    rootPanelItems: [
      {
        actionGroupExtractMode: 'ITEM',
        panelItems: [
          {
            actionGroupExtractMode: 'ITEM',
            panelItems: [
              {
                actionGroupExtractMode: 'ITEM',
                panelItems: [
                  {
                    caption: '搜索表单',
                    itemStyle: 'DEFAULT',
                    itemType: 'CTRLPOS',
                    layoutPos: {
                      shrink: 1,
                      layout: 'FLEX',
                    },
                    showCaption: true,
                    id: 'searchform',
                  },
                ],
                predefinedType: 'CONTAINER_GROUP',
                layout: {
                  layout: 'FLEX',
                },
                dataRegionType: 'INHERIT',
                caption: '按钮位置右边',
                itemStyle: 'DEFAULT',
                itemType: 'CONTAINER',
                layoutPos: {
                  layoutPos: 'CENTER',
                  layout: 'BORDER',
                },
                showCaption: true,
                id: 'container_group',
              },
              {
                actionGroupExtractMode: 'ITEM',
                panelItems: [
                  {
                    caption: '搜索表单',
                    itemStyle: 'DEFAULT',
                    itemType: 'CTRLPOS',
                    layoutPos: {
                      shrink: 1,
                      layout: 'FLEX',
                    },
                    showCaption: true,
                    id: 'searchform1',
                  },
                ],
                predefinedType: 'CONTAINER_GROUP',
                layout: {
                  layout: 'FLEX',
                },
                dataRegionType: 'INHERIT',
                caption: '按钮位置下方',
                itemStyle: 'DEFAULT',
                itemType: 'CONTAINER',
                layoutPos: {
                  layoutPos: 'CENTER',
                  layout: 'BORDER',
                },
                showCaption: true,
                id: 'container_group1',
              },
            ],
            predefinedType: 'CONTAINER_SCROLL_MAIN',
            layout: {
              layout: 'BORDER',
            },
            dataRegionType: 'INHERIT',
            caption: '面板容器',
            itemStyle: 'DEFAULT',
            itemType: 'CONTAINER',
            layoutPos: {
              layoutPos: 'CENTER',
              layout: 'BORDER',
            },
            showCaption: true,
            id: 'container_scroll_main',
          },
        ],
        predefinedType: 'CONTAINER_SCROLL',
        layout: {
          layout: 'BORDER',
        },
        dataRegionType: 'INHERIT',
        caption: '滚动条容器',
        itemStyle: 'DEFAULT',
        itemType: 'CONTAINER',
        layoutPos: {
          shrink: 1,
          layout: 'FLEX',
        },
        id: 'container_scroll',
      },
    ],
    layoutPanel: true,
    controls: [
      {
        searchButtonPos: 'BOTTOM',
        searchButtonStyle: 'DEFAULT',
        deformPages: [
          {
            layout: {
              columnCount: 24,
              layout: 'TABLE_24COL',
            },
            deformDetails: [
              {
                dataType: 25,
                enableCond: 3,
                labelPos: 'LEFT',
                labelWidth: 130,
                noPrivDisplayMode: 1,
                appDEFieldId: 'name',
                editor: {
                  editorType: 'TEXTBOX',
                  valueType: 'SIMPLE',
                  editable: true,
                  id: 'n_name_like',
                },
                allowEmpty: true,
                capLanguageRes: {
                  lanResTag: 'CONTROL.DEFSFITEM.MASTER.N_NAME_LIKE',
                },
                caption: '名称',
                codeName: 'n_name_like',
                detailStyle: 'DEFAULT',
                detailType: 'FORMITEM',
                layoutPos: {
                  colLG: 12,
                  colMD: 12,
                  layout: 'TABLE_24COL',
                },
                showCaption: true,
                id: 'n_name_like',
              },
              {
                dataType: 25,
                enableCond: 3,
                labelPos: 'LEFT',
                labelWidth: 130,
                noPrivDisplayMode: 1,
                appDEFieldId: 'type',
                editor: {
                  singleSelect: true,
                  handlerType: 'PickupText',
                  enableAC: true,
                  forceSelection: true,
                  showTrigger: true,
                  editorParams: {
                    AC: 'TRUE',
                    TRIGGER: 'TRUE',
                    PICKUPVIEW: 'FALSE',
                  },
                  editorType: 'PICKEREX_TRIGGER',
                  valueType: 'SIMPLE',
                  editable: true,
                  id: 'n_type_eq',
                },
                allowEmpty: true,
                caption: '类型',
                codeName: 'n_type_eq',
                detailStyle: 'DEFAULT',
                detailType: 'FORMITEM',
                layoutPos: {
                  colLG: 12,
                  colMD: 12,
                  layout: 'TABLE_24COL',
                },
                showCaption: true,
                id: 'n_type_eq',
              },
            ],
            caption: '常规条件',
            codeName: 'formpage1',
            detailStyle: 'DEFAULT',
            detailType: 'FORMPAGE',
            id: 'formpage1',
          },
        ],
        layout: {
          columnCount: 24,
          layout: 'TABLE_24COL',
        },
        tabHeaderPos: 'TOP',
        noTabHeader: true,
        autoLoad: true,
        showBusyIndicator: true,
        codeName: 'searchform_layout2',
        controlType: 'SEARCHFORM',
        logicName: '搜索表单_布局_按钮位置下方',
        appDataEntityId: 'web.master',
        controlLogics: [
          {
            eventNames: 'onSearch',
            logicTag: 'searchform1',
            logicType: 'SCRIPT',
            scriptCode: 'util.message.info(data);',
            triggerType: 'CTRLEVENT',
            id: 'search_form_onsearch',
          },
        ],
        controlParam: {
          id: 'searchform1',
        },
        modelId: '56e37fe29b9cf2e0b36d9400fc1db93f',
        modelType: 'PSDEFORM_SEARCHFORM',
        name: 'searchform1',
        id: 'web.master.searchform_layout2',
      },
      {
        searchButtonPos: 'RIGHT',
        searchButtonStyle: 'DEFAULT',
        deformPages: [
          {
            layout: {
              columnCount: 24,
              layout: 'TABLE_24COL',
            },
            deformDetails: [
              {
                dataType: 25,
                enableCond: 3,
                labelPos: 'LEFT',
                labelWidth: 130,
                noPrivDisplayMode: 1,
                appDEFieldId: 'name',
                editor: {
                  editorType: 'TEXTBOX',
                  valueType: 'SIMPLE',
                  editable: true,
                  id: 'n_name_like',
                },
                allowEmpty: true,
                capLanguageRes: {
                  lanResTag: 'CONTROL.DEFSFITEM.MASTER.N_NAME_LIKE',
                },
                caption: '名称',
                codeName: 'n_name_like',
                detailStyle: 'DEFAULT',
                detailType: 'FORMITEM',
                defdgroupLogics: [
                  {
                    logicCat: 'SCRIPTCODE_CHANGE',
                    groupOP: 'AND',
                    defdlogics: [
                      {
                        logicType: 'SINGLE',
                      },
                    ],
                    logicType: 'GROUP',
                  },
                  {
                    logicCat: 'SCRIPTCODE_CLICK',
                    groupOP: 'AND',
                    defdlogics: [
                      {
                        logicType: 'SINGLE',
                      },
                    ],
                    logicType: 'GROUP',
                  },
                ],
                layoutPos: {
                  colLG: 12,
                  colMD: 12,
                  layout: 'TABLE_24COL',
                },
                showCaption: true,
                id: 'n_name_like',
              },
              {
                dataType: 25,
                enableCond: 3,
                ignoreInput: 3,
                labelPos: 'LEFT',
                labelWidth: 130,
                noPrivDisplayMode: 1,
                appDEFieldId: 'type',
                editor: {
                  singleSelect: true,
                  handlerType: 'PickupText',
                  enableAC: true,
                  forceSelection: true,
                  showTrigger: true,
                  editorParams: {
                    AC: 'TRUE',
                    TRIGGER: 'TRUE',
                    PICKUPVIEW: 'FALSE',
                  },
                  editorType: 'PICKEREX_TRIGGER',
                  valueType: 'SIMPLE',
                  editable: true,
                  id: 'n_type_eq',
                },
                allowEmpty: true,
                convertToCodeItemText: true,
                needCodeListConfig: true,
                caption: '类型',
                codeName: 'n_type_eq',
                detailStyle: 'DEFAULT',
                detailType: 'FORMITEM',
                layoutPos: {
                  colLG: 12,
                  colMD: 12,
                  layout: 'TABLE_24COL',
                },
                showCaption: true,
                id: 'n_type_eq',
              },
            ],
            caption: '常规条件',
            codeName: 'formpage1',
            detailStyle: 'DEFAULT',
            detailType: 'FORMPAGE',
            id: 'formpage1',
          },
        ],
        layout: {
          columnCount: 24,
          layout: 'TABLE_24COL',
        },
        tabHeaderPos: 'TOP',
        noTabHeader: true,
        autoLoad: true,
        showBusyIndicator: true,
        codeName: 'searchform_layout1',
        controlType: 'SEARCHFORM',
        logicName: '搜索表单_布局_按钮位置右边',
        appDataEntityId: 'web.master',
        controlLogics: [
          {
            eventNames: 'onSearch',
            logicTag: 'searchform',
            logicType: 'SCRIPT',
            scriptCode: 'util.message.info(data);',
            triggerType: 'CTRLEVENT',
            id: 'search_form_onsearch',
          },
        ],
        controlParam: {
          id: 'searchform',
        },
        modelId: 'bc6989f9b0891ff0bdeeed7a876c61a4',
        modelType: 'PSDEFORM_SEARCHFORM',
        name: 'searchform',
        id: 'web.master.searchform_layout1',
      },
      {
        searchButtonPos: 'RIGHT',
        searchButtonStyle: 'DEFAULT',
        deformPages: [
          {
            layout: {
              columnCount: 24,
              layout: 'TABLE_24COL',
            },
            deformDetails: [
              {
                dataType: 25,
                enableCond: 3,
                labelPos: 'LEFT',
                labelWidth: 130,
                noPrivDisplayMode: 1,
                appDEFieldId: 'name',
                editor: {
                  editorType: 'TEXTBOX',
                  valueType: 'SIMPLE',
                  editable: true,
                  id: 'n_name_like',
                },
                allowEmpty: true,
                capLanguageRes: {
                  lanResTag: 'CONTROL.DEFSFITEM.MASTER.N_NAME_LIKE',
                },
                caption: '名称',
                codeName: 'n_name_like',
                detailStyle: 'DEFAULT',
                detailType: 'FORMITEM',
                defdgroupLogics: [
                  {
                    logicCat: 'SCRIPTCODE_CHANGE',
                    groupOP: 'AND',
                    defdlogics: [
                      {
                        logicType: 'SINGLE',
                      },
                    ],
                    logicType: 'GROUP',
                  },
                  {
                    logicCat: 'SCRIPTCODE_CLICK',
                    groupOP: 'AND',
                    defdlogics: [
                      {
                        logicType: 'SINGLE',
                      },
                    ],
                    logicType: 'GROUP',
                  },
                ],
                layoutPos: {
                  colLG: 12,
                  colMD: 12,
                  layout: 'TABLE_24COL',
                },
                showCaption: true,
                id: 'n_name_like',
              },
              {
                dataType: 25,
                enableCond: 3,
                ignoreInput: 3,
                labelPos: 'LEFT',
                labelWidth: 130,
                noPrivDisplayMode: 1,
                appDEFieldId: 'type',
                editor: {
                  singleSelect: true,
                  handlerType: 'PickupText',
                  enableAC: true,
                  forceSelection: true,
                  showTrigger: true,
                  editorParams: {
                    AC: 'TRUE',
                    TRIGGER: 'TRUE',
                    PICKUPVIEW: 'FALSE',
                  },
                  editorType: 'PICKEREX_TRIGGER',
                  valueType: 'SIMPLE',
                  editable: true,
                  id: 'n_type_eq',
                },
                allowEmpty: true,
                convertToCodeItemText: true,
                needCodeListConfig: true,
                caption: '类型',
                codeName: 'n_type_eq',
                detailStyle: 'DEFAULT',
                detailType: 'FORMITEM',
                layoutPos: {
                  colLG: 12,
                  colMD: 12,
                  layout: 'TABLE_24COL',
                },
                showCaption: true,
                id: 'n_type_eq',
              },
            ],
            caption: '常规条件',
            codeName: 'formpage1',
            detailStyle: 'DEFAULT',
            detailType: 'FORMPAGE',
            id: 'formpage1',
          },
        ],
        layout: {
          columnCount: 24,
          layout: 'TABLE_24COL',
        },
        tabHeaderPos: 'TOP',
        noTabHeader: true,
        autoLoad: true,
        showBusyIndicator: true,
        codeName: 'searchform_layout1',
        controlType: 'SEARCHFORM',
        logicName: '搜索表单_布局_按钮位置右边',
        appDataEntityId: 'web.master',
        controlLogics: [
          {
            eventNames: 'onSearch',
            logicTag: 'searchform2',
            logicType: 'SCRIPT',
            scriptCode: 'util.message.info(data);',
            triggerType: 'CTRLEVENT',
            id: 'search_form_onsearch',
          },
        ],
        controlParam: {
          id: 'searchform2',
        },
        modelId: 'bc6989f9b0891ff0bdeeed7a876c61a4',
        modelType: 'PSDEFORM_SEARCHFORM',
        name: 'searchform2',
        id: 'web.master.searchform_layout1',
      },
      {
        codeName: 'searchform_layout_toolbar',
        controlType: 'TOOLBAR',
        logicName: '工具栏_基础',
        appDataEntityId: 'web.master',
        controlParam: {
          id: 'toolbar',
        },
        modelId: 'e2386b44801b1f7a387e01db205ec923',
        modelType: 'PSDETOOLBAR',
        name: 'toolbar',
        id: 'searchform_layout_toolbar',
      },
      {
        capLanguageRes: {
          lanResTag: 'DE.LNAME.MASTER',
        },
        caption: '搜索表单_布局',
        codeName: 'searchform_layout_captionbar',
        controlType: 'CAPTIONBAR',
        appDataEntityId: 'web.master',
        controlParam: {},
        name: 'captionbar',
        id: 'searchform_layout_captionbar',
      },
    ],
    codeName: 'a4b2a3c18a4e4f5d560',
    controlType: 'VIEWLAYOUTPANEL',
    logicName: 'searchform_layout',
    appDataEntityId: 'web.master',
    controlParam: {},
    modelId: '4d0a62037322f601ce864cddbf776209',
    modelType: 'PSSYSVIEWLAYOUTPANEL',
    name: 'layoutpanel',
    id: 'a4b2a3c18a4e4f5d560',
  },
  title: '搜索表单_布局',
  viewStyle: 'DEFAULT',
  viewType: 'DECUSTOMVIEW',
  enableDP: true,
  showCaptionBar: false,
  modelId: 'b2f14bc15fe9039bd92dc6bde5069a95',
  modelType: 'PSAPPDEVIEW',
  name: 'MASTERsearchform_layout',
  id: 'web.master_searchform_layout',
};
