export default {
  deviewCodeName: 'calendar_nav',
  deviewId: '7071afd3db2b4b2b8081ff01d53b1861',
  accUserMode: 3,
  capLanguageRes: {
    lanResTag: 'DE.LNAME.MASTER',
  },
  caption: '日历_内置导航栏',
  codeName: 'master_calendar_nav',
  appDataEntityId: 'web.master',
  appViewMsgGroupId: 'calendar_nav',
  viewLayoutPanel: {
    viewProxyMode: true,
    layoutMode: 'FLEX',
    layout: {
      layout: 'FLEX',
    },
    rootPanelItems: [
      {
        actionGroupExtractMode: 'ITEM',
        panelItems: [
          {
            actionGroupExtractMode: 'ITEM',
            panelItems: [
              {
                actionGroupExtractMode: 'ITEM',
                panelItems: [
                  {
                    actionGroupExtractMode: 'ITEM',
                    panelItems: [
                      {
                        actionGroupExtractMode: 'ITEM',
                        panelItems: [
                          {
                            actionGroupExtractMode: 'ITEM',
                            panelItems: [
                              {
                                caption: '日历',
                                itemStyle: 'DEFAULT',
                                itemType: 'CTRLPOS',
                                layoutPos: {
                                  shrink: 1,
                                  layout: 'FLEX',
                                },
                                showCaption: true,
                                id: 'calendar1',
                              },
                            ],
                            layout: {
                              layout: 'FLEX',
                            },
                            dataRegionType: 'INHERIT',
                            caption: '容器',
                            itemStyle: 'DEFAULT',
                            itemType: 'CONTAINER',
                            layoutPos: {
                              shrink: 1,
                              layout: 'FLEX',
                            },
                            id: 'container1',
                          },
                        ],
                        predefinedType: 'CONTAINER_GROUP',
                        layout: {
                          layout: 'FLEX',
                        },
                        dataRegionType: 'INHERIT',
                        caption: '右侧导航栏',
                        itemStyle: 'DEFAULT',
                        itemType: 'CONTAINER',
                        layoutPos: {
                          shrink: 1,
                          layout: 'FLEX',
                        },
                        showCaption: true,
                        id: 'container_group1',
                      },
                      {
                        actionGroupExtractMode: 'ITEM',
                        panelItems: [
                          {
                            actionGroupExtractMode: 'ITEM',
                            panelItems: [
                              {
                                caption: '日历',
                                itemStyle: 'DEFAULT',
                                itemType: 'CTRLPOS',
                                layoutPos: {
                                  shrink: 1,
                                  layout: 'FLEX',
                                },
                                showCaption: true,
                                id: 'calendar2',
                              },
                            ],
                            layout: {
                              layout: 'FLEX',
                            },
                            dataRegionType: 'INHERIT',
                            caption: '容器',
                            itemStyle: 'DEFAULT',
                            itemType: 'CONTAINER',
                            layoutPos: {
                              shrink: 1,
                              layout: 'FLEX',
                            },
                            id: 'container2',
                          },
                        ],
                        predefinedType: 'CONTAINER_GROUP',
                        layout: {
                          layout: 'FLEX',
                        },
                        dataRegionType: 'INHERIT',
                        caption: '下方导航栏',
                        itemStyle: 'DEFAULT',
                        itemType: 'CONTAINER',
                        layoutPos: {
                          shrink: 1,
                          layout: 'FLEX',
                        },
                        showCaption: true,
                        id: 'container_group2',
                      },
                    ],
                    layout: {
                      layout: 'FLEX',
                    },
                    dataRegionType: 'INHERIT',
                    caption: '容器',
                    itemStyle: 'DEFAULT',
                    itemType: 'CONTAINER',
                    layoutPos: {
                      shrink: 1,
                      layout: 'FLEX',
                    },
                    id: 'container',
                  },
                ],
                predefinedType: 'CONTAINER_GROUP',
                layout: {
                  layout: 'FLEX',
                },
                dataRegionType: 'INHERIT',
                caption: '导航栏-可设置位置，宽高',
                itemStyle: 'DEFAULT',
                itemType: 'CONTAINER',
                layoutPos: {
                  layoutPos: 'CENTER',
                  layout: 'BORDER',
                },
                showCaption: true,
                id: 'container_group',
              },
            ],
            predefinedType: 'CONTAINER_SCROLL_MAIN',
            layout: {
              layout: 'BORDER',
            },
            dataRegionType: 'INHERIT',
            caption: '面板容器',
            itemStyle: 'DEFAULT',
            itemType: 'CONTAINER',
            layoutPos: {
              layoutPos: 'CENTER',
              layout: 'BORDER',
            },
            showCaption: true,
            id: 'container_scroll_main',
          },
        ],
        predefinedType: 'CONTAINER_SCROLL',
        layout: {
          layout: 'BORDER',
        },
        dataRegionType: 'INHERIT',
        caption: '滚动条容器',
        itemStyle: 'DEFAULT',
        itemType: 'CONTAINER',
        layoutPos: {
          shrink: 1,
          layout: 'FLEX',
        },
        id: 'container_scroll',
      },
    ],
    layoutPanel: true,
    controls: [
      {
        calendarStyle: 'MONTH',
        groupMode: 'NONE',
        legendPos: 'NONE',
        sysCalendarItems: [
          {
            beginTimeAppDEFieldId: 'date',
            endTimeAppDEFieldId: 'date',
            idAppDEFieldId: 'id',
            itemStyle: 'DEFAULT',
            itemType: 'date',
            appDEDataSetId: 'fetch_default',
            textAppDEFieldId: 'name',
            appDataEntityId: 'web.master',
            navAppViewId: 'web.master_info_view',
            id: 'date',
          },
        ],
        navViewPos: 'NONE',
        autoLoad: true,
        showBusyIndicator: true,
        codeName: 'calendar_nav_width',
        controlType: 'CALENDAR',
        logicName: '日历_内置导航栏_导航栏宽度',
        appDataEntityId: 'web.master',
        controlParam: {
          id: 'calendar1',
        },
        modelId: '16cf9a2264db1e6d6002ebb88e3acd68',
        modelType: 'PSSYSCALENDAR',
        name: 'calendar1',
        id: 'web.master.calendar_nav_width',
      },
      {
        calendarStyle: 'MONTH',
        groupMode: 'NONE',
        legendPos: 'NONE',
        sysCalendarItems: [
          {
            beginTimeAppDEFieldId: 'date',
            endTimeAppDEFieldId: 'date',
            idAppDEFieldId: 'id',
            itemStyle: 'DEFAULT',
            itemType: 'date',
            appDEDataSetId: 'fetch_default',
            textAppDEFieldId: 'name',
            appDataEntityId: 'web.master',
            navAppViewId: 'web.master_info_view',
            id: 'date',
          },
        ],
        navViewPos: 'NONE',
        autoLoad: true,
        showBusyIndicator: true,
        codeName: 'calendar_nav_height',
        controlType: 'CALENDAR',
        logicName: '日历_内置导航栏_导航栏高度',
        appDataEntityId: 'web.master',
        controlParam: {
          id: 'calendar2',
        },
        modelId: 'e8fbbd6bf15fac59e36b0ae34df0bcef',
        modelType: 'PSSYSCALENDAR',
        name: 'calendar2',
        id: 'web.master.calendar_nav_height',
      },
      {
        capLanguageRes: {
          lanResTag: 'DE.LNAME.MASTER',
        },
        caption: '日历_内置导航栏',
        codeName: 'calendar_nav_captionbar',
        controlType: 'CAPTIONBAR',
        appDataEntityId: 'web.master',
        controlParam: {},
        name: 'captionbar',
        id: 'calendar_nav_captionbar',
      },
    ],
    codeName: 'usr0515586613',
    controlType: 'VIEWLAYOUTPANEL',
    logicName: '日历_内置导航栏布局面板',
    appDataEntityId: 'web.master',
    controlParam: {},
    modelId: 'a23ca897d20e971a8568c775c0277fbd',
    modelType: 'PSSYSVIEWLAYOUTPANEL',
    name: 'layoutpanel',
    id: 'usr0515586613',
  },
  title: '日历_内置导航栏',
  viewStyle: 'DEFAULT',
  viewType: 'DECUSTOMVIEW',
  enableDP: true,
  showCaptionBar: false,
  modelId: 'c5c4e50366fc8014351f3d886a41bd52',
  modelType: 'PSAPPDEVIEW',
  name: 'MASTERcalendar_nav',
  id: 'web.master_calendar_nav',
};
