export default {
  enableDirtyChecking: true,
  showDataInfoBar: true,
  xdataControlName: 'form',
  loadDefault: true,
  deviewCodeName: 'data_picker_link',
  deviewId: 'cec732bb60be3e997faaf797d4e05b43',
  accUserMode: 3,
  capLanguageRes: {
    lanResTag: 'DE.LNAME.MASTER',
  },
  caption: '编辑器_数据选择（数据链接）',
  codeName: 'master_data_picker_link',
  appDataEntityId: 'web.master',
  appViewEngines: [
    {
      engineCat: 'VIEW',
      engineType: 'EditView',
      id: 'engine',
    },
  ],
  appViewMsgGroupId: 'data_picker_link',
  appViewNavContexts: [
    {
      rawValue: true,
      key: 'MASTER',
      value: 'sample',
      name: 'MASTER',
      id: 'master',
    },
  ],
  controls: [
    {
      xdataControlName: 'form',
      codeName: 'data_picker_link_toolbar',
      controlType: 'TOOLBAR',
      logicName: '编辑器_数据选择（数据链接）_工具栏',
      appDataEntityId: 'web.master',
      controlParam: {
        id: 'toolbar',
      },
      modelId: 'bc1846fb1e3e44d9e944e6589456bc77',
      modelType: 'PSDETOOLBAR',
      name: 'toolbar',
      id: 'data_picker_link_toolbar',
    },
    {
      createControlAction: {
        appDEMethodId: 'create',
        appDataEntityId: 'web.master',
        id: 'create',
      },
      getDraftFromControlAction: {
        appDataEntityId: 'web.master',
        id: 'loaddraftfrom',
      },
      getDraftControlAction: {
        appDEMethodId: 'get_draft',
        appDataEntityId: 'web.master',
        id: 'loaddraft',
      },
      getControlAction: {
        appDEMethodId: 'get_sample_date',
        appDataEntityId: 'web.master',
        id: 'load',
      },
      removeControlAction: {
        appDEMethodId: 'remove',
        appDataEntityId: 'web.master',
        id: 'remove',
      },
      updateControlAction: {
        appDEMethodId: 'update',
        appDataEntityId: 'web.master',
        id: 'update',
      },
      deformPages: [
        {
          layout: {
            columnCount: 24,
            layout: 'TABLE_24COL',
          },
          deformDetails: [
            {
              layout: {
                columnCount: 24,
                layout: 'TABLE_24COL',
              },
              deformDetails: [
                {
                  createDV: '中国',
                  dataType: 25,
                  enableCond: 3,
                  labelPos: 'NONE',
                  noPrivDisplayMode: 1,
                  editor: {
                    linkAppViewId: 'web.region_info_view',
                    enableLinkView: true,
                    singleSelect: true,
                    forceSelection: true,
                    valueItemName: 'formitem1',
                    editorParams: {
                      EDITABLE: 'FALSE',
                      LINKVIEW: 'TRUE',
                      AC: 'FALSE',
                      TRIGGER: 'FALSE',
                      PICKUPVIEW: 'FALSE',
                    },
                    editorType: 'PICKEREX_LINKONLY',
                    editorItems: [
                      {
                        id: 'formitem1',
                      },
                    ],
                    placeHolder: '数据链接',
                    valueType: 'SIMPLE',
                    id: 'formitem',
                  },
                  updateDV: '中国',
                  allowEmpty: true,
                  caption: '数据链接',
                  codeName: 'formitem',
                  detailStyle: 'DEFAULT',
                  detailType: 'FORMITEM',
                  layoutPos: {
                    colMD: 24,
                    layout: 'TABLE_24COL',
                  },
                  id: 'formitem',
                },
                {
                  createDV: '86',
                  dataType: 25,
                  enableCond: 3,
                  labelPos: 'LEFT',
                  labelWidth: 130,
                  noPrivDisplayMode: 1,
                  editor: {
                    editorType: 'HIDDEN',
                    valueType: 'SIMPLE',
                    editable: true,
                    id: 'formitem1',
                  },
                  updateDV: '86',
                  allowEmpty: true,
                  hidden: true,
                  codeName: 'formitem1',
                  detailStyle: 'DEFAULT',
                  detailType: 'FORMITEM',
                  layoutPos: {
                    colMD: 24,
                    layout: 'TABLE_24COL',
                  },
                  id: 'formitem1',
                },
              ],
              caption: '表单项',
              codeName: 'group1',
              detailStyle: 'DEFAULT',
              detailType: 'GROUPPANEL',
              layoutPos: {
                colMD: 24,
                layout: 'TABLE_24COL',
              },
              showCaption: true,
              id: 'group1',
            },
            {
              layout: {
                columnCount: 24,
                layout: 'TABLE_24COL',
              },
              deformDetails: [
                {
                  appViewId: 'web.master_grid_data_picker_link',
                  parentDataJO: {
                    srfparentdename: 'MASTER',
                    SRFPARENTTYPE: 'CUSTOM',
                  },
                  codeName: 'druipart1',
                  detailStyle: 'DEFAULT',
                  detailType: 'DRUIPART',
                  layoutPos: {
                    colMD: 24,
                    layout: 'TABLE_24COL',
                  },
                  showCaption: true,
                  id: 'druipart1',
                },
              ],
              caption: '表格列',
              codeName: 'grouppanel1',
              detailStyle: 'DEFAULT',
              detailType: 'GROUPPANEL',
              layoutPos: {
                colMD: 24,
                layout: 'TABLE_24COL',
              },
              showCaption: true,
              id: 'grouppanel1',
            },
            {
              dataType: 25,
              enableCond: 3,
              labelPos: 'LEFT',
              labelWidth: 130,
              noPrivDisplayMode: 1,
              appDEFieldId: 'id',
              editor: {
                editorType: 'HIDDEN',
                valueType: 'SIMPLE',
                editable: true,
                id: 'id',
              },
              allowEmpty: true,
              hidden: true,
              capLanguageRes: {
                lanResTag: 'DEF.LNAME.MASTER.ID',
              },
              caption: '标识',
              codeName: 'id',
              detailStyle: 'DEFAULT',
              detailType: 'FORMITEM',
              layoutPos: {
                colMD: 24,
                layout: 'TABLE_24COL',
              },
              id: 'id',
            },
          ],
          caption: '数据链接',
          codeName: 'formpage1',
          detailStyle: 'DEFAULT',
          detailType: 'FORMPAGE',
          id: 'formpage1',
        },
      ],
      layout: {
        columnCount: 24,
        layout: 'TABLE_24COL',
      },
      tabHeaderPos: 'TOP',
      noTabHeader: true,
      autoLoad: true,
      showBusyIndicator: true,
      codeName: 'main46',
      controlType: 'FORM',
      logicName: '编辑器_数据选择（数据链接）_表单',
      appDataEntityId: 'web.master',
      controlParam: {
        id: 'form',
      },
      modelId: 'b23974b2f3afca38ba2dc14836f87f67',
      modelType: 'PSDEFORM_EDITFORM',
      name: 'form',
      id: 'web.master.main46',
    },
    {
      codeName: 'data_picker_link_datainfobar',
      controlType: 'DATAINFOBAR',
      appDataEntityId: 'web.master',
      controlParam: {
        id: 'datainfobar',
      },
      name: 'datainfobar',
      id: 'data_picker_link_datainfobar',
    },
    {
      capLanguageRes: {
        lanResTag: 'DE.LNAME.MASTER',
      },
      caption: '编辑器_数据选择（数据链接）',
      codeName: 'data_picker_link_captionbar',
      controlType: 'CAPTIONBAR',
      appDataEntityId: 'web.master',
      controlParam: {},
      name: 'captionbar',
      id: 'data_picker_link_captionbar',
    },
  ],
  viewLayoutPanel: {
    layoutBodyOnly: true,
    useDefaultLayout: true,
    layoutPanel: true,
    codeName: 'layoutpanel',
    controlStyle: 'APPDEEDITVIEW',
    controlType: 'VIEWLAYOUTPANEL',
    appDataEntityId: 'web.master',
    controlParam: {},
    id: 'layoutpanel',
  },
  title: '编辑器_数据选择（数据链接）',
  viewStyle: 'DEFAULT',
  viewType: 'DEEDITVIEW',
  enableDP: true,
  showCaptionBar: false,
  modelId: '2cb22e5259ddae39e23accc0ac170a11',
  modelType: 'PSAPPDEVIEW',
  name: 'MASTERdata_picker_link',
  id: 'web.master_data_picker_link',
};
