export default {
  deviewCodeName: 'ui_action_cssandicon',
  deviewId: 'ae0acf387e80d14a3860dd02aab64900',
  accUserMode: 3,
  capLanguageRes: {
    lanResTag: 'DE.LNAME.MASTER',
  },
  caption: '界面行为_样式及图标',
  codeName: 'master_ui_action_cssandicon',
  appDataEntityId: 'web.master',
  appViewMsgGroupId: 'ui_action_cssandicon',
  viewLayoutPanel: {
    layoutBodyOnly: true,
    viewProxyMode: true,
    layoutMode: 'FLEX',
    layout: {
      layout: 'FLEX',
    },
    rootPanelItems: [
      {
        actionGroupExtractMode: 'ITEM',
        panelItems: [
          {
            actionGroupExtractMode: 'ITEM',
            buttonListType: 'UIACTIONGROUP',
            uiactionGroup: {
              uiactionGroupDetails: [
                {
                  actionLevel: 100,
                  afterItemType: 'NONE',
                  beforeItemType: 'NONE',
                  buttonStyle: 'INVERSE',
                  caption: '打开视图',
                  detailType: 'DEUIACTION',
                  uiactionId: 'open_view6@master',
                  showCaption: true,
                  showIcon: true,
                  sysImage: {
                    cssClass: 'fa fa-lightbulb-o',
                    glyph: 'xf0eb@FontAwesome',
                  },
                  id: 'u3661b94',
                },
                {
                  actionLevel: 100,
                  afterItemType: 'NONE',
                  beforeItemType: 'NONE',
                  buttonStyle: 'DANGER',
                  caption: '打开视图',
                  detailType: 'DEUIACTION',
                  uiactionId: 'open_view5@master',
                  showCaption: true,
                  showIcon: true,
                  sysImage: {
                    cssClass: 'fa fa-exclamation',
                    glyph: 'xf12a@FontAwesome',
                  },
                  id: 'uf4d2990',
                },
                {
                  actionLevel: 100,
                  afterItemType: 'NONE',
                  beforeItemType: 'NONE',
                  buttonStyle: 'WARNING',
                  caption: '打开视图',
                  detailType: 'DEUIACTION',
                  uiactionId: 'open_view4@master',
                  showCaption: true,
                  showIcon: true,
                  sysImage: {
                    cssClass: 'fa fa-send-o',
                    glyph: 'xf1d9@FontAwesome',
                  },
                  id: 'u20b0cfe',
                },
                {
                  actionLevel: 100,
                  afterItemType: 'NONE',
                  beforeItemType: 'NONE',
                  buttonStyle: 'INFO',
                  caption: '打开视图',
                  detailType: 'DEUIACTION',
                  uiactionId: 'open_view2@master',
                  showCaption: true,
                  showIcon: true,
                  sysImage: {
                    cssClass: 'fa fa-cube',
                    glyph: 'xf1b2@FontAwesome',
                  },
                  id: 'uab86613',
                },
                {
                  actionLevel: 100,
                  afterItemType: 'NONE',
                  beforeItemType: 'NONE',
                  buttonStyle: 'SUCCESS',
                  caption: '打开视图',
                  detailType: 'DEUIACTION',
                  uiactionId: 'open_view3@master',
                  showCaption: true,
                  showIcon: true,
                  sysImage: {
                    cssClass: 'cloudy',
                  },
                  id: 'u09de2c3',
                },
                {
                  actionLevel: 100,
                  afterItemType: 'NONE',
                  beforeItemType: 'NONE',
                  buttonStyle: 'PRIMARY',
                  caption: '打开视图',
                  detailType: 'DEUIACTION',
                  uiactionId: 'open_view1@master',
                  showCaption: true,
                  showIcon: true,
                  sysImage: {
                    cssClass: 'fa fa-google',
                    glyph: 'xf1a0@FontAwesome',
                  },
                  id: 'u0ebc904',
                },
              ],
              appDataEntityId: 'web.master',
              uniqueTag: 'master__Ac5c6ca354b8a3b6605',
              name: '界面行为样式及图标',
              id: 'ac5c6ca354b8a3b6605',
            },
            caption: '按钮组',
            itemStyle: 'DEFAULT',
            itemType: 'BUTTONLIST',
            layoutPos: {
              shrink: 1,
              layout: 'FLEX',
            },
            id: 'buttonlist',
          },
        ],
        layout: {
          layout: 'FLEX',
        },
        dataRegionType: 'INHERIT',
        caption: '容器',
        itemStyle: 'DEFAULT',
        itemType: 'CONTAINER',
        layoutPos: {
          shrink: 1,
          layout: 'FLEX',
          spacingBottom: 'OUTERLARGE',
          spacingLeft: 'OUTERLARGE',
          spacingRight: 'OUTERLARGE',
          spacingTop: 'OUTERLARGE',
        },
        id: 'container',
      },
    ],
    layoutPanel: true,
    controls: [
      {
        capLanguageRes: {
          lanResTag: 'DE.LNAME.MASTER',
        },
        caption: '界面行为_样式及图标',
        codeName: 'ui_action_cssandicon_captionbar',
        controlType: 'CAPTIONBAR',
        appDataEntityId: 'web.master',
        controlParam: {},
        name: 'captionbar',
        id: 'ui_action_cssandicon_captionbar',
      },
    ],
    codeName: 'a5d89ddf07744d926f9',
    controlType: 'VIEWLAYOUTPANEL',
    logicName: 'ui_action_cssandicon',
    appDataEntityId: 'web.master',
    controlParam: {},
    modelId: '93056d30387455d68414b7f90c80d1a3',
    modelType: 'PSSYSVIEWLAYOUTPANEL',
    name: 'layoutpanel',
    id: 'a5d89ddf07744d926f9',
  },
  title: '界面行为_样式及图标',
  viewStyle: 'DEFAULT',
  viewType: 'DECUSTOMVIEW',
  enableDP: true,
  showCaptionBar: true,
  modelId: '8e435ccacc5b10cafb75e98bafe5ec08',
  modelType: 'PSAPPDEVIEW',
  name: 'MASTERui_action_cssandicon',
  id: 'web.master_ui_action_cssandicon',
};
