export default {
  enableDirtyChecking: true,
  showDataInfoBar: true,
  xdataControlName: 'form',
  loadDefault: true,
  deviewCodeName: 'form_layout',
  deviewId: '06a64fd15ae48779b6ee07fc8ec9ff07',
  accUserMode: 3,
  capLanguageRes: {
    lanResTag: 'DE.LNAME.MASTER',
  },
  caption: '编辑表单_布局',
  codeName: 'master_form_layout',
  appDataEntityId: 'web.master',
  appViewEngines: [
    {
      engineCat: 'VIEW',
      engineType: 'EditView',
      id: 'engine',
    },
  ],
  appViewMsgGroupId: 'form_layout',
  appViewNavContexts: [
    {
      rawValue: true,
      key: 'MASTER',
      value: 'sample',
      name: 'MASTER',
      id: 'master',
    },
  ],
  controls: [
    {
      xdataControlName: 'form',
      codeName: 'form_layout_toolbar',
      controlType: 'TOOLBAR',
      logicName: '编辑表单_布局_工具栏',
      appDataEntityId: 'web.master',
      controlParam: {
        id: 'toolbar',
      },
      modelId: '655990424f6036617ba15047d060b071',
      modelType: 'PSDETOOLBAR',
      name: 'toolbar',
      id: 'form_layout_toolbar',
    },
    {
      createControlAction: {
        appDEMethodId: 'create',
        appDataEntityId: 'web.master',
        id: 'create',
      },
      getDraftFromControlAction: {
        appDataEntityId: 'web.master',
        id: 'loaddraftfrom',
      },
      getDraftControlAction: {
        appDEMethodId: 'get_draft',
        appDataEntityId: 'web.master',
        id: 'loaddraft',
      },
      getControlAction: {
        appDEMethodId: 'get_sample_date',
        appDataEntityId: 'web.master',
        id: 'load',
      },
      removeControlAction: {
        appDEMethodId: 'remove',
        appDataEntityId: 'web.master',
        id: 'remove',
      },
      updateControlAction: {
        appDEMethodId: 'update',
        appDataEntityId: 'web.master',
        id: 'update',
      },
      deformPages: [
        {
          layout: {
            columnCount: 24,
            layout: 'TABLE_24COL',
          },
          deformDetails: [
            {
              layout: {
                columnCount: 24,
                layout: 'TABLE_24COL',
              },
              deformDetails: [
                {
                  layout: {
                    columnCount: 24,
                    layout: 'TABLE_24COL',
                  },
                  deformDetails: [
                    {
                      rawItem: {
                        caption: '1',
                        halign: 'LEFT',
                        valign: 'MIDDLE',
                        wrapMode: 'NOWRAP',
                        contentType: 'RAW',
                        sysCss: {
                          cssName: 'el-alert el-alert--warning is-light',
                        },
                        id: 'rawitem1',
                      },
                      codeName: 'rawitem1',
                      detailStyle: 'DEFAULT',
                      detailType: 'RAWITEM',
                      layoutPos: {
                        colLG: 1,
                        colMD: 24,
                        layout: 'TABLE_24COL',
                      },
                      sysCss: {
                        cssName: 'el-alert el-alert--warning is-light',
                      },
                      showCaption: true,
                      id: 'rawitem1',
                    },
                    {
                      rawItem: {
                        caption: '1',
                        halign: 'LEFT',
                        valign: 'MIDDLE',
                        wrapMode: 'NOWRAP',
                        contentType: 'RAW',
                        sysCss: {
                          cssName: 'el-alert el-alert--success is-light',
                        },
                        id: 'rawitem2',
                      },
                      codeName: 'rawitem2',
                      detailStyle: 'DEFAULT',
                      detailType: 'RAWITEM',
                      layoutPos: {
                        colLG: 1,
                        colMD: 24,
                        layout: 'TABLE_24COL',
                      },
                      sysCss: {
                        cssName: 'el-alert el-alert--success is-light',
                      },
                      showCaption: true,
                      id: 'rawitem2',
                    },
                  ],
                  caption: '分组面板',
                  codeName: 'grouppanel1',
                  detailStyle: 'DEFAULT',
                  detailType: 'GROUPPANEL',
                  layoutPos: {
                    colMD: 24,
                    layout: 'TABLE_24COL',
                  },
                  id: 'grouppanel1',
                },
                {
                  layout: {
                    columnCount: 24,
                    layout: 'TABLE_24COL',
                  },
                  deformDetails: [
                    {
                      rawItem: {
                        caption: '4',
                        halign: 'LEFT',
                        valign: 'MIDDLE',
                        wrapMode: 'NOWRAP',
                        contentType: 'RAW',
                        sysCss: {
                          cssName: 'el-alert el-alert--warning is-light',
                        },
                        id: 'rawitem3',
                      },
                      codeName: 'rawitem3',
                      detailStyle: 'DEFAULT',
                      detailType: 'RAWITEM',
                      layoutPos: {
                        colLG: 4,
                        colMD: 24,
                        layout: 'TABLE_24COL',
                      },
                      sysCss: {
                        cssName: 'el-alert el-alert--warning is-light',
                      },
                      showCaption: true,
                      id: 'rawitem3',
                    },
                    {
                      rawItem: {
                        caption: '4',
                        halign: 'LEFT',
                        valign: 'MIDDLE',
                        wrapMode: 'NOWRAP',
                        contentType: 'RAW',
                        sysCss: {
                          cssName: 'el-alert el-alert--success is-light',
                        },
                        id: 'rawitem4',
                      },
                      codeName: 'rawitem4',
                      detailStyle: 'DEFAULT',
                      detailType: 'RAWITEM',
                      layoutPos: {
                        colLG: 4,
                        colMD: 24,
                        layout: 'TABLE_24COL',
                      },
                      sysCss: {
                        cssName: 'el-alert el-alert--success is-light',
                      },
                      showCaption: true,
                      id: 'rawitem4',
                    },
                  ],
                  caption: '分组面板',
                  codeName: 'grouppanel2',
                  detailStyle: 'DEFAULT',
                  detailType: 'GROUPPANEL',
                  layoutPos: {
                    colMD: 24,
                    layout: 'TABLE_24COL',
                  },
                  id: 'grouppanel2',
                },
                {
                  layout: {
                    columnCount: 24,
                    layout: 'TABLE_24COL',
                  },
                  deformDetails: [
                    {
                      rawItem: {
                        caption: '8',
                        halign: 'LEFT',
                        valign: 'MIDDLE',
                        wrapMode: 'NOWRAP',
                        contentType: 'RAW',
                        sysCss: {
                          cssName: 'el-alert el-alert--warning is-light',
                        },
                        id: 'rawitem5',
                      },
                      codeName: 'rawitem5',
                      detailStyle: 'DEFAULT',
                      detailType: 'RAWITEM',
                      layoutPos: {
                        colLG: 8,
                        colMD: 24,
                        layout: 'TABLE_24COL',
                      },
                      sysCss: {
                        cssName: 'el-alert el-alert--warning is-light',
                      },
                      showCaption: true,
                      id: 'rawitem5',
                    },
                    {
                      rawItem: {
                        caption: '8',
                        halign: 'LEFT',
                        valign: 'MIDDLE',
                        wrapMode: 'NOWRAP',
                        contentType: 'RAW',
                        sysCss: {
                          cssName: 'el-alert el-alert--success is-light',
                        },
                        id: 'rawitem6',
                      },
                      codeName: 'rawitem6',
                      detailStyle: 'DEFAULT',
                      detailType: 'RAWITEM',
                      layoutPos: {
                        colLG: 8,
                        colMD: 24,
                        layout: 'TABLE_24COL',
                      },
                      sysCss: {
                        cssName: 'el-alert el-alert--success is-light',
                      },
                      showCaption: true,
                      id: 'rawitem6',
                    },
                  ],
                  caption: '分组面板',
                  codeName: 'grouppanel3',
                  detailStyle: 'DEFAULT',
                  detailType: 'GROUPPANEL',
                  layoutPos: {
                    colMD: 24,
                    layout: 'TABLE_24COL',
                  },
                  id: 'grouppanel3',
                },
                {
                  layout: {
                    columnCount: 24,
                    layout: 'TABLE_24COL',
                  },
                  deformDetails: [
                    {
                      rawItem: {
                        caption: '12',
                        halign: 'LEFT',
                        valign: 'MIDDLE',
                        wrapMode: 'NOWRAP',
                        contentType: 'RAW',
                        sysCss: {
                          cssName: 'el-alert el-alert--warning is-light',
                        },
                        id: 'rawitem7',
                      },
                      codeName: 'rawitem7',
                      detailStyle: 'DEFAULT',
                      detailType: 'RAWITEM',
                      layoutPos: {
                        colLG: 12,
                        colMD: 24,
                        layout: 'TABLE_24COL',
                      },
                      sysCss: {
                        cssName: 'el-alert el-alert--warning is-light',
                      },
                      showCaption: true,
                      id: 'rawitem7',
                    },
                    {
                      rawItem: {
                        caption: '12',
                        halign: 'LEFT',
                        valign: 'MIDDLE',
                        wrapMode: 'NOWRAP',
                        contentType: 'RAW',
                        sysCss: {
                          cssName: 'el-alert el-alert--success is-light',
                        },
                        id: 'rawitem8',
                      },
                      codeName: 'rawitem8',
                      detailStyle: 'DEFAULT',
                      detailType: 'RAWITEM',
                      layoutPos: {
                        colLG: 12,
                        colMD: 24,
                        layout: 'TABLE_24COL',
                      },
                      sysCss: {
                        cssName: 'el-alert el-alert--success is-light',
                      },
                      showCaption: true,
                      id: 'rawitem8',
                    },
                  ],
                  caption: '分组面板',
                  codeName: 'grouppanel4',
                  detailStyle: 'DEFAULT',
                  detailType: 'GROUPPANEL',
                  layoutPos: {
                    colMD: 24,
                    layout: 'TABLE_24COL',
                  },
                  id: 'grouppanel4',
                },
                {
                  layout: {
                    columnCount: 24,
                    layout: 'TABLE_24COL',
                  },
                  deformDetails: [
                    {
                      rawItem: {
                        caption: '24',
                        halign: 'LEFT',
                        valign: 'MIDDLE',
                        wrapMode: 'NOWRAP',
                        contentType: 'RAW',
                        sysCss: {
                          cssName: 'el-alert el-alert--warning is-light',
                        },
                        id: 'rawitem9',
                      },
                      codeName: 'rawitem9',
                      detailStyle: 'DEFAULT',
                      detailType: 'RAWITEM',
                      layoutPos: {
                        colLG: 24,
                        colMD: 24,
                        layout: 'TABLE_24COL',
                      },
                      sysCss: {
                        cssName: 'el-alert el-alert--warning is-light',
                      },
                      showCaption: true,
                      id: 'rawitem9',
                    },
                  ],
                  caption: '分组面板',
                  codeName: 'grouppanel5',
                  detailStyle: 'DEFAULT',
                  detailType: 'GROUPPANEL',
                  layoutPos: {
                    colMD: 24,
                    layout: 'TABLE_24COL',
                  },
                  id: 'grouppanel5',
                },
                {
                  layout: {
                    columnCount: 24,
                    layout: 'TABLE_24COL',
                  },
                  deformDetails: [
                    {
                      rawItem: {
                        caption: '4（偏移1）',
                        halign: 'LEFT',
                        valign: 'MIDDLE',
                        wrapMode: 'NOWRAP',
                        contentType: 'RAW',
                        sysCss: {
                          cssName: 'el-alert el-alert--warning is-light',
                        },
                        id: 'rawitem10',
                      },
                      codeName: 'rawitem10',
                      detailStyle: 'DEFAULT',
                      detailType: 'RAWITEM',
                      layoutPos: {
                        colLG: 4,
                        colLGOffset: 1,
                        colMD: 24,
                        layout: 'TABLE_24COL',
                      },
                      sysCss: {
                        cssName: 'el-alert el-alert--warning is-light',
                      },
                      showCaption: true,
                      id: 'rawitem10',
                    },
                    {
                      rawItem: {
                        caption: '12（偏移7）',
                        halign: 'LEFT',
                        valign: 'MIDDLE',
                        wrapMode: 'NOWRAP',
                        contentType: 'RAW',
                        sysCss: {
                          cssName: 'el-alert el-alert--success is-light',
                        },
                        id: 'rawitem11',
                      },
                      codeName: 'rawitem11',
                      detailStyle: 'DEFAULT',
                      detailType: 'RAWITEM',
                      layoutPos: {
                        colLG: 12,
                        colLGOffset: 7,
                        colMD: 24,
                        layout: 'TABLE_24COL',
                      },
                      sysCss: {
                        cssName: 'el-alert el-alert--success is-light',
                      },
                      showCaption: true,
                      id: 'rawitem11',
                    },
                  ],
                  caption: '偏移',
                  codeName: 'grouppanel6',
                  detailStyle: 'DEFAULT',
                  detailType: 'GROUPPANEL',
                  layoutPos: {
                    colMD: 24,
                    layout: 'TABLE_24COL',
                  },
                  id: 'grouppanel6',
                },
                {
                  layout: {
                    columnCount: 24,
                    layout: 'TABLE_24COL',
                  },
                  deformDetails: [
                    {
                      rawItem: {
                        caption: '12（100*100）',
                        halign: 'LEFT',
                        valign: 'MIDDLE',
                        wrapMode: 'NOWRAP',
                        contentType: 'RAW',
                        sysCss: {
                          cssName: 'el-alert el-alert--warning is-light',
                        },
                        rawItemHeight: 100,
                        rawItemWidth: 100,
                        id: 'rawitem12',
                      },
                      codeName: 'rawitem12',
                      contentHeight: 100,
                      contentWidth: 100,
                      detailStyle: 'DEFAULT',
                      detailType: 'RAWITEM',
                      height: 100,
                      layoutPos: {
                        colLG: 12,
                        colMD: 24,
                        height: 100,
                        heightMode: 'PX',
                        layout: 'TABLE_24COL',
                        width: 100,
                        widthMode: 'PX',
                      },
                      sysCss: {
                        cssName: 'el-alert el-alert--warning is-light',
                      },
                      width: 100,
                      showCaption: true,
                      id: 'rawitem12',
                    },
                  ],
                  caption: '定高宽',
                  codeName: 'grouppanel8',
                  detailStyle: 'DEFAULT',
                  detailType: 'GROUPPANEL',
                  layoutPos: {
                    colMD: 24,
                    layout: 'TABLE_24COL',
                  },
                  id: 'grouppanel8',
                },
              ],
              enableAnchor: true,
              caption: '栅格布局',
              codeName: 'group1',
              detailStyle: 'DEFAULT',
              detailType: 'GROUPPANEL',
              layoutPos: {
                colMD: 24,
                layout: 'TABLE_24COL',
              },
              id: 'group1',
            },
            {
              dataType: 25,
              enableCond: 3,
              labelPos: 'LEFT',
              labelWidth: 130,
              noPrivDisplayMode: 1,
              appDEFieldId: 'id',
              editor: {
                editorType: 'HIDDEN',
                valueType: 'SIMPLE',
                editable: true,
                id: 'id',
              },
              allowEmpty: true,
              hidden: true,
              capLanguageRes: {
                lanResTag: 'DEF.LNAME.MASTER.ID',
              },
              caption: '标识',
              codeName: 'id',
              detailStyle: 'DEFAULT',
              detailType: 'FORMITEM',
              layoutPos: {
                colMD: 24,
                layout: 'TABLE_24COL',
              },
              id: 'id',
            },
          ],
          caption: '栅格布局',
          codeName: 'formpage1',
          detailStyle: 'DEFAULT',
          detailType: 'FORMPAGE',
          id: 'formpage1',
        },
        {
          layout: {
            columnCount: 24,
            layout: 'TABLE_24COL',
          },
          deformDetails: [
            {
              layout: {
                columnCount: 24,
                layout: 'TABLE_24COL',
              },
              deformDetails: [
                {
                  layout: {
                    dir: 'column',
                    layout: 'FLEX',
                  },
                  deformDetails: [
                    {
                      rawItem: {
                        caption: 'A',
                        halign: 'LEFT',
                        valign: 'MIDDLE',
                        wrapMode: 'NOWRAP',
                        contentType: 'RAW',
                        sysCss: {
                          cssName: 'el-alert el-alert--warning is-light',
                        },
                        rawItemHeight: 100,
                        rawItemWidth: 100,
                        id: 'rawitem14',
                      },
                      codeName: 'rawitem14',
                      detailStyle: 'DEFAULT',
                      detailType: 'RAWITEM',
                      layoutPos: {
                        shrink: 1,
                        height: 100,
                        heightMode: 'PX',
                        layout: 'FLEX',
                        width: 100,
                        widthMode: 'PX',
                      },
                      sysCss: {
                        cssName: 'el-alert el-alert--warning is-light',
                      },
                      showCaption: true,
                      id: 'rawitem14',
                    },
                    {
                      rawItem: {
                        caption: 'B',
                        halign: 'LEFT',
                        valign: 'MIDDLE',
                        wrapMode: 'NOWRAP',
                        contentType: 'RAW',
                        sysCss: {
                          cssName: 'el-alert el-alert--success is-light',
                        },
                        rawItemHeight: 100,
                        rawItemWidth: 100,
                        id: 'rawitem15',
                      },
                      codeName: 'rawitem15',
                      detailStyle: 'DEFAULT',
                      detailType: 'RAWITEM',
                      layoutPos: {
                        shrink: 1,
                        height: 100,
                        heightMode: 'PX',
                        layout: 'FLEX',
                        width: 100,
                        widthMode: 'PX',
                      },
                      sysCss: {
                        cssName: 'el-alert el-alert--success is-light',
                      },
                      showCaption: true,
                      id: 'rawitem15',
                    },
                    {
                      rawItem: {
                        caption: 'C',
                        halign: 'LEFT',
                        valign: 'MIDDLE',
                        wrapMode: 'NOWRAP',
                        contentType: 'RAW',
                        sysCss: {
                          cssName: 'el-alert el-alert--info is-light',
                        },
                        rawItemHeight: 100,
                        rawItemWidth: 100,
                        id: 'rawitem16',
                      },
                      codeName: 'rawitem16',
                      detailStyle: 'DEFAULT',
                      detailType: 'RAWITEM',
                      layoutPos: {
                        shrink: 1,
                        height: 100,
                        heightMode: 'PX',
                        layout: 'FLEX',
                        width: 100,
                        widthMode: 'PX',
                      },
                      sysCss: {
                        cssName: 'el-alert el-alert--info is-light',
                      },
                      showCaption: true,
                      id: 'rawitem16',
                    },
                  ],
                  caption: 'Flex从上到下',
                  codeName: 'grouppanel10',
                  detailStyle: 'DEFAULT',
                  detailType: 'GROUPPANEL',
                  layoutPos: {
                    colLG: 12,
                    colMD: 24,
                    layout: 'TABLE_24COL',
                  },
                  showCaption: true,
                  id: 'grouppanel10',
                },
                {
                  layout: {
                    dir: 'column-reverse',
                    layout: 'FLEX',
                  },
                  deformDetails: [
                    {
                      rawItem: {
                        caption: 'A',
                        halign: 'LEFT',
                        valign: 'MIDDLE',
                        wrapMode: 'NOWRAP',
                        contentType: 'RAW',
                        sysCss: {
                          cssName: 'el-alert el-alert--warning is-light',
                        },
                        rawItemHeight: 100,
                        rawItemWidth: 100,
                        id: 'rawitem17',
                      },
                      codeName: 'rawitem17',
                      detailStyle: 'DEFAULT',
                      detailType: 'RAWITEM',
                      layoutPos: {
                        shrink: 1,
                        height: 100,
                        heightMode: 'PX',
                        layout: 'FLEX',
                        width: 100,
                        widthMode: 'PX',
                      },
                      sysCss: {
                        cssName: 'el-alert el-alert--warning is-light',
                      },
                      showCaption: true,
                      id: 'rawitem17',
                    },
                    {
                      rawItem: {
                        caption: 'B',
                        halign: 'LEFT',
                        valign: 'MIDDLE',
                        wrapMode: 'NOWRAP',
                        contentType: 'RAW',
                        sysCss: {
                          cssName: 'el-alert el-alert--success is-light',
                        },
                        rawItemHeight: 100,
                        rawItemWidth: 100,
                        id: 'rawitem18',
                      },
                      codeName: 'rawitem18',
                      detailStyle: 'DEFAULT',
                      detailType: 'RAWITEM',
                      layoutPos: {
                        shrink: 1,
                        height: 100,
                        heightMode: 'PX',
                        layout: 'FLEX',
                        width: 100,
                        widthMode: 'PX',
                      },
                      sysCss: {
                        cssName: 'el-alert el-alert--success is-light',
                      },
                      showCaption: true,
                      id: 'rawitem18',
                    },
                    {
                      rawItem: {
                        caption: 'C',
                        halign: 'LEFT',
                        valign: 'MIDDLE',
                        wrapMode: 'NOWRAP',
                        contentType: 'RAW',
                        sysCss: {
                          cssName: 'el-alert el-alert--info is-light',
                        },
                        rawItemHeight: 100,
                        rawItemWidth: 100,
                        id: 'rawitem19',
                      },
                      codeName: 'rawitem19',
                      detailStyle: 'DEFAULT',
                      detailType: 'RAWITEM',
                      layoutPos: {
                        shrink: 1,
                        height: 100,
                        heightMode: 'PX',
                        layout: 'FLEX',
                        width: 100,
                        widthMode: 'PX',
                      },
                      sysCss: {
                        cssName: 'el-alert el-alert--info is-light',
                      },
                      showCaption: true,
                      id: 'rawitem19',
                    },
                  ],
                  caption: 'Flex从下到上',
                  codeName: 'grouppanel12',
                  detailStyle: 'DEFAULT',
                  detailType: 'GROUPPANEL',
                  layoutPos: {
                    colLG: 12,
                    colMD: 24,
                    layout: 'TABLE_24COL',
                  },
                  showCaption: true,
                  id: 'grouppanel12',
                },
                {
                  layout: {
                    dir: 'row',
                    layout: 'FLEX',
                  },
                  deformDetails: [
                    {
                      rawItem: {
                        caption: 'A',
                        halign: 'LEFT',
                        valign: 'MIDDLE',
                        wrapMode: 'NOWRAP',
                        contentType: 'RAW',
                        sysCss: {
                          cssName: 'el-alert el-alert--warning is-light',
                        },
                        rawItemHeight: 100,
                        rawItemWidth: 100,
                        id: 'rawitem20',
                      },
                      codeName: 'rawitem20',
                      detailStyle: 'DEFAULT',
                      detailType: 'RAWITEM',
                      layoutPos: {
                        shrink: 1,
                        height: 100,
                        heightMode: 'PX',
                        layout: 'FLEX',
                        width: 100,
                        widthMode: 'PX',
                      },
                      sysCss: {
                        cssName: 'el-alert el-alert--warning is-light',
                      },
                      showCaption: true,
                      id: 'rawitem20',
                    },
                    {
                      rawItem: {
                        caption: 'B',
                        halign: 'LEFT',
                        valign: 'MIDDLE',
                        wrapMode: 'NOWRAP',
                        contentType: 'RAW',
                        sysCss: {
                          cssName: 'el-alert el-alert--success is-light',
                        },
                        rawItemHeight: 100,
                        rawItemWidth: 100,
                        id: 'rawitem21',
                      },
                      codeName: 'rawitem21',
                      detailStyle: 'DEFAULT',
                      detailType: 'RAWITEM',
                      layoutPos: {
                        shrink: 1,
                        height: 100,
                        heightMode: 'PX',
                        layout: 'FLEX',
                        width: 100,
                        widthMode: 'PX',
                      },
                      sysCss: {
                        cssName: 'el-alert el-alert--success is-light',
                      },
                      showCaption: true,
                      id: 'rawitem21',
                    },
                    {
                      rawItem: {
                        caption: 'C',
                        halign: 'LEFT',
                        valign: 'MIDDLE',
                        wrapMode: 'NOWRAP',
                        contentType: 'RAW',
                        sysCss: {
                          cssName: 'el-alert el-alert--info is-light',
                        },
                        rawItemHeight: 100,
                        rawItemWidth: 100,
                        id: 'rawitem22',
                      },
                      codeName: 'rawitem22',
                      detailStyle: 'DEFAULT',
                      detailType: 'RAWITEM',
                      layoutPos: {
                        shrink: 1,
                        height: 100,
                        heightMode: 'PX',
                        layout: 'FLEX',
                        width: 100,
                        widthMode: 'PX',
                      },
                      sysCss: {
                        cssName: 'el-alert el-alert--info is-light',
                      },
                      showCaption: true,
                      id: 'rawitem22',
                    },
                  ],
                  caption: 'Flex水平向左',
                  codeName: 'grouppanel13',
                  contentHeight: 184,
                  detailStyle: 'DEFAULT',
                  detailType: 'GROUPPANEL',
                  height: 200,
                  layoutPos: {
                    colLG: 12,
                    colMD: 24,
                    height: 200,
                    heightMode: 'PX',
                    layout: 'TABLE_24COL',
                  },
                  showCaption: true,
                  id: 'grouppanel13',
                },
                {
                  layout: {
                    dir: 'row-reverse',
                    layout: 'FLEX',
                  },
                  deformDetails: [
                    {
                      rawItem: {
                        caption: 'A',
                        halign: 'LEFT',
                        valign: 'MIDDLE',
                        wrapMode: 'NOWRAP',
                        contentType: 'RAW',
                        sysCss: {
                          cssName: 'el-alert el-alert--warning is-light',
                        },
                        rawItemHeight: 100,
                        rawItemWidth: 100,
                        id: 'rawitem23',
                      },
                      codeName: 'rawitem23',
                      detailStyle: 'DEFAULT',
                      detailType: 'RAWITEM',
                      layoutPos: {
                        shrink: 1,
                        height: 100,
                        heightMode: 'PX',
                        layout: 'FLEX',
                        width: 100,
                        widthMode: 'PX',
                      },
                      sysCss: {
                        cssName: 'el-alert el-alert--warning is-light',
                      },
                      showCaption: true,
                      id: 'rawitem23',
                    },
                    {
                      rawItem: {
                        caption: 'B',
                        halign: 'LEFT',
                        valign: 'MIDDLE',
                        wrapMode: 'NOWRAP',
                        contentType: 'RAW',
                        sysCss: {
                          cssName: 'el-alert el-alert--success is-light',
                        },
                        id: 'rawitem24',
                      },
                      codeName: 'rawitem24',
                      detailStyle: 'DEFAULT',
                      detailType: 'RAWITEM',
                      layoutPos: {
                        shrink: 1,
                        height: 100,
                        heightMode: 'PX',
                        layout: 'FLEX',
                        width: 100,
                        widthMode: 'PX',
                      },
                      sysCss: {
                        cssName: 'el-alert el-alert--success is-light',
                      },
                      showCaption: true,
                      id: 'rawitem24',
                    },
                    {
                      rawItem: {
                        caption: 'C',
                        halign: 'LEFT',
                        valign: 'MIDDLE',
                        wrapMode: 'NOWRAP',
                        contentType: 'RAW',
                        sysCss: {
                          cssName: 'el-alert el-alert--info is-light',
                        },
                        rawItemHeight: 100,
                        rawItemWidth: 100,
                        id: 'rawitem25',
                      },
                      codeName: 'rawitem25',
                      detailStyle: 'DEFAULT',
                      detailType: 'RAWITEM',
                      layoutPos: {
                        shrink: 1,
                        height: 100,
                        heightMode: 'PX',
                        layout: 'FLEX',
                        width: 100,
                        widthMode: 'PX',
                      },
                      sysCss: {
                        cssName: 'el-alert el-alert--info is-light',
                      },
                      showCaption: true,
                      id: 'rawitem25',
                    },
                  ],
                  caption: 'Flex水平向右',
                  codeName: 'grouppanel14',
                  contentHeight: 184,
                  detailStyle: 'DEFAULT',
                  detailType: 'GROUPPANEL',
                  height: 200,
                  layoutPos: {
                    colLG: 12,
                    colMD: 24,
                    height: 200,
                    heightMode: 'PX',
                    layout: 'TABLE_24COL',
                  },
                  showCaption: true,
                  id: 'grouppanel14',
                },
                {
                  layout: {
                    align: 'center',
                    layout: 'FLEX',
                  },
                  deformDetails: [
                    {
                      rawItem: {
                        caption: 'A',
                        halign: 'LEFT',
                        valign: 'MIDDLE',
                        wrapMode: 'NOWRAP',
                        contentType: 'RAW',
                        sysCss: {
                          cssName: 'el-alert el-alert--warning is-light',
                        },
                        rawItemHeight: 100,
                        rawItemWidth: 100,
                        id: 'rawitem26',
                      },
                      codeName: 'rawitem26',
                      detailStyle: 'DEFAULT',
                      detailType: 'RAWITEM',
                      layoutPos: {
                        shrink: 1,
                        height: 100,
                        heightMode: 'PX',
                        layout: 'FLEX',
                        width: 100,
                        widthMode: 'PX',
                      },
                      sysCss: {
                        cssName: 'el-alert el-alert--warning is-light',
                      },
                      showCaption: true,
                      id: 'rawitem26',
                    },
                    {
                      rawItem: {
                        caption: 'B',
                        halign: 'LEFT',
                        valign: 'MIDDLE',
                        wrapMode: 'NOWRAP',
                        contentType: 'RAW',
                        sysCss: {
                          cssName: 'el-alert el-alert--success is-light',
                        },
                        rawItemHeight: 100,
                        rawItemWidth: 100,
                        id: 'rawitem27',
                      },
                      codeName: 'rawitem27',
                      detailStyle: 'DEFAULT',
                      detailType: 'RAWITEM',
                      layoutPos: {
                        shrink: 1,
                        height: 100,
                        heightMode: 'PX',
                        layout: 'FLEX',
                        width: 100,
                        widthMode: 'PX',
                      },
                      sysCss: {
                        cssName: 'el-alert el-alert--success is-light',
                      },
                      showCaption: true,
                      id: 'rawitem27',
                    },
                    {
                      rawItem: {
                        caption: 'C',
                        halign: 'LEFT',
                        valign: 'MIDDLE',
                        wrapMode: 'NOWRAP',
                        contentType: 'RAW',
                        sysCss: {
                          cssName: 'el-alert el-alert--info is-light',
                        },
                        rawItemHeight: 100,
                        rawItemWidth: 100,
                        id: 'rawitem28',
                      },
                      codeName: 'rawitem28',
                      detailStyle: 'DEFAULT',
                      detailType: 'RAWITEM',
                      layoutPos: {
                        shrink: 1,
                        height: 100,
                        heightMode: 'PX',
                        layout: 'FLEX',
                        width: 100,
                        widthMode: 'PX',
                      },
                      sysCss: {
                        cssName: 'el-alert el-alert--info is-light',
                      },
                      showCaption: true,
                      id: 'rawitem28',
                    },
                  ],
                  caption: 'Flex水平居中',
                  codeName: 'grouppanel15',
                  contentHeight: 184,
                  detailStyle: 'DEFAULT',
                  detailType: 'GROUPPANEL',
                  height: 200,
                  layoutPos: {
                    colLG: 12,
                    colMD: 24,
                    height: 200,
                    heightMode: 'PX',
                    layout: 'TABLE_24COL',
                  },
                  showCaption: true,
                  id: 'grouppanel15',
                },
                {
                  layout: {
                    align: 'space-between',
                    layout: 'FLEX',
                  },
                  deformDetails: [
                    {
                      rawItem: {
                        caption: 'A',
                        halign: 'LEFT',
                        valign: 'MIDDLE',
                        wrapMode: 'NOWRAP',
                        contentType: 'RAW',
                        sysCss: {
                          cssName: 'el-alert el-alert--warning is-light',
                        },
                        rawItemHeight: 100,
                        rawItemWidth: 100,
                        id: 'rawitem29',
                      },
                      codeName: 'rawitem29',
                      detailStyle: 'DEFAULT',
                      detailType: 'RAWITEM',
                      layoutPos: {
                        shrink: 1,
                        height: 100,
                        heightMode: 'PX',
                        layout: 'FLEX',
                        width: 100,
                        widthMode: 'PX',
                      },
                      sysCss: {
                        cssName: 'el-alert el-alert--warning is-light',
                      },
                      showCaption: true,
                      id: 'rawitem29',
                    },
                    {
                      rawItem: {
                        caption: 'B',
                        halign: 'LEFT',
                        valign: 'MIDDLE',
                        wrapMode: 'NOWRAP',
                        contentType: 'RAW',
                        sysCss: {
                          cssName: 'el-alert el-alert--success is-light',
                        },
                        rawItemHeight: 100,
                        rawItemWidth: 100,
                        id: 'rawitem30',
                      },
                      codeName: 'rawitem30',
                      detailStyle: 'DEFAULT',
                      detailType: 'RAWITEM',
                      layoutPos: {
                        shrink: 1,
                        height: 100,
                        heightMode: 'PX',
                        layout: 'FLEX',
                        width: 100,
                        widthMode: 'PX',
                      },
                      sysCss: {
                        cssName: 'el-alert el-alert--success is-light',
                      },
                      showCaption: true,
                      id: 'rawitem30',
                    },
                    {
                      rawItem: {
                        caption: 'C',
                        halign: 'LEFT',
                        valign: 'MIDDLE',
                        wrapMode: 'NOWRAP',
                        contentType: 'RAW',
                        sysCss: {
                          cssName: 'el-alert el-alert--info is-light',
                        },
                        rawItemHeight: 100,
                        rawItemWidth: 100,
                        id: 'rawitem31',
                      },
                      codeName: 'rawitem31',
                      detailStyle: 'DEFAULT',
                      detailType: 'RAWITEM',
                      layoutPos: {
                        shrink: 1,
                        height: 100,
                        heightMode: 'PX',
                        layout: 'FLEX',
                        width: 100,
                        widthMode: 'PX',
                      },
                      sysCss: {
                        cssName: 'el-alert el-alert--info is-light',
                      },
                      showCaption: true,
                      id: 'rawitem31',
                    },
                  ],
                  caption: 'Flex水平两端对齐',
                  codeName: 'grouppanel16',
                  contentHeight: 184,
                  detailStyle: 'DEFAULT',
                  detailType: 'GROUPPANEL',
                  height: 200,
                  layoutPos: {
                    colLG: 12,
                    colMD: 24,
                    height: 200,
                    heightMode: 'PX',
                    layout: 'TABLE_24COL',
                  },
                  showCaption: true,
                  id: 'grouppanel16',
                },
                {
                  layout: {
                    align: 'space-around',
                    layout: 'FLEX',
                  },
                  deformDetails: [
                    {
                      rawItem: {
                        caption: 'A',
                        halign: 'LEFT',
                        valign: 'MIDDLE',
                        wrapMode: 'NOWRAP',
                        contentType: 'RAW',
                        sysCss: {
                          cssName: 'el-alert el-alert--warning is-light',
                        },
                        rawItemHeight: 100,
                        rawItemWidth: 100,
                        id: 'rawitem32',
                      },
                      codeName: 'rawitem32',
                      detailStyle: 'DEFAULT',
                      detailType: 'RAWITEM',
                      layoutPos: {
                        shrink: 1,
                        height: 100,
                        heightMode: 'PX',
                        layout: 'FLEX',
                        width: 100,
                        widthMode: 'PX',
                      },
                      sysCss: {
                        cssName: 'el-alert el-alert--warning is-light',
                      },
                      showCaption: true,
                      id: 'rawitem32',
                    },
                    {
                      rawItem: {
                        caption: 'B',
                        halign: 'LEFT',
                        valign: 'MIDDLE',
                        wrapMode: 'NOWRAP',
                        contentType: 'RAW',
                        sysCss: {
                          cssName: 'el-alert el-alert--success is-light',
                        },
                        rawItemHeight: 100,
                        rawItemWidth: 100,
                        id: 'rawitem33',
                      },
                      codeName: 'rawitem33',
                      detailStyle: 'DEFAULT',
                      detailType: 'RAWITEM',
                      layoutPos: {
                        shrink: 1,
                        height: 100,
                        heightMode: 'PX',
                        layout: 'FLEX',
                        width: 100,
                        widthMode: 'PX',
                      },
                      sysCss: {
                        cssName: 'el-alert el-alert--success is-light',
                      },
                      showCaption: true,
                      id: 'rawitem33',
                    },
                    {
                      rawItem: {
                        caption: 'C',
                        halign: 'LEFT',
                        valign: 'MIDDLE',
                        wrapMode: 'NOWRAP',
                        contentType: 'RAW',
                        sysCss: {
                          cssName: 'el-alert el-alert--info is-light',
                        },
                        rawItemHeight: 100,
                        rawItemWidth: 100,
                        id: 'rawitem34',
                      },
                      codeName: 'rawitem34',
                      detailStyle: 'DEFAULT',
                      detailType: 'RAWITEM',
                      layoutPos: {
                        shrink: 1,
                        height: 100,
                        heightMode: 'PX',
                        layout: 'FLEX',
                        width: 100,
                        widthMode: 'PX',
                      },
                      sysCss: {
                        cssName: 'el-alert el-alert--info is-light',
                      },
                      showCaption: true,
                      id: 'rawitem34',
                    },
                  ],
                  caption: 'Flex水平间隔相同',
                  codeName: 'grouppanel17',
                  contentHeight: 184,
                  detailStyle: 'DEFAULT',
                  detailType: 'GROUPPANEL',
                  height: 200,
                  layoutPos: {
                    colLG: 12,
                    colMD: 24,
                    height: 200,
                    heightMode: 'PX',
                    layout: 'TABLE_24COL',
                  },
                  showCaption: true,
                  id: 'grouppanel17',
                },
                {
                  layout: {
                    layout: 'FLEX',
                    valign: 'flex-start',
                  },
                  deformDetails: [
                    {
                      rawItem: {
                        caption: 'A',
                        halign: 'LEFT',
                        valign: 'MIDDLE',
                        wrapMode: 'NOWRAP',
                        contentType: 'RAW',
                        sysCss: {
                          cssName: 'el-alert el-alert--warning is-light',
                        },
                        rawItemHeight: 40,
                        rawItemWidth: 100,
                        id: 'rawitem35',
                      },
                      codeName: 'rawitem35',
                      detailStyle: 'DEFAULT',
                      detailType: 'RAWITEM',
                      layoutPos: {
                        shrink: 1,
                        height: 40,
                        heightMode: 'PX',
                        layout: 'FLEX',
                        width: 100,
                        widthMode: 'PX',
                      },
                      sysCss: {
                        cssName: 'el-alert el-alert--warning is-light',
                      },
                      showCaption: true,
                      id: 'rawitem35',
                    },
                    {
                      rawItem: {
                        caption: 'B',
                        halign: 'LEFT',
                        valign: 'MIDDLE',
                        wrapMode: 'NOWRAP',
                        contentType: 'RAW',
                        sysCss: {
                          cssName: 'el-alert el-alert--success is-light',
                        },
                        rawItemHeight: 70,
                        rawItemWidth: 100,
                        id: 'rawitem36',
                      },
                      codeName: 'rawitem36',
                      detailStyle: 'DEFAULT',
                      detailType: 'RAWITEM',
                      layoutPos: {
                        shrink: 1,
                        height: 70,
                        heightMode: 'PX',
                        layout: 'FLEX',
                        width: 100,
                        widthMode: 'PX',
                      },
                      sysCss: {
                        cssName: 'el-alert el-alert--success is-light',
                      },
                      showCaption: true,
                      id: 'rawitem36',
                    },
                    {
                      rawItem: {
                        caption: 'C',
                        halign: 'LEFT',
                        valign: 'MIDDLE',
                        wrapMode: 'NOWRAP',
                        contentType: 'RAW',
                        sysCss: {
                          cssName: 'el-alert el-alert--info is-light',
                        },
                        rawItemHeight: 100,
                        rawItemWidth: 100,
                        id: 'rawitem37',
                      },
                      codeName: 'rawitem37',
                      detailStyle: 'DEFAULT',
                      detailType: 'RAWITEM',
                      layoutPos: {
                        shrink: 1,
                        height: 100,
                        heightMode: 'PX',
                        layout: 'FLEX',
                        width: 100,
                        widthMode: 'PX',
                      },
                      sysCss: {
                        cssName: 'el-alert el-alert--info is-light',
                      },
                      showCaption: true,
                      id: 'rawitem37',
                    },
                  ],
                  caption: 'Flex垂直上对齐',
                  codeName: 'grouppanel19',
                  contentHeight: 184,
                  detailStyle: 'DEFAULT',
                  detailType: 'GROUPPANEL',
                  height: 200,
                  layoutPos: {
                    colLG: 12,
                    colMD: 24,
                    height: 200,
                    heightMode: 'PX',
                    layout: 'TABLE_24COL',
                  },
                  showCaption: true,
                  id: 'grouppanel19',
                },
                {
                  layout: {
                    layout: 'FLEX',
                    valign: 'flex-end',
                  },
                  deformDetails: [
                    {
                      rawItem: {
                        caption: 'A',
                        halign: 'LEFT',
                        valign: 'MIDDLE',
                        wrapMode: 'NOWRAP',
                        contentType: 'RAW',
                        sysCss: {
                          cssName: 'el-alert el-alert--warning is-light',
                        },
                        rawItemHeight: 40,
                        rawItemWidth: 100,
                        id: 'rawitem38',
                      },
                      codeName: 'rawitem38',
                      detailStyle: 'DEFAULT',
                      detailType: 'RAWITEM',
                      layoutPos: {
                        shrink: 1,
                        height: 40,
                        heightMode: 'PX',
                        layout: 'FLEX',
                        width: 100,
                        widthMode: 'PX',
                      },
                      sysCss: {
                        cssName: 'el-alert el-alert--warning is-light',
                      },
                      showCaption: true,
                      id: 'rawitem38',
                    },
                    {
                      rawItem: {
                        caption: 'B',
                        halign: 'LEFT',
                        valign: 'MIDDLE',
                        wrapMode: 'NOWRAP',
                        contentType: 'RAW',
                        sysCss: {
                          cssName: 'el-alert el-alert--success is-light',
                        },
                        rawItemHeight: 70,
                        rawItemWidth: 100,
                        id: 'rawitem39',
                      },
                      codeName: 'rawitem39',
                      detailStyle: 'DEFAULT',
                      detailType: 'RAWITEM',
                      layoutPos: {
                        shrink: 1,
                        height: 70,
                        heightMode: 'PX',
                        layout: 'FLEX',
                        width: 100,
                        widthMode: 'PX',
                      },
                      sysCss: {
                        cssName: 'el-alert el-alert--success is-light',
                      },
                      showCaption: true,
                      id: 'rawitem39',
                    },
                    {
                      rawItem: {
                        caption: 'C',
                        halign: 'LEFT',
                        valign: 'MIDDLE',
                        wrapMode: 'NOWRAP',
                        contentType: 'RAW',
                        sysCss: {
                          cssName: 'el-alert el-alert--info is-light',
                        },
                        rawItemHeight: 100,
                        rawItemWidth: 100,
                        id: 'rawitem40',
                      },
                      codeName: 'rawitem40',
                      detailStyle: 'DEFAULT',
                      detailType: 'RAWITEM',
                      layoutPos: {
                        shrink: 1,
                        height: 100,
                        heightMode: 'PX',
                        layout: 'FLEX',
                        width: 100,
                        widthMode: 'PX',
                      },
                      sysCss: {
                        cssName: 'el-alert el-alert--info is-light',
                      },
                      showCaption: true,
                      id: 'rawitem40',
                    },
                  ],
                  caption: 'Flex垂直下对齐',
                  codeName: 'grouppanel20',
                  contentHeight: 184,
                  detailStyle: 'DEFAULT',
                  detailType: 'GROUPPANEL',
                  height: 200,
                  layoutPos: {
                    colLG: 12,
                    colMD: 24,
                    height: 200,
                    heightMode: 'PX',
                    layout: 'TABLE_24COL',
                  },
                  showCaption: true,
                  id: 'grouppanel20',
                },
                {
                  layout: {
                    layout: 'FLEX',
                    valign: 'center',
                  },
                  deformDetails: [
                    {
                      rawItem: {
                        caption: 'A',
                        halign: 'LEFT',
                        valign: 'MIDDLE',
                        wrapMode: 'NOWRAP',
                        contentType: 'RAW',
                        sysCss: {
                          cssName: 'el-alert el-alert--warning is-light',
                        },
                        rawItemHeight: 40,
                        rawItemWidth: 100,
                        id: 'rawitem41',
                      },
                      codeName: 'rawitem41',
                      detailStyle: 'DEFAULT',
                      detailType: 'RAWITEM',
                      layoutPos: {
                        shrink: 1,
                        height: 40,
                        heightMode: 'PX',
                        layout: 'FLEX',
                        width: 100,
                        widthMode: 'PX',
                      },
                      sysCss: {
                        cssName: 'el-alert el-alert--warning is-light',
                      },
                      showCaption: true,
                      id: 'rawitem41',
                    },
                    {
                      rawItem: {
                        caption: 'B',
                        halign: 'LEFT',
                        valign: 'MIDDLE',
                        wrapMode: 'NOWRAP',
                        contentType: 'RAW',
                        sysCss: {
                          cssName: 'el-alert el-alert--success is-light',
                        },
                        rawItemHeight: 70,
                        rawItemWidth: 100,
                        id: 'rawitem42',
                      },
                      codeName: 'rawitem42',
                      detailStyle: 'DEFAULT',
                      detailType: 'RAWITEM',
                      layoutPos: {
                        shrink: 1,
                        height: 70,
                        heightMode: 'PX',
                        layout: 'FLEX',
                        width: 100,
                        widthMode: 'PX',
                      },
                      sysCss: {
                        cssName: 'el-alert el-alert--success is-light',
                      },
                      showCaption: true,
                      id: 'rawitem42',
                    },
                    {
                      rawItem: {
                        caption: 'C',
                        halign: 'LEFT',
                        valign: 'MIDDLE',
                        wrapMode: 'NOWRAP',
                        contentType: 'RAW',
                        sysCss: {
                          cssName: 'el-alert el-alert--info is-light',
                        },
                        rawItemHeight: 100,
                        rawItemWidth: 100,
                        id: 'rawitem43',
                      },
                      codeName: 'rawitem43',
                      detailStyle: 'DEFAULT',
                      detailType: 'RAWITEM',
                      layoutPos: {
                        shrink: 1,
                        height: 100,
                        heightMode: 'PX',
                        layout: 'FLEX',
                        width: 100,
                        widthMode: 'PX',
                      },
                      sysCss: {
                        cssName: 'el-alert el-alert--info is-light',
                      },
                      showCaption: true,
                      id: 'rawitem43',
                    },
                  ],
                  caption: 'Flex垂直居中',
                  codeName: 'grouppanel21',
                  contentHeight: 184,
                  detailStyle: 'DEFAULT',
                  detailType: 'GROUPPANEL',
                  height: 200,
                  layoutPos: {
                    colLG: 12,
                    colMD: 24,
                    height: 200,
                    heightMode: 'PX',
                    layout: 'TABLE_24COL',
                  },
                  showCaption: true,
                  id: 'grouppanel21',
                },
                {
                  layout: {
                    layout: 'FLEX',
                    valign: 'baseline',
                  },
                  deformDetails: [
                    {
                      rawItem: {
                        caption: 'A',
                        halign: 'LEFT',
                        valign: 'MIDDLE',
                        wrapMode: 'NOWRAP',
                        contentType: 'RAW',
                        sysCss: {
                          cssName:
                            'el-alert el-alert--warning is-light baseline-warning',
                        },
                        rawItemHeight: 40,
                        rawItemWidth: 100,
                        id: 'rawitem44',
                      },
                      codeName: 'rawitem44',
                      detailStyle: 'DEFAULT',
                      detailType: 'RAWITEM',
                      layoutPos: {
                        shrink: 1,
                        height: 40,
                        heightMode: 'PX',
                        layout: 'FLEX',
                        width: 100,
                        widthMode: 'PX',
                      },
                      sysCss: {
                        cssName:
                          'el-alert el-alert--warning is-light baseline-warning',
                      },
                      showCaption: true,
                      id: 'rawitem44',
                    },
                    {
                      rawItem: {
                        caption: 'B',
                        halign: 'LEFT',
                        valign: 'MIDDLE',
                        wrapMode: 'NOWRAP',
                        contentType: 'RAW',
                        sysCss: {
                          cssName: 'el-alert el-alert--success is-light',
                        },
                        rawItemHeight: 70,
                        rawItemWidth: 100,
                        id: 'rawitem45',
                      },
                      codeName: 'rawitem45',
                      detailStyle: 'DEFAULT',
                      detailType: 'RAWITEM',
                      layoutPos: {
                        shrink: 1,
                        height: 70,
                        heightMode: 'PX',
                        layout: 'FLEX',
                        width: 100,
                        widthMode: 'PX',
                      },
                      sysCss: {
                        cssName: 'el-alert el-alert--success is-light',
                      },
                      showCaption: true,
                      id: 'rawitem45',
                    },
                    {
                      rawItem: {
                        caption: 'C',
                        halign: 'LEFT',
                        valign: 'MIDDLE',
                        wrapMode: 'NOWRAP',
                        contentType: 'RAW',
                        sysCss: {
                          cssName:
                            'el-alert el-alert--info is-light baseline-message',
                        },
                        rawItemHeight: 100,
                        rawItemWidth: 100,
                        id: 'rawitem46',
                      },
                      codeName: 'rawitem46',
                      detailStyle: 'DEFAULT',
                      detailType: 'RAWITEM',
                      layoutPos: {
                        shrink: 1,
                        height: 100,
                        heightMode: 'PX',
                        layout: 'FLEX',
                        width: 100,
                        widthMode: 'PX',
                      },
                      sysCss: {
                        cssName:
                          'el-alert el-alert--info is-light baseline-message',
                      },
                      showCaption: true,
                      id: 'rawitem46',
                    },
                  ],
                  caption: 'Flex垂直基线对齐',
                  codeName: 'grouppanel22',
                  contentHeight: 184,
                  detailStyle: 'DEFAULT',
                  detailType: 'GROUPPANEL',
                  height: 200,
                  layoutPos: {
                    colLG: 12,
                    colMD: 24,
                    height: 200,
                    heightMode: 'PX',
                    layout: 'TABLE_24COL',
                  },
                  showCaption: true,
                  id: 'grouppanel22',
                },
                {
                  layout: {
                    layout: 'FLEX',
                    valign: 'stretch',
                  },
                  deformDetails: [
                    {
                      rawItem: {
                        caption: 'A',
                        halign: 'LEFT',
                        valign: 'MIDDLE',
                        wrapMode: 'NOWRAP',
                        contentType: 'RAW',
                        sysCss: {
                          cssName: 'el-alert el-alert--warning is-light',
                        },
                        rawItemWidth: 100,
                        id: 'rawitem47',
                      },
                      codeName: 'rawitem47',
                      detailStyle: 'DEFAULT',
                      detailType: 'RAWITEM',
                      layoutPos: {
                        shrink: 1,
                        layout: 'FLEX',
                        width: 100,
                        widthMode: 'PX',
                      },
                      sysCss: {
                        cssName: 'el-alert el-alert--warning is-light',
                      },
                      showCaption: true,
                      id: 'rawitem47',
                    },
                    {
                      rawItem: {
                        caption: 'B',
                        halign: 'LEFT',
                        valign: 'MIDDLE',
                        wrapMode: 'NOWRAP',
                        contentType: 'RAW',
                        sysCss: {
                          cssName: 'el-alert el-alert--success is-light',
                        },
                        rawItemWidth: 100,
                        id: 'rawitem48',
                      },
                      codeName: 'rawitem48',
                      detailStyle: 'DEFAULT',
                      detailType: 'RAWITEM',
                      layoutPos: {
                        shrink: 1,
                        layout: 'FLEX',
                        width: 100,
                        widthMode: 'PX',
                      },
                      sysCss: {
                        cssName: 'el-alert el-alert--success is-light',
                      },
                      showCaption: true,
                      id: 'rawitem48',
                    },
                    {
                      rawItem: {
                        caption: 'C',
                        halign: 'LEFT',
                        valign: 'MIDDLE',
                        wrapMode: 'NOWRAP',
                        contentType: 'RAW',
                        sysCss: {
                          cssName: 'el-alert el-alert--info is-light',
                        },
                        rawItemWidth: 100,
                        id: 'rawitem49',
                      },
                      codeName: 'rawitem49',
                      detailStyle: 'DEFAULT',
                      detailType: 'RAWITEM',
                      layoutPos: {
                        shrink: 1,
                        layout: 'FLEX',
                        width: 100,
                        widthMode: 'PX',
                      },
                      sysCss: {
                        cssName: 'el-alert el-alert--info is-light',
                      },
                      showCaption: true,
                      id: 'rawitem49',
                    },
                  ],
                  caption: 'Flex垂直占满',
                  codeName: 'grouppanel23',
                  contentHeight: 184,
                  detailStyle: 'DEFAULT',
                  detailType: 'GROUPPANEL',
                  height: 200,
                  layoutPos: {
                    colLG: 12,
                    colMD: 24,
                    height: 200,
                    heightMode: 'PX',
                    layout: 'TABLE_24COL',
                  },
                  showCaption: true,
                  id: 'grouppanel23',
                },
                {
                  layout: {
                    layout: 'FLEX',
                  },
                  deformDetails: [
                    {
                      rawItem: {
                        caption: 'A',
                        halign: 'LEFT',
                        valign: 'MIDDLE',
                        wrapMode: 'NOWRAP',
                        contentType: 'RAW',
                        sysCss: {
                          cssName: 'el-alert el-alert--warning is-light',
                        },
                        id: 'rawitem50',
                      },
                      codeName: 'rawitem50',
                      detailStyle: 'DEFAULT',
                      detailType: 'RAWITEM',
                      layoutPos: {
                        grow: 1,
                        shrink: 1,
                        layout: 'FLEX',
                      },
                      sysCss: {
                        cssName: 'el-alert el-alert--warning is-light',
                      },
                      showCaption: true,
                      id: 'rawitem50',
                    },
                    {
                      rawItem: {
                        caption: 'B',
                        halign: 'LEFT',
                        valign: 'MIDDLE',
                        wrapMode: 'NOWRAP',
                        contentType: 'RAW',
                        sysCss: {
                          cssName: 'el-alert el-alert--success is-light',
                        },
                        id: 'rawitem51',
                      },
                      codeName: 'rawitem51',
                      detailStyle: 'DEFAULT',
                      detailType: 'RAWITEM',
                      layoutPos: {
                        grow: 3,
                        shrink: 1,
                        layout: 'FLEX',
                      },
                      sysCss: {
                        cssName: 'el-alert el-alert--success is-light',
                      },
                      showCaption: true,
                      id: 'rawitem51',
                    },
                    {
                      rawItem: {
                        caption: 'C',
                        halign: 'LEFT',
                        valign: 'MIDDLE',
                        wrapMode: 'NOWRAP',
                        contentType: 'RAW',
                        sysCss: {
                          cssName: 'el-alert el-alert--info is-light',
                        },
                        id: 'rawitem52',
                      },
                      codeName: 'rawitem52',
                      detailStyle: 'DEFAULT',
                      detailType: 'RAWITEM',
                      layoutPos: {
                        grow: 1,
                        shrink: 1,
                        layout: 'FLEX',
                      },
                      sysCss: {
                        cssName: 'el-alert el-alert--info is-light',
                      },
                      showCaption: true,
                      id: 'rawitem52',
                    },
                  ],
                  caption: 'Flex自适应',
                  codeName: 'grouppanel24',
                  contentHeight: 184,
                  detailStyle: 'DEFAULT',
                  detailType: 'GROUPPANEL',
                  height: 200,
                  layoutPos: {
                    colLG: 12,
                    colMD: 24,
                    height: 200,
                    heightMode: 'PX',
                    layout: 'TABLE_24COL',
                  },
                  showCaption: true,
                  id: 'grouppanel24',
                },
              ],
              enableAnchor: true,
              caption: 'Flex布局',
              codeName: 'grouppanel7',
              detailStyle: 'DEFAULT',
              detailType: 'GROUPPANEL',
              layoutPos: {
                colMD: 24,
                layout: 'TABLE_24COL',
              },
              id: 'grouppanel7',
            },
          ],
          caption: 'Flex布局',
          codeName: 'formpage2',
          detailStyle: 'DEFAULT',
          detailType: 'FORMPAGE',
          id: 'formpage2',
        },
        {
          layout: {
            columnCount: 24,
            layout: 'TABLE_24COL',
          },
          deformDetails: [
            {
              layout: {
                columnCount: 24,
                layout: 'TABLE_24COL',
              },
              deformDetails: [
                {
                  dataType: 25,
                  enableCond: 3,
                  labelPos: 'TOP',
                  labelWidth: 130,
                  noPrivDisplayMode: 1,
                  editor: {
                    editorType: 'TEXTBOX',
                    valueType: 'SIMPLE',
                    editable: true,
                    id: 'formitem',
                  },
                  allowEmpty: true,
                  caption: '上方标签',
                  codeName: 'formitem',
                  detailStyle: 'DEFAULT',
                  detailType: 'FORMITEM',
                  layoutPos: {
                    colMD: 24,
                    layout: 'TABLE_24COL',
                  },
                  showCaption: true,
                  id: 'formitem',
                },
                {
                  dataType: 25,
                  enableCond: 3,
                  labelPos: 'LEFT',
                  labelWidth: 130,
                  noPrivDisplayMode: 1,
                  editor: {
                    editorType: 'TEXTBOX',
                    valueType: 'SIMPLE',
                    editable: true,
                    id: 'formitem1',
                  },
                  allowEmpty: true,
                  caption: '左侧标签',
                  codeName: 'formitem1',
                  detailStyle: 'DEFAULT',
                  detailType: 'FORMITEM',
                  layoutPos: {
                    colMD: 24,
                    layout: 'TABLE_24COL',
                  },
                  showCaption: true,
                  id: 'formitem1',
                },
                {
                  dataType: 25,
                  enableCond: 3,
                  labelPos: 'LEFT',
                  labelWidth: 200,
                  noPrivDisplayMode: 1,
                  editor: {
                    editorType: 'TEXTBOX',
                    valueType: 'SIMPLE',
                    editable: true,
                    id: 'formitem2',
                  },
                  allowEmpty: true,
                  caption: '左侧标签（宽200）',
                  codeName: 'formitem2',
                  detailStyle: 'DEFAULT',
                  detailType: 'FORMITEM',
                  layoutPos: {
                    colMD: 24,
                    layout: 'TABLE_24COL',
                  },
                  showCaption: true,
                  id: 'formitem2',
                },
                {
                  dataType: 25,
                  enableCond: 3,
                  labelPos: 'RIGHT',
                  labelWidth: 130,
                  noPrivDisplayMode: 1,
                  editor: {
                    editorType: 'TEXTBOX',
                    valueType: 'SIMPLE',
                    editable: true,
                    id: 'formitem4',
                  },
                  allowEmpty: true,
                  caption: '右侧标签',
                  codeName: 'formitem4',
                  detailStyle: 'DEFAULT',
                  detailType: 'FORMITEM',
                  layoutPos: {
                    colMD: 24,
                    layout: 'TABLE_24COL',
                  },
                  showCaption: true,
                  id: 'formitem4',
                },
                {
                  dataType: 25,
                  enableCond: 3,
                  labelPos: 'BOTTOM',
                  labelWidth: 130,
                  noPrivDisplayMode: 1,
                  editor: {
                    editorType: 'TEXTBOX',
                    valueType: 'SIMPLE',
                    editable: true,
                    id: 'formitem5',
                  },
                  allowEmpty: true,
                  caption: '下方标签',
                  codeName: 'formitem5',
                  detailStyle: 'DEFAULT',
                  detailType: 'FORMITEM',
                  layoutPos: {
                    colMD: 24,
                    layout: 'TABLE_24COL',
                  },
                  showCaption: true,
                  id: 'formitem5',
                },
                {
                  rawItem: {
                    caption: '无标签',
                    halign: 'LEFT',
                    valign: 'MIDDLE',
                    wrapMode: 'NOWRAP',
                    contentType: 'RAW',
                    sysCss: {
                      cssName: 'el-alert el-alert--info is-light',
                    },
                    id: 'rawitem13',
                  },
                  codeName: 'rawitem13',
                  detailStyle: 'DEFAULT',
                  detailType: 'RAWITEM',
                  layoutPos: {
                    colMD: 24,
                    layout: 'TABLE_24COL',
                  },
                  sysCss: {
                    cssName: 'el-alert el-alert--info is-light',
                  },
                  showCaption: true,
                  id: 'rawitem13',
                },
                {
                  dataType: 25,
                  enableCond: 3,
                  labelPos: 'NONE',
                  noPrivDisplayMode: 1,
                  editor: {
                    editorType: 'TEXTBOX',
                    valueType: 'SIMPLE',
                    editable: true,
                    id: 'formitem3',
                  },
                  allowEmpty: true,
                  codeName: 'formitem3',
                  detailStyle: 'DEFAULT',
                  detailType: 'FORMITEM',
                  layoutPos: {
                    colMD: 24,
                    layout: 'TABLE_24COL',
                  },
                  id: 'formitem3',
                },
              ],
              enableAnchor: true,
              caption: '表单项标签布局',
              codeName: 'grouppanel9',
              detailStyle: 'DEFAULT',
              detailType: 'GROUPPANEL',
              layoutPos: {
                colMD: 24,
                layout: 'TABLE_24COL',
              },
              showCaption: true,
              id: 'grouppanel9',
            },
            {
              layout: {
                columnCount: 24,
                layout: 'TABLE_24COL',
              },
              deformDetails: [
                {
                  createDV: '编辑器宽200',
                  dataType: 25,
                  enableCond: 3,
                  itemWidth: 330,
                  labelPos: 'LEFT',
                  labelWidth: 130,
                  noPrivDisplayMode: 1,
                  editor: {
                    editorType: 'TEXTBOX',
                    editorWidth: 200,
                    valueType: 'SIMPLE',
                    editable: true,
                    id: 'formitem6',
                  },
                  allowEmpty: true,
                  caption: '表单项',
                  codeName: 'formitem6',
                  detailStyle: 'DEFAULT',
                  detailType: 'FORMITEM',
                  layoutPos: {
                    colMD: 24,
                    layout: 'TABLE_24COL',
                  },
                  showCaption: true,
                  id: 'formitem6',
                },
                {
                  createDV: '编辑器高150',
                  dataType: 25,
                  enableCond: 3,
                  itemHeight: 150,
                  labelPos: 'LEFT',
                  labelWidth: 130,
                  noPrivDisplayMode: 1,
                  editor: {
                    showMaxLength: true,
                    editorHeight: 150,
                    editorType: 'TEXTAREA',
                    valueType: 'SIMPLE',
                    editable: true,
                    id: 'formitem7',
                  },
                  allowEmpty: true,
                  caption: '表单项',
                  codeName: 'formitem7',
                  detailStyle: 'DEFAULT',
                  detailType: 'FORMITEM',
                  layoutPos: {
                    colMD: 24,
                    layout: 'TABLE_24COL',
                  },
                  showCaption: true,
                  id: 'formitem7',
                },
              ],
              enableAnchor: true,
              caption: '表单项编辑器布局',
              codeName: 'grouppanel18',
              detailStyle: 'DEFAULT',
              detailType: 'GROUPPANEL',
              layoutPos: {
                colMD: 24,
                layout: 'TABLE_24COL',
              },
              showCaption: true,
              id: 'grouppanel18',
            },
          ],
          caption: '编辑器布局',
          codeName: 'formpage3',
          detailStyle: 'DEFAULT',
          detailType: 'FORMPAGE',
          id: 'formpage3',
        },
      ],
      layout: {
        columnCount: 24,
        layout: 'TABLE_24COL',
      },
      tabHeaderPos: 'TOP',
      autoLoad: true,
      showBusyIndicator: true,
      codeName: 'form_layout_form',
      controlType: 'FORM',
      logicName: '编辑表单_布局_表单',
      appDataEntityId: 'web.master',
      controlParam: {
        id: 'form',
      },
      modelId: 'aa3741b751f5c3ca5964f8914876becd',
      modelType: 'PSDEFORM_EDITFORM',
      name: 'form',
      id: 'web.master.form_layout_form',
    },
    {
      codeName: 'form_layout_datainfobar',
      controlType: 'DATAINFOBAR',
      appDataEntityId: 'web.master',
      controlParam: {
        id: 'datainfobar',
      },
      name: 'datainfobar',
      id: 'form_layout_datainfobar',
    },
    {
      capLanguageRes: {
        lanResTag: 'DE.LNAME.MASTER',
      },
      caption: '编辑表单_布局',
      codeName: 'form_layout_captionbar',
      controlType: 'CAPTIONBAR',
      appDataEntityId: 'web.master',
      controlParam: {},
      name: 'captionbar',
      id: 'form_layout_captionbar',
    },
  ],
  viewLayoutPanel: {
    layoutBodyOnly: true,
    useDefaultLayout: true,
    layoutPanel: true,
    codeName: 'layoutpanel',
    controlStyle: 'APPDEEDITVIEW',
    controlType: 'VIEWLAYOUTPANEL',
    appDataEntityId: 'web.master',
    controlParam: {},
    id: 'layoutpanel',
  },
  title: '编辑表单_布局',
  viewStyle: 'DEFAULT',
  viewType: 'DEEDITVIEW',
  enableDP: true,
  showCaptionBar: false,
  modelId: 'a760c725aa7fba2175db26360fcc44e5',
  modelType: 'PSAPPDEVIEW',
  name: 'MASTERform_layout',
  id: 'web.master_form_layout',
};
