export default {
  enableSearch: true,
  loadDefault: true,
  deviewCodeName: 'Chart_funnelPlot',
  deviewId: 'dc2486dd86908a780d425463b14ab2aa',
  accUserMode: 3,
  capLanguageRes: {
    lanResTag: 'DE.LNAME.MASTER',
  },
  caption: '图表_漏斗图',
  codeName: 'master_chart_funnel_plot',
  appDataEntityId: 'web.master',
  appViewEngines: [
    {
      engineCat: 'VIEW',
      engineType: 'ChartView',
      id: 'engine',
    },
  ],
  appViewMsgGroupId: 'chart_funnelplot',
  controls: [
    {
      searchButtonStyle: 'DEFAULT',
      deformPages: [
        {
          layout: {
            columnCount: 24,
            layout: 'TABLE_24COL',
          },
          caption: '常规条件',
          codeName: 'formpage1',
          detailStyle: 'DEFAULT',
          detailType: 'FORMPAGE',
          id: 'formpage1',
        },
      ],
      layout: {
        columnCount: 24,
        layout: 'TABLE_24COL',
      },
      tabHeaderPos: 'TOP',
      noTabHeader: true,
      autoLoad: true,
      showBusyIndicator: true,
      codeName: 'usr05152251_search_form',
      controlType: 'SEARCHFORM',
      logicName: '图表_漏斗图_搜索表单',
      appDataEntityId: 'web.master',
      controlParam: {
        id: 'searchform',
      },
      modelId: '87f31add937bd8632ba225f1ec428207',
      modelType: 'PSDEFORM_SEARCHFORM',
      name: 'searchform',
      id: 'web.master.usr05152251_search_form',
    },
    {
      coordinateSystem: 'NONE',
      chartCoordinateSystems: [
        {
          echartsType: 'none',
          type: 'NONE',
          name: '[funnel_0]无坐标系[0]',
          id: '0',
        },
      ],
      dechartDataGrid: {
        id: '0',
      },
      dechartLegend: {
        legendPos: 'TOP',
        showLegend: true,
        id: '0',
      },
      dechartSerieses: [
        {
          caption: '漏斗图',
          catalogField: 'TYPE',
          echartsType: 'funnel',
          chartCoordinateSystemId: '0',
          chartDataSetId: '0',
          chartSeriesEncode: {
            category: 'TYPE',
            value: 'QUANTITY',
            type: 'NONE',
            name: '坐标系编码',
            id: '0',
          },
          seriesLayoutBy: 'column',
          seriesType: 'funnel',
          valueField: 'QUANTITY',
          enableChartDataSet: true,
          id: 'funnel_0',
        },
      ],
      dechartTitle: {
        title: '漏斗图',
        titlePos: 'LEFT',
        id: '0',
      },
      chartDataSetGroups: [
        {
          appDEDataSetId: 'fetch_default',
          appDataEntityId: 'web.master',
          name: 'DEFAULT',
          id: '0',
        },
      ],
      chartDataSets: [
        {
          chartDataSetFields: [
            {
              groupField: true,
              name: 'TYPE',
              id: '0',
            },
            {
              index: 1,
              name: 'QUANTITY',
              id: '1',
            },
          ],
          name: 'funnel_0-DEFAULT',
          id: '0',
        },
      ],
      navViewPos: 'NONE',
      fetchControlAction: {
        appDEMethodId: 'fetch_default',
        appDataEntityId: 'web.master',
        id: 'fetch',
      },
      readOnly: true,
      autoLoad: true,
      showBusyIndicator: true,
      codeName: 'master_chart_funnel_plot_chart',
      controlType: 'CHART',
      height: 300,
      logicName: 'Chart8',
      appDataEntityId: 'web.master',
      controlParam: {
        id: 'chart',
      },
      modelId: 'd623f2a9e695773c73271641d5599015',
      modelType: 'PSDECHART',
      userParam: {
        'EC.color':
          '["#5470c6","#91cc75","#fac858","#ee6666","#73c0de","#3ba272","#fc8452","#9a60b4","#ea7ccc","#5470c6","#91cc75"]',
      },
      name: 'chart',
      id: 'web.master.master_chart_funnel_plot_chart',
    },
    {
      capLanguageRes: {
        lanResTag: 'DE.LNAME.MASTER',
      },
      caption: '图表_漏斗图',
      codeName: 'chart_funnel_plot_captionbar',
      controlType: 'CAPTIONBAR',
      appDataEntityId: 'web.master',
      controlParam: {},
      name: 'captionbar',
      id: 'chart_funnel_plot_captionbar',
    },
  ],
  viewLayoutPanel: {
    layoutBodyOnly: true,
    useDefaultLayout: true,
    layoutPanel: true,
    codeName: 'layoutpanel',
    controlStyle: 'APPDECHARTVIEW',
    controlType: 'VIEWLAYOUTPANEL',
    appDataEntityId: 'web.master',
    controlParam: {},
    id: 'layoutpanel',
  },
  title: '图表_漏斗图',
  viewStyle: 'DEFAULT',
  viewType: 'DECHARTVIEW',
  enableDP: true,
  showCaptionBar: false,
  modelId: '9e2c822579b4caa5a9138498d37d511a',
  modelType: 'PSAPPDEVIEW',
  name: 'MASTERChart_funnelPlot',
  id: 'web.master_chart_funnel_plot',
};
