export default {
  deviewCodeName: 'toolbar_group',
  deviewId: 'cb20027d1a68f3068b7e7629cfc92433',
  accUserMode: 3,
  capLanguageRes: {
    lanResTag: 'DE.LNAME.MASTER',
  },
  caption: '工具栏_分组',
  codeName: 'master_toolbar_group',
  appDataEntityId: 'web.master',
  appViewMsgGroupId: 'toolbar_group',
  viewLayoutPanel: {
    viewProxyMode: true,
    layoutMode: 'FLEX',
    layout: {
      layout: 'FLEX',
    },
    rootPanelItems: [
      {
        actionGroupExtractMode: 'ITEM',
        panelItems: [
          {
            actionGroupExtractMode: 'ITEM',
            panelItems: [
              {
                actionGroupExtractMode: 'ITEM',
                panelItems: [
                  {
                    caption: '工具栏',
                    itemStyle: 'DEFAULT',
                    itemType: 'CTRLPOS',
                    layoutPos: {
                      shrink: 1,
                      layout: 'FLEX',
                    },
                    showCaption: true,
                    id: 'toolbar',
                  },
                ],
                layout: {
                  layout: 'FLEX',
                },
                dataRegionType: 'INHERIT',
                caption: '容器',
                itemStyle: 'DEFAULT',
                itemType: 'CONTAINER',
                layoutPos: {
                  layoutPos: 'CENTER',
                  layout: 'BORDER',
                },
                id: 'container',
              },
            ],
            predefinedType: 'CONTAINER_SCROLL_MAIN',
            layout: {
              layout: 'BORDER',
            },
            dataRegionType: 'INHERIT',
            caption: '面板容器',
            itemStyle: 'DEFAULT',
            itemType: 'CONTAINER',
            layoutPos: {
              layoutPos: 'CENTER',
              layout: 'BORDER',
            },
            showCaption: true,
            id: 'container_scroll_main',
          },
        ],
        predefinedType: 'CONTAINER_SCROLL',
        layout: {
          layout: 'BORDER',
        },
        dataRegionType: 'INHERIT',
        caption: '滚动条容器',
        itemStyle: 'DEFAULT',
        itemType: 'CONTAINER',
        layoutPos: {
          shrink: 1,
          layout: 'FLEX',
        },
        id: 'container_scroll',
      },
    ],
    layoutPanel: true,
    controls: [
      {
        detoolbarItems: [
          {
            actionLevel: 100,
            detoolbarItems: [
              {
                actionLevel: 100,
                noPrivDisplayMode: 2,
                uiactionId: 'open_dialog@master',
                uiactionTarget: 'NONE',
                valid: true,
                caption: '界面行为1',
                itemType: 'DEUIACTION',
                tooltip: '界面行为1',
                showCaption: true,
                showIcon: true,
                id: 'deuiaction1',
              },
              {
                actionLevel: 100,
                noPrivDisplayMode: 2,
                uiactionId: 'open_dialog@master',
                uiactionTarget: 'NONE',
                valid: true,
                caption: '界面行为2',
                itemType: 'DEUIACTION',
                tooltip: '界面行为2',
                showCaption: true,
                showIcon: true,
                id: 'deuiaction2',
              },
            ],
            valid: true,
            caption: '分组',
            itemType: 'ITEMS',
            tooltip: '分组',
            showCaption: true,
            showIcon: true,
            id: 'items1',
          },
        ],
        codeName: 'toolbar_group_toolbar',
        controlType: 'TOOLBAR',
        logicName: '工具栏_分组',
        appDataEntityId: 'web.master',
        controlParam: {
          id: 'toolbar',
        },
        modelId: '15c7b63ac290f0613431a1c665d9f1e4',
        modelType: 'PSDETOOLBAR',
        name: 'toolbar',
        id: 'toolbar_group_toolbar',
      },
      {
        capLanguageRes: {
          lanResTag: 'DE.LNAME.MASTER',
        },
        caption: '工具栏_分组',
        codeName: 'toolbar_group_captionbar',
        controlType: 'CAPTIONBAR',
        appDataEntityId: 'web.master',
        controlParam: {},
        name: 'captionbar',
        id: 'toolbar_group_captionbar',
      },
    ],
    codeName: 'usr0515620429',
    controlType: 'VIEWLAYOUTPANEL',
    logicName: '工具栏_分组布局面板',
    appDataEntityId: 'web.master',
    controlParam: {},
    modelId: '87598ba08f2761ac544dae552cc8a339',
    modelType: 'PSSYSVIEWLAYOUTPANEL',
    name: 'layoutpanel',
    id: 'usr0515620429',
  },
  title: '工具栏_分组',
  viewStyle: 'DEFAULT',
  viewType: 'DECUSTOMVIEW',
  enableDP: true,
  showCaptionBar: false,
  modelId: '9012e64a88be39ed946bd01b4e810bd7',
  modelType: 'PSAPPDEVIEW',
  name: 'MASTERtoolbar_group',
  id: 'web.master_toolbar_group',
};
