export default {
  enableSearch: true,
  loadDefault: true,
  deviewCodeName: 'Chart_instrument',
  deviewId: 'fd151e1c9e1754a0c37f663beb711510',
  accUserMode: 3,
  capLanguageRes: {
    lanResTag: 'DE.LNAME.MASTER',
  },
  caption: '图表_仪表图',
  codeName: 'master_chart_instrument',
  appDataEntityId: 'web.master',
  appViewEngines: [
    {
      engineCat: 'VIEW',
      engineType: 'ChartView',
      id: 'engine',
    },
  ],
  appViewMsgGroupId: 'chart_instrument',
  controls: [
    {
      searchButtonStyle: 'DEFAULT',
      deformPages: [
        {
          layout: {
            columnCount: 24,
            layout: 'TABLE_24COL',
          },
          caption: '常规条件',
          codeName: 'formpage1',
          detailStyle: 'DEFAULT',
          detailType: 'FORMPAGE',
          id: 'formpage1',
        },
      ],
      layout: {
        columnCount: 24,
        layout: 'TABLE_24COL',
      },
      tabHeaderPos: 'TOP',
      noTabHeader: true,
      autoLoad: true,
      showBusyIndicator: true,
      codeName: 'chart_instrument_search_form',
      controlType: 'SEARCHFORM',
      logicName: '图表_仪表图_搜索表单',
      appDataEntityId: 'web.master',
      controlParam: {
        id: 'searchform',
      },
      modelId: '7eec04d731fa4138f6bed7eeae7aab21',
      modelType: 'PSDEFORM_SEARCHFORM',
      name: 'searchform',
      id: 'web.master.chart_instrument_search_form',
    },
    {
      dechartDataGrid: {
        id: '0',
      },
      dechartLegend: {
        showLegend: true,
        id: '0',
      },
      dechartTitle: {
        title: '图表_仪表图_图表',
        id: '0',
      },
      navViewPos: 'NONE',
      fetchControlAction: {
        appDEMethodId: 'fetch_default',
        appDataEntityId: 'web.master',
        id: 'fetch',
      },
      readOnly: true,
      autoLoad: true,
      showBusyIndicator: true,
      codeName: 'chart_instrument_chart',
      controlType: 'CHART',
      height: 300,
      logicName: 'Chart12',
      appDataEntityId: 'web.master',
      controlParam: {
        id: 'chart',
      },
      modelId: '8efa0f81c3b254e78b21d1161e8a08dd',
      modelType: 'PSDECHART',
      userParam: {
        'EC.color':
          '["#5470c6","#91cc75","#fac858","#ee6666","#73c0de","#3ba272","#fc8452","#9a60b4","#ea7ccc","#5470c6","#91cc75"]',
      },
      name: 'chart',
      id: 'web.master.chart_instrument_chart',
    },
    {
      capLanguageRes: {
        lanResTag: 'DE.LNAME.MASTER',
      },
      caption: '图表_仪表图',
      codeName: 'chart_instrument_captionbar',
      controlType: 'CAPTIONBAR',
      appDataEntityId: 'web.master',
      controlParam: {},
      name: 'captionbar',
      id: 'chart_instrument_captionbar',
    },
  ],
  viewLayoutPanel: {
    layoutBodyOnly: true,
    useDefaultLayout: true,
    layoutPanel: true,
    codeName: 'layoutpanel',
    controlStyle: 'APPDECHARTVIEW',
    controlType: 'VIEWLAYOUTPANEL',
    appDataEntityId: 'web.master',
    controlParam: {},
    id: 'layoutpanel',
  },
  title: '图表_仪表图',
  viewStyle: 'DEFAULT',
  viewType: 'DECHARTVIEW',
  enableDP: true,
  showCaptionBar: false,
  modelId: '3018a3dbda6cdb469d4eeb52231fac5c',
  modelType: 'PSAPPDEVIEW',
  name: 'MASTERChart_instrument',
  id: 'web.master_chart_instrument',
};
