export default {
  deviewCodeName: 'list_nav',
  deviewId: 'bd68f2392b844ee3b65764d40630968d',
  accUserMode: 3,
  capLanguageRes: {
    lanResTag: 'DE.LNAME.MASTER',
  },
  caption: '列表_内置导航',
  codeName: 'master_list_nav',
  appDataEntityId: 'web.master',
  appViewMsgGroupId: 'list_nav',
  viewLayoutPanel: {
    viewProxyMode: true,
    layoutMode: 'FLEX',
    layout: {
      layout: 'FLEX',
    },
    rootPanelItems: [
      {
        actionGroupExtractMode: 'ITEM',
        panelItems: [
          {
            actionGroupExtractMode: 'ITEM',
            panelItems: [
              {
                actionGroupExtractMode: 'ITEM',
                panelItems: [
                  {
                    caption: '列表',
                    itemStyle: 'DEFAULT',
                    itemType: 'CTRLPOS',
                    layoutPos: {
                      shrink: 1,
                      layout: 'FLEX',
                    },
                    showCaption: true,
                    id: 'list',
                  },
                ],
                predefinedType: 'CONTAINER_GROUP',
                layout: {
                  layout: 'FLEX',
                },
                dataRegionType: 'INHERIT',
                caption: '右边(导航栏宽度800)',
                itemStyle: 'DEFAULT',
                itemType: 'CONTAINER',
                layoutPos: {
                  layoutPos: 'CENTER',
                  layout: 'BORDER',
                },
                showCaption: true,
                id: 'container_group',
              },
              {
                actionGroupExtractMode: 'ITEM',
                panelItems: [
                  {
                    caption: '列表',
                    contentHeight: 1200,
                    height: 1200,
                    itemStyle: 'DEFAULT',
                    itemType: 'CTRLPOS',
                    layoutPos: {
                      shrink: 1,
                      height: 1200,
                      heightMode: 'PX',
                      layout: 'FLEX',
                    },
                    showCaption: true,
                    id: 'list1',
                  },
                  {
                    actionGroupExtractMode: 'ITEM',
                    panelItems: [
                      {
                        caption: '列表',
                        itemStyle: 'DEFAULT',
                        itemType: 'CTRLPOS',
                        layoutPos: {
                          shrink: 1,
                          layout: 'FLEX',
                        },
                        showCaption: true,
                        id: 'list2',
                      },
                    ],
                    predefinedType: 'CONTAINER_GROUP',
                    layout: {
                      layout: 'FLEX',
                    },
                    dataRegionType: 'INHERIT',
                    caption: '行明细',
                    itemStyle: 'DEFAULT',
                    itemType: 'CONTAINER',
                    layoutPos: {
                      shrink: 1,
                      layout: 'FLEX',
                    },
                    showCaption: true,
                    id: 'container_group2',
                  },
                ],
                predefinedType: 'CONTAINER_GROUP',
                layout: {
                  layout: 'FLEX',
                },
                dataRegionType: 'INHERIT',
                caption: '下边（导航栏高度700）',
                itemStyle: 'DEFAULT',
                itemType: 'CONTAINER',
                layoutPos: {
                  layoutPos: 'CENTER',
                  layout: 'BORDER',
                },
                showCaption: true,
                id: 'container_group1',
              },
            ],
            predefinedType: 'CONTAINER_SCROLL_MAIN',
            layout: {
              layout: 'BORDER',
            },
            dataRegionType: 'INHERIT',
            caption: '面板容器',
            itemStyle: 'DEFAULT',
            itemType: 'CONTAINER',
            layoutPos: {
              layoutPos: 'CENTER',
              layout: 'BORDER',
            },
            showCaption: true,
            id: 'container_scroll_main',
          },
        ],
        predefinedType: 'CONTAINER_SCROLL',
        layout: {
          layout: 'BORDER',
        },
        dataRegionType: 'INHERIT',
        caption: '滚动条容器',
        itemStyle: 'DEFAULT',
        itemType: 'CONTAINER',
        layoutPos: {
          shrink: 1,
          layout: 'FLEX',
        },
        id: 'container_scroll',
      },
    ],
    layoutPanel: true,
    controls: [
      {
        groupMode: 'NONE',
        groupStyle: 'DEFAULT',
        itemLayoutPanel: {
          layoutMode: 'FLEX',
          layout: {
            layout: 'FLEX',
          },
          rootPanelItems: [
            {
              actionGroupExtractMode: 'ITEM',
              panelItems: [
                {
                  editor: {
                    halign: 'LEFT',
                    renderMode: 'TEXT_DYNAMIC',
                    valign: 'MIDDLE',
                    wrapMode: 'NOWRAP',
                    editorType: 'SPAN',
                    predefinedType: 'FIELD_TEXT_DYNAMIC',
                    valueType: 'SIMPLE',
                    editable: true,
                    id: 'name',
                  },
                  viewFieldName: 'name',
                  allowEmpty: true,
                  caption: '文本(动态)',
                  itemStyle: 'DEFAULT',
                  itemType: 'FIELD',
                  layoutPos: {
                    shrink: 1,
                    layout: 'FLEX',
                  },
                  id: 'name',
                },
              ],
              layout: {
                layout: 'FLEX',
              },
              dataRegionType: 'INHERIT',
              caption: '容器',
              itemStyle: 'DEFAULT',
              itemType: 'CONTAINER',
              layoutPos: {
                shrink: 1,
                layout: 'FLEX',
              },
              id: 'container',
            },
          ],
          layoutPanel: true,
          codeName: 'a3745787c6aef98dc79',
          controlType: 'PANEL',
          logicName: 'list_bottom_nav列表',
          appDataEntityId: 'web.master',
          controlParam: {},
          modelId: '19dbbec176567960535aa0a410d8e750',
          modelType: 'PSSYSVIEWPANEL',
          name: 'list1_itempanel',
          id: 'web.master.a3745787c6aef98dc79',
        },
        delistDataItems: [
          {
            appDEFieldId: 'name',
            dataType: 25,
            id: 'name',
          },
          {
            appDEFieldId: 'id',
            dataType: 25,
            id: 'srfkey',
          },
          {
            appDEFieldId: 'name',
            dataType: 25,
            id: 'srfmajortext',
          },
          {
            appDEFieldId: 'region_id',
            dataType: 25,
            id: 'region_id',
          },
        ],
        pagingMode: 1,
        pagingSize: 10,
        enablePagingBar: true,
        showHeader: true,
        singleSelect: true,
        navAppViewId: 'web.master_info_view',
        navViewHeight: 700,
        navViewPos: 'BOTTOM',
        createControlAction: {
          appDEMethodId: 'create',
          appDataEntityId: 'web.master',
          id: 'create',
        },
        fetchControlAction: {
          appDEMethodId: 'fetch_default',
          appDataEntityId: 'web.master',
          id: 'fetch',
        },
        getControlAction: {
          appDEMethodId: 'get',
          appDataEntityId: 'web.master',
          id: 'load',
        },
        removeControlAction: {
          appDEMethodId: 'remove',
          appDataEntityId: 'web.master',
          id: 'remove',
        },
        updateControlAction: {
          appDEMethodId: 'update',
          appDataEntityId: 'web.master',
          id: 'update',
        },
        autoLoad: true,
        showBusyIndicator: true,
        codeName: 'list_bottom_nav',
        controlType: 'LIST',
        logicName: 'list_bottom_nav',
        appDataEntityId: 'web.master',
        controlParam: {
          id: 'list1',
        },
        modelId: '57f9a9d0ab397dec0135f363d213f0e4',
        modelType: 'PSDELIST',
        name: 'list1',
        id: 'web.master.list_bottom_nav',
      },
      {
        groupMode: 'NONE',
        groupStyle: 'DEFAULT',
        itemLayoutPanel: {
          layoutMode: 'FLEX',
          layout: {
            layout: 'FLEX',
          },
          rootPanelItems: [
            {
              actionGroupExtractMode: 'ITEM',
              panelItems: [
                {
                  editor: {
                    halign: 'LEFT',
                    renderMode: 'TEXT_DYNAMIC',
                    valign: 'MIDDLE',
                    wrapMode: 'NOWRAP',
                    editorType: 'SPAN',
                    predefinedType: 'FIELD_TEXT_DYNAMIC',
                    valueType: 'SIMPLE',
                    editable: true,
                    id: 'name',
                  },
                  viewFieldName: 'name',
                  allowEmpty: true,
                  caption: '文本(动态)',
                  itemStyle: 'DEFAULT',
                  itemType: 'FIELD',
                  layoutPos: {
                    shrink: 1,
                    layout: 'FLEX',
                  },
                  id: 'name',
                },
              ],
              layout: {
                layout: 'FLEX',
              },
              dataRegionType: 'INHERIT',
              caption: '容器',
              itemStyle: 'DEFAULT',
              itemType: 'CONTAINER',
              layoutPos: {
                shrink: 1,
                layout: 'FLEX',
              },
              id: 'container',
            },
          ],
          layoutPanel: true,
          codeName: 'a783706c32bf3c2954a',
          controlType: 'PANEL',
          logicName: 'list_right_nav列表',
          appDataEntityId: 'web.master',
          controlParam: {},
          modelId: '21b013921c35195228c6b34680545d8e',
          modelType: 'PSSYSVIEWPANEL',
          name: 'list_itempanel',
          id: 'web.master.a783706c32bf3c2954a',
        },
        delistDataItems: [
          {
            appDEFieldId: 'name',
            dataType: 25,
            id: 'name',
          },
          {
            appDEFieldId: 'id',
            dataType: 25,
            id: 'srfkey',
          },
          {
            appDEFieldId: 'name',
            dataType: 25,
            id: 'srfmajortext',
          },
          {
            appDEFieldId: 'region_id',
            dataType: 25,
            id: 'region_id',
          },
        ],
        pagingMode: 1,
        pagingSize: 10,
        enablePagingBar: true,
        showHeader: true,
        singleSelect: true,
        navAppViewId: 'web.master_info_view',
        navViewPos: 'RIGHT',
        navViewWidth: 800,
        createControlAction: {
          appDEMethodId: 'create',
          appDataEntityId: 'web.master',
          id: 'create',
        },
        fetchControlAction: {
          appDEMethodId: 'fetch_default',
          appDataEntityId: 'web.master',
          id: 'fetch',
        },
        getControlAction: {
          appDEMethodId: 'get',
          appDataEntityId: 'web.master',
          id: 'load',
        },
        removeControlAction: {
          appDEMethodId: 'remove',
          appDataEntityId: 'web.master',
          id: 'remove',
        },
        updateControlAction: {
          appDEMethodId: 'update',
          appDataEntityId: 'web.master',
          id: 'update',
        },
        autoLoad: true,
        showBusyIndicator: true,
        codeName: 'list_right_nav',
        controlType: 'LIST',
        logicName: 'list_right_nav',
        appDataEntityId: 'web.master',
        controlParam: {
          id: 'list',
        },
        modelId: 'fddd1eea33c9f845fb74cc6950fbaf91',
        modelType: 'PSDELIST',
        name: 'list',
        id: 'web.master.list_right_nav',
      },
      {
        groupMode: 'NONE',
        groupStyle: 'DEFAULT',
        itemLayoutPanel: {
          layoutMode: 'FLEX',
          layout: {
            layout: 'FLEX',
          },
          rootPanelItems: [
            {
              actionGroupExtractMode: 'ITEM',
              panelItems: [
                {
                  editor: {
                    halign: 'LEFT',
                    renderMode: 'TEXT_DYNAMIC',
                    valign: 'MIDDLE',
                    wrapMode: 'NOWRAP',
                    editorType: 'SPAN',
                    predefinedType: 'FIELD_TEXT_DYNAMIC',
                    valueType: 'SIMPLE',
                    editable: true,
                    id: 'name',
                  },
                  viewFieldName: 'name',
                  allowEmpty: true,
                  caption: '文本(动态)',
                  itemStyle: 'DEFAULT',
                  itemType: 'FIELD',
                  layoutPos: {
                    shrink: 1,
                    layout: 'FLEX',
                  },
                  id: 'name',
                },
              ],
              layout: {
                align: 'space-between',
                layout: 'FLEX',
              },
              dataRegionType: 'INHERIT',
              itemStyle: 'DEFAULT',
              itemType: 'CONTAINER',
              layoutPos: {
                shrink: 1,
                layout: 'FLEX',
              },
              id: 'container1',
            },
          ],
          layoutPanel: true,
          codeName: 'aaf494e5356d50abb8a',
          controlType: 'PANEL',
          logicName: 'list_rowdetail_nav列表',
          appDataEntityId: 'web.master',
          controlParam: {},
          modelId: '1a41fb238b9ffdc70f451b3df5b557c4',
          modelType: 'PSSYSVIEWPANEL',
          name: 'list2_itempanel',
          id: 'web.master.aaf494e5356d50abb8a',
        },
        delistDataItems: [
          {
            appDEFieldId: 'name',
            dataType: 25,
            id: 'name',
          },
          {
            appDEFieldId: 'id',
            dataType: 25,
            id: 'srfkey',
          },
          {
            appDEFieldId: 'name',
            dataType: 25,
            id: 'srfmajortext',
          },
          {
            appDEFieldId: 'region_id',
            dataType: 25,
            id: 'region_id',
          },
        ],
        pagingSize: 1000,
        showHeader: true,
        navAppViewId: 'web.master_info_view',
        navViewPos: 'ROWDETAIL',
        createControlAction: {
          appDEMethodId: 'create',
          appDataEntityId: 'web.master',
          id: 'create',
        },
        fetchControlAction: {
          appDEMethodId: 'fetch_default',
          appDataEntityId: 'web.master',
          id: 'fetch',
        },
        getControlAction: {
          appDEMethodId: 'get',
          appDataEntityId: 'web.master',
          id: 'load',
        },
        removeControlAction: {
          appDEMethodId: 'remove',
          appDataEntityId: 'web.master',
          id: 'remove',
        },
        updateControlAction: {
          appDEMethodId: 'update',
          appDataEntityId: 'web.master',
          id: 'update',
        },
        autoLoad: true,
        showBusyIndicator: true,
        codeName: 'list_rowdetail_nav',
        controlType: 'LIST',
        logicName: 'list_rowdetail_nav',
        appDataEntityId: 'web.master',
        controlParam: {
          id: 'list2',
        },
        modelId: '43c7b2b30ce7ab3755682eb8f82c5d1f',
        modelType: 'PSDELIST',
        name: 'list2',
        id: 'web.master.list_rowdetail_nav',
      },
      {
        capLanguageRes: {
          lanResTag: 'DE.LNAME.MASTER',
        },
        caption: '列表_内置导航',
        codeName: 'list_nav_captionbar',
        controlType: 'CAPTIONBAR',
        appDataEntityId: 'web.master',
        controlParam: {},
        name: 'captionbar',
        id: 'list_nav_captionbar',
      },
    ],
    codeName: 'usr0516001160',
    controlType: 'VIEWLAYOUTPANEL',
    logicName: '列表_内置导航布局面板',
    appDataEntityId: 'web.master',
    controlParam: {},
    modelId: '4a2aebed83b78cae9e769c8b92f8adaa',
    modelType: 'PSSYSVIEWLAYOUTPANEL',
    name: 'layoutpanel',
    id: 'usr0516001160',
  },
  title: '列表_内置导航',
  viewStyle: 'DEFAULT',
  viewType: 'DECUSTOMVIEW',
  enableDP: true,
  showCaptionBar: false,
  modelId: 'd3e32d0bbfffd466c9ab95ad3916ba74',
  modelType: 'PSAPPDEVIEW',
  name: 'MASTERlist_nav',
  id: 'web.master_list_nav',
};
