export default {
  deviewCodeName: 'counter_form_group',
  deviewId: '5eb4de48f9222a3f81a3a98f663bee06',
  accUserMode: 3,
  capLanguageRes: {
    lanResTag: 'DE.LNAME.MASTER',
  },
  caption: '计数器_表单内分组',
  codeName: 'master_counter_form_group',
  appDataEntityId: 'web.master',
  appViewMsgGroupId: 'counter_form_group',
  viewLayoutPanel: {
    layoutBodyOnly: true,
    viewProxyMode: true,
    layoutMode: 'FLEX',
    layout: {
      layout: 'FLEX',
    },
    rootPanelItems: [
      {
        actionGroupExtractMode: 'ITEM',
        panelItems: [
          {
            caption: '表单',
            itemStyle: 'DEFAULT',
            itemType: 'CTRLPOS',
            layoutPos: {
              shrink: 1,
              layout: 'FLEX',
            },
            showCaption: true,
            id: 'form',
          },
        ],
        predefinedType: 'CONTAINER_GROUP',
        layout: {
          layout: 'FLEX',
        },
        dataRegionType: 'INHERIT',
        caption: '分页部件',
        itemStyle: 'DEFAULT',
        itemType: 'CONTAINER',
        layoutPos: {
          shrink: 1,
          layout: 'FLEX',
        },
        showCaption: true,
        id: 'container_group',
      },
    ],
    layoutPanel: true,
    controls: [
      {
        createControlAction: {
          appDEMethodId: 'create',
          appDataEntityId: 'web.master',
          id: 'create',
        },
        getDraftFromControlAction: {
          appDataEntityId: 'web.master',
          id: 'loaddraftfrom',
        },
        getDraftControlAction: {
          appDEMethodId: 'get_draft',
          appDataEntityId: 'web.master',
          id: 'loaddraft',
        },
        getControlAction: {
          appDEMethodId: 'get',
          appDataEntityId: 'web.master',
          id: 'load',
        },
        removeControlAction: {
          appDEMethodId: 'remove',
          appDataEntityId: 'web.master',
          id: 'remove',
        },
        updateControlAction: {
          appDEMethodId: 'update',
          appDataEntityId: 'web.master',
          id: 'update',
        },
        deformPages: [
          {
            layout: {
              columnCount: 24,
              layout: 'TABLE_24COL',
            },
            deformDetails: [
              {
                deformTabPages: [
                  {
                    layout: {
                      columnCount: 24,
                      layout: 'TABLE_24COL',
                    },
                    deformDetails: [
                      {
                        maskMode: 0,
                        appViewId: 'web.master_counter_exp_form',
                        parentDataJO: {
                          srfparentdename: 'MASTER',
                          SRFPARENTTYPE: 'CUSTOM',
                        },
                        codeName: 'tabpanel1_form_group_form_druipart',
                        detailStyle: 'DEFAULT',
                        detailType: 'DRUIPART',
                        layoutPos: {
                          colMD: 24,
                          layout: 'TABLE_24COL',
                        },
                        showCaption: true,
                        id: 'tabpanel1_form_group_form_druipart',
                      },
                    ],
                    caption: '表单',
                    codeName: 'tabpanel1_form_group_form',
                    counterId: 'form_group_form',
                    detailStyle: 'DEFAULT',
                    detailType: 'TABPAGE',
                    appCounterRefId: 'c08c472f59332aa507b4952a6d4e5c5f',
                    showCaption: true,
                    id: 'tabpanel1_form_group_form',
                  },
                  {
                    layout: {
                      columnCount: 24,
                      layout: 'TABLE_24COL',
                    },
                    deformDetails: [
                      {
                        maskMode: 0,
                        appViewId: 'web.master_counter_exp_grid',
                        parentDataJO: {
                          srfparentdename: 'MASTER',
                          SRFPARENTTYPE: 'CUSTOM',
                        },
                        codeName: 'tabpanel1_form_group_grid_druipart',
                        detailStyle: 'DEFAULT',
                        detailType: 'DRUIPART',
                        layoutPos: {
                          colMD: 24,
                          layout: 'TABLE_24COL',
                        },
                        showCaption: true,
                        id: 'tabpanel1_form_group_grid_druipart',
                      },
                    ],
                    caption: '表格',
                    codeName: 'tabpanel1_form_group_grid',
                    counterId: 'form_group_grid',
                    detailStyle: 'DEFAULT',
                    detailType: 'TABPAGE',
                    appCounterRefId: 'c08c472f59332aa507b4952a6d4e5c5f',
                    showCaption: true,
                    id: 'tabpanel1_form_group_grid',
                  },
                ],
                codeName: 'tabpanel1',
                detailStyle: 'DEFAULT',
                detailType: 'TABPANEL',
                layoutPos: {
                  colMD: 24,
                  layout: 'TABLE_24COL',
                },
                id: 'tabpanel1',
              },
              {
                dataType: 25,
                enableCond: 3,
                labelPos: 'LEFT',
                labelWidth: 130,
                noPrivDisplayMode: 1,
                appDEFieldId: 'id',
                editor: {
                  editorType: 'HIDDEN',
                  valueType: 'SIMPLE',
                  editable: true,
                  id: 'id',
                },
                allowEmpty: true,
                hidden: true,
                capLanguageRes: {
                  lanResTag: 'DEF.LNAME.MASTER.ID',
                },
                caption: '标识',
                codeName: 'id',
                detailStyle: 'DEFAULT',
                detailType: 'FORMITEM',
                layoutPos: {
                  colMD: 24,
                  layout: 'TABLE_24COL',
                },
                id: 'id',
              },
            ],
            caption: '基本信息',
            codeName: 'formpage1',
            detailStyle: 'DEFAULT',
            detailType: 'FORMPAGE',
            id: 'formpage1',
          },
        ],
        layout: {
          columnCount: 24,
          layout: 'TABLE_24COL',
        },
        tabHeaderPos: 'TOP',
        noTabHeader: true,
        autoLoad: true,
        showBusyIndicator: true,
        appCounterRefs: [
          {
            appCounter: {
              codeName: 'Counter',
              counterType: 'DEDR',
              getAppDEActionId: 'get_counter_data',
              appDataEntityId: 'web.master',
              timer: 60000,
              uniqueTag: 'Counter',
              name: '计数器',
              id: 'web.counter',
            },
            tag: 'c08c472f59332aa507b4952a6d4e5c5f',
            uniqueTag: 'Counter',
            id: 'c08c472f59332aa507b4952a6d4e5c5f',
          },
        ],
        codeName: 'main61',
        controlType: 'FORM',
        logicName: '计数器_表单内分组_表单',
        appDataEntityId: 'web.master',
        controlParam: {
          id: 'form',
        },
        modelId: '6d16ce78e944c8c759f9b0e809d30f7e',
        modelType: 'PSDEFORM_EDITFORM',
        name: 'form',
        id: 'web.master.main61',
      },
      {
        capLanguageRes: {
          lanResTag: 'DE.LNAME.MASTER',
        },
        caption: '计数器_表单内分组',
        codeName: 'counter_form_group_captionbar',
        controlType: 'CAPTIONBAR',
        appDataEntityId: 'web.master',
        controlParam: {},
        name: 'captionbar',
        id: 'counter_form_group_captionbar',
      },
    ],
    codeName: 'a4848cc7e09a45c5608',
    controlType: 'VIEWLAYOUTPANEL',
    logicName: 'counter_form_group',
    appDataEntityId: 'web.master',
    controlParam: {},
    modelId: 'db4140b4be24a3b710f78a7b43115961',
    modelType: 'PSSYSVIEWLAYOUTPANEL',
    name: 'layoutpanel',
    id: 'a4848cc7e09a45c5608',
  },
  title: '计数器_表单内分组',
  viewStyle: 'DEFAULT',
  viewType: 'DECUSTOMVIEW',
  enableDP: true,
  showCaptionBar: true,
  modelId: '69f8bf6361a314b70f410aa6287633de',
  modelType: 'PSAPPDEVIEW',
  name: 'MASTERcounter_form_group',
  id: 'web.master_counter_form_group',
};
