export default {
  tabLayout: 'FLOW',
  loadDefault: true,
  showDataInfoBar: true,
  deviewCodeName: 'calendar',
  deviewId: '7066cbb17a782b9424b40cd3bcbd9120',
  accUserMode: 3,
  capLanguageRes: {
    lanResTag: 'DE.LNAME.MASTER',
  },
  caption: '日历',
  codeName: 'master_calendar',
  appDataEntityId: 'web.master',
  appViewEngines: [
    {
      engineCat: 'VIEW',
      engineType: 'TabExpView',
      id: 'engine',
    },
  ],
  appViewMsgGroupId: 'calendar',
  controls: [
    {
      dedrtabPages: [
        {
          caption: '常规',
          appViewId: 'web.master_calendar_base',
          id: 'base',
        },
        {
          caption: '多数据',
          appViewId: 'web.master_calendar_multiple_data',
          id: 'multiple_data',
        },
        {
          caption: '项布局',
          appViewId: 'web.master_calendar_layout',
          id: 'layout',
        },
        {
          caption: '分组',
          appViewId: 'web.master_claendar_group',
          id: 'group',
        },
        {
          caption: '逻辑',
          appViewId: 'web.master_calendar_logic',
          id: 'logic',
        },
        {
          caption: '内置工具栏',
          appViewId: 'web.master_calendar_toolbar',
          id: 'toolbar',
        },
        {
          caption: '内置导航',
          appViewId: 'web.master_calendar_nav',
          id: 'built_in_nav',
        },
        {
          caption: '界面样式及图标',
          appViewId: 'web.master_calendar_style_icon',
          id: 'css',
        },
      ],
      dataRelationTag: 'calendar_DR',
      editItemCapLanguageRes: {
        lanResTag: 'DE.LNAME.MASTER',
      },
      editItemCaption: '主数据',
      uniqueTag: 'master_calendar__tabexppanel',
      autoLoad: true,
      showBusyIndicator: true,
      codeName: 'calendar_dr',
      controlType: 'DRTAB',
      appDataEntityId: 'web.master',
      controlParam: {
        id: 'tabexppanel',
      },
      modelId: '197e4f271a24c7351f6413c5ea11f677',
      modelType: 'PSDEDRTAB',
      name: 'tabexppanel',
      id: 'calendar_dr',
    },
    {
      capLanguageRes: {
        lanResTag: 'DE.LNAME.MASTER',
      },
      caption: '日历',
      codeName: 'calendar_captionbar',
      controlType: 'CAPTIONBAR',
      appDataEntityId: 'web.master',
      controlParam: {},
      name: 'captionbar',
      id: 'calendar_captionbar',
    },
  ],
  viewLayoutPanel: {
    layoutBodyOnly: true,
    useDefaultLayout: true,
    layoutPanel: true,
    codeName: 'layoutpanel',
    controlStyle: 'APPDETABEXPVIEW',
    controlType: 'VIEWLAYOUTPANEL',
    appDataEntityId: 'web.master',
    controlParam: {},
    id: 'layoutpanel',
  },
  title: '日历',
  viewStyle: 'DEFAULT',
  viewType: 'DETABEXPVIEW',
  enableDP: true,
  showCaptionBar: false,
  modelId: '397fd54627cb8d9e58be41f3ed747f6b',
  modelType: 'PSAPPDEVIEW',
  name: 'MASTERcalendar',
  id: 'web.master_calendar',
};
