export default {
  tabLayout: 'FLOW',
  loadDefault: true,
  showDataInfoBar: true,
  deviewCodeName: 'data',
  deviewId: 'dcd5a5551986a3bc7d23fba436822664',
  accUserMode: 3,
  capLanguageRes: {
    lanResTag: 'DE.LNAME.MASTER',
  },
  caption: '卡片',
  codeName: 'master_data',
  appDataEntityId: 'web.master',
  appViewEngines: [
    {
      engineCat: 'VIEW',
      engineType: 'TabExpView',
      id: 'engine',
    },
  ],
  appViewMsgGroupId: 'data',
  controls: [
    {
      dedrtabPages: [
        {
          caption: '常规',
          appViewId: 'web.master_card_base',
          id: 'base',
        },
        {
          caption: '看板模式',
          appViewId: 'web.master_card_kanbanview',
          id: 'kanban',
        },
        {
          caption: '布局',
          appViewId: 'web.master_card_layout',
          id: 'layout',
        },
        {
          caption: '逻辑',
          appViewId: 'web.master_card_panellogic',
          id: 'logic',
        },
        {
          caption: '分组',
          appViewId: 'web.master_card_group',
          id: 'group',
        },
        {
          caption: '内置工具栏',
          appViewId: 'web.master_doing_custom_view',
          id: 'toolbar',
        },
        {
          caption: '批操作工具栏',
          appViewId: 'web.master_doing_custom_view',
          id: 'batchtoolbar',
        },
        {
          caption: '值显示',
          appViewId: 'web.master_card_format',
          id: 'value_display',
        },
        {
          caption: '内置导航',
          appViewId: 'web.region_card_nav',
          id: 'built_in_nav',
        },
        {
          caption: '界面样式及图标',
          appViewId: 'web.master_card_cssandicon',
          id: 'css_and_icon',
        },
        {
          caption: '事件及调用',
          appViewId: 'web.master_card_logic',
          id: 'event_and_call',
        },
      ],
      dataRelationTag: 'data_DR',
      editItemCapLanguageRes: {
        lanResTag: 'DE.LNAME.MASTER',
      },
      editItemCaption: '主数据',
      uniqueTag: 'master_data__tabexppanel',
      autoLoad: true,
      showBusyIndicator: true,
      codeName: 'data_dr',
      controlType: 'DRTAB',
      appDataEntityId: 'web.master',
      controlParam: {
        id: 'tabexppanel',
      },
      modelId: '055214edbfe4fd7e5b5d4a45fd1199f5',
      modelType: 'PSDEDRTAB',
      name: 'tabexppanel',
      id: 'data_dr',
    },
    {
      capLanguageRes: {
        lanResTag: 'DE.LNAME.MASTER',
      },
      caption: '卡片',
      codeName: 'data_captionbar',
      controlType: 'CAPTIONBAR',
      appDataEntityId: 'web.master',
      controlParam: {},
      name: 'captionbar',
      id: 'data_captionbar',
    },
  ],
  viewLayoutPanel: {
    layoutBodyOnly: true,
    useDefaultLayout: true,
    layoutPanel: true,
    codeName: 'layoutpanel',
    controlStyle: 'APPDETABEXPVIEW',
    controlType: 'VIEWLAYOUTPANEL',
    appDataEntityId: 'web.master',
    controlParam: {},
    id: 'layoutpanel',
  },
  title: '卡片',
  viewStyle: 'DEFAULT',
  viewType: 'DETABEXPVIEW',
  enableDP: true,
  showCaptionBar: false,
  modelId: '8e89584f67364862cfabb395f703d015',
  modelType: 'PSAPPDEVIEW',
  name: 'MASTERdata',
  id: 'web.master_data',
};
