export default {
  deviewCodeName: 'calendar_logic',
  deviewId: '53113e0c126bb83a9bd340fa70c0e46c',
  accUserMode: 3,
  capLanguageRes: {
    lanResTag: 'DE.LNAME.MASTER',
  },
  caption: '日历_面板逻辑',
  codeName: 'master_calendar_logic',
  appDataEntityId: 'web.master',
  appViewMsgGroupId: 'calendar_logic',
  viewLayoutPanel: {
    viewProxyMode: true,
    layoutMode: 'FLEX',
    layout: {
      layout: 'FLEX',
    },
    rootPanelItems: [
      {
        actionGroupExtractMode: 'ITEM',
        panelItems: [
          {
            actionGroupExtractMode: 'ITEM',
            panelItems: [
              {
                actionGroupExtractMode: 'ITEM',
                panelItems: [
                  {
                    actionGroupExtractMode: 'ITEM',
                    panelItems: [
                      {
                        caption: '日历',
                        itemStyle: 'DEFAULT',
                        itemType: 'CTRLPOS',
                        layoutPos: {
                          shrink: 1,
                          layout: 'FLEX',
                        },
                        showCaption: true,
                        id: 'calendar',
                      },
                    ],
                    layout: {
                      layout: 'FLEX',
                    },
                    dataRegionType: 'INHERIT',
                    caption: '容器',
                    itemStyle: 'DEFAULT',
                    itemType: 'CONTAINER',
                    layoutPos: {
                      shrink: 1,
                      layout: 'FLEX',
                    },
                    id: 'container',
                  },
                  {
                    actionGroupExtractMode: 'ITEM',
                    panelItems: [
                      {
                        actionGroupExtractMode: 'ITEM',
                        panelItems: [
                          {
                            caption: '日历',
                            itemStyle: 'DEFAULT',
                            itemType: 'CTRLPOS',
                            layoutPos: {
                              shrink: 1,
                              layout: 'FLEX',
                            },
                            showCaption: true,
                            id: 'calendar1',
                          },
                        ],
                        layout: {
                          layout: 'FLEX',
                        },
                        dataRegionType: 'INHERIT',
                        caption: '容器',
                        itemStyle: 'DEFAULT',
                        itemType: 'CONTAINER',
                        layoutPos: {
                          shrink: 1,
                          layout: 'FLEX',
                        },
                        id: 'container1',
                      },
                    ],
                    predefinedType: 'CONTAINER_GROUP',
                    layout: {
                      layout: 'FLEX',
                    },
                    dataRegionType: 'INHERIT',
                    caption: '上下文菜单',
                    itemStyle: 'DEFAULT',
                    itemType: 'CONTAINER',
                    layoutPos: {
                      shrink: 1,
                      layout: 'FLEX',
                    },
                    showCaption: true,
                    id: 'container_group1',
                  },
                ],
                predefinedType: 'CONTAINER_GROUP',
                layout: {
                  layout: 'FLEX',
                },
                dataRegionType: 'INHERIT',
                caption: '拖动编辑',
                itemStyle: 'DEFAULT',
                itemType: 'CONTAINER',
                layoutPos: {
                  layoutPos: 'CENTER',
                  layout: 'BORDER',
                },
                showCaption: true,
                id: 'container_group',
              },
            ],
            predefinedType: 'CONTAINER_SCROLL_MAIN',
            layout: {
              layout: 'BORDER',
            },
            dataRegionType: 'INHERIT',
            caption: '面板容器',
            itemStyle: 'DEFAULT',
            itemType: 'CONTAINER',
            layoutPos: {
              layoutPos: 'CENTER',
              layout: 'BORDER',
            },
            showCaption: true,
            id: 'container_scroll_main',
          },
        ],
        predefinedType: 'CONTAINER_SCROLL',
        layout: {
          layout: 'BORDER',
        },
        dataRegionType: 'INHERIT',
        caption: '滚动条容器',
        itemStyle: 'DEFAULT',
        itemType: 'CONTAINER',
        layoutPos: {
          shrink: 1,
          layout: 'FLEX',
        },
        id: 'container_scroll',
      },
    ],
    layoutPanel: true,
    controls: [
      {
        calendarStyle: 'MONTH',
        groupMode: 'NONE',
        legendPos: 'NONE',
        sysCalendarItems: [
          {
            beginTimeAppDEFieldId: 'date',
            endTimeAppDEFieldId: 'date',
            idAppDEFieldId: 'id',
            itemStyle: 'DEFAULT',
            itemType: 'date',
            appDEDataSetId: 'fetch_default',
            textAppDEFieldId: 'name',
            enableEdit: true,
            appDataEntityId: 'web.master',
            id: 'date',
          },
        ],
        navViewPos: 'NONE',
        autoLoad: true,
        showBusyIndicator: true,
        codeName: 'claendar_logic_drag',
        controlType: 'CALENDAR',
        logicName: '日历_面板逻辑_拖动编辑',
        appDataEntityId: 'web.master',
        controlParam: {
          id: 'calendar',
        },
        modelId: '4e487bb8ee4954b9f5d0b282502fcca8',
        modelType: 'PSSYSCALENDAR',
        name: 'calendar',
        id: 'web.master.claendar_logic_drag',
      },
      {
        calendarStyle: 'MONTH',
        groupMode: 'NONE',
        legendPos: 'NONE',
        sysCalendarItems: [
          {
            beginTimeAppDEFieldId: 'date',
            endTimeAppDEFieldId: 'date',
            idAppDEFieldId: 'id',
            itemStyle: 'DEFAULT',
            itemType: 'date',
            appDEDataSetId: 'fetch_default',
            decontextMenu: {
              detoolbarItems: [
                {
                  actionLevel: 100,
                  noPrivDisplayMode: 2,
                  uiactionId: 'gridview_removeaction',
                  uiactionTarget: 'MULTIKEY',
                  valid: true,
                  capLanguageRes: {
                    lanResTag: 'TBB.TEXT.*.REMOVE',
                  },
                  caption: '删除',
                  itemType: 'DEUIACTION',
                  sysImage: {
                    cssClass: 'fa fa-remove',
                    glyph: 'xf00d@FontAwesome',
                  },
                  tooltip: '删除',
                  tooltipLanguageRes: {
                    lanResTag: 'TBB.TOOLTIP.*.REMOVE',
                  },
                  showCaption: true,
                  showIcon: true,
                  id: 'deuiaction2',
                },
              ],
              codeName: 'calendar_logic_cm',
              controlType: 'CONTEXTMENU',
              logicName: '日历_上下文菜单',
              appDataEntityId: 'web.master',
              controlParam: {
                id: 'cm',
              },
              modelId: 'eeea9e0c46b3ed545a387935c0786683',
              modelType: 'PSDETOOLBAR',
              name: 'cm',
              id: 'calendar_logic_cm',
            },
            textAppDEFieldId: 'name',
            appDataEntityId: 'web.master',
            id: 'date',
          },
        ],
        navViewPos: 'NONE',
        autoLoad: true,
        showBusyIndicator: true,
        controls: [
          {
            detoolbarItems: [
              {
                actionLevel: 100,
                noPrivDisplayMode: 2,
                uiactionId: 'gridview_removeaction',
                uiactionTarget: 'MULTIKEY',
                valid: true,
                capLanguageRes: {
                  lanResTag: 'TBB.TEXT.*.REMOVE',
                },
                caption: '删除',
                itemType: 'DEUIACTION',
                sysImage: {
                  cssClass: 'fa fa-remove',
                  glyph: 'xf00d@FontAwesome',
                },
                tooltip: '删除',
                tooltipLanguageRes: {
                  lanResTag: 'TBB.TOOLTIP.*.REMOVE',
                },
                showCaption: true,
                showIcon: true,
                id: 'deuiaction2',
              },
            ],
            codeName: 'calendar_logic_cm',
            controlType: 'CONTEXTMENU',
            logicName: '日历_上下文菜单',
            appDataEntityId: 'web.master',
            controlParam: {
              id: 'cm',
            },
            modelId: 'eeea9e0c46b3ed545a387935c0786683',
            modelType: 'PSDETOOLBAR',
            name: 'cm',
            id: 'calendar_logic_cm',
          },
        ],
        codeName: 'calendar_logic_context_menu',
        controlType: 'CALENDAR',
        logicName: '日历_面板逻辑_上下文菜单',
        appDataEntityId: 'web.master',
        controlParam: {
          id: 'calendar1',
        },
        modelId: '7103c1effc46a00b47d70e3ac19e7ce5',
        modelType: 'PSSYSCALENDAR',
        name: 'calendar1',
        id: 'web.master.calendar_logic_context_menu',
      },
      {
        capLanguageRes: {
          lanResTag: 'DE.LNAME.MASTER',
        },
        caption: '日历_面板逻辑',
        codeName: 'calendar_logic_captionbar',
        controlType: 'CAPTIONBAR',
        appDataEntityId: 'web.master',
        controlParam: {},
        name: 'captionbar',
        id: 'calendar_logic_captionbar',
      },
    ],
    codeName: 'usr0515477750',
    controlType: 'VIEWLAYOUTPANEL',
    logicName: '日历_面板逻辑布局面板',
    appDataEntityId: 'web.master',
    controlParam: {},
    modelId: '0c7518758674223ab1a59d39239a5a31',
    modelType: 'PSSYSVIEWLAYOUTPANEL',
    name: 'layoutpanel',
    id: 'usr0515477750',
  },
  title: '日历_面板逻辑',
  viewStyle: 'DEFAULT',
  viewType: 'DECUSTOMVIEW',
  enableDP: true,
  showCaptionBar: false,
  modelId: '57399b77262f9cbb619b946c52bc49d4',
  modelType: 'PSAPPDEVIEW',
  name: 'MASTERcalendar_logic',
  id: 'web.master_calendar_logic',
};
