export default {
  enableDirtyChecking: true,
  showDataInfoBar: true,
  xdataControlName: 'form',
  loadDefault: true,
  deviewCodeName: 'editor_data_picker',
  deviewId: 'f9ad15798713a291505b9007255bef5f',
  accUserMode: 3,
  capLanguageRes: {
    lanResTag: 'DE.LNAME.MASTER',
  },
  caption: '编辑器_数据选择',
  codeName: 'master_editor_data_picker',
  appDataEntityId: 'web.master',
  appViewEngines: [
    {
      engineCat: 'VIEW',
      engineType: 'EditView',
      id: 'engine',
    },
  ],
  appViewMsgGroupId: 'editor_data_picker',
  controls: [
    {
      xdataControlName: 'form',
      codeName: 'editor_data_picker_toolbar',
      controlType: 'TOOLBAR',
      logicName: '编辑器_数据选择_工具栏',
      appDataEntityId: 'web.master',
      controlParam: {
        id: 'toolbar',
      },
      modelId: 'aadc23de8b984c80943c452341d89d85',
      modelType: 'PSDETOOLBAR',
      name: 'toolbar',
      id: 'editor_data_picker_toolbar',
    },
    {
      createControlAction: {
        appDEMethodId: 'create',
        appDataEntityId: 'web.master',
        id: 'create',
      },
      getDraftFromControlAction: {
        appDataEntityId: 'web.master',
        id: 'loaddraftfrom',
      },
      getDraftControlAction: {
        appDEMethodId: 'get_draft',
        appDataEntityId: 'web.master',
        id: 'loaddraft',
      },
      getControlAction: {
        appDEMethodId: 'get',
        appDataEntityId: 'web.master',
        id: 'load',
      },
      removeControlAction: {
        appDEMethodId: 'remove',
        appDataEntityId: 'web.master',
        id: 'remove',
      },
      updateControlAction: {
        appDEMethodId: 'update',
        appDataEntityId: 'web.master',
        id: 'update',
      },
      deformPages: [
        {
          layout: {
            columnCount: 24,
            layout: 'TABLE_24COL',
          },
          deformDetails: [
            {
              layout: {
                columnCount: 24,
                layout: 'TABLE_24COL',
              },
              deformDetails: [
                {
                  dataType: 25,
                  enableCond: 3,
                  labelPos: 'NONE',
                  noPrivDisplayMode: 1,
                  editor: {
                    enablePickupView: true,
                    singleSelect: true,
                    pickupAppViewId: 'web.master_depickup_view',
                    appDEACModeId: 'default',
                    appDEDataSetId: 'fetch_default',
                    appDataEntityId: 'web.master',
                    enableAC: true,
                    forceSelection: true,
                    showTrigger: true,
                    valueItemName: 'formitem6',
                    editorParams: {
                      AC: 'TRUE',
                      PICKUPVIEW: 'TRUE',
                    },
                    editorType: 'PICKER',
                    editorItems: [
                      {
                        id: 'formitem6',
                      },
                    ],
                    placeHolder: '占位提示-数据选择',
                    valueType: 'SIMPLE',
                    editable: true,
                    id: 'formitem',
                  },
                  allowEmpty: true,
                  caption: '数据选择',
                  codeName: 'formitem',
                  detailStyle: 'DEFAULT',
                  detailType: 'FORMITEM',
                  layoutPos: {
                    colLG: 12,
                    colMD: 12,
                    layout: 'TABLE_24COL',
                  },
                  id: 'formitem',
                },
                {
                  dataType: 25,
                  enableCond: 3,
                  labelPos: 'LEFT',
                  labelWidth: 130,
                  noPrivDisplayMode: 1,
                  editor: {
                    editorType: 'TEXTBOX',
                    valueType: 'SIMPLE',
                    editable: true,
                    id: 'formitem6',
                  },
                  allowEmpty: true,
                  caption: '选取值项',
                  codeName: 'formitem6',
                  detailStyle: 'DEFAULT',
                  detailType: 'FORMITEM',
                  layoutPos: {
                    colLG: 12,
                    colMD: 12,
                    layout: 'TABLE_24COL',
                  },
                  showCaption: true,
                  id: 'formitem6',
                },
              ],
              caption: '数据选择',
              codeName: 'group1',
              detailStyle: 'DEFAULT',
              detailType: 'GROUPPANEL',
              layoutPos: {
                colMD: 24,
                layout: 'TABLE_24COL',
              },
              showCaption: true,
              id: 'group1',
            },
            {
              layout: {
                columnCount: 24,
                layout: 'TABLE_24COL',
              },
              deformDetails: [
                {
                  dataType: 25,
                  enableCond: 3,
                  labelPos: 'NONE',
                  noPrivDisplayMode: 1,
                  editor: {
                    enablePickupView: true,
                    singleSelect: true,
                    pickupAppViewId: 'web.master_depickup_view',
                    appDEACModeId: 'default',
                    appDEDataSetId: 'fetch_default',
                    appDataEntityId: 'web.master',
                    forceSelection: true,
                    showTrigger: true,
                    valueItemName: 'formitem7',
                    editorParams: {
                      AC: 'FALSE',
                      TRIGGER: 'TRUE',
                      PICKUPVIEW: 'TRUE',
                    },
                    editorType: 'PICKEREX_NOAC',
                    editorItems: [
                      {
                        id: 'formitem7',
                      },
                    ],
                    placeHolder: '数据选择（无AC）',
                    valueType: 'SIMPLE',
                    editable: true,
                    id: 'formitem1',
                  },
                  allowEmpty: true,
                  caption: '数据选择（无AC）',
                  codeName: 'formitem1',
                  detailStyle: 'DEFAULT',
                  detailType: 'FORMITEM',
                  layoutPos: {
                    colMD: 24,
                    layout: 'TABLE_24COL',
                  },
                  id: 'formitem1',
                },
                {
                  dataType: 25,
                  enableCond: 3,
                  labelPos: 'LEFT',
                  labelWidth: 130,
                  noPrivDisplayMode: 1,
                  editor: {
                    editorType: 'HIDDEN',
                    valueType: 'SIMPLE',
                    editable: true,
                    id: 'formitem7',
                  },
                  allowEmpty: true,
                  hidden: true,
                  codeName: 'formitem7',
                  detailStyle: 'DEFAULT',
                  detailType: 'FORMITEM',
                  layoutPos: {
                    colMD: 24,
                    layout: 'TABLE_24COL',
                  },
                  id: 'formitem7',
                },
              ],
              caption: '数据选择（无AC）',
              codeName: 'grouppanel1',
              detailStyle: 'DEFAULT',
              detailType: 'GROUPPANEL',
              layoutPos: {
                colMD: 24,
                layout: 'TABLE_24COL',
              },
              showCaption: true,
              id: 'grouppanel1',
            },
            {
              layout: {
                columnCount: 24,
                layout: 'TABLE_24COL',
              },
              deformDetails: [
                {
                  dataType: 25,
                  enableCond: 3,
                  labelPos: 'NONE',
                  noPrivDisplayMode: 1,
                  editor: {
                    linkAppViewId: 'web.region_info_view',
                    enableLinkView: true,
                    enablePickupView: true,
                    singleSelect: true,
                    pickupAppViewId: 'web.region_pickup_view',
                    forceSelection: true,
                    showTrigger: true,
                    valueItemName: 'formitem8',
                    editorParams: {
                      LINKVIEW: 'TRUE',
                      AC: 'FALSE',
                      TRIGGER: 'TRUE',
                      PICKUPVIEW: 'TRUE',
                    },
                    editorType: 'PICKEREX_NOAC_LINK',
                    editorItems: [
                      {
                        id: 'formitem8',
                      },
                    ],
                    placeHolder: '数据选择（无AC、数据链接）',
                    valueType: 'SIMPLE',
                    editable: true,
                    id: 'formitem2',
                  },
                  allowEmpty: true,
                  caption: '数据选择（无AC、数据链接）',
                  codeName: 'formitem2',
                  detailStyle: 'DEFAULT',
                  detailType: 'FORMITEM',
                  layoutPos: {
                    colMD: 24,
                    layout: 'TABLE_24COL',
                  },
                  id: 'formitem2',
                },
                {
                  dataType: 25,
                  enableCond: 3,
                  labelPos: 'LEFT',
                  labelWidth: 130,
                  noPrivDisplayMode: 1,
                  editor: {
                    editorType: 'HIDDEN',
                    valueType: 'SIMPLE',
                    editable: true,
                    id: 'formitem8',
                  },
                  allowEmpty: true,
                  hidden: true,
                  codeName: 'formitem8',
                  detailStyle: 'DEFAULT',
                  detailType: 'FORMITEM',
                  layoutPos: {
                    colMD: 24,
                    layout: 'TABLE_24COL',
                  },
                  id: 'formitem8',
                },
              ],
              caption: '数据选择（无AC、数据链接）',
              codeName: 'grouppanel2',
              detailStyle: 'DEFAULT',
              detailType: 'GROUPPANEL',
              layoutPos: {
                colMD: 24,
                layout: 'TABLE_24COL',
              },
              showCaption: true,
              id: 'grouppanel2',
            },
            {
              layout: {
                columnCount: 24,
                layout: 'TABLE_24COL',
              },
              deformDetails: [
                {
                  dataType: 25,
                  enableCond: 3,
                  labelPos: 'NONE',
                  noPrivDisplayMode: 1,
                  editor: {
                    linkAppViewId: 'web.master_modal_edit_view',
                    enableLinkView: true,
                    singleSelect: true,
                    appDEACModeId: 'default',
                    appDEDataSetId: 'fetch_default',
                    appDataEntityId: 'web.master',
                    enableAC: true,
                    forceSelection: true,
                    showTrigger: true,
                    valueItemName: 'formitem9',
                    editorParams: {
                      LINKVIEW: 'TRUE',
                      AC: 'TRUE',
                      TRIGGER: 'TRUE',
                      PICKUPVIEW: 'FALSE',
                    },
                    editorType: 'PICKEREX_TRIGGER_LINK',
                    editorItems: [
                      {
                        id: 'formitem9',
                      },
                    ],
                    placeHolder: '数据选择（下拉、数据链接）',
                    valueType: 'SIMPLE',
                    editable: true,
                    id: 'formitem3',
                  },
                  allowEmpty: true,
                  caption: '数据选择（下拉、数据链接）',
                  codeName: 'formitem3',
                  detailStyle: 'DEFAULT',
                  detailType: 'FORMITEM',
                  layoutPos: {
                    colMD: 24,
                    layout: 'TABLE_24COL',
                  },
                  id: 'formitem3',
                },
                {
                  dataType: 25,
                  enableCond: 3,
                  labelPos: 'LEFT',
                  labelWidth: 130,
                  noPrivDisplayMode: 1,
                  editor: {
                    editorType: 'HIDDEN',
                    valueType: 'SIMPLE',
                    editable: true,
                    id: 'formitem9',
                  },
                  allowEmpty: true,
                  hidden: true,
                  codeName: 'formitem9',
                  detailStyle: 'DEFAULT',
                  detailType: 'FORMITEM',
                  layoutPos: {
                    colMD: 24,
                    layout: 'TABLE_24COL',
                  },
                  id: 'formitem9',
                },
              ],
              caption: '数据选择（下拉、数据链接）',
              codeName: 'grouppanel3',
              detailStyle: 'DEFAULT',
              detailType: 'GROUPPANEL',
              layoutPos: {
                colMD: 24,
                layout: 'TABLE_24COL',
              },
              showCaption: true,
              id: 'grouppanel3',
            },
            {
              layout: {
                columnCount: 24,
                layout: 'TABLE_24COL',
              },
              deformDetails: [
                {
                  dataType: 25,
                  enableCond: 3,
                  labelPos: 'NONE',
                  noPrivDisplayMode: 1,
                  editor: {
                    linkAppViewId: 'web.master_modal_edit_view',
                    enableLinkView: true,
                    enablePickupView: true,
                    singleSelect: true,
                    appDEACModeId: 'default',
                    appDEDataSetId: 'fetch_default',
                    appDataEntityId: 'web.master',
                    enableAC: true,
                    forceSelection: true,
                    valueItemName: 'formitem10',
                    editorParams: {
                      LINKVIEW: 'TRUE',
                      AC: 'TRUE',
                      TRIGGER: 'FALSE',
                      PICKUPVIEW: 'TRUE',
                    },
                    editorType: 'PICKEREX_LINK',
                    editorItems: [
                      {
                        id: 'formitem10',
                      },
                    ],
                    placeHolder: '数据选择（数据链接）',
                    valueType: 'SIMPLE',
                    editable: true,
                    id: 'formitem4',
                  },
                  allowEmpty: true,
                  caption: '数据选择（数据链接）',
                  codeName: 'formitem4',
                  detailStyle: 'DEFAULT',
                  detailType: 'FORMITEM',
                  layoutPos: {
                    colMD: 24,
                    layout: 'TABLE_24COL',
                  },
                  id: 'formitem4',
                },
                {
                  dataType: 25,
                  enableCond: 3,
                  labelPos: 'LEFT',
                  labelWidth: 130,
                  noPrivDisplayMode: 1,
                  editor: {
                    editorType: 'HIDDEN',
                    valueType: 'SIMPLE',
                    editable: true,
                    id: 'formitem10',
                  },
                  allowEmpty: true,
                  hidden: true,
                  codeName: 'formitem10',
                  detailStyle: 'DEFAULT',
                  detailType: 'FORMITEM',
                  layoutPos: {
                    colMD: 24,
                    layout: 'TABLE_24COL',
                  },
                  id: 'formitem10',
                },
              ],
              caption: '数据选择（数据链接）',
              codeName: 'grouppanel4',
              detailStyle: 'DEFAULT',
              detailType: 'GROUPPANEL',
              layoutPos: {
                colMD: 24,
                layout: 'TABLE_24COL',
              },
              showCaption: true,
              id: 'grouppanel4',
            },
            {
              layout: {
                columnCount: 24,
                layout: 'TABLE_24COL',
              },
              deformDetails: [
                {
                  dataType: 25,
                  enableCond: 3,
                  labelPos: 'NONE',
                  noPrivDisplayMode: 1,
                  editor: {
                    singleSelect: true,
                    pickupAppViewId: 'web.master_depickup_view',
                    appDEACModeId: 'default',
                    appDEDataSetId: 'fetch_default',
                    appDataEntityId: 'web.master',
                    enableAC: true,
                    forceSelection: true,
                    valueItemName: 'formitem11',
                    editorParams: {
                      AC: 'TRUE',
                      TRIGGER: 'FALSE',
                      PICKUPVIEW: 'FALSE',
                    },
                    editorType: 'PICKEREX_NOBUTTON',
                    editorItems: [
                      {
                        id: 'formitem11',
                      },
                    ],
                    placeHolder: '数据选择（无按钮）',
                    valueType: 'SIMPLE',
                    editable: true,
                    id: 'formitem5',
                  },
                  allowEmpty: true,
                  caption: '数据选择（无按钮）',
                  codeName: 'formitem5',
                  detailStyle: 'DEFAULT',
                  detailType: 'FORMITEM',
                  layoutPos: {
                    colMD: 24,
                    layout: 'TABLE_24COL',
                  },
                  id: 'formitem5',
                },
                {
                  dataType: 25,
                  enableCond: 3,
                  labelPos: 'LEFT',
                  labelWidth: 130,
                  noPrivDisplayMode: 1,
                  editor: {
                    editorType: 'HIDDEN',
                    valueType: 'SIMPLE',
                    editable: true,
                    id: 'formitem11',
                  },
                  allowEmpty: true,
                  hidden: true,
                  codeName: 'formitem11',
                  detailStyle: 'DEFAULT',
                  detailType: 'FORMITEM',
                  layoutPos: {
                    colMD: 24,
                    layout: 'TABLE_24COL',
                  },
                  id: 'formitem11',
                },
              ],
              caption: '数据选择（无按钮）',
              codeName: 'grouppanel5',
              detailStyle: 'DEFAULT',
              detailType: 'GROUPPANEL',
              layoutPos: {
                colMD: 24,
                layout: 'TABLE_24COL',
              },
              showCaption: true,
              id: 'grouppanel5',
            },
            {
              layout: {
                columnCount: 24,
                layout: 'TABLE_24COL',
              },
              deformDetails: [
                {
                  dataType: 25,
                  enableCond: 3,
                  labelPos: 'LEFT',
                  labelWidth: 30,
                  noPrivDisplayMode: 1,
                  editor: {
                    singleSelect: true,
                    appDEACModeId: 'default',
                    appDEDataSetId: 'fetch_default',
                    appDataEntityId: 'web.region',
                    enableAC: true,
                    forceSelection: true,
                    showTrigger: true,
                    valueItemName: 'province_id',
                    editorParams: {
                      'SRFNAVPARAM.n_level_eq': '1',
                      AC: 'TRUE',
                      TRIGGER: 'TRUE',
                      PICKUPVIEW: 'FALSE',
                    },
                    editorType: 'PICKEREX_TRIGGER',
                    editorItems: [
                      {
                        id: 'province_id',
                      },
                    ],
                    valueType: 'SIMPLE',
                    editable: true,
                    navigateParams: [
                      {
                        key: 'n_level_eq',
                        value: '1',
                        rawValue: true,
                        id: 'n_level_eq',
                      },
                    ],
                    id: 'province',
                  },
                  allowEmpty: true,
                  caption: '省',
                  codeName: 'province',
                  detailStyle: 'DEFAULT',
                  detailType: 'FORMITEM',
                  layoutPos: {
                    colLG: 5,
                    colMD: 5,
                    layout: 'TABLE_24COL',
                  },
                  showCaption: true,
                  id: 'province',
                },
                {
                  dataType: 25,
                  enableCond: 3,
                  labelPos: 'LEFT',
                  labelWidth: 30,
                  noPrivDisplayMode: 1,
                  editor: {
                    singleSelect: true,
                    appDEACModeId: 'default',
                    appDEDataSetId: 'fetch_default',
                    appDataEntityId: 'web.region',
                    enableAC: true,
                    forceSelection: true,
                    showTrigger: true,
                    valueItemName: 'city_id',
                    editorParams: {
                      AC: 'TRUE',
                      'SRFNAVPARAM.n_parent_id_eq': '%province_id%',
                      TRIGGER: 'TRUE',
                      PICKUPVIEW: 'FALSE',
                    },
                    editorType: 'PICKEREX_TRIGGER',
                    editorItems: [
                      {
                        id: 'city_id',
                      },
                    ],
                    valueType: 'SIMPLE',
                    editable: true,
                    navigateParams: [
                      {
                        key: 'n_parent_id_eq',
                        value: 'province_id',
                        id: 'n_parent_id_eq',
                      },
                    ],
                    id: 'city',
                  },
                  resetItemNames: ['province_id'],
                  allowEmpty: true,
                  caption: '市',
                  codeName: 'city',
                  detailStyle: 'DEFAULT',
                  detailType: 'FORMITEM',
                  defdgroupLogics: [
                    {
                      logicCat: 'ITEMENABLE',
                      relatedDetailNames: ['province_id'],
                      groupOP: 'AND',
                      defdlogics: [
                        {
                          condOP: 'ISNOTNULL',
                          defdname: 'province_id',
                          logicType: 'SINGLE',
                          name: 'province_id值不为空(NotNil)',
                          id: 'province_id值不为空(notnil)',
                        },
                      ],
                      logicType: 'GROUP',
                    },
                  ],
                  layoutPos: {
                    colLG: 5,
                    colMD: 5,
                    layout: 'TABLE_24COL',
                  },
                  showCaption: true,
                  id: 'city',
                },
                {
                  dataType: 25,
                  enableCond: 3,
                  labelPos: 'LEFT',
                  labelWidth: 30,
                  noPrivDisplayMode: 1,
                  editor: {
                    singleSelect: true,
                    appDEACModeId: 'default',
                    appDEDataSetId: 'fetch_default',
                    appDataEntityId: 'web.region',
                    enableAC: true,
                    forceSelection: true,
                    showTrigger: true,
                    valueItemName: 'district_id',
                    editorParams: {
                      AC: 'TRUE',
                      'SRFNAVPARAM.n_parent_id_eq': '%city_id%',
                      TRIGGER: 'TRUE',
                      PICKUPVIEW: 'FALSE',
                    },
                    editorType: 'PICKEREX_TRIGGER',
                    editorItems: [
                      {
                        id: 'district_id',
                      },
                    ],
                    valueType: 'SIMPLE',
                    editable: true,
                    navigateParams: [
                      {
                        key: 'n_parent_id_eq',
                        value: 'city_id',
                        id: 'n_parent_id_eq',
                      },
                    ],
                    id: 'district',
                  },
                  resetItemNames: ['city_id'],
                  allowEmpty: true,
                  caption: '区',
                  codeName: 'district',
                  detailStyle: 'DEFAULT',
                  detailType: 'FORMITEM',
                  defdgroupLogics: [
                    {
                      logicCat: 'ITEMENABLE',
                      relatedDetailNames: ['city_id'],
                      groupOP: 'AND',
                      defdlogics: [
                        {
                          condOP: 'ISNOTNULL',
                          defdname: 'city_id',
                          logicType: 'SINGLE',
                          name: 'city_id值不为空(NotNil)',
                          id: 'city_id值不为空(notnil)',
                        },
                      ],
                      logicType: 'GROUP',
                    },
                  ],
                  layoutPos: {
                    colLG: 5,
                    colMD: 5,
                    layout: 'TABLE_24COL',
                  },
                  showCaption: true,
                  id: 'district',
                },
                {
                  dataType: 25,
                  enableCond: 3,
                  labelPos: 'LEFT',
                  labelWidth: 130,
                  noPrivDisplayMode: 1,
                  editor: {
                    editorType: 'HIDDEN',
                    valueType: 'SIMPLE',
                    editable: true,
                    id: 'province_id',
                  },
                  allowEmpty: true,
                  hidden: true,
                  codeName: 'province_id',
                  detailStyle: 'DEFAULT',
                  detailType: 'FORMITEM',
                  layoutPos: {
                    colMD: 24,
                    layout: 'TABLE_24COL',
                  },
                  id: 'province_id',
                },
                {
                  dataType: 25,
                  enableCond: 3,
                  labelPos: 'LEFT',
                  labelWidth: 130,
                  noPrivDisplayMode: 1,
                  editor: {
                    editorType: 'HIDDEN',
                    valueType: 'SIMPLE',
                    editable: true,
                    id: 'city_id',
                  },
                  resetItemNames: ['province_id'],
                  allowEmpty: true,
                  hidden: true,
                  codeName: 'city_id',
                  detailStyle: 'DEFAULT',
                  detailType: 'FORMITEM',
                  layoutPos: {
                    colMD: 24,
                    layout: 'TABLE_24COL',
                  },
                  id: 'city_id',
                },
                {
                  dataType: 25,
                  enableCond: 3,
                  labelPos: 'LEFT',
                  labelWidth: 130,
                  noPrivDisplayMode: 1,
                  editor: {
                    editorType: 'HIDDEN',
                    valueType: 'SIMPLE',
                    editable: true,
                    id: 'district_id',
                  },
                  resetItemNames: ['city_id'],
                  allowEmpty: true,
                  hidden: true,
                  codeName: 'district_id',
                  detailStyle: 'DEFAULT',
                  detailType: 'FORMITEM',
                  layoutPos: {
                    colMD: 24,
                    layout: 'TABLE_24COL',
                  },
                  id: 'district_id',
                },
              ],
              caption: '级联数据选择',
              codeName: 'grouppanel21',
              detailStyle: 'DEFAULT',
              detailType: 'GROUPPANEL',
              layoutPos: {
                colMD: 24,
                layout: 'TABLE_24COL',
              },
              showCaption: true,
              id: 'grouppanel21',
            },
            {
              layout: {
                columnCount: 24,
                layout: 'TABLE_24COL',
              },
              deformDetails: [
                {
                  dataType: 25,
                  enableCond: 3,
                  labelPos: 'NONE',
                  noPrivDisplayMode: 1,
                  editor: {
                    enablePickupView: true,
                    singleSelect: true,
                    appDEACModeId: 'default',
                    appDEDataSetId: 'fetch_default',
                    appDataEntityId: 'web.region',
                    enableAC: true,
                    forceSelection: true,
                    showTrigger: true,
                    editorParams: {
                      buttontexts: '["移除","新增"]',
                      'SRFNAVPARAM.size': '50',
                      remotesearch: 'true',
                      valueType: 'SIMPLES',
                      objectNameField: 'name',
                      AC: 'TRUE',
                      titles: '["可选区划", "已选区划"]',
                      objectIdField: 'id',
                      PICKUPVIEW: 'TRUE',
                    },
                    editorStyle: 'TRANSFER_PICKER',
                    editorType: 'PICKER',
                    objectIdField: 'id',
                    objectNameField: 'name',
                    valueType: 'SIMPLES',
                    editable: true,
                    navigateParams: [
                      {
                        key: 'size',
                        value: '50',
                        rawValue: true,
                        id: 'size',
                      },
                    ],
                    id: 'formitem12',
                  },
                  allowEmpty: true,
                  caption: '区划',
                  codeName: 'formitem12',
                  detailStyle: 'DEFAULT',
                  detailType: 'FORMITEM',
                  layoutPos: {
                    colMD: 24,
                    layout: 'TABLE_24COL',
                  },
                  id: 'formitem12',
                },
              ],
              caption: '穿梭框',
              codeName: 'grouppanel6',
              detailStyle: 'DEFAULT',
              detailType: 'GROUPPANEL',
              layoutPos: {
                colMD: 24,
                layout: 'TABLE_24COL',
              },
              showCaption: true,
              id: 'grouppanel6',
            },
            {
              dataType: 25,
              enableCond: 3,
              labelPos: 'LEFT',
              labelWidth: 130,
              noPrivDisplayMode: 1,
              appDEFieldId: 'id',
              editor: {
                editorType: 'HIDDEN',
                valueType: 'SIMPLE',
                editable: true,
                id: 'id',
              },
              allowEmpty: true,
              hidden: true,
              capLanguageRes: {
                lanResTag: 'DEF.LNAME.MASTER.ID',
              },
              caption: '标识',
              codeName: 'id',
              detailStyle: 'DEFAULT',
              detailType: 'FORMITEM',
              layoutPos: {
                colMD: 24,
                layout: 'TABLE_24COL',
              },
              id: 'id',
            },
          ],
          caption: '数据选择',
          codeName: 'formpage1',
          detailStyle: 'DEFAULT',
          detailType: 'FORMPAGE',
          id: 'formpage1',
        },
      ],
      layout: {
        columnCount: 24,
        layout: 'TABLE_24COL',
      },
      tabHeaderPos: 'TOP',
      noTabHeader: true,
      autoLoad: true,
      showBusyIndicator: true,
      codeName: 'main43',
      controlType: 'FORM',
      logicName: '编辑器_数据选择_表单',
      appDataEntityId: 'web.master',
      controlParam: {
        id: 'form',
      },
      modelId: '736995ae370ca4a921bbf974ead6cc1e',
      modelType: 'PSDEFORM_EDITFORM',
      name: 'form',
      id: 'web.master.main43',
    },
    {
      codeName: 'editor_data_picker_datainfobar',
      controlType: 'DATAINFOBAR',
      appDataEntityId: 'web.master',
      controlParam: {
        id: 'datainfobar',
      },
      name: 'datainfobar',
      id: 'editor_data_picker_datainfobar',
    },
    {
      capLanguageRes: {
        lanResTag: 'DE.LNAME.MASTER',
      },
      caption: '编辑器_数据选择',
      codeName: 'editor_data_picker_captionbar',
      controlType: 'CAPTIONBAR',
      appDataEntityId: 'web.master',
      controlParam: {},
      name: 'captionbar',
      id: 'editor_data_picker_captionbar',
    },
  ],
  viewLayoutPanel: {
    layoutBodyOnly: true,
    useDefaultLayout: true,
    layoutPanel: true,
    codeName: 'layoutpanel',
    controlStyle: 'APPDEEDITVIEW',
    controlType: 'VIEWLAYOUTPANEL',
    appDataEntityId: 'web.master',
    controlParam: {},
    id: 'layoutpanel',
  },
  title: '编辑器_数据选择',
  viewStyle: 'DEFAULT',
  viewType: 'DEEDITVIEW',
  enableDP: true,
  showCaptionBar: false,
  modelId: '7c45888093777b7f5ba25304c7358225',
  modelType: 'PSAPPDEVIEW',
  name: 'MASTEReditor_data_picker',
  id: 'web.master_editor_data_picker',
};
