export default {
  enableSearch: true,
  loadDefault: true,
  deviewCodeName: 'Chart_scatter',
  deviewId: 'ff0c072288e8897e9754665eea69d1e8',
  accUserMode: 3,
  capLanguageRes: {
    lanResTag: 'DE.LNAME.MASTER',
  },
  caption: '图表_散点图',
  codeName: 'master_chart_scatter',
  appDataEntityId: 'web.master',
  appViewEngines: [
    {
      engineCat: 'VIEW',
      engineType: 'ChartView',
      id: 'engine',
    },
  ],
  appViewMsgGroupId: 'chart_scatter',
  controls: [
    {
      searchButtonStyle: 'DEFAULT',
      deformPages: [
        {
          layout: {
            columnCount: 24,
            layout: 'TABLE_24COL',
          },
          caption: '常规条件',
          codeName: 'formpage1',
          detailStyle: 'DEFAULT',
          detailType: 'FORMPAGE',
          id: 'formpage1',
        },
      ],
      layout: {
        columnCount: 24,
        layout: 'TABLE_24COL',
      },
      tabHeaderPos: 'TOP',
      noTabHeader: true,
      autoLoad: true,
      showBusyIndicator: true,
      codeName: 'chart_scatter_search_form',
      controlType: 'SEARCHFORM',
      logicName: '图表_散点图_搜索表单',
      appDataEntityId: 'web.master',
      controlParam: {
        id: 'searchform',
      },
      modelId: '71c8a4276e9ac369a20c79e5da355b61',
      modelType: 'PSDEFORM_SEARCHFORM',
      name: 'searchform',
      id: 'web.master.chart_scatter_search_form',
    },
    {
      coordinateSystem: 'XY',
      chartCoordinateSystems: [
        {
          chartGrid: {
            chartGridXAxis0Id: '0',
            chartGridYAxis0Id: '0',
            chartCoordinateSystemId: '0',
            type: 'grid',
            name: '[scatter_0]直角坐标系[0]',
            id: '0',
          },
          echartsType: 'cartesian2d',
          type: 'XY',
          name: '[scatter_0]直角坐标系[0]',
          id: '0',
        },
      ],
      dechartDataGrid: {
        id: '0',
      },
      dechartLegend: {
        legendPos: 'BOTTOM',
        showLegend: true,
        id: '0',
      },
      dechartSerieses: [
        {
          catalogField: 'TYPE',
          echartsType: 'scatter',
          chartCoordinateSystemId: '0',
          chartDataSetId: '0',
          chartSeriesEncode: {
            chartXAxisId: '0',
            chartYAxisId: '0',
            x: ['TYPE'],
            y: ['QUANTITY'],
            itemId: 'NAME',
            itemName: 'NAME',
            type: 'XY',
            name: '坐标系编码',
            id: '0',
          },
          seriesField: 'NAME',
          seriesLayoutBy: 'column',
          seriesType: 'scatter',
          valueField: 'QUANTITY',
          enableChartDataSet: true,
          userParam: {
            'EC.itemStyle':
              '{"color":"#C92424","borderWidth":5,"borderColor":"#C92424"}',
          },
          id: 'scatter_0',
        },
      ],
      dechartTitle: {
        title: '散点图',
        titlePos: 'LEFT',
        id: '0',
      },
      chartDataSetGroups: [
        {
          appDEDataSetId: 'fetch_default',
          appDataEntityId: 'web.master',
          name: 'DEFAULT',
          id: '0',
        },
      ],
      chartDataSets: [
        {
          chartDataSetFields: [
            {
              groupField: true,
              name: 'TYPE',
              id: '0',
            },
            {
              groupField: true,
              index: 1,
              name: 'NAME',
              id: '1',
            },
            {
              index: 2,
              name: 'QUANTITY',
              id: '2',
            },
          ],
          name: 'scatter_0-DEFAULT',
          id: '0',
        },
      ],
      chartGrids: [
        {
          chartGridXAxis0Id: '0',
          chartGridYAxis0Id: '0',
          chartCoordinateSystemId: '0',
          type: 'grid',
          name: '[scatter_0]直角坐标系[0]',
          id: '0',
        },
      ],
      chartXAxises: [
        {
          echartsPos: 'xAxis',
          echartsType: 'category',
          position: 'bottom',
          type: 'category',
          name: 'axis_xAxis_0',
          id: '0',
        },
      ],
      chartYAxises: [
        {
          echartsPos: 'yAxis',
          echartsType: 'value',
          position: 'left',
          type: 'numeric',
          name: 'axis_yAxis_0',
          id: '0',
        },
      ],
      navViewPos: 'NONE',
      fetchControlAction: {
        appDEMethodId: 'fetch_default',
        appDataEntityId: 'web.master',
        id: 'fetch',
      },
      readOnly: true,
      autoLoad: true,
      showBusyIndicator: true,
      codeName: 'chart_scatter_chart',
      controlType: 'CHART',
      height: 300,
      logicName: 'Chart13',
      appDataEntityId: 'web.master',
      controlParam: {
        id: 'chart',
      },
      modelId: '2403e5f12de783f2d8d79ec0357e436d',
      modelType: 'PSDECHART',
      userParam: {
        'EC.color':
          '["#5470c6","#91cc75","#fac858","#ee6666","#73c0de","#3ba272","#fc8452","#9a60b4","#ea7ccc","#5470c6","#91cc75"]',
      },
      name: 'chart',
      id: 'web.master.chart_scatter_chart',
    },
    {
      capLanguageRes: {
        lanResTag: 'DE.LNAME.MASTER',
      },
      caption: '图表_散点图',
      codeName: 'chart_scatter_captionbar',
      controlType: 'CAPTIONBAR',
      appDataEntityId: 'web.master',
      controlParam: {},
      name: 'captionbar',
      id: 'chart_scatter_captionbar',
    },
  ],
  viewLayoutPanel: {
    layoutBodyOnly: true,
    useDefaultLayout: true,
    layoutPanel: true,
    codeName: 'layoutpanel',
    controlStyle: 'APPDECHARTVIEW',
    controlType: 'VIEWLAYOUTPANEL',
    appDataEntityId: 'web.master',
    controlParam: {},
    id: 'layoutpanel',
  },
  title: '图表_散点图',
  viewStyle: 'DEFAULT',
  viewType: 'DECHARTVIEW',
  enableDP: true,
  showCaptionBar: false,
  modelId: 'a46d823b976bf67b5f2676ea91e1b20c',
  modelType: 'PSAPPDEVIEW',
  name: 'MASTERChart_scatter',
  id: 'web.master_chart_scatter',
};
