export default {
  mdctrlActiveMode: 2,
  xdataControlName: 'tree',
  loadDefault: true,
  deviewCodeName: 'Tree_drag',
  deviewId: 'd77f2d0ed8b954117eeca82ddceacb9c',
  accUserMode: 3,
  capLanguageRes: {
    lanResTag: 'DE.LNAME.MASTER',
  },
  caption: '树视图_拖拽',
  codeName: 'master_tree_drag',
  appDataEntityId: 'web.master',
  appViewEngines: [
    {
      engineCat: 'VIEW',
      engineType: 'TreeView',
      id: 'engine',
    },
  ],
  appViewMsgGroupId: 'tree_drag',
  controls: [
    {
      detreeNodeRSs: [
        {
          childDETreeNodeId: 'node_2',
          parentAppDEFieldId: 'parent_id',
          parentDER1N: {
            pickupDEFName: 'PARENT_ID',
            codeName: 'parent',
            dertype: 'DER1N',
            logicName: '上级区划',
            orderValue: 100,
            serviceCodeName: 'parent',
            name: 'DER1N_REGION_REGION_PARENT_ID',
            id: 'mock.region.der1n_region_region_parent_id',
          },
          parentDETreeNodeId: 'node_1',
          parentValueLevel: 1,
          searchMode: 3,
          id: '区划数据（node_1）-区划子数据（node_2）',
        },
        {
          childDETreeNodeId: 'node_1',
          parentDETreeNodeId: 'node',
          parentValueLevel: 1,
          searchMode: 3,
          id: '主数据（node）-名称（node_1）',
        },
        {
          childDETreeNodeId: 'node',
          parentDETreeNodeId: 'root',
          parentValueLevel: 1,
          searchMode: 3,
          name: '默认根节点（ROOT）-主数据（node）',
          id: '默认根节点（root）-主数据（node）',
        },
        {
          childDETreeNodeId: 'node_2',
          parentAppDEFieldId: 'parent_id',
          parentDER1N: {
            pickupDEFName: 'PARENT_ID',
            codeName: 'parent',
            dertype: 'DER1N',
            logicName: '上级区划',
            orderValue: 100,
            serviceCodeName: 'parent',
            name: 'DER1N_REGION_REGION_PARENT_ID',
            id: 'mock.region.der1n_region_region_parent_id',
          },
          parentDETreeNodeId: 'node_2',
          parentValueLevel: 1,
          searchMode: 3,
          id: '区划子数据（node_2）-区划子数据（node_2）',
        },
      ],
      detreeNodes: [
        {
          text: '默认根节点',
          nodeType: 'ROOT',
          treeNodeType: 'STATIC',
          hasDETreeNodeRSs: true,
          rootNode: true,
          name: '默认根节点',
          id: 'root',
        },
        {
          text: '区域',
          nodeType: 'node',
          treeNodeType: 'STATIC',
          hasDETreeNodeRSs: true,
          name: '区域',
          id: 'node',
        },
        {
          dataSourceType: 'DEDATASET',
          idAppDEFieldId: 'id',
          leafFlagAppDEFieldId: 'leaf',
          appDEDataSetId: 'fetch_root',
          textAppDEFieldId: 'name',
          nodeType: 'node_1',
          appDataEntityId: 'web.region',
          treeNodeType: 'DE',
          hasDETreeNodeRSs: true,
          allowDrag: true,
          allowDrop: true,
          name: '区划数据',
          id: 'node_1',
        },
        {
          dataSourceType: 'DEDATASET',
          idAppDEFieldId: 'id',
          leafFlagAppDEFieldId: 'leaf',
          appDEDataSetId: 'fetch_child',
          textAppDEFieldId: 'name',
          nodeType: 'node_2',
          appDataEntityId: 'web.region',
          treeNodeType: 'DE',
          hasDETreeNodeRSs: true,
          allowDrag: true,
          allowDrop: true,
          name: '区划子数据',
          id: 'node_2',
        },
      ],
      outputIconDefault: true,
      navViewPos: 'NONE',
      createControlAction: {
        appDEMethodId: 'create',
        appDataEntityId: 'web.master',
        id: 'create',
      },
      fetchControlAction: {
        appDataEntityId: 'web.master',
        id: 'fetch',
      },
      getControlAction: {
        appDEMethodId: 'get',
        appDataEntityId: 'web.master',
        id: 'load',
      },
      removeControlAction: {
        appDEMethodId: 'remove',
        appDataEntityId: 'web.master',
        id: 'remove',
      },
      updateControlAction: {
        appDEMethodId: 'update',
        appDataEntityId: 'web.master',
        id: 'update',
      },
      autoLoad: true,
      showBusyIndicator: true,
      codeName: 'tree_drag_tree_view',
      controlType: 'TREEVIEW',
      logicName: '树视图_拖拽_树视图',
      appDataEntityId: 'web.master',
      controlParam: {
        id: 'tree',
      },
      modelId: 'c3e56b29b74ce0eb0253359b77238b13',
      modelType: 'PSDETREEVIEW',
      name: 'tree',
      id: 'web.master.tree_drag_tree_view',
    },
    {
      groupMode: 'SINGLE',
      controlType: 'SEARCHBAR',
      appDataEntityId: 'web.master',
      controlParam: {
        id: 'searchbar',
      },
      id: 'searchbar',
    },
    {
      capLanguageRes: {
        lanResTag: 'DE.LNAME.MASTER',
      },
      caption: '树视图_拖拽',
      codeName: 'tree_drag_captionbar',
      controlType: 'CAPTIONBAR',
      appDataEntityId: 'web.master',
      controlParam: {},
      name: 'captionbar',
      id: 'tree_drag_captionbar',
    },
  ],
  viewLayoutPanel: {
    layoutBodyOnly: true,
    useDefaultLayout: true,
    layoutPanel: true,
    codeName: 'layoutpanel',
    controlStyle: 'APPDETREEVIEW',
    controlType: 'VIEWLAYOUTPANEL',
    appDataEntityId: 'web.master',
    controlParam: {},
    id: 'layoutpanel',
  },
  title: '树视图_拖拽',
  viewStyle: 'DEFAULT',
  viewType: 'DETREEVIEW',
  enableDP: true,
  showCaptionBar: false,
  modelId: '2e8d37fe7d34bfe3ead01f1d2891a478',
  modelType: 'PSAPPDEVIEW',
  name: 'MASTERTree_drag',
  id: 'web.master_tree_drag',
};
