export default {
  htmlUrl: 'https://open.ibizlab.cn/apphub/zh/',
  loadDefault: true,
  deviewCodeName: 'html_view',
  deviewId: 'bdc9065c83027bbb681cfcc25dcef5d8',
  accUserMode: 3,
  capLanguageRes: {
    lanResTag: 'DE.LNAME.MASTER',
  },
  caption: 'HTML视图',
  codeName: 'master_html_view',
  appDataEntityId: 'web.master',
  appViewEngines: [
    {
      engineCat: 'VIEW',
      engineType: 'HtmlView',
      id: 'engine',
    },
  ],
  appViewMsgGroupId: 'html_view_group',
  controls: [
    {
      capLanguageRes: {
        lanResTag: 'DE.LNAME.MASTER',
      },
      caption: 'HTML视图',
      codeName: 'html_view_captionbar',
      controlType: 'CAPTIONBAR',
      appDataEntityId: 'web.master',
      controlParam: {},
      name: 'captionbar',
      id: 'html_view_captionbar',
    },
  ],
  viewLayoutPanel: {
    layoutBodyOnly: true,
    useDefaultLayout: true,
    layoutPanel: true,
    codeName: 'layoutpanel',
    controlStyle: 'APPDEHTMLVIEW',
    controlType: 'VIEWLAYOUTPANEL',
    appDataEntityId: 'web.master',
    controlParam: {},
    id: 'layoutpanel',
  },
  title: 'HTML视图',
  viewStyle: 'DEFAULT',
  viewType: 'DEHTMLVIEW',
  enableDP: true,
  showCaptionBar: false,
  modelId: 'b8c42f79c8ef982b14e1a9cc47dae307',
  modelType: 'PSAPPDEVIEW',
  name: 'MASTERhtml_view',
  id: 'web.master_html_view',
};
