export default {
  deviewCodeName: 'card_group',
  deviewId: 'd591c845a73245fb2d889c460e38f61c',
  accUserMode: 3,
  capLanguageRes: {
    lanResTag: 'DE.LNAME.MASTER',
  },
  caption: '卡片_分组',
  codeName: 'master_card_group',
  appDataEntityId: 'web.master',
  appViewMsgGroupId: 'card_group',
  viewLayoutPanel: {
    viewProxyMode: true,
    layoutMode: 'FLEX',
    layout: {
      layout: 'FLEX',
    },
    rootPanelItems: [
      {
        actionGroupExtractMode: 'ITEM',
        panelItems: [
          {
            actionGroupExtractMode: 'ITEM',
            panelItems: [
              {
                actionGroupExtractMode: 'ITEM',
                panelItems: [
                  {
                    caption: '数据视图',
                    itemStyle: 'DEFAULT',
                    itemType: 'CTRLPOS',
                    layoutPos: {
                      shrink: 1,
                      layout: 'FLEX',
                    },
                    showCaption: true,
                    id: 'dataview',
                  },
                ],
                predefinedType: 'CONTAINER_GROUP',
                layout: {
                  layout: 'FLEX',
                },
                dataRegionType: 'INHERIT',
                caption: '自动分组',
                itemStyle: 'DEFAULT',
                itemType: 'CONTAINER',
                layoutPos: {
                  layoutPos: 'CENTER',
                  layout: 'BORDER',
                },
                showCaption: true,
                id: 'container_group',
              },
              {
                actionGroupExtractMode: 'ITEM',
                panelItems: [
                  {
                    caption: '数据视图',
                    itemStyle: 'DEFAULT',
                    itemType: 'CTRLPOS',
                    layoutPos: {
                      shrink: 1,
                      layout: 'FLEX',
                    },
                    showCaption: true,
                    id: 'dataview1',
                  },
                ],
                predefinedType: 'CONTAINER_GROUP',
                layout: {
                  layout: 'FLEX',
                },
                dataRegionType: 'INHERIT',
                caption: '代码表分组',
                itemStyle: 'DEFAULT',
                itemType: 'CONTAINER',
                layoutPos: {
                  layoutPos: 'CENTER',
                  layout: 'BORDER',
                },
                showCaption: true,
                id: 'container_group1',
              },
              {
                actionGroupExtractMode: 'ITEM',
                panelItems: [
                  {
                    caption: '数据视图',
                    itemStyle: 'DEFAULT',
                    itemType: 'CTRLPOS',
                    layoutPos: {
                      shrink: 1,
                      layout: 'FLEX',
                    },
                    showCaption: true,
                    id: 'dataview2',
                  },
                ],
                predefinedType: 'CONTAINER_GROUP',
                layout: {
                  layout: 'FLEX',
                },
                dataRegionType: 'INHERIT',
                caption: '分组界面行为组',
                itemStyle: 'DEFAULT',
                itemType: 'CONTAINER',
                layoutPos: {
                  layoutPos: 'CENTER',
                  layout: 'BORDER',
                },
                showCaption: true,
                id: 'container_group2',
              },
            ],
            predefinedType: 'CONTAINER_SCROLL_MAIN',
            layout: {
              layout: 'BORDER',
            },
            dataRegionType: 'INHERIT',
            caption: '面板容器',
            itemStyle: 'DEFAULT',
            itemType: 'CONTAINER',
            layoutPos: {
              layoutPos: 'CENTER',
              layout: 'BORDER',
            },
            showCaption: true,
            id: 'container_scroll_main',
          },
        ],
        predefinedType: 'CONTAINER_SCROLL',
        layout: {
          layout: 'BORDER',
        },
        dataRegionType: 'INHERIT',
        caption: '滚动条容器',
        itemStyle: 'DEFAULT',
        itemType: 'CONTAINER',
        layoutPos: {
          shrink: 1,
          layout: 'FLEX',
        },
        id: 'container_scroll',
      },
    ],
    layoutPanel: true,
    controls: [
      {
        groupLayout: 'ROW',
        groupMode: 'CODELIST',
        groupAppDEFieldId: 'status',
        groupCodeListId: 'web.mock__cl_status',
        groupStyle: 'DEFAULT',
        dedataViewDataItems: [
          {
            appDEFieldId: 'id',
            dataType: 25,
            id: 'srfkey',
          },
          {
            appDEFieldId: 'name',
            dataType: 25,
            id: 'srfmajortext',
          },
        ],
        pagingMode: 1,
        pagingSize: 20,
        enableGroup: true,
        enablePagingBar: true,
        navViewPos: 'NONE',
        createControlAction: {
          appDEMethodId: 'create',
          appDataEntityId: 'web.master',
          id: 'create',
        },
        fetchControlAction: {
          appDEMethodId: 'fetch_default',
          appDataEntityId: 'web.master',
          id: 'fetch',
        },
        getControlAction: {
          appDEMethodId: 'get',
          appDataEntityId: 'web.master',
          id: 'load',
        },
        removeControlAction: {
          appDEMethodId: 'remove',
          appDataEntityId: 'web.master',
          id: 'remove',
        },
        updateControlAction: {
          appDEMethodId: 'update',
          appDataEntityId: 'web.master',
          id: 'update',
        },
        autoLoad: true,
        showBusyIndicator: true,
        codeName: 'card_group2',
        controlType: 'DATAVIEW',
        logicName: '卡片_代码表分组',
        appDataEntityId: 'web.master',
        controlParam: {
          id: 'dataview1',
        },
        modelId: 'e321d2c2af175ee8a8ba9051367407aa',
        modelType: 'PSDEDATAVIEW',
        name: 'dataview1',
        id: 'web.master.card_group2',
      },
      {
        groupLayout: 'ROW',
        groupMode: 'CODELIST',
        groupAppDEFieldId: 'status',
        groupCodeListId: 'web.mock__cl_status',
        groupUIActionGroup: {
          uiactionGroupDetails: [
            {
              actionLevel: 100,
              afterItemType: 'NONE',
              beforeItemType: 'NONE',
              buttonStyle: 'DEFAULT',
              caption: '打开关于',
              detailType: 'DEUIACTION',
              uiactionId: 'open_about@master',
              showCaption: true,
              showIcon: true,
              sysImage: {
                cssClass: 'fa fa-info-circle',
                glyph: 'xf05a@FontAwesome',
              },
              id: 'ubc28a2e',
            },
            {
              actionLevel: 100,
              afterItemType: 'NONE',
              beforeItemType: 'NONE',
              buttonStyle: 'DEFAULT',
              caption: '打开文档',
              detailType: 'DEUIACTION',
              uiactionId: 'open_document@master',
              showCaption: true,
              showIcon: true,
              id: 'u16b8690',
            },
            {
              actionLevel: 100,
              afterItemType: 'NONE',
              beforeItemType: 'NONE',
              buttonStyle: 'DEFAULT',
              caption: '打开弹窗',
              detailType: 'DEUIACTION',
              uiactionId: 'open_dialog@master',
              showCaption: true,
              showIcon: true,
              id: 'u423b10f',
            },
          ],
          appDataEntityId: 'web.master',
          uniqueTag: 'master__A23a502ec6f556cf9b4',
          name: '按钮组',
          id: 'a23a502ec6f556cf9b4',
        },
        groupStyle: 'DEFAULT',
        dedataViewDataItems: [
          {
            appDEFieldId: 'id',
            dataType: 25,
            id: 'srfkey',
          },
          {
            appDEFieldId: 'name',
            dataType: 25,
            id: 'srfmajortext',
          },
        ],
        pagingMode: 1,
        pagingSize: 20,
        enableGroup: true,
        enablePagingBar: true,
        navViewPos: 'NONE',
        createControlAction: {
          appDEMethodId: 'create',
          appDataEntityId: 'web.master',
          id: 'create',
        },
        fetchControlAction: {
          appDEMethodId: 'fetch_default',
          appDataEntityId: 'web.master',
          id: 'fetch',
        },
        getControlAction: {
          appDEMethodId: 'get',
          appDataEntityId: 'web.master',
          id: 'load',
        },
        removeControlAction: {
          appDEMethodId: 'remove',
          appDataEntityId: 'web.master',
          id: 'remove',
        },
        updateControlAction: {
          appDEMethodId: 'update',
          appDataEntityId: 'web.master',
          id: 'update',
        },
        autoLoad: true,
        showBusyIndicator: true,
        codeName: 'card_group3',
        controlType: 'DATAVIEW',
        logicName: '卡片_分组界面行为组',
        appDataEntityId: 'web.master',
        controlParam: {
          id: 'dataview2',
        },
        modelId: '9a51bc11a7f49721693b058060647c43',
        modelType: 'PSDEDATAVIEW',
        name: 'dataview2',
        id: 'web.master.card_group3',
      },
      {
        groupLayout: 'ROW',
        groupMode: 'AUTO',
        groupAppDEFieldId: 'quantity',
        groupStyle: 'DEFAULT',
        itemLayoutPanel: {
          layoutMode: 'FLEX',
          layout: {
            layout: 'FLEX',
          },
          rootPanelItems: [
            {
              actionGroupExtractMode: 'ITEM',
              panelItems: [
                {
                  editor: {
                    halign: 'LEFT',
                    renderMode: 'TEXT_DYNAMIC',
                    valign: 'MIDDLE',
                    wrapMode: 'NOWRAP',
                    editorType: 'SPAN',
                    predefinedType: 'FIELD_TEXT_DYNAMIC',
                    valueType: 'SIMPLE',
                    editable: true,
                    id: 'name',
                  },
                  viewFieldName: 'name',
                  allowEmpty: true,
                  caption: '文本(动态)',
                  itemStyle: 'DEFAULT',
                  itemType: 'FIELD',
                  layoutPos: {
                    shrink: 1,
                    layout: 'FLEX',
                  },
                  id: 'name',
                },
              ],
              layout: {
                layout: 'FLEX',
              },
              dataRegionType: 'INHERIT',
              caption: '容器',
              itemStyle: 'DEFAULT',
              itemType: 'CONTAINER',
              layoutPos: {
                shrink: 1,
                layout: 'FLEX',
              },
              id: 'container',
            },
          ],
          layoutPanel: true,
          codeName: 'a3c01d239e092a8f240',
          controlType: 'PANEL',
          logicName: 'card_group1卡片视图',
          appDataEntityId: 'web.master',
          controlParam: {},
          modelId: 'e1d8ac6f1d45d676aa03d6a50c940847',
          modelType: 'PSSYSVIEWPANEL',
          name: 'itemlayoutpanel',
          id: 'web.master.a3c01d239e092a8f240',
        },
        dedataViewDataItems: [
          {
            appDEFieldId: 'id',
            dataType: 25,
            id: 'srfkey',
          },
          {
            appDEFieldId: 'name',
            dataType: 25,
            id: 'srfmajortext',
          },
        ],
        pagingMode: 1,
        pagingSize: 20,
        enableGroup: true,
        enablePagingBar: true,
        navViewPos: 'NONE',
        createControlAction: {
          appDEMethodId: 'create',
          appDataEntityId: 'web.master',
          id: 'create',
        },
        fetchControlAction: {
          appDEMethodId: 'fetch_default',
          appDataEntityId: 'web.master',
          id: 'fetch',
        },
        getControlAction: {
          appDEMethodId: 'get',
          appDataEntityId: 'web.master',
          id: 'load',
        },
        removeControlAction: {
          appDEMethodId: 'remove',
          appDataEntityId: 'web.master',
          id: 'remove',
        },
        updateControlAction: {
          appDEMethodId: 'update',
          appDataEntityId: 'web.master',
          id: 'update',
        },
        autoLoad: true,
        showBusyIndicator: true,
        codeName: 'card_group1',
        controlType: 'DATAVIEW',
        logicName: '卡片_自动分组',
        appDataEntityId: 'web.master',
        controlParam: {
          id: 'dataview',
        },
        modelId: 'cc61314f0b8193610200208252539fce',
        modelType: 'PSDEDATAVIEW',
        name: 'dataview',
        id: 'web.master.card_group1',
      },
      {
        capLanguageRes: {
          lanResTag: 'DE.LNAME.MASTER',
        },
        caption: '卡片_分组',
        codeName: 'card_group_captionbar',
        controlType: 'CAPTIONBAR',
        appDataEntityId: 'web.master',
        controlParam: {},
        name: 'captionbar',
        id: 'card_group_captionbar',
      },
    ],
    codeName: 'usr0516099221',
    controlType: 'VIEWLAYOUTPANEL',
    logicName: '卡片_分组布局面板',
    appDataEntityId: 'web.master',
    controlParam: {},
    modelId: '91e208f807b745c3a079b1d2a73aed81',
    modelType: 'PSSYSVIEWLAYOUTPANEL',
    name: 'layoutpanel',
    id: 'usr0516099221',
  },
  title: '卡片_分组',
  viewStyle: 'DEFAULT',
  viewType: 'DECUSTOMVIEW',
  enableDP: true,
  showCaptionBar: false,
  modelId: '8847039f477094239c460c32ed5fd8ad',
  modelType: 'PSAPPDEVIEW',
  name: 'MASTERcard_group',
  id: 'web.master_card_group',
};
