export default {
  mdctrlActiveMode: 2,
  xdataControlName: 'tree',
  loadDefault: true,
  deviewCodeName: 'Tree_contextmenu',
  deviewId: '39d6d1d55e0570070c1d7c74912a5599',
  accUserMode: 3,
  capLanguageRes: {
    lanResTag: 'DE.LNAME.MASTER',
  },
  caption: '树视图_右键菜单',
  codeName: 'master_tree_contextmenu',
  appDataEntityId: 'web.master',
  appViewEngines: [
    {
      engineCat: 'VIEW',
      engineType: 'TreeView',
      id: 'engine',
    },
  ],
  appViewMsgGroupId: 'tree_contextmenu',
  controls: [
    {
      detreeNodeRSs: [
        {
          childDETreeNodeId: 'node',
          parentDETreeNodeId: 'node_1',
          parentValueLevel: 1,
          searchMode: 3,
          id: '主数据（node_1）-名称（node）',
        },
        {
          childDETreeNodeId: 'node_1',
          parentDETreeNodeId: 'root',
          parentValueLevel: 1,
          searchMode: 3,
          name: '默认根节点（ROOT）-主数据（node_1）',
          id: '默认根节点（root）-主数据（node_1）',
        },
      ],
      detreeNodes: [
        {
          text: '默认根节点',
          nodeType: 'ROOT',
          treeNodeType: 'STATIC',
          hasDETreeNodeRSs: true,
          rootNode: true,
          name: '默认根节点',
          id: 'root',
        },
        {
          dataSourceType: 'DEDATASET',
          idAppDEFieldId: 'id',
          appDEDataSetId: 'fetch_default',
          textAppDEFieldId: 'name',
          nodeType: 'node',
          appDataEntityId: 'web.master',
          decontextMenu: {
            detoolbarItems: [
              {
                actionLevel: 100,
                noPrivDisplayMode: 2,
                uiactionId: 'gridview_removeaction',
                uiactionTarget: 'MULTIKEY',
                valid: true,
                capLanguageRes: {
                  lanResTag: 'TBB.TEXT.*.REMOVE',
                },
                caption: '删除',
                itemType: 'DEUIACTION',
                sysImage: {
                  cssClass: 'fa fa-remove',
                  glyph: 'xf00d@FontAwesome',
                },
                tooltip: '删除',
                tooltipLanguageRes: {
                  lanResTag: 'TBB.TOOLTIP.*.REMOVE',
                },
                showCaption: true,
                showIcon: true,
                id: 'deuiaction2',
              },
            ],
            codeName: 'tree_contextmenu_node_cm',
            controlType: 'CONTEXTMENU',
            logicName: '树节点_上下文菜单',
            appDataEntityId: 'web.master',
            controlParam: {
              id: 'node_cm',
            },
            modelId: '6afd4b5e9c5cba5cc418b064eebcf188',
            modelType: 'PSDETOOLBAR',
            name: 'node_cm',
            id: 'tree_contextmenu_node_cm',
          },
          treeNodeType: 'DE',
          name: '名称',
          id: 'node',
        },
        {
          text: '主数据',
          nodeType: 'node_1',
          treeNodeType: 'STATIC',
          hasDETreeNodeRSs: true,
          name: '主数据',
          id: 'node_1',
        },
      ],
      outputIconDefault: true,
      navViewPos: 'NONE',
      createControlAction: {
        appDEMethodId: 'create',
        appDataEntityId: 'web.master',
        id: 'create',
      },
      fetchControlAction: {
        appDataEntityId: 'web.master',
        id: 'fetch',
      },
      getControlAction: {
        appDEMethodId: 'get',
        appDataEntityId: 'web.master',
        id: 'load',
      },
      removeControlAction: {
        appDEMethodId: 'remove',
        appDataEntityId: 'web.master',
        id: 'remove',
      },
      updateControlAction: {
        appDEMethodId: 'update',
        appDataEntityId: 'web.master',
        id: 'update',
      },
      autoLoad: true,
      showBusyIndicator: true,
      controls: [
        {
          detoolbarItems: [
            {
              actionLevel: 100,
              noPrivDisplayMode: 2,
              uiactionId: 'gridview_removeaction',
              uiactionTarget: 'MULTIKEY',
              valid: true,
              capLanguageRes: {
                lanResTag: 'TBB.TEXT.*.REMOVE',
              },
              caption: '删除',
              itemType: 'DEUIACTION',
              sysImage: {
                cssClass: 'fa fa-remove',
                glyph: 'xf00d@FontAwesome',
              },
              tooltip: '删除',
              tooltipLanguageRes: {
                lanResTag: 'TBB.TOOLTIP.*.REMOVE',
              },
              showCaption: true,
              showIcon: true,
              id: 'deuiaction2',
            },
          ],
          codeName: 'tree_contextmenu_node_cm',
          controlType: 'CONTEXTMENU',
          logicName: '树节点_上下文菜单',
          appDataEntityId: 'web.master',
          controlParam: {
            id: 'node_cm',
          },
          modelId: '6afd4b5e9c5cba5cc418b064eebcf188',
          modelType: 'PSDETOOLBAR',
          name: 'node_cm',
          id: 'tree_contextmenu_node_cm',
        },
      ],
      codeName: 'tree_contextmenu_tree_view',
      controlType: 'TREEVIEW',
      logicName: '树视图_右键菜单_树视图',
      appDataEntityId: 'web.master',
      controlParam: {
        id: 'tree',
      },
      modelId: '320b3c3065d4f8a4da71be018625cdda',
      modelType: 'PSDETREEVIEW',
      name: 'tree',
      id: 'web.master.tree_contextmenu_tree_view',
    },
    {
      groupMode: 'SINGLE',
      controlType: 'SEARCHBAR',
      appDataEntityId: 'web.master',
      controlParam: {
        id: 'searchbar',
      },
      id: 'searchbar',
    },
    {
      capLanguageRes: {
        lanResTag: 'DE.LNAME.MASTER',
      },
      caption: '树视图_右键菜单',
      codeName: 'tree_contextmenu_captionbar',
      controlType: 'CAPTIONBAR',
      appDataEntityId: 'web.master',
      controlParam: {},
      name: 'captionbar',
      id: 'tree_contextmenu_captionbar',
    },
  ],
  viewLayoutPanel: {
    layoutBodyOnly: true,
    useDefaultLayout: true,
    layoutPanel: true,
    codeName: 'layoutpanel',
    controlStyle: 'APPDETREEVIEW',
    controlType: 'VIEWLAYOUTPANEL',
    appDataEntityId: 'web.master',
    controlParam: {},
    id: 'layoutpanel',
  },
  title: '树视图_右键菜单',
  viewStyle: 'DEFAULT',
  viewType: 'DETREEVIEW',
  enableDP: true,
  showCaptionBar: false,
  modelId: '1acd56590578d4f980bf1633cc7b181b',
  modelType: 'PSAPPDEVIEW',
  name: 'MASTERTree_contextmenu',
  id: 'web.master_tree_contextmenu',
};
