export default {
  mdctrlActiveMode: 2,
  xdataControlName: 'kanban',
  loadDefault: true,
  deviewCodeName: 'kanban_view',
  deviewId: 'caba86568c652ea0b84749fe2e3d68df',
  accUserMode: 3,
  capLanguageRes: {
    lanResTag: 'DE.LNAME.MASTER',
  },
  caption: '看板视图',
  codeName: 'master_kanban_view',
  appDataEntityId: 'web.master',
  appViewMsgGroupId: 'kanban_view_group',
  viewLayoutPanel: {
    layoutBodyOnly: true,
    viewProxyMode: true,
    layoutMode: 'FLEX',
    layout: {
      layout: 'FLEX',
    },
    rootPanelItems: [
      {
        actionGroupExtractMode: 'ITEM',
        panelItems: [
          {
            actionGroupExtractMode: 'ITEM',
            panelItems: [
              {
                actionGroupExtractMode: 'ITEM',
                panelItems: [
                  {
                    caption: '页面标题',
                    itemStyle: 'DEFAULT',
                    itemType: 'CTRLPOS',
                    layoutPos: {
                      shrink: 1,
                      layout: 'FLEX',
                    },
                    showCaption: true,
                    id: 'captionbar',
                  },
                ],
                layout: {
                  align: 'center',
                  layout: 'FLEX',
                },
                dataRegionType: 'INHERIT',
                caption: '容器',
                itemStyle: 'DEFAULT',
                itemType: 'CONTAINER',
                layoutPos: {
                  shrink: 1,
                  heightMode: 'FULL',
                  layout: 'FLEX',
                },
                id: 'view_captionbar',
              },
            ],
            layout: {
              layout: 'FLEX',
            },
            dataRegionType: 'INHERIT',
            caption: '容器',
            itemStyle: 'DEFAULT',
            itemType: 'CONTAINER',
            layoutPos: {
              shrink: 1,
              heightMode: 'FULL',
              layout: 'FLEX',
            },
            id: 'view_header_left',
          },
          {
            actionGroupExtractMode: 'ITEM',
            panelItems: [
              {
                actionGroupExtractMode: 'ITEM',
                panelItems: [
                  {
                    caption: '工具栏',
                    itemStyle: 'DEFAULT',
                    itemType: 'CTRLPOS',
                    layoutPos: {
                      shrink: 1,
                      layout: 'FLEX',
                    },
                    showCaption: true,
                    id: 'toolbar',
                  },
                ],
                layout: {
                  align: 'center',
                  layout: 'FLEX',
                },
                dataRegionType: 'INHERIT',
                caption: '容器',
                itemStyle: 'DEFAULT',
                itemType: 'CONTAINER',
                layoutPos: {
                  shrink: 1,
                  heightMode: 'FULL',
                  layout: 'FLEX',
                },
                id: 'view_toolbar',
              },
            ],
            layout: {
              layout: 'FLEX',
            },
            dataRegionType: 'INHERIT',
            caption: '容器',
            itemStyle: 'DEFAULT',
            itemType: 'CONTAINER',
            layoutPos: {
              shrink: 1,
              heightMode: 'FULL',
              layout: 'FLEX',
            },
            id: 'view_header_right',
          },
        ],
        predefinedType: 'VIEWHEADER',
        layout: {
          align: 'space-between',
          dir: 'row',
          layout: 'FLEX',
          valign: 'center',
        },
        dataRegionType: 'INHERIT',
        caption: '容器',
        itemStyle: 'DEFAULT',
        itemType: 'CONTAINER',
        layoutPos: {
          shrink: 0,
          layout: 'FLEX',
        },
        id: 'view_header',
      },
      {
        actionGroupExtractMode: 'ITEM',
        panelItems: [
          {
            caption: '搜索表单',
            itemStyle: 'DEFAULT',
            itemType: 'CTRLPOS',
            layoutPos: {
              shrink: 1,
              layout: 'FLEX',
            },
            showCaption: true,
            id: 'searchform',
          },
        ],
        layout: {
          dir: 'column',
          layout: 'FLEX',
        },
        dataRegionType: 'INHERIT',
        itemStyle: 'DEFAULT',
        itemType: 'CONTAINER',
        layoutPos: {
          shrink: 0,
          layout: 'FLEX',
        },
        id: 'view_searchform',
      },
      {
        actionGroupExtractMode: 'ITEM',
        panelItems: [
          {
            caption: '看板',
            contentHeight: 800,
            height: 800,
            itemStyle: 'DEFAULT',
            itemType: 'CTRLPOS',
            layoutPos: {
              grow: 1,
              shrink: 1,
              height: 800,
              heightMode: 'PX',
              layout: 'FLEX',
            },
            showCaption: true,
            id: 'kanban',
          },
        ],
        predefinedType: 'VIEWCONTENT',
        layout: {
          layout: 'FLEX',
        },
        dataRegionType: 'INHERIT',
        caption: '容器',
        itemStyle: 'DEFAULT',
        itemType: 'CONTAINER',
        layoutPos: {
          grow: 1,
          shrink: 1,
          layout: 'FLEX',
        },
        id: 'view_kanban',
      },
    ],
    layoutPanel: true,
    appViewEngines: [
      {
        engineCat: 'VIEW',
        engineType: 'KanBanView',
        id: 'engine',
      },
    ],
    appViewLogics: [
      {
        logicTrigger: 'CUSTOM',
        logicType: 'APPUILOGIC',
        builtinAppUILogic: {
          actionAfterWizard: 'DEFAULT',
          newDataAppView: {
            openMode: 'POPUPMODAL',
            refAppViewId: 'web.master_edit_view',
          },
          appUILogicRefViews: [
            {
              openMode: 'POPUPMODAL',
              refAppViewId: 'web.master_edit_view',
            },
          ],
          builtinLogic: true,
          logicType: 'PREDEFINED',
          viewLogicType: 'APP_NEWDATA',
          id: '新建数据',
        },
        builtinLogic: true,
        id: 'newdata',
      },
      {
        logicTrigger: 'CUSTOM',
        logicType: 'APPUILOGIC',
        builtinAppUILogic: {
          openDataAppView: {
            openMode: 'POPUPMODAL',
            refAppViewId: 'web.master_edit_view',
          },
          editMode: true,
          appUILogicRefViews: [
            {
              openMode: 'POPUPMODAL',
              refAppViewId: 'web.master_edit_view',
            },
          ],
          builtinLogic: true,
          logicType: 'PREDEFINED',
          viewLogicType: 'APP_OPENDATA',
          id: '打开数据',
        },
        builtinLogic: true,
        id: 'opendata',
      },
    ],
    appViewRefs: [
      {
        realOpenMode: 'POPUPMODAL',
        realTitle: '主数据编辑视图',
        refAppViewId: 'web.master_edit_view',
        name: 'NEWDATA',
        id: 'newdata',
      },
      {
        realOpenMode: 'POPUPMODAL',
        realTitle: '主数据编辑视图',
        refAppViewId: 'web.master_edit_view',
        name: 'EDITDATA',
        id: 'editdata',
      },
    ],
    controls: [
      {
        xdataControlName: 'kanban',
        codeName: 'kanban_view_toolbar',
        controlType: 'TOOLBAR',
        logicName: '看板视图_工具栏',
        appDataEntityId: 'web.master',
        controlParam: {
          id: 'toolbar',
        },
        modelId: 'f79d8d6d9465fb1473aa64159458f751',
        modelType: 'PSDETOOLBAR',
        name: 'toolbar',
        id: 'kanban_view_toolbar',
      },
      {
        searchButtonStyle: 'DEFAULT',
        deformPages: [
          {
            layout: {
              columnCount: 24,
              layout: 'TABLE_24COL',
            },
            caption: '常规条件',
            codeName: 'formpage1',
            detailStyle: 'DEFAULT',
            detailType: 'FORMPAGE',
            id: 'formpage1',
          },
        ],
        layout: {
          columnCount: 24,
          layout: 'TABLE_24COL',
        },
        tabHeaderPos: 'TOP',
        noTabHeader: true,
        autoLoad: true,
        showBusyIndicator: true,
        codeName: 'kanban_view_search_form',
        controlType: 'SEARCHFORM',
        logicName: '看板视图_搜索表单',
        appDataEntityId: 'web.master',
        controlParam: {
          id: 'searchform',
        },
        modelId: 'c10306e8ff80584590f56df835aa3612',
        modelType: 'PSDEFORM_SEARCHFORM',
        name: 'searchform',
        id: 'web.master.kanban_view_search_form',
      },
      {
        updateGroupControlAction: {
          appDEMethodId: 'update',
          appDataEntityId: 'web.master',
          id: 'updategroup',
        },
        cardHeight: 100,
        cardWidth: 200,
        groupLayout: 'ROW',
        groupMode: 'CODELIST',
        groupAppDEFieldId: 'status',
        groupCodeListId: 'web.mock__cl_status',
        groupStyle: 'DEFAULT',
        itemLayoutPanel: {
          layoutMode: 'TABLE_24COL',
          layout: {
            columnCount: 24,
            layout: 'TABLE_24COL',
          },
          rootPanelItems: [
            {
              actionGroupExtractMode: 'ITEM',
              panelItems: [
                {
                  editor: {
                    halign: 'LEFT',
                    renderMode: 'TEXT_DYNAMIC',
                    valign: 'MIDDLE',
                    wrapMode: 'NOWRAP',
                    editorType: 'SPAN',
                    predefinedType: 'FIELD_TEXT_DYNAMIC',
                    valueType: 'SIMPLE',
                    editable: true,
                    id: 'name',
                  },
                  viewFieldName: 'name',
                  allowEmpty: true,
                  caption: '文本(动态)',
                  itemStyle: 'DEFAULT',
                  itemType: 'FIELD',
                  layoutPos: {
                    shrink: 1,
                    layout: 'FLEX',
                  },
                  id: 'name',
                },
              ],
              layout: {
                dir: 'column',
                layout: 'FLEX',
              },
              dataRegionType: 'INHERIT',
              itemStyle: 'DEFAULT',
              itemType: 'CONTAINER',
              layoutPos: {
                colMD: 24,
                layout: 'TABLE_24COL',
              },
              id: 'page_container',
            },
          ],
          codeName: 'usr0513936387',
          controlType: 'PANEL',
          logicName: '看板视图_看板_卡片面板',
          appDataEntityId: 'web.master',
          controlParam: {},
          modelId: '426f214f5a892228cdd429de56f0f025',
          modelType: 'PSSYSVIEWPANEL',
          name: 'itemlayoutpanel',
          id: 'web.master.usr0513936387',
        },
        minorSortDir: 'ASC',
        minorSortAppDEFieldId: 'px',
        dedataViewDataItems: [
          {
            appDEFieldId: 'id',
            dataType: 25,
            id: 'srfkey',
          },
          {
            appDEFieldId: 'name',
            dataType: 25,
            id: 'srfmajortext',
          },
          {
            appDEFieldId: 'region_id',
            dataType: 25,
            id: 'region_id',
          },
        ],
        pagingSize: 1000,
        appendDEItems: true,
        enableCardEdit: true,
        enableCardEditGroup: true,
        enableCardEditOrder: true,
        enableCardNew: true,
        enableGroup: true,
        navViewPos: 'NONE',
        createControlAction: {
          appDEMethodId: 'create',
          appDataEntityId: 'web.master',
          id: 'create',
        },
        fetchControlAction: {
          appDEMethodId: 'fetch_default',
          appDataEntityId: 'web.master',
          id: 'fetch',
        },
        getControlAction: {
          appDEMethodId: 'get',
          appDataEntityId: 'web.master',
          id: 'load',
        },
        moveControlAction: {
          appDEMethodId: 'update',
          appDataEntityId: 'web.master',
          id: 'move',
        },
        removeControlAction: {
          appDEMethodId: 'remove',
          appDataEntityId: 'web.master',
          id: 'remove',
        },
        updateControlAction: {
          appDEMethodId: 'update',
          appDataEntityId: 'web.master',
          id: 'update',
        },
        autoLoad: true,
        showBusyIndicator: true,
        codeName: 'kanban_view_kan_ban',
        controlType: 'KANBAN',
        logicName: '看板视图_看板',
        appDataEntityId: 'web.master',
        controlParam: {
          id: 'kanban',
        },
        modelId: '0b599dce2f18912b0b626b3c170fde73',
        modelType: 'PSDEKANBAN',
        name: 'kanban',
        id: 'web.master.kanban_view_kan_ban',
      },
      {
        groupMode: 'SINGLE',
        quickSearchMode: 1,
        enableQuickSearch: true,
        controlType: 'SEARCHBAR',
        appDataEntityId: 'web.master',
        controlParam: {
          id: 'searchbar',
        },
        id: 'searchbar',
      },
      {
        capLanguageRes: {
          lanResTag: 'DE.LNAME.MASTER',
        },
        caption: '看板视图',
        codeName: 'kanban_view_captionbar',
        controlType: 'CAPTIONBAR',
        appDataEntityId: 'web.master',
        controlParam: {},
        name: 'captionbar',
        id: 'kanban_view_captionbar',
      },
    ],
    codeName: 'a45c26937b984a50eea',
    controlType: 'VIEWLAYOUTPANEL',
    logicName: 'kanban_view实体看板视图布局面板',
    appDataEntityId: 'web.master',
    controlParam: {},
    modelId: 'e2af4522c1d99c7895d8c0946accbac4',
    modelType: 'PSSYSVIEWLAYOUTPANEL',
    name: 'layoutpanel',
    id: 'a45c26937b984a50eea',
  },
  title: '看板视图',
  viewStyle: 'DEFAULT',
  viewType: 'DEKANBANVIEW',
  enableDP: true,
  showCaptionBar: true,
  modelId: '24dfe3e1efd2c0f143962bdc6b7cb9c8',
  modelType: 'PSAPPDEVIEW',
  name: 'MASTERkanban_view',
  id: 'web.master_kanban_view',
};
