export default {
  tabLayout: 'FLOW',
  loadDefault: true,
  showDataInfoBar: true,
  deviewCodeName: 'toolbar',
  deviewId: 'c1c8ec236e5b72f1736f9ee1db9c8d34',
  accUserMode: 3,
  capLanguageRes: {
    lanResTag: 'DE.LNAME.MASTER',
  },
  caption: '工具栏',
  codeName: 'master_toolbar',
  appDataEntityId: 'web.master',
  appViewEngines: [
    {
      engineCat: 'VIEW',
      engineType: 'TabExpView',
      id: 'engine',
    },
  ],
  appViewMsgGroupId: 'toolbar',
  controls: [
    {
      dedrtabPages: [
        {
          caption: '基础',
          appViewId: 'web.master_toolbar_base',
          id: 'base',
        },
        {
          caption: '界面样式及图标',
          appViewId: 'web.master_toolbar_style',
          id: 'css',
        },
      ],
      dataRelationTag: 'toolbar_DR',
      editItemCapLanguageRes: {
        lanResTag: 'DE.LNAME.MASTER',
      },
      editItemCaption: '主数据',
      uniqueTag: 'master_toolbar__tabexppanel',
      autoLoad: true,
      showBusyIndicator: true,
      codeName: 'toolbar_dr',
      controlType: 'DRTAB',
      appDataEntityId: 'web.master',
      controlParam: {
        id: 'tabexppanel',
      },
      modelId: '5a6acc7c85f17326fa679cc6d0ca6ec8',
      modelType: 'PSDEDRTAB',
      name: 'tabexppanel',
      id: 'toolbar_dr',
    },
    {
      capLanguageRes: {
        lanResTag: 'DE.LNAME.MASTER',
      },
      caption: '工具栏',
      codeName: 'toolbar_captionbar',
      controlType: 'CAPTIONBAR',
      appDataEntityId: 'web.master',
      controlParam: {},
      name: 'captionbar',
      id: 'toolbar_captionbar',
    },
  ],
  viewLayoutPanel: {
    layoutBodyOnly: true,
    useDefaultLayout: true,
    layoutPanel: true,
    codeName: 'layoutpanel',
    controlStyle: 'APPDETABEXPVIEW',
    controlType: 'VIEWLAYOUTPANEL',
    appDataEntityId: 'web.master',
    controlParam: {},
    id: 'layoutpanel',
  },
  title: '工具栏',
  viewStyle: 'DEFAULT',
  viewType: 'DETABEXPVIEW',
  enableDP: true,
  showCaptionBar: false,
  modelId: '309536432d1a2c94042c77d5b7630c0a',
  modelType: 'PSAPPDEVIEW',
  name: 'MASTERtoolbar',
  id: 'web.master_toolbar',
};
