export default {
  sideBarLayout: 'LEFT',
  showDataInfoBar: true,
  loadDefault: true,
  deviewCodeName: 'data_view_exp_view',
  deviewId: '8ff3b2258080881e5506547615b68bc0',
  accUserMode: 3,
  capLanguageRes: {
    lanResTag: 'DE.LNAME.MASTER',
  },
  caption: '卡片导航',
  codeName: 'master_data_view_exp_view',
  appDataEntityId: 'web.master',
  appViewMsgGroupId: 'data_view_exp_view',
  viewLayoutPanel: {
    layoutBodyOnly: true,
    viewProxyMode: true,
    layoutMode: 'FLEX',
    layout: {
      layout: 'FLEX',
    },
    rootPanelItems: [
      {
        actionGroupExtractMode: 'ITEM',
        panelItems: [
          {
            actionGroupExtractMode: 'ITEM',
            panelItems: [
              {
                actionGroupExtractMode: 'ITEM',
                panelItems: [
                  {
                    caption: '卡片导航',
                    itemStyle: 'DEFAULT',
                    itemType: 'CTRLPOS',
                    layoutPos: {
                      colMD: 24,
                      layout: 'TABLE_24COL',
                    },
                    showCaption: true,
                    id: 'dataviewexpbar',
                  },
                ],
                layout: {
                  columnCount: 24,
                  layout: 'TABLE_24COL',
                },
                dataRegionType: 'INHERIT',
                caption: '面板容器',
                itemStyle: 'DEFAULT',
                itemType: 'CONTAINER',
                layoutPos: {
                  grow: 12,
                  shrink: 1,
                  layout: 'SIMPLEFLEX',
                },
                id: 'container1',
              },
              {
                actionGroupExtractMode: 'ITEM',
                layout: {
                  columnCount: 24,
                  layout: 'TABLE_24COL',
                },
                dataRegionType: 'INHERIT',
                caption: '面板容器',
                itemStyle: 'DEFAULT',
                itemType: 'CONTAINER',
                layoutPos: {
                  grow: 0,
                  shrink: 1,
                  layout: 'SIMPLEFLEX',
                },
                id: 'container2',
              },
            ],
            predefinedType: 'CONTAINER_GRID',
            layout: {
              layout: 'SIMPLEFLEX',
            },
            dataRegionType: 'INHERIT',
            caption: '栅格容器',
            itemStyle: 'DEFAULT',
            itemType: 'CONTAINER',
            layoutPos: {
              shrink: 1,
              layout: 'FLEX',
            },
            id: 'container_grid',
          },
        ],
        layout: {
          layout: 'FLEX',
        },
        dataRegionType: 'INHERIT',
        caption: '容器',
        itemStyle: 'DEFAULT',
        itemType: 'CONTAINER',
        layoutPos: {
          shrink: 1,
          layout: 'FLEX',
        },
        id: 'container',
      },
    ],
    layoutPanel: true,
    appViewEngines: [
      {
        engineCat: 'VIEW',
        engineType: 'DataViewExpView',
        id: 'engine',
      },
    ],
    appViewLogics: [
      {
        logicTrigger: 'CUSTOM',
        logicType: 'APPUILOGIC',
        builtinAppUILogic: {
          actionAfterWizard: 'DEFAULT',
          builtinLogic: true,
          logicType: 'PREDEFINED',
          viewLogicType: 'APP_NEWDATA',
          id: '新建数据',
        },
        builtinLogic: true,
        id: 'newdata',
      },
      {
        logicTrigger: 'CUSTOM',
        logicType: 'APPUILOGIC',
        builtinAppUILogic: {
          editMode: true,
          builtinLogic: true,
          logicType: 'PREDEFINED',
          viewLogicType: 'APP_OPENDATA',
          id: '打开数据',
        },
        builtinLogic: true,
        id: 'opendata',
      },
    ],
    controls: [
      {
        xdataControlName: 'dataviewexpbar_dataview',
        enableCounter: true,
        showTitleBar: true,
        autoLoad: true,
        showBusyIndicator: true,
        appViewRefs: [
          {
            realTitle: '详细信息',
            refAppViewId: 'web.master_info_view',
            name: 'EXPITEM:DEFAULT',
            id: 'expitem:default',
          },
        ],
        controls: [
          {
            groupMode: 'NONE',
            groupStyle: 'DEFAULT',
            itemLayoutPanel: {
              layoutMode: 'FLEX',
              layout: {
                layout: 'FLEX',
              },
              rootPanelItems: [
                {
                  actionGroupExtractMode: 'ITEM',
                  panelItems: [
                    {
                      actionGroupExtractMode: 'ITEM',
                      panelItems: [
                        {
                          rawItem: {
                            sysImage: {
                              rawContent:
                                '<svg id="图层_2" data-name="图层 2" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 45.05908 45.05914"><defs><style>.cls-1{fill:#01b0ff;}</style></defs><title>ibizlab. 2</title><path class="cls-1" d="M1.64777,456.35452v45.05914H46.70685V456.35452Zm39.92407,3.86188-9.51965,19.60479L11.59913,460.1221ZM4.35572,497.13931v-34.424c8.37353,26.80664,17.53088,34.424,17.53088,34.424ZM17.424,472.06509l12.64337,12.21838-5.52484,9.77466S16.25531,478.54611,17.424,472.06509Zm9.031,25.07422,6.58728-9.031,7.64978,9.031Zm16.71912-2.99152-7.54029-9.61389,7.63453-13.10132Z" transform="translate(-1.64777 -456.35452)"/></svg>',
                            },
                            contentType: 'IMAGE',
                            predefinedType: 'STATIC_IMAGE',
                            rawItemHeight: 48,
                            rawItemWidth: 48,
                            id: 'static_image',
                          },
                          caption: '图片',
                          contentHeight: 48,
                          contentWidth: 48,
                          height: 48,
                          itemStyle: 'DEFAULT',
                          itemType: 'RAWITEM',
                          layoutPos: {
                            shrink: 1,
                            height: 48,
                            heightMode: 'PX',
                            layout: 'FLEX',
                            width: 48,
                            widthMode: 'PX',
                          },
                          sysImage: {
                            rawContent:
                              '<svg id="图层_2" data-name="图层 2" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 45.05908 45.05914"><defs><style>.cls-1{fill:#01b0ff;}</style></defs><title>ibizlab. 2</title><path class="cls-1" d="M1.64777,456.35452v45.05914H46.70685V456.35452Zm39.92407,3.86188-9.51965,19.60479L11.59913,460.1221ZM4.35572,497.13931v-34.424c8.37353,26.80664,17.53088,34.424,17.53088,34.424ZM17.424,472.06509l12.64337,12.21838-5.52484,9.77466S16.25531,478.54611,17.424,472.06509Zm9.031,25.07422,6.58728-9.031,7.64978,9.031Zm16.71912-2.99152-7.54029-9.61389,7.63453-13.10132Z" transform="translate(-1.64777 -456.35452)"/></svg>',
                          },
                          width: 48,
                          showCaption: true,
                          id: 'static_image',
                        },
                        {
                          actionGroupExtractMode: 'ITEM',
                          panelItems: [
                            {
                              editor: {
                                halign: 'LEFT',
                                renderMode: 'TEXT_DYNAMIC',
                                valign: 'MIDDLE',
                                wrapMode: 'NOWRAP',
                                editorType: 'SPAN',
                                predefinedType: 'FIELD_TEXT_DYNAMIC',
                                valueType: 'SIMPLE',
                                editable: true,
                                id: 'name',
                              },
                              viewFieldName: 'name',
                              allowEmpty: true,
                              caption: '文本(动态)',
                              itemStyle: 'DEFAULT',
                              itemType: 'FIELD',
                              layoutPos: {
                                shrink: 1,
                                layout: 'FLEX',
                              },
                              id: 'name',
                            },
                            {
                              editor: {
                                halign: 'LEFT',
                                renderMode: 'TEXT_DYNAMIC',
                                valign: 'MIDDLE',
                                wrapMode: 'NOWRAP',
                                editorType: 'SPAN',
                                predefinedType: 'FIELD_TEXT_DYNAMIC',
                                valueType: 'SIMPLE',
                                editable: true,
                                id: 'quantity',
                              },
                              viewFieldName: 'quantity',
                              allowEmpty: true,
                              caption: '文本(动态)',
                              itemStyle: 'DEFAULT',
                              itemType: 'FIELD',
                              layoutPos: {
                                shrink: 1,
                                layout: 'FLEX',
                              },
                              id: 'quantity',
                            },
                            {
                              editor: {
                                halign: 'LEFT',
                                renderMode: 'TEXT_DYNAMIC',
                                valign: 'MIDDLE',
                                wrapMode: 'NOWRAP',
                                appCodeListId: 'web.mock__cl_status',
                                editorType: 'SPAN',
                                predefinedType: 'FIELD_TEXT_DYNAMIC',
                                valueType: 'SIMPLE',
                                editable: true,
                                id: 'status',
                              },
                              viewFieldName: 'status',
                              allowEmpty: true,
                              convertToCodeItemText: true,
                              caption: '文本(动态)',
                              itemStyle: 'DEFAULT',
                              itemType: 'FIELD',
                              layoutPos: {
                                shrink: 1,
                                layout: 'FLEX',
                              },
                              id: 'status',
                            },
                          ],
                          layout: {
                            align: 'center',
                            dir: 'column',
                            layout: 'FLEX',
                            valign: 'center',
                          },
                          dataRegionType: 'INHERIT',
                          caption: '容器',
                          itemStyle: 'DEFAULT',
                          itemType: 'CONTAINER',
                          layoutPos: {
                            shrink: 1,
                            layout: 'FLEX',
                            spacingLeft: 'OUTERMEDIUM',
                          },
                          id: 'container2',
                        },
                      ],
                      layout: {
                        align: 'flex-start',
                        dir: 'row',
                        layout: 'FLEX',
                        valign: 'center',
                      },
                      dataRegionType: 'INHERIT',
                      caption: '容器',
                      itemStyle: 'DEFAULT',
                      itemType: 'CONTAINER',
                      layoutPos: {
                        shrink: 1,
                        layout: 'FLEX',
                      },
                      id: 'container',
                    },
                  ],
                  layout: {
                    layout: 'FLEX',
                  },
                  dataRegionType: 'INHERIT',
                  itemStyle: 'DEFAULT',
                  itemType: 'CONTAINER',
                  layoutPos: {
                    shrink: 1,
                    layout: 'FLEX',
                  },
                  id: 'container1',
                },
              ],
              layoutPanel: true,
              codeName: 'a40c3b52f4a769ff56b',
              controlType: 'PANEL',
              logicName: 'card_base卡片视图',
              appDataEntityId: 'web.master',
              controlParam: {},
              modelId: 'c7f399249a60560746c2ed9270368a59',
              modelType: 'PSSYSVIEWPANEL',
              name: 'itemlayoutpanel',
              id: 'web.master.a40c3b52f4a769ff56b',
            },
            dedataViewDataItems: [
              {
                appDEFieldId: 'id',
                dataType: 25,
                id: 'srfkey',
              },
              {
                appDEFieldId: 'name',
                dataType: 25,
                id: 'srfmajortext',
              },
            ],
            pagingMode: 1,
            pagingSize: 10,
            enablePagingBar: true,
            singleSelect: true,
            navAppViewId: 'web.master_info_view',
            navViewPos: 'RIGHT',
            navViewWidth: 800,
            createControlAction: {
              appDEMethodId: 'create',
              appDataEntityId: 'web.master',
              id: 'create',
            },
            fetchControlAction: {
              appDEMethodId: 'fetch_default',
              appDataEntityId: 'web.master',
              id: 'fetch',
            },
            getControlAction: {
              appDEMethodId: 'get',
              appDataEntityId: 'web.master',
              id: 'load',
            },
            removeControlAction: {
              appDEMethodId: 'remove',
              appDataEntityId: 'web.master',
              id: 'remove',
            },
            updateControlAction: {
              appDEMethodId: 'update',
              appDataEntityId: 'web.master',
              id: 'update',
            },
            autoLoad: true,
            showBusyIndicator: true,
            codeName: 'card_right_nav',
            controlType: 'DATAVIEW',
            logicName: '卡片_内置导航右',
            appDataEntityId: 'web.master',
            controlLogics: [
              {
                eventNames: 'SELECTIONCHANGE',
                logicTag: 'dataviewexpbar_dataview',
                logicType: 'CUSTOM',
                triggerType: 'CTRLEVENT',
                id: 'dataviewexpbar_selectionchange',
              },
              {
                eventNames: 'LOAD',
                logicTag: 'dataviewexpbar_dataview',
                logicType: 'CUSTOM',
                triggerType: 'CTRLEVENT',
                id: 'dataviewexpbar_load',
              },
            ],
            controlParam: {
              id: 'dataviewexpbar_dataview',
            },
            modelId: '065188985fbb2365b5cd053fbc18ec27',
            modelType: 'PSDEDATAVIEW',
            name: 'dataviewexpbar_dataview',
            id: 'web.master.card_right_nav',
          },
        ],
        codeName: 'data_view_exp_view_dataviewexpbar',
        controlType: 'DATAVIEWEXPBAR',
        appDataEntityId: 'web.master',
        controlParam: {
          id: 'dataviewexpbar',
        },
        modelId: 'b21d87b1fb43314a9e07e761f81335b2_dataviewexpbar',
        modelType: 'PSEXPBAR',
        name: 'dataviewexpbar',
        id: 'data_view_exp_view_dataviewexpbar',
      },
      {
        groupMode: 'SINGLE',
        quickSearchMode: 1,
        enableQuickSearch: true,
        controlType: 'SEARCHBAR',
        appDataEntityId: 'web.master',
        controlParam: {
          id: 'searchbar',
        },
        id: 'searchbar',
      },
      {
        capLanguageRes: {
          lanResTag: 'DE.LNAME.MASTER',
        },
        caption: '卡片导航',
        codeName: 'data_view_exp_view_captionbar',
        controlType: 'CAPTIONBAR',
        appDataEntityId: 'web.master',
        controlParam: {},
        name: 'captionbar',
        id: 'data_view_exp_view_captionbar',
      },
    ],
    codeName: 'a62389dd11d01fbdecf',
    controlType: 'VIEWLAYOUTPANEL',
    logicName: 'data_view_exp_view实体卡片视图导航视图布局面板',
    appDataEntityId: 'web.master',
    controlParam: {},
    modelId: 'f9218a35585b3f2dae08009b54e130ff',
    modelType: 'PSSYSVIEWLAYOUTPANEL',
    name: 'layoutpanel',
    id: 'a62389dd11d01fbdecf',
  },
  title: '卡片导航',
  viewStyle: 'DEFAULT',
  viewType: 'DEDATAVIEWEXPVIEW',
  enableDP: true,
  showCaptionBar: true,
  modelId: 'b21d87b1fb43314a9e07e761f81335b2',
  modelType: 'PSAPPDEVIEW',
  name: 'MASTERdata_view_exp_view',
  id: 'web.master_data_view_exp_view',
};
