export default {
  deviewCodeName: 'calendar_multiple_data',
  deviewId: '4a5860c7d50467dec9fc1d3707027abc',
  accUserMode: 3,
  capLanguageRes: {
    lanResTag: 'DE.LNAME.MASTER',
  },
  caption: '日历_多数据',
  codeName: 'master_calendar_multiple_data',
  appDataEntityId: 'web.master',
  appViewMsgGroupId: 'calendar_multiple_data',
  viewLayoutPanel: {
    viewProxyMode: true,
    layoutMode: 'FLEX',
    layout: {
      layout: 'FLEX',
    },
    rootPanelItems: [
      {
        actionGroupExtractMode: 'ITEM',
        panelItems: [
          {
            actionGroupExtractMode: 'ITEM',
            panelItems: [
              {
                actionGroupExtractMode: 'ITEM',
                panelItems: [
                  {
                    caption: '日历',
                    itemStyle: 'DEFAULT',
                    itemType: 'CTRLPOS',
                    layoutPos: {
                      shrink: 1,
                      layout: 'FLEX',
                    },
                    showCaption: true,
                    id: 'calendar',
                  },
                ],
                layout: {
                  layout: 'FLEX',
                },
                dataRegionType: 'INHERIT',
                caption: '容器',
                itemStyle: 'DEFAULT',
                itemType: 'CONTAINER',
                layoutPos: {
                  layoutPos: 'CENTER',
                  layout: 'BORDER',
                },
                id: 'container',
              },
            ],
            predefinedType: 'CONTAINER_SCROLL_MAIN',
            layout: {
              layout: 'BORDER',
            },
            dataRegionType: 'INHERIT',
            caption: '面板容器',
            itemStyle: 'DEFAULT',
            itemType: 'CONTAINER',
            layoutPos: {
              layoutPos: 'CENTER',
              layout: 'BORDER',
            },
            showCaption: true,
            id: 'container_scroll_main',
          },
        ],
        predefinedType: 'CONTAINER_SCROLL',
        layout: {
          layout: 'BORDER',
        },
        dataRegionType: 'INHERIT',
        caption: '滚动条容器',
        itemStyle: 'DEFAULT',
        itemType: 'CONTAINER',
        layoutPos: {
          shrink: 1,
          layout: 'FLEX',
        },
        id: 'container_scroll',
      },
    ],
    layoutPanel: true,
    controls: [
      {
        calendarStyle: 'MONTH',
        groupMode: 'NONE',
        legendPos: 'TOP',
        sysCalendarItems: [
          {
            beginTimeAppDEFieldId: 'date',
            endTimeAppDEFieldId: 'date',
            idAppDEFieldId: 'id',
            itemStyle: 'DEFAULT',
            itemType: 'date',
            appDEDataSetId: 'fetch_default',
            textAppDEFieldId: 'name',
            appDataEntityId: 'web.master',
            id: 'date',
          },
          {
            beginTimeAppDEFieldId: 'create_time',
            endTimeAppDEFieldId: 'create_time',
            idAppDEFieldId: 'id',
            itemStyle: 'DEFAULT',
            itemType: 'create_date',
            appDEDataSetId: 'fetch_default',
            textAppDEFieldId: 'name',
            appDataEntityId: 'web.master',
            id: 'create_date',
          },
          {
            beginTimeAppDEFieldId: 'update_time',
            endTimeAppDEFieldId: 'update_time',
            idAppDEFieldId: 'id',
            itemStyle: 'DEFAULT',
            itemType: 'update_date',
            appDEDataSetId: 'fetch_default',
            textAppDEFieldId: 'name',
            appDataEntityId: 'web.master',
            id: 'update_date',
          },
        ],
        navViewPos: 'NONE',
        autoLoad: true,
        showBusyIndicator: true,
        codeName: 'calendar_multiple_data',
        controlType: 'CALENDAR',
        logicName: '日历_多数据',
        appDataEntityId: 'web.master',
        controlParam: {
          id: 'calendar',
        },
        modelId: '4a5860c7d50467dec9fc1d3707027abc',
        modelType: 'PSSYSCALENDAR',
        name: 'calendar',
        id: 'web.master.calendar_multiple_data',
      },
      {
        capLanguageRes: {
          lanResTag: 'DE.LNAME.MASTER',
        },
        caption: '日历_多数据',
        codeName: 'calendar_multiple_data_captionbar',
        controlType: 'CAPTIONBAR',
        appDataEntityId: 'web.master',
        controlParam: {},
        name: 'captionbar',
        id: 'calendar_multiple_data_captionbar',
      },
    ],
    codeName: 'usr0515314750',
    controlType: 'VIEWLAYOUTPANEL',
    logicName: '日历_多数据布局面板',
    appDataEntityId: 'web.master',
    controlParam: {},
    modelId: '0036a196f562bcea4d75afdac5738eae',
    modelType: 'PSSYSVIEWLAYOUTPANEL',
    name: 'layoutpanel',
    id: 'usr0515314750',
  },
  title: '日历_多数据',
  viewStyle: 'DEFAULT',
  viewType: 'DECUSTOMVIEW',
  enableDP: true,
  showCaptionBar: false,
  modelId: 'c1ec4c679558df6d76728c57621cb63a',
  modelType: 'PSAPPDEVIEW',
  name: 'MASTERcalendar_multiple_data',
  id: 'web.master_calendar_multiple_data',
};
