export default {
  deviewCodeName: 'treeview_nav',
  deviewId: '2b60e8652c9101bd2f330eb24c6d9471',
  accUserMode: 3,
  capLanguageRes: {
    lanResTag: 'DE.LNAME.MASTER',
  },
  caption: '树视图_内置导航',
  codeName: 'master_treeview_nav',
  appDataEntityId: 'web.master',
  appViewMsgGroupId: 'treeview_nav',
  viewLayoutPanel: {
    viewProxyMode: true,
    layoutMode: 'FLEX',
    layout: {
      layout: 'FLEX',
    },
    rootPanelItems: [
      {
        actionGroupExtractMode: 'ITEM',
        panelItems: [
          {
            actionGroupExtractMode: 'ITEM',
            panelItems: [
              {
                actionGroupExtractMode: 'ITEM',
                panelItems: [
                  {
                    caption: '树视图',
                    itemStyle: 'DEFAULT',
                    itemType: 'CTRLPOS',
                    layoutPos: {
                      shrink: 1,
                      layout: 'FLEX',
                    },
                    showCaption: true,
                    id: 'tree',
                  },
                ],
                predefinedType: 'CONTAINER_GROUP',
                layout: {
                  layout: 'FLEX',
                },
                dataRegionType: 'INHERIT',
                caption: '右方（内置导航宽度800）',
                itemStyle: 'DEFAULT',
                itemType: 'CONTAINER',
                layoutPos: {
                  layoutPos: 'CENTER',
                  layout: 'BORDER',
                },
                showCaption: true,
                id: 'container_group',
              },
              {
                actionGroupExtractMode: 'ITEM',
                panelItems: [
                  {
                    caption: '树视图',
                    contentHeight: 900,
                    height: 900,
                    itemStyle: 'DEFAULT',
                    itemType: 'CTRLPOS',
                    layoutPos: {
                      shrink: 1,
                      height: 900,
                      heightMode: 'PX',
                      layout: 'FLEX',
                    },
                    showCaption: true,
                    id: 'tree1',
                  },
                ],
                predefinedType: 'CONTAINER_GROUP',
                layout: {
                  layout: 'FLEX',
                },
                dataRegionType: 'INHERIT',
                caption: '下方（内置导航高度700）',
                itemStyle: 'DEFAULT',
                itemType: 'CONTAINER',
                layoutPos: {
                  layoutPos: 'CENTER',
                  layout: 'BORDER',
                },
                showCaption: true,
                id: 'container_group1',
              },
            ],
            predefinedType: 'CONTAINER_SCROLL_MAIN',
            layout: {
              layout: 'BORDER',
            },
            dataRegionType: 'INHERIT',
            caption: '面板容器',
            itemStyle: 'DEFAULT',
            itemType: 'CONTAINER',
            layoutPos: {
              layoutPos: 'CENTER',
              layout: 'BORDER',
            },
            showCaption: true,
            id: 'container_scroll_main',
          },
        ],
        predefinedType: 'CONTAINER_SCROLL',
        layout: {
          layout: 'BORDER',
        },
        dataRegionType: 'INHERIT',
        caption: '滚动条容器',
        itemStyle: 'DEFAULT',
        itemType: 'CONTAINER',
        layoutPos: {
          shrink: 1,
          layout: 'FLEX',
        },
        id: 'container_scroll',
      },
    ],
    layoutPanel: true,
    controls: [
      {
        detreeNodeRSs: [
          {
            childDETreeNodeId: 'node_2',
            parentAppDEFieldId: 'parent_id',
            parentDER1N: {
              pickupDEFName: 'PARENT_ID',
              codeName: 'parent',
              dertype: 'DER1N',
              logicName: '上级区划',
              orderValue: 100,
              serviceCodeName: 'parent',
              name: 'DER1N_REGION_REGION_PARENT_ID',
              id: 'mock.region.der1n_region_region_parent_id',
            },
            parentDETreeNodeId: 'node_2',
            parentValueLevel: 1,
            searchMode: 3,
            id: '区划子数据（node_2）-区划子数据（node_2）',
          },
          {
            childDETreeNodeId: 'node_2',
            parentAppDEFieldId: 'parent_id',
            parentDER1N: {
              pickupDEFName: 'PARENT_ID',
              codeName: 'parent',
              dertype: 'DER1N',
              logicName: '上级区划',
              orderValue: 100,
              serviceCodeName: 'parent',
              name: 'DER1N_REGION_REGION_PARENT_ID',
              id: 'mock.region.der1n_region_region_parent_id',
            },
            parentDETreeNodeId: 'node_1',
            parentValueLevel: 1,
            searchMode: 3,
            id: '区划数据（node_1）-区划子数据（node_2）',
          },
          {
            childDETreeNodeId: 'node_1',
            parentDETreeNodeId: 'root',
            parentValueLevel: 1,
            searchMode: 3,
            name: '默认根节点（ROOT）-区划数据（node_1）',
            id: '默认根节点（root）-区划数据（node_1）',
          },
        ],
        detreeNodes: [
          {
            text: '默认根节点',
            nodeType: 'ROOT',
            treeNodeType: 'STATIC',
            hasDETreeNodeRSs: true,
            rootNode: true,
            name: '默认根节点',
            id: 'root',
          },
          {
            dataSourceType: 'DEDATASET',
            idAppDEFieldId: 'id',
            leafFlagAppDEFieldId: 'leaf',
            appDEDataSetId: 'fetch_root',
            textAppDEFieldId: 'name',
            navAppViewId: 'web.region_info_view',
            nodeType: 'node_1',
            appDataEntityId: 'web.region',
            treeNodeType: 'DE',
            hasDETreeNodeRSs: true,
            name: '区划数据',
            id: 'node_1',
          },
          {
            dataSourceType: 'DEDATASET',
            idAppDEFieldId: 'id',
            leafFlagAppDEFieldId: 'leaf',
            appDEDataSetId: 'fetch_child',
            textAppDEFieldId: 'name',
            navAppViewId: 'web.region_info_view',
            nodeType: 'node_2',
            appDataEntityId: 'web.region',
            treeNodeType: 'DE',
            hasDETreeNodeRSs: true,
            name: '区划子数据',
            id: 'node_2',
          },
        ],
        outputIconDefault: true,
        navViewPos: 'RIGHT',
        navViewWidth: 800,
        createControlAction: {
          appDEMethodId: 'create',
          appDataEntityId: 'web.master',
          id: 'create',
        },
        fetchControlAction: {
          appDataEntityId: 'web.master',
          id: 'fetch',
        },
        getControlAction: {
          appDEMethodId: 'get',
          appDataEntityId: 'web.master',
          id: 'load',
        },
        removeControlAction: {
          appDEMethodId: 'remove',
          appDataEntityId: 'web.master',
          id: 'remove',
        },
        updateControlAction: {
          appDEMethodId: 'update',
          appDataEntityId: 'web.master',
          id: 'update',
        },
        autoLoad: true,
        showBusyIndicator: true,
        codeName: 'tree_right_nav',
        controlType: 'TREEVIEW',
        logicName: '树视图_内置导航右',
        appDataEntityId: 'web.master',
        controlParam: {
          id: 'tree',
        },
        modelId: '66ccb6f8503cc99ae52506110b6a1aae',
        modelType: 'PSDETREEVIEW',
        name: 'tree',
        id: 'web.master.tree_right_nav',
      },
      {
        detreeNodeRSs: [
          {
            childDETreeNodeId: 'node_2',
            parentAppDEFieldId: 'parent_id',
            parentDER1N: {
              pickupDEFName: 'PARENT_ID',
              codeName: 'parent',
              dertype: 'DER1N',
              logicName: '上级区划',
              orderValue: 100,
              serviceCodeName: 'parent',
              name: 'DER1N_REGION_REGION_PARENT_ID',
              id: 'mock.region.der1n_region_region_parent_id',
            },
            parentDETreeNodeId: 'node_2',
            parentValueLevel: 1,
            searchMode: 3,
            id: '区划子数据（node_2）-区划子数据（node_2）',
          },
          {
            childDETreeNodeId: 'node_2',
            parentAppDEFieldId: 'parent_id',
            parentDER1N: {
              pickupDEFName: 'PARENT_ID',
              codeName: 'parent',
              dertype: 'DER1N',
              logicName: '上级区划',
              orderValue: 100,
              serviceCodeName: 'parent',
              name: 'DER1N_REGION_REGION_PARENT_ID',
              id: 'mock.region.der1n_region_region_parent_id',
            },
            parentDETreeNodeId: 'node_1',
            parentValueLevel: 1,
            searchMode: 3,
            id: '区划数据（node_1）-区划子数据（node_2）',
          },
          {
            childDETreeNodeId: 'node_1',
            parentDETreeNodeId: 'root',
            parentValueLevel: 1,
            searchMode: 3,
            name: '默认根节点（ROOT）-区划数据（node_1）',
            id: '默认根节点（root）-区划数据（node_1）',
          },
        ],
        detreeNodes: [
          {
            text: '默认根节点',
            nodeType: 'ROOT',
            treeNodeType: 'STATIC',
            hasDETreeNodeRSs: true,
            rootNode: true,
            name: '默认根节点',
            id: 'root',
          },
          {
            dataSourceType: 'DEDATASET',
            idAppDEFieldId: 'id',
            leafFlagAppDEFieldId: 'leaf',
            appDEDataSetId: 'fetch_root',
            textAppDEFieldId: 'name',
            navAppViewId: 'web.region_info_view',
            nodeType: 'node_1',
            appDataEntityId: 'web.region',
            treeNodeType: 'DE',
            hasDETreeNodeRSs: true,
            name: '区划数据',
            id: 'node_1',
          },
          {
            dataSourceType: 'DEDATASET',
            idAppDEFieldId: 'id',
            leafFlagAppDEFieldId: 'leaf',
            appDEDataSetId: 'fetch_child',
            textAppDEFieldId: 'name',
            navAppViewId: 'web.region_info_view',
            nodeType: 'node_2',
            appDataEntityId: 'web.region',
            treeNodeType: 'DE',
            hasDETreeNodeRSs: true,
            name: '区划子数据',
            id: 'node_2',
          },
        ],
        outputIconDefault: true,
        navViewHeight: 700,
        navViewPos: 'BOTTOM',
        createControlAction: {
          appDEMethodId: 'create',
          appDataEntityId: 'web.master',
          id: 'create',
        },
        fetchControlAction: {
          appDataEntityId: 'web.master',
          id: 'fetch',
        },
        getControlAction: {
          appDEMethodId: 'get',
          appDataEntityId: 'web.master',
          id: 'load',
        },
        removeControlAction: {
          appDEMethodId: 'remove',
          appDataEntityId: 'web.master',
          id: 'remove',
        },
        updateControlAction: {
          appDEMethodId: 'update',
          appDataEntityId: 'web.master',
          id: 'update',
        },
        autoLoad: true,
        showBusyIndicator: true,
        codeName: 'tree_bottom_nav',
        controlType: 'TREEVIEW',
        logicName: '树视图_内置导航下',
        appDataEntityId: 'web.master',
        controlParam: {
          id: 'tree1',
        },
        modelId: '75d602062688e260543c12655ef57830',
        modelType: 'PSDETREEVIEW',
        name: 'tree1',
        id: 'web.master.tree_bottom_nav',
      },
      {
        capLanguageRes: {
          lanResTag: 'DE.LNAME.MASTER',
        },
        caption: '树视图_内置导航',
        codeName: 'treeview_nav_captionbar',
        controlType: 'CAPTIONBAR',
        appDataEntityId: 'web.master',
        controlParam: {},
        name: 'captionbar',
        id: 'treeview_nav_captionbar',
      },
    ],
    codeName: 'ab65d666af3925812d4',
    controlType: 'VIEWLAYOUTPANEL',
    logicName: '树视图——内置导航布局面板',
    appDataEntityId: 'web.master',
    controlParam: {},
    modelId: '9372b4440a23f53fdde4a997dadc61e7',
    modelType: 'PSSYSVIEWLAYOUTPANEL',
    name: 'layoutpanel',
    id: 'ab65d666af3925812d4',
  },
  title: '树视图_内置导航',
  viewStyle: 'DEFAULT',
  viewType: 'DECUSTOMVIEW',
  enableDP: true,
  showCaptionBar: false,
  modelId: 'f8a4b4f58b6e377ab5f5c7bd8147b009',
  modelType: 'PSAPPDEVIEW',
  name: 'MASTERtreeview_nav',
  id: 'web.master_treeview_nav',
};
