export default {
  mdctrlActiveMode: 2,
  xdataControlName: 'tree',
  loadDefault: true,
  deviewCodeName: 'counter_tree',
  deviewId: '77db7e21ff352c9456d57f80f8cbe5fd',
  accUserMode: 3,
  capLanguageRes: {
    lanResTag: 'DE.LNAME.MASTER',
  },
  caption: '计数器_树视图',
  codeName: 'master_counter_tree',
  appDataEntityId: 'web.master',
  appViewEngines: [
    {
      engineCat: 'VIEW',
      engineType: 'TreeView',
      id: 'engine',
    },
  ],
  appViewMsgGroupId: 'counter_tree',
  controls: [
    {
      appCounterRefId: 'c08c472f59332aa507b4952a6d4e5c5f',
      detreeNodeRSs: [
        {
          childDETreeNodeId: 'node_2',
          parentDETreeNodeId: 'node',
          parentValueLevel: 1,
          searchMode: 3,
          id: '节点名称（node）-节点名称2（node_2）',
        },
        {
          childDETreeNodeId: 'node',
          parentDETreeNodeId: 'root',
          parentValueLevel: 1,
          searchMode: 3,
          name: '默认根节点（ROOT）-节点名称（node）',
          id: '默认根节点（root）-节点名称（node）',
        },
        {
          childDETreeNodeId: 'node_1',
          parentDETreeNodeId: 'root',
          parentValueLevel: 1,
          searchMode: 3,
          name: '默认根节点（ROOT）-节点名称1（node_1）',
          id: '默认根节点（root）-节点名称1（node_1）',
        },
      ],
      detreeNodes: [
        {
          text: '默认根节点',
          nodeType: 'ROOT',
          treeNodeType: 'STATIC',
          hasDETreeNodeRSs: true,
          rootNode: true,
          name: '默认根节点',
          id: 'root',
        },
        {
          text: '节点1',
          nodeType: 'node',
          treeNodeType: 'STATIC',
          hasDETreeNodeRSs: true,
          name: '节点1',
          id: 'node',
        },
        {
          text: '节点2',
          counterId: 'tree',
          nodeType: 'node_1',
          treeNodeType: 'STATIC',
          name: '节点2',
          id: 'node_1',
        },
        {
          text: '节点1-1',
          nodeType: 'node_2',
          treeNodeType: 'STATIC',
          name: '节点1-1',
          id: 'node_2',
        },
      ],
      outputIconDefault: true,
      navViewPos: 'NONE',
      createControlAction: {
        appDEMethodId: 'create',
        appDataEntityId: 'web.master',
        id: 'create',
      },
      fetchControlAction: {
        appDataEntityId: 'web.master',
        id: 'fetch',
      },
      getControlAction: {
        appDEMethodId: 'get',
        appDataEntityId: 'web.master',
        id: 'load',
      },
      removeControlAction: {
        appDEMethodId: 'remove',
        appDataEntityId: 'web.master',
        id: 'remove',
      },
      updateControlAction: {
        appDEMethodId: 'update',
        appDataEntityId: 'web.master',
        id: 'update',
      },
      autoLoad: true,
      showBusyIndicator: true,
      appCounterRefs: [
        {
          appCounter: {
            codeName: 'Counter',
            counterType: 'DEDR',
            getAppDEActionId: 'get_counter_data',
            appDataEntityId: 'web.master',
            timer: 60000,
            uniqueTag: 'Counter',
            name: '计数器',
            id: 'web.counter',
          },
          tag: 'c08c472f59332aa507b4952a6d4e5c5f',
          uniqueTag: 'Counter',
          id: 'c08c472f59332aa507b4952a6d4e5c5f',
        },
      ],
      codeName: 'counter_tree_tree_view',
      controlType: 'TREEVIEW',
      logicName: '计数器_树视图_树视图',
      appDataEntityId: 'web.master',
      controlParam: {
        id: 'tree',
      },
      modelId: '4f8ae429f974d30ec2e125a65f96daa8',
      modelType: 'PSDETREEVIEW',
      name: 'tree',
      id: 'web.master.counter_tree_tree_view',
    },
    {
      groupMode: 'SINGLE',
      controlType: 'SEARCHBAR',
      appDataEntityId: 'web.master',
      controlParam: {
        id: 'searchbar',
      },
      id: 'searchbar',
    },
    {
      capLanguageRes: {
        lanResTag: 'DE.LNAME.MASTER',
      },
      caption: '计数器_树视图',
      codeName: 'counter_tree_captionbar',
      controlType: 'CAPTIONBAR',
      appDataEntityId: 'web.master',
      controlParam: {},
      name: 'captionbar',
      id: 'counter_tree_captionbar',
    },
  ],
  viewLayoutPanel: {
    layoutBodyOnly: true,
    useDefaultLayout: true,
    layoutPanel: true,
    codeName: 'layoutpanel',
    controlStyle: 'APPDETREEVIEW',
    controlType: 'VIEWLAYOUTPANEL',
    appDataEntityId: 'web.master',
    controlParam: {},
    id: 'layoutpanel',
  },
  title: '计数器_树视图',
  viewStyle: 'DEFAULT',
  viewType: 'DETREEVIEW',
  enableDP: true,
  showCaptionBar: false,
  modelId: '5a27f677a8e3a74073267fe2b9d61f96',
  modelType: 'PSAPPDEVIEW',
  name: 'MASTERcounter_tree',
  id: 'web.master_counter_tree',
};
