export default {
  deviewCodeName: 'Tree_base',
  deviewId: '6aefa50fa45c5c3472a9b2249b066bd6',
  accUserMode: 3,
  capLanguageRes: {
    lanResTag: 'DE.LNAME.MASTER',
  },
  caption: '树视图_基础',
  codeName: 'master_tree_base',
  appDataEntityId: 'web.master',
  appViewMsgGroupId: 'tree_base',
  viewLayoutPanel: {
    viewProxyMode: true,
    layoutMode: 'FLEX',
    layout: {
      layout: 'FLEX',
    },
    rootPanelItems: [
      {
        actionGroupExtractMode: 'ITEM',
        panelItems: [
          {
            actionGroupExtractMode: 'ITEM',
            panelItems: [
              {
                dataRegionType: 'INHERIT',
                panelTabPages: [
                  {
                    panelItems: [
                      {
                        caption: '树视图',
                        itemStyle: 'DEFAULT',
                        itemType: 'CTRLPOS',
                        layoutPos: {
                          shrink: 1,
                          layout: 'FLEX',
                        },
                        showCaption: true,
                        id: 'tree',
                      },
                    ],
                    layout: {
                      layout: 'FLEX',
                    },
                    dataRegionType: 'INHERIT',
                    caption: '静态节点',
                    itemStyle: 'DEFAULT',
                    itemType: 'TABPAGE',
                    layoutPos: {
                      shrink: 1,
                      layout: 'FLEX',
                    },
                    showCaption: true,
                    id: 'tabpage',
                  },
                  {
                    panelItems: [
                      {
                        caption: '树视图',
                        itemStyle: 'DEFAULT',
                        itemType: 'CTRLPOS',
                        layoutPos: {
                          shrink: 1,
                          layout: 'FLEX',
                        },
                        showCaption: true,
                        id: 'tree1',
                      },
                    ],
                    layout: {
                      layout: 'FLEX',
                    },
                    dataRegionType: 'INHERIT',
                    caption: '代码表节点',
                    itemStyle: 'DEFAULT',
                    itemType: 'TABPAGE',
                    layoutPos: {
                      shrink: 1,
                      layout: 'FLEX',
                    },
                    showCaption: true,
                    id: 'tabpage1',
                  },
                  {
                    panelItems: [
                      {
                        caption: '树视图',
                        itemStyle: 'DEFAULT',
                        itemType: 'CTRLPOS',
                        layoutPos: {
                          shrink: 1,
                          layout: 'FLEX',
                        },
                        showCaption: true,
                        id: 'tree2',
                      },
                    ],
                    layout: {
                      layout: 'FLEX',
                    },
                    dataRegionType: 'INHERIT',
                    caption: '实体节点',
                    itemStyle: 'DEFAULT',
                    itemType: 'TABPAGE',
                    layoutPos: {
                      shrink: 1,
                      layout: 'FLEX',
                    },
                    showCaption: true,
                    id: 'tabpage2',
                  },
                ],
                caption: '分页部件',
                itemStyle: 'DEFAULT',
                itemType: 'TABPANEL',
                layoutPos: {
                  layoutPos: 'CENTER',
                  layout: 'BORDER',
                  spacingLeft: 'OUTERMEDIUM',
                  spacingRight: 'OUTERMEDIUM',
                },
                id: 'tabpanel',
              },
            ],
            predefinedType: 'CONTAINER_SCROLL_MAIN',
            layout: {
              layout: 'BORDER',
            },
            dataRegionType: 'INHERIT',
            caption: '面板容器',
            itemStyle: 'DEFAULT',
            itemType: 'CONTAINER',
            layoutPos: {
              layoutPos: 'CENTER',
              layout: 'BORDER',
            },
            showCaption: true,
            id: 'container_scroll_main',
          },
        ],
        predefinedType: 'CONTAINER_SCROLL',
        layout: {
          layout: 'BORDER',
        },
        dataRegionType: 'INHERIT',
        caption: '滚动条容器',
        itemStyle: 'DEFAULT',
        itemType: 'CONTAINER',
        layoutPos: {
          shrink: 1,
          layout: 'FLEX',
        },
        id: 'container_scroll',
      },
    ],
    layoutPanel: true,
    controls: [
      {
        detreeNodeRSs: [
          {
            childDETreeNodeId: 'node_2',
            parentDETreeNodeId: 'node',
            parentValueLevel: 1,
            searchMode: 3,
            id: '静态节点1（node）-静态节点1-1（node_2）',
          },
          {
            childDETreeNodeId: 'node_4',
            parentDETreeNodeId: 'node_1',
            parentValueLevel: 1,
            searchMode: 3,
            id: '静态节点2（node_1）-静态节点2-1（node_4）',
          },
          {
            childDETreeNodeId: 'node',
            parentDETreeNodeId: 'root',
            parentValueLevel: 1,
            searchMode: 3,
            name: '默认根节点（ROOT）-静态节点1（node）',
            id: '默认根节点（root）-静态节点1（node）',
          },
          {
            childDETreeNodeId: 'node_3',
            parentDETreeNodeId: 'node',
            parentValueLevel: 1,
            searchMode: 3,
            id: '静态节点1（node）-静态节点1-2（node_3）',
          },
          {
            childDETreeNodeId: 'node_5',
            parentDETreeNodeId: 'node_1',
            parentValueLevel: 1,
            searchMode: 3,
            id: '静态节点2（node_1）-静态节点2-2（node_5）',
          },
          {
            childDETreeNodeId: 'node_1',
            parentDETreeNodeId: 'root',
            parentValueLevel: 1,
            searchMode: 3,
            name: '默认根节点（ROOT）-静态节点2（node_1）',
            id: '默认根节点（root）-静态节点2（node_1）',
          },
        ],
        detreeNodes: [
          {
            text: '默认根节点',
            nodeType: 'ROOT',
            treeNodeType: 'STATIC',
            hasDETreeNodeRSs: true,
            rootNode: true,
            name: '默认根节点',
            id: 'root',
          },
          {
            text: '静态节点1',
            nodeType: 'node',
            treeNodeType: 'STATIC',
            hasDETreeNodeRSs: true,
            name: '静态节点1',
            id: 'node',
          },
          {
            text: '静态节点2',
            nodeType: 'node_1',
            treeNodeType: 'STATIC',
            hasDETreeNodeRSs: true,
            name: '静态节点2',
            id: 'node_1',
          },
          {
            text: '静态节点1-1',
            nodeType: 'node_2',
            treeNodeType: 'STATIC',
            name: '静态节点1-1',
            id: 'node_2',
          },
          {
            text: '静态节点1-2',
            nodeType: 'node_3',
            treeNodeType: 'STATIC',
            name: '静态节点1-2',
            id: 'node_3',
          },
          {
            text: '静态节点2-1',
            nodeType: 'node_4',
            treeNodeType: 'STATIC',
            name: '静态节点2-1',
            id: 'node_4',
          },
          {
            text: '静态节点2-2',
            nodeType: 'node_5',
            treeNodeType: 'STATIC',
            name: '静态节点2-2',
            id: 'node_5',
          },
        ],
        outputIconDefault: true,
        navViewPos: 'NONE',
        createControlAction: {
          appDEMethodId: 'create',
          appDataEntityId: 'web.master',
          id: 'create',
        },
        fetchControlAction: {
          appDataEntityId: 'web.master',
          id: 'fetch',
        },
        getControlAction: {
          appDEMethodId: 'get',
          appDataEntityId: 'web.master',
          id: 'load',
        },
        removeControlAction: {
          appDEMethodId: 'remove',
          appDataEntityId: 'web.master',
          id: 'remove',
        },
        updateControlAction: {
          appDEMethodId: 'update',
          appDataEntityId: 'web.master',
          id: 'update',
        },
        autoLoad: true,
        showBusyIndicator: true,
        codeName: 'tree_base1',
        controlType: 'TREEVIEW',
        logicName: '树视图基础_静态节点',
        appDataEntityId: 'web.master',
        controlParam: {
          id: 'tree',
        },
        modelId: 'a28894eef7a2c956a51e0746f3e9d2dd',
        modelType: 'PSDETREEVIEW',
        name: 'tree',
        id: 'web.master.tree_base1',
      },
      {
        detreeNodeRSs: [
          {
            childDETreeNodeId: 'node_3',
            parentDETreeNodeId: 'root',
            parentValueLevel: 1,
            searchMode: 3,
            name: '默认根节点（ROOT）-地区代码表（node_3）',
            id: '默认根节点（root）-地区代码表（node_3）',
          },
          {
            childDETreeNodeId: 'node_1',
            parentDETreeNodeId: 'node_3',
            parentValueLevel: 1,
            searchMode: 3,
            id: '地区代码表（node_3）-地区（node_1）',
          },
          {
            childDETreeNodeId: 'node',
            parentDETreeNodeId: 'node_2',
            parentValueLevel: 1,
            searchMode: 3,
            id: '选项代码表（node_2）-选项（node）',
          },
          {
            childDETreeNodeId: 'node_2',
            parentDETreeNodeId: 'root',
            parentValueLevel: 1,
            searchMode: 3,
            name: '默认根节点（ROOT）-选项代码表（node_2）',
            id: '默认根节点（root）-选项代码表（node_2）',
          },
        ],
        detreeNodes: [
          {
            text: '默认根节点',
            nodeType: 'ROOT',
            treeNodeType: 'STATIC',
            hasDETreeNodeRSs: true,
            rootNode: true,
            name: '默认根节点',
            id: 'root',
          },
          {
            codeListId: 'web.mock__cl_sample',
            nodeType: 'node',
            treeNodeType: 'CODELIST',
            name: '选项',
            id: 'node',
          },
          {
            codeListId: 'web.mock__cl_status',
            nodeType: 'node_1',
            treeNodeType: 'CODELIST',
            expanded: true,
            name: '状态',
            id: 'node_1',
          },
          {
            text: '选项代码表',
            nodeType: 'node_2',
            treeNodeType: 'STATIC',
            hasDETreeNodeRSs: true,
            expanded: true,
            name: '选项代码表',
            id: 'node_2',
          },
          {
            text: '状态代码表',
            nodeType: 'node_3',
            treeNodeType: 'STATIC',
            hasDETreeNodeRSs: true,
            expanded: true,
            name: '状态代码表',
            id: 'node_3',
          },
        ],
        outputIconDefault: true,
        navViewPos: 'NONE',
        createControlAction: {
          appDEMethodId: 'create',
          appDataEntityId: 'web.master',
          id: 'create',
        },
        fetchControlAction: {
          appDataEntityId: 'web.master',
          id: 'fetch',
        },
        getControlAction: {
          appDEMethodId: 'get',
          appDataEntityId: 'web.master',
          id: 'load',
        },
        removeControlAction: {
          appDEMethodId: 'remove',
          appDataEntityId: 'web.master',
          id: 'remove',
        },
        updateControlAction: {
          appDEMethodId: 'update',
          appDataEntityId: 'web.master',
          id: 'update',
        },
        autoLoad: true,
        showBusyIndicator: true,
        codeName: 'tree_base2',
        controlType: 'TREEVIEW',
        logicName: '树视图基础_代码表节点',
        appDataEntityId: 'web.master',
        controlParam: {
          id: 'tree1',
        },
        modelId: 'aa0b4131d52aa48066f931dcd4579cf2',
        modelType: 'PSDETREEVIEW',
        name: 'tree1',
        id: 'web.master.tree_base2',
      },
      {
        detreeNodeRSs: [
          {
            childDETreeNodeId: 'node_4',
            parentAppDEFieldId: 'parent_id',
            parentDER1N: {
              pickupDEFName: 'PARENT_ID',
              codeName: 'parent',
              dertype: 'DER1N',
              logicName: '上级区划',
              orderValue: 100,
              serviceCodeName: 'parent',
              name: 'DER1N_REGION_REGION_PARENT_ID',
              id: 'mock.region.der1n_region_region_parent_id',
            },
            parentDETreeNodeId: 'node_4',
            parentValueLevel: 1,
            searchMode: 3,
            id: '区划子数据（node_4）-区划子数据（node_4）',
          },
          {
            childDETreeNodeId: 'node',
            parentDETreeNodeId: 'node_3',
            parentValueLevel: 1,
            searchMode: 3,
            id: '主数据（node_3）-名称（node）',
          },
          {
            childDETreeNodeId: 'node_2',
            parentAppDEFieldId: 'parent_id',
            parentDER1N: {
              pickupDEFName: 'PARENT_ID',
              codeName: 'parent',
              dertype: 'DER1N',
              logicName: '上级区划',
              orderValue: 100,
              serviceCodeName: 'parent',
              name: 'DER1N_REGION_REGION_PARENT_ID',
              id: 'mock.region.der1n_region_region_parent_id',
            },
            parentDETreeNodeId: 'node_1',
            parentValueLevel: 1,
            searchMode: 3,
            id: '明细数据（node_1）-明显名称（node_2）',
          },
          {
            childDETreeNodeId: 'node_4',
            parentAppDEFieldId: 'parent_id',
            parentDER1N: {
              pickupDEFName: 'PARENT_ID',
              codeName: 'parent',
              dertype: 'DER1N',
              logicName: '上级区划',
              orderValue: 100,
              serviceCodeName: 'parent',
              name: 'DER1N_REGION_REGION_PARENT_ID',
              id: 'mock.region.der1n_region_region_parent_id',
            },
            parentDETreeNodeId: 'node_2',
            parentValueLevel: 1,
            searchMode: 3,
            id: '区划数据（node_2）-区划子数据（node_4）',
          },
          {
            childDETreeNodeId: 'node_3',
            parentDETreeNodeId: 'root',
            parentValueLevel: 1,
            searchMode: 3,
            name: '默认根节点（ROOT）-主数据（node_3）',
            id: '默认根节点（root）-主数据（node_3）',
          },
          {
            childDETreeNodeId: 'node_1',
            parentDETreeNodeId: 'root',
            parentValueLevel: 1,
            searchMode: 3,
            name: '默认根节点（ROOT）-区划数据（node_1）',
            id: '默认根节点（root）-区划数据（node_1）',
          },
        ],
        detreeNodes: [
          {
            text: '默认根节点',
            nodeType: 'ROOT',
            treeNodeType: 'STATIC',
            hasDETreeNodeRSs: true,
            rootNode: true,
            name: '默认根节点',
            id: 'root',
          },
          {
            dataSourceType: 'DEDATASET',
            idAppDEFieldId: 'id',
            appDEDataSetId: 'fetch_default',
            textAppDEFieldId: 'name',
            nodeType: 'node',
            appDataEntityId: 'web.master',
            treeNodeType: 'DE',
            expanded: true,
            name: '名称',
            id: 'node',
          },
          {
            text: '区划',
            nodeType: 'node_1',
            treeNodeType: 'STATIC',
            hasDETreeNodeRSs: true,
            name: '区划',
            id: 'node_1',
          },
          {
            dataSourceType: 'DEDATASET',
            idAppDEFieldId: 'id',
            leafFlagAppDEFieldId: 'leaf',
            appDEDataSetId: 'fetch_root',
            textAppDEFieldId: 'name',
            nodeType: 'node_2',
            appDataEntityId: 'web.region',
            treeNodeType: 'DE',
            hasDETreeNodeRSs: true,
            name: '区划数据',
            id: 'node_2',
          },
          {
            text: '主数据',
            nodeType: 'node_3',
            treeNodeType: 'STATIC',
            hasDETreeNodeRSs: true,
            name: '主数据',
            id: 'node_3',
          },
          {
            dataSourceType: 'DEDATASET',
            idAppDEFieldId: 'id',
            leafFlagAppDEFieldId: 'leaf',
            appDEDataSetId: 'fetch_child',
            textAppDEFieldId: 'name',
            nodeType: 'node_4',
            appDataEntityId: 'web.region',
            treeNodeType: 'DE',
            hasDETreeNodeRSs: true,
            name: '区划子数据',
            id: 'node_4',
          },
        ],
        outputIconDefault: true,
        navViewPos: 'NONE',
        createControlAction: {
          appDEMethodId: 'create',
          appDataEntityId: 'web.master',
          id: 'create',
        },
        fetchControlAction: {
          appDataEntityId: 'web.master',
          id: 'fetch',
        },
        getControlAction: {
          appDEMethodId: 'get',
          appDataEntityId: 'web.master',
          id: 'load',
        },
        removeControlAction: {
          appDEMethodId: 'remove',
          appDataEntityId: 'web.master',
          id: 'remove',
        },
        updateControlAction: {
          appDEMethodId: 'update',
          appDataEntityId: 'web.master',
          id: 'update',
        },
        autoLoad: true,
        showBusyIndicator: true,
        codeName: 'tree_base3',
        controlType: 'TREEVIEW',
        logicName: '树视图基础_实体节点',
        appDataEntityId: 'web.master',
        controlParam: {
          id: 'tree2',
        },
        modelId: 'f8b1a1a772a926809a1706ea7f7332d4',
        modelType: 'PSDETREEVIEW',
        name: 'tree2',
        id: 'web.master.tree_base3',
      },
      {
        capLanguageRes: {
          lanResTag: 'DE.LNAME.MASTER',
        },
        caption: '树视图_基础',
        codeName: 'tree_base_captionbar',
        controlType: 'CAPTIONBAR',
        appDataEntityId: 'web.master',
        controlParam: {},
        name: 'captionbar',
        id: 'tree_base_captionbar',
      },
    ],
    codeName: 'adce9c785d92c11f262',
    controlType: 'VIEWLAYOUTPANEL',
    logicName: '树视图_基础布局面板',
    appDataEntityId: 'web.master',
    controlParam: {},
    modelId: '98565a2573959c4a8e8e31415e848e90',
    modelType: 'PSSYSVIEWLAYOUTPANEL',
    name: 'layoutpanel',
    id: 'adce9c785d92c11f262',
  },
  title: '树视图_基础',
  viewStyle: 'DEFAULT',
  viewType: 'DECUSTOMVIEW',
  enableDP: true,
  showCaptionBar: false,
  modelId: 'a9afacfc4f22f1e58a11e0dc5674ee7d',
  modelType: 'PSAPPDEVIEW',
  name: 'MASTERTree_base',
  id: 'web.master_tree_base',
};
