export default {
  tabLayout: 'FLOW',
  loadDefault: true,
  showDataInfoBar: true,
  deviewCodeName: 'logic_plugin',
  deviewId: '9ed5cdfa831f8341dde10c78aa96d4fa',
  accUserMode: 3,
  capLanguageRes: {
    lanResTag: 'DE.LNAME.MASTER',
  },
  caption: '逻辑插件',
  codeName: 'master_logic_plugin',
  appDataEntityId: 'web.master',
  appViewEngines: [
    {
      engineCat: 'VIEW',
      engineType: 'TabExpView',
      id: 'engine',
    },
  ],
  appViewMsgGroupId: 'logic_plugin',
  controls: [
    {
      dedrtabPages: [
        {
          caption: '计数器插件',
          appViewId: 'web.master_counter_plugin',
          id: 'counter_plugin',
        },
        {
          caption: '实体行为插件',
          appViewId: 'web.master_de_action_plugin',
          id: 'de_action_plugin',
        },
        {
          caption: '界面行为插件',
          appViewId: 'web.master_action_plugin',
          id: 'action_plugin',
        },
        {
          caption: '界面逻辑节点插件',
          appViewId: 'web.master_ui_logic_plugin',
          id: 'ui_logic_plugin',
        },
      ],
      dataRelationTag: 'DataRelation4',
      editItemCapLanguageRes: {
        lanResTag: 'DE.LNAME.MASTER',
      },
      editItemCaption: '主数据',
      uniqueTag: 'master_logic_plugin__tabexppanel',
      autoLoad: true,
      showBusyIndicator: true,
      codeName: 'data_relation4',
      controlType: 'DRTAB',
      appDataEntityId: 'web.master',
      controlParam: {
        id: 'tabexppanel',
      },
      modelId: 'f32ab4855d160ca1b25b85c016900b9c',
      modelType: 'PSDEDRTAB',
      name: 'tabexppanel',
      id: 'data_relation4',
    },
    {
      capLanguageRes: {
        lanResTag: 'DE.LNAME.MASTER',
      },
      caption: '逻辑插件',
      codeName: 'logic_plugin_captionbar',
      controlType: 'CAPTIONBAR',
      appDataEntityId: 'web.master',
      controlParam: {},
      name: 'captionbar',
      id: 'logic_plugin_captionbar',
    },
  ],
  viewLayoutPanel: {
    layoutBodyOnly: true,
    useDefaultLayout: true,
    layoutPanel: true,
    codeName: 'layoutpanel',
    controlStyle: 'APPDETABEXPVIEW',
    controlType: 'VIEWLAYOUTPANEL',
    appDataEntityId: 'web.master',
    controlParam: {},
    id: 'layoutpanel',
  },
  title: '逻辑插件',
  viewStyle: 'DEFAULT',
  viewType: 'DETABEXPVIEW',
  enableDP: true,
  showCaptionBar: false,
  modelId: '014d14fd3fed59d5ca8f5d7d33c7f143',
  modelType: 'PSAPPDEVIEW',
  name: 'MASTERlogic_plugin',
  id: 'web.master_logic_plugin',
};
