export default {
  deviewCodeName: 'list_group',
  deviewId: 'e78605e11099709547d88a41386253c6',
  accUserMode: 3,
  capLanguageRes: {
    lanResTag: 'DE.LNAME.MASTER',
  },
  caption: '列表_分组',
  codeName: 'master_list_group',
  appDataEntityId: 'web.master',
  appViewMsgGroupId: 'list_group',
  viewLayoutPanel: {
    viewProxyMode: true,
    layoutMode: 'FLEX',
    layout: {
      layout: 'FLEX',
    },
    rootPanelItems: [
      {
        actionGroupExtractMode: 'ITEM',
        panelItems: [
          {
            actionGroupExtractMode: 'ITEM',
            panelItems: [
              {
                actionGroupExtractMode: 'ITEM',
                panelItems: [
                  {
                    caption: '列表',
                    itemStyle: 'DEFAULT',
                    itemType: 'CTRLPOS',
                    layoutPos: {
                      shrink: 1,
                      layout: 'FLEX',
                    },
                    showCaption: true,
                    id: 'list',
                  },
                ],
                predefinedType: 'CONTAINER_GROUP',
                layout: {
                  layout: 'FLEX',
                },
                dataRegionType: 'INHERIT',
                caption: '自动分组',
                itemStyle: 'DEFAULT',
                itemType: 'CONTAINER',
                layoutPos: {
                  layoutPos: 'CENTER',
                  layout: 'BORDER',
                },
                showCaption: true,
                id: 'container_group',
              },
              {
                actionGroupExtractMode: 'ITEM',
                panelItems: [
                  {
                    caption: '列表',
                    itemStyle: 'DEFAULT',
                    itemType: 'CTRLPOS',
                    layoutPos: {
                      shrink: 1,
                      layout: 'FLEX',
                    },
                    showCaption: true,
                    id: 'list1',
                  },
                ],
                predefinedType: 'CONTAINER_GROUP',
                layout: {
                  layout: 'FLEX',
                },
                dataRegionType: 'INHERIT',
                caption: '分组代码表',
                itemStyle: 'DEFAULT',
                itemType: 'CONTAINER',
                layoutPos: {
                  layoutPos: 'CENTER',
                  layout: 'BORDER',
                },
                showCaption: true,
                id: 'container_group1',
              },
              {
                actionGroupExtractMode: 'ITEM',
                panelItems: [
                  {
                    caption: '列表',
                    itemStyle: 'DEFAULT',
                    itemType: 'CTRLPOS',
                    layoutPos: {
                      shrink: 1,
                      layout: 'FLEX',
                    },
                    showCaption: true,
                    id: 'list2',
                  },
                ],
                predefinedType: 'CONTAINER_GROUP',
                layout: {
                  layout: 'FLEX',
                },
                dataRegionType: 'INHERIT',
                caption: '分组界面行为组',
                itemStyle: 'DEFAULT',
                itemType: 'CONTAINER',
                layoutPos: {
                  layoutPos: 'CENTER',
                  layout: 'BORDER',
                },
                showCaption: true,
                id: 'container_group2',
              },
            ],
            predefinedType: 'CONTAINER_SCROLL_MAIN',
            layout: {
              layout: 'BORDER',
            },
            dataRegionType: 'INHERIT',
            caption: '面板容器',
            itemStyle: 'DEFAULT',
            itemType: 'CONTAINER',
            layoutPos: {
              layoutPos: 'CENTER',
              layout: 'BORDER',
            },
            showCaption: true,
            id: 'container_scroll_main',
          },
        ],
        predefinedType: 'CONTAINER_SCROLL',
        layout: {
          layout: 'BORDER',
        },
        dataRegionType: 'INHERIT',
        caption: '滚动条容器',
        itemStyle: 'DEFAULT',
        itemType: 'CONTAINER',
        layoutPos: {
          shrink: 1,
          layout: 'FLEX',
        },
        id: 'container_scroll',
      },
    ],
    layoutPanel: true,
    controls: [
      {
        groupMode: 'CODELIST',
        groupAppDEFieldId: 'status',
        groupCodeListId: 'web.mock__cl_status',
        groupStyle: 'DEFAULT',
        itemLayoutPanel: {
          layoutMode: 'FLEX',
          layout: {
            layout: 'FLEX',
          },
          rootPanelItems: [
            {
              actionGroupExtractMode: 'ITEM',
              panelItems: [
                {
                  editor: {
                    halign: 'LEFT',
                    renderMode: 'TEXT_DYNAMIC',
                    valign: 'MIDDLE',
                    wrapMode: 'NOWRAP',
                    editorType: 'SPAN',
                    predefinedType: 'FIELD_TEXT_DYNAMIC',
                    valueType: 'SIMPLE',
                    editable: true,
                    id: 'name',
                  },
                  viewFieldName: 'name',
                  allowEmpty: true,
                  caption: '文本(动态)',
                  itemStyle: 'DEFAULT',
                  itemType: 'FIELD',
                  layoutPos: {
                    shrink: 1,
                    layout: 'FLEX',
                  },
                  id: 'name',
                },
              ],
              layout: {
                layout: 'FLEX',
              },
              dataRegionType: 'INHERIT',
              caption: '容器',
              itemStyle: 'DEFAULT',
              itemType: 'CONTAINER',
              layoutPos: {
                shrink: 1,
                layout: 'FLEX',
              },
              id: 'container',
            },
          ],
          layoutPanel: true,
          codeName: 'a44a27a4c8d8057098a',
          controlType: 'PANEL',
          logicName: 'list_group2列表',
          appDataEntityId: 'web.master',
          controlParam: {},
          modelId: '70dd187124e80c9427847e92e4dd08d9',
          modelType: 'PSSYSVIEWPANEL',
          name: 'list1_itempanel',
          id: 'web.master.a44a27a4c8d8057098a',
        },
        delistDataItems: [
          {
            appDEFieldId: 'name',
            dataType: 25,
            id: 'name',
          },
          {
            appDEFieldId: 'id',
            dataType: 25,
            id: 'srfkey',
          },
          {
            appDEFieldId: 'name',
            dataType: 25,
            id: 'srfmajortext',
          },
          {
            appDEFieldId: 'region_id',
            dataType: 25,
            id: 'region_id',
          },
        ],
        pagingSize: 1000,
        enableGroup: true,
        showHeader: true,
        navViewPos: 'NONE',
        createControlAction: {
          appDEMethodId: 'create',
          appDataEntityId: 'web.master',
          id: 'create',
        },
        fetchControlAction: {
          appDEMethodId: 'fetch_default',
          appDataEntityId: 'web.master',
          id: 'fetch',
        },
        getControlAction: {
          appDEMethodId: 'get',
          appDataEntityId: 'web.master',
          id: 'load',
        },
        removeControlAction: {
          appDEMethodId: 'remove',
          appDataEntityId: 'web.master',
          id: 'remove',
        },
        updateControlAction: {
          appDEMethodId: 'update',
          appDataEntityId: 'web.master',
          id: 'update',
        },
        autoLoad: true,
        showBusyIndicator: true,
        codeName: 'list_group2',
        controlType: 'LIST',
        logicName: 'list_group2',
        appDataEntityId: 'web.master',
        controlParam: {
          id: 'list1',
        },
        modelId: '26f6acda111bc642f505bd1b699c6e60',
        modelType: 'PSDELIST',
        name: 'list1',
        id: 'web.master.list_group2',
      },
      {
        groupMode: 'CODELIST',
        groupAppDEFieldId: 'status',
        groupCodeListId: 'web.mock__cl_status',
        groupUIActionGroup: {
          uiactionGroupDetails: [
            {
              actionLevel: 100,
              afterItemType: 'NONE',
              beforeItemType: 'NONE',
              buttonStyle: 'DEFAULT',
              caption: '打开关于',
              detailType: 'DEUIACTION',
              uiactionId: 'open_about@master',
              showCaption: true,
              showIcon: true,
              sysImage: {
                cssClass: 'fa fa-info-circle',
                glyph: 'xf05a@FontAwesome',
              },
              id: 'ubc28a2e',
            },
            {
              actionLevel: 100,
              afterItemType: 'NONE',
              beforeItemType: 'NONE',
              buttonStyle: 'DEFAULT',
              caption: '打开文档',
              detailType: 'DEUIACTION',
              uiactionId: 'open_document@master',
              showCaption: true,
              showIcon: true,
              id: 'u16b8690',
            },
            {
              actionLevel: 100,
              afterItemType: 'NONE',
              beforeItemType: 'NONE',
              buttonStyle: 'DEFAULT',
              caption: '打开弹窗',
              detailType: 'DEUIACTION',
              uiactionId: 'open_dialog@master',
              showCaption: true,
              showIcon: true,
              id: 'u423b10f',
            },
          ],
          appDataEntityId: 'web.master',
          uniqueTag: 'master__A23a502ec6f556cf9b4',
          name: '按钮组',
          id: 'a23a502ec6f556cf9b4',
        },
        groupStyle: 'DEFAULT',
        itemLayoutPanel: {
          layoutMode: 'FLEX',
          layout: {
            layout: 'FLEX',
          },
          rootPanelItems: [
            {
              actionGroupExtractMode: 'ITEM',
              panelItems: [
                {
                  editor: {
                    halign: 'LEFT',
                    renderMode: 'TEXT_DYNAMIC',
                    valign: 'MIDDLE',
                    wrapMode: 'NOWRAP',
                    editorType: 'SPAN',
                    predefinedType: 'FIELD_TEXT_DYNAMIC',
                    valueType: 'SIMPLE',
                    editable: true,
                    id: 'name',
                  },
                  viewFieldName: 'name',
                  allowEmpty: true,
                  caption: '文本(动态)',
                  itemStyle: 'DEFAULT',
                  itemType: 'FIELD',
                  layoutPos: {
                    shrink: 1,
                    layout: 'FLEX',
                  },
                  id: 'name',
                },
              ],
              layout: {
                layout: 'FLEX',
              },
              dataRegionType: 'INHERIT',
              caption: '容器',
              itemStyle: 'DEFAULT',
              itemType: 'CONTAINER',
              layoutPos: {
                shrink: 1,
                layout: 'FLEX',
              },
              id: 'container',
            },
          ],
          layoutPanel: true,
          codeName: 'ab5ca8ad757e0cee868',
          controlType: 'PANEL',
          logicName: 'list_group3列表',
          appDataEntityId: 'web.master',
          controlParam: {},
          modelId: 'e2d42cdef70ea399096d474a800f0f64',
          modelType: 'PSSYSVIEWPANEL',
          name: 'list2_itempanel',
          id: 'web.master.ab5ca8ad757e0cee868',
        },
        delistDataItems: [
          {
            appDEFieldId: 'name',
            dataType: 25,
            id: 'name',
          },
          {
            appDEFieldId: 'id',
            dataType: 25,
            id: 'srfkey',
          },
          {
            appDEFieldId: 'name',
            dataType: 25,
            id: 'srfmajortext',
          },
          {
            appDEFieldId: 'region_id',
            dataType: 25,
            id: 'region_id',
          },
        ],
        pagingSize: 1000,
        enableGroup: true,
        showHeader: true,
        navViewPos: 'NONE',
        createControlAction: {
          appDEMethodId: 'create',
          appDataEntityId: 'web.master',
          id: 'create',
        },
        fetchControlAction: {
          appDEMethodId: 'fetch_default',
          appDataEntityId: 'web.master',
          id: 'fetch',
        },
        getControlAction: {
          appDEMethodId: 'get',
          appDataEntityId: 'web.master',
          id: 'load',
        },
        removeControlAction: {
          appDEMethodId: 'remove',
          appDataEntityId: 'web.master',
          id: 'remove',
        },
        updateControlAction: {
          appDEMethodId: 'update',
          appDataEntityId: 'web.master',
          id: 'update',
        },
        autoLoad: true,
        showBusyIndicator: true,
        codeName: 'list_group3',
        controlType: 'LIST',
        logicName: 'list_group3',
        appDataEntityId: 'web.master',
        controlParam: {
          id: 'list2',
        },
        modelId: '74f335e5831629c3ce47ffb68428c12e',
        modelType: 'PSDELIST',
        name: 'list2',
        id: 'web.master.list_group3',
      },
      {
        groupMode: 'AUTO',
        groupAppDEFieldId: 'quantity',
        groupStyle: 'DEFAULT',
        itemLayoutPanel: {
          layoutMode: 'FLEX',
          layout: {
            layout: 'FLEX',
          },
          rootPanelItems: [
            {
              actionGroupExtractMode: 'ITEM',
              panelItems: [
                {
                  editor: {
                    halign: 'LEFT',
                    renderMode: 'TEXT_DYNAMIC',
                    valign: 'MIDDLE',
                    wrapMode: 'NOWRAP',
                    editorType: 'SPAN',
                    predefinedType: 'FIELD_TEXT_DYNAMIC',
                    valueType: 'SIMPLE',
                    editable: true,
                    id: 'name',
                  },
                  viewFieldName: 'name',
                  allowEmpty: true,
                  caption: '文本(动态)',
                  itemStyle: 'DEFAULT',
                  itemType: 'FIELD',
                  layoutPos: {
                    shrink: 1,
                    layout: 'FLEX',
                  },
                  id: 'name',
                },
              ],
              layout: {
                layout: 'FLEX',
              },
              dataRegionType: 'INHERIT',
              caption: '容器',
              itemStyle: 'DEFAULT',
              itemType: 'CONTAINER',
              layoutPos: {
                shrink: 1,
                layout: 'FLEX',
              },
              id: 'container',
            },
          ],
          layoutPanel: true,
          codeName: 'ac475b8e43eec7f215c',
          controlType: 'PANEL',
          logicName: 'list_group1列表',
          appDataEntityId: 'web.master',
          controlParam: {},
          modelId: '69f5f16b8ed496f6cd04047fa74e34a3',
          modelType: 'PSSYSVIEWPANEL',
          name: 'list_itempanel',
          id: 'web.master.ac475b8e43eec7f215c',
        },
        delistDataItems: [
          {
            appDEFieldId: 'name',
            dataType: 25,
            id: 'name',
          },
          {
            appDEFieldId: 'id',
            dataType: 25,
            id: 'srfkey',
          },
          {
            appDEFieldId: 'name',
            dataType: 25,
            id: 'srfmajortext',
          },
          {
            appDEFieldId: 'region_id',
            dataType: 25,
            id: 'region_id',
          },
        ],
        pagingSize: 1000,
        enableGroup: true,
        showHeader: true,
        navViewPos: 'NONE',
        createControlAction: {
          appDEMethodId: 'create',
          appDataEntityId: 'web.master',
          id: 'create',
        },
        fetchControlAction: {
          appDEMethodId: 'fetch_default',
          appDataEntityId: 'web.master',
          id: 'fetch',
        },
        getControlAction: {
          appDEMethodId: 'get',
          appDataEntityId: 'web.master',
          id: 'load',
        },
        removeControlAction: {
          appDEMethodId: 'remove',
          appDataEntityId: 'web.master',
          id: 'remove',
        },
        updateControlAction: {
          appDEMethodId: 'update',
          appDataEntityId: 'web.master',
          id: 'update',
        },
        autoLoad: true,
        showBusyIndicator: true,
        codeName: 'list_group1',
        controlType: 'LIST',
        logicName: 'list_group1',
        appDataEntityId: 'web.master',
        controlParam: {
          id: 'list',
        },
        modelId: 'c675bb037f74453d59fedcd19a24f6d5',
        modelType: 'PSDELIST',
        name: 'list',
        id: 'web.master.list_group1',
      },
      {
        capLanguageRes: {
          lanResTag: 'DE.LNAME.MASTER',
        },
        caption: '列表_分组',
        codeName: 'list_group_captionbar',
        controlType: 'CAPTIONBAR',
        appDataEntityId: 'web.master',
        controlParam: {},
        name: 'captionbar',
        id: 'list_group_captionbar',
      },
    ],
    codeName: 'usr0516354768',
    controlType: 'VIEWLAYOUTPANEL',
    logicName: '列表_分组布局面板',
    appDataEntityId: 'web.master',
    controlParam: {},
    modelId: '9982e3758c849459d21fbc9e4ae4a31b',
    modelType: 'PSSYSVIEWLAYOUTPANEL',
    name: 'layoutpanel',
    id: 'usr0516354768',
  },
  title: '列表_分组',
  viewStyle: 'DEFAULT',
  viewType: 'DECUSTOMVIEW',
  enableDP: true,
  showCaptionBar: false,
  modelId: 'c4ff698b6ee4a1b93ff693610620a31d',
  modelType: 'PSAPPDEVIEW',
  name: 'MASTERlist_group',
  id: 'web.master_list_group',
};
