export default {
  enableDirtyChecking: true,
  showDataInfoBar: true,
  xdataControlName: 'form',
  loadDefault: true,
  deviewCodeName: 'data_mpicker',
  deviewId: '18b92cb4a3fe749e2dd5fd99655002a8',
  accUserMode: 3,
  capLanguageRes: {
    lanResTag: 'DE.LNAME.MASTER',
  },
  caption: '编辑器_地址框选择',
  codeName: 'master_data_mpicker',
  appDataEntityId: 'web.master',
  appViewEngines: [
    {
      engineCat: 'VIEW',
      engineType: 'EditView',
      id: 'engine',
    },
  ],
  appViewMsgGroupId: 'data_mpicker',
  controls: [
    {
      xdataControlName: 'form',
      codeName: 'data_mpicker_toolbar',
      controlType: 'TOOLBAR',
      logicName: '编辑器_地址框选择_工具栏',
      appDataEntityId: 'web.master',
      controlParam: {
        id: 'toolbar',
      },
      modelId: '6f56c8d7ba7a944060f1008bb0239241',
      modelType: 'PSDETOOLBAR',
      name: 'toolbar',
      id: 'data_mpicker_toolbar',
    },
    {
      createControlAction: {
        appDEMethodId: 'create',
        appDataEntityId: 'web.master',
        id: 'create',
      },
      getDraftFromControlAction: {
        appDataEntityId: 'web.master',
        id: 'loaddraftfrom',
      },
      getDraftControlAction: {
        appDEMethodId: 'get_draft',
        appDataEntityId: 'web.master',
        id: 'loaddraft',
      },
      getControlAction: {
        appDEMethodId: 'get',
        appDataEntityId: 'web.master',
        id: 'load',
      },
      removeControlAction: {
        appDEMethodId: 'remove',
        appDataEntityId: 'web.master',
        id: 'remove',
      },
      updateControlAction: {
        appDEMethodId: 'update',
        appDataEntityId: 'web.master',
        id: 'update',
      },
      deformItemUpdates: [
        {
          codeName: 'fill_value',
          defiupdateDetails: [
            {
              id: 'value',
            },
          ],
          scriptCode:
            'if (data.formitem != null) {\r\n    return {value:data.formitem};\r\n}',
          customCode: true,
          showBusyIndicator: true,
          name: '填充显示选取值',
          id: 'fill_value',
        },
        {
          codeName: 'fill_value1',
          defiupdateDetails: [
            {
              id: 'value1',
            },
          ],
          scriptCode:
            'if (data.formitem1 != null) {\r\n    return {value1:data.formitem1};\r\n}',
          customCode: true,
          showBusyIndicator: true,
          name: '填充显示选取值1',
          id: 'fill_value1',
        },
      ],
      deformPages: [
        {
          layout: {
            columnCount: 24,
            layout: 'TABLE_24COL',
          },
          deformDetails: [
            {
              layout: {
                columnCount: 24,
                layout: 'TABLE_24COL',
              },
              deformDetails: [
                {
                  dataType: 25,
                  enableCond: 3,
                  labelPos: 'LEFT',
                  labelWidth: 130,
                  noPrivDisplayMode: 1,
                  deformItemUpdateId: 'fill_value',
                  editor: {
                    enablePickupView: true,
                    pickupAppViewId: 'web.region_m_pickup_view',
                    appDEACModeId: 'default',
                    appDEDataSetId: 'fetch_default',
                    appDataEntityId: 'web.region',
                    forceSelection: true,
                    showTrigger: true,
                    valueItemName: 'formitem',
                    editorParams: {
                      PICKUPVIEW: 'TRUE',
                    },
                    editorType: 'ADDRESSPICKUP',
                    editorItems: [
                      {
                        id: 'formitem',
                      },
                    ],
                    valueType: 'SIMPLE',
                    editable: true,
                    id: 'formitem',
                  },
                  allowEmpty: true,
                  caption: '地址框选择',
                  codeName: 'formitem',
                  detailStyle: 'DEFAULT',
                  detailType: 'FORMITEM',
                  layoutPos: {
                    colMD: 24,
                    layout: 'TABLE_24COL',
                  },
                  showCaption: true,
                  id: 'formitem',
                },
                {
                  dataType: 25,
                  enableCond: 3,
                  labelPos: 'LEFT',
                  labelWidth: 130,
                  noPrivDisplayMode: 1,
                  editor: {
                    halign: 'LEFT',
                    valign: 'MIDDLE',
                    wrapMode: 'NOWRAP',
                    editorType: 'SPAN',
                    valueType: 'SIMPLE',
                    editable: true,
                    id: 'value',
                  },
                  allowEmpty: true,
                  caption: '选取值',
                  codeName: 'value',
                  detailStyle: 'DEFAULT',
                  detailType: 'FORMITEM',
                  layoutPos: {
                    colMD: 24,
                    layout: 'TABLE_24COL',
                  },
                  showCaption: true,
                  id: 'value',
                },
              ],
              caption: '地址框选择',
              codeName: 'group1',
              detailStyle: 'DEFAULT',
              detailType: 'GROUPPANEL',
              layoutPos: {
                colMD: 24,
                layout: 'TABLE_24COL',
              },
              showCaption: true,
              id: 'group1',
            },
            {
              layout: {
                columnCount: 24,
                layout: 'TABLE_24COL',
              },
              deformDetails: [
                {
                  dataType: 25,
                  enableCond: 3,
                  labelPos: 'LEFT',
                  labelWidth: 130,
                  noPrivDisplayMode: 1,
                  deformItemUpdateId: 'fill_value1',
                  editor: {
                    enablePickupView: true,
                    pickupAppViewId: 'web.region_m_pickup_view',
                    handlerType: 'AC',
                    appDEACModeId: 'default',
                    appDEDataSetId: 'fetch_default',
                    appDataEntityId: 'web.region',
                    forceSelection: true,
                    showTrigger: true,
                    valueItemName: 'formitem',
                    editorParams: {
                      PICKUPVIEW: 'TRUE',
                    },
                    editorType: 'ADDRESSPICKUP_AC',
                    editorItems: [
                      {
                        id: 'formitem',
                      },
                    ],
                    valueType: 'SIMPLE',
                    editable: true,
                    id: 'formitem1',
                  },
                  allowEmpty: true,
                  caption: '地址框（支持选择、AC）',
                  codeName: 'formitem1',
                  detailStyle: 'DEFAULT',
                  detailType: 'FORMITEM',
                  layoutPos: {
                    colMD: 24,
                    layout: 'TABLE_24COL',
                  },
                  showCaption: true,
                  id: 'formitem1',
                },
                {
                  dataType: 25,
                  enableCond: 3,
                  labelPos: 'LEFT',
                  labelWidth: 130,
                  noPrivDisplayMode: 1,
                  editor: {
                    showMaxLength: true,
                    editorType: 'TEXTAREA',
                    valueType: 'SIMPLE',
                    editable: true,
                    id: 'value1',
                  },
                  allowEmpty: true,
                  caption: '选取值',
                  codeName: 'value1',
                  detailStyle: 'DEFAULT',
                  detailType: 'FORMITEM',
                  layoutPos: {
                    colMD: 24,
                    layout: 'TABLE_24COL',
                  },
                  showCaption: true,
                  id: 'value1',
                },
              ],
              caption: '地址框（支持选择、AC）',
              codeName: 'grouppanel1',
              detailStyle: 'DEFAULT',
              detailType: 'GROUPPANEL',
              defdgroupLogics: [
                {
                  logicCat: 'PANELVISIBLE',
                  relatedDetailNames: ['formitem'],
                  groupOP: 'AND',
                  defdlogics: [
                    {
                      condOP: 'EQ',
                      defdname: 'formitem',
                      value: '1',
                      logicType: 'SINGLE',
                      id: 'formitem等于(=) 1',
                    },
                  ],
                  logicType: 'GROUP',
                },
              ],
              layoutPos: {
                colMD: 24,
                layout: 'TABLE_24COL',
              },
              showCaption: true,
              id: 'grouppanel1',
            },
            {
              dataType: 25,
              enableCond: 3,
              labelPos: 'LEFT',
              labelWidth: 130,
              noPrivDisplayMode: 1,
              appDEFieldId: 'id',
              editor: {
                editorType: 'HIDDEN',
                valueType: 'SIMPLE',
                editable: true,
                id: 'id',
              },
              allowEmpty: true,
              hidden: true,
              capLanguageRes: {
                lanResTag: 'DEF.LNAME.MASTER.ID',
              },
              caption: '标识',
              codeName: 'id',
              detailStyle: 'DEFAULT',
              detailType: 'FORMITEM',
              layoutPos: {
                colMD: 24,
                layout: 'TABLE_24COL',
              },
              id: 'id',
            },
          ],
          caption: '地址框选择',
          codeName: 'formpage1',
          detailStyle: 'DEFAULT',
          detailType: 'FORMPAGE',
          id: 'formpage1',
        },
      ],
      layout: {
        columnCount: 24,
        layout: 'TABLE_24COL',
      },
      tabHeaderPos: 'TOP',
      noTabHeader: true,
      autoLoad: true,
      showBusyIndicator: true,
      codeName: 'main48',
      controlType: 'FORM',
      logicName: '编辑器_地址框选择_表单',
      appDataEntityId: 'web.master',
      controlParam: {
        id: 'form',
      },
      modelId: '7a13e9389e32ee0fe529995acfd5b259',
      modelType: 'PSDEFORM_EDITFORM',
      name: 'form',
      id: 'web.master.main48',
    },
    {
      codeName: 'data_mpicker_datainfobar',
      controlType: 'DATAINFOBAR',
      appDataEntityId: 'web.master',
      controlParam: {
        id: 'datainfobar',
      },
      name: 'datainfobar',
      id: 'data_mpicker_datainfobar',
    },
    {
      capLanguageRes: {
        lanResTag: 'DE.LNAME.MASTER',
      },
      caption: '编辑器_地址框选择',
      codeName: 'data_mpicker_captionbar',
      controlType: 'CAPTIONBAR',
      appDataEntityId: 'web.master',
      controlParam: {},
      name: 'captionbar',
      id: 'data_mpicker_captionbar',
    },
  ],
  viewLayoutPanel: {
    layoutBodyOnly: true,
    useDefaultLayout: true,
    layoutPanel: true,
    codeName: 'layoutpanel',
    controlStyle: 'APPDEEDITVIEW',
    controlType: 'VIEWLAYOUTPANEL',
    appDataEntityId: 'web.master',
    controlParam: {},
    id: 'layoutpanel',
  },
  title: '编辑器_地址框选择',
  viewStyle: 'DEFAULT',
  viewType: 'DEEDITVIEW',
  enableDP: true,
  showCaptionBar: false,
  modelId: 'a7f07c6ed491f5a0000e849803ac0318',
  modelType: 'PSAPPDEVIEW',
  name: 'MASTERdata_mpicker',
  id: 'web.master_data_mpicker',
};
