export default {
  deviewCodeName: 'ui_action_parameter',
  deviewId: 'c55eef8f452c4b1ca0156f905102cf59',
  accUserMode: 3,
  capLanguageRes: {
    lanResTag: 'DE.LNAME.MASTER',
  },
  caption: '界面行为_行为参数',
  codeName: 'master_ui_action_parameter',
  appDataEntityId: 'web.master',
  appViewMsgGroupId: 'ui_action_parameter',
  viewLayoutPanel: {
    layoutBodyOnly: true,
    viewProxyMode: true,
    layoutMode: 'FLEX',
    layout: {
      layout: 'FLEX',
    },
    rootPanelItems: [
      {
        actionGroupExtractMode: 'ITEM',
        panelItems: [
          {
            actionGroupExtractMode: 'ITEM',
            panelItems: [
              {
                actionGroupExtractMode: 'ITEM',
                panelItems: [
                  {
                    rawItem: {
                      caption: '搜索：',
                      halign: 'LEFT',
                      renderMode: 'PARAGRAPH',
                      valign: 'MIDDLE',
                      wrapMode: 'NOWRAP',
                      contentType: 'RAW',
                      predefinedType: 'STATIC_LABEL',
                      id: 'static_label',
                    },
                    caption: '标签',
                    itemStyle: 'DEFAULT',
                    itemType: 'RAWITEM',
                    layoutPos: {
                      shrink: 1,
                      layout: 'FLEX',
                    },
                    showCaption: true,
                    id: 'static_label',
                  },
                  {
                    editor: {
                      editorType: 'TEXTBOX',
                      predefinedType: 'FIELD_TEXTBOX',
                      valueType: 'SIMPLE',
                      editable: true,
                      id: 'field_textbox',
                    },
                    viewFieldName: 'wd',
                    allowEmpty: true,
                    caption: '文本框',
                    itemStyle: 'DEFAULT',
                    itemType: 'FIELD',
                    layoutPos: {
                      shrink: 1,
                      layout: 'FLEX',
                    },
                    id: 'field_textbox',
                  },
                ],
                layout: {
                  dir: 'row',
                  layout: 'FLEX',
                  valign: 'center',
                },
                dataRegionType: 'INHERIT',
                caption: '容器',
                itemStyle: 'DEFAULT',
                itemType: 'CONTAINER',
                layoutPos: {
                  shrink: 1,
                  layout: 'FLEX',
                },
                id: 'container1',
              },
              {
                actionType: 'UIACTION',
                buttonStyle: 'DEFAULT',
                buttonType: 'PANELBUTTON',
                uiactionId: 'opan_baidu@master',
                renderMode: 'BUTTON',
                tooltip: '百度一下',
                uiactionTarget: 'SINGLEDATA',
                caption: '百度一下',
                itemStyle: 'DEFAULT',
                itemType: 'BUTTON',
                layoutPos: {
                  shrink: 1,
                  layout: 'FLEX',
                },
                sysImage: {
                  cssClass: 'fa fa-search',
                  glyph: 'xf002@FontAwesome',
                },
                showCaption: true,
                id: 'button_calluilogic',
              },
            ],
            layout: {
              dir: 'row',
              layout: 'FLEX',
              valign: 'center',
            },
            dataRegionType: 'INHERIT',
            caption: '容器',
            itemStyle: 'DEFAULT',
            itemType: 'CONTAINER',
            layoutPos: {
              shrink: 1,
              layout: 'FLEX',
            },
            id: 'container2',
          },
        ],
        layout: {
          layout: 'FLEX',
        },
        dataRegionType: 'INHERIT',
        caption: '容器',
        itemStyle: 'DEFAULT',
        itemType: 'CONTAINER',
        layoutPos: {
          shrink: 1,
          layout: 'FLEX',
          spacingBottom: 'OUTERLARGE',
          spacingLeft: 'OUTERLARGE',
          spacingRight: 'OUTERLARGE',
          spacingTop: 'OUTERLARGE',
        },
        id: 'container',
      },
    ],
    layoutPanel: true,
    controls: [
      {
        capLanguageRes: {
          lanResTag: 'DE.LNAME.MASTER',
        },
        caption: '界面行为_行为参数',
        codeName: 'ui_action_parameter_captionbar',
        controlType: 'CAPTIONBAR',
        appDataEntityId: 'web.master',
        controlParam: {},
        name: 'captionbar',
        id: 'ui_action_parameter_captionbar',
      },
    ],
    codeName: 'acac97fcb92437a46e0',
    controlType: 'VIEWLAYOUTPANEL',
    logicName: 'ui_action_parameter',
    appDataEntityId: 'web.master',
    controlParam: {},
    modelId: '5d9347011c440e771d7207d53fc4be7a',
    modelType: 'PSSYSVIEWLAYOUTPANEL',
    name: 'layoutpanel',
    id: 'acac97fcb92437a46e0',
  },
  title: '界面行为_行为参数',
  viewStyle: 'DEFAULT',
  viewType: 'DECUSTOMVIEW',
  enableDP: true,
  showCaptionBar: true,
  modelId: 'ddcc2e77671d038462a126bdd641a884',
  modelType: 'PSAPPDEVIEW',
  name: 'MASTERui_action_parameter',
  id: 'web.master_ui_action_parameter',
};
