export default {
  deviewCodeName: 'calendar_toolbar',
  deviewId: '83c58ac4a995caea9e3a3753eb74f285',
  accUserMode: 3,
  capLanguageRes: {
    lanResTag: 'DE.LNAME.MASTER',
  },
  caption: '日历_内置工具栏',
  codeName: 'master_calendar_toolbar',
  appDataEntityId: 'web.master',
  appViewMsgGroupId: 'calendar_toolbar',
  viewLayoutPanel: {
    viewProxyMode: true,
    layoutMode: 'FLEX',
    layout: {
      layout: 'FLEX',
    },
    rootPanelItems: [
      {
        actionGroupExtractMode: 'ITEM',
        panelItems: [
          {
            actionGroupExtractMode: 'ITEM',
            panelItems: [
              {
                actionGroupExtractMode: 'ITEM',
                panelItems: [
                  {
                    actionGroupExtractMode: 'ITEM',
                    panelItems: [
                      {
                        caption: '日历',
                        itemStyle: 'DEFAULT',
                        itemType: 'CTRLPOS',
                        layoutPos: {
                          shrink: 1,
                          layout: 'FLEX',
                        },
                        showCaption: true,
                        id: 'calendar',
                      },
                    ],
                    predefinedType: 'CONTAINER_GROUP',
                    layout: {
                      layout: 'FLEX',
                    },
                    dataRegionType: 'INHERIT',
                    caption: '快速操作工具栏',
                    itemStyle: 'DEFAULT',
                    itemType: 'CONTAINER',
                    layoutPos: {
                      shrink: 1,
                      layout: 'FLEX',
                    },
                    showCaption: true,
                    id: 'container_group',
                  },
                  {
                    actionGroupExtractMode: 'ITEM',
                    panelItems: [
                      {
                        actionGroupExtractMode: 'ITEM',
                        panelItems: [
                          {
                            caption: '日历',
                            itemStyle: 'DEFAULT',
                            itemType: 'CTRLPOS',
                            layoutPos: {
                              shrink: 1,
                              layout: 'FLEX',
                            },
                            showCaption: true,
                            id: 'calendar1',
                          },
                        ],
                        layout: {
                          layout: 'FLEX',
                        },
                        dataRegionType: 'INHERIT',
                        caption: '容器',
                        itemStyle: 'DEFAULT',
                        itemType: 'CONTAINER',
                        layoutPos: {
                          shrink: 1,
                          layout: 'FLEX',
                        },
                        id: 'container1',
                      },
                    ],
                    predefinedType: 'CONTAINER_GROUP',
                    layout: {
                      layout: 'FLEX',
                    },
                    dataRegionType: 'INHERIT',
                    caption: '批操作工具栏',
                    itemStyle: 'DEFAULT',
                    itemType: 'CONTAINER',
                    layoutPos: {
                      shrink: 1,
                      layout: 'FLEX',
                    },
                    showCaption: true,
                    id: 'container_group1',
                  },
                ],
                layout: {
                  layout: 'FLEX',
                },
                dataRegionType: 'INHERIT',
                caption: '容器',
                itemStyle: 'DEFAULT',
                itemType: 'CONTAINER',
                layoutPos: {
                  layoutPos: 'CENTER',
                  layout: 'BORDER',
                },
                id: 'container',
              },
            ],
            predefinedType: 'CONTAINER_SCROLL_MAIN',
            layout: {
              layout: 'BORDER',
            },
            dataRegionType: 'INHERIT',
            caption: '面板容器',
            itemStyle: 'DEFAULT',
            itemType: 'CONTAINER',
            layoutPos: {
              layoutPos: 'CENTER',
              layout: 'BORDER',
            },
            showCaption: true,
            id: 'container_scroll_main',
          },
        ],
        predefinedType: 'CONTAINER_SCROLL',
        layout: {
          layout: 'BORDER',
        },
        dataRegionType: 'INHERIT',
        caption: '滚动条容器',
        itemStyle: 'DEFAULT',
        itemType: 'CONTAINER',
        layoutPos: {
          shrink: 1,
          layout: 'FLEX',
        },
        id: 'container_scroll',
      },
    ],
    layoutPanel: true,
    controls: [
      {
        calendarStyle: 'MONTH',
        groupMode: 'NONE',
        legendPos: 'NONE',
        sysCalendarItems: [
          {
            beginTimeAppDEFieldId: 'date',
            endTimeAppDEFieldId: 'date',
            idAppDEFieldId: 'id',
            itemStyle: 'DEFAULT',
            itemType: 'date',
            appDEDataSetId: 'fetch_default',
            textAppDEFieldId: 'name',
            appDataEntityId: 'web.master',
            id: 'date',
          },
        ],
        navViewPos: 'NONE',
        autoLoad: true,
        showBusyIndicator: true,
        controls: [
          {
            detoolbarItems: [
              {
                actionLevel: 100,
                noPrivDisplayMode: 2,
                uiactionId: 'gridview_newaction',
                valid: true,
                capLanguageRes: {
                  lanResTag: 'TBB.TEXT.*.NEW',
                },
                caption: '新建',
                itemType: 'DEUIACTION',
                sysImage: {
                  cssClass: 'fa fa-file-text-o',
                  glyph: 'xf0f6@FontAwesome',
                },
                tooltip: '新建',
                tooltipLanguageRes: {
                  lanResTag: 'TBB.TOOLTIP.*.NEW',
                },
                showCaption: true,
                showIcon: true,
                id: 'deuiaction1',
              },
            ],
            codeName: 'calendar_toolbar_calendar_quicktoolbar',
            controlType: 'TOOLBAR',
            logicName: '快速新建工具栏',
            appDataEntityId: 'web.master',
            controlParam: {
              id: 'calendar_quicktoolbar',
            },
            modelId: '58fc08492a7557e91b37e663b09f7dbb',
            modelType: 'PSDETOOLBAR',
            name: 'calendar_quicktoolbar',
            id: 'calendar_toolbar_calendar_quicktoolbar',
          },
        ],
        codeName: 'calendar_quicktoolbar',
        controlType: 'CALENDAR',
        logicName: '日历_内置工具栏_快速操作工具栏',
        appDataEntityId: 'web.master',
        controlParam: {
          id: 'calendar',
        },
        modelId: '3a094fd3aa1649837665fd5df6944051',
        modelType: 'PSSYSCALENDAR',
        name: 'calendar',
        id: 'web.master.calendar_quicktoolbar',
      },
      {
        calendarStyle: 'MONTH',
        groupMode: 'NONE',
        legendPos: 'NONE',
        sysCalendarItems: [
          {
            beginTimeAppDEFieldId: 'date',
            endTimeAppDEFieldId: 'date',
            idAppDEFieldId: 'id',
            itemStyle: 'DEFAULT',
            itemType: 'date',
            appDEDataSetId: 'fetch_default',
            textAppDEFieldId: 'name',
            appDataEntityId: 'web.master',
            id: 'date',
          },
        ],
        navViewPos: 'NONE',
        autoLoad: true,
        showBusyIndicator: true,
        controls: [
          {
            detoolbarItems: [
              {
                actionLevel: 100,
                noPrivDisplayMode: 2,
                uiactionId: 'open_dialog@master',
                uiactionTarget: 'NONE',
                valid: true,
                caption: '打开弹窗',
                itemType: 'DEUIACTION',
                tooltip: '打开弹窗',
                showCaption: true,
                showIcon: true,
                id: 'deuiaction1',
              },
            ],
            codeName: 'calendar_toolbar_calendar1_batchtoolbar',
            controlType: 'TOOLBAR',
            logicName: '批操作工具栏',
            appDataEntityId: 'web.master',
            controlParam: {
              id: 'calendar1_batchtoolbar',
            },
            modelId: 'a27c6354e5a33f02d8a71c96263bc017',
            modelType: 'PSDETOOLBAR',
            name: 'calendar1_batchtoolbar',
            id: 'calendar_toolbar_calendar1_batchtoolbar',
          },
        ],
        codeName: 'calendar_batch_toolbar',
        controlType: 'CALENDAR',
        logicName: '日历_内置工具栏_批操作工具栏',
        appDataEntityId: 'web.master',
        controlParam: {
          id: 'calendar1',
        },
        modelId: '633d282adf50f46c716fe6d67309986d',
        modelType: 'PSSYSCALENDAR',
        name: 'calendar1',
        id: 'web.master.calendar_batch_toolbar',
      },
      {
        capLanguageRes: {
          lanResTag: 'DE.LNAME.MASTER',
        },
        caption: '日历_内置工具栏',
        codeName: 'calendar_toolbar_captionbar',
        controlType: 'CAPTIONBAR',
        appDataEntityId: 'web.master',
        controlParam: {},
        name: 'captionbar',
        id: 'calendar_toolbar_captionbar',
      },
    ],
    codeName: 'usr0515617984',
    controlType: 'VIEWLAYOUTPANEL',
    logicName: '日历_内置工具栏布局面板',
    appDataEntityId: 'web.master',
    controlParam: {},
    modelId: '0ef7e87fbe203b97fb61c15bdb04b6d4',
    modelType: 'PSSYSVIEWLAYOUTPANEL',
    name: 'layoutpanel',
    id: 'usr0515617984',
  },
  title: '日历_内置工具栏',
  viewStyle: 'DEFAULT',
  viewType: 'DECUSTOMVIEW',
  enableDP: true,
  showCaptionBar: false,
  modelId: 'fb9b2eaecbcd2e2453014331b4f06c0f',
  modelType: 'PSAPPDEVIEW',
  name: 'MASTERcalendar_toolbar',
  id: 'web.master_calendar_toolbar',
};
