export default {
  mdctrlActiveMode: 2,
  xdataControlName: 'kanban',
  loadDefault: true,
  deviewCodeName: 'kanban_style',
  deviewId: 'fdddb063b4669b26d6170a59f0e475bb',
  accUserMode: 3,
  capLanguageRes: {
    lanResTag: 'DE.LNAME.MASTER',
  },
  caption: '看板_样式',
  codeName: 'master_kanban_style',
  appDataEntityId: 'web.master',
  appViewMsgGroupId: 'kanban_style',
  viewLayoutPanel: {
    viewProxyMode: true,
    layoutMode: 'FLEX',
    layout: {
      layout: 'FLEX',
    },
    rootPanelItems: [
      {
        actionGroupExtractMode: 'ITEM',
        panelItems: [
          {
            actionGroupExtractMode: 'ITEM',
            panelItems: [
              {
                actionGroupExtractMode: 'ITEM',
                panelItems: [
                  {
                    caption: '页面标题',
                    itemStyle: 'DEFAULT',
                    itemType: 'CTRLPOS',
                    layoutPos: {
                      shrink: 1,
                      layout: 'FLEX',
                    },
                    showCaption: true,
                    id: 'captionbar',
                  },
                ],
                layout: {
                  align: 'center',
                  layout: 'FLEX',
                },
                dataRegionType: 'INHERIT',
                caption: '容器',
                itemStyle: 'DEFAULT',
                itemType: 'CONTAINER',
                layoutPos: {
                  shrink: 1,
                  heightMode: 'FULL',
                  layout: 'FLEX',
                },
                id: 'view_captionbar',
              },
            ],
            layout: {
              layout: 'FLEX',
            },
            dataRegionType: 'INHERIT',
            caption: '容器',
            itemStyle: 'DEFAULT',
            itemType: 'CONTAINER',
            layoutPos: {
              shrink: 1,
              heightMode: 'FULL',
              layout: 'FLEX',
            },
            id: 'view_header_left',
          },
          {
            actionGroupExtractMode: 'ITEM',
            panelItems: [
              {
                actionGroupExtractMode: 'ITEM',
                panelItems: [
                  {
                    caption: '工具栏',
                    itemStyle: 'DEFAULT',
                    itemType: 'CTRLPOS',
                    layoutPos: {
                      shrink: 1,
                      layout: 'FLEX',
                    },
                    showCaption: true,
                    id: 'toolbar',
                  },
                ],
                layout: {
                  align: 'center',
                  layout: 'FLEX',
                },
                dataRegionType: 'INHERIT',
                caption: '容器',
                itemStyle: 'DEFAULT',
                itemType: 'CONTAINER',
                layoutPos: {
                  shrink: 1,
                  heightMode: 'FULL',
                  layout: 'FLEX',
                },
                id: 'view_toolbar',
              },
            ],
            layout: {
              layout: 'FLEX',
            },
            dataRegionType: 'INHERIT',
            caption: '容器',
            itemStyle: 'DEFAULT',
            itemType: 'CONTAINER',
            layoutPos: {
              shrink: 1,
              heightMode: 'FULL',
              layout: 'FLEX',
            },
            id: 'view_header_right',
          },
        ],
        predefinedType: 'VIEWHEADER',
        layout: {
          align: 'space-between',
          dir: 'row',
          layout: 'FLEX',
          valign: 'center',
        },
        dataRegionType: 'INHERIT',
        caption: '容器',
        itemStyle: 'DEFAULT',
        itemType: 'CONTAINER',
        layoutPos: {
          shrink: 0,
          layout: 'FLEX',
        },
        id: 'view_header',
      },
      {
        actionGroupExtractMode: 'ITEM',
        panelItems: [
          {
            caption: '搜索表单',
            itemStyle: 'DEFAULT',
            itemType: 'CTRLPOS',
            layoutPos: {
              shrink: 1,
              layout: 'FLEX',
            },
            showCaption: true,
            id: 'searchform',
          },
        ],
        layout: {
          dir: 'column',
          layout: 'FLEX',
        },
        dataRegionType: 'INHERIT',
        itemStyle: 'DEFAULT',
        itemType: 'CONTAINER',
        layoutPos: {
          shrink: 0,
          layout: 'FLEX',
        },
        id: 'view_searchform',
      },
      {
        actionGroupExtractMode: 'ITEM',
        panelItems: [
          {
            caption: '看板部件',
            itemStyle: 'DEFAULT',
            itemType: 'CTRLPOS',
            layoutPos: {
              shrink: 1,
              layout: 'FLEX',
            },
            showCaption: true,
            id: 'dashboard',
          },
        ],
        predefinedType: 'VIEWCONTENT',
        layout: {
          layout: 'FLEX',
        },
        dataRegionType: 'INHERIT',
        caption: '容器',
        itemStyle: 'DEFAULT',
        itemType: 'CONTAINER',
        layoutPos: {
          grow: 1,
          shrink: 1,
          layout: 'FLEX',
        },
        id: 'view_kanban',
      },
    ],
    layoutPanel: true,
    appViewEngines: [
      {
        engineCat: 'VIEW',
        engineType: 'KanBanView',
        id: 'engine',
      },
    ],
    appViewLogics: [
      {
        logicTrigger: 'CUSTOM',
        logicType: 'APPUILOGIC',
        builtinAppUILogic: {
          actionAfterWizard: 'DEFAULT',
          newDataAppView: {
            openMode: 'POPUPMODAL',
            refAppViewId: 'web.master_edit_view',
          },
          appUILogicRefViews: [
            {
              openMode: 'POPUPMODAL',
              refAppViewId: 'web.master_edit_view',
            },
          ],
          builtinLogic: true,
          logicType: 'PREDEFINED',
          viewLogicType: 'APP_NEWDATA',
          id: '新建数据',
        },
        builtinLogic: true,
        id: 'newdata',
      },
      {
        logicTrigger: 'CUSTOM',
        logicType: 'APPUILOGIC',
        builtinAppUILogic: {
          openDataAppView: {
            openMode: 'POPUPMODAL',
            refAppViewId: 'web.master_edit_view',
          },
          editMode: true,
          appUILogicRefViews: [
            {
              openMode: 'POPUPMODAL',
              refAppViewId: 'web.master_edit_view',
            },
          ],
          builtinLogic: true,
          logicType: 'PREDEFINED',
          viewLogicType: 'APP_OPENDATA',
          id: '打开数据',
        },
        builtinLogic: true,
        id: 'opendata',
      },
    ],
    appViewRefs: [
      {
        realOpenMode: 'POPUPMODAL',
        realTitle: '主数据编辑视图',
        refAppViewId: 'web.master_edit_view',
        name: 'NEWDATA',
        id: 'newdata',
      },
      {
        realOpenMode: 'POPUPMODAL',
        realTitle: '主数据编辑视图',
        refAppViewId: 'web.master_edit_view',
        name: 'EDITDATA',
        id: 'editdata',
      },
    ],
    controls: [
      {
        xdataControlName: 'kanban',
        codeName: 'kanban_style_toolbar',
        controlType: 'TOOLBAR',
        logicName: '看板_样式_工具栏',
        appDataEntityId: 'web.master',
        controlParam: {
          id: 'toolbar',
        },
        modelId: '51051b0068455657972e82507dd6e5d9',
        modelType: 'PSDETOOLBAR',
        name: 'toolbar',
        id: 'kanban_style_toolbar',
      },
      {
        searchButtonStyle: 'DEFAULT',
        deformPages: [
          {
            layout: {
              columnCount: 24,
              layout: 'TABLE_24COL',
            },
            caption: '常规条件',
            codeName: 'formpage1',
            detailStyle: 'DEFAULT',
            detailType: 'FORMPAGE',
            id: 'formpage1',
          },
        ],
        layout: {
          columnCount: 24,
          layout: 'TABLE_24COL',
        },
        tabHeaderPos: 'TOP',
        noTabHeader: true,
        autoLoad: true,
        showBusyIndicator: true,
        codeName: 'kanban_style_search_form',
        controlType: 'SEARCHFORM',
        logicName: '看板_样式_搜索表单',
        appDataEntityId: 'web.master',
        controlParam: {
          id: 'searchform',
        },
        modelId: '721378098c3730c1f81a43f0cd6f3d3f',
        modelType: 'PSDEFORM_SEARCHFORM',
        name: 'searchform',
        id: 'web.master.kanban_style_search_form',
      },
      {
        updateGroupControlAction: {
          appDEMethodId: 'update',
          appDataEntityId: 'web.master',
          id: 'updategroup',
        },
        groupMode: 'NONE',
        groupStyle: 'DEFAULT',
        itemLayoutPanel: {
          layoutMode: 'TABLE_24COL',
          layout: {
            columnCount: 24,
            layout: 'TABLE_24COL',
          },
          rootPanelItems: [
            {
              actionGroupExtractMode: 'ITEM',
              layout: {
                dir: 'column',
                layout: 'FLEX',
              },
              dataRegionType: 'INHERIT',
              itemStyle: 'DEFAULT',
              itemType: 'CONTAINER',
              layoutPos: {
                colMD: 24,
                layout: 'TABLE_24COL',
              },
              id: 'page_container',
            },
          ],
          codeName: 'usr0516775541',
          controlType: 'PANEL',
          logicName: '看板_样式_看板_卡片面板',
          appDataEntityId: 'web.master',
          controlParam: {},
          modelId: '028924c318d8309491b92de22c177c6c',
          modelType: 'PSSYSVIEWPANEL',
          name: 'itemlayoutpanel',
          id: 'web.master.usr0516775541',
        },
        dedataViewDataItems: [
          {
            appDEFieldId: 'id',
            dataType: 25,
            id: 'srfkey',
          },
          {
            appDEFieldId: 'name',
            dataType: 25,
            id: 'srfmajortext',
          },
          {
            appDEFieldId: 'region_id',
            dataType: 25,
            id: 'region_id',
          },
        ],
        pagingSize: 1000,
        appendDEItems: true,
        navViewPos: 'NONE',
        createControlAction: {
          appDEMethodId: 'create',
          appDataEntityId: 'web.master',
          id: 'create',
        },
        fetchControlAction: {
          appDEMethodId: 'fetch_default',
          appDataEntityId: 'web.master',
          id: 'fetch',
        },
        getControlAction: {
          appDEMethodId: 'get',
          appDataEntityId: 'web.master',
          id: 'load',
        },
        removeControlAction: {
          appDEMethodId: 'remove',
          appDataEntityId: 'web.master',
          id: 'remove',
        },
        updateControlAction: {
          appDEMethodId: 'update',
          appDataEntityId: 'web.master',
          id: 'update',
        },
        autoLoad: true,
        showBusyIndicator: true,
        codeName: 'kanban_style_kan_ban',
        controlType: 'KANBAN',
        logicName: '看板_样式_看板',
        appDataEntityId: 'web.master',
        controlParam: {
          id: 'kanban',
        },
        modelId: '98be79d7111e69f96cd985a1852f5248',
        modelType: 'PSDEKANBAN',
        name: 'kanban',
        id: 'web.master.kanban_style_kan_ban',
      },
      {
        layout: {
          columnCount: 24,
          layout: 'TABLE_24COL',
        },
        autoLoad: true,
        showBusyIndicator: true,
        controls: [
          {
            contentControlId: 'dashboard_sysportlet1_chart',
            layoutPos: {
              colMD: 24,
              height: 400,
              heightMode: 'PX',
              layout: 'TABLE_24COL',
            },
            sysImage: {
              cssClass: 'fa fa-rebel',
              glyph: 'xf1d0@FontAwesome',
            },
            portletType: 'CHART',
            title: '看板标题图标',
            showTitleBar: true,
            autoLoad: true,
            showBusyIndicator: true,
            controls: [
              {
                coordinateSystem: 'XY',
                chartCoordinateSystems: [
                  {
                    chartGrid: {
                      chartGridXAxis0Id: '0',
                      chartGridYAxis0Id: '0',
                      chartCoordinateSystemId: '0',
                      type: 'grid',
                      name: '[bar_0]直角坐标系[0]',
                      id: '0',
                    },
                    echartsType: 'cartesian2d',
                    type: 'XY',
                    name: '[bar_0]直角坐标系[0]',
                    id: '0',
                  },
                ],
                dechartDataGrid: {
                  id: '0',
                },
                dechartLegend: {
                  id: '0',
                },
                dechartSerieses: [
                  {
                    catalogField: 'NAME',
                    echartsType: 'bar',
                    chartCoordinateSystemId: '0',
                    chartDataSetId: '0',
                    chartSeriesEncode: {
                      chartXAxisId: '0',
                      chartYAxisId: '0',
                      x: ['NAME'],
                      y: ['PX'],
                      type: 'XY',
                      name: '坐标系编码',
                      id: '0',
                    },
                    seriesLayoutBy: 'column',
                    seriesType: 'bar',
                    valueField: 'PX',
                    enableChartDataSet: true,
                    navAppViewId: 'web.master_grid_view_read',
                    navigateParams: [
                      {
                        key: 'n_name_eq',
                        value: 'name',
                        id: 'n_name_eq',
                      },
                    ],
                    id: 'bar_0',
                  },
                ],
                dechartTitle: {
                  title: '图表视图_图表',
                  id: '0',
                },
                chartDataSetGroups: [
                  {
                    appDEDataSetId: 'fetch_default',
                    appDataEntityId: 'web.master',
                    name: 'DEFAULT',
                    id: '0',
                  },
                ],
                chartDataSets: [
                  {
                    chartDataSetFields: [
                      {
                        groupField: true,
                        name: 'NAME',
                        id: '0',
                      },
                      {
                        index: 1,
                        name: 'PX',
                        id: '1',
                      },
                    ],
                    name: 'bar_0-DEFAULT',
                    id: '0',
                  },
                ],
                chartGrids: [
                  {
                    chartGridXAxis0Id: '0',
                    chartGridYAxis0Id: '0',
                    chartCoordinateSystemId: '0',
                    type: 'grid',
                    name: '[bar_0]直角坐标系[0]',
                    id: '0',
                  },
                ],
                chartXAxises: [
                  {
                    caption: '名称',
                    echartsPos: 'xAxis',
                    echartsType: 'category',
                    position: 'bottom',
                    type: 'category',
                    name: 'axis_xAxis_0',
                    id: '0',
                  },
                ],
                chartYAxises: [
                  {
                    caption: '排序',
                    echartsPos: 'yAxis',
                    echartsType: 'value',
                    position: 'left',
                    type: 'numeric',
                    name: 'axis_yAxis_0',
                    id: '0',
                  },
                ],
                navViewPos: 'NONE',
                fetchControlAction: {
                  appDEMethodId: 'fetch_default',
                  appDataEntityId: 'web.master',
                  id: 'fetch',
                },
                readOnly: true,
                autoLoad: true,
                showBusyIndicator: true,
                codeName: 'chart_view_chart',
                controlType: 'CHART',
                height: 300,
                logicName: 'Chart',
                appDataEntityId: 'web.master',
                controlParam: {},
                modelId: '3774628b5cc0b4121a1682558a946e55',
                modelType: 'PSDECHART',
                userParam: {
                  'EC.color':
                    '["#5470c6","#91cc75","#fac858","#ee6666","#73c0de","#3ba272","#fc8452","#9a60b4","#ea7ccc","#5470c6","#91cc75"]',
                },
                name: 'dashboard_sysportlet1_chart',
                id: 'web.master.chart_view_chart',
              },
            ],
            codeName: 'chart',
            controlType: 'PORTLET',
            height: 400,
            appDataEntityId: 'web.master',
            controlParam: {},
            modelId: 'a4d85ae666b9a5378583de4555cea904',
            modelType: 'PSSYSDBPART',
            name: 'dashboard_sysportlet1',
            id: 'chart',
          },
          {
            contentControlId: 'dashboard_sysportlet2_list',
            layoutPos: {
              colMD: 24,
              height: 400,
              heightMode: 'PX',
              layout: 'TABLE_24COL',
            },
            portletType: 'LIST',
            title: '门户部件_列表',
            showTitleBar: true,
            autoLoad: true,
            showBusyIndicator: true,
            controls: [
              {
                groupMode: 'NONE',
                groupStyle: 'DEFAULT',
                itemLayoutPanel: {
                  layoutMode: 'FLEX',
                  layout: {
                    layout: 'FLEX',
                  },
                  rootPanelItems: [
                    {
                      actionGroupExtractMode: 'ITEM',
                      panelItems: [
                        {
                          actionGroupExtractMode: 'ITEM',
                          panelItems: [
                            {
                              rawItem: {
                                sysImage: {
                                  rawContent:
                                    '<svg id="图层_2" data-name="图层 2" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 45.05908 45.05914"><defs><style>.cls-1{fill:#01b0ff;}</style></defs><title>ibizlab. 2</title><path class="cls-1" d="M1.64777,456.35452v45.05914H46.70685V456.35452Zm39.92407,3.86188-9.51965,19.60479L11.59913,460.1221ZM4.35572,497.13931v-34.424c8.37353,26.80664,17.53088,34.424,17.53088,34.424ZM17.424,472.06509l12.64337,12.21838-5.52484,9.77466S16.25531,478.54611,17.424,472.06509Zm9.031,25.07422,6.58728-9.031,7.64978,9.031Zm16.71912-2.99152-7.54029-9.61389,7.63453-13.10132Z" transform="translate(-1.64777 -456.35452)"/></svg>',
                                },
                                contentType: 'IMAGE',
                                predefinedType: 'STATIC_IMAGE',
                                rawItemHeight: 32,
                                rawItemWidth: 32,
                                id: 'static_image',
                              },
                              caption: '图片',
                              contentHeight: 32,
                              contentWidth: 32,
                              height: 32,
                              itemStyle: 'DEFAULT',
                              itemType: 'RAWITEM',
                              layoutPos: {
                                shrink: 1,
                                height: 32,
                                heightMode: 'PX',
                                layout: 'FLEX',
                                width: 32,
                                widthMode: 'PX',
                              },
                              sysImage: {
                                rawContent:
                                  '<svg id="图层_2" data-name="图层 2" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 45.05908 45.05914"><defs><style>.cls-1{fill:#01b0ff;}</style></defs><title>ibizlab. 2</title><path class="cls-1" d="M1.64777,456.35452v45.05914H46.70685V456.35452Zm39.92407,3.86188-9.51965,19.60479L11.59913,460.1221ZM4.35572,497.13931v-34.424c8.37353,26.80664,17.53088,34.424,17.53088,34.424ZM17.424,472.06509l12.64337,12.21838-5.52484,9.77466S16.25531,478.54611,17.424,472.06509Zm9.031,25.07422,6.58728-9.031,7.64978,9.031Zm16.71912-2.99152-7.54029-9.61389,7.63453-13.10132Z" transform="translate(-1.64777 -456.35452)"/></svg>',
                              },
                              width: 32,
                              showCaption: true,
                              id: 'static_image',
                            },
                            {
                              actionGroupExtractMode: 'ITEM',
                              panelItems: [
                                {
                                  editor: {
                                    halign: 'LEFT',
                                    renderMode: 'TEXT_DYNAMIC',
                                    valign: 'MIDDLE',
                                    wrapMode: 'NOWRAP',
                                    editorType: 'SPAN',
                                    predefinedType: 'FIELD_TEXT_DYNAMIC',
                                    valueType: 'SIMPLE',
                                    editable: true,
                                    id: 'name',
                                  },
                                  valueFormat: '名称：@',
                                  viewFieldName: 'name',
                                  allowEmpty: true,
                                  caption: '文本(动态)',
                                  itemStyle: 'DEFAULT',
                                  itemType: 'FIELD',
                                  layoutPos: {
                                    shrink: 1,
                                    layout: 'FLEX',
                                  },
                                  id: 'name',
                                },
                                {
                                  editor: {
                                    halign: 'LEFT',
                                    renderMode: 'TEXT_DYNAMIC',
                                    valign: 'MIDDLE',
                                    wrapMode: 'NOWRAP',
                                    editorType: 'SPAN',
                                    predefinedType: 'FIELD_TEXT_DYNAMIC',
                                    valueType: 'SIMPLE',
                                    editable: true,
                                    id: 'quantity',
                                  },
                                  valueFormat: '数量：#,###',
                                  viewFieldName: 'quantity',
                                  allowEmpty: true,
                                  caption: '文本(动态)',
                                  itemStyle: 'DEFAULT',
                                  itemType: 'FIELD',
                                  layoutPos: {
                                    shrink: 1,
                                    layout: 'FLEX',
                                  },
                                  id: 'quantity',
                                },
                              ],
                              layout: {
                                align: 'center',
                                dir: 'column',
                                layout: 'FLEX',
                              },
                              dataRegionType: 'INHERIT',
                              caption: '容器',
                              itemStyle: 'DEFAULT',
                              itemType: 'CONTAINER',
                              layoutPos: {
                                shrink: 1,
                                layout: 'FLEX',
                                spacingLeft: 'OUTERMEDIUM',
                              },
                              id: 'container3',
                            },
                          ],
                          layout: {
                            align: 'center',
                            dir: 'row',
                            layout: 'FLEX',
                            valign: 'center',
                          },
                          dataRegionType: 'INHERIT',
                          caption: '容器',
                          itemStyle: 'DEFAULT',
                          itemType: 'CONTAINER',
                          layoutPos: {
                            shrink: 1,
                            layout: 'FLEX',
                          },
                          id: 'container',
                        },
                        {
                          editor: {
                            halign: 'LEFT',
                            renderMode: 'TEXT_DYNAMIC',
                            valign: 'MIDDLE',
                            wrapMode: 'NOWRAP',
                            editorType: 'SPAN',
                            predefinedType: 'FIELD_TEXT_DYNAMIC',
                            valueType: 'SIMPLE',
                            editable: true,
                            id: 'description',
                          },
                          viewFieldName: 'description',
                          allowEmpty: true,
                          caption: '文本(动态)',
                          itemStyle: 'DEFAULT',
                          itemType: 'FIELD',
                          layoutPos: {
                            shrink: 1,
                            layout: 'FLEX',
                          },
                          id: 'description',
                        },
                        {
                          actionGroupExtractMode: 'ITEM',
                          panelItems: [
                            {
                              editor: {
                                halign: 'LEFT',
                                renderMode: 'TEXT_DYNAMIC',
                                valign: 'MIDDLE',
                                wrapMode: 'NOWRAP',
                                appCodeListId: 'web.mock__cl_status',
                                editorType: 'SPAN',
                                predefinedType: 'FIELD_TEXT_DYNAMIC',
                                valueType: 'SIMPLE',
                                editable: true,
                                id: 'status',
                              },
                              viewFieldName: 'status',
                              allowEmpty: true,
                              convertToCodeItemText: true,
                              caption: '文本(动态)',
                              itemStyle: 'DEFAULT',
                              itemType: 'FIELD',
                              layoutPos: {
                                shrink: 1,
                                layout: 'FLEX',
                              },
                              id: 'status',
                            },
                          ],
                          layout: {
                            layout: 'FLEX',
                          },
                          dataRegionType: 'INHERIT',
                          caption: '容器',
                          itemStyle: 'DEFAULT',
                          itemType: 'CONTAINER',
                          layoutPos: {
                            shrink: 1,
                            layout: 'FLEX',
                          },
                          id: 'container2',
                        },
                      ],
                      layout: {
                        align: 'space-between',
                        dir: 'row',
                        layout: 'FLEX',
                        valign: 'center',
                      },
                      dataRegionType: 'INHERIT',
                      itemStyle: 'DEFAULT',
                      itemType: 'CONTAINER',
                      layoutPos: {
                        shrink: 1,
                        layout: 'FLEX',
                      },
                      id: 'container1',
                    },
                  ],
                  layoutPanel: true,
                  codeName: 'a45733c8151766b36e7',
                  controlType: 'PANEL',
                  logicName: 'list_base列表',
                  appDataEntityId: 'web.master',
                  controlParam: {},
                  modelId: '0e083f0ce9582c64bb69ba0f90f57a57',
                  modelType: 'PSSYSVIEWPANEL',
                  name: 'dashboard_sysportlet2_list_itempanel',
                  id: 'web.master.a45733c8151766b36e7',
                },
                delistDataItems: [
                  {
                    appDEFieldId: 'id',
                    dataType: 25,
                    id: 'srfkey',
                  },
                  {
                    appDEFieldId: 'name',
                    dataType: 25,
                    id: 'srfmajortext',
                  },
                  {
                    appDEFieldId: 'region_id',
                    dataType: 25,
                    id: 'region_id',
                  },
                ],
                pagingSize: 1000,
                showHeader: true,
                navViewPos: 'NONE',
                createControlAction: {
                  appDEMethodId: 'create',
                  appDataEntityId: 'web.master',
                  id: 'create',
                },
                fetchControlAction: {
                  appDEMethodId: 'fetch_default',
                  appDataEntityId: 'web.master',
                  id: 'fetch',
                },
                getControlAction: {
                  appDEMethodId: 'get',
                  appDataEntityId: 'web.master',
                  id: 'load',
                },
                removeControlAction: {
                  appDEMethodId: 'remove',
                  appDataEntityId: 'web.master',
                  id: 'remove',
                },
                updateControlAction: {
                  appDEMethodId: 'update',
                  appDataEntityId: 'web.master',
                  id: 'update',
                },
                autoLoad: true,
                showBusyIndicator: true,
                codeName: 'list_base',
                controlType: 'LIST',
                height: 300,
                logicName: 'list_base',
                appDataEntityId: 'web.master',
                controlParam: {},
                modelId: 'aeb64f8ec9b775be90a929a12ff30351',
                modelType: 'PSDELIST',
                name: 'dashboard_sysportlet2_list',
                id: 'web.master.list_base',
              },
            ],
            codeName: 'list',
            controlType: 'PORTLET',
            height: 400,
            appDataEntityId: 'web.master',
            controlParam: {},
            modelId: 'f4de28dd7a4ea2d147326a5e52d68796',
            modelType: 'PSSYSDBPART',
            name: 'dashboard_sysportlet2',
            id: 'list',
          },
        ],
        codeName: 'dashboard6',
        controlType: 'DASHBOARD',
        logicName: '数据看板_样式',
        appDataEntityId: 'web.master',
        controlParam: {
          id: 'dashboard',
        },
        modelId: '3ae7c5d4a678c9a72a09933b42933867',
        modelType: 'PSSYSDASHBOARD',
        name: 'dashboard',
        id: 'web.master.dashboard6',
      },
      {
        groupMode: 'SINGLE',
        quickSearchMode: 1,
        enableQuickSearch: true,
        controlType: 'SEARCHBAR',
        appDataEntityId: 'web.master',
        controlParam: {
          id: 'searchbar',
        },
        id: 'searchbar',
      },
      {
        capLanguageRes: {
          lanResTag: 'DE.LNAME.MASTER',
        },
        caption: '看板_样式',
        codeName: 'kanban_style_captionbar',
        controlType: 'CAPTIONBAR',
        appDataEntityId: 'web.master',
        controlParam: {},
        name: 'captionbar',
        id: 'kanban_style_captionbar',
      },
    ],
    codeName: 'usr0516676736',
    controlType: 'VIEWLAYOUTPANEL',
    logicName: 'kanban_style实体看板视图布局面板',
    appDataEntityId: 'web.master',
    controlParam: {},
    modelId: 'f78679a61c793dadf948ee87b0769c3e',
    modelType: 'PSSYSVIEWLAYOUTPANEL',
    name: 'layoutpanel',
    id: 'usr0516676736',
  },
  title: '看板_样式',
  viewStyle: 'DEFAULT',
  viewType: 'DEKANBANVIEW',
  enableDP: true,
  showCaptionBar: false,
  modelId: '3ae7c5d4a678c9a72a09933b42933867',
  modelType: 'PSAPPDEVIEW',
  name: 'MASTERkanban_style',
  id: 'web.master_kanban_style',
};
