export default {
  tabLayout: 'FLOW',
  loadDefault: true,
  showDataInfoBar: true,
  deviewCodeName: 'searchbar',
  deviewId: '2de2f3b34b0328ff50f0bd0c2c69aaa5',
  accUserMode: 3,
  capLanguageRes: {
    lanResTag: 'DE.LNAME.MASTER',
  },
  caption: '搜索栏',
  codeName: 'master_searchbar',
  appDataEntityId: 'web.master',
  appViewEngines: [
    {
      engineCat: 'VIEW',
      engineType: 'TabExpView',
      id: 'engine',
    },
  ],
  appViewMsgGroupId: 'searchbar',
  controls: [
    {
      dedrtabPages: [
        {
          caption: '基础',
          appViewId: 'web.master_searchbar_base',
          id: 'base',
        },
      ],
      dataRelationTag: 'searchbar_DR',
      editItemCapLanguageRes: {
        lanResTag: 'DE.LNAME.MASTER',
      },
      editItemCaption: '主数据',
      uniqueTag: 'master_searchbar__tabexppanel',
      autoLoad: true,
      showBusyIndicator: true,
      codeName: 'searchbar_dr',
      controlType: 'DRTAB',
      appDataEntityId: 'web.master',
      controlParam: {
        id: 'tabexppanel',
      },
      modelId: 'bfe8448e06842343f30bbc4759957b89',
      modelType: 'PSDEDRTAB',
      name: 'tabexppanel',
      id: 'searchbar_dr',
    },
    {
      capLanguageRes: {
        lanResTag: 'DE.LNAME.MASTER',
      },
      caption: '搜索栏',
      codeName: 'searchbar_captionbar',
      controlType: 'CAPTIONBAR',
      appDataEntityId: 'web.master',
      controlParam: {},
      name: 'captionbar',
      id: 'searchbar_captionbar',
    },
  ],
  viewLayoutPanel: {
    layoutBodyOnly: true,
    useDefaultLayout: true,
    layoutPanel: true,
    codeName: 'layoutpanel',
    controlStyle: 'APPDETABEXPVIEW',
    controlType: 'VIEWLAYOUTPANEL',
    appDataEntityId: 'web.master',
    controlParam: {},
    id: 'layoutpanel',
  },
  title: '搜索栏',
  viewStyle: 'DEFAULT',
  viewType: 'DETABEXPVIEW',
  enableDP: true,
  showCaptionBar: false,
  modelId: '30d6ef39c43e96138400492bcb416bef',
  modelType: 'PSAPPDEVIEW',
  name: 'MASTERsearchbar',
  id: 'web.master_searchbar',
};
