export default {
  deviewCodeName: 'searchform_btncss',
  deviewId: 'ca90a4ced36603d2bb086982b8cdb332',
  accUserMode: 3,
  capLanguageRes: {
    lanResTag: 'DE.LNAME.MASTER',
  },
  caption: '搜索表单_按钮样式',
  codeName: 'master_searchform_btncss',
  appDataEntityId: 'web.master',
  appViewMsgGroupId: 'searchform_btncss',
  viewLayoutPanel: {
    layoutBodyOnly: true,
    viewProxyMode: true,
    layoutMode: 'FLEX',
    layout: {
      layout: 'FLEX',
    },
    rootPanelItems: [
      {
        actionGroupExtractMode: 'ITEM',
        panelItems: [
          {
            actionGroupExtractMode: 'ITEM',
            panelItems: [
              {
                actionGroupExtractMode: 'ITEM',
                panelItems: [
                  {
                    caption: '搜索表单',
                    itemStyle: 'DEFAULT',
                    itemType: 'CTRLPOS',
                    layoutPos: {
                      shrink: 1,
                      layout: 'FLEX',
                    },
                    showCaption: true,
                    id: 'searchform',
                  },
                ],
                predefinedType: 'CONTAINER_GROUP',
                layout: {
                  layout: 'FLEX',
                },
                dataRegionType: 'INHERIT',
                caption: '默认',
                itemStyle: 'DEFAULT',
                itemType: 'CONTAINER',
                layoutPos: {
                  layoutPos: 'CENTER',
                  layout: 'BORDER',
                },
                showCaption: true,
                id: 'container_group',
              },
              {
                actionGroupExtractMode: 'ITEM',
                panelItems: [
                  {
                    caption: '搜索表单',
                    itemStyle: 'DEFAULT',
                    itemType: 'CTRLPOS',
                    layoutPos: {
                      shrink: 1,
                      layout: 'FLEX',
                    },
                    showCaption: true,
                    id: 'searchform1',
                  },
                ],
                predefinedType: 'CONTAINER_GROUP',
                layout: {
                  layout: 'FLEX',
                },
                dataRegionType: 'INHERIT',
                caption: '不显示',
                itemStyle: 'DEFAULT',
                itemType: 'CONTAINER',
                layoutPos: {
                  layoutPos: 'CENTER',
                  layout: 'BORDER',
                },
                showCaption: true,
                id: 'container_group1',
              },
              {
                actionGroupExtractMode: 'ITEM',
                panelItems: [
                  {
                    caption: '搜索表单',
                    itemStyle: 'DEFAULT',
                    itemType: 'CTRLPOS',
                    layoutPos: {
                      shrink: 1,
                      layout: 'FLEX',
                    },
                    showCaption: true,
                    id: 'searchform2',
                  },
                ],
                predefinedType: 'CONTAINER_GROUP',
                layout: {
                  layout: 'FLEX',
                },
                dataRegionType: 'INHERIT',
                caption: '只有搜索',
                itemStyle: 'DEFAULT',
                itemType: 'CONTAINER',
                layoutPos: {
                  layoutPos: 'CENTER',
                  layout: 'BORDER',
                },
                showCaption: true,
                id: 'container_group2',
              },
            ],
            predefinedType: 'CONTAINER_SCROLL_MAIN',
            layout: {
              layout: 'BORDER',
            },
            dataRegionType: 'INHERIT',
            caption: '面板容器',
            itemStyle: 'DEFAULT',
            itemType: 'CONTAINER',
            layoutPos: {
              layoutPos: 'CENTER',
              layout: 'BORDER',
            },
            showCaption: true,
            id: 'container_scroll_main',
          },
        ],
        predefinedType: 'CONTAINER_SCROLL',
        layout: {
          layout: 'BORDER',
        },
        dataRegionType: 'INHERIT',
        caption: '滚动条容器',
        itemStyle: 'DEFAULT',
        itemType: 'CONTAINER',
        layoutPos: {
          shrink: 1,
          layout: 'FLEX',
        },
        id: 'container_scroll',
      },
    ],
    layoutPanel: true,
    controls: [
      {
        searchButtonPos: 'RIGHT',
        searchButtonStyle: 'DEFAULT',
        deformPages: [
          {
            layout: {
              columnCount: 24,
              layout: 'TABLE_24COL',
            },
            deformDetails: [
              {
                dataType: 25,
                enableCond: 3,
                labelPos: 'LEFT',
                labelWidth: 130,
                noPrivDisplayMode: 1,
                appDEFieldId: 'name',
                editor: {
                  editorType: 'TEXTBOX',
                  valueType: 'SIMPLE',
                  editable: true,
                  id: 'n_name_like',
                },
                allowEmpty: true,
                capLanguageRes: {
                  lanResTag: 'CONTROL.DEFSFITEM.MASTER.N_NAME_LIKE',
                },
                caption: '名称',
                codeName: 'n_name_like',
                detailStyle: 'DEFAULT',
                detailType: 'FORMITEM',
                layoutPos: {
                  colLG: 12,
                  colMD: 12,
                  layout: 'TABLE_24COL',
                },
                showCaption: true,
                id: 'n_name_like',
              },
              {
                dataType: 25,
                enableCond: 3,
                labelPos: 'LEFT',
                labelWidth: 130,
                noPrivDisplayMode: 1,
                appDEFieldId: 'type',
                editor: {
                  singleSelect: true,
                  handlerType: 'PickupText',
                  enableAC: true,
                  forceSelection: true,
                  showTrigger: true,
                  editorParams: {
                    AC: 'TRUE',
                    TRIGGER: 'TRUE',
                    PICKUPVIEW: 'FALSE',
                  },
                  editorType: 'PICKEREX_TRIGGER',
                  valueType: 'SIMPLE',
                  editable: true,
                  id: 'n_type_eq',
                },
                allowEmpty: true,
                caption: '类型',
                codeName: 'n_type_eq',
                detailStyle: 'DEFAULT',
                detailType: 'FORMITEM',
                layoutPos: {
                  colLG: 12,
                  colMD: 12,
                  layout: 'TABLE_24COL',
                },
                showCaption: true,
                id: 'n_type_eq',
              },
            ],
            caption: '常规条件',
            codeName: 'formpage1',
            detailStyle: 'DEFAULT',
            detailType: 'FORMPAGE',
            id: 'formpage1',
          },
        ],
        layout: {
          columnCount: 24,
          layout: 'TABLE_24COL',
        },
        tabHeaderPos: 'TOP',
        noTabHeader: true,
        autoLoad: true,
        showBusyIndicator: true,
        codeName: 'searchform_layout3',
        controlType: 'SEARCHFORM',
        logicName: '搜索表单_按钮样式_默认',
        appDataEntityId: 'web.master',
        controlLogics: [
          {
            eventNames: 'onSearch',
            logicTag: 'searchform',
            logicType: 'SCRIPT',
            scriptCode: 'util.message.info(data);',
            triggerType: 'CTRLEVENT',
            id: 'search_form_onsearch',
          },
        ],
        controlParam: {
          id: 'searchform',
        },
        modelId: 'b26d2beca674a15021663a7cef986fa9',
        modelType: 'PSDEFORM_SEARCHFORM',
        name: 'searchform',
        id: 'web.master.searchform_layout3',
      },
      {
        searchButtonPos: 'RIGHT',
        searchButtonStyle: 'NONE',
        enableAutoSearch: true,
        deformPages: [
          {
            layout: {
              columnCount: 24,
              layout: 'TABLE_24COL',
            },
            deformDetails: [
              {
                dataType: 25,
                enableCond: 3,
                labelPos: 'LEFT',
                labelWidth: 130,
                noPrivDisplayMode: 1,
                appDEFieldId: 'name',
                editor: {
                  editorType: 'TEXTBOX',
                  valueType: 'SIMPLE',
                  editable: true,
                  id: 'n_name_like',
                },
                allowEmpty: true,
                capLanguageRes: {
                  lanResTag: 'CONTROL.DEFSFITEM.MASTER.N_NAME_LIKE',
                },
                caption: '名称',
                codeName: 'n_name_like',
                detailStyle: 'DEFAULT',
                detailType: 'FORMITEM',
                layoutPos: {
                  colLG: 12,
                  colMD: 12,
                  layout: 'TABLE_24COL',
                },
                showCaption: true,
                id: 'n_name_like',
              },
              {
                dataType: 25,
                enableCond: 3,
                labelPos: 'LEFT',
                labelWidth: 130,
                noPrivDisplayMode: 1,
                appDEFieldId: 'type',
                editor: {
                  singleSelect: true,
                  handlerType: 'PickupText',
                  enableAC: true,
                  forceSelection: true,
                  showTrigger: true,
                  editorParams: {
                    AC: 'TRUE',
                    TRIGGER: 'TRUE',
                    PICKUPVIEW: 'FALSE',
                  },
                  editorType: 'PICKEREX_TRIGGER',
                  valueType: 'SIMPLE',
                  editable: true,
                  id: 'n_type_eq',
                },
                allowEmpty: true,
                caption: '类型',
                codeName: 'n_type_eq',
                detailStyle: 'DEFAULT',
                detailType: 'FORMITEM',
                layoutPos: {
                  colLG: 12,
                  colMD: 12,
                  layout: 'TABLE_24COL',
                },
                showCaption: true,
                id: 'n_type_eq',
              },
            ],
            caption: '常规条件',
            codeName: 'formpage1',
            detailStyle: 'DEFAULT',
            detailType: 'FORMPAGE',
            id: 'formpage1',
          },
        ],
        layout: {
          columnCount: 24,
          layout: 'TABLE_24COL',
        },
        tabHeaderPos: 'TOP',
        noTabHeader: true,
        autoLoad: true,
        showBusyIndicator: true,
        codeName: 'searchform_layout4',
        controlType: 'SEARCHFORM',
        logicName: '搜索表单_按钮样式_不显示',
        appDataEntityId: 'web.master',
        controlLogics: [
          {
            eventNames: 'onSearch',
            logicTag: 'searchform1',
            logicType: 'SCRIPT',
            scriptCode: 'util.message.info(data);',
            triggerType: 'CTRLEVENT',
            id: 'search_form_onsearch',
          },
        ],
        controlParam: {
          id: 'searchform1',
        },
        modelId: 'eab8d6ef6a7747c9b471947d266d8f9e',
        modelType: 'PSDEFORM_SEARCHFORM',
        name: 'searchform1',
        id: 'web.master.searchform_layout4',
      },
      {
        searchButtonPos: 'RIGHT',
        searchButtonStyle: 'SEARCHONLY',
        deformPages: [
          {
            layout: {
              columnCount: 24,
              layout: 'TABLE_24COL',
            },
            deformDetails: [
              {
                dataType: 25,
                enableCond: 3,
                labelPos: 'LEFT',
                labelWidth: 130,
                noPrivDisplayMode: 1,
                appDEFieldId: 'name',
                editor: {
                  editorType: 'TEXTBOX',
                  valueType: 'SIMPLE',
                  editable: true,
                  id: 'n_name_like',
                },
                allowEmpty: true,
                capLanguageRes: {
                  lanResTag: 'CONTROL.DEFSFITEM.MASTER.N_NAME_LIKE',
                },
                caption: '名称',
                codeName: 'n_name_like',
                detailStyle: 'DEFAULT',
                detailType: 'FORMITEM',
                layoutPos: {
                  colLG: 12,
                  colMD: 12,
                  layout: 'TABLE_24COL',
                },
                showCaption: true,
                id: 'n_name_like',
              },
              {
                dataType: 25,
                enableCond: 3,
                labelPos: 'LEFT',
                labelWidth: 130,
                noPrivDisplayMode: 1,
                appDEFieldId: 'type',
                editor: {
                  singleSelect: true,
                  handlerType: 'PickupText',
                  enableAC: true,
                  forceSelection: true,
                  showTrigger: true,
                  editorParams: {
                    AC: 'TRUE',
                    TRIGGER: 'TRUE',
                    PICKUPVIEW: 'FALSE',
                  },
                  editorType: 'PICKEREX_TRIGGER',
                  valueType: 'SIMPLE',
                  editable: true,
                  id: 'n_type_eq',
                },
                allowEmpty: true,
                caption: '类型',
                codeName: 'n_type_eq',
                detailStyle: 'DEFAULT',
                detailType: 'FORMITEM',
                layoutPos: {
                  colLG: 12,
                  colMD: 12,
                  layout: 'TABLE_24COL',
                },
                showCaption: true,
                id: 'n_type_eq',
              },
            ],
            caption: '常规条件',
            codeName: 'formpage1',
            detailStyle: 'DEFAULT',
            detailType: 'FORMPAGE',
            id: 'formpage1',
          },
        ],
        layout: {
          columnCount: 24,
          layout: 'TABLE_24COL',
        },
        tabHeaderPos: 'TOP',
        noTabHeader: true,
        autoLoad: true,
        showBusyIndicator: true,
        codeName: 'searchform_layout5',
        controlType: 'SEARCHFORM',
        logicName: '搜索表单_按钮样式_只有搜索',
        appDataEntityId: 'web.master',
        controlLogics: [
          {
            eventNames: 'onSearch',
            logicTag: 'searchform2',
            logicType: 'SCRIPT',
            scriptCode: 'util.message.info(data);',
            triggerType: 'CTRLEVENT',
            id: 'search_form_onsearch',
          },
        ],
        controlParam: {
          id: 'searchform2',
        },
        modelId: 'cb20af572127bc95b5a45a26ddc95654',
        modelType: 'PSDEFORM_SEARCHFORM',
        name: 'searchform2',
        id: 'web.master.searchform_layout5',
      },
      {
        capLanguageRes: {
          lanResTag: 'DE.LNAME.MASTER',
        },
        caption: '搜索表单_按钮样式',
        codeName: 'searchform_btncss_captionbar',
        controlType: 'CAPTIONBAR',
        appDataEntityId: 'web.master',
        controlParam: {},
        name: 'captionbar',
        id: 'searchform_btncss_captionbar',
      },
    ],
    codeName: 'a351726d2d4257cb838',
    controlType: 'VIEWLAYOUTPANEL',
    logicName: 'searchform_btncss',
    appDataEntityId: 'web.master',
    controlParam: {},
    modelId: '7ba8e22ab7ff18b4a0601861e41d600a',
    modelType: 'PSSYSVIEWLAYOUTPANEL',
    name: 'layoutpanel',
    id: 'a351726d2d4257cb838',
  },
  title: '搜索表单_按钮样式',
  viewStyle: 'DEFAULT',
  viewType: 'DECUSTOMVIEW',
  enableDP: true,
  showCaptionBar: false,
  modelId: '66d53c78bbb2a656c54bf0afa094b60c',
  modelType: 'PSAPPDEVIEW',
  name: 'MASTERsearchform_btncss',
  id: 'web.master_searchform_btncss',
};
