export default {
  mdctrlActiveMode: 2,
  xdataControlName: 'list',
  loadDefault: true,
  deviewCodeName: 'list_logic',
  deviewId: '4e89342275371a75d5b0e46af31866b8',
  accUserMode: 2,
  capLanguageRes: {
    lanResTag: 'DE.LNAME.MASTER',
  },
  caption: '列表_事件及调用',
  codeName: 'master_list_logic',
  appDataEntityId: 'web.master',
  appViewEngines: [
    {
      engineCat: 'VIEW',
      engineType: 'ListView',
      id: 'engine',
    },
  ],
  appViewLogics: [
    {
      logicTrigger: 'CUSTOM',
      logicType: 'APPUILOGIC',
      builtinAppUILogic: {
        actionAfterWizard: 'DEFAULT',
        newDataAppView: {
          openMode: 'POPUPMODAL',
          refAppViewId: 'web.master_edit_view',
        },
        appUILogicRefViews: [
          {
            openMode: 'POPUPMODAL',
            refAppViewId: 'web.master_edit_view',
          },
        ],
        builtinLogic: true,
        logicType: 'PREDEFINED',
        viewLogicType: 'APP_NEWDATA',
        id: '新建数据',
      },
      builtinLogic: true,
      id: 'newdata',
    },
    {
      logicTrigger: 'CUSTOM',
      logicType: 'APPUILOGIC',
      builtinAppUILogic: {
        openDataAppView: {
          openMode: 'POPUPMODAL',
          refAppViewId: 'web.master_edit_view',
        },
        editMode: true,
        appUILogicRefViews: [
          {
            openMode: 'POPUPMODAL',
            refAppViewId: 'web.master_edit_view',
          },
        ],
        builtinLogic: true,
        logicType: 'PREDEFINED',
        viewLogicType: 'APP_OPENDATA',
        id: '打开数据',
      },
      builtinLogic: true,
      id: 'opendata',
    },
  ],
  appViewMsgGroupId: 'event_and_call',
  appViewRefs: [
    {
      realOpenMode: 'POPUPMODAL',
      realTitle: '主数据编辑视图',
      refAppViewId: 'web.master_edit_view',
      name: 'NEWDATA',
      id: 'newdata',
    },
    {
      realOpenMode: 'POPUPMODAL',
      realTitle: '主数据编辑视图',
      refAppViewId: 'web.master_edit_view',
      name: 'EDITDATA',
      id: 'editdata',
    },
  ],
  controls: [
    {
      searchButtonStyle: 'DEFAULT',
      deformPages: [
        {
          layout: {
            columnCount: 24,
            layout: 'TABLE_24COL',
          },
          caption: '常规条件',
          codeName: 'formpage1',
          detailStyle: 'DEFAULT',
          detailType: 'FORMPAGE',
          id: 'formpage1',
        },
      ],
      layout: {
        columnCount: 24,
        layout: 'TABLE_24COL',
      },
      tabHeaderPos: 'TOP',
      noTabHeader: true,
      autoLoad: true,
      showBusyIndicator: true,
      codeName: 'main81',
      controlType: 'SEARCHFORM',
      logicName: '列表_事件及调用_搜索表单',
      appDataEntityId: 'web.master',
      controlParam: {
        id: 'searchform',
      },
      modelId: 'ea4a058c31f4af99cf49225556461c31',
      modelType: 'PSDEFORM_SEARCHFORM',
      name: 'searchform',
      id: 'web.master.main81',
    },
    {
      detoolbarItems: [
        {
          actionLevel: 100,
          noPrivDisplayMode: 2,
          uiactionId: 'single_data_key@master',
          uiactionTarget: 'SINGLEKEY',
          valid: true,
          caption: '单选数据（主键）',
          itemType: 'DEUIACTION',
          tooltip: '单选数据（主键）',
          showCaption: true,
          showIcon: true,
          id: 'deuiaction1',
        },
        {
          actionLevel: 100,
          noPrivDisplayMode: 2,
          uiactionId: 'single_data@master',
          uiactionTarget: 'SINGLEDATA',
          valid: true,
          caption: '单项数据',
          itemType: 'DEUIACTION',
          tooltip: '单项数据',
          showCaption: true,
          showIcon: true,
          id: 'deuiaction2',
        },
        {
          actionLevel: 100,
          noPrivDisplayMode: 2,
          uiactionId: 'specify_view_parameters@master',
          uiactionTarget: 'SINGLEKEY',
          valid: true,
          caption: '指定视图参数',
          itemType: 'DEUIACTION',
          tooltip: '指定视图参数',
          showCaption: true,
          showIcon: true,
          id: 'deuiaction3',
        },
        {
          actionLevel: 100,
          noPrivDisplayMode: 2,
          uiactionId: 'select_data@master',
          uiactionTarget: 'SINGLEDATA',
          valid: true,
          caption: '输出选择数据',
          itemType: 'DEUIACTION',
          tooltip: '输出选择数据',
          showCaption: true,
          showIcon: true,
          id: 'deuiaction4',
        },
      ],
      xdataControlName: 'list',
      codeName: 'list_logic_toolbar',
      controlType: 'TOOLBAR',
      logicName: '列表_事件及调用_工具栏',
      appDataEntityId: 'web.master',
      controlParam: {
        id: 'toolbar',
      },
      modelId: '2614356c12aa938eb20616e7f40c1eba',
      modelType: 'PSDETOOLBAR',
      name: 'toolbar',
      id: 'list_logic_toolbar',
    },
    {
      groupMode: 'NONE',
      groupStyle: 'DEFAULT',
      itemLayoutPanel: {
        layoutMode: 'FLEX',
        layout: {
          layout: 'FLEX',
        },
        rootPanelItems: [
          {
            actionGroupExtractMode: 'ITEM',
            panelItems: [
              {
                actionGroupExtractMode: 'ITEM',
                panelItems: [
                  {
                    rawItem: {
                      sysImage: {
                        rawContent:
                          '<svg id="图层_2" data-name="图层 2" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 45.05908 45.05914"><defs><style>.cls-1{fill:#01b0ff;}</style></defs><title>ibizlab. 2</title><path class="cls-1" d="M1.64777,456.35452v45.05914H46.70685V456.35452Zm39.92407,3.86188-9.51965,19.60479L11.59913,460.1221ZM4.35572,497.13931v-34.424c8.37353,26.80664,17.53088,34.424,17.53088,34.424ZM17.424,472.06509l12.64337,12.21838-5.52484,9.77466S16.25531,478.54611,17.424,472.06509Zm9.031,25.07422,6.58728-9.031,7.64978,9.031Zm16.71912-2.99152-7.54029-9.61389,7.63453-13.10132Z" transform="translate(-1.64777 -456.35452)"/></svg>',
                      },
                      contentType: 'IMAGE',
                      predefinedType: 'STATIC_IMAGE',
                      rawItemHeight: 32,
                      rawItemWidth: 32,
                      id: 'static_image',
                    },
                    caption: '图片',
                    contentHeight: 32,
                    contentWidth: 32,
                    height: 32,
                    itemStyle: 'DEFAULT',
                    itemType: 'RAWITEM',
                    layoutPos: {
                      shrink: 1,
                      height: 32,
                      heightMode: 'PX',
                      layout: 'FLEX',
                      width: 32,
                      widthMode: 'PX',
                    },
                    sysImage: {
                      rawContent:
                        '<svg id="图层_2" data-name="图层 2" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 45.05908 45.05914"><defs><style>.cls-1{fill:#01b0ff;}</style></defs><title>ibizlab. 2</title><path class="cls-1" d="M1.64777,456.35452v45.05914H46.70685V456.35452Zm39.92407,3.86188-9.51965,19.60479L11.59913,460.1221ZM4.35572,497.13931v-34.424c8.37353,26.80664,17.53088,34.424,17.53088,34.424ZM17.424,472.06509l12.64337,12.21838-5.52484,9.77466S16.25531,478.54611,17.424,472.06509Zm9.031,25.07422,6.58728-9.031,7.64978,9.031Zm16.71912-2.99152-7.54029-9.61389,7.63453-13.10132Z" transform="translate(-1.64777 -456.35452)"/></svg>',
                    },
                    width: 32,
                    showCaption: true,
                    id: 'static_image',
                  },
                  {
                    actionGroupExtractMode: 'ITEM',
                    panelItems: [
                      {
                        editor: {
                          halign: 'LEFT',
                          renderMode: 'TEXT_DYNAMIC',
                          valign: 'MIDDLE',
                          wrapMode: 'NOWRAP',
                          editorType: 'SPAN',
                          predefinedType: 'FIELD_TEXT_DYNAMIC',
                          valueType: 'SIMPLE',
                          editable: true,
                          id: 'name',
                        },
                        valueFormat: '名称：@',
                        viewFieldName: 'name',
                        allowEmpty: true,
                        caption: '文本(动态)',
                        itemStyle: 'DEFAULT',
                        itemType: 'FIELD',
                        layoutPos: {
                          shrink: 1,
                          layout: 'FLEX',
                        },
                        id: 'name',
                      },
                      {
                        editor: {
                          halign: 'LEFT',
                          renderMode: 'TEXT_DYNAMIC',
                          valign: 'MIDDLE',
                          wrapMode: 'NOWRAP',
                          editorType: 'SPAN',
                          predefinedType: 'FIELD_TEXT_DYNAMIC',
                          valueType: 'SIMPLE',
                          editable: true,
                          id: 'quantity',
                        },
                        valueFormat: '数量：#,###',
                        viewFieldName: 'quantity',
                        allowEmpty: true,
                        caption: '文本(动态)',
                        itemStyle: 'DEFAULT',
                        itemType: 'FIELD',
                        layoutPos: {
                          shrink: 1,
                          layout: 'FLEX',
                        },
                        id: 'quantity',
                      },
                    ],
                    layout: {
                      align: 'center',
                      dir: 'column',
                      layout: 'FLEX',
                    },
                    dataRegionType: 'INHERIT',
                    caption: '容器',
                    itemStyle: 'DEFAULT',
                    itemType: 'CONTAINER',
                    layoutPos: {
                      shrink: 1,
                      layout: 'FLEX',
                      spacingLeft: 'OUTERMEDIUM',
                    },
                    id: 'container3',
                  },
                ],
                layout: {
                  align: 'center',
                  dir: 'row',
                  layout: 'FLEX',
                  valign: 'center',
                },
                dataRegionType: 'INHERIT',
                caption: '容器',
                itemStyle: 'DEFAULT',
                itemType: 'CONTAINER',
                layoutPos: {
                  shrink: 1,
                  layout: 'FLEX',
                },
                id: 'container',
              },
              {
                actionGroupExtractMode: 'ITEM',
                panelItems: [
                  {
                    editor: {
                      halign: 'LEFT',
                      renderMode: 'TEXT_DYNAMIC',
                      valign: 'MIDDLE',
                      wrapMode: 'NOWRAP',
                      appCodeListId: 'web.mock__cl_status',
                      editorType: 'SPAN',
                      predefinedType: 'FIELD_TEXT_DYNAMIC',
                      valueType: 'SIMPLE',
                      editable: true,
                      id: 'status',
                    },
                    viewFieldName: 'status',
                    allowEmpty: true,
                    convertToCodeItemText: true,
                    caption: '文本(动态)',
                    itemStyle: 'DEFAULT',
                    itemType: 'FIELD',
                    layoutPos: {
                      shrink: 1,
                      layout: 'FLEX',
                    },
                    id: 'status',
                  },
                ],
                layout: {
                  layout: 'FLEX',
                },
                dataRegionType: 'INHERIT',
                caption: '容器',
                itemStyle: 'DEFAULT',
                itemType: 'CONTAINER',
                layoutPos: {
                  shrink: 1,
                  layout: 'FLEX',
                },
                id: 'container2',
              },
              {
                actionGroupExtractMode: 'ITEM',
                panelItems: [
                  {
                    actionGroupExtractMode: 'ITEM',
                    buttonListType: 'UIACTIONGROUP',
                    uiactionGroup: {
                      uiactionGroupDetails: [
                        {
                          actionLevel: 100,
                          afterItemType: 'NONE',
                          beforeItemType: 'NONE',
                          buttonStyle: 'DEFAULT',
                          caption: '单选数据（主键）',
                          detailType: 'DEUIACTION',
                          uiactionId: 'single_data_key@master',
                          showCaption: true,
                          showIcon: true,
                          id: 'uc50332c',
                        },
                        {
                          actionLevel: 100,
                          afterItemType: 'NONE',
                          beforeItemType: 'NONE',
                          buttonStyle: 'DEFAULT',
                          caption: '单项数据',
                          detailType: 'DEUIACTION',
                          uiactionId: 'single_data@master',
                          showCaption: true,
                          showIcon: true,
                          id: 'uc12bbfd',
                        },
                        {
                          actionLevel: 100,
                          afterItemType: 'NONE',
                          beforeItemType: 'NONE',
                          buttonStyle: 'DEFAULT',
                          caption: '指定视图参数',
                          detailType: 'DEUIACTION',
                          uiactionId: 'specify_view_parameters@master',
                          showCaption: true,
                          showIcon: true,
                          id: 'uf0bc74e',
                        },
                        {
                          actionLevel: 100,
                          afterItemType: 'NONE',
                          beforeItemType: 'NONE',
                          buttonStyle: 'DEFAULT',
                          caption: '输出选择数据',
                          detailType: 'DEUIACTION',
                          uiactionId: 'select_data@master',
                          showCaption: true,
                          showIcon: true,
                          id: 'u580f528',
                        },
                      ],
                      appDataEntityId: 'web.master',
                      id: '事件及调用行为组',
                    },
                    caption: '按钮组',
                    itemStyle: 'DEFAULT',
                    itemType: 'BUTTONLIST',
                    layoutPos: {
                      shrink: 1,
                      layout: 'FLEX',
                    },
                    id: 'buttonlist',
                  },
                ],
                layout: {
                  layout: 'FLEX',
                },
                dataRegionType: 'INHERIT',
                caption: '容器',
                itemStyle: 'DEFAULT',
                itemType: 'CONTAINER',
                layoutPos: {
                  shrink: 1,
                  layout: 'FLEX',
                },
                id: 'container4',
              },
            ],
            layout: {
              align: 'space-between',
              dir: 'row',
              layout: 'FLEX',
              valign: 'center',
            },
            dataRegionType: 'INHERIT',
            itemStyle: 'DEFAULT',
            itemType: 'CONTAINER',
            layoutPos: {
              shrink: 1,
              layout: 'FLEX',
            },
            id: 'container1',
          },
        ],
        layoutPanel: true,
        codeName: 'list_itempanel',
        controlType: 'PANEL',
        logicName: 'list_logic_List列表',
        appDataEntityId: 'web.master',
        controlParam: {},
        modelId: 'b46fcc42c61a11a9c61c380e406ec2ef',
        modelType: 'PSSYSVIEWPANEL',
        name: 'list_itempanel',
        id: 'web.master.list_itempanel',
      },
      pagingSize: 1000,
      showHeader: true,
      navViewPos: 'NONE',
      createControlAction: {
        appDEMethodId: 'create',
        appDataEntityId: 'web.master',
        id: 'create',
      },
      fetchControlAction: {
        appDEMethodId: 'fetch_default',
        appDataEntityId: 'web.master',
        id: 'fetch',
      },
      getControlAction: {
        appDEMethodId: 'get',
        appDataEntityId: 'web.master',
        id: 'load',
      },
      removeControlAction: {
        appDEMethodId: 'remove',
        appDataEntityId: 'web.master',
        id: 'remove',
      },
      updateControlAction: {
        appDEMethodId: 'update',
        appDataEntityId: 'web.master',
        id: 'update',
      },
      autoLoad: true,
      showBusyIndicator: true,
      codeName: 'list_logic_list',
      controlType: 'LIST',
      logicName: 'List2',
      appDataEntityId: 'web.master',
      controlParam: {
        id: 'list',
      },
      modelId: '340c69ad2cd03fa82589d36b5a5c26af',
      modelType: 'PSDELIST',
      name: 'list',
      id: 'web.master.list_logic_list',
    },
    {
      groupMode: 'SINGLE',
      quickSearchMode: 1,
      enableQuickSearch: true,
      controlType: 'SEARCHBAR',
      appDataEntityId: 'web.master',
      controlParam: {
        id: 'searchbar',
      },
      id: 'searchbar',
    },
    {
      capLanguageRes: {
        lanResTag: 'DE.LNAME.MASTER',
      },
      caption: '列表_事件及调用',
      codeName: 'list_logic_captionbar',
      controlType: 'CAPTIONBAR',
      appDataEntityId: 'web.master',
      controlParam: {},
      name: 'captionbar',
      id: 'list_logic_captionbar',
    },
  ],
  viewLayoutPanel: {
    layoutBodyOnly: true,
    useDefaultLayout: true,
    layoutPanel: true,
    codeName: 'layoutpanel',
    controlStyle: 'APPDELISTVIEW',
    controlType: 'VIEWLAYOUTPANEL',
    appDataEntityId: 'web.master',
    controlParam: {},
    id: 'layoutpanel',
  },
  title: '列表_事件及调用',
  viewStyle: 'DEFAULT',
  viewType: 'DELISTVIEW',
  enableDP: true,
  showCaptionBar: false,
  modelId: '358798f975c00778cb1bd6a6ffb489e1',
  modelType: 'PSAPPDEVIEW',
  name: 'MASTERlist_logic',
  id: 'web.master_list_logic',
};
