export default {
  tabLayout: 'FLOW',
  loadDefault: true,
  showDataInfoBar: true,
  deviewCodeName: 'tab_nav',
  deviewId: 'c87b1c6dc8c19c3869a88d59146702a8',
  accUserMode: 3,
  capLanguageRes: {
    lanResTag: 'DE.LNAME.MASTER',
  },
  caption: '导航视图',
  codeName: 'master_tab_nav',
  appDataEntityId: 'web.master',
  appViewEngines: [
    {
      engineCat: 'VIEW',
      engineType: 'TabExpView',
      id: 'engine',
    },
  ],
  appViewMsgGroupId: 'tab_nav',
  controls: [
    {
      dedrtabPages: [
        {
          caption: '树导航视图',
          appViewId: 'web.master_tree_exp',
          id: 'tree_ext',
        },
        {
          caption: '表格导航',
          appViewId: 'web.region_grid_nav',
          id: 'grid_nav',
        },
        {
          caption: '列表导航',
          appViewId: 'web.region_list_exp_view',
          id: 'list_nav',
        },
        {
          caption: '卡片导航',
          appViewId: 'web.region_data_view_exp_view',
          id: 'card_nav',
        },
        {
          caption: '日历导航',
          appViewId: 'web.master_calendar_exp_view',
          id: 'cal_nav',
        },
      ],
      dataRelationTag: 'DataRelation',
      editItemCapLanguageRes: {
        lanResTag: 'DE.LNAME.MASTER',
      },
      editItemCaption: '主数据',
      uniqueTag: 'master_tab_nav__tabexppanel',
      autoLoad: true,
      showBusyIndicator: true,
      codeName: 'data_relation',
      controlType: 'DRTAB',
      appDataEntityId: 'web.master',
      controlParam: {
        id: 'tabexppanel',
      },
      modelId: '2f4257762762e1abceb561dfab1f0002',
      modelType: 'PSDEDRTAB',
      name: 'tabexppanel',
      id: 'data_relation',
    },
    {
      capLanguageRes: {
        lanResTag: 'DE.LNAME.MASTER',
      },
      caption: '导航视图',
      codeName: 'tab_nav_captionbar',
      controlType: 'CAPTIONBAR',
      appDataEntityId: 'web.master',
      controlParam: {},
      name: 'captionbar',
      id: 'tab_nav_captionbar',
    },
  ],
  viewLayoutPanel: {
    layoutBodyOnly: true,
    useDefaultLayout: true,
    layoutPanel: true,
    codeName: 'layoutpanel',
    controlStyle: 'APPDETABEXPVIEW',
    controlType: 'VIEWLAYOUTPANEL',
    appDataEntityId: 'web.master',
    controlParam: {},
    id: 'layoutpanel',
  },
  title: '导航视图',
  viewStyle: 'DEFAULT',
  viewType: 'DETABEXPVIEW',
  enableDP: true,
  showCaptionBar: false,
  modelId: '541d332bb7a880724402e62424510f30',
  modelType: 'PSAPPDEVIEW',
  name: 'MASTERtab_nav',
  id: 'web.master_tab_nav',
};
