export default {
  tabLayout: 'FLOW',
  loadDefault: true,
  showDataInfoBar: true,
  deviewCodeName: 'treeview',
  deviewId: 'c17f084b1e2f8cdef24f0ad7dfc5a878',
  accUserMode: 3,
  capLanguageRes: {
    lanResTag: 'DE.LNAME.MASTER',
  },
  caption: '树视图',
  codeName: 'master_treeview',
  appDataEntityId: 'web.master',
  appViewEngines: [
    {
      engineCat: 'VIEW',
      engineType: 'TabExpView',
      id: 'engine',
    },
  ],
  appViewMsgGroupId: 'treeview',
  controls: [
    {
      dedrtabPages: [
        {
          caption: '常规',
          appViewId: 'web.master_tree_base',
          id: 'base',
        },
        {
          caption: '数据源',
          appViewId: 'web.master_tree_datasource',
          id: 'data_source',
        },
        {
          caption: '搜索',
          appViewId: 'web.master_tree_search',
          id: 'search',
        },
        {
          caption: '导航传参',
          appViewId: 'web.master_treeview_navparams',
          id: 'pass_parameters',
        },
        {
          caption: '右键菜单',
          appViewId: 'web.master_tree_contextmenu',
          id: 'right_click',
        },
        {
          caption: '拖拽',
          appViewId: 'web.master_tree_drag',
          id: 'drag_and_drop',
        },
        {
          caption: '树表格',
          appViewId: 'web.region_tree_grid_view',
          id: 'tree_table',
        },
        {
          caption: '甘特图',
          appViewId: 'web.master_gantt_view',
          id: 'gantt',
        },
        {
          caption: '内置导航',
          appViewId: 'web.master_treeview_nav',
          id: 'built_in_nav',
        },
        {
          caption: '界面样式及图标',
          appViewId: 'web.master_treeview_cssandicon',
          id: 'css_and_icon',
        },
        {
          caption: '事件及调用',
          appViewId: 'web.master_doing_custom_view',
          id: 'event_and_call',
        },
      ],
      dataRelationTag: 'tree_DR',
      editItemCapLanguageRes: {
        lanResTag: 'DE.LNAME.MASTER',
      },
      editItemCaption: '主数据',
      uniqueTag: 'master_treeview__tabexppanel',
      autoLoad: true,
      showBusyIndicator: true,
      codeName: 'tree_dr',
      controlType: 'DRTAB',
      appDataEntityId: 'web.master',
      controlParam: {
        id: 'tabexppanel',
      },
      modelId: '59de09bd98db1fb6cb222643b9318950',
      modelType: 'PSDEDRTAB',
      name: 'tabexppanel',
      id: 'tree_dr',
    },
    {
      capLanguageRes: {
        lanResTag: 'DE.LNAME.MASTER',
      },
      caption: '树视图',
      codeName: 'treeview_captionbar',
      controlType: 'CAPTIONBAR',
      appDataEntityId: 'web.master',
      controlParam: {},
      name: 'captionbar',
      id: 'treeview_captionbar',
    },
  ],
  viewLayoutPanel: {
    layoutBodyOnly: true,
    useDefaultLayout: true,
    layoutPanel: true,
    codeName: 'layoutpanel',
    controlStyle: 'APPDETABEXPVIEW',
    controlType: 'VIEWLAYOUTPANEL',
    appDataEntityId: 'web.master',
    controlParam: {},
    id: 'layoutpanel',
  },
  title: '树视图',
  viewStyle: 'DEFAULT',
  viewType: 'DETABEXPVIEW',
  enableDP: true,
  showCaptionBar: false,
  modelId: '72e91624ab10abc720fc9f514ad8b770',
  modelType: 'PSAPPDEVIEW',
  name: 'MASTERtreeview',
  id: 'web.master_treeview',
};
