export default {
  gridRowActiveMode: 2,
  expandSearchForm: true,
  xdataControlName: 'grid',
  loadDefault: true,
  deviewCodeName: 'searchform_advanced',
  deviewId: 'f233f9bf78908e07d5e63ad8a53f8853',
  accUserMode: 3,
  capLanguageRes: {
    lanResTag: 'DE.LNAME.MASTER',
  },
  caption: '搜索表单_高级搜索',
  codeName: 'master_searchform_advanced',
  appDataEntityId: 'web.master',
  appViewMsgGroupId: 'searchform_advanced',
  viewLayoutPanel: {
    viewProxyMode: true,
    layoutMode: 'FLEX',
    layout: {
      layout: 'FLEX',
    },
    rootPanelItems: [
      {
        actionGroupExtractMode: 'ITEM',
        panelItems: [
          {
            actionGroupExtractMode: 'ITEM',
            panelItems: [
              {
                actionGroupExtractMode: 'ITEM',
                panelItems: [
                  {
                    caption: '页面标题',
                    itemStyle: 'DEFAULT',
                    itemType: 'CTRLPOS',
                    layoutPos: {
                      shrink: 1,
                      layout: 'FLEX',
                    },
                    showCaption: true,
                    id: 'captionbar',
                  },
                ],
                layout: {
                  align: 'center',
                  layout: 'FLEX',
                },
                dataRegionType: 'INHERIT',
                caption: '容器',
                itemStyle: 'DEFAULT',
                itemType: 'CONTAINER',
                layoutPos: {
                  shrink: 1,
                  heightMode: 'FULL',
                  layout: 'FLEX',
                },
                id: 'view_captionbar',
              },
            ],
            layout: {
              layout: 'FLEX',
            },
            dataRegionType: 'INHERIT',
            caption: '容器',
            itemStyle: 'DEFAULT',
            itemType: 'CONTAINER',
            layoutPos: {
              shrink: 1,
              heightMode: 'FULL',
              layout: 'FLEX',
            },
            id: 'view_header_left',
          },
          {
            actionGroupExtractMode: 'ITEM',
            panelItems: [
              {
                actionGroupExtractMode: 'ITEM',
                panelItems: [
                  {
                    caption: '工具栏',
                    itemStyle: 'DEFAULT',
                    itemType: 'CTRLPOS',
                    layoutPos: {
                      shrink: 1,
                      layout: 'FLEX',
                    },
                    showCaption: true,
                    id: 'toolbar',
                  },
                ],
                layout: {
                  align: 'center',
                  layout: 'FLEX',
                },
                dataRegionType: 'INHERIT',
                caption: '容器',
                itemStyle: 'DEFAULT',
                itemType: 'CONTAINER',
                layoutPos: {
                  shrink: 1,
                  heightMode: 'FULL',
                  layout: 'FLEX',
                },
                id: 'view_toolbar',
              },
            ],
            layout: {
              layout: 'FLEX',
            },
            dataRegionType: 'INHERIT',
            caption: '容器',
            itemStyle: 'DEFAULT',
            itemType: 'CONTAINER',
            layoutPos: {
              shrink: 1,
              heightMode: 'FULL',
              layout: 'FLEX',
            },
            id: 'view_header_right',
          },
        ],
        predefinedType: 'VIEWHEADER',
        layout: {
          align: 'space-between',
          dir: 'row',
          layout: 'FLEX',
          valign: 'center',
        },
        dataRegionType: 'INHERIT',
        caption: '容器',
        itemStyle: 'DEFAULT',
        itemType: 'CONTAINER',
        layoutPos: {
          shrink: 0,
          layout: 'FLEX',
        },
        id: 'view_header',
      },
      {
        actionGroupExtractMode: 'ITEM',
        panelItems: [
          {
            caption: '搜索表单',
            itemStyle: 'DEFAULT',
            itemType: 'CTRLPOS',
            layoutPos: {
              shrink: 1,
              layout: 'FLEX',
            },
            showCaption: true,
            id: 'searchform',
          },
        ],
        layout: {
          dir: 'column',
          layout: 'FLEX',
        },
        dataRegionType: 'INHERIT',
        itemStyle: 'DEFAULT',
        itemType: 'CONTAINER',
        layoutPos: {
          shrink: 0,
          layout: 'FLEX',
        },
        id: 'view_searchform',
      },
      {
        actionGroupExtractMode: 'ITEM',
        panelItems: [
          {
            caption: '表格',
            itemStyle: 'DEFAULT',
            itemType: 'CTRLPOS',
            layoutPos: {
              grow: 1,
              shrink: 1,
              layout: 'FLEX',
            },
            showCaption: true,
            id: 'grid',
          },
        ],
        predefinedType: 'VIEWCONTENT',
        layout: {
          layout: 'FLEX',
        },
        dataRegionType: 'INHERIT',
        caption: '容器',
        itemStyle: 'DEFAULT',
        itemType: 'CONTAINER',
        layoutPos: {
          grow: 1,
          shrink: 1,
          layout: 'FLEX',
        },
        id: 'view_content',
      },
    ],
    layoutPanel: true,
    appViewEngines: [
      {
        engineCat: 'VIEW',
        engineType: 'GridView',
        id: 'engine',
      },
    ],
    appViewLogics: [
      {
        logicTrigger: 'CUSTOM',
        logicType: 'APPUILOGIC',
        builtinAppUILogic: {
          actionAfterWizard: 'DEFAULT',
          newDataAppView: {
            openMode: 'POPUPMODAL',
            refAppViewId: 'web.master_edit_view',
          },
          appUILogicRefViews: [
            {
              openMode: 'POPUPMODAL',
              refAppViewId: 'web.master_edit_view',
            },
          ],
          builtinLogic: true,
          logicType: 'PREDEFINED',
          viewLogicType: 'APP_NEWDATA',
          id: '新建数据',
        },
        builtinLogic: true,
        id: 'newdata',
      },
      {
        logicTrigger: 'CUSTOM',
        logicType: 'APPUILOGIC',
        builtinAppUILogic: {
          openDataAppView: {
            openMode: 'POPUPMODAL',
            refAppViewId: 'web.master_edit_view',
          },
          editMode: true,
          appUILogicRefViews: [
            {
              openMode: 'POPUPMODAL',
              refAppViewId: 'web.master_edit_view',
            },
          ],
          builtinLogic: true,
          logicType: 'PREDEFINED',
          viewLogicType: 'APP_OPENDATA',
          id: '打开数据',
        },
        builtinLogic: true,
        id: 'opendata',
      },
    ],
    appViewRefs: [
      {
        realOpenMode: 'POPUPMODAL',
        realTitle: '主数据编辑视图',
        refAppViewId: 'web.master_edit_view',
        name: 'EDITDATA',
        id: 'editdata',
      },
      {
        realOpenMode: 'POPUPMODAL',
        realTitle: '主数据编辑视图',
        refAppViewId: 'web.master_edit_view',
        name: 'NEWDATA',
        id: 'newdata',
      },
    ],
    controls: [
      {
        searchButtonStyle: 'SEARCHONLY',
        enableAdvanceSearch: true,
        deformPages: [
          {
            layout: {
              columnCount: 24,
              layout: 'TABLE_24COL',
            },
            deformDetails: [
              {
                dataType: 25,
                enableCond: 3,
                labelPos: 'LEFT',
                labelWidth: 100,
                noPrivDisplayMode: 1,
                appDEFieldId: 'name',
                editor: {
                  editorType: 'TEXTBOX',
                  valueType: 'SIMPLE',
                  editable: true,
                  id: 'n_name_like',
                },
                allowEmpty: true,
                capLanguageRes: {
                  lanResTag: 'CONTROL.DEFSFITEM.MASTER.N_NAME_LIKE',
                },
                caption: '名称(%)',
                codeName: 'n_name_like',
                detailStyle: 'DEFAULT',
                detailType: 'FORMITEM',
                layoutPos: {
                  colLG: 12,
                  colMD: 12,
                  layout: 'TABLE_24COL',
                },
                showCaption: true,
                userTag: 'permanent',
                id: 'n_name_like',
              },
              {
                dataType: 25,
                enableCond: 3,
                labelPos: 'LEFT',
                labelWidth: 100,
                noPrivDisplayMode: 1,
                appDEFieldId: 'type',
                editor: {
                  singleSelect: true,
                  handlerType: 'PickupText',
                  enableAC: true,
                  forceSelection: true,
                  showTrigger: true,
                  editorParams: {
                    AC: 'TRUE',
                    TRIGGER: 'TRUE',
                    PICKUPVIEW: 'FALSE',
                  },
                  editorType: 'PICKEREX_TRIGGER',
                  valueType: 'SIMPLE',
                  editable: true,
                  id: 'n_type_eq',
                },
                allowEmpty: true,
                caption: '类型(=)',
                codeName: 'n_type_eq',
                detailStyle: 'DEFAULT',
                detailType: 'FORMITEM',
                layoutPos: {
                  colLG: 12,
                  colMD: 12,
                  layout: 'TABLE_24COL',
                },
                showCaption: true,
                userTag: 'permanent',
                id: 'n_type_eq',
              },
              {
                layout: {
                  columnCount: 24,
                  layout: 'TABLE_24COL',
                },
                deformDetails: [
                  {
                    dataType: 6,
                    enableCond: 3,
                    labelPos: 'LEFT',
                    labelWidth: 100,
                    noPrivDisplayMode: 1,
                    appDEFieldId: 'quantity',
                    editor: {
                      editorType: 'TEXTBOX',
                      valueType: 'SIMPLE',
                      editable: true,
                      id: 'n_quantity_ltandeq',
                    },
                    allowEmpty: true,
                    caption: '数量',
                    codeName: 'n_quantity_ltandeq',
                    detailStyle: 'DEFAULT',
                    detailType: 'FORMITEM',
                    layoutPos: {
                      colLG: 12,
                      colMD: 12,
                      layout: 'TABLE_24COL',
                    },
                    showCaption: true,
                    id: 'n_quantity_ltandeq',
                  },
                  {
                    dataType: 9,
                    enableCond: 3,
                    labelPos: 'LEFT',
                    labelWidth: 100,
                    noPrivDisplayMode: 1,
                    appDEFieldId: 'status',
                    editor: {
                      singleSelect: true,
                      handlerType: 'PickupText',
                      enableAC: true,
                      forceSelection: true,
                      showTrigger: true,
                      editorParams: {
                        AC: 'TRUE',
                        TRIGGER: 'TRUE',
                        PICKUPVIEW: 'FALSE',
                      },
                      editorType: 'PICKEREX_TRIGGER',
                      valueType: 'SIMPLE',
                      editable: true,
                      id: 'n_status_eq',
                    },
                    allowEmpty: true,
                    caption: '状态',
                    codeName: 'n_status_eq',
                    detailStyle: 'DEFAULT',
                    detailType: 'FORMITEM',
                    layoutPos: {
                      colLG: 12,
                      colMD: 12,
                      layout: 'TABLE_24COL',
                    },
                    showCaption: true,
                    id: 'n_status_eq',
                  },
                ],
                codeName: 'grouppanel1',
                detailStyle: 'DEFAULT',
                detailType: 'GROUPPANEL',
                layoutPos: {
                  colLG: 24,
                  colMD: 24,
                  layout: 'TABLE_24COL',
                },
                id: 'grouppanel1',
              },
            ],
            caption: '常规条件',
            codeName: 'formpage1',
            detailStyle: 'DEFAULT',
            detailType: 'FORMPAGE',
            id: 'formpage1',
          },
        ],
        layout: {
          columnCount: 24,
          layout: 'TABLE_24COL',
        },
        tabHeaderPos: 'TOP',
        noTabHeader: true,
        autoLoad: true,
        showBusyIndicator: true,
        codeName: 'main17',
        controlType: 'SEARCHFORM',
        logicName: '搜索表单_高级搜索_搜索表单',
        appDataEntityId: 'web.master',
        controlLogics: [
          {
            eventNames: 'onSearch',
            logicTag: 'searchform',
            logicType: 'SCRIPT',
            scriptCode: 'util.message.info(data);',
            triggerType: 'CTRLEVENT',
            id: 'search_form_onsearch',
          },
        ],
        controlParam: {
          id: 'searchform',
        },
        modelId: '1bb58406e5c6c5e7a8e5fe332c814802',
        modelType: 'PSDEFORM_SEARCHFORM',
        name: 'searchform',
        id: 'web.master.main17',
      },
      {
        aggMode: 'NONE',
        columnEnableFilter: 2,
        columnEnableLink: 2,
        groupMode: 'NONE',
        groupStyle: 'DEFAULT',
        degridColumns: [
          {
            clconvertMode: 'NONE',
            dataItemName: 'name',
            excelCaption: '名称',
            appDEFieldId: 'name',
            valueType: 'SIMPLE',
            aggMode: 'NONE',
            align: 'LEFT',
            capLanguageRes: {
              lanResTag: 'DEF.LNAME.MASTER.NAME',
            },
            caption: '名称',
            codeName: 'name',
            columnType: 'DEFGRIDCOLUMN',
            noPrivDisplayMode: 1,
            width: 150,
            widthUnit: 'PX',
            enableSort: true,
            id: 'name',
          },
        ],
        degridDataItems: [
          {
            appDEFieldId: 'name',
            valueType: 'SIMPLE',
            dataType: 25,
            id: 'name',
          },
          {
            appDEFieldId: 'id',
            valueType: 'SIMPLE',
            dataType: 25,
            id: 'srfkey',
          },
          {
            appDEFieldId: 'id',
            valueType: 'SIMPLE',
            dataType: 25,
            id: 'srfdataaccaction',
          },
          {
            appDEFieldId: 'region_id',
            valueType: 'SIMPLE',
            dataType: 25,
            id: 'region_id',
          },
          {
            appDEFieldId: 'name',
            valueType: 'SIMPLE',
            dataType: 25,
            id: 'srfmajortext',
          },
        ],
        degridEditItems: [
          {
            caption: '标识',
            codeName: 'srfkey',
            enableCond: 3,
            appDEFieldId: 'id',
            editor: {
              editorType: 'HIDDEN',
              valueType: 'SIMPLE',
              editable: true,
              id: 'srfkey',
            },
            allowEmpty: true,
            id: 'srfkey',
          },
        ],
        pagingMode: 1,
        pagingSize: 10,
        sortMode: 'REMOTE',
        enableCustomized: true,
        enablePagingBar: true,
        navViewPos: 'NONE',
        fetchControlAction: {
          appDEMethodId: 'fetch_default',
          appDataEntityId: 'web.master',
          id: 'fetch',
        },
        removeControlAction: {
          appDEMethodId: 'remove',
          appDataEntityId: 'web.master',
          id: 'remove',
        },
        autoLoad: true,
        showBusyIndicator: true,
        codeName: 'main4',
        controlType: 'GRID',
        logicName: '搜索表单_高级搜索_表格',
        appDataEntityId: 'web.master',
        controlParam: {
          id: 'grid',
        },
        modelId: '041da0bcd89f343a9585df3453cfd3c3',
        modelType: 'PSDEGRID',
        name: 'grid',
        id: 'web.master.main4',
      },
      {
        xdataControlName: 'grid',
        codeName: 'searchform_advanced_toolbar',
        controlType: 'TOOLBAR',
        logicName: '搜索表单_高级搜索_工具栏',
        appDataEntityId: 'web.master',
        controlParam: {
          id: 'toolbar',
        },
        modelId: 'e6726a439d8bca15a11d9f66a45c93b0',
        modelType: 'PSDETOOLBAR',
        name: 'toolbar',
        id: 'searchform_advanced_toolbar',
      },
      {
        groupMode: 'SINGLE',
        controlType: 'SEARCHBAR',
        appDataEntityId: 'web.master',
        controlParam: {
          id: 'searchbar',
        },
        id: 'searchbar',
      },
      {
        capLanguageRes: {
          lanResTag: 'DE.LNAME.MASTER',
        },
        caption: '搜索表单_高级搜索',
        codeName: 'searchform_advanced_captionbar',
        controlType: 'CAPTIONBAR',
        appDataEntityId: 'web.master',
        controlParam: {},
        name: 'captionbar',
        id: 'searchform_advanced_captionbar',
      },
    ],
    codeName: 'usr0527766436',
    controlType: 'VIEWLAYOUTPANEL',
    logicName: 'searchform_advanced表格视图布局',
    appDataEntityId: 'web.master',
    controlParam: {},
    modelId: 'fa69af31d1c9f92c6ec2bb548ce1e2a8',
    modelType: 'PSSYSVIEWLAYOUTPANEL',
    name: 'layoutpanel',
    id: 'usr0527766436',
  },
  title: '搜索表单_高级搜索',
  viewStyle: 'DEFAULT',
  viewType: 'DEGRIDVIEW',
  enableDP: true,
  showCaptionBar: false,
  modelId: '01f31b0c225130d93d62d956ee2698ad',
  modelType: 'PSAPPDEVIEW',
  name: 'MASTERsearchform_advanced',
  id: 'web.master_searchform_advanced',
};
