export default {
  openMode: 'INDEXVIEWTAB_POPUPMODAL',
  deviewCodeName: 'design_Modal',
  deviewId: '8f29be30ad335cb3a28a0f14ed7f8e57',
  accUserMode: 2,
  caption: '表单设计',
  codeName: 'psdeformdesign_modal',
  height: 90,
  appDataEntityId: 'web.psdeform',
  controls: [
    {
      caption: '表单设计',
      codeName: 'design_modal_captionbar',
      controlType: 'CAPTIONBAR',
      appDataEntityId: 'web.psdeform',
      controlParam: {},
      name: 'captionbar',
      id: 'design_modal_captionbar',
    },
  ],
  viewLayoutPanel: {
    layoutBodyOnly: true,
    useDefaultLayout: true,
    layoutPanel: true,
    codeName: 'layoutpanel',
    controlStyle: 'APPDESUBAPPREFVIEW',
    controlType: 'VIEWLAYOUTPANEL',
    appDataEntityId: 'web.psdeform',
    controlParam: {},
    id: 'layoutpanel',
  },
  priority: 90,
  title: '表单设计',
  viewStyle: 'DEFAULT',
  viewType: 'DESUBAPPREFVIEW',
  width: 90,
  enableDP: true,
  showCaptionBar: true,
  modelId: 'd2b06cade4752bda6779eb1df7336094',
  modelType: 'PSAPPDEVIEW',
  name: 'psdeformdesign_modal',
  id: 'web.psdeformdesign_modal',
};
