export default {
  gridRowActiveMode: 2,
  expandSearchForm: true,
  pickupMode: true,
  xdataControlName: 'grid',
  loadDefault: true,
  deviewCodeName: 'PickupGridView',
  deviewId: 'd0bf32603c61422a75dce2454aff910c',
  accUserMode: 3,
  capLanguageRes: {
    lanResTag: 'DE.LNAME.REGION',
  },
  caption: '区划选择表格视图',
  codeName: 'region_pickup_grid_view',
  appDataEntityId: 'web.region',
  appViewEngines: [
    {
      engineCat: 'VIEW',
      engineType: 'PickupGridView',
      id: 'engine',
    },
  ],
  appViewMsgGroupId: 'pickupgridview',
  controls: [
    {
      aggMode: 'NONE',
      columnEnableFilter: 2,
      columnEnableLink: 2,
      groupMode: 'NONE',
      groupStyle: 'DEFAULT',
      degridColumns: [
        {
          clconvertMode: 'NONE',
          dataItemName: 'code',
          excelCaption: '编码',
          appDEFieldId: 'code',
          valueType: 'SIMPLE',
          aggMode: 'NONE',
          align: 'LEFT',
          caption: '编码',
          codeName: 'code',
          columnType: 'DEFGRIDCOLUMN',
          noPrivDisplayMode: 1,
          width: 150,
          widthUnit: 'PX',
          enableSort: true,
          id: 'code',
        },
        {
          clconvertMode: 'NONE',
          dataItemName: 'name',
          excelCaption: '名称',
          appDEFieldId: 'name',
          valueType: 'SIMPLE',
          enableRowEdit: true,
          aggMode: 'NONE',
          align: 'LEFT',
          capLanguageRes: {
            lanResTag: 'DEF.LNAME.REGION.NAME',
          },
          caption: '名称',
          codeName: 'name',
          columnType: 'DEFGRIDCOLUMN',
          noPrivDisplayMode: 1,
          width: 200,
          widthUnit: 'PX',
          enableSort: true,
          id: 'name',
        },
        {
          clconvertMode: 'NONE',
          dataItemName: 'parent_name',
          excelCaption: '上级区划',
          linkAppViewId: 'web.region_redirect_view',
          linkValueItem: 'parent_id',
          appDEFieldId: 'parent_name',
          valueType: 'SIMPLE',
          enableLinkView: true,
          enableRowEdit: true,
          aggMode: 'NONE',
          align: 'LEFT',
          caption: '上级区划',
          codeName: 'parent_name',
          columnType: 'DEFGRIDCOLUMN',
          noPrivDisplayMode: 1,
          width: 200,
          widthUnit: 'PX',
          enableSort: true,
          id: 'parent_name',
        },
        {
          clconvertMode: 'NONE',
          dataItemName: 'level',
          excelCaption: '级别',
          appDEFieldId: 'level',
          valueType: 'SIMPLE',
          enableRowEdit: true,
          aggMode: 'NONE',
          align: 'LEFT',
          caption: '级别',
          codeName: 'level',
          columnType: 'DEFGRIDCOLUMN',
          noPrivDisplayMode: 1,
          width: 100,
          widthUnit: 'PX',
          enableSort: true,
          id: 'level',
        },
        {
          clconvertMode: 'FRONT',
          dataItemName: 'status',
          excelCaption: '状态',
          appCodeListId: 'web.mock__cl_status',
          appDEFieldId: 'status',
          valueType: 'SIMPLE',
          enableRowEdit: true,
          aggMode: 'NONE',
          align: 'LEFT',
          caption: '状态',
          codeName: 'status',
          columnType: 'DEFGRIDCOLUMN',
          noPrivDisplayMode: 1,
          width: 150,
          widthUnit: 'PX',
          enableSort: true,
          id: 'status',
        },
        {
          clconvertMode: 'NONE',
          dataItemName: 'path',
          excelCaption: '全路径',
          appDEFieldId: 'path',
          valueType: 'SIMPLE',
          enableRowEdit: true,
          aggMode: 'NONE',
          align: 'LEFT',
          caption: '全路径',
          codeName: 'path',
          columnType: 'DEFGRIDCOLUMN',
          noPrivDisplayMode: 1,
          width: 300,
          widthUnit: 'PX',
          enableSort: true,
          id: 'path',
        },
        {
          clconvertMode: 'NONE',
          dataItemName: 'sort',
          excelCaption: '排序',
          appDEFieldId: 'sort',
          valueType: 'SIMPLE',
          enableRowEdit: true,
          aggMode: 'NONE',
          align: 'LEFT',
          caption: '排序',
          codeName: 'sort',
          columnType: 'DEFGRIDCOLUMN',
          noPrivDisplayMode: 1,
          width: 100,
          widthUnit: 'PX',
          enableSort: true,
          id: 'sort',
        },
        {
          clconvertMode: 'NONE',
          dataItemName: 'longitude',
          excelCaption: '经度',
          appDEFieldId: 'longitude',
          valueType: 'SIMPLE',
          enableRowEdit: true,
          aggMode: 'NONE',
          align: 'LEFT',
          caption: '经度',
          codeName: 'longitude',
          columnType: 'DEFGRIDCOLUMN',
          noPrivDisplayMode: 1,
          width: 100,
          widthUnit: 'PX',
          enableSort: true,
          id: 'longitude',
        },
        {
          clconvertMode: 'NONE',
          dataItemName: 'latitude',
          excelCaption: '纬度',
          appDEFieldId: 'latitude',
          valueType: 'SIMPLE',
          enableRowEdit: true,
          aggMode: 'NONE',
          align: 'LEFT',
          caption: '纬度',
          codeName: 'latitude',
          columnType: 'DEFGRIDCOLUMN',
          noPrivDisplayMode: 1,
          width: 100,
          widthUnit: 'PX',
          enableSort: true,
          id: 'latitude',
        },
        {
          clconvertMode: 'NONE',
          dataItemName: 'update_time',
          excelCaption: '更新时间',
          appDEFieldId: 'update_time',
          valueFormat: 'YYYY-MM-DD HH:mm:ss',
          valueType: 'SIMPLE',
          aggMode: 'NONE',
          align: 'LEFT',
          capLanguageRes: {
            lanResTag: 'DEF.LNAME.UPDATE_TIME',
          },
          caption: '更新时间',
          codeName: 'update_time',
          columnType: 'DEFGRIDCOLUMN',
          noPrivDisplayMode: 1,
          width: 200,
          widthUnit: 'PX',
          enableSort: true,
          id: 'update_time',
        },
        {
          clconvertMode: 'NONE',
          dataItemName: 'create_time',
          excelCaption: '创建时间',
          appDEFieldId: 'create_time',
          valueFormat: 'YYYY-MM-DD HH:mm:ss',
          valueType: 'SIMPLE',
          aggMode: 'NONE',
          align: 'LEFT',
          capLanguageRes: {
            lanResTag: 'DEF.LNAME.REGION.CREATE_TIME',
          },
          caption: '创建时间',
          codeName: 'create_time',
          columnType: 'DEFGRIDCOLUMN',
          noPrivDisplayMode: 1,
          width: 200,
          widthUnit: 'PX',
          enableSort: true,
          id: 'create_time',
        },
      ],
      degridDataItems: [
        {
          appDEFieldId: 'code',
          valueType: 'SIMPLE',
          dataType: 25,
          id: 'code',
        },
        {
          appDEFieldId: 'name',
          valueType: 'SIMPLE',
          dataType: 25,
          id: 'name',
        },
        {
          appDEFieldId: 'parent_name',
          valueType: 'SIMPLE',
          dataType: 25,
          id: 'parent_name',
        },
        {
          appDEFieldId: 'level',
          valueType: 'SIMPLE',
          dataType: 9,
          id: 'level',
        },
        {
          appDEFieldId: 'status',
          valueType: 'SIMPLE',
          dataType: 9,
          id: 'status',
        },
        {
          appDEFieldId: 'path',
          valueType: 'SIMPLE',
          dataType: 25,
          id: 'path',
        },
        {
          appDEFieldId: 'sort',
          valueType: 'SIMPLE',
          dataType: 9,
          id: 'sort',
        },
        {
          appDEFieldId: 'longitude',
          valueType: 'SIMPLE',
          dataType: 29,
          id: 'longitude',
        },
        {
          appDEFieldId: 'latitude',
          valueType: 'SIMPLE',
          dataType: 29,
          id: 'latitude',
        },
        {
          format: 'YYYY-MM-DD HH:mm:ss',
          appDEFieldId: 'update_time',
          valueType: 'SIMPLE',
          dataType: 5,
          id: 'update_time',
        },
        {
          format: 'YYYY-MM-DD HH:mm:ss',
          appDEFieldId: 'create_time',
          valueType: 'SIMPLE',
          dataType: 5,
          id: 'create_time',
        },
        {
          appDEFieldId: 'id',
          valueType: 'SIMPLE',
          dataType: 25,
          id: 'srfkey',
        },
        {
          appDEFieldId: 'id',
          valueType: 'SIMPLE',
          dataType: 25,
          id: 'srfdataaccaction',
        },
        {
          appDEFieldId: 'parent_id',
          valueType: 'SIMPLE',
          dataType: 25,
          id: 'parent_id',
        },
        {
          appDEFieldId: 'name',
          valueType: 'SIMPLE',
          dataType: 25,
          id: 'srfmajortext',
        },
      ],
      degridEditItems: [
        {
          caption: '名称',
          codeName: 'name',
          enableCond: 3,
          appDEFieldId: 'name',
          editor: {
            maxLength: 200,
            editorType: 'TEXTBOX',
            valueType: 'SIMPLE',
            editable: true,
            id: 'name',
          },
          allowEmpty: true,
          id: 'name',
        },
        {
          caption: '上级区划',
          codeName: 'parent_name',
          enableCond: 3,
          appDEFieldId: 'parent_name',
          editor: {
            enablePickupView: true,
            singleSelect: true,
            appDEACModeId: 'default',
            appDEDataSetId: 'fetch_default',
            appDataEntityId: 'web.region',
            enableAC: true,
            forceSelection: true,
            showTrigger: true,
            valueItemName: 'parent_id',
            editorParams: {
              AC: 'TRUE',
              PICKUPVIEW: 'TRUE',
            },
            editorType: 'PICKER',
            editorItems: [{}],
            valueType: 'SIMPLE',
            editable: true,
            id: 'parent_name',
          },
          allowEmpty: true,
          id: 'parent_name',
        },
        {
          caption: '级别',
          codeName: 'level',
          enableCond: 3,
          appDEFieldId: 'level',
          editor: {
            editorType: 'TEXTBOX',
            valueType: 'SIMPLE',
            editable: true,
            id: 'level',
          },
          allowEmpty: true,
          id: 'level',
        },
        {
          caption: '状态',
          codeName: 'status',
          enableCond: 3,
          appDEFieldId: 'status',
          editor: {
            singleSelect: true,
            appCodeListId: 'web.mock__cl_status',
            editorType: 'DROPDOWNLIST',
            valueType: 'SIMPLE',
            editable: true,
            id: 'status',
          },
          allowEmpty: true,
          needCodeListConfig: true,
          id: 'status',
        },
        {
          caption: '全路径',
          codeName: 'path',
          enableCond: 3,
          appDEFieldId: 'path',
          editor: {
            maxLength: 500,
            editorType: 'TEXTBOX',
            valueType: 'SIMPLE',
            editable: true,
            id: 'path',
          },
          allowEmpty: true,
          id: 'path',
        },
        {
          caption: '排序',
          codeName: 'sort',
          enableCond: 3,
          appDEFieldId: 'sort',
          editor: {
            editorType: 'TEXTBOX',
            valueType: 'SIMPLE',
            editable: true,
            id: 'sort',
          },
          allowEmpty: true,
          id: 'sort',
        },
        {
          caption: '经度',
          codeName: 'longitude',
          enableCond: 3,
          appDEFieldId: 'longitude',
          editor: {
            editorType: 'TEXTBOX',
            valueType: 'SIMPLE',
            editable: true,
            id: 'longitude',
          },
          allowEmpty: true,
          id: 'longitude',
        },
        {
          caption: '纬度',
          codeName: 'latitude',
          enableCond: 3,
          appDEFieldId: 'latitude',
          editor: {
            editorType: 'TEXTBOX',
            valueType: 'SIMPLE',
            editable: true,
            id: 'latitude',
          },
          allowEmpty: true,
          id: 'latitude',
        },
        {
          caption: '标识',
          codeName: 'srfkey',
          enableCond: 3,
          appDEFieldId: 'id',
          editor: {
            editorType: 'HIDDEN',
            valueType: 'SIMPLE',
            editable: true,
            id: 'srfkey',
          },
          allowEmpty: true,
          id: 'srfkey',
        },
        {
          enableCond: 3,
          appDEFieldId: 'parent_id',
          editor: {
            editorType: 'HIDDEN',
            valueType: 'SIMPLE',
            editable: true,
          },
          allowEmpty: true,
          id: 'parent_id',
        },
      ],
      pagingMode: 1,
      pagingSize: 20,
      sortMode: 'REMOTE',
      enableCustomized: true,
      enablePagingBar: true,
      navViewPos: 'NONE',
      fetchControlAction: {
        appDEMethodId: 'fetch_default',
        appDataEntityId: 'web.region',
        id: 'fetch',
      },
      removeControlAction: {
        appDEMethodId: 'remove',
        appDataEntityId: 'web.region',
        id: 'remove',
      },
      autoLoad: true,
      showBusyIndicator: true,
      codeName: 'grid_pickup',
      controlType: 'GRID',
      logicName: '选择表格',
      appDataEntityId: 'web.region',
      controlParam: {
        id: 'grid',
      },
      modelId: '33f8a6aaa2c3f9a65580e339a6ccf3a4',
      modelType: 'PSDEGRID',
      name: 'grid',
      id: 'web.region.grid_pickup',
    },
    {
      searchButtonStyle: 'DEFAULT',
      deformPages: [
        {
          layout: {
            columnCount: 24,
            layout: 'TABLE_24COL',
          },
          deformDetails: [
            {
              dataType: 25,
              enableCond: 3,
              labelPos: 'LEFT',
              labelWidth: 130,
              noPrivDisplayMode: 1,
              appDEFieldId: 'name',
              editor: {
                editorType: 'TEXTBOX',
                valueType: 'SIMPLE',
                editable: true,
                id: 'n_name_like',
              },
              allowEmpty: true,
              capLanguageRes: {
                lanResTag: 'CONTROL.DEFSFITEM.REGION.N_NAME_LIKE',
              },
              caption: '名称(%)',
              codeName: 'n_name_like',
              detailStyle: 'DEFAULT',
              detailType: 'FORMITEM',
              layoutPos: {
                colLG: 8,
                colMD: 8,
                layout: 'TABLE_24COL',
              },
              showCaption: true,
              id: 'n_name_like',
            },
            {
              dataType: 25,
              enableCond: 3,
              labelPos: 'LEFT',
              labelWidth: 130,
              noPrivDisplayMode: 1,
              appDEFieldId: 'code',
              editor: {
                editorType: 'TEXTBOX',
                valueType: 'SIMPLE',
                editable: true,
                id: 'n_code_like',
              },
              allowEmpty: true,
              caption: '编码(%)',
              codeName: 'n_code_like',
              detailStyle: 'DEFAULT',
              detailType: 'FORMITEM',
              layoutPos: {
                colLG: 8,
                colMD: 8,
                layout: 'TABLE_24COL',
              },
              showCaption: true,
              id: 'n_code_like',
            },
            {
              dataType: 25,
              enableCond: 3,
              labelPos: 'LEFT',
              labelWidth: 130,
              noPrivDisplayMode: 1,
              appDEFieldId: 'parent_name',
              editor: {
                enablePickupView: true,
                singleSelect: true,
                pickupAppViewId: 'web.region_pickup_view',
                handlerType: 'PickupText',
                appDEACModeId: 'default',
                appDEDataSetId: 'fetch_default',
                appDataEntityId: 'web.region',
                enableAC: true,
                forceSelection: true,
                showTrigger: true,
                valueItemName: 'n_parent_id_eq',
                editorParams: {
                  AC: 'TRUE',
                  PICKUPVIEW: 'TRUE',
                },
                editorType: 'PICKER',
                editorItems: [
                  {
                    id: 'n_parent_id_eq',
                  },
                ],
                valueType: 'SIMPLE',
                editable: true,
                id: 'n_parent_name_eq',
              },
              allowEmpty: true,
              caption: '上级区划(=)',
              codeName: 'n_parent_name_eq',
              detailStyle: 'DEFAULT',
              detailType: 'FORMITEM',
              layoutPos: {
                colLG: 8,
                colMD: 8,
                layout: 'TABLE_24COL',
              },
              showCaption: true,
              id: 'n_parent_name_eq',
            },
            {
              dataType: 25,
              enableCond: 3,
              labelPos: 'LEFT',
              labelWidth: 130,
              noPrivDisplayMode: 1,
              appDEFieldId: 'parent_id',
              editor: {
                editorType: 'HIDDEN',
                valueType: 'SIMPLE',
                editable: true,
                id: 'n_parent_id_eq',
              },
              allowEmpty: true,
              hidden: true,
              caption: '上级区划标识(=)',
              codeName: 'n_parent_id_eq',
              detailStyle: 'DEFAULT',
              detailType: 'FORMITEM',
              layoutPos: {
                colLG: 8,
                colMD: 8,
                layout: 'TABLE_24COL',
              },
              id: 'n_parent_id_eq',
            },
            {
              dataType: 9,
              enableCond: 3,
              labelPos: 'LEFT',
              labelWidth: 130,
              noPrivDisplayMode: 1,
              appDEFieldId: 'status',
              editor: {
                singleSelect: true,
                appCodeListId: 'web.mock__cl_status',
                editorType: 'DROPDOWNLIST',
                valueType: 'SIMPLE',
                editable: true,
                id: 'n_status_eq',
              },
              allowEmpty: true,
              needCodeListConfig: true,
              caption: '状态(=)',
              codeName: 'n_status_eq',
              detailStyle: 'DEFAULT',
              detailType: 'FORMITEM',
              layoutPos: {
                colLG: 8,
                colMD: 8,
                layout: 'TABLE_24COL',
              },
              showCaption: true,
              id: 'n_status_eq',
            },
            {
              dataType: 25,
              enableCond: 3,
              labelPos: 'LEFT',
              labelWidth: 130,
              noPrivDisplayMode: 1,
              editor: {
                editorType: 'NUMBERRANGE',
                valueType: 'SIMPLE',
                editable: true,
                id: 'level',
              },
              allowEmpty: true,
              caption: '级别',
              codeName: 'level',
              detailStyle: 'DEFAULT',
              detailType: 'FORMITEM',
              layoutPos: {
                colLG: 8,
                colMD: 8,
                layout: 'TABLE_24COL',
              },
              showCaption: true,
              id: 'level',
            },
          ],
          capLanguageRes: {
            lanResTag: 'CONTROL.DEFORM.REGION.DEFAULT.FORMPAGE.FORMPAGE1',
          },
          caption: '常规条件',
          codeName: 'formpage1',
          detailStyle: 'DEFAULT',
          detailType: 'FORMPAGE',
          id: 'formpage1',
        },
      ],
      layout: {
        columnCount: 24,
        layout: 'TABLE_24COL',
      },
      tabHeaderPos: 'TOP',
      noTabHeader: true,
      autoLoad: true,
      showBusyIndicator: true,
      codeName: 'default',
      controlType: 'SEARCHFORM',
      logicName: '默认搜索表单',
      appDataEntityId: 'web.region',
      controlParam: {
        id: 'searchform',
      },
      modelId: '3dc9ea359ce488ec65b7253220f11dd6',
      modelType: 'PSDEFORM_SEARCHFORM',
      name: 'searchform',
      id: 'web.region.default',
    },
    {
      groupMode: 'SINGLE',
      controlType: 'SEARCHBAR',
      appDataEntityId: 'web.region',
      controlParam: {
        id: 'searchbar',
      },
      id: 'searchbar',
    },
    {
      capLanguageRes: {
        lanResTag: 'DE.LNAME.REGION',
      },
      caption: '区划选择表格视图',
      codeName: 'pickup_grid_view_captionbar',
      controlType: 'CAPTIONBAR',
      appDataEntityId: 'web.region',
      controlParam: {},
      name: 'captionbar',
      id: 'pickup_grid_view_captionbar',
    },
  ],
  viewLayoutPanel: {
    layoutBodyOnly: true,
    useDefaultLayout: true,
    layoutPanel: true,
    codeName: 'layoutpanel',
    controlStyle: 'APPDEPICKUPGRIDVIEW',
    controlType: 'VIEWLAYOUTPANEL',
    appDataEntityId: 'web.region',
    controlParam: {},
    id: 'layoutpanel',
  },
  title: '区划选择表格视图',
  viewStyle: 'DEFAULT',
  viewType: 'DEPICKUPGRIDVIEW',
  enableDP: true,
  showCaptionBar: true,
  modelId: 'a2b166a16b0ec9d02ba0b57abbd45656',
  modelType: 'PSAPPDEVIEW',
  name: 'REGIONPickupGridView',
  id: 'web.region_pickup_grid_view',
};
