export default {
  enableDirtyChecking: true,
  showDataInfoBar: true,
  xdataControlName: 'form',
  loadDefault: true,
  deviewCodeName: 'sedit_view9',
  deviewId: 'a92b050ae3519d5b5ede0c4a87c55757',
  accUserMode: 2,
  capLanguageRes: {
    lanResTag: 'DE.LNAME.REGION',
  },
  caption: '编辑视图',
  codeName: 'region_sedit_view9',
  appDataEntityId: 'web.region',
  appViewEngines: [
    {
      engineCat: 'VIEW',
      engineType: 'EditView',
      id: 'engine',
    },
  ],
  appViewNavContexts: [
    {
      rawValue: true,
      key: 'REGION',
      value: '86',
      name: 'REGION',
      id: 'region',
    },
  ],
  controls: [
    {
      xdataControlName: 'form',
      codeName: 'sedit_view9_toolbar',
      controlType: 'TOOLBAR',
      logicName: '编辑视图（用于嵌入多编辑）_工具栏',
      appDataEntityId: 'web.region',
      controlParam: {
        id: 'toolbar',
      },
      modelId: '084c37b92e983a477a325b3ee40832ff',
      modelType: 'PSDETOOLBAR',
      name: 'toolbar',
      id: 'sedit_view9_toolbar',
    },
    {
      createControlAction: {
        appDEMethodId: 'create',
        appDataEntityId: 'web.region',
        id: 'create',
      },
      getDraftFromControlAction: {
        appDataEntityId: 'web.region',
        id: 'loaddraftfrom',
      },
      getDraftControlAction: {
        appDEMethodId: 'get_draft',
        appDataEntityId: 'web.region',
        id: 'loaddraft',
      },
      getControlAction: {
        appDEMethodId: 'get',
        appDataEntityId: 'web.region',
        id: 'load',
      },
      removeControlAction: {
        appDEMethodId: 'remove',
        appDataEntityId: 'web.region',
        id: 'remove',
      },
      updateControlAction: {
        appDEMethodId: 'update',
        appDataEntityId: 'web.region',
        id: 'update',
      },
      deformPages: [
        {
          layout: {
            columnCount: 24,
            layout: 'TABLE_24COL',
          },
          deformDetails: [
            {
              layout: {
                columnCount: 24,
                layout: 'TABLE_24COL',
              },
              deformDetails: [
                {
                  dataType: 25,
                  enableCond: 3,
                  labelPos: 'LEFT',
                  labelWidth: 130,
                  noPrivDisplayMode: 1,
                  appDEFieldId: 'id',
                  editor: {
                    editorType: 'HIDDEN',
                    valueType: 'SIMPLE',
                    editable: true,
                    id: 'id',
                  },
                  allowEmpty: true,
                  hidden: true,
                  capLanguageRes: {
                    lanResTag: 'DEF.LNAME.REGION.ID',
                  },
                  caption: '标识',
                  codeName: 'id',
                  detailStyle: 'DEFAULT',
                  detailType: 'FORMITEM',
                  layoutPos: {
                    colLG: 12,
                    colMD: 12,
                    layout: 'TABLE_24COL',
                  },
                  id: 'id',
                },
                {
                  dataType: 25,
                  enableCond: 1,
                  labelPos: 'LEFT',
                  labelWidth: 130,
                  noPrivDisplayMode: 1,
                  appDEFieldId: 'code',
                  editor: {
                    halign: 'LEFT',
                    valign: 'MIDDLE',
                    wrapMode: 'NOWRAP',
                    editorType: 'SPAN',
                    valueType: 'SIMPLE',
                    editable: true,
                    id: 'code',
                  },
                  allowEmpty: true,
                  caption: '编码',
                  codeName: 'code',
                  detailStyle: 'DEFAULT',
                  detailType: 'FORMITEM',
                  layoutPos: {
                    colLG: 12,
                    colMD: 12,
                    layout: 'TABLE_24COL',
                  },
                  showCaption: true,
                  id: 'code',
                },
                {
                  dataType: 25,
                  enableCond: 3,
                  labelPos: 'LEFT',
                  labelWidth: 130,
                  noPrivDisplayMode: 1,
                  appDEFieldId: 'name',
                  editor: {
                    halign: 'LEFT',
                    valign: 'MIDDLE',
                    wrapMode: 'NOWRAP',
                    editorType: 'SPAN',
                    valueType: 'SIMPLE',
                    editable: true,
                    id: 'name',
                  },
                  allowEmpty: true,
                  capLanguageRes: {
                    lanResTag: 'DEF.LNAME.REGION.NAME',
                  },
                  caption: '名称',
                  codeName: 'name',
                  detailStyle: 'DEFAULT',
                  detailType: 'FORMITEM',
                  layoutPos: {
                    colLG: 12,
                    colMD: 12,
                    layout: 'TABLE_24COL',
                  },
                  showCaption: true,
                  id: 'name',
                },
                {
                  dataType: 9,
                  enableCond: 3,
                  labelPos: 'LEFT',
                  labelWidth: 130,
                  noPrivDisplayMode: 1,
                  appDEFieldId: 'level',
                  editor: {
                    halign: 'LEFT',
                    valign: 'MIDDLE',
                    wrapMode: 'NOWRAP',
                    editorType: 'SPAN',
                    valueType: 'SIMPLE',
                    editable: true,
                    id: 'level',
                  },
                  allowEmpty: true,
                  caption: '级别',
                  codeName: 'level',
                  detailStyle: 'DEFAULT',
                  detailType: 'FORMITEM',
                  layoutPos: {
                    colLG: 12,
                    colMD: 12,
                    layout: 'TABLE_24COL',
                  },
                  showCaption: true,
                  id: 'level',
                },
                {
                  dataType: 25,
                  enableCond: 3,
                  labelPos: 'LEFT',
                  labelWidth: 130,
                  noPrivDisplayMode: 1,
                  appDEFieldId: 'parent_name',
                  editor: {
                    halign: 'LEFT',
                    valign: 'MIDDLE',
                    wrapMode: 'NOWRAP',
                    editorType: 'SPAN',
                    valueType: 'SIMPLE',
                    editable: true,
                    id: 'parent_name',
                  },
                  allowEmpty: true,
                  caption: '上级区划',
                  codeName: 'parent_name',
                  detailStyle: 'DEFAULT',
                  detailType: 'FORMITEM',
                  layoutPos: {
                    colLG: 12,
                    colMD: 12,
                    layout: 'TABLE_24COL',
                  },
                  showCaption: true,
                  id: 'parent_name',
                },
                {
                  dataType: 25,
                  enableCond: 3,
                  labelPos: 'LEFT',
                  labelWidth: 130,
                  noPrivDisplayMode: 1,
                  appDEFieldId: 'path',
                  editor: {
                    halign: 'LEFT',
                    valign: 'MIDDLE',
                    wrapMode: 'NOWRAP',
                    editorType: 'SPAN',
                    valueType: 'SIMPLE',
                    editable: true,
                    id: 'path',
                  },
                  allowEmpty: true,
                  caption: '全路径',
                  codeName: 'path',
                  detailStyle: 'DEFAULT',
                  detailType: 'FORMITEM',
                  layoutPos: {
                    colLG: 12,
                    colMD: 12,
                    layout: 'TABLE_24COL',
                  },
                  showCaption: true,
                  id: 'path',
                },
                {
                  dataType: 25,
                  enableCond: 3,
                  ignoreInput: 3,
                  labelPos: 'LEFT',
                  labelWidth: 130,
                  noPrivDisplayMode: 1,
                  appDEFieldId: 'status',
                  editor: {
                    halign: 'LEFT',
                    valign: 'MIDDLE',
                    wrapMode: 'NOWRAP',
                    appCodeListId: 'web.mock__cl_status',
                    editorType: 'SPAN',
                    valueType: 'SIMPLE',
                    editable: true,
                    id: 'status',
                  },
                  allowEmpty: true,
                  convertToCodeItemText: true,
                  caption: '状态',
                  codeName: 'status',
                  detailStyle: 'DEFAULT',
                  detailType: 'FORMITEM',
                  layoutPos: {
                    colLG: 12,
                    colMD: 12,
                    layout: 'TABLE_24COL',
                  },
                  showCaption: true,
                  id: 'status',
                },
                {
                  dataType: 9,
                  enableCond: 3,
                  labelPos: 'LEFT',
                  labelWidth: 130,
                  noPrivDisplayMode: 1,
                  appDEFieldId: 'sort',
                  editor: {
                    halign: 'LEFT',
                    valign: 'MIDDLE',
                    wrapMode: 'NOWRAP',
                    editorType: 'SPAN',
                    valueType: 'SIMPLE',
                    editable: true,
                    id: 'sort',
                  },
                  allowEmpty: true,
                  caption: '排序',
                  codeName: 'sort',
                  detailStyle: 'DEFAULT',
                  detailType: 'FORMITEM',
                  layoutPos: {
                    colLG: 12,
                    colMD: 12,
                    layout: 'TABLE_24COL',
                  },
                  showCaption: true,
                  id: 'sort',
                },
                {
                  dataType: 29,
                  enableCond: 3,
                  labelPos: 'LEFT',
                  labelWidth: 130,
                  noPrivDisplayMode: 1,
                  appDEFieldId: 'longitude',
                  editor: {
                    halign: 'LEFT',
                    valign: 'MIDDLE',
                    wrapMode: 'NOWRAP',
                    editorType: 'SPAN',
                    valueType: 'SIMPLE',
                    editable: true,
                    id: 'longitude',
                  },
                  allowEmpty: true,
                  caption: '经度',
                  codeName: 'longitude',
                  detailStyle: 'DEFAULT',
                  detailType: 'FORMITEM',
                  layoutPos: {
                    colLG: 12,
                    colMD: 12,
                    layout: 'TABLE_24COL',
                  },
                  showCaption: true,
                  id: 'longitude',
                },
                {
                  dataType: 29,
                  enableCond: 3,
                  labelPos: 'LEFT',
                  labelWidth: 130,
                  noPrivDisplayMode: 1,
                  appDEFieldId: 'latitude',
                  editor: {
                    halign: 'LEFT',
                    valign: 'MIDDLE',
                    wrapMode: 'NOWRAP',
                    editorType: 'SPAN',
                    valueType: 'SIMPLE',
                    editable: true,
                    id: 'latitude',
                  },
                  allowEmpty: true,
                  caption: '纬度',
                  codeName: 'latitude',
                  detailStyle: 'DEFAULT',
                  detailType: 'FORMITEM',
                  layoutPos: {
                    colLG: 12,
                    colMD: 12,
                    layout: 'TABLE_24COL',
                  },
                  showCaption: true,
                  id: 'latitude',
                },
              ],
              capLanguageRes: {
                lanResTag: 'CONTROL.DEFORM.REGION.MAIN.GROUPPANEL.GROUP1',
              },
              caption: '区划基本信息',
              codeName: 'group1',
              detailStyle: 'DEFAULT',
              detailType: 'GROUPPANEL',
              layoutPos: {
                colMD: 24,
                layout: 'TABLE_24COL',
              },
              id: 'group1',
            },
            {
              appViewId: 'web.region_medit_view9',
              parentDataJO: {
                SRFPARENTTYPE: 'DER1N',
                srfparentdename: 'REGION',
                srfparentmode: 'DER1N_REGION_REGION_PARENT_ID',
                srfparentdefname: 'PARENT_ID',
                SRFDER1NID: 'DER1N_REGION_REGION_PARENT_ID',
              },
              caption: '多表单编辑视图',
              codeName: 'druipart1',
              detailStyle: 'DEFAULT',
              detailType: 'DRUIPART',
              layoutPos: {
                colMD: 24,
                layout: 'TABLE_24COL',
              },
              showCaption: true,
              id: 'druipart1',
            },
          ],
          capLanguageRes: {
            lanResTag: 'CONTROL.DEFORM.REGION.MAIN.FORMPAGE.FORMPAGE1',
          },
          caption: '基本信息',
          codeName: 'formpage1',
          detailStyle: 'DEFAULT',
          detailType: 'FORMPAGE',
          id: 'formpage1',
        },
      ],
      layout: {
        columnCount: 24,
        layout: 'TABLE_24COL',
      },
      tabHeaderPos: 'TOP',
      noTabHeader: true,
      autoLoad: true,
      showBusyIndicator: true,
      codeName: 'main3',
      controlType: 'FORM',
      logicName: '编辑视图（用于嵌入多编辑）_表单',
      appDataEntityId: 'web.region',
      controlParam: {
        id: 'form',
      },
      modelId: '0ba70fa8a9948551abbc0c9fb1254808',
      modelType: 'PSDEFORM_EDITFORM',
      name: 'form',
      id: 'web.region.main3',
    },
    {
      codeName: 'sedit_view9_datainfobar',
      controlType: 'DATAINFOBAR',
      appDataEntityId: 'web.region',
      controlParam: {
        id: 'datainfobar',
      },
      name: 'datainfobar',
      id: 'sedit_view9_datainfobar',
    },
    {
      capLanguageRes: {
        lanResTag: 'DE.LNAME.REGION',
      },
      caption: '编辑视图',
      codeName: 'sedit_view9_captionbar',
      controlType: 'CAPTIONBAR',
      appDataEntityId: 'web.region',
      controlParam: {},
      name: 'captionbar',
      id: 'sedit_view9_captionbar',
    },
  ],
  viewLayoutPanel: {
    layoutBodyOnly: true,
    useDefaultLayout: true,
    layoutPanel: true,
    codeName: 'layoutpanel',
    controlStyle: 'APPDEEDITVIEW',
    controlType: 'VIEWLAYOUTPANEL',
    appDataEntityId: 'web.region',
    controlParam: {},
    id: 'layoutpanel',
  },
  title: '编辑视图',
  viewStyle: 'DEFAULT',
  viewType: 'DEEDITVIEW',
  enableDP: true,
  showCaptionBar: true,
  modelId: 'db954ed6d912c607fb7f6b022fa26798',
  modelType: 'PSAPPDEVIEW',
  name: 'REGIONsedit_view9',
  id: 'web.region_sedit_view9',
};
