export default {
  gridRowActiveMode: 2,
  xdataControlName: 'grid',
  loadDefault: true,
  deviewCodeName: 'grid_nav',
  deviewId: '708e29b6224205e56453f9b487adf305',
  accUserMode: 2,
  capLanguageRes: {
    lanResTag: 'DE.LNAME.REGION',
  },
  caption: '表格导航',
  codeName: 'region_grid_nav',
  appDataEntityId: 'web.region',
  appViewMsgGroupId: 'grid_nav',
  viewLayoutPanel: {
    viewProxyMode: true,
    layoutMode: 'FLEX',
    layout: {
      layout: 'FLEX',
    },
    rootPanelItems: [
      {
        actionGroupExtractMode: 'ITEM',
        panelItems: [
          {
            caption: '搜索栏',
            itemStyle: 'DEFAULT',
            itemType: 'CTRLPOS',
            layoutPos: {
              shrink: 1,
              layout: 'FLEX',
            },
            showCaption: true,
            id: 'searchbar',
          },
          {
            actionGroupExtractMode: 'ITEM',
            panelItems: [
              {
                actionGroupExtractMode: 'ITEM',
                panelItems: [
                  {
                    caption: '页面标题',
                    itemStyle: 'DEFAULT',
                    itemType: 'CTRLPOS',
                    layoutPos: {
                      shrink: 1,
                      layout: 'FLEX',
                    },
                    showCaption: true,
                    id: 'captionbar',
                  },
                ],
                layout: {
                  align: 'center',
                  layout: 'FLEX',
                },
                dataRegionType: 'INHERIT',
                caption: '容器',
                itemStyle: 'DEFAULT',
                itemType: 'CONTAINER',
                layoutPos: {
                  shrink: 1,
                  heightMode: 'FULL',
                  layout: 'FLEX',
                },
                id: 'view_captionbar',
              },
            ],
            layout: {
              layout: 'FLEX',
            },
            dataRegionType: 'INHERIT',
            caption: '容器',
            itemStyle: 'DEFAULT',
            itemType: 'CONTAINER',
            layoutPos: {
              shrink: 1,
              heightMode: 'FULL',
              layout: 'FLEX',
            },
            id: 'view_header_left',
          },
          {
            actionGroupExtractMode: 'ITEM',
            panelItems: [
              {
                actionGroupExtractMode: 'ITEM',
                panelItems: [
                  {
                    caption: '工具栏',
                    itemStyle: 'DEFAULT',
                    itemType: 'CTRLPOS',
                    layoutPos: {
                      shrink: 1,
                      layout: 'FLEX',
                    },
                    showCaption: true,
                    id: 'toolbar',
                  },
                ],
                layout: {
                  align: 'center',
                  layout: 'FLEX',
                },
                dataRegionType: 'INHERIT',
                caption: '容器',
                itemStyle: 'DEFAULT',
                itemType: 'CONTAINER',
                layoutPos: {
                  shrink: 1,
                  heightMode: 'FULL',
                  layout: 'FLEX',
                },
                id: 'view_toolbar',
              },
            ],
            layout: {
              dir: 'row',
              layout: 'FLEX',
            },
            dataRegionType: 'INHERIT',
            caption: '容器',
            itemStyle: 'DEFAULT',
            itemType: 'CONTAINER',
            layoutPos: {
              shrink: 1,
              heightMode: 'FULL',
              layout: 'FLEX',
            },
            id: 'view_header_right',
          },
        ],
        predefinedType: 'VIEWHEADER',
        layout: {
          align: 'space-between',
          dir: 'row',
          layout: 'FLEX',
          valign: 'center',
        },
        dataRegionType: 'INHERIT',
        caption: '容器',
        itemStyle: 'DEFAULT',
        itemType: 'CONTAINER',
        layoutPos: {
          shrink: 0,
          layout: 'FLEX',
        },
        id: 'view_header',
      },
      {
        actionGroupExtractMode: 'ITEM',
        panelItems: [
          {
            caption: '搜索表单',
            itemStyle: 'DEFAULT',
            itemType: 'CTRLPOS',
            layoutPos: {
              shrink: 1,
              layout: 'FLEX',
            },
            showCaption: true,
            id: 'searchform',
          },
        ],
        layout: {
          dir: 'column',
          layout: 'FLEX',
        },
        dataRegionType: 'INHERIT',
        itemStyle: 'DEFAULT',
        itemType: 'CONTAINER',
        layoutPos: {
          shrink: 0,
          layout: 'FLEX',
        },
        id: 'view_searchform',
      },
      {
        actionGroupExtractMode: 'ITEM',
        panelItems: [
          {
            caption: '表格',
            itemStyle: 'DEFAULT',
            itemType: 'CTRLPOS',
            layoutPos: {
              grow: 1,
              shrink: 1,
              layout: 'FLEX',
            },
            showCaption: true,
            id: 'grid',
          },
        ],
        predefinedType: 'VIEWCONTENT',
        layout: {
          layout: 'FLEX',
        },
        dataRegionType: 'INHERIT',
        caption: '容器',
        itemStyle: 'DEFAULT',
        itemType: 'CONTAINER',
        layoutPos: {
          grow: 1,
          shrink: 1,
          layout: 'FLEX',
        },
        id: 'view_content',
      },
    ],
    layoutPanel: true,
    appViewEngines: [
      {
        engineCat: 'VIEW',
        engineType: 'GridView',
        id: 'engine',
      },
    ],
    appViewLogics: [
      {
        logicTrigger: 'CUSTOM',
        logicType: 'APPUILOGIC',
        builtinAppUILogic: {
          actionAfterWizard: 'DEFAULT',
          newDataAppView: {
            openMode: 'POPUPMODAL',
            refAppViewId: 'web.region_edit_view',
          },
          appUILogicRefViews: [
            {
              openMode: 'POPUPMODAL',
              refAppViewId: 'web.region_edit_view',
            },
          ],
          builtinLogic: true,
          logicType: 'PREDEFINED',
          viewLogicType: 'APP_NEWDATA',
          id: '新建数据',
        },
        builtinLogic: true,
        id: 'newdata',
      },
      {
        logicTrigger: 'CUSTOM',
        logicType: 'APPUILOGIC',
        builtinAppUILogic: {
          openDataAppView: {
            openMode: 'POPUPMODAL',
            refAppViewId: 'web.region_edit_view',
          },
          editMode: true,
          appUILogicRefViews: [
            {
              openMode: 'POPUPMODAL',
              refAppViewId: 'web.region_edit_view',
            },
          ],
          builtinLogic: true,
          logicType: 'PREDEFINED',
          viewLogicType: 'APP_OPENDATA',
          id: '打开数据',
        },
        builtinLogic: true,
        id: 'opendata',
      },
    ],
    appViewRefs: [
      {
        realOpenMode: 'POPUPMODAL',
        realTitle: '区划编辑视图',
        refAppViewId: 'web.region_edit_view',
        name: 'EDITDATA',
        id: 'editdata',
      },
      {
        realOpenMode: 'POPUPMODAL',
        realTitle: '区划编辑视图',
        refAppViewId: 'web.region_edit_view',
        name: 'NEWDATA',
        id: 'newdata',
      },
    ],
    controls: [
      {
        aggMode: 'NONE',
        columnEnableFilter: 2,
        columnEnableLink: 2,
        groupMode: 'NONE',
        groupStyle: 'DEFAULT',
        degridColumns: [
          {
            clconvertMode: 'NONE',
            dataItemName: 'code',
            excelCaption: '编码',
            appDEFieldId: 'code',
            valueType: 'SIMPLE',
            aggMode: 'NONE',
            align: 'LEFT',
            caption: '编码',
            codeName: 'code',
            columnType: 'DEFGRIDCOLUMN',
            noPrivDisplayMode: 1,
            width: 150,
            widthUnit: 'PX',
            enableSort: true,
            id: 'code',
          },
          {
            clconvertMode: 'NONE',
            dataItemName: 'name',
            excelCaption: '名称',
            appDEFieldId: 'name',
            valueType: 'SIMPLE',
            enableRowEdit: true,
            aggMode: 'NONE',
            align: 'LEFT',
            capLanguageRes: {
              lanResTag: 'DEF.LNAME.REGION.NAME',
            },
            caption: '名称',
            codeName: 'name',
            columnType: 'DEFGRIDCOLUMN',
            noPrivDisplayMode: 1,
            width: 200,
            widthUnit: 'PX',
            enableSort: true,
            id: 'name',
          },
          {
            clconvertMode: 'NONE',
            dataItemName: 'parent_name',
            excelCaption: '上级区划',
            linkAppViewId: 'web.region_redirect_view',
            linkValueItem: 'parent_id',
            appDEFieldId: 'parent_name',
            valueType: 'SIMPLE',
            enableLinkView: true,
            enableRowEdit: true,
            aggMode: 'NONE',
            align: 'LEFT',
            caption: '上级区划',
            codeName: 'parent_name',
            columnType: 'DEFGRIDCOLUMN',
            noPrivDisplayMode: 1,
            width: 200,
            widthUnit: 'PX',
            enableSort: true,
            id: 'parent_name',
          },
          {
            clconvertMode: 'NONE',
            dataItemName: 'level',
            excelCaption: '级别',
            appDEFieldId: 'level',
            valueType: 'SIMPLE',
            enableRowEdit: true,
            aggMode: 'NONE',
            align: 'LEFT',
            caption: '级别',
            codeName: 'level',
            columnType: 'DEFGRIDCOLUMN',
            noPrivDisplayMode: 1,
            width: 100,
            widthUnit: 'PX',
            enableSort: true,
            id: 'level',
          },
          {
            clconvertMode: 'FRONT',
            dataItemName: 'status',
            excelCaption: '状态',
            appCodeListId: 'web.mock__cl_status',
            appDEFieldId: 'status',
            valueType: 'SIMPLE',
            enableRowEdit: true,
            aggMode: 'NONE',
            align: 'LEFT',
            caption: '状态',
            codeName: 'status',
            columnType: 'DEFGRIDCOLUMN',
            noPrivDisplayMode: 1,
            width: 150,
            widthUnit: 'PX',
            enableSort: true,
            id: 'status',
          },
          {
            clconvertMode: 'NONE',
            dataItemName: 'path',
            excelCaption: '全路径',
            appDEFieldId: 'path',
            valueType: 'SIMPLE',
            enableRowEdit: true,
            aggMode: 'NONE',
            align: 'LEFT',
            caption: '全路径',
            codeName: 'path',
            columnType: 'DEFGRIDCOLUMN',
            noPrivDisplayMode: 1,
            width: 300,
            widthUnit: 'PX',
            enableSort: true,
            id: 'path',
          },
          {
            clconvertMode: 'NONE',
            dataItemName: 'sort',
            excelCaption: '排序',
            appDEFieldId: 'sort',
            valueType: 'SIMPLE',
            enableRowEdit: true,
            aggMode: 'NONE',
            align: 'LEFT',
            caption: '排序',
            codeName: 'sort',
            columnType: 'DEFGRIDCOLUMN',
            noPrivDisplayMode: 1,
            width: 100,
            widthUnit: 'PX',
            enableSort: true,
            id: 'sort',
          },
        ],
        degridDataItems: [
          {
            appDEFieldId: 'code',
            valueType: 'SIMPLE',
            dataType: 25,
            id: 'code',
          },
          {
            appDEFieldId: 'name',
            valueType: 'SIMPLE',
            dataType: 25,
            id: 'name',
          },
          {
            appDEFieldId: 'parent_name',
            valueType: 'SIMPLE',
            dataType: 25,
            id: 'parent_name',
          },
          {
            appDEFieldId: 'level',
            valueType: 'SIMPLE',
            dataType: 9,
            id: 'level',
          },
          {
            appDEFieldId: 'status',
            valueType: 'SIMPLE',
            dataType: 9,
            id: 'status',
          },
          {
            appDEFieldId: 'path',
            valueType: 'SIMPLE',
            dataType: 25,
            id: 'path',
          },
          {
            appDEFieldId: 'sort',
            valueType: 'SIMPLE',
            dataType: 9,
            id: 'sort',
          },
          {
            appDEFieldId: 'id',
            valueType: 'SIMPLE',
            dataType: 25,
            id: 'srfkey',
          },
          {
            appDEFieldId: 'id',
            valueType: 'SIMPLE',
            dataType: 25,
            id: 'srfdataaccaction',
          },
          {
            appDEFieldId: 'parent_id',
            valueType: 'SIMPLE',
            dataType: 25,
            id: 'parent_id',
          },
          {
            appDEFieldId: 'name',
            valueType: 'SIMPLE',
            dataType: 25,
            id: 'srfmajortext',
          },
        ],
        degridEditItems: [
          {
            caption: '名称',
            codeName: 'name',
            enableCond: 3,
            appDEFieldId: 'name',
            editor: {
              maxLength: 200,
              editorType: 'TEXTBOX',
              valueType: 'SIMPLE',
              editable: true,
              id: 'name',
            },
            allowEmpty: true,
            id: 'name',
          },
          {
            caption: '上级区划',
            codeName: 'parent_name',
            enableCond: 3,
            appDEFieldId: 'parent_name',
            editor: {
              enablePickupView: true,
              singleSelect: true,
              appDEACModeId: 'default',
              appDEDataSetId: 'fetch_default',
              appDataEntityId: 'web.region',
              enableAC: true,
              forceSelection: true,
              showTrigger: true,
              valueItemName: 'parent_id',
              editorParams: {
                AC: 'TRUE',
                PICKUPVIEW: 'TRUE',
              },
              editorType: 'PICKER',
              editorItems: [{}],
              valueType: 'SIMPLE',
              editable: true,
              id: 'parent_name',
            },
            allowEmpty: true,
            id: 'parent_name',
          },
          {
            caption: '级别',
            codeName: 'level',
            enableCond: 3,
            appDEFieldId: 'level',
            editor: {
              editorType: 'TEXTBOX',
              valueType: 'SIMPLE',
              editable: true,
              id: 'level',
            },
            allowEmpty: true,
            id: 'level',
          },
          {
            caption: '状态',
            codeName: 'status',
            enableCond: 3,
            appDEFieldId: 'status',
            editor: {
              singleSelect: true,
              appCodeListId: 'web.mock__cl_status',
              editorType: 'DROPDOWNLIST',
              valueType: 'SIMPLE',
              editable: true,
              id: 'status',
            },
            allowEmpty: true,
            needCodeListConfig: true,
            id: 'status',
          },
          {
            caption: '全路径',
            codeName: 'path',
            enableCond: 3,
            appDEFieldId: 'path',
            editor: {
              maxLength: 500,
              editorType: 'TEXTBOX',
              valueType: 'SIMPLE',
              editable: true,
              id: 'path',
            },
            allowEmpty: true,
            id: 'path',
          },
          {
            caption: '排序',
            codeName: 'sort',
            enableCond: 3,
            appDEFieldId: 'sort',
            editor: {
              editorType: 'TEXTBOX',
              valueType: 'SIMPLE',
              editable: true,
              id: 'sort',
            },
            allowEmpty: true,
            id: 'sort',
          },
          {
            caption: '标识',
            codeName: 'srfkey',
            enableCond: 3,
            appDEFieldId: 'id',
            editor: {
              editorType: 'HIDDEN',
              valueType: 'SIMPLE',
              editable: true,
              id: 'srfkey',
            },
            allowEmpty: true,
            id: 'srfkey',
          },
          {
            enableCond: 3,
            appDEFieldId: 'parent_id',
            editor: {
              editorType: 'HIDDEN',
              valueType: 'SIMPLE',
              editable: true,
            },
            allowEmpty: true,
            id: 'parent_id',
          },
        ],
        pagingMode: 1,
        pagingSize: 100,
        sortMode: 'REMOTE',
        enableCustomized: true,
        enablePagingBar: true,
        navAppViewId: 'web.region_info_view',
        navViewMinWidth: 750,
        navViewPos: 'ANY_RIGHT',
        navViewWidth: 750,
        fetchControlAction: {
          appDEMethodId: 'fetch_default',
          appDataEntityId: 'web.region',
          id: 'fetch',
        },
        removeControlAction: {
          appDEMethodId: 'remove',
          appDataEntityId: 'web.region',
          id: 'remove',
        },
        autoLoad: true,
        showBusyIndicator: true,
        codeName: 'nav',
        controlType: 'GRID',
        logicName: '导航表格',
        appDataEntityId: 'web.region',
        controlParam: {
          id: 'grid',
        },
        modelId: '3a83c6797098a3d6b0fe975c47e6bc5f',
        modelType: 'PSDEGRID',
        name: 'grid',
        id: 'web.region.nav',
      },
      {
        searchButtonStyle: 'DEFAULT',
        deformPages: [
          {
            layout: {
              columnCount: 24,
              layout: 'TABLE_24COL',
            },
            deformDetails: [
              {
                dataType: 25,
                enableCond: 3,
                labelPos: 'LEFT',
                labelWidth: 130,
                noPrivDisplayMode: 1,
                appDEFieldId: 'name',
                editor: {
                  editorType: 'TEXTBOX',
                  valueType: 'SIMPLE',
                  editable: true,
                  id: 'n_name_like',
                },
                allowEmpty: true,
                capLanguageRes: {
                  lanResTag: 'CONTROL.DEFSFITEM.REGION.N_NAME_LIKE',
                },
                caption: '名称(%)',
                codeName: 'n_name_like',
                detailStyle: 'DEFAULT',
                detailType: 'FORMITEM',
                layoutPos: {
                  colLG: 8,
                  colMD: 8,
                  layout: 'TABLE_24COL',
                },
                showCaption: true,
                id: 'n_name_like',
              },
              {
                dataType: 25,
                enableCond: 3,
                labelPos: 'LEFT',
                labelWidth: 130,
                noPrivDisplayMode: 1,
                appDEFieldId: 'code',
                editor: {
                  editorType: 'TEXTBOX',
                  valueType: 'SIMPLE',
                  editable: true,
                  id: 'n_code_like',
                },
                allowEmpty: true,
                caption: '编码(%)',
                codeName: 'n_code_like',
                detailStyle: 'DEFAULT',
                detailType: 'FORMITEM',
                layoutPos: {
                  colLG: 8,
                  colMD: 8,
                  layout: 'TABLE_24COL',
                },
                showCaption: true,
                id: 'n_code_like',
              },
              {
                dataType: 25,
                enableCond: 3,
                labelPos: 'LEFT',
                labelWidth: 130,
                noPrivDisplayMode: 1,
                appDEFieldId: 'parent_name',
                editor: {
                  enablePickupView: true,
                  singleSelect: true,
                  pickupAppViewId: 'web.region_pickup_view',
                  handlerType: 'PickupText',
                  appDEACModeId: 'default',
                  appDEDataSetId: 'fetch_default',
                  appDataEntityId: 'web.region',
                  enableAC: true,
                  forceSelection: true,
                  showTrigger: true,
                  valueItemName: 'n_parent_id_eq',
                  editorParams: {
                    AC: 'TRUE',
                    PICKUPVIEW: 'TRUE',
                  },
                  editorType: 'PICKER',
                  editorItems: [
                    {
                      id: 'n_parent_id_eq',
                    },
                  ],
                  valueType: 'SIMPLE',
                  editable: true,
                  id: 'n_parent_name_eq',
                },
                allowEmpty: true,
                caption: '上级区划(=)',
                codeName: 'n_parent_name_eq',
                detailStyle: 'DEFAULT',
                detailType: 'FORMITEM',
                layoutPos: {
                  colLG: 8,
                  colMD: 8,
                  layout: 'TABLE_24COL',
                },
                showCaption: true,
                id: 'n_parent_name_eq',
              },
              {
                dataType: 25,
                enableCond: 3,
                labelPos: 'LEFT',
                labelWidth: 130,
                noPrivDisplayMode: 1,
                appDEFieldId: 'parent_id',
                editor: {
                  editorType: 'HIDDEN',
                  valueType: 'SIMPLE',
                  editable: true,
                  id: 'n_parent_id_eq',
                },
                allowEmpty: true,
                hidden: true,
                caption: '上级区划标识(=)',
                codeName: 'n_parent_id_eq',
                detailStyle: 'DEFAULT',
                detailType: 'FORMITEM',
                layoutPos: {
                  colLG: 8,
                  colMD: 8,
                  layout: 'TABLE_24COL',
                },
                id: 'n_parent_id_eq',
              },
              {
                dataType: 9,
                enableCond: 3,
                labelPos: 'LEFT',
                labelWidth: 130,
                noPrivDisplayMode: 1,
                appDEFieldId: 'status',
                editor: {
                  singleSelect: true,
                  appCodeListId: 'web.mock__cl_status',
                  editorType: 'DROPDOWNLIST',
                  valueType: 'SIMPLE',
                  editable: true,
                  id: 'n_status_eq',
                },
                allowEmpty: true,
                needCodeListConfig: true,
                caption: '状态(=)',
                codeName: 'n_status_eq',
                detailStyle: 'DEFAULT',
                detailType: 'FORMITEM',
                layoutPos: {
                  colLG: 8,
                  colMD: 8,
                  layout: 'TABLE_24COL',
                },
                showCaption: true,
                id: 'n_status_eq',
              },
              {
                dataType: 25,
                enableCond: 3,
                labelPos: 'LEFT',
                labelWidth: 130,
                noPrivDisplayMode: 1,
                editor: {
                  editorType: 'NUMBERRANGE',
                  valueType: 'SIMPLE',
                  editable: true,
                  id: 'level',
                },
                allowEmpty: true,
                caption: '级别',
                codeName: 'level',
                detailStyle: 'DEFAULT',
                detailType: 'FORMITEM',
                layoutPos: {
                  colLG: 8,
                  colMD: 8,
                  layout: 'TABLE_24COL',
                },
                showCaption: true,
                id: 'level',
              },
            ],
            capLanguageRes: {
              lanResTag: 'CONTROL.DEFORM.REGION.DEFAULT.FORMPAGE.FORMPAGE1',
            },
            caption: '常规条件',
            codeName: 'formpage1',
            detailStyle: 'DEFAULT',
            detailType: 'FORMPAGE',
            id: 'formpage1',
          },
        ],
        layout: {
          columnCount: 24,
          layout: 'TABLE_24COL',
        },
        tabHeaderPos: 'TOP',
        noTabHeader: true,
        autoLoad: true,
        showBusyIndicator: true,
        codeName: 'default',
        controlType: 'SEARCHFORM',
        logicName: '默认搜索表单',
        appDataEntityId: 'web.region',
        controlParam: {
          id: 'searchform',
        },
        modelId: '3dc9ea359ce488ec65b7253220f11dd6',
        modelType: 'PSDEFORM_SEARCHFORM',
        name: 'searchform',
        id: 'web.region.default',
      },
      {
        groupMode: 'SINGLE',
        searchBarGroups: [
          {
            caption: '全部',
            data: '{"theme_model":{"searchconds":[{"condtype":"GROUP","condop":"AND","bnotmode":false,"searchconds":[]}]}}',
            itemType: 'GROUP',
            id: 'all',
          },
          {
            caption: '省级',
            data: '{"theme_model":{"searchconds":[{"condtype":"GROUP","condop":"AND","bnotmode":false,"searchconds":[{"condtype":"DEFIELD","fieldname":"level","condop":"EQ","value":"1"}]}]}}',
            itemType: 'GROUP',
            id: 'l1',
          },
          {
            caption: '市级',
            data: '{"theme_model":{"searchconds":[{"condtype":"GROUP","condop":"AND","bnotmode":false,"searchconds":[{"condtype":"DEFIELD","fieldname":"level","condop":"EQ","value":"2"}]}]}}',
            itemType: 'GROUP',
            id: 'l2',
          },
        ],
        quickSearchMode: 2,
        enableGroup: true,
        enableQuickSearch: true,
        codeName: 'level',
        controlType: 'SEARCHBAR',
        logicName: '级别',
        appDataEntityId: 'web.region',
        controlParam: {
          id: 'searchbar',
        },
        modelId: '8c99d19c91bd8c4a260b6b32452b7762',
        modelType: 'PSSYSSEARCHBAR',
        name: 'searchbar',
        id: 'web.region.level',
      },
      {
        capLanguageRes: {
          lanResTag: 'DE.LNAME.REGION',
        },
        caption: '表格导航',
        codeName: 'grid_nav_captionbar',
        controlType: 'CAPTIONBAR',
        appDataEntityId: 'web.region',
        controlParam: {},
        name: 'captionbar',
        id: 'grid_nav_captionbar',
      },
    ],
    codeName: 'usr0506629128',
    controlType: 'VIEWLAYOUTPANEL',
    logicName: 'grid_nav表格视图布局',
    appDataEntityId: 'web.region',
    controlParam: {},
    modelId: 'c71086e0164b8a127f81a4b9bb98f037',
    modelType: 'PSSYSVIEWLAYOUTPANEL',
    name: 'layoutpanel',
    id: 'usr0506629128',
  },
  title: '表格导航',
  viewStyle: 'DEFAULT',
  viewType: 'DEGRIDVIEW',
  enableDP: true,
  showCaptionBar: false,
  modelId: '1abf86850106382180ee87cb1e933923',
  modelType: 'PSAPPDEVIEW',
  name: 'REGIONgrid_nav',
  id: 'web.region_grid_nav',
};
