export default {
  gridRowActiveMode: 2,
  enableRowEdit: true,
  xdataControlName: 'grid',
  loadDefault: true,
  funcViewMode: 'MDATAVIEW',
  deviewCodeName: 'GridView',
  deviewId: 'dd975ab6e4594df9c2b6720bf64542d6',
  accUserMode: 3,
  capLanguageRes: {
    lanResTag: 'DE.LNAME.REGION',
  },
  caption: '区划表格视图',
  codeName: 'region_grid_view',
  appDataEntityId: 'web.region',
  appViewEngines: [
    {
      engineCat: 'VIEW',
      engineType: 'GridView',
      id: 'engine',
    },
  ],
  appViewLogics: [
    {
      logicTrigger: 'CUSTOM',
      logicType: 'APPUILOGIC',
      builtinAppUILogic: {
        actionAfterWizard: 'DEFAULT',
        newDataAppView: {
          openMode: 'POPUPMODAL',
          refAppViewId: 'web.region_edit_view',
        },
        appUILogicRefViews: [
          {
            openMode: 'POPUPMODAL',
            refAppViewId: 'web.region_edit_view',
          },
        ],
        builtinLogic: true,
        logicType: 'PREDEFINED',
        viewLogicType: 'APP_NEWDATA',
        id: '新建数据',
      },
      builtinLogic: true,
      id: 'newdata',
    },
    {
      logicTrigger: 'CUSTOM',
      logicType: 'APPUILOGIC',
      builtinAppUILogic: {
        openDataAppView: {
          openMode: 'POPUPMODAL',
          refAppViewId: 'web.region_edit_view',
        },
        editMode: true,
        appUILogicRefViews: [
          {
            openMode: 'POPUPMODAL',
            refAppViewId: 'web.region_edit_view',
          },
        ],
        builtinLogic: true,
        logicType: 'PREDEFINED',
        viewLogicType: 'APP_OPENDATA',
        id: '打开数据',
      },
      builtinLogic: true,
      id: 'opendata',
    },
  ],
  appViewMsgGroupId: 'usrvmgroup0529030821',
  appViewRefs: [
    {
      realOpenMode: 'POPUPMODAL',
      realTitle: '区划信息',
      refAppViewId: 'web.region_info_view',
      name: 'OPENDATA',
      id: 'opendata',
    },
    {
      realOpenMode: 'POPUPMODAL',
      realTitle: '区划编辑视图',
      refAppViewId: 'web.region_edit_view',
      name: 'NEWDATA',
      id: 'newdata',
    },
    {
      realOpenMode: 'POPUPMODAL',
      realTitle: '区划编辑视图',
      refAppViewId: 'web.region_edit_view',
      name: 'EDITDATA',
      id: 'editdata',
    },
  ],
  controls: [
    {
      groupMode: 'SINGLE',
      searchBarGroups: [
        {
          caption: '全部',
          data: '{"theme_model":{"searchconds":[{"condtype":"GROUP","condop":"AND","bnotmode":false,"searchconds":[]}]}}',
          itemType: 'GROUP',
          id: 'all',
        },
        {
          caption: '省级',
          data: '{"theme_model":{"searchconds":[{"condtype":"GROUP","condop":"AND","bnotmode":false,"searchconds":[{"condtype":"DEFIELD","fieldname":"level","condop":"EQ","value":"1"}]}]}}',
          itemType: 'GROUP',
          id: 'l1',
        },
        {
          caption: '市级',
          data: '{"theme_model":{"searchconds":[{"condtype":"GROUP","condop":"AND","bnotmode":false,"searchconds":[{"condtype":"DEFIELD","fieldname":"level","condop":"EQ","value":"2"}]}]}}',
          itemType: 'GROUP',
          id: 'l2',
        },
      ],
      quickSearchMode: 2,
      enableGroup: true,
      enableQuickSearch: true,
      codeName: 'level',
      controlType: 'SEARCHBAR',
      logicName: '级别',
      appDataEntityId: 'web.region',
      controlParam: {
        id: 'searchbar',
      },
      modelId: '8c99d19c91bd8c4a260b6b32452b7762',
      modelType: 'PSSYSSEARCHBAR',
      name: 'searchbar',
      id: 'web.region.level',
    },
    {
      aggMode: 'NONE',
      columnEnableFilter: 2,
      columnEnableLink: 2,
      frozenLastColumn: 1,
      gridStyle: 'TREEGRID',
      groupMode: 'NONE',
      groupStyle: 'DEFAULT',
      minorSortDir: 'ASC',
      minorSortAppDEFieldId: 'sort',
      degridColumns: [
        {
          clconvertMode: 'NONE',
          dataItemName: 'code',
          excelCaption: '编码',
          appDEFieldId: 'code',
          valueType: 'SIMPLE',
          aggMode: 'NONE',
          align: 'LEFT',
          caption: '编码',
          codeName: 'code',
          columnType: 'DEFGRIDCOLUMN',
          noPrivDisplayMode: 1,
          width: 150,
          widthUnit: 'PX',
          enableSort: true,
          id: 'code',
        },
        {
          clconvertMode: 'NONE',
          dataItemName: 'name',
          excelCaption: '名称',
          appDEFieldId: 'name',
          treeColumnMode: 1,
          valueType: 'SIMPLE',
          enableRowEdit: true,
          aggMode: 'NONE',
          align: 'LEFT',
          capLanguageRes: {
            lanResTag: 'DEF.LNAME.REGION.NAME',
          },
          caption: '名称',
          codeName: 'name',
          columnType: 'DEFGRIDCOLUMN',
          noPrivDisplayMode: 1,
          width: 200,
          widthUnit: 'PX',
          enableSort: true,
          id: 'name',
        },
        {
          clconvertMode: 'NONE',
          dataItemName: 'parent_name',
          excelCaption: '上级区划',
          linkAppViewId: 'web.region_redirect_view',
          linkValueItem: 'parent_id',
          appDEFieldId: 'parent_name',
          treeColumnMode: 8,
          valueType: 'SIMPLE',
          enableLinkView: true,
          enableRowEdit: true,
          aggMode: 'NONE',
          align: 'LEFT',
          caption: '上级区划',
          codeName: 'parent_name',
          columnType: 'DEFGRIDCOLUMN',
          noPrivDisplayMode: 1,
          width: 200,
          widthUnit: 'PX',
          enableSort: true,
          id: 'parent_name',
        },
        {
          clconvertMode: 'NONE',
          dataItemName: 'level',
          excelCaption: '级别',
          appDEFieldId: 'level',
          valueType: 'SIMPLE',
          enableRowEdit: true,
          aggMode: 'NONE',
          align: 'LEFT',
          caption: '级别',
          codeName: 'level',
          columnType: 'DEFGRIDCOLUMN',
          noPrivDisplayMode: 1,
          width: 100,
          widthUnit: 'PX',
          enableSort: true,
          id: 'level',
        },
        {
          clconvertMode: 'FRONT',
          dataItemName: 'status',
          excelCaption: '状态',
          appCodeListId: 'web.mock__cl_status',
          appDEFieldId: 'status',
          valueType: 'SIMPLE',
          enableRowEdit: true,
          aggMode: 'NONE',
          align: 'LEFT',
          caption: '状态',
          codeName: 'status',
          columnType: 'DEFGRIDCOLUMN',
          noPrivDisplayMode: 1,
          width: 150,
          widthUnit: 'PX',
          enableSort: true,
          id: 'status',
        },
        {
          clconvertMode: 'NONE',
          dataItemName: 'path',
          excelCaption: '全路径',
          appDEFieldId: 'path',
          valueType: 'SIMPLE',
          enableRowEdit: true,
          aggMode: 'NONE',
          align: 'LEFT',
          caption: '全路径',
          codeName: 'path',
          columnType: 'DEFGRIDCOLUMN',
          noPrivDisplayMode: 1,
          width: 500,
          widthUnit: 'STAR',
          enableSort: true,
          id: 'path',
        },
        {
          clconvertMode: 'NONE',
          dataItemName: 'sort',
          excelCaption: '排序',
          appDEFieldId: 'sort',
          valueType: 'SIMPLE',
          enableRowEdit: true,
          aggMode: 'NONE',
          align: 'LEFT',
          caption: '排序',
          codeName: 'sort',
          columnType: 'DEFGRIDCOLUMN',
          noPrivDisplayMode: 1,
          width: 100,
          widthUnit: 'PX',
          enableSort: true,
          id: 'sort',
        },
        {
          clconvertMode: 'NONE',
          dataItemName: 'longitude',
          excelCaption: '经度',
          appDEFieldId: 'longitude',
          valueType: 'SIMPLE',
          enableRowEdit: true,
          aggMode: 'NONE',
          align: 'LEFT',
          caption: '经度',
          codeName: 'longitude',
          columnType: 'DEFGRIDCOLUMN',
          noPrivDisplayMode: 1,
          width: 100,
          widthUnit: 'PX',
          enableSort: true,
          id: 'longitude',
        },
        {
          clconvertMode: 'NONE',
          dataItemName: 'latitude',
          excelCaption: '纬度',
          appDEFieldId: 'latitude',
          valueType: 'SIMPLE',
          enableRowEdit: true,
          aggMode: 'NONE',
          align: 'LEFT',
          caption: '纬度',
          codeName: 'latitude',
          columnType: 'DEFGRIDCOLUMN',
          noPrivDisplayMode: 1,
          width: 100,
          widthUnit: 'PX',
          enableSort: true,
          id: 'latitude',
        },
        {
          clconvertMode: 'NONE',
          dataItemName: 'update_time',
          excelCaption: '更新时间',
          appDEFieldId: 'update_time',
          valueFormat: 'YYYY-MM-DD HH:mm:ss',
          valueType: 'SIMPLE',
          aggMode: 'NONE',
          align: 'LEFT',
          capLanguageRes: {
            lanResTag: 'DEF.LNAME.UPDATE_TIME',
          },
          caption: '更新时间',
          codeName: 'update_time',
          columnType: 'DEFGRIDCOLUMN',
          noPrivDisplayMode: 1,
          width: 200,
          widthUnit: 'PX',
          enableSort: true,
          id: 'update_time',
        },
        {
          clconvertMode: 'NONE',
          dataItemName: 'create_time',
          excelCaption: '创建时间',
          appDEFieldId: 'create_time',
          valueFormat: 'YYYY-MM-DD HH:mm:ss',
          valueType: 'SIMPLE',
          aggMode: 'NONE',
          align: 'LEFT',
          capLanguageRes: {
            lanResTag: 'DEF.LNAME.REGION.CREATE_TIME',
          },
          caption: '创建时间',
          codeName: 'create_time',
          columnType: 'DEFGRIDCOLUMN',
          noPrivDisplayMode: 1,
          width: 200,
          widthUnit: 'PX',
          enableSort: true,
          id: 'create_time',
        },
        {
          deuiactionGroup: {
            uiactionGroupDetails: [
              {
                actionLevel: 100,
                afterItemType: 'NONE',
                beforeItemType: 'NONE',
                buttonStyle: 'DEFAULT',
                caption: '查看',
                detailType: 'DEUIACTION',
                uiactionId: 'view@region',
                showCaption: true,
                showIcon: true,
                sysImage: {
                  cssClass: 'fa fa-file-text',
                  glyph: 'xf15c@FontAwesome',
                },
                id: 'u988f5c7',
              },
              {
                actionLevel: 100,
                afterItemType: 'NONE',
                beforeItemType: 'NONE',
                buttonStyle: 'DEFAULT',
                caption: '编辑',
                detailType: 'DEUIACTION',
                uiactionId: 'edit@region',
                showCaption: true,
                showIcon: true,
                sysImage: {
                  cssClass: 'fa fa-edit',
                  glyph: 'xf044@FontAwesome',
                },
                id: 'ubfba42f',
              },
              {
                actionLevel: 100,
                afterItemType: 'NONE',
                beforeItemType: 'NONE',
                buttonStyle: 'DEFAULT',
                caption: '删除',
                detailType: 'DEUIACTION',
                uiactionId: 'remove@region',
                showCaption: true,
                showIcon: true,
                sysImage: {
                  cssClass: 'fa fa-trash',
                  glyph: 'xf1f8@FontAwesome',
                },
                id: 'u662706e',
              },
            ],
            appDataEntityId: 'web.region',
            uniqueTag: 'region__Aa191c5fc4defabcf44',
            name: '表格操作列',
            id: 'aa191c5fc4defabcf44',
          },
          aggMode: 'NONE',
          align: 'CENTER',
          caption: '操作',
          codeName: 'uagridcolumn1',
          columnType: 'UAGRIDCOLUMN',
          noPrivDisplayMode: 1,
          width: 200,
          widthUnit: 'PX',
          id: 'uagridcolumn1',
        },
      ],
      degridDataItems: [
        {
          appDEFieldId: 'code',
          valueType: 'SIMPLE',
          dataType: 25,
          id: 'code',
        },
        {
          appDEFieldId: 'name',
          valueType: 'SIMPLE',
          dataType: 25,
          id: 'name',
        },
        {
          appDEFieldId: 'parent_name',
          valueType: 'SIMPLE',
          dataType: 25,
          id: 'parent_name',
        },
        {
          appDEFieldId: 'level',
          valueType: 'SIMPLE',
          dataType: 9,
          id: 'level',
        },
        {
          appDEFieldId: 'status',
          valueType: 'SIMPLE',
          dataType: 9,
          id: 'status',
        },
        {
          appDEFieldId: 'path',
          valueType: 'SIMPLE',
          dataType: 25,
          id: 'path',
        },
        {
          appDEFieldId: 'sort',
          valueType: 'SIMPLE',
          dataType: 9,
          id: 'sort',
        },
        {
          appDEFieldId: 'longitude',
          valueType: 'SIMPLE',
          dataType: 29,
          id: 'longitude',
        },
        {
          appDEFieldId: 'latitude',
          valueType: 'SIMPLE',
          dataType: 29,
          id: 'latitude',
        },
        {
          format: 'YYYY-MM-DD HH:mm:ss',
          appDEFieldId: 'update_time',
          valueType: 'SIMPLE',
          dataType: 5,
          id: 'update_time',
        },
        {
          format: 'YYYY-MM-DD HH:mm:ss',
          appDEFieldId: 'create_time',
          valueType: 'SIMPLE',
          dataType: 5,
          id: 'create_time',
        },
        {
          appDEFieldId: 'id',
          valueType: 'SIMPLE',
          dataType: 25,
          id: 'id',
        },
        {
          appDEFieldId: 'parent_id',
          valueType: 'SIMPLE',
          dataType: 25,
          id: 'parent_id',
        },
        {
          appDEFieldId: 'id',
          valueType: 'SIMPLE',
          dataType: 25,
          id: 'srfkey',
        },
        {
          appDEFieldId: 'id',
          valueType: 'SIMPLE',
          dataType: 25,
          id: 'srfdataaccaction',
        },
        {
          appDEFieldId: 'name',
          valueType: 'SIMPLE',
          dataType: 25,
          id: 'srfmajortext',
        },
      ],
      degridEditItems: [
        {
          caption: '名称',
          codeName: 'name',
          enableCond: 3,
          appDEFieldId: 'name',
          editor: {
            maxLength: 200,
            editorType: 'TEXTBOX',
            valueType: 'SIMPLE',
            editable: true,
            id: 'name',
          },
          allowEmpty: true,
          id: 'name',
        },
        {
          caption: '上级区划',
          codeName: 'parent_name',
          enableCond: 3,
          appDEFieldId: 'parent_name',
          editor: {
            enablePickupView: true,
            singleSelect: true,
            pickupAppViewId: 'web.region_pickup_view',
            handlerType: 'PickupText',
            appDEACModeId: 'default',
            appDEDataSetId: 'fetch_default',
            appDataEntityId: 'web.region',
            enableAC: true,
            forceSelection: true,
            showTrigger: true,
            valueItemName: 'parent_id',
            editorParams: {
              AC: 'TRUE',
              PICKUPVIEW: 'TRUE',
            },
            editorType: 'PICKER',
            editorItems: [{}],
            valueType: 'SIMPLE',
            editable: true,
            id: 'parent_name',
          },
          allowEmpty: true,
          id: 'parent_name',
        },
        {
          caption: '级别',
          codeName: 'level',
          enableCond: 3,
          appDEFieldId: 'level',
          editor: {
            editorType: 'TEXTBOX',
            valueType: 'SIMPLE',
            editable: true,
            id: 'level',
          },
          allowEmpty: true,
          id: 'level',
        },
        {
          caption: '状态',
          codeName: 'status',
          enableCond: 3,
          appDEFieldId: 'status',
          editor: {
            singleSelect: true,
            appCodeListId: 'web.mock__cl_status',
            editorType: 'DROPDOWNLIST',
            valueType: 'SIMPLE',
            editable: true,
            id: 'status',
          },
          allowEmpty: true,
          needCodeListConfig: true,
          id: 'status',
        },
        {
          caption: '全路径',
          codeName: 'path',
          enableCond: 3,
          appDEFieldId: 'path',
          editor: {
            maxLength: 500,
            editorType: 'TEXTBOX',
            valueType: 'SIMPLE',
            editable: true,
            id: 'path',
          },
          allowEmpty: true,
          id: 'path',
        },
        {
          caption: '排序',
          codeName: 'sort',
          enableCond: 3,
          appDEFieldId: 'sort',
          editor: {
            editorType: 'TEXTBOX',
            valueType: 'SIMPLE',
            editable: true,
            id: 'sort',
          },
          allowEmpty: true,
          id: 'sort',
        },
        {
          caption: '经度',
          codeName: 'longitude',
          enableCond: 3,
          appDEFieldId: 'longitude',
          editor: {
            editorType: 'TEXTBOX',
            valueType: 'SIMPLE',
            editable: true,
            id: 'longitude',
          },
          allowEmpty: true,
          id: 'longitude',
        },
        {
          caption: '纬度',
          codeName: 'latitude',
          enableCond: 3,
          appDEFieldId: 'latitude',
          editor: {
            editorType: 'TEXTBOX',
            valueType: 'SIMPLE',
            editable: true,
            id: 'latitude',
          },
          allowEmpty: true,
          id: 'latitude',
        },
        {
          caption: '标识',
          codeName: 'srfkey',
          enableCond: 3,
          appDEFieldId: 'id',
          editor: {
            editorType: 'HIDDEN',
            valueType: 'SIMPLE',
            editable: true,
            id: 'srfkey',
          },
          allowEmpty: true,
          id: 'srfkey',
        },
        {
          enableCond: 3,
          appDEFieldId: 'parent_id',
          editor: {
            editorType: 'HIDDEN',
            valueType: 'SIMPLE',
            editable: true,
          },
          allowEmpty: true,
          id: 'parent_id',
        },
      ],
      pagingMode: 1,
      pagingSize: 100,
      sortMode: 'REMOTE',
      enableCustomized: true,
      enablePagingBar: true,
      enableRowEdit: true,
      enableRowNew: true,
      navViewPos: 'NONE',
      createControlAction: {
        appDEMethodId: 'create',
        appDataEntityId: 'web.region',
        id: 'create',
      },
      fetchControlAction: {
        appDEMethodId: 'fetch_default',
        appDataEntityId: 'web.region',
        id: 'fetch',
      },
      getDraftControlAction: {
        appDEMethodId: 'get_draft',
        appDataEntityId: 'web.region',
        id: 'loaddraft',
      },
      getControlAction: {
        appDEMethodId: 'get',
        appDataEntityId: 'web.region',
        id: 'load',
      },
      removeControlAction: {
        appDEMethodId: 'remove',
        appDataEntityId: 'web.region',
        id: 'remove',
      },
      updateControlAction: {
        appDEMethodId: 'update',
        appDataEntityId: 'web.region',
        id: 'update',
      },
      autoLoad: true,
      showBusyIndicator: true,
      codeName: 'main',
      controlType: 'GRID',
      logicName: '主表格',
      appDataEntityId: 'web.region',
      controlParam: {
        id: 'grid',
      },
      modelId: '714462b8e2e4d033523b2f10cf3ea4c9',
      modelType: 'PSDEGRID',
      name: 'grid',
      id: 'web.region.main',
    },
    {
      searchButtonStyle: 'DEFAULT',
      deformPages: [
        {
          layout: {
            columnCount: 24,
            layout: 'TABLE_24COL',
          },
          deformDetails: [
            {
              dataType: 25,
              enableCond: 3,
              labelPos: 'LEFT',
              labelWidth: 130,
              noPrivDisplayMode: 1,
              appDEFieldId: 'name',
              editor: {
                editorType: 'TEXTBOX',
                valueType: 'SIMPLE',
                editable: true,
                id: 'n_name_like',
              },
              allowEmpty: true,
              capLanguageRes: {
                lanResTag: 'CONTROL.DEFSFITEM.REGION.N_NAME_LIKE',
              },
              caption: '名称(%)',
              codeName: 'n_name_like',
              detailStyle: 'DEFAULT',
              detailType: 'FORMITEM',
              layoutPos: {
                colLG: 8,
                colMD: 8,
                layout: 'TABLE_24COL',
              },
              showCaption: true,
              id: 'n_name_like',
            },
            {
              dataType: 25,
              enableCond: 3,
              labelPos: 'LEFT',
              labelWidth: 130,
              noPrivDisplayMode: 1,
              appDEFieldId: 'code',
              editor: {
                editorType: 'TEXTBOX',
                valueType: 'SIMPLE',
                editable: true,
                id: 'n_code_like',
              },
              allowEmpty: true,
              caption: '编码(%)',
              codeName: 'n_code_like',
              detailStyle: 'DEFAULT',
              detailType: 'FORMITEM',
              layoutPos: {
                colLG: 8,
                colMD: 8,
                layout: 'TABLE_24COL',
              },
              showCaption: true,
              id: 'n_code_like',
            },
            {
              dataType: 25,
              enableCond: 3,
              labelPos: 'LEFT',
              labelWidth: 130,
              noPrivDisplayMode: 1,
              appDEFieldId: 'parent_name',
              editor: {
                enablePickupView: true,
                singleSelect: true,
                pickupAppViewId: 'web.region_pickup_view',
                handlerType: 'PickupText',
                appDEACModeId: 'default',
                appDEDataSetId: 'fetch_default',
                appDataEntityId: 'web.region',
                enableAC: true,
                forceSelection: true,
                showTrigger: true,
                valueItemName: 'n_parent_id_eq',
                editorParams: {
                  AC: 'TRUE',
                  PICKUPVIEW: 'TRUE',
                },
                editorType: 'PICKER',
                editorItems: [
                  {
                    id: 'n_parent_id_eq',
                  },
                ],
                valueType: 'SIMPLE',
                editable: true,
                id: 'n_parent_name_eq',
              },
              allowEmpty: true,
              caption: '上级区划(=)',
              codeName: 'n_parent_name_eq',
              detailStyle: 'DEFAULT',
              detailType: 'FORMITEM',
              layoutPos: {
                colLG: 8,
                colMD: 8,
                layout: 'TABLE_24COL',
              },
              showCaption: true,
              id: 'n_parent_name_eq',
            },
            {
              dataType: 25,
              enableCond: 3,
              labelPos: 'LEFT',
              labelWidth: 130,
              noPrivDisplayMode: 1,
              appDEFieldId: 'parent_id',
              editor: {
                editorType: 'HIDDEN',
                valueType: 'SIMPLE',
                editable: true,
                id: 'n_parent_id_eq',
              },
              allowEmpty: true,
              hidden: true,
              caption: '上级区划标识(=)',
              codeName: 'n_parent_id_eq',
              detailStyle: 'DEFAULT',
              detailType: 'FORMITEM',
              layoutPos: {
                colLG: 8,
                colMD: 8,
                layout: 'TABLE_24COL',
              },
              id: 'n_parent_id_eq',
            },
            {
              dataType: 9,
              enableCond: 3,
              labelPos: 'LEFT',
              labelWidth: 130,
              noPrivDisplayMode: 1,
              appDEFieldId: 'status',
              editor: {
                singleSelect: true,
                appCodeListId: 'web.mock__cl_status',
                editorType: 'DROPDOWNLIST',
                valueType: 'SIMPLE',
                editable: true,
                id: 'n_status_eq',
              },
              allowEmpty: true,
              needCodeListConfig: true,
              caption: '状态(=)',
              codeName: 'n_status_eq',
              detailStyle: 'DEFAULT',
              detailType: 'FORMITEM',
              layoutPos: {
                colLG: 8,
                colMD: 8,
                layout: 'TABLE_24COL',
              },
              showCaption: true,
              id: 'n_status_eq',
            },
            {
              dataType: 25,
              enableCond: 3,
              labelPos: 'LEFT',
              labelWidth: 130,
              noPrivDisplayMode: 1,
              editor: {
                editorType: 'NUMBERRANGE',
                valueType: 'SIMPLE',
                editable: true,
                id: 'level',
              },
              allowEmpty: true,
              caption: '级别',
              codeName: 'level',
              detailStyle: 'DEFAULT',
              detailType: 'FORMITEM',
              layoutPos: {
                colLG: 8,
                colMD: 8,
                layout: 'TABLE_24COL',
              },
              showCaption: true,
              id: 'level',
            },
          ],
          capLanguageRes: {
            lanResTag: 'CONTROL.DEFORM.REGION.DEFAULT.FORMPAGE.FORMPAGE1',
          },
          caption: '常规条件',
          codeName: 'formpage1',
          detailStyle: 'DEFAULT',
          detailType: 'FORMPAGE',
          id: 'formpage1',
        },
      ],
      layout: {
        columnCount: 24,
        layout: 'TABLE_24COL',
      },
      tabHeaderPos: 'TOP',
      noTabHeader: true,
      autoLoad: true,
      showBusyIndicator: true,
      codeName: 'default',
      controlType: 'SEARCHFORM',
      logicName: '默认搜索表单',
      appDataEntityId: 'web.region',
      controlParam: {
        id: 'searchform',
      },
      modelId: '3dc9ea359ce488ec65b7253220f11dd6',
      modelType: 'PSDEFORM_SEARCHFORM',
      name: 'searchform',
      id: 'web.region.default',
    },
    {
      detoolbarItems: [
        {
          actionLevel: 100,
          noPrivDisplayMode: 2,
          uiactionId: 'gridview_searchbar',
          enableToggleMode: true,
          valid: true,
          capLanguageRes: {
            lanResTag: 'TBB.TEXT.*.FILTER',
          },
          caption: '过滤',
          itemType: 'DEUIACTION',
          sysImage: {
            cssClass: 'fa fa-filter',
            glyph: 'xf0b0@FontAwesome',
          },
          tooltip: '过滤',
          tooltipLanguageRes: {
            lanResTag: 'TBB.TOOLTIP.*.FILTER',
          },
          showCaption: true,
          showIcon: true,
          id: 'tbitem10',
        },
        {
          itemType: 'SEPERATOR',
          id: 'tbitem14',
        },
        {
          actionLevel: 100,
          noPrivDisplayMode: 2,
          uiactionId: 'gridview_newaction',
          valid: true,
          capLanguageRes: {
            lanResTag: 'TBB.TEXT.*.NEW',
          },
          caption: '新建',
          itemType: 'DEUIACTION',
          sysImage: {
            cssClass: 'fa fa-file-text-o',
            glyph: 'xf0f6@FontAwesome',
          },
          tooltip: '新建',
          tooltipLanguageRes: {
            lanResTag: 'TBB.TOOLTIP.*.NEW',
          },
          showCaption: true,
          showIcon: true,
          id: 'tbitem5',
        },
        {
          actionLevel: 100,
          noPrivDisplayMode: 2,
          uiactionId: 'gridview_editaction',
          uiactionTarget: 'SINGLEKEY',
          valid: true,
          capLanguageRes: {
            lanResTag: 'TBB.TEXT.*.EDIT',
          },
          caption: '编辑',
          itemType: 'DEUIACTION',
          sysImage: {
            cssClass: 'fa fa-edit',
            glyph: 'xf044@FontAwesome',
          },
          tooltip: '编辑',
          tooltipLanguageRes: {
            lanResTag: 'TBB.TOOLTIP.*.EDIT',
          },
          showCaption: true,
          showIcon: true,
          id: 'tbitem2',
        },
        {
          actionLevel: 100,
          noPrivDisplayMode: 2,
          uiactionId: 'gridview_copyaction',
          uiactionTarget: 'SINGLEKEY',
          valid: true,
          capLanguageRes: {
            lanResTag: 'TBB.TEXT.*.COPY',
          },
          caption: '拷贝',
          itemType: 'DEUIACTION',
          sysImage: {
            cssClass: 'fa fa-copy',
            glyph: 'xf0c5@FontAwesome',
          },
          tooltip: '拷贝',
          tooltipLanguageRes: {
            lanResTag: 'TBB.TOOLTIP.*.COPY',
          },
          showCaption: true,
          showIcon: true,
          id: 'tbitem1',
        },
        {
          itemType: 'SEPERATOR',
          id: 'tbitem15',
        },
        {
          actionLevel: 100,
          noPrivDisplayMode: 2,
          uiactionId: 'gridview_roweditaction',
          enableToggleMode: true,
          valid: true,
          caption: '行编辑',
          itemType: 'DEUIACTION',
          sysImage: {
            cssClass: 'fa fa-table',
            glyph: 'xf0ce@FontAwesome',
          },
          tooltip: '行编辑',
          showCaption: true,
          showIcon: true,
          id: 'tbitem9',
        },
        {
          actionLevel: 100,
          noPrivDisplayMode: 2,
          uiactionId: 'gridview_newrowaction',
          valid: true,
          caption: '新建行',
          itemType: 'DEUIACTION',
          sysImage: {
            cssClass: 'fa fa-plus',
            glyph: 'xf067@FontAwesome',
          },
          tooltip: '新建行',
          showIcon: true,
          id: 'tbitem6',
        },
        {
          itemType: 'SEPERATOR',
          id: 'tbitem23',
        },
        {
          actionLevel: 100,
          noPrivDisplayMode: 2,
          uiactionId: 'gridview_removeaction',
          uiactionTarget: 'MULTIKEY',
          valid: true,
          capLanguageRes: {
            lanResTag: 'TBB.TEXT.*.REMOVE',
          },
          caption: '删除',
          itemType: 'DEUIACTION',
          sysImage: {
            cssClass: 'fa fa-remove',
            glyph: 'xf00d@FontAwesome',
          },
          tooltip: '删除',
          tooltipLanguageRes: {
            lanResTag: 'TBB.TOOLTIP.*.REMOVE',
          },
          showCaption: true,
          showIcon: true,
          id: 'tbitem8',
        },
        {
          itemType: 'SEPERATOR',
          id: 'tbitem16',
        },
        {
          actionLevel: 100,
          noPrivDisplayMode: 2,
          uiactionId: 'gridview_exportaction',
          valid: true,
          capLanguageRes: {
            lanResTag: 'TBB.TEXT.*.EXPORT',
          },
          caption: '导出',
          itemType: 'DEUIACTION',
          sysImage: {
            cssClass: 'fa fa-file-excel-o',
            glyph: 'xf1c3@FontAwesome',
          },
          tooltip: '导出',
          tooltipLanguageRes: {
            lanResTag: 'TBB.TOOLTIP.*.EXPORT',
          },
          showCaption: true,
          showIcon: true,
          id: 'tbitem3',
        },
        {
          itemType: 'SEPERATOR',
          id: 'tbitem17',
        },
        {
          actionLevel: 100,
          detoolbarItems: [
            {
              actionLevel: 100,
              noPrivDisplayMode: 2,
              uiactionId: 'gridview_importbar',
              valid: true,
              caption: '数据导入',
              itemType: 'DEUIACTION',
              sysImage: {
                cssClass: 'fa fa-upload',
                glyph: 'xf093@FontAwesome',
              },
              tooltip: '数据导入',
              showCaption: true,
              showIcon: true,
              id: 'tbitem25',
            },
          ],
          valid: true,
          caption: '其它',
          itemType: 'ITEMS',
          tooltip: '其它',
          showCaption: true,
          showIcon: true,
          id: 'tbitem20',
        },
      ],
      xdataControlName: 'grid',
      codeName: 'grid_view_toolbar',
      controlType: 'TOOLBAR',
      logicName: '工具栏模板（默认表格界面）',
      appDataEntityId: 'web.region',
      controlParam: {
        id: 'toolbar',
      },
      modelId: 'be13efa10085e0f52c5770d1b73c1fe5',
      modelType: 'PSDETOOLBAR',
      name: 'toolbar',
      id: 'grid_view_toolbar',
    },
    {
      capLanguageRes: {
        lanResTag: 'DE.LNAME.REGION',
      },
      caption: '区划表格视图',
      codeName: 'grid_view_captionbar',
      controlType: 'CAPTIONBAR',
      appDataEntityId: 'web.region',
      controlParam: {},
      name: 'captionbar',
      id: 'grid_view_captionbar',
    },
  ],
  viewLayoutPanel: {
    layoutBodyOnly: true,
    useDefaultLayout: true,
    layoutPanel: true,
    codeName: 'layoutpanel',
    controlStyle: 'APPDEGRIDVIEW',
    controlType: 'VIEWLAYOUTPANEL',
    appDataEntityId: 'web.region',
    controlParam: {},
    id: 'layoutpanel',
  },
  title: '区划表格视图',
  viewStyle: 'DEFAULT',
  viewType: 'DEGRIDVIEW',
  enableDP: true,
  showCaptionBar: true,
  modelId: '7796d5c9cd8062b311d288fd3fa66fe3',
  modelType: 'PSAPPDEVIEW',
  name: 'REGIONGridView',
  id: 'web.region_grid_view',
};
