export default {
  sideBarLayout: 'LEFT',
  showDataInfoBar: true,
  loadDefault: true,
  deviewCodeName: 'list_exp_view',
  deviewId: '10c1c12a8451abe80dea0478eb673f7b',
  accUserMode: 3,
  capLanguageRes: {
    lanResTag: 'DE.LNAME.REGION',
  },
  caption: '列表导航',
  codeName: 'region_list_exp_view',
  appDataEntityId: 'web.region',
  appViewEngines: [
    {
      engineCat: 'VIEW',
      engineType: 'ListExpView',
      id: 'engine',
    },
  ],
  appViewLogics: [
    {
      logicTrigger: 'CUSTOM',
      logicType: 'APPUILOGIC',
      builtinAppUILogic: {
        actionAfterWizard: 'DEFAULT',
        builtinLogic: true,
        logicType: 'PREDEFINED',
        viewLogicType: 'APP_NEWDATA',
        id: '新建数据',
      },
      builtinLogic: true,
      id: 'newdata',
    },
    {
      logicTrigger: 'CUSTOM',
      logicType: 'APPUILOGIC',
      builtinAppUILogic: {
        editMode: true,
        builtinLogic: true,
        logicType: 'PREDEFINED',
        viewLogicType: 'APP_OPENDATA',
        id: '打开数据',
      },
      builtinLogic: true,
      id: 'opendata',
    },
  ],
  appViewMsgGroupId: 'list_exp_view_group',
  controls: [
    {
      xdataControlName: 'listexpbar_list',
      enableCounter: true,
      showTitleBar: true,
      autoLoad: true,
      showBusyIndicator: true,
      appViewRefs: [
        {
          realOpenMode: 'POPUPMODAL',
          realTitle: '区划信息',
          refAppViewId: 'web.region_info_view',
          name: 'EXPITEM:DEFAULT',
          id: 'expitem:default',
        },
      ],
      controls: [
        {
          groupMode: 'NONE',
          groupStyle: 'DEFAULT',
          itemLayoutPanel: {
            layoutMode: 'TABLE_24COL',
            layout: {
              columnCount: 24,
              layout: 'TABLE_24COL',
            },
            rootPanelItems: [
              {
                actionGroupExtractMode: 'ITEM',
                panelItems: [
                  {
                    actionGroupExtractMode: 'ITEM',
                    panelItems: [
                      {
                        rawItem: {
                          sysImage: {
                            rawContent:
                              '<svg id="图层_2" data-name="图层 2" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 45.05908 45.05914"><defs><style>.cls-1{fill:#01b0ff;}</style></defs><title>ibizlab. 2</title><path class="cls-1" d="M1.64777,456.35452v45.05914H46.70685V456.35452Zm39.92407,3.86188-9.51965,19.60479L11.59913,460.1221ZM4.35572,497.13931v-34.424c8.37353,26.80664,17.53088,34.424,17.53088,34.424ZM17.424,472.06509l12.64337,12.21838-5.52484,9.77466S16.25531,478.54611,17.424,472.06509Zm9.031,25.07422,6.58728-9.031,7.64978,9.031Zm16.71912-2.99152-7.54029-9.61389,7.63453-13.10132Z" transform="translate(-1.64777 -456.35452)"/></svg>',
                          },
                          contentType: 'IMAGE',
                          predefinedType: 'STATIC_IMAGE',
                          rawItemHeight: 32,
                          rawItemWidth: 32,
                          id: 'static_image',
                        },
                        caption: '图片',
                        contentHeight: 32,
                        contentWidth: 32,
                        height: 32,
                        itemStyle: 'DEFAULT',
                        itemType: 'RAWITEM',
                        layoutPos: {
                          shrink: 1,
                          height: 32,
                          heightMode: 'PX',
                          layout: 'FLEX',
                          width: 32,
                          widthMode: 'PX',
                        },
                        sysImage: {
                          rawContent:
                            '<svg id="图层_2" data-name="图层 2" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 45.05908 45.05914"><defs><style>.cls-1{fill:#01b0ff;}</style></defs><title>ibizlab. 2</title><path class="cls-1" d="M1.64777,456.35452v45.05914H46.70685V456.35452Zm39.92407,3.86188-9.51965,19.60479L11.59913,460.1221ZM4.35572,497.13931v-34.424c8.37353,26.80664,17.53088,34.424,17.53088,34.424ZM17.424,472.06509l12.64337,12.21838-5.52484,9.77466S16.25531,478.54611,17.424,472.06509Zm9.031,25.07422,6.58728-9.031,7.64978,9.031Zm16.71912-2.99152-7.54029-9.61389,7.63453-13.10132Z" transform="translate(-1.64777 -456.35452)"/></svg>',
                        },
                        width: 32,
                        showCaption: true,
                        id: 'static_image',
                      },
                      {
                        actionGroupExtractMode: 'ITEM',
                        panelItems: [
                          {
                            editor: {
                              halign: 'LEFT',
                              renderMode: 'TEXT_DYNAMIC',
                              valign: 'MIDDLE',
                              wrapMode: 'NOWRAP',
                              editorType: 'SPAN',
                              predefinedType: 'FIELD_TEXT_DYNAMIC',
                              valueType: 'SIMPLE',
                              editable: true,
                              id: 'name',
                            },
                            viewFieldName: 'name',
                            allowEmpty: true,
                            caption: '文本(动态)',
                            itemStyle: 'DEFAULT',
                            itemType: 'FIELD',
                            layoutPos: {
                              shrink: 1,
                              layout: 'FLEX',
                            },
                            id: 'name',
                          },
                          {
                            editor: {
                              halign: 'LEFT',
                              renderMode: 'TEXT_DYNAMIC',
                              valign: 'MIDDLE',
                              wrapMode: 'NOWRAP',
                              editorType: 'SPAN',
                              predefinedType: 'FIELD_TEXT_DYNAMIC',
                              valueType: 'SIMPLE',
                              editable: true,
                              id: 'code',
                            },
                            viewFieldName: 'code',
                            allowEmpty: true,
                            caption: '文本(动态)',
                            itemStyle: 'DEFAULT',
                            itemType: 'FIELD',
                            layoutPos: {
                              shrink: 1,
                              layout: 'FLEX',
                            },
                            id: 'code',
                          },
                        ],
                        layout: {
                          align: 'center',
                          dir: 'column',
                          layout: 'FLEX',
                        },
                        dataRegionType: 'INHERIT',
                        caption: '容器',
                        itemStyle: 'DEFAULT',
                        itemType: 'CONTAINER',
                        layoutPos: {
                          shrink: 1,
                          layout: 'FLEX',
                          spacingLeft: 'OUTERMEDIUM',
                        },
                        id: 'container2',
                      },
                    ],
                    layout: {
                      align: 'center',
                      dir: 'row',
                      layout: 'FLEX',
                      valign: 'center',
                    },
                    dataRegionType: 'INHERIT',
                    caption: '容器',
                    itemStyle: 'DEFAULT',
                    itemType: 'CONTAINER',
                    layoutPos: {
                      shrink: 1,
                      layout: 'FLEX',
                    },
                    id: 'container',
                  },
                  {
                    editor: {
                      halign: 'LEFT',
                      renderMode: 'TEXT_DYNAMIC',
                      valign: 'MIDDLE',
                      wrapMode: 'NOWRAP',
                      editorType: 'SPAN',
                      predefinedType: 'FIELD_TEXT_DYNAMIC',
                      valueType: 'SIMPLE',
                      editable: true,
                      id: 'path',
                    },
                    viewFieldName: 'path',
                    allowEmpty: true,
                    caption: '文本(动态)',
                    itemStyle: 'DEFAULT',
                    itemType: 'FIELD',
                    layoutPos: {
                      shrink: 1,
                      layout: 'FLEX',
                    },
                    id: 'path',
                  },
                  {
                    actionGroupExtractMode: 'ITEM',
                    panelItems: [
                      {
                        editor: {
                          halign: 'LEFT',
                          renderMode: 'TEXT_DYNAMIC',
                          valign: 'MIDDLE',
                          wrapMode: 'NOWRAP',
                          appCodeListId: 'web.mock__cl_status',
                          editorType: 'SPAN',
                          predefinedType: 'FIELD_TEXT_DYNAMIC',
                          valueType: 'SIMPLE',
                          editable: true,
                          id: 'status',
                        },
                        viewFieldName: 'status',
                        allowEmpty: true,
                        convertToCodeItemText: true,
                        caption: '文本(动态)',
                        itemStyle: 'DEFAULT',
                        itemType: 'FIELD',
                        layoutPos: {
                          shrink: 1,
                          layout: 'FLEX',
                        },
                        id: 'status',
                      },
                    ],
                    layout: {
                      layout: 'FLEX',
                    },
                    dataRegionType: 'INHERIT',
                    caption: '容器',
                    itemStyle: 'DEFAULT',
                    itemType: 'CONTAINER',
                    layoutPos: {
                      shrink: 1,
                      layout: 'FLEX',
                    },
                    id: 'container3',
                  },
                ],
                layout: {
                  align: 'space-between',
                  dir: 'row',
                  layout: 'FLEX',
                  valign: 'center',
                },
                dataRegionType: 'INHERIT',
                caption: '容器',
                itemStyle: 'DEFAULT',
                itemType: 'CONTAINER',
                layoutPos: {
                  colMD: 24,
                  layout: 'TABLE_24COL',
                },
                id: 'container1',
              },
            ],
            codeName: 'usr0513913681',
            controlType: 'PANEL',
            logicName: 'List_列表项面板',
            appDataEntityId: 'web.region',
            controlParam: {},
            modelId: '4c1e1505d20810e6a39df6c21041b0c4',
            modelType: 'PSSYSVIEWPANEL',
            name: 'listexpbar_list_itempanel',
            id: 'web.region.usr0513913681',
          },
          delistDataItems: [
            {
              appDEFieldId: 'id',
              dataType: 25,
              id: 'srfkey',
            },
            {
              appDEFieldId: 'name',
              dataType: 25,
              id: 'srfmajortext',
            },
            {
              appDEFieldId: 'parent_id',
              dataType: 25,
              id: 'parent_id',
            },
          ],
          pagingSize: 1000,
          showHeader: true,
          navAppViewId: 'web.region_info_view',
          navViewPos: 'NONE',
          createControlAction: {
            appDEMethodId: 'create',
            appDataEntityId: 'web.region',
            id: 'create',
          },
          fetchControlAction: {
            appDEMethodId: 'fetch_default',
            appDataEntityId: 'web.region',
            id: 'fetch',
          },
          getControlAction: {
            appDEMethodId: 'get',
            appDataEntityId: 'web.region',
            id: 'load',
          },
          removeControlAction: {
            appDEMethodId: 'remove',
            appDataEntityId: 'web.region',
            id: 'remove',
          },
          updateControlAction: {
            appDEMethodId: 'update',
            appDataEntityId: 'web.region',
            id: 'update',
          },
          autoLoad: true,
          showBusyIndicator: true,
          codeName: 'list_exp_view_list',
          controlType: 'LIST',
          logicName: 'List',
          appDataEntityId: 'web.region',
          controlLogics: [
            {
              eventNames: 'SELECTIONCHANGE',
              logicTag: 'listexpbar_list',
              logicType: 'CUSTOM',
              triggerType: 'CTRLEVENT',
              id: 'listexpbar_selectionchange',
            },
            {
              eventNames: 'LOAD',
              logicTag: 'listexpbar_list',
              logicType: 'CUSTOM',
              triggerType: 'CTRLEVENT',
              id: 'listexpbar_load',
            },
          ],
          controlParam: {
            id: 'listexpbar_list',
          },
          modelId: '955f01864669ff8a94a1b6914fd245c1',
          modelType: 'PSDELIST',
          name: 'listexpbar_list',
          id: 'web.region.list_exp_view_list',
        },
      ],
      codeName: 'list_exp_view_listexpbar',
      controlType: 'LISTEXPBAR',
      appDataEntityId: 'web.region',
      controlParam: {
        id: 'listexpbar',
      },
      modelId: 'bebf4a0caa4a820193987a252c470499_listexpbar',
      modelType: 'PSEXPBAR',
      name: 'listexpbar',
      id: 'list_exp_view_listexpbar',
    },
    {
      groupMode: 'SINGLE',
      quickSearchMode: 1,
      enableQuickSearch: true,
      controlType: 'SEARCHBAR',
      appDataEntityId: 'web.region',
      controlParam: {
        id: 'searchbar',
      },
      id: 'searchbar',
    },
    {
      capLanguageRes: {
        lanResTag: 'DE.LNAME.REGION',
      },
      caption: '列表导航',
      codeName: 'list_exp_view_captionbar',
      controlType: 'CAPTIONBAR',
      appDataEntityId: 'web.region',
      controlParam: {},
      name: 'captionbar',
      id: 'list_exp_view_captionbar',
    },
  ],
  viewLayoutPanel: {
    layoutBodyOnly: true,
    useDefaultLayout: true,
    layoutPanel: true,
    codeName: 'layoutpanel',
    controlStyle: 'APPDELISTEXPVIEW',
    controlType: 'VIEWLAYOUTPANEL',
    appDataEntityId: 'web.region',
    controlParam: {},
    id: 'layoutpanel',
  },
  title: '列表导航',
  viewStyle: 'DEFAULT',
  viewType: 'DELISTEXPVIEW',
  enableDP: true,
  showCaptionBar: false,
  modelId: 'bebf4a0caa4a820193987a252c470499',
  modelType: 'PSAPPDEVIEW',
  name: 'REGIONlist_exp_view',
  id: 'web.region_list_exp_view',
};
