export default {
  deviewCodeName: 'card_nav',
  deviewId: 'a889244ddf083f1aa6b0d54cd3e9b8c4',
  accUserMode: 2,
  capLanguageRes: {
    lanResTag: 'DE.LNAME.REGION',
  },
  caption: '卡片导航',
  codeName: 'region_card_nav',
  appDataEntityId: 'web.region',
  viewLayoutPanel: {
    layoutBodyOnly: true,
    viewProxyMode: true,
    layoutMode: 'FLEX',
    layout: {
      layout: 'FLEX',
    },
    rootPanelItems: [
      {
        actionGroupExtractMode: 'ITEM',
        panelItems: [
          {
            actionGroupExtractMode: 'ITEM',
            panelItems: [
              {
                caption: '数据视图',
                itemStyle: 'DEFAULT',
                itemType: 'CTRLPOS',
                layoutPos: {
                  shrink: 1,
                  layout: 'FLEX',
                },
                showCaption: true,
                id: 'dataview',
              },
            ],
            predefinedType: 'CONTAINER_GROUP',
            layout: {
              layout: 'FLEX',
            },
            dataRegionType: 'INHERIT',
            caption: '右方（内置导航宽度800）',
            itemStyle: 'DEFAULT',
            itemType: 'CONTAINER',
            layoutPos: {
              shrink: 1,
              layout: 'FLEX',
            },
            showCaption: true,
            id: 'container_group',
          },
          {
            actionGroupExtractMode: 'ITEM',
            panelItems: [
              {
                caption: '数据视图',
                contentHeight: 800,
                height: 800,
                itemStyle: 'DEFAULT',
                itemType: 'CTRLPOS',
                layoutPos: {
                  shrink: 1,
                  height: 800,
                  heightMode: 'PX',
                  layout: 'FLEX',
                },
                showCaption: true,
                id: 'dataview1',
              },
            ],
            predefinedType: 'CONTAINER_GROUP',
            layout: {
              layout: 'FLEX',
            },
            dataRegionType: 'INHERIT',
            caption: '下方(内置导航高度500)',
            itemStyle: 'DEFAULT',
            itemType: 'CONTAINER',
            layoutPos: {
              shrink: 1,
              layout: 'FLEX',
            },
            showCaption: true,
            id: 'container_group1',
          },
        ],
        layout: {
          layout: 'FLEX',
        },
        dataRegionType: 'INHERIT',
        caption: '容器',
        itemStyle: 'DEFAULT',
        itemType: 'CONTAINER',
        layoutPos: {
          shrink: 1,
          layout: 'FLEX',
        },
        id: 'container',
      },
    ],
    layoutPanel: true,
    controls: [
      {
        cardHeight: 80,
        cardWidth: 180,
        groupMode: 'NONE',
        groupStyle: 'DEFAULT',
        itemLayoutPanel: {
          layoutMode: 'FLEX',
          layout: {
            layout: 'FLEX',
          },
          rootPanelItems: [
            {
              actionGroupExtractMode: 'ITEM',
              panelItems: [
                {
                  actionGroupExtractMode: 'ITEM',
                  panelItems: [
                    {
                      editor: {
                        halign: 'LEFT',
                        renderMode: 'TEXT_DYNAMIC',
                        valign: 'MIDDLE',
                        wrapMode: 'NOWRAP',
                        editorType: 'SPAN',
                        predefinedType: 'FIELD_TEXT_DYNAMIC',
                        valueType: 'SIMPLE',
                        editable: true,
                        id: 'name',
                      },
                      allowEmpty: true,
                      caption: '文本(动态)',
                      itemStyle: 'DEFAULT',
                      itemType: 'FIELD',
                      layoutPos: {
                        shrink: 1,
                        layout: 'FLEX',
                      },
                      id: 'name',
                    },
                    {
                      editor: {
                        halign: 'LEFT',
                        renderMode: 'TEXT_DYNAMIC',
                        valign: 'MIDDLE',
                        wrapMode: 'NOWRAP',
                        editorType: 'SPAN',
                        predefinedType: 'FIELD_TEXT_DYNAMIC',
                        valueType: 'SIMPLE',
                        editable: true,
                        id: 'code',
                      },
                      allowEmpty: true,
                      caption: '文本(动态)',
                      itemStyle: 'DEFAULT',
                      itemType: 'FIELD',
                      layoutPos: {
                        shrink: 1,
                        layout: 'FLEX',
                      },
                      id: 'code',
                    },
                  ],
                  layout: {
                    align: 'space-between',
                    dir: 'row',
                    layout: 'FLEX',
                  },
                  dataRegionType: 'INHERIT',
                  caption: '容器',
                  itemStyle: 'DEFAULT',
                  itemType: 'CONTAINER',
                  layoutPos: {
                    shrink: 1,
                    layout: 'FLEX',
                  },
                  id: 'container',
                },
                {
                  actionGroupExtractMode: 'ITEM',
                  panelItems: [
                    {
                      editor: {
                        halign: 'LEFT',
                        renderMode: 'TEXT_DYNAMIC',
                        valign: 'MIDDLE',
                        wrapMode: 'NOWRAP',
                        appCodeListId: 'web.mock__cl_status',
                        editorType: 'SPAN',
                        predefinedType: 'FIELD_TEXT_DYNAMIC',
                        valueType: 'SIMPLE',
                        editable: true,
                        id: 'status',
                      },
                      viewFieldName: 'status',
                      allowEmpty: true,
                      convertToCodeItemText: true,
                      caption: '文本(动态)',
                      itemStyle: 'DEFAULT',
                      itemType: 'FIELD',
                      layoutPos: {
                        shrink: 1,
                        layout: 'FLEX',
                      },
                      id: 'status',
                    },
                  ],
                  layout: {
                    align: 'flex-start',
                    dir: 'row-reverse',
                    layout: 'FLEX',
                  },
                  dataRegionType: 'INHERIT',
                  caption: '容器',
                  itemStyle: 'DEFAULT',
                  itemType: 'CONTAINER',
                  layoutPos: {
                    shrink: 1,
                    layout: 'FLEX',
                  },
                  id: 'container2',
                },
              ],
              layout: {
                layout: 'FLEX',
              },
              dataRegionType: 'INHERIT',
              itemStyle: 'DEFAULT',
              itemType: 'CONTAINER',
              layoutPos: {
                shrink: 1,
                layout: 'FLEX',
              },
              id: 'container1',
            },
          ],
          layoutPanel: true,
          codeName: 'auto21837017',
          controlType: 'PANEL',
          logicName: 'card_nav_1卡片视图',
          appDataEntityId: 'web.region',
          controlParam: {},
          modelId: 'e6d0050b0be25e67fe5979345d3e4697',
          modelType: 'PSSYSVIEWPANEL',
          name: 'itemlayoutpanel',
          id: 'web.region.auto21837017',
        },
        dedataViewDataItems: [
          {
            appDEFieldId: 'id',
            dataType: 25,
            id: 'srfkey',
          },
          {
            appDEFieldId: 'name',
            dataType: 25,
            id: 'srfmajortext',
          },
        ],
        pagingMode: 1,
        pagingSize: 20,
        enablePagingBar: true,
        singleSelect: true,
        navAppViewId: 'web.region_info_view',
        navViewPos: 'RIGHT',
        navViewWidth: 800,
        createControlAction: {
          appDEMethodId: 'create',
          appDataEntityId: 'web.region',
          id: 'create',
        },
        fetchControlAction: {
          appDEMethodId: 'fetch_default',
          appDataEntityId: 'web.region',
          id: 'fetch',
        },
        getControlAction: {
          appDEMethodId: 'get',
          appDataEntityId: 'web.region',
          id: 'load',
        },
        removeControlAction: {
          appDEMethodId: 'remove',
          appDataEntityId: 'web.region',
          id: 'remove',
        },
        updateControlAction: {
          appDEMethodId: 'update',
          appDataEntityId: 'web.region',
          id: 'update',
        },
        autoLoad: true,
        showBusyIndicator: true,
        codeName: 'card_nav1',
        controlType: 'DATAVIEW',
        logicName: 'card_nav_1',
        appDataEntityId: 'web.region',
        controlParam: {
          id: 'dataview',
        },
        modelId: '76d02b9492f3c4a8ae6f67bdae282cf9',
        modelType: 'PSDEDATAVIEW',
        name: 'dataview',
        id: 'web.region.card_nav1',
      },
      {
        cardHeight: 80,
        cardWidth: 180,
        groupMode: 'NONE',
        groupStyle: 'DEFAULT',
        itemLayoutPanel: {
          layoutMode: 'FLEX',
          layout: {
            layout: 'FLEX',
          },
          rootPanelItems: [
            {
              actionGroupExtractMode: 'ITEM',
              panelItems: [
                {
                  actionGroupExtractMode: 'ITEM',
                  panelItems: [
                    {
                      editor: {
                        halign: 'LEFT',
                        renderMode: 'TEXT_DYNAMIC',
                        valign: 'MIDDLE',
                        wrapMode: 'NOWRAP',
                        editorType: 'SPAN',
                        predefinedType: 'FIELD_TEXT_DYNAMIC',
                        valueType: 'SIMPLE',
                        editable: true,
                        id: 'name',
                      },
                      allowEmpty: true,
                      caption: '文本(动态)',
                      itemStyle: 'DEFAULT',
                      itemType: 'FIELD',
                      layoutPos: {
                        shrink: 1,
                        layout: 'FLEX',
                      },
                      id: 'name',
                    },
                    {
                      editor: {
                        halign: 'LEFT',
                        renderMode: 'TEXT_DYNAMIC',
                        valign: 'MIDDLE',
                        wrapMode: 'NOWRAP',
                        editorType: 'SPAN',
                        predefinedType: 'FIELD_TEXT_DYNAMIC',
                        valueType: 'SIMPLE',
                        editable: true,
                        id: 'code',
                      },
                      allowEmpty: true,
                      caption: '文本(动态)',
                      itemStyle: 'DEFAULT',
                      itemType: 'FIELD',
                      layoutPos: {
                        shrink: 1,
                        layout: 'FLEX',
                      },
                      id: 'code',
                    },
                  ],
                  layout: {
                    align: 'space-between',
                    dir: 'row',
                    layout: 'FLEX',
                  },
                  dataRegionType: 'INHERIT',
                  caption: '容器',
                  itemStyle: 'DEFAULT',
                  itemType: 'CONTAINER',
                  layoutPos: {
                    shrink: 1,
                    layout: 'FLEX',
                  },
                  id: 'container',
                },
                {
                  actionGroupExtractMode: 'ITEM',
                  panelItems: [
                    {
                      editor: {
                        halign: 'LEFT',
                        renderMode: 'TEXT_DYNAMIC',
                        valign: 'MIDDLE',
                        wrapMode: 'NOWRAP',
                        appCodeListId: 'web.mock__cl_status',
                        editorType: 'SPAN',
                        predefinedType: 'FIELD_TEXT_DYNAMIC',
                        valueType: 'SIMPLE',
                        editable: true,
                        id: 'status',
                      },
                      viewFieldName: 'status',
                      allowEmpty: true,
                      convertToCodeItemText: true,
                      caption: '文本(动态)',
                      itemStyle: 'DEFAULT',
                      itemType: 'FIELD',
                      layoutPos: {
                        shrink: 1,
                        layout: 'FLEX',
                      },
                      id: 'status',
                    },
                  ],
                  layout: {
                    align: 'flex-start',
                    dir: 'row-reverse',
                    layout: 'FLEX',
                  },
                  dataRegionType: 'INHERIT',
                  caption: '容器',
                  itemStyle: 'DEFAULT',
                  itemType: 'CONTAINER',
                  layoutPos: {
                    shrink: 1,
                    layout: 'FLEX',
                  },
                  id: 'container2',
                },
              ],
              layout: {
                layout: 'FLEX',
              },
              dataRegionType: 'INHERIT',
              itemStyle: 'DEFAULT',
              itemType: 'CONTAINER',
              layoutPos: {
                shrink: 1,
                layout: 'FLEX',
              },
              id: 'container1',
            },
          ],
          layoutPanel: true,
          codeName: 'auto21837017',
          controlType: 'PANEL',
          logicName: 'card_nav_1卡片视图',
          appDataEntityId: 'web.region',
          controlParam: {},
          modelId: 'e6d0050b0be25e67fe5979345d3e4697',
          modelType: 'PSSYSVIEWPANEL',
          name: 'itemlayoutpanel',
          id: 'web.region.auto21837017',
        },
        dedataViewDataItems: [
          {
            appDEFieldId: 'id',
            dataType: 25,
            id: 'srfkey',
          },
          {
            appDEFieldId: 'name',
            dataType: 25,
            id: 'srfmajortext',
          },
        ],
        pagingMode: 1,
        pagingSize: 10,
        enablePagingBar: true,
        singleSelect: true,
        navAppViewId: 'web.region_info_view',
        navViewHeight: 500,
        navViewPos: 'BOTTOM',
        createControlAction: {
          appDEMethodId: 'create',
          appDataEntityId: 'web.region',
          id: 'create',
        },
        fetchControlAction: {
          appDEMethodId: 'fetch_default',
          appDataEntityId: 'web.region',
          id: 'fetch',
        },
        getControlAction: {
          appDEMethodId: 'get',
          appDataEntityId: 'web.region',
          id: 'load',
        },
        removeControlAction: {
          appDEMethodId: 'remove',
          appDataEntityId: 'web.region',
          id: 'remove',
        },
        updateControlAction: {
          appDEMethodId: 'update',
          appDataEntityId: 'web.region',
          id: 'update',
        },
        autoLoad: true,
        showBusyIndicator: true,
        codeName: 'card_nav2',
        controlType: 'DATAVIEW',
        logicName: 'card_nav_2',
        appDataEntityId: 'web.region',
        controlParam: {
          id: 'dataview1',
        },
        modelId: '14879d76de978fadf8799ec64c7aa303',
        modelType: 'PSDEDATAVIEW',
        name: 'dataview1',
        id: 'web.region.card_nav2',
      },
      {
        capLanguageRes: {
          lanResTag: 'DE.LNAME.REGION',
        },
        caption: '卡片导航',
        codeName: 'card_nav_captionbar',
        controlType: 'CAPTIONBAR',
        appDataEntityId: 'web.region',
        controlParam: {},
        name: 'captionbar',
        id: 'card_nav_captionbar',
      },
    ],
    codeName: 'a8154c531530463d3a5',
    controlType: 'VIEWLAYOUTPANEL',
    logicName: 'card_nav',
    appDataEntityId: 'web.region',
    controlParam: {},
    modelId: 'd66564168213f858431343bcbc5d5d7c',
    modelType: 'PSSYSVIEWLAYOUTPANEL',
    name: 'layoutpanel',
    id: 'a8154c531530463d3a5',
  },
  title: '卡片导航',
  viewStyle: 'DEFAULT',
  viewType: 'DECUSTOMVIEW',
  enableDP: true,
  showCaptionBar: false,
  modelId: '0ffadc477bd1f28abd28fd7eedcf3f7c',
  modelType: 'PSAPPDEVIEW',
  name: 'REGIONcard_nav',
  id: 'web.region_card_nav',
};
