export default {
  sideBarLayout: 'LEFT',
  showDataInfoBar: true,
  loadDefault: true,
  deviewCodeName: 'data_view_exp_view',
  deviewId: 'a42c25f9f3e5d5e36b7ad4476d731e65',
  accUserMode: 2,
  capLanguageRes: {
    lanResTag: 'DE.LNAME.REGION',
  },
  caption: '卡片导航',
  codeName: 'region_data_view_exp_view',
  appDataEntityId: 'web.region',
  appViewEngines: [
    {
      engineCat: 'VIEW',
      engineType: 'DataViewExpView',
      id: 'engine',
    },
  ],
  appViewLogics: [
    {
      logicTrigger: 'CUSTOM',
      logicType: 'APPUILOGIC',
      builtinAppUILogic: {
        actionAfterWizard: 'DEFAULT',
        builtinLogic: true,
        logicType: 'PREDEFINED',
        viewLogicType: 'APP_NEWDATA',
        id: '新建数据',
      },
      builtinLogic: true,
      id: 'newdata',
    },
    {
      logicTrigger: 'CUSTOM',
      logicType: 'APPUILOGIC',
      builtinAppUILogic: {
        editMode: true,
        builtinLogic: true,
        logicType: 'PREDEFINED',
        viewLogicType: 'APP_OPENDATA',
        id: '打开数据',
      },
      builtinLogic: true,
      id: 'opendata',
    },
  ],
  controls: [
    {
      xdataControlName: 'dataviewexpbar_dataview',
      enableCounter: true,
      showTitleBar: true,
      autoLoad: true,
      showBusyIndicator: true,
      appViewRefs: [
        {
          realOpenMode: 'POPUPMODAL',
          realTitle: '区划信息',
          refAppViewId: 'web.region_info_view',
          name: 'EXPITEM:DEFAULT',
          id: 'expitem:default',
        },
      ],
      controls: [
        {
          cardHeight: 80,
          cardWidth: 180,
          groupMode: 'NONE',
          groupStyle: 'DEFAULT',
          itemLayoutPanel: {
            layoutMode: 'FLEX',
            layout: {
              layout: 'FLEX',
            },
            rootPanelItems: [
              {
                actionGroupExtractMode: 'ITEM',
                panelItems: [
                  {
                    actionGroupExtractMode: 'ITEM',
                    panelItems: [
                      {
                        editor: {
                          halign: 'LEFT',
                          renderMode: 'TEXT_DYNAMIC',
                          valign: 'MIDDLE',
                          wrapMode: 'NOWRAP',
                          editorType: 'SPAN',
                          predefinedType: 'FIELD_TEXT_DYNAMIC',
                          valueType: 'SIMPLE',
                          editable: true,
                          id: 'name',
                        },
                        allowEmpty: true,
                        caption: '文本(动态)',
                        itemStyle: 'DEFAULT',
                        itemType: 'FIELD',
                        layoutPos: {
                          shrink: 1,
                          layout: 'FLEX',
                        },
                        id: 'name',
                      },
                      {
                        editor: {
                          halign: 'LEFT',
                          renderMode: 'TEXT_DYNAMIC',
                          valign: 'MIDDLE',
                          wrapMode: 'NOWRAP',
                          editorType: 'SPAN',
                          predefinedType: 'FIELD_TEXT_DYNAMIC',
                          valueType: 'SIMPLE',
                          editable: true,
                          id: 'code',
                        },
                        allowEmpty: true,
                        caption: '文本(动态)',
                        itemStyle: 'DEFAULT',
                        itemType: 'FIELD',
                        layoutPos: {
                          shrink: 1,
                          layout: 'FLEX',
                        },
                        id: 'code',
                      },
                    ],
                    layout: {
                      align: 'space-between',
                      dir: 'row',
                      layout: 'FLEX',
                    },
                    dataRegionType: 'INHERIT',
                    caption: '容器',
                    itemStyle: 'DEFAULT',
                    itemType: 'CONTAINER',
                    layoutPos: {
                      shrink: 1,
                      layout: 'FLEX',
                    },
                    id: 'container',
                  },
                  {
                    actionGroupExtractMode: 'ITEM',
                    panelItems: [
                      {
                        editor: {
                          halign: 'LEFT',
                          renderMode: 'TEXT_DYNAMIC',
                          valign: 'MIDDLE',
                          wrapMode: 'NOWRAP',
                          appCodeListId: 'web.mock__cl_status',
                          editorType: 'SPAN',
                          predefinedType: 'FIELD_TEXT_DYNAMIC',
                          valueType: 'SIMPLE',
                          editable: true,
                          id: 'status',
                        },
                        viewFieldName: 'status',
                        allowEmpty: true,
                        convertToCodeItemText: true,
                        caption: '文本(动态)',
                        itemStyle: 'DEFAULT',
                        itemType: 'FIELD',
                        layoutPos: {
                          shrink: 1,
                          layout: 'FLEX',
                        },
                        id: 'status',
                      },
                    ],
                    layout: {
                      align: 'flex-start',
                      dir: 'row-reverse',
                      layout: 'FLEX',
                    },
                    dataRegionType: 'INHERIT',
                    caption: '容器',
                    itemStyle: 'DEFAULT',
                    itemType: 'CONTAINER',
                    layoutPos: {
                      shrink: 1,
                      layout: 'FLEX',
                    },
                    id: 'container2',
                  },
                ],
                layout: {
                  layout: 'FLEX',
                },
                dataRegionType: 'INHERIT',
                itemStyle: 'DEFAULT',
                itemType: 'CONTAINER',
                layoutPos: {
                  shrink: 1,
                  layout: 'FLEX',
                },
                id: 'container1',
              },
            ],
            layoutPanel: true,
            codeName: 'auto21837017',
            controlType: 'PANEL',
            logicName: 'card_nav_1卡片视图',
            appDataEntityId: 'web.region',
            controlParam: {},
            modelId: 'e6d0050b0be25e67fe5979345d3e4697',
            modelType: 'PSSYSVIEWPANEL',
            name: 'itemlayoutpanel',
            id: 'web.region.auto21837017',
          },
          dedataViewDataItems: [
            {
              appDEFieldId: 'id',
              dataType: 25,
              id: 'srfkey',
            },
            {
              appDEFieldId: 'name',
              dataType: 25,
              id: 'srfmajortext',
            },
          ],
          pagingMode: 1,
          pagingSize: 20,
          enablePagingBar: true,
          singleSelect: true,
          navAppViewId: 'web.region_info_view',
          navViewPos: 'NONE',
          createControlAction: {
            appDEMethodId: 'create',
            appDataEntityId: 'web.region',
            id: 'create',
          },
          fetchControlAction: {
            appDEMethodId: 'fetch_default',
            appDataEntityId: 'web.region',
            id: 'fetch',
          },
          getControlAction: {
            appDEMethodId: 'get',
            appDataEntityId: 'web.region',
            id: 'load',
          },
          removeControlAction: {
            appDEMethodId: 'remove',
            appDataEntityId: 'web.region',
            id: 'remove',
          },
          updateControlAction: {
            appDEMethodId: 'update',
            appDataEntityId: 'web.region',
            id: 'update',
          },
          autoLoad: true,
          showBusyIndicator: true,
          codeName: 'data_view_exp_view_data_view',
          controlType: 'DATAVIEW',
          logicName: 'data_view_exp_view_DataView',
          appDataEntityId: 'web.region',
          controlLogics: [
            {
              eventNames: 'SELECTIONCHANGE',
              logicTag: 'dataviewexpbar_dataview',
              logicType: 'CUSTOM',
              triggerType: 'CTRLEVENT',
              id: 'dataviewexpbar_selectionchange',
            },
            {
              eventNames: 'LOAD',
              logicTag: 'dataviewexpbar_dataview',
              logicType: 'CUSTOM',
              triggerType: 'CTRLEVENT',
              id: 'dataviewexpbar_load',
            },
          ],
          controlParam: {
            id: 'dataviewexpbar_dataview',
          },
          modelId: 'd0b10344f292eaf6fdd1f21fdaa426b0',
          modelType: 'PSDEDATAVIEW',
          name: 'dataviewexpbar_dataview',
          id: 'web.region.data_view_exp_view_data_view',
        },
      ],
      codeName: 'data_view_exp_view_dataviewexpbar',
      controlType: 'DATAVIEWEXPBAR',
      appDataEntityId: 'web.region',
      controlParam: {
        id: 'dataviewexpbar',
      },
      width: 660,
      modelId: 'cd21cedeaaf3634a731fd0c0dee5eb94_dataviewexpbar',
      modelType: 'PSEXPBAR',
      name: 'dataviewexpbar',
      id: 'data_view_exp_view_dataviewexpbar',
    },
    {
      groupMode: 'SINGLE',
      quickSearchMode: 1,
      enableQuickSearch: true,
      controlType: 'SEARCHBAR',
      appDataEntityId: 'web.region',
      controlParam: {
        id: 'searchbar',
      },
      id: 'searchbar',
    },
    {
      capLanguageRes: {
        lanResTag: 'DE.LNAME.REGION',
      },
      caption: '卡片导航',
      codeName: 'data_view_exp_view_captionbar',
      controlType: 'CAPTIONBAR',
      appDataEntityId: 'web.region',
      controlParam: {},
      name: 'captionbar',
      id: 'data_view_exp_view_captionbar',
    },
  ],
  viewLayoutPanel: {
    layoutBodyOnly: true,
    useDefaultLayout: true,
    layoutPanel: true,
    codeName: 'layoutpanel',
    controlStyle: 'APPDEDATAVIEWEXPVIEW',
    controlType: 'VIEWLAYOUTPANEL',
    appDataEntityId: 'web.region',
    controlParam: {},
    id: 'layoutpanel',
  },
  title: '卡片导航',
  viewStyle: 'DEFAULT',
  viewType: 'DEDATAVIEWEXPVIEW',
  enableDP: true,
  showCaptionBar: false,
  modelId: 'cd21cedeaaf3634a731fd0c0dee5eb94',
  modelType: 'PSAPPDEVIEW',
  name: 'REGIONdata_view_exp_view',
  id: 'web.region_data_view_exp_view',
};
