export default {
  gridRowActiveMode: 2,
  xdataControlName: 'grid',
  loadDefault: true,
  deviewCodeName: 'detail_grid_view',
  deviewId: '5e1f377ae7164af5d9eb90753ad1ebbf',
  accUserMode: 2,
  capLanguageRes: {
    lanResTag: 'DE.LNAME.REGION',
  },
  caption: '明细数据',
  codeName: 'region_detail_grid_view',
  appDataEntityId: 'web.region',
  appViewEngines: [
    {
      engineCat: 'VIEW',
      engineType: 'GridView',
      id: 'engine',
    },
  ],
  appViewLogics: [
    {
      logicTrigger: 'CUSTOM',
      logicType: 'APPUILOGIC',
      builtinAppUILogic: {
        actionAfterWizard: 'DEFAULT',
        newDataAppView: {
          openMode: 'POPUPMODAL',
          refAppViewId: 'web.region_edit_view',
        },
        appUILogicRefViews: [
          {
            openMode: 'POPUPMODAL',
            refAppViewId: 'web.region_edit_view',
          },
        ],
        builtinLogic: true,
        logicType: 'PREDEFINED',
        viewLogicType: 'APP_NEWDATA',
        id: '新建数据',
      },
      builtinLogic: true,
      id: 'newdata',
    },
    {
      logicTrigger: 'CUSTOM',
      logicType: 'APPUILOGIC',
      builtinAppUILogic: {
        openDataAppView: {
          refAppViewId: 'web.region_redirect_view',
        },
        editMode: true,
        appUILogicRefViews: [
          {
            refAppViewId: 'web.region_redirect_view',
          },
        ],
        builtinLogic: true,
        logicType: 'PREDEFINED',
        viewLogicType: 'APP_OPENDATA',
        id: '打开数据',
      },
      builtinLogic: true,
      id: 'opendata',
    },
  ],
  appViewRefs: [
    {
      realTitle: '区划数据重定向视图',
      refAppViewId: 'web.region_redirect_view',
      name: 'EDITDATA',
      id: 'editdata',
    },
    {
      realOpenMode: 'POPUPMODAL',
      realTitle: '区划编辑视图',
      refAppViewId: 'web.region_edit_view',
      name: 'NEWDATA',
      id: 'newdata',
    },
  ],
  controls: [
    {
      xdataControlName: 'grid',
      codeName: 'detail_grid_view_toolbar',
      controlType: 'TOOLBAR',
      logicName: '明细数据_工具栏',
      appDataEntityId: 'web.region',
      controlParam: {
        id: 'toolbar',
      },
      modelId: 'd005eafe847b22a27ce631e2ec095870',
      modelType: 'PSDETOOLBAR',
      name: 'toolbar',
      id: 'detail_grid_view_toolbar',
    },
    {
      aggMode: 'NONE',
      columnEnableFilter: 2,
      columnEnableLink: 2,
      groupMode: 'NONE',
      groupStyle: 'DEFAULT',
      degridColumns: [
        {
          clconvertMode: 'NONE',
          dataItemName: 'code',
          excelCaption: '编码',
          appDEFieldId: 'code',
          valueType: 'SIMPLE',
          aggMode: 'NONE',
          align: 'LEFT',
          caption: '编码',
          codeName: 'code',
          columnType: 'DEFGRIDCOLUMN',
          noPrivDisplayMode: 1,
          width: 150,
          widthUnit: 'PX',
          enableSort: true,
          id: 'code',
        },
        {
          clconvertMode: 'NONE',
          dataItemName: 'name',
          excelCaption: '名称',
          appDEFieldId: 'name',
          treeColumnMode: 1,
          valueType: 'SIMPLE',
          enableRowEdit: true,
          aggMode: 'NONE',
          align: 'LEFT',
          capLanguageRes: {
            lanResTag: 'DEF.LNAME.REGION.NAME',
          },
          caption: '名称',
          codeName: 'name',
          columnType: 'DEFGRIDCOLUMN',
          noPrivDisplayMode: 1,
          width: 200,
          widthUnit: 'PX',
          enableSort: true,
          id: 'name',
        },
        {
          clconvertMode: 'NONE',
          dataItemName: 'parent_name',
          excelCaption: '上级区划',
          linkAppViewId: 'web.region_redirect_view',
          linkValueItem: 'parent_id',
          appDEFieldId: 'parent_name',
          treeColumnMode: 8,
          valueType: 'SIMPLE',
          enableLinkView: true,
          enableRowEdit: true,
          aggMode: 'NONE',
          align: 'LEFT',
          caption: '上级区划',
          codeName: 'parent_name',
          columnType: 'DEFGRIDCOLUMN',
          noPrivDisplayMode: 1,
          width: 200,
          widthUnit: 'PX',
          enableSort: true,
          id: 'parent_name',
        },
        {
          clconvertMode: 'NONE',
          dataItemName: 'level',
          excelCaption: '级别',
          appDEFieldId: 'level',
          valueType: 'SIMPLE',
          enableRowEdit: true,
          aggMode: 'NONE',
          align: 'LEFT',
          caption: '级别',
          codeName: 'level',
          columnType: 'DEFGRIDCOLUMN',
          noPrivDisplayMode: 1,
          width: 100,
          widthUnit: 'PX',
          enableSort: true,
          id: 'level',
        },
        {
          clconvertMode: 'FRONT',
          dataItemName: 'status',
          excelCaption: '状态',
          appCodeListId: 'web.mock__cl_status',
          appDEFieldId: 'status',
          valueType: 'SIMPLE',
          enableRowEdit: true,
          aggMode: 'NONE',
          align: 'LEFT',
          caption: '状态',
          codeName: 'status',
          columnType: 'DEFGRIDCOLUMN',
          noPrivDisplayMode: 1,
          width: 150,
          widthUnit: 'PX',
          enableSort: true,
          id: 'status',
        },
        {
          clconvertMode: 'NONE',
          dataItemName: 'path',
          excelCaption: '全路径',
          appDEFieldId: 'path',
          valueType: 'SIMPLE',
          enableRowEdit: true,
          aggMode: 'NONE',
          align: 'LEFT',
          caption: '全路径',
          codeName: 'path',
          columnType: 'DEFGRIDCOLUMN',
          noPrivDisplayMode: 1,
          width: 300,
          widthUnit: 'PX',
          enableSort: true,
          id: 'path',
        },
        {
          clconvertMode: 'NONE',
          dataItemName: 'sort',
          excelCaption: '排序',
          appDEFieldId: 'sort',
          valueType: 'SIMPLE',
          enableRowEdit: true,
          aggMode: 'NONE',
          align: 'LEFT',
          caption: '排序',
          codeName: 'sort',
          columnType: 'DEFGRIDCOLUMN',
          noPrivDisplayMode: 1,
          width: 100,
          widthUnit: 'PX',
          enableSort: true,
          id: 'sort',
        },
        {
          clconvertMode: 'NONE',
          dataItemName: 'longitude',
          excelCaption: '经度',
          appDEFieldId: 'longitude',
          valueType: 'SIMPLE',
          enableRowEdit: true,
          aggMode: 'NONE',
          align: 'LEFT',
          caption: '经度',
          codeName: 'longitude',
          columnType: 'DEFGRIDCOLUMN',
          noPrivDisplayMode: 1,
          width: 100,
          widthUnit: 'PX',
          enableSort: true,
          id: 'longitude',
        },
        {
          clconvertMode: 'NONE',
          dataItemName: 'latitude',
          excelCaption: '纬度',
          appDEFieldId: 'latitude',
          valueType: 'SIMPLE',
          enableRowEdit: true,
          aggMode: 'NONE',
          align: 'LEFT',
          caption: '纬度',
          codeName: 'latitude',
          columnType: 'DEFGRIDCOLUMN',
          noPrivDisplayMode: 1,
          width: 100,
          widthUnit: 'PX',
          enableSort: true,
          id: 'latitude',
        },
        {
          clconvertMode: 'NONE',
          dataItemName: 'update_time',
          excelCaption: '更新时间',
          appDEFieldId: 'update_time',
          valueFormat: 'YYYY-MM-DD HH:mm:ss',
          valueType: 'SIMPLE',
          aggMode: 'NONE',
          align: 'LEFT',
          capLanguageRes: {
            lanResTag: 'DEF.LNAME.UPDATE_TIME',
          },
          caption: '更新时间',
          codeName: 'update_time',
          columnType: 'DEFGRIDCOLUMN',
          noPrivDisplayMode: 1,
          width: 200,
          widthUnit: 'PX',
          enableSort: true,
          id: 'update_time',
        },
        {
          clconvertMode: 'NONE',
          dataItemName: 'create_time',
          excelCaption: '创建时间',
          appDEFieldId: 'create_time',
          valueFormat: 'YYYY-MM-DD HH:mm:ss',
          valueType: 'SIMPLE',
          aggMode: 'NONE',
          align: 'LEFT',
          capLanguageRes: {
            lanResTag: 'DEF.LNAME.REGION.CREATE_TIME',
          },
          caption: '创建时间',
          codeName: 'create_time',
          columnType: 'DEFGRIDCOLUMN',
          noPrivDisplayMode: 1,
          width: 200,
          widthUnit: 'PX',
          enableSort: true,
          id: 'create_time',
        },
        {
          deuiactionGroup: {
            uiactionGroupDetails: [
              {
                actionLevel: 100,
                afterItemType: 'NONE',
                beforeItemType: 'NONE',
                buttonStyle: 'DEFAULT',
                caption: '查看',
                detailType: 'DEUIACTION',
                uiactionId: 'view@region',
                showCaption: true,
                showIcon: true,
                sysImage: {
                  cssClass: 'fa fa-file-text',
                  glyph: 'xf15c@FontAwesome',
                },
                id: 'u988f5c7',
              },
              {
                actionLevel: 100,
                afterItemType: 'NONE',
                beforeItemType: 'NONE',
                buttonStyle: 'DEFAULT',
                caption: '编辑',
                detailType: 'DEUIACTION',
                uiactionId: 'edit@region',
                showCaption: true,
                showIcon: true,
                sysImage: {
                  cssClass: 'fa fa-edit',
                  glyph: 'xf044@FontAwesome',
                },
                id: 'ubfba42f',
              },
              {
                actionLevel: 100,
                afterItemType: 'NONE',
                beforeItemType: 'NONE',
                buttonStyle: 'DEFAULT',
                caption: '删除',
                detailType: 'DEUIACTION',
                uiactionId: 'remove@region',
                showCaption: true,
                showIcon: true,
                sysImage: {
                  cssClass: 'fa fa-trash',
                  glyph: 'xf1f8@FontAwesome',
                },
                id: 'u662706e',
              },
            ],
            appDataEntityId: 'web.region',
            uniqueTag: 'region__Aa191c5fc4defabcf44',
            name: '表格操作列',
            id: 'aa191c5fc4defabcf44',
          },
          aggMode: 'NONE',
          align: 'CENTER',
          caption: '操作',
          codeName: 'uagridcolumn1',
          columnType: 'UAGRIDCOLUMN',
          noPrivDisplayMode: 1,
          width: 200,
          widthUnit: 'PX',
          id: 'uagridcolumn1',
        },
        {
          clconvertMode: 'FRONT',
          dataItemName: 'create_man',
          excelCaption: '创建人',
          appCodeListId: 'web.sysoperator',
          appDEFieldId: 'create_man',
          valueType: 'SIMPLE',
          aggMode: 'NONE',
          align: 'LEFT',
          capLanguageRes: {
            lanResTag: 'DEF.LNAME.REGION.CREATE_MAN',
          },
          caption: '创建人',
          codeName: 'create_man',
          columnType: 'DEFGRIDCOLUMN',
          hideMode: 2,
          noPrivDisplayMode: 1,
          width: 100,
          widthUnit: 'PX',
          enableSort: true,
          id: 'create_man',
        },
      ],
      degridDataItems: [
        {
          appDEFieldId: 'code',
          valueType: 'SIMPLE',
          dataType: 25,
          id: 'code',
        },
        {
          appDEFieldId: 'name',
          valueType: 'SIMPLE',
          dataType: 25,
          id: 'name',
        },
        {
          appDEFieldId: 'parent_name',
          valueType: 'SIMPLE',
          dataType: 25,
          id: 'parent_name',
        },
        {
          appDEFieldId: 'level',
          valueType: 'SIMPLE',
          dataType: 9,
          id: 'level',
        },
        {
          appDEFieldId: 'status',
          valueType: 'SIMPLE',
          dataType: 9,
          id: 'status',
        },
        {
          appDEFieldId: 'path',
          valueType: 'SIMPLE',
          dataType: 25,
          id: 'path',
        },
        {
          appDEFieldId: 'sort',
          valueType: 'SIMPLE',
          dataType: 9,
          id: 'sort',
        },
        {
          appDEFieldId: 'longitude',
          valueType: 'SIMPLE',
          dataType: 29,
          id: 'longitude',
        },
        {
          appDEFieldId: 'latitude',
          valueType: 'SIMPLE',
          dataType: 29,
          id: 'latitude',
        },
        {
          format: 'YYYY-MM-DD HH:mm:ss',
          appDEFieldId: 'update_time',
          valueType: 'SIMPLE',
          dataType: 5,
          id: 'update_time',
        },
        {
          format: 'YYYY-MM-DD HH:mm:ss',
          appDEFieldId: 'create_time',
          valueType: 'SIMPLE',
          dataType: 5,
          id: 'create_time',
        },
        {
          appDEFieldId: 'create_man',
          valueType: 'SIMPLE',
          dataType: 25,
          id: 'create_man',
        },
        {
          appDEFieldId: 'id',
          valueType: 'SIMPLE',
          dataType: 25,
          id: 'id',
        },
        {
          appDEFieldId: 'parent_id',
          valueType: 'SIMPLE',
          dataType: 25,
          id: 'parent_id',
        },
        {
          appDEFieldId: 'id',
          valueType: 'SIMPLE',
          dataType: 25,
          id: 'srfkey',
        },
        {
          appDEFieldId: 'id',
          valueType: 'SIMPLE',
          dataType: 25,
          id: 'srfdataaccaction',
        },
        {
          appDEFieldId: 'name',
          valueType: 'SIMPLE',
          dataType: 25,
          id: 'srfmajortext',
        },
      ],
      degridEditItems: [
        {
          caption: '名称',
          codeName: 'name',
          enableCond: 3,
          appDEFieldId: 'name',
          editor: {
            maxLength: 200,
            editorType: 'TEXTBOX',
            valueType: 'SIMPLE',
            editable: true,
            id: 'name',
          },
          allowEmpty: true,
          id: 'name',
        },
        {
          caption: '上级区划',
          codeName: 'parent_name',
          enableCond: 3,
          appDEFieldId: 'parent_name',
          editor: {
            enablePickupView: true,
            singleSelect: true,
            appDEACModeId: 'default',
            appDEDataSetId: 'fetch_default',
            appDataEntityId: 'web.region',
            enableAC: true,
            forceSelection: true,
            showTrigger: true,
            valueItemName: 'parent_id',
            editorParams: {
              AC: 'TRUE',
              PICKUPVIEW: 'TRUE',
            },
            editorType: 'PICKER',
            editorItems: [{}],
            valueType: 'SIMPLE',
            editable: true,
            id: 'parent_name',
          },
          allowEmpty: true,
          id: 'parent_name',
        },
        {
          caption: '级别',
          codeName: 'level',
          enableCond: 3,
          appDEFieldId: 'level',
          editor: {
            editorType: 'TEXTBOX',
            valueType: 'SIMPLE',
            editable: true,
            id: 'level',
          },
          allowEmpty: true,
          id: 'level',
        },
        {
          caption: '状态',
          codeName: 'status',
          enableCond: 3,
          appDEFieldId: 'status',
          editor: {
            singleSelect: true,
            appCodeListId: 'web.mock__cl_status',
            editorType: 'DROPDOWNLIST',
            valueType: 'SIMPLE',
            editable: true,
            id: 'status',
          },
          allowEmpty: true,
          needCodeListConfig: true,
          id: 'status',
        },
        {
          caption: '全路径',
          codeName: 'path',
          enableCond: 3,
          appDEFieldId: 'path',
          editor: {
            maxLength: 500,
            editorType: 'TEXTBOX',
            valueType: 'SIMPLE',
            editable: true,
            id: 'path',
          },
          allowEmpty: true,
          id: 'path',
        },
        {
          caption: '排序',
          codeName: 'sort',
          enableCond: 3,
          appDEFieldId: 'sort',
          editor: {
            editorType: 'TEXTBOX',
            valueType: 'SIMPLE',
            editable: true,
            id: 'sort',
          },
          allowEmpty: true,
          id: 'sort',
        },
        {
          caption: '经度',
          codeName: 'longitude',
          enableCond: 3,
          appDEFieldId: 'longitude',
          editor: {
            editorType: 'TEXTBOX',
            valueType: 'SIMPLE',
            editable: true,
            id: 'longitude',
          },
          allowEmpty: true,
          id: 'longitude',
        },
        {
          caption: '纬度',
          codeName: 'latitude',
          enableCond: 3,
          appDEFieldId: 'latitude',
          editor: {
            editorType: 'TEXTBOX',
            valueType: 'SIMPLE',
            editable: true,
            id: 'latitude',
          },
          allowEmpty: true,
          id: 'latitude',
        },
        {
          caption: '标识',
          codeName: 'srfkey',
          enableCond: 3,
          appDEFieldId: 'id',
          editor: {
            editorType: 'HIDDEN',
            valueType: 'SIMPLE',
            editable: true,
            id: 'srfkey',
          },
          allowEmpty: true,
          id: 'srfkey',
        },
        {
          enableCond: 3,
          appDEFieldId: 'parent_id',
          editor: {
            editorType: 'HIDDEN',
            valueType: 'SIMPLE',
            editable: true,
          },
          allowEmpty: true,
          id: 'parent_id',
        },
      ],
      pagingMode: 1,
      pagingSize: 20,
      sortMode: 'REMOTE',
      enableCustomized: true,
      enablePagingBar: true,
      navViewPos: 'NONE',
      fetchControlAction: {
        appDEMethodId: 'fetch_default',
        appDataEntityId: 'web.region',
        id: 'fetch',
      },
      removeControlAction: {
        appDEMethodId: 'remove',
        appDataEntityId: 'web.region',
        id: 'remove',
      },
      autoLoad: true,
      showBusyIndicator: true,
      codeName: 'detail_grid_view_grid',
      controlType: 'GRID',
      logicName: '明细数据_表格',
      appDataEntityId: 'web.region',
      controlParam: {
        id: 'grid',
      },
      modelId: 'cd4eb3a52010cb92007aaca3826e6fd6',
      modelType: 'PSDEGRID',
      name: 'grid',
      id: 'web.region.detail_grid_view_grid',
    },
    {
      searchButtonStyle: 'DEFAULT',
      deformPages: [
        {
          layout: {
            columnCount: 24,
            layout: 'TABLE_24COL',
          },
          caption: '常规条件',
          codeName: 'formpage1',
          detailStyle: 'DEFAULT',
          detailType: 'FORMPAGE',
          id: 'formpage1',
        },
      ],
      layout: {
        columnCount: 24,
        layout: 'TABLE_24COL',
      },
      tabHeaderPos: 'TOP',
      noTabHeader: true,
      autoLoad: true,
      showBusyIndicator: true,
      codeName: 'detail_grid_view_search_form',
      controlType: 'SEARCHFORM',
      logicName: '明细数据_搜索表单',
      appDataEntityId: 'web.region',
      controlParam: {
        id: 'searchform',
      },
      modelId: '1c815f8ab2d2bf286d64edd8a9a80d56',
      modelType: 'PSDEFORM_SEARCHFORM',
      name: 'searchform',
      id: 'web.region.detail_grid_view_search_form',
    },
    {
      groupMode: 'SINGLE',
      quickSearchMode: 1,
      enableQuickSearch: true,
      controlType: 'SEARCHBAR',
      appDataEntityId: 'web.region',
      controlParam: {
        id: 'searchbar',
      },
      id: 'searchbar',
    },
    {
      capLanguageRes: {
        lanResTag: 'DE.LNAME.REGION',
      },
      caption: '明细数据',
      codeName: 'detail_grid_view_captionbar',
      controlType: 'CAPTIONBAR',
      appDataEntityId: 'web.region',
      controlParam: {},
      name: 'captionbar',
      id: 'detail_grid_view_captionbar',
    },
  ],
  viewLayoutPanel: {
    layoutBodyOnly: true,
    useDefaultLayout: true,
    layoutPanel: true,
    codeName: 'layoutpanel',
    controlStyle: 'APPDEGRIDVIEW',
    controlType: 'VIEWLAYOUTPANEL',
    appDataEntityId: 'web.region',
    controlParam: {},
    id: 'layoutpanel',
  },
  title: '明细数据',
  viewStyle: 'DEFAULT',
  viewType: 'DEGRIDVIEW',
  enableDP: true,
  showCaptionBar: true,
  modelId: '1f9b4b9dea11af743a207ae79ac9b5d9',
  modelType: 'PSAPPDEVIEW',
  name: 'REGIONdetail_grid_view',
  id: 'web.region_detail_grid_view',
};
