export default {
  enableDirtyChecking: true,
  xdataControlName: 'form',
  loadDefault: true,
  deviewCodeName: 'edit_view9',
  deviewId: '17f5bfd08d83ca704252437afcee033e',
  accUserMode: 3,
  capLanguageRes: {
    lanResTag: 'DE.LNAME.REGION',
  },
  caption: '编辑视图（部件视图）',
  codeName: 'region_edit_view9',
  appDataEntityId: 'web.region',
  appViewEngines: [
    {
      engineCat: 'VIEW',
      engineType: 'EditView9',
      id: 'engine',
    },
  ],
  controls: [
    {
      xdataControlName: 'form',
      codeName: 'edit_view9_toolbar',
      controlType: 'TOOLBAR',
      logicName: '编辑视图（部件视图）_工具栏',
      appDataEntityId: 'web.region',
      controlParam: {
        id: 'toolbar',
      },
      modelId: '4a8ee05184f1885abbd1f21ce4bdffb4',
      modelType: 'PSDETOOLBAR',
      name: 'toolbar',
      id: 'edit_view9_toolbar',
    },
    {
      createControlAction: {
        appDEMethodId: 'create',
        appDataEntityId: 'web.region',
        id: 'create',
      },
      getDraftFromControlAction: {
        appDataEntityId: 'web.region',
        id: 'loaddraftfrom',
      },
      getDraftControlAction: {
        appDEMethodId: 'get_draft',
        appDataEntityId: 'web.region',
        id: 'loaddraft',
      },
      getControlAction: {
        appDEMethodId: 'get',
        appDataEntityId: 'web.region',
        id: 'load',
      },
      removeControlAction: {
        appDEMethodId: 'remove',
        appDataEntityId: 'web.region',
        id: 'remove',
      },
      updateControlAction: {
        appDEMethodId: 'update',
        appDataEntityId: 'web.region',
        id: 'update',
      },
      deformPages: [
        {
          layout: {
            columnCount: 24,
            layout: 'TABLE_24COL',
          },
          deformDetails: [
            {
              layout: {
                columnCount: 24,
                layout: 'TABLE_24COL',
              },
              deformDetails: [
                {
                  dataType: 25,
                  enableCond: 3,
                  labelPos: 'LEFT',
                  labelWidth: 130,
                  noPrivDisplayMode: 1,
                  appDEFieldId: 'name',
                  editor: {
                    maxLength: 200,
                    editorType: 'TEXTBOX',
                    valueType: 'SIMPLE',
                    editable: true,
                    id: 'name',
                  },
                  allowEmpty: true,
                  capLanguageRes: {
                    lanResTag: 'DEF.LNAME.REGION.NAME',
                  },
                  caption: '名称',
                  codeName: 'name',
                  detailStyle: 'DEFAULT',
                  detailType: 'FORMITEM',
                  layoutPos: {
                    colLG: 20,
                    colMD: 20,
                    layout: 'TABLE_24COL',
                  },
                  showCaption: true,
                  id: 'name',
                },
                {
                  dataType: 9,
                  enableCond: 3,
                  labelPos: 'LEFT',
                  labelWidth: 130,
                  noPrivDisplayMode: 1,
                  appDEFieldId: 'status',
                  editor: {
                    singleSelect: true,
                    appCodeListId: 'web.mock__cl_status',
                    editorType: 'DROPDOWNLIST',
                    valueType: 'SIMPLE',
                    editable: true,
                    id: 'status',
                  },
                  allowEmpty: true,
                  needCodeListConfig: true,
                  caption: '状态',
                  codeName: 'status',
                  detailStyle: 'DEFAULT',
                  detailType: 'FORMITEM',
                  layoutPos: {
                    colLG: 4,
                    colMD: 4,
                    layout: 'TABLE_24COL',
                  },
                  showCaption: true,
                  id: 'status',
                },
              ],
              caption: '区划基本信息',
              codeName: 'group1',
              detailStyle: 'DEFAULT',
              detailType: 'GROUPPANEL',
              layoutPos: {
                colMD: 24,
                layout: 'TABLE_24COL',
              },
              id: 'group1',
            },
            {
              dataType: 25,
              enableCond: 3,
              labelPos: 'LEFT',
              labelWidth: 130,
              noPrivDisplayMode: 1,
              appDEFieldId: 'id',
              editor: {
                editorType: 'HIDDEN',
                valueType: 'SIMPLE',
                editable: true,
                id: 'id',
              },
              allowEmpty: true,
              hidden: true,
              capLanguageRes: {
                lanResTag: 'DEF.LNAME.REGION.ID',
              },
              caption: '标识',
              codeName: 'id',
              detailStyle: 'DEFAULT',
              detailType: 'FORMITEM',
              layoutPos: {
                colMD: 24,
                layout: 'TABLE_24COL',
              },
              id: 'id',
            },
          ],
          caption: '基本信息',
          codeName: 'formpage1',
          detailStyle: 'DEFAULT',
          detailType: 'FORMPAGE',
          id: 'formpage1',
        },
      ],
      layout: {
        columnCount: 24,
        layout: 'TABLE_24COL',
      },
      tabHeaderPos: 'TOP',
      noTabHeader: true,
      autoLoad: true,
      showBusyIndicator: true,
      codeName: 'edit_view9_form',
      controlType: 'FORM',
      logicName: '编辑视图（部件视图）_表单',
      appDataEntityId: 'web.region',
      controlParam: {
        id: 'form',
      },
      modelId: 'e2b16dbc15027f67ebfc4f7eb8e76a3d',
      modelType: 'PSDEFORM_EDITFORM',
      name: 'form',
      id: 'web.region.edit_view9_form',
    },
    {
      capLanguageRes: {
        lanResTag: 'DE.LNAME.REGION',
      },
      caption: '编辑视图（部件视图）',
      codeName: 'edit_view9_captionbar',
      controlType: 'CAPTIONBAR',
      appDataEntityId: 'web.region',
      controlParam: {},
      name: 'captionbar',
      id: 'edit_view9_captionbar',
    },
  ],
  viewLayoutPanel: {
    layoutBodyOnly: true,
    useDefaultLayout: true,
    layoutPanel: true,
    codeName: 'layoutpanel',
    controlStyle: 'APPDEEDITVIEW9',
    controlType: 'VIEWLAYOUTPANEL',
    appDataEntityId: 'web.region',
    controlParam: {},
    id: 'layoutpanel',
  },
  title: '编辑视图（部件视图）',
  viewStyle: 'DEFAULT',
  viewType: 'DEEDITVIEW9',
  enableDP: true,
  showCaptionBar: false,
  modelId: '909c8304d1735997ab08b6e68d303d45',
  modelType: 'PSAPPDEVIEW',
  name: 'REGIONedit_view9',
  id: 'web.region_edit_view9',
};
