export default {
  funcViewMode: 'PICKUPVIEW',
  deviewCodeName: 'PickupView',
  deviewId: '79f7bd7c850598aa4446fedf591b2e48',
  accUserMode: 3,
  capLanguageRes: {
    lanResTag: 'DE.LNAME.REGION',
  },
  caption: '区划数据选择视图',
  codeName: 'region_pickup_view',
  appDataEntityId: 'web.region',
  appViewEngines: [
    {
      engineCat: 'VIEW',
      engineType: 'PickupView',
      id: 'engine',
    },
  ],
  controls: [
    {
      embeddedAppDEViewId: 'web.region_pickup_grid_view',
      codeName: 'pickup_view_pickupviewpanel',
      controlType: 'PICKUPVIEWPANEL',
      appDataEntityId: 'web.region',
      controlParam: {
        id: 'pickupviewpanel',
      },
      name: 'pickupviewpanel',
      id: 'pickup_view_pickupviewpanel',
    },
    {
      capLanguageRes: {
        lanResTag: 'DE.LNAME.REGION',
      },
      caption: '区划数据选择视图',
      codeName: 'pickup_view_captionbar',
      controlType: 'CAPTIONBAR',
      appDataEntityId: 'web.region',
      controlParam: {},
      name: 'captionbar',
      id: 'pickup_view_captionbar',
    },
  ],
  viewLayoutPanel: {
    layoutBodyOnly: true,
    useDefaultLayout: true,
    layoutPanel: true,
    codeName: 'layoutpanel',
    controlStyle: 'APPDEPICKUPVIEW',
    controlType: 'VIEWLAYOUTPANEL',
    appDataEntityId: 'web.region',
    controlParam: {},
    id: 'layoutpanel',
  },
  title: '区划数据选择视图',
  viewStyle: 'DEFAULT',
  viewType: 'DEPICKUPVIEW',
  enableDP: true,
  showCaptionBar: false,
  modelId: 'a83344ab2a808dc70157420bfa332a6c',
  modelType: 'PSAPPDEVIEW',
  name: 'REGIONPickupView',
  id: 'web.region_pickup_view',
};
