export default {
  enableDirtyChecking: true,
  showDataInfoBar: true,
  xdataControlName: 'form',
  loadDefault: true,
  deviewCodeName: 'edit_view2',
  deviewId: '529074ac9a26b010facc9c1d8546df51',
  accUserMode: 3,
  capLanguageRes: {
    lanResTag: 'DE.LNAME.REGION',
  },
  caption: '编辑视图（左右关系）',
  codeName: 'region_edit_view2',
  appDataEntityId: 'web.region',
  appViewEngines: [
    {
      engineCat: 'VIEW',
      engineType: 'EditView2',
      id: 'engine',
    },
  ],
  appViewNavContexts: [
    {
      rawValue: true,
      key: 'REGION',
      value: '86',
      name: 'REGION',
      id: 'region',
    },
  ],
  controls: [
    {
      xdataControlName: 'form',
      codeName: 'edit_view2_toolbar',
      controlType: 'TOOLBAR',
      logicName: '编辑视图（左右关系）_工具栏',
      appDataEntityId: 'web.region',
      controlParam: {
        id: 'toolbar',
      },
      modelId: 'e054671615e43041ca56d7d3cfc77682',
      modelType: 'PSDETOOLBAR',
      name: 'toolbar',
      id: 'edit_view2_toolbar',
    },
    {
      createControlAction: {
        appDEMethodId: 'create',
        appDataEntityId: 'web.region',
        id: 'create',
      },
      getDraftFromControlAction: {
        appDataEntityId: 'web.region',
        id: 'loaddraftfrom',
      },
      getDraftControlAction: {
        appDEMethodId: 'get_draft',
        appDataEntityId: 'web.region',
        id: 'loaddraft',
      },
      getControlAction: {
        appDEMethodId: 'get',
        appDataEntityId: 'web.region',
        id: 'load',
      },
      removeControlAction: {
        appDEMethodId: 'remove',
        appDataEntityId: 'web.region',
        id: 'remove',
      },
      updateControlAction: {
        appDEMethodId: 'update',
        appDataEntityId: 'web.region',
        id: 'update',
      },
      infoFormMode: true,
      deformPages: [
        {
          layout: {
            columnCount: 24,
            layout: 'TABLE_24COL',
          },
          deformDetails: [
            {
              layout: {
                columnCount: 24,
                layout: 'TABLE_24COL',
              },
              deformDetails: [
                {
                  dataType: 25,
                  enableCond: 3,
                  labelPos: 'LEFT',
                  labelWidth: 130,
                  noPrivDisplayMode: 1,
                  appDEFieldId: 'id',
                  editor: {
                    editorType: 'HIDDEN',
                    valueType: 'SIMPLE',
                    editable: true,
                    id: 'id',
                  },
                  allowEmpty: true,
                  hidden: true,
                  capLanguageRes: {
                    lanResTag: 'DEF.LNAME.REGION.ID',
                  },
                  caption: '标识',
                  codeName: 'id',
                  detailStyle: 'DEFAULT',
                  detailType: 'FORMITEM',
                  layoutPos: {
                    colLG: 12,
                    colMD: 12,
                    layout: 'TABLE_24COL',
                  },
                  id: 'id',
                },
                {
                  dataType: 25,
                  enableCond: 1,
                  labelPos: 'LEFT',
                  labelWidth: 130,
                  noPrivDisplayMode: 1,
                  appDEFieldId: 'code',
                  editor: {
                    maxLength: 100,
                    editorType: 'TEXTBOX',
                    valueType: 'SIMPLE',
                    editable: true,
                    readOnly: true,
                    id: 'code',
                  },
                  allowEmpty: true,
                  caption: '编码',
                  codeName: 'code',
                  detailStyle: 'DEFAULT',
                  detailType: 'FORMITEM',
                  layoutPos: {
                    colLG: 12,
                    colMD: 12,
                    layout: 'TABLE_24COL',
                  },
                  showCaption: true,
                  id: 'code',
                },
                {
                  dataType: 25,
                  enableCond: 3,
                  labelPos: 'LEFT',
                  labelWidth: 130,
                  noPrivDisplayMode: 1,
                  appDEFieldId: 'name',
                  editor: {
                    maxLength: 200,
                    editorType: 'TEXTBOX',
                    valueType: 'SIMPLE',
                    editable: true,
                    readOnly: true,
                    id: 'name',
                  },
                  allowEmpty: true,
                  capLanguageRes: {
                    lanResTag: 'DEF.LNAME.REGION.NAME',
                  },
                  caption: '名称',
                  codeName: 'name',
                  detailStyle: 'DEFAULT',
                  detailType: 'FORMITEM',
                  layoutPos: {
                    colLG: 12,
                    colMD: 12,
                    layout: 'TABLE_24COL',
                  },
                  showCaption: true,
                  id: 'name',
                },
                {
                  dataType: 9,
                  enableCond: 3,
                  labelPos: 'LEFT',
                  labelWidth: 130,
                  noPrivDisplayMode: 1,
                  appDEFieldId: 'level',
                  editor: {
                    editorType: 'TEXTBOX',
                    valueType: 'SIMPLE',
                    editable: true,
                    readOnly: true,
                    id: 'level',
                  },
                  allowEmpty: true,
                  caption: '级别',
                  codeName: 'level',
                  detailStyle: 'DEFAULT',
                  detailType: 'FORMITEM',
                  layoutPos: {
                    colLG: 12,
                    colMD: 12,
                    layout: 'TABLE_24COL',
                  },
                  showCaption: true,
                  id: 'level',
                },
                {
                  dataType: 25,
                  enableCond: 3,
                  labelPos: 'LEFT',
                  labelWidth: 130,
                  noPrivDisplayMode: 1,
                  appDEFieldId: 'parent_name',
                  editor: {
                    enablePickupView: true,
                    singleSelect: true,
                    pickupAppViewId: 'web.region_pickup_view',
                    handlerType: 'PickupText',
                    appDEACModeId: 'default',
                    appDEDataSetId: 'fetch_default',
                    appDataEntityId: 'web.region',
                    enableAC: true,
                    forceSelection: true,
                    showTrigger: true,
                    valueItemName: 'parent_id',
                    editorParams: {
                      AC: 'TRUE',
                      PICKUPVIEW: 'TRUE',
                    },
                    editorType: 'PICKER',
                    editorItems: [
                      {
                        id: 'parent_id',
                      },
                    ],
                    valueType: 'SIMPLE',
                    editable: true,
                    readOnly: true,
                    id: 'parent_name',
                  },
                  allowEmpty: true,
                  caption: '上级区划',
                  codeName: 'parent_name',
                  detailStyle: 'DEFAULT',
                  detailType: 'FORMITEM',
                  layoutPos: {
                    colLG: 12,
                    colMD: 12,
                    layout: 'TABLE_24COL',
                  },
                  showCaption: true,
                  id: 'parent_name',
                },
                {
                  dataType: 25,
                  enableCond: 3,
                  labelPos: 'LEFT',
                  labelWidth: 130,
                  noPrivDisplayMode: 1,
                  appDEFieldId: 'parent_id',
                  editor: {
                    editorType: 'HIDDEN',
                    valueType: 'SIMPLE',
                    editable: true,
                    id: 'parent_id',
                  },
                  allowEmpty: true,
                  hidden: true,
                  caption: '上级区划标识',
                  codeName: 'parent_id',
                  detailStyle: 'DEFAULT',
                  detailType: 'FORMITEM',
                  layoutPos: {
                    colLG: 12,
                    colMD: 12,
                    layout: 'TABLE_24COL',
                  },
                  id: 'parent_id',
                },
                {
                  dataType: 25,
                  enableCond: 3,
                  labelPos: 'LEFT',
                  labelWidth: 130,
                  noPrivDisplayMode: 1,
                  appDEFieldId: 'path',
                  editor: {
                    maxLength: 500,
                    editorType: 'TEXTBOX',
                    valueType: 'SIMPLE',
                    editable: true,
                    readOnly: true,
                    id: 'path',
                  },
                  allowEmpty: true,
                  caption: '全路径',
                  codeName: 'path',
                  detailStyle: 'DEFAULT',
                  detailType: 'FORMITEM',
                  layoutPos: {
                    colLG: 24,
                    colMD: 24,
                    layout: 'TABLE_24COL',
                  },
                  showCaption: true,
                  id: 'path',
                },
                {
                  dataType: 9,
                  enableCond: 3,
                  labelPos: 'LEFT',
                  labelWidth: 130,
                  noPrivDisplayMode: 1,
                  appDEFieldId: 'status',
                  editor: {
                    singleSelect: true,
                    appCodeListId: 'web.mock__cl_status',
                    editorType: 'DROPDOWNLIST',
                    valueType: 'SIMPLE',
                    editable: true,
                    readOnly: true,
                    id: 'status',
                  },
                  allowEmpty: true,
                  needCodeListConfig: true,
                  caption: '状态',
                  codeName: 'status',
                  detailStyle: 'DEFAULT',
                  detailType: 'FORMITEM',
                  layoutPos: {
                    colLG: 12,
                    colMD: 12,
                    layout: 'TABLE_24COL',
                  },
                  showCaption: true,
                  id: 'status',
                },
                {
                  dataType: 9,
                  enableCond: 3,
                  labelPos: 'LEFT',
                  labelWidth: 130,
                  noPrivDisplayMode: 1,
                  appDEFieldId: 'sort',
                  editor: {
                    editorType: 'TEXTBOX',
                    valueType: 'SIMPLE',
                    editable: true,
                    readOnly: true,
                    id: 'sort',
                  },
                  allowEmpty: true,
                  caption: '排序',
                  codeName: 'sort',
                  detailStyle: 'DEFAULT',
                  detailType: 'FORMITEM',
                  layoutPos: {
                    colLG: 12,
                    colMD: 12,
                    layout: 'TABLE_24COL',
                  },
                  showCaption: true,
                  id: 'sort',
                },
                {
                  dataType: 29,
                  enableCond: 3,
                  labelPos: 'LEFT',
                  labelWidth: 130,
                  noPrivDisplayMode: 1,
                  appDEFieldId: 'longitude',
                  editor: {
                    editorType: 'TEXTBOX',
                    valueType: 'SIMPLE',
                    editable: true,
                    readOnly: true,
                    id: 'longitude',
                  },
                  allowEmpty: true,
                  caption: '经度',
                  codeName: 'longitude',
                  detailStyle: 'DEFAULT',
                  detailType: 'FORMITEM',
                  layoutPos: {
                    colLG: 12,
                    colMD: 12,
                    layout: 'TABLE_24COL',
                  },
                  showCaption: true,
                  id: 'longitude',
                },
                {
                  dataType: 29,
                  enableCond: 3,
                  labelPos: 'LEFT',
                  labelWidth: 130,
                  noPrivDisplayMode: 1,
                  appDEFieldId: 'latitude',
                  editor: {
                    editorType: 'TEXTBOX',
                    valueType: 'SIMPLE',
                    editable: true,
                    readOnly: true,
                    id: 'latitude',
                  },
                  allowEmpty: true,
                  caption: '纬度',
                  codeName: 'latitude',
                  detailStyle: 'DEFAULT',
                  detailType: 'FORMITEM',
                  layoutPos: {
                    colLG: 12,
                    colMD: 12,
                    layout: 'TABLE_24COL',
                  },
                  showCaption: true,
                  id: 'latitude',
                },
                {
                  dataType: 5,
                  enableCond: 3,
                  ignoreInput: 3,
                  labelPos: 'LEFT',
                  labelWidth: 130,
                  noPrivDisplayMode: 1,
                  appDEFieldId: 'create_time',
                  editor: {
                    halign: 'LEFT',
                    valign: 'MIDDLE',
                    wrapMode: 'NOWRAP',
                    editorType: 'SPAN',
                    valueType: 'SIMPLE',
                    editable: true,
                    id: 'create_time',
                  },
                  valueFormat: 'YYYY-MM-DD HH:mm:ss',
                  allowEmpty: true,
                  capLanguageRes: {
                    lanResTag: 'DEF.LNAME.REGION.CREATE_TIME',
                  },
                  caption: '创建时间',
                  codeName: 'create_time',
                  detailStyle: 'DEFAULT',
                  detailType: 'FORMITEM',
                  layoutPos: {
                    colLG: 12,
                    colMD: 12,
                    layout: 'TABLE_24COL',
                  },
                  showCaption: true,
                  id: 'create_time',
                },
                {
                  dataType: 25,
                  enableCond: 3,
                  ignoreInput: 3,
                  labelPos: 'LEFT',
                  labelWidth: 130,
                  noPrivDisplayMode: 1,
                  appDEFieldId: 'update_man',
                  editor: {
                    halign: 'LEFT',
                    valign: 'MIDDLE',
                    wrapMode: 'NOWRAP',
                    appCodeListId: 'web.sysoperator',
                    editorType: 'SPAN',
                    valueType: 'SIMPLE',
                    editable: true,
                    id: 'update_man',
                  },
                  allowEmpty: true,
                  convertToCodeItemText: true,
                  capLanguageRes: {
                    lanResTag: 'DEF.LNAME.UPDATE_MAN',
                  },
                  caption: '更新人',
                  codeName: 'update_man',
                  detailStyle: 'DEFAULT',
                  detailType: 'FORMITEM',
                  layoutPos: {
                    colLG: 12,
                    colMD: 12,
                    layout: 'TABLE_24COL',
                  },
                  showCaption: true,
                  id: 'update_man',
                },
              ],
              capLanguageRes: {
                lanResTag: 'CONTROL.DEFORM.REGION.MAIN.GROUPPANEL.GROUP1',
              },
              caption: '区划信息',
              codeName: 'group1',
              detailStyle: 'DEFAULT',
              detailType: 'GROUPPANEL',
              layoutPos: {
                colMD: 24,
                layout: 'TABLE_24COL',
              },
              showCaption: true,
              id: 'group1',
            },
          ],
          capLanguageRes: {
            lanResTag: 'CONTROL.DEFORM.REGION.MAIN.FORMPAGE.FORMPAGE1',
          },
          caption: '基本信息',
          codeName: 'formpage1',
          detailStyle: 'DEFAULT',
          detailType: 'FORMPAGE',
          id: 'formpage1',
        },
      ],
      layout: {
        columnCount: 24,
        layout: 'TABLE_24COL',
      },
      tabHeaderPos: 'TOP',
      noTabHeader: true,
      autoLoad: true,
      showBusyIndicator: true,
      codeName: 'edit_view2_form',
      controlType: 'FORM',
      logicName: '编辑视图（左右关系）_表单',
      appDataEntityId: 'web.region',
      controlParam: {
        id: 'form',
      },
      modelId: 'c27646f578929c1cf8e2834ba132899a',
      modelType: 'PSDEFORM_EDITFORM',
      name: 'form',
      id: 'web.region.edit_view2_form',
    },
    {
      dedrbarGroups: [
        {
          caption: '默认',
          name: '默认',
          id: 'a134c2498ecf9e6f9d0',
        },
      ],
      showTitle: true,
      dataRelationTag: 'edit_view2_DR',
      editItemCapLanguageRes: {
        lanResTag: 'DE.LNAME.REGION',
      },
      editItemCaption: '区划',
      dedrctrlItems: [
        {
          dedrbarGroupId: 'a134c2498ecf9e6f9d0',
          caption: '明细数据',
          appViewId: 'web.region_detail_grid_view',
          id: 'detail',
        },
      ],
      uniqueTag: 'region_edit_view2__drbar',
      autoLoad: true,
      showBusyIndicator: true,
      codeName: 'edit_view2_dr',
      controlType: 'DRBAR',
      appDataEntityId: 'web.region',
      controlParam: {
        id: 'drbar',
      },
      modelId: 'e5d9ba2db847b7507b05f9d74c2e8010',
      modelType: 'PSDEDRBAR',
      name: 'drbar',
      id: 'edit_view2_dr',
    },
    {
      codeName: 'edit_view2_datainfobar',
      controlType: 'DATAINFOBAR',
      appDataEntityId: 'web.region',
      controlParam: {
        id: 'datainfobar',
      },
      name: 'datainfobar',
      id: 'edit_view2_datainfobar',
    },
    {
      capLanguageRes: {
        lanResTag: 'DE.LNAME.REGION',
      },
      caption: '编辑视图（左右关系）',
      codeName: 'edit_view2_captionbar',
      controlType: 'CAPTIONBAR',
      appDataEntityId: 'web.region',
      controlParam: {},
      name: 'captionbar',
      id: 'edit_view2_captionbar',
    },
  ],
  viewLayoutPanel: {
    layoutBodyOnly: true,
    useDefaultLayout: true,
    layoutPanel: true,
    codeName: 'layoutpanel',
    controlStyle: 'APPDEEDITVIEW2',
    controlType: 'VIEWLAYOUTPANEL',
    appDataEntityId: 'web.region',
    controlParam: {},
    id: 'layoutpanel',
  },
  title: '编辑视图（左右关系）',
  viewStyle: 'DEFAULT',
  viewType: 'DEEDITVIEW2',
  enableDP: true,
  showCaptionBar: true,
  modelId: '5bd905824232d7da053e0f1afcda3f26',
  modelType: 'PSAPPDEVIEW',
  name: 'REGIONedit_view2',
  id: 'web.region_edit_view2',
};
