export default {
  tabLayout: 'TOP',
  loadDefault: true,
  showDataInfoBar: true,
  deviewCodeName: 'edit_view_tab_exp',
  deviewId: 'c3e865da3b9f8a999ded1f13366ca48e',
  accUserMode: 2,
  capLanguageRes: {
    lanResTag: 'DE.LNAME.REGION',
  },
  caption: '编辑视图',
  codeName: 'region_edit_view_tab_exp',
  appDataEntityId: 'web.region',
  appViewEngines: [
    {
      engineCat: 'VIEW',
      engineType: 'TabExpView',
      id: 'engine',
    },
  ],
  controls: [
    {
      dedrtabPages: [
        {
          caption: '编辑视图',
          appViewId: 'web.region_sedit_view',
          id: 'edit_view',
        },
        {
          caption: '编辑视图（左右关系）',
          appViewId: 'web.region_edit_view2',
          id: 'edit_view2',
        },
        {
          caption: '编辑视图（分页关系）',
          appViewId: 'web.region_edit_view3',
          id: 'edit_view3',
        },
        {
          caption: '编辑视图（上下关系）',
          appViewId: 'web.region_edit_view4',
          id: 'edit_view4',
        },
      ],
      dataRelationTag: 'DataRelation2',
      editItemCapLanguageRes: {
        lanResTag: 'DE.LNAME.REGION',
      },
      editItemCaption: '区划',
      uniqueTag: 'region_edit_view_tab_exp__tabexppanel',
      autoLoad: true,
      showBusyIndicator: true,
      codeName: 'data_relation2',
      controlType: 'DRTAB',
      appDataEntityId: 'web.region',
      controlParam: {
        id: 'tabexppanel',
      },
      modelId: '0f4339929f282894d53c1b130ccc6956',
      modelType: 'PSDEDRTAB',
      name: 'tabexppanel',
      id: 'data_relation2',
    },
    {
      capLanguageRes: {
        lanResTag: 'DE.LNAME.REGION',
      },
      caption: '编辑视图',
      codeName: 'edit_view_tab_exp_captionbar',
      controlType: 'CAPTIONBAR',
      appDataEntityId: 'web.region',
      controlParam: {},
      name: 'captionbar',
      id: 'edit_view_tab_exp_captionbar',
    },
  ],
  viewLayoutPanel: {
    layoutBodyOnly: true,
    useDefaultLayout: true,
    layoutPanel: true,
    codeName: 'layoutpanel',
    controlStyle: 'APPDETABEXPVIEW',
    controlType: 'VIEWLAYOUTPANEL',
    appDataEntityId: 'web.region',
    controlParam: {},
    id: 'layoutpanel',
  },
  title: '编辑视图',
  viewStyle: 'DEFAULT',
  viewType: 'DETABEXPVIEW',
  enableDP: true,
  showCaptionBar: true,
  modelId: '7baaa054650826ec5f42900486f8c436',
  modelType: 'PSAPPDEVIEW',
  name: 'REGIONedit_view_tab_exp',
  id: 'web.region_edit_view_tab_exp',
};
