export default {
  funcViewMode: 'MPICKUPVIEW',
  deviewCodeName: 'MPickupView',
  deviewId: '3f39890c3b9c3877aa908c42e84c1fc3',
  accUserMode: 3,
  capLanguageRes: {
    lanResTag: 'DE.LNAME.REGION',
  },
  caption: '区划数据多项选择视图',
  codeName: 'region_m_pickup_view',
  appDataEntityId: 'web.region',
  appViewEngines: [
    {
      engineCat: 'VIEW',
      engineType: 'MPickupView',
      id: 'engine',
    },
  ],
  controls: [
    {
      groupMode: 'NONE',
      groupStyle: 'DEFAULT',
      delistDataItems: [
        {
          appDEFieldId: 'id',
          dataType: 25,
          id: 'srfkey',
        },
        {
          appDEFieldId: 'name',
          dataType: 25,
          id: 'srfmajortext',
        },
        {
          appDEFieldId: 'parent_id',
          dataType: 25,
          id: 'parent_id',
        },
      ],
      pagingSize: 1000,
      showHeader: true,
      navViewPos: 'NONE',
      createControlAction: {
        appDEMethodId: 'create',
        appDataEntityId: 'web.region',
        id: 'create',
      },
      fetchControlAction: {
        appDEMethodId: 'fetch_default',
        appDataEntityId: 'web.region',
        id: 'fetch',
      },
      getControlAction: {
        appDEMethodId: 'get',
        appDataEntityId: 'web.region',
        id: 'load',
      },
      removeControlAction: {
        appDEMethodId: 'remove',
        appDataEntityId: 'web.region',
        id: 'remove',
      },
      updateControlAction: {
        appDEMethodId: 'update',
        appDataEntityId: 'web.region',
        id: 'update',
      },
      autoLoad: true,
      showBusyIndicator: true,
      codeName: 'simplelist',
      controlType: 'LIST',
      logicName: 'simplelist',
      appDataEntityId: 'web.region',
      controlParam: {
        id: 'simplelist',
      },
      modelId: '936aae8d1c53ee264a4c34987b1974a3',
      modelType: 'PSDELIST',
      name: 'simplelist',
      id: 'web.region.simplelist',
    },
    {
      embeddedAppDEViewId: 'web.region_pickup_grid_view',
      codeName: 'm_pickup_view_pickupviewpanel',
      controlType: 'PICKUPVIEWPANEL',
      appDataEntityId: 'web.region',
      controlParam: {
        id: 'pickupviewpanel',
      },
      name: 'pickupviewpanel',
      id: 'm_pickup_view_pickupviewpanel',
    },
    {
      capLanguageRes: {
        lanResTag: 'DE.LNAME.REGION',
      },
      caption: '区划数据多项选择视图',
      codeName: 'm_pickup_view_captionbar',
      controlType: 'CAPTIONBAR',
      appDataEntityId: 'web.region',
      controlParam: {},
      name: 'captionbar',
      id: 'm_pickup_view_captionbar',
    },
  ],
  viewLayoutPanel: {
    layoutBodyOnly: true,
    useDefaultLayout: true,
    layoutPanel: true,
    codeName: 'layoutpanel',
    controlStyle: 'APPDEMPICKUPVIEW',
    controlType: 'VIEWLAYOUTPANEL',
    appDataEntityId: 'web.region',
    controlParam: {},
    id: 'layoutpanel',
  },
  title: '区划数据多项选择视图',
  viewStyle: 'DEFAULT',
  viewType: 'DEMPICKUPVIEW',
  enableDP: true,
  showCaptionBar: false,
  modelId: '5d760ea0ea60702e912b271c6b8f39a2',
  modelType: 'PSAPPDEVIEW',
  name: 'REGIONMPickupView',
  id: 'web.region_m_pickup_view',
};
