export default {
  deviewCodeName: 'child_appb_view3',
  deviewId: '74a975afcff7fee892c734fb5a7d63f6',
  accUserMode: 2,
  capLanguageRes: {
    lanResTag: 'DE.LNAME.MASTER',
  },
  caption: '子应用B视图3',
  codeName: 'master_child_appb_view3',
  appDataEntityId: 'web.master',
  viewLayoutPanel: {
    layoutBodyOnly: true,
    viewProxyMode: true,
    layoutMode: 'FLEX',
    layout: {
      layout: 'FLEX',
    },
    rootPanelItems: [
      {
        actionGroupExtractMode: 'ITEM',
        panelItems: [
          {
            rawItem: {
              caption: '子应用B关系界面1',
              halign: 'LEFT',
              renderMode: 'TEXT',
              valign: 'MIDDLE',
              wrapMode: 'NOWRAP',
              contentType: 'RAW',
              sysCss: {
                cssName: 'large_white_bold_front',
              },
              predefinedType: 'STATIC_TEXT',
              id: 'static_text',
            },
            caption: '子应用B关系界面1',
            itemStyle: 'DEFAULT',
            itemType: 'RAWITEM',
            layoutPos: {
              shrink: 1,
              layout: 'FLEX',
            },
            sysCss: {
              cssName: 'large_white_bold_front',
            },
            showCaption: true,
            id: 'static_text',
          },
        ],
        layout: {
          align: 'center',
          dir: 'row',
          layout: 'FLEX',
          valign: 'center',
        },
        dataRegionType: 'INHERIT',
        caption: '容器',
        contentHeight: 400,
        cssStyle: 'background: orange;',
        height: 400,
        itemStyle: 'DEFAULT',
        itemType: 'CONTAINER',
        layoutPos: {
          shrink: 1,
          height: 400,
          heightMode: 'PX',
          layout: 'FLEX',
          widthMode: 'FULL',
        },
        id: 'container',
      },
    ],
    layoutPanel: true,
    controls: [
      {
        capLanguageRes: {
          lanResTag: 'DE.LNAME.MASTER',
        },
        caption: '子应用B视图3',
        codeName: 'child_appb_view3_captionbar',
        controlType: 'CAPTIONBAR',
        appDataEntityId: 'web.master',
        controlParam: {},
        name: 'captionbar',
        id: 'child_appb_view3_captionbar',
      },
    ],
    codeName: 'layoutpanel',
    controlType: 'VIEWLAYOUTPANEL',
    logicName: 'child_appb_view3',
    appDataEntityId: 'web.master',
    controlParam: {},
    modelId: '5a14a15fe3bbe868d605d26c32a13b27',
    modelType: 'PSSYSVIEWLAYOUTPANEL',
    id: 'layoutpanel',
  },
  title: '子应用B视图3',
  viewStyle: 'DEFAULT',
  viewType: 'DECUSTOMVIEW',
  enableDP: true,
  showCaptionBar: false,
  modelId: '4cb98ca11e515eaed97d083a31193013',
  modelType: 'PSAPPDEVIEW',
  name: 'MASTERchild_appb_view3',
  id: 'web.master_child_appb_view3',
};
