// 图标清单
export const EMOJILIST = [
  '😀',
  '😃',
  '😄',
  '😁',
  '😆',
  '😅',
  '😂',
  '🤣',
  '😌',
  '😊',
  '😇',
  '🙂',
  '🙃',
  '😉',
  '😌',
  '😍',
  '😘',
  '😗',
  '😙',
  '😚',
  '😋',
  '😜',
  '😝',
  '😛',
  '🤑',
  '🤗',
  '🤓',
  '😎',
  '🤡',
  '🤠',
  '😏',
  '😒',
  '😞',
  '😔',
  '😟',
  '😕',
  '🙁',
  '☹️',
  '😣',
  '😖',
  '😫',
  '😩',
  '😤',
  '😠',
  '😡',
  '😶',
  '😐',
  '😑',
  '😯',
  '😦',
  '😧',
  '😮',
  '😲',
  '😵',
  '😳',
  '😱',
  '😨',
  '😰',
  '😢',
  '😥',
  '🤤',
  '😭',
  '😓',
  '😪',
  '😴',
  '🙄',
  '🤔',
  '🤥',
  '😬',
  '🤐',
  '🤢',
  '🤧',
  '😷',
  '🤒',
  '🤕',
  '😈',
  '👿',
  '👹',
  '👺',
  '💩',
  '👻',
  '💀',
  '☠️',
  '👽',
  '👾',
  '🤖',
  '🎃',
  '😺',
  '😸',
  '😹',
  '😻',
  '😼',
  '😽',
  '🙀',
  '😿',
  '😾',
  '👐',
  '🙌',
  '👏',
  '🙏',
  '🤝',
  '👍',
  '👎',
  '👊',
  '✊',
  '🤛',
  '🤜',
  '🤞',
  '✌️',
  '🤘',
  '👌',
  '👈',
  '👉',
  '👆',
  '👇',
  '☝️',
  '✋',
  '🤚',
  '🖐',
  '🖖',
  '👋',
  '🤙',
  '💪',
  '🖕',
  '✍️',
  '🤳',
  '💅',
  '💍',
  '💄',
  '💋',
  '👄',
  '👅',
  '👂',
  '👃',
  '👣',
  '👁',
  '👀',
  '🗣',
  '👤',
  '👥',
  '👶',
  '👦',
  '👧',
  '👨',
  '👩',
  '👱‍♀',
  '👱',
  '👴',
  '👵',
  '👲',
  '👳‍♀',
  '👳',
  '👮‍♀',
  '👮',
  '👷‍♀',
  '👷',
  '💂‍♀',
  '💂',
  '👩‍⚕',
  '👨‍⚕',
  '👩‍🌾',
  '👨‍🌾',
  '👩‍🍳',
  '👨‍🍳',
  '👩‍🎓',
  '👨‍🎓',
  '👩‍🎤',
  '👨‍🎤',
  '👩‍🏫',
  '👨‍🏫',
  '👩‍🏭',
  '👨‍🏭',
  '👩‍💻',
  '👨‍💻',
  '👩‍💼',
  '👨‍💼',
  '👩‍🔧',
  '👨‍🔧',
  '👩‍🔬',
  '👨‍🔬',
  '👩‍🎨',
  '👨‍🎨',
  '👩‍🚒',
  '👨‍🚒',
  '👩‍🚀',
  '👨‍🚀',
  '🤶',
  '🎅',
  '👸',
  '🤴',
  '👰',
  '🤵',
  '👼',
  '🤰',
  '🙇‍♀',
  '🙇',
  '💁',
  '💁‍♂',
  '🙅',
  '🙅‍♂',
  '🙆',
  '🙆‍♂',
  '🙋',
  '🙋‍♂',
  '🤦‍♀',
  '🤦‍♂',
  '🤷‍♀',
  '🤷‍♂',
  '🙎',
  '🙎‍♂',
  '🙍',
  '🙍‍♂',
  '💇',
  '💇‍♂',
  '💆',
  '💆‍♂',
  '🕴',
  '💃',
  '🕺',
  '👯',
  '👯‍♂',
  '🚶‍♀',
  '🚶',
  '🏃‍♀',
  '🏃',
  '👫',
  '👭',
  '👬',
  '💑',
  '👩‍❤️‍👩',
  '👨‍❤️‍👨',
  '💏',
  '👩‍❤️‍💋‍👩',
  '👨‍❤️‍💋‍👨',
  '👪',
  '👨‍👩‍👧',
  '👨‍👩‍👧‍👦',
  '👨‍👩‍👦‍👦',
  '👨‍👩‍👧‍👧',
  '👩‍👩‍👦',
  '👩‍👩‍👧',
  '👩‍👩‍👧‍👦',
  '👩‍👩‍👦‍👦',
  '👩‍👩‍👧‍👧',
  '👨‍👨‍👦',
  '👨‍👨‍👧',
  '👨‍👨‍👧‍👦',
  '👨‍👨‍👦‍👦',
  '👨‍👨‍👧‍👧',
  '👩‍👦',
  '👩‍👧',
  '👩‍👧‍👦',
  '👩‍👦‍👦',
  '👩‍👧‍👧',
  '👨‍👦',
  '👨‍👧',
  '👨‍👧‍👦',
  '👨‍👦‍👦',
  '👨‍👧‍👧',
  '👚',
  '👕',
  '👖',
  '👔',
  '👗',
  '👙',
  '👘',
  '👠',
  '👡',
  '👢',
  '👞',
  '👟',
  '👒',
  '🎩',
  '🎓',
  '👑',
  '⛑',
  '🎒',
  '👝',
  '👛',
  '👜',
  '💼',
  '👓',
  '🕶',
  '🌂',
  '☂️',
  '🐶',
  '🐱',
  '🐭',
  '🐹',
  '🐰',
  '🦊',
  '🐻',
  '🐼',
  '🐨',
  '🐯',
  '🦁',
  '🐮',
  '🐷',
  '🐽',
  '🐸',
  '🐵',
  '🙈',
  '🙉',
  '🙊',
  '🐒',
  '🐔',
  '🐧',
  '🐦',
  '🐤',
  '🐣',
  '🐥',
  '🦆',
  '🦅',
  '🦉',
  '🦇',
  '🐺',
  '🐗',
  '🐴',
  '🦄',
  '🐝',
  '🐛',
  '🦋',
  '🐌',
  '🐚',
  '🐞',
  '🐜',
  '🕷',
  '🕸',
  '🐢',
  '🐍',
  '🦎',
  '🦂',
  '🦀',
  '🦑',
  '🐙',
  '🦐',
  '🐠',
  '🐟',
  '🐡',
  '🐬',
  '🦈',
  '🐳',
  '🐋',
  '🐊',
  '🐆',
  '🐅',
  '🐃',
  '🐂',
  '🐄',
  '🦌',
  '🐪',
  '🐫',
  '🐘',
  '🦏',
  '🦍',
  '🐎',
  '🐖',
  '🐐',
  '🐏',
  '🐑',
  '🐕',
  '🐩',
  '🐈',
  '🐓',
  '🦃',
  '🕊',
  '🐇',
  '🐁',
  '🐀',
  '🐿',
  '🐾',
  '🐉',
  '🐲',
  '🌵',
  '🎄',
  '🌲',
  '🌳',
  '🌴',
  '🌱',
  '🌿',
  '☘️',
  '🍀',
  '🎍',
  '🎋',
  '🍃',
  '🍂',
  '🍁',
  '🍄',
  '🌾',
  '💐',
  '🌷',
  '🌹',
  '🥀',
  '🌻',
  '🌼',
  '🌸',
  '🌺',
  '🌎',
  '🌍',
  '🌏',
  '🌕',
  '🌖',
  '🌗',
  '🌘',
  '🌑',
  '🌒',
  '🌓',
  '🌔',
  '🌚',
  '🌝',
  '🌞',
  '🌛',
  '🌜',
  '🌙',
  '💫',
  '⭐️',
  '🌟',
  '✨',
  '⚡️',
  '🔥',
  '💥',
  '☄',
  '☀️',
  '🌤',
  '⛅️',
  '🌥',
  '🌦',
  '🌈',
  '☁️',
  '🌧',
  '⛈',
  '🌩',
  '🌨',
  '☃️',
  '⛄️',
  '❄️',
  '🌬',
  '💨',
  '🌪',
  '🌫',
  '🌊',
  '💧',
  '💦',
  '☔️',
  '🍏',
  '🍎',
  '🍐',
  '🍊',
  '🍋',
  '🍌',
  '🍉',
  '🍇',
  '🍓',
  '🍈',
  '🍒',
  '🍑',
  '🍍',
  '🥝',
  '🥑',
  '🍅',
  '🍆',
  '🥒',
  '🥕',
  '🌽',
  '🌶',
  '🥔',
  '🍠',
  '🌰',
  '🥜',
  '🍯',
  '🥐',
  '🍞',
  '🥖',
  '🧀',
  '🥚',
  '🍳',
  '🥓',
  '🥞',
  '🍤',
  '🍗',
  '🍖',
  '🍕',
  '🌭',
  '🍔',
  '🍟',
  '🥙',
  '🌮',
  '🌯',
  '🥗',
  '🥘',
  '🍝',
  '🍜',
  '🍲',
  '🍥',
  '🍣',
  '🍱',
  '🍛',
  '🍚',
  '🍙',
  '🍘',
  '🍢',
  '🍡',
  '🍧',
  '🍨',
  '🍦',
  '🍰',
  '🎂',
  '🍮',
  '🍭',
  '🍬',
  '🍫',
  '🍿',
  '🍩',
  '🍪',
  '🥛',
  '🍼',
  '☕️',
  '🍵',
  '🍶',
  '🍺',
  '🍻',
  '🥂',
  '🍷',
  '🥃',
  '🍸',
  '🍹',
  '🍾',
  '🥄',
  '🍴',
  '🍽',
  '⚽️',
  '🏀',
  '🏈',
  '⚾️',
  '🎾',
  '🏐',
  '🏉',
  '🎱',
  '🏓',
  '🏸',
  '🥅',
  '🏒',
  '🏑',
  '🏏',
  '⛳️',
  '🏹',
  '🎣',
  '🥊',
  '🥋',
  '⛸',
  '🎿',
  '⛷',
  '🏂',
  '🏋️‍♀️',
  '🏋',
  '🤺',
  '🤼‍♀',
  '🤼‍♂',
  '🤸‍♀',
  '🤸‍♂',
  '⛹️‍♀️',
  '⛹',
  '🤾‍♀',
  '🤾‍♂',
  '🏌️‍♀️',
  '🏌',
  '🏄‍♀',
  '🏄',
  '🏊‍♀',
  '🏊',
  '🤽‍♀',
  '🤽‍♂',
  '🚣‍♀',
  '🚣',
  '🏇',
  '🚴‍♀',
  '🚴',
  '🚵‍♀',
  '🚵',
  '🎽',
  '🏅',
  '🎖',
  '🥇',
  '🥈',
  '🥉',
  '🏆',
  '🏵',
  '🎗',
  '🎫',
  '🎟',
  '🎪',
  '🤹‍♀',
  '🤹‍♂',
  '🎭',
  '🎨',
  '🎬',
  '🎤',
  '🎧',
  '🎼',
  '🎹',
  '🥁',
  '🎷',
  '🎺',
  '🎸',
  '🎻',
  '🎲',
  '🎯',
  '🎳',
  '🎮',
  '🎰',
  '🚗',
  '🚕',
  '🚙',
  '🚌',
  '🚎',
  '🏎',
  '🚓',
  '🚑',
  '🚒',
  '🚐',
  '🚚',
  '🚛',
  '🚜',
  '🛴',
  '🚲',
  '🛵',
  '🏍',
  '🚨',
  '🚔',
  '🚍',
  '🚘',
  '🚖',
  '🚡',
  '🚠',
  '🚟',
  '🚃',
  '🚋',
  '🚞',
  '🚝',
  '🚄',
  '🚅',
  '🚈',
  '🚂',
  '🚆',
  '🚇',
  '🚊',
  '🚉',
  '🚁',
  '🛩',
  '✈️',
  '🛫',
  '🛬',
  '🚀',
  '🛰',
  '💺',
  '🛶',
  '⛵️',
  '🛥',
  '🚤',
  '🛳',
  '⛴',
  '🚢',
  '⚓️',
  '🚧',
  '⛽️',
  '🚏',
  '🚦',
  '🚥',
  '🗺',
  '🗿',
  '🗽',
  '⛲️',
  '🗼',
  '🏰',
  '🏯',
  '🏟',
  '🎡',
  '🎢',
  '🎠',
  '⛱',
  '🏖',
  '🏝',
  '⛰',
  '🏔',
  '🗻',
  '🌋',
  '🏜',
  '🏕',
  '⛺️',
  '🛤',
  '🛣',
  '🏗',
  '🏭',
  '🏠',
  '🏡',
  '🏘',
  '🏚',
  '🏢',
  '🏬',
  '🏣',
  '🏤',
  '🏥',
  '🏦',
  '🏨',
  '🏪',
  '🏫',
  '🏩',
  '💒',
  '🏛',
  '⛪️',
  '🕌',
  '🕍',
  '🕋',
  '⛩',
  '🗾',
  '🎑',
  '🏞',
  '🌅',
  '🌄',
  '🌠',
  '🎇',
  '🎆',
  '🌇',
  '🌆',
  '🏙',
  '🌃',
  '🌌',
  '🌉',
  '🌁',
  '⌚️',
  '📱',
  '📲',
  '💻',
  '⌨️',
  '🖥',
  '🖨',
  '🖱',
  '🖲',
  '🕹',
  '🗜',
  '💽',
  '💾',
  '💿',
  '📀',
  '📼',
  '📷',
  '📸',
  '📹',
  '🎥',
  '📽',
  '🎞',
  '📞',
  '☎️',
  '📟',
  '📠',
  '📺',
  '📻',
  '🎙',
  '🎚',
  '🎛',
  '⏱',
  '⏲',
  '⏰',
  '🕰',
  '⌛️',
  '⏳',
  '📡',
  '🔋',
  '🔌',
  '💡',
  '🔦',
  '🕯',
  '🗑',
  '🛢',
  '💸',
  '💵',
  '💴',
  '💶',
  '💷',
  '💰',
  '💳',
  '💎',
  '⚖️',
  '🔧',
  '🔨',
  '⚒',
  '🛠',
  '⛏',
  '🔩',
  '⚙️',
  '⛓',
  '🔫',
  '💣',
  '🔪',
  '🗡',
  '⚔️',
  '🛡',
  '🚬',
  '⚰️',
  '⚱️',
  '🏺',
  '🔮',
  '📿',
  '💈',
  '⚗️',
  '🔭',
  '🔬',
  '🕳',
  '💊',
  '💉',
  '🌡',
  '🚽',
  '🚰',
  '🚿',
  '🛁',
  '🛀',
  '🛎',
  '🔑',
  '🗝',
  '🚪',
  '🛋',
  '🛏',
  '🛌',
  '🖼',
  '🛍',
  '🛒',
  '🎁',
  '🎈',
  '🎏',
  '🎀',
  '🎊',
  '🎉',
  '🎎',
  '🏮',
  '🎐',
  '✉️',
  '📩',
  '📨',
  '📧',
  '💌',
  '📥',
  '📤',
  '📦',
  '🏷',
  '📪',
  '📫',
  '📬',
  '📭',
  '📮',
  '📯',
  '📜',
  '📃',
  '📄',
  '📑',
  '📊',
  '📈',
  '📉',
  '🗒',
  '🗓',
  '📆',
  '📅',
  '📇',
  '🗃',
  '🗳',
  '🗄',
  '📋',
  '📁',
  '📂',
  '🗂',
  '🗞',
  '📰',
  '📓',
  '📔',
  '📒',
  '📕',
  '📗',
  '📘',
  '📙',
  '📚',
  '📖',
  '🔖',
  '🔗',
  '📎',
  '🖇',
  '📐',
  '📏',
  '📌',
  '📍',
  '✂️',
  '🖊',
  '🖋',
  '✒️',
  '🖌',
  '🖍',
  '📝',
  '✏️',
  '🔍',
  '🔎',
  '🔏',
  '🔐',
  '🔒',
  '🔓',
  '❤️',
  '💛',
  '💚',
  '💙',
  '💜',
  '🖤',
  '💔',
  '❣️',
  '💕',
  '💞',
  '💓',
  '💗',
  '💖',
  '💘',
  '💝',
  '💟',
  '☮️',
  '✝️',
  '☪️',
  '🕉',
  '☸️',
  '✡️',
  '🔯',
  '🕎',
  '☯️',
  '☦️',
  '🛐',
  '⛎',
  '♈️',
  '♉️',
  '♊️',
  '♋️',
  '♌️',
  '♍️',
  '♎️',
  '♏️',
  '♐️',
  '♑️',
  '♒️',
  '♓️',
  '🆔',
  '⚛️',
  '🉑',
  '☢️',
  '☣️',
  '📴',
  '📳',
  '🈶',
  '🈚️',
  '🈸',
  '🈺',
  '🈷️',
  '✴️',
  '🆚',
  '💮',
  '🉐',
  '㊙️',
  '㊗️',
  '🈴',
  '🈵',
  '🈹',
  '🈲',
  '🅰️',
  '🅱️',
  '🆎',
  '🆑',
  '🅾️',
  '🆘',
  '❌',
  '⭕️',
  '🛑',
  '⛔️',
  '📛',
  '🚫',
  '💯',
  '💢',
  '♨️',
  '🚷',
  '🚯',
  '🚳',
  '🚱',
  '🔞',
  '📵',
  '🚭',
  '❗️',
  '❕',
  '❓',
  '❔',
  '‼️',
  '⁉️',
  '🔅',
  '🔆',
  '〽️',
  '⚠️',
  '🚸',
  '🔱',
  '⚜️',
  '🔰',
  '♻️',
  '✅',
  '🈯️',
  '💹',
  '❇️',
  '✳️',
  '❎',
  '🌐',
  '💠',
  'Ⓜ️',
  '🌀',
  '💤',
  '🏧',
  '🚾',
  '♿️',
  '🅿️',
  '🈳',
  '🈂️',
  '🛂',
  '🛃',
  '🛄',
  '🛅',
  '🚹',
  '🚺',
  '🚼',
  '🚻',
  '🚮',
  '🎦',
  '📶',
  '🈁',
  '🔣',
  'ℹ️',
  '🔤',
  '🔡',
  '🔠',
  '🆖',
  '🆗',
  '🆙',
  '🆒',
  '🆕',
  '🆓',
  '0️⃣',
  '1️⃣',
  '2️⃣',
  '3️⃣',
  '4️⃣',
  '5️⃣',
  '6️⃣',
  '7️⃣',
  '8️⃣',
  '9️⃣',
  '🔟',
  '🔢',
  '#️⃣',
  '*️⃣',
  '▶️',
  '⏸',
  '⏯',
  '⏹',
  '⏺',
  '⏭',
  '⏮',
  '⏩',
  '⏪',
  '⏫',
  '⏬',
  '◀️',
  '🔼',
  '🔽',
  '➡️',
  '⬅️',
  '⬆️',
  '⬇️',
  '↗️',
  '↘️',
  '↙️',
  '↖️',
  '↕️',
  '↔️',
  '↪️',
  '↩️',
  '⤴️',
  '⤵️',
  '🔀',
  '🔁',
  '🔂',
  '🔄',
  '🔃',
  '🎵',
  '🎶',
  '➕',
  '➖',
  '➗',
  '✖️',
  '💲',
  '💱',
  '™️',
  '©️',
  '®️',
  '〰️',
  '➰',
  '➿',
  '🔚',
  '🔙',
  '🔛',
  '🔝',
  '🔜',
  '✔️',
  '☑️',
  '🔘',
  '⚪️',
  '⚫️',
  '🔴',
  '🔵',
  '🔺',
  '🔻',
  '🔸',
  '🔹',
  '🔶',
  '🔷',
  '🔳',
  '🔲',
  '▪️',
  '▫️',
  '◾️',
  '◽️',
  '◼️',
  '◻️',
  '⬛️',
  '⬜️',
  '🔈',
  '🔇',
  '🔉',
  '🔊',
  '🔔',
  '🔕',
  '📣',
  '📢',
  '👁‍🗨',
  '💬',
  '💭',
  '🗯',
  '♠️',
  '♣️',
  '♥️',
  '♦️',
  '🃏',
  '🎴',
  '🀄️',
  '🕐',
  '🕑',
  '🕒',
  '🕓',
  '🕔',
  '🕕',
  '🕖',
  '🕗',
  '🕘',
  '🕙',
  '🕚',
  '🕛',
  '🕜',
  '🕝',
  '🕞',
  '🕟',
  '🕠',
  '🕡',
  '🕢',
  '🕣',
  '🕤',
  '🕥',
  '🕦',
  '🕧',
  '🏳️',
  '🏴',
  '🏁',
  '🚩',
  '🏳️‍🌈',
  '🇦🇫',
  '🇦🇽',
  '🇦🇱',
  '🇩🇿',
  '🇦🇸',
  '🇦🇩',
  '🇦🇴',
  '🇦🇮',
  '🇦🇶',
  '🇦🇬',
  '🇦🇷',
  '🇦🇲',
  '🇦🇼',
  '🇦🇺',
  '🇦🇹',
  '🇦🇿',
  '🇧🇸',
  '🇧🇭',
  '🇧🇩',
  '🇧🇧',
  '🇧🇾',
  '🇧🇪',
  '🇧🇿',
  '🇧🇯',
  '🇧🇲',
  '🇧🇹',
  '🇧🇴',
  '🇧🇶',
  '🇧🇦',
  '🇧🇼',
  '🇧🇷',
  '🇮🇴',
  '🇻🇬',
  '🇧🇳',
  '🇧🇬',
  '🇧🇫',
  '🇧🇮',
  '🇨🇻',
  '🇰🇭',
  '🇨🇲',
  '🇨🇦',
  '🇮🇨',
  '🇰🇾',
  '🇨🇫',
  '🇹🇩',
  '🇨🇱',
  '🇨🇳',
  '🇨🇽',
  '🇨🇨',
  '🇨🇴',
  '🇰🇲',
  '🇨🇬',
  '🇨🇩',
  '🇨🇰',
  '🇨🇷',
  '🇨🇮',
  '🇭🇷',
  '🇨🇺',
  '🇨🇼',
  '🇨🇾',
  '🇨🇿',
  '🇩🇰',
  '🇩🇯',
  '🇩🇲',
  '🇩🇴',
  '🇪🇨',
  '🇪🇬',
  '🇸🇻',
  '🇬🇶',
  '🇪🇷',
  '🇪🇪',
  '🇪🇹',
  '🇪🇺',
  '🇫🇰',
  '🇫🇴',
  '🇫🇯',
  '🇫🇮',
  '🇫🇷',
  '🇬🇫',
  '🇵🇫',
  '🇹🇫',
  '🇬🇦',
  '🇬🇲',
  '🇬🇪',
  '🇩🇪',
  '🇬🇭',
  '🇬🇮',
  '🇬🇷',
  '🇬🇱',
  '🇬🇩',
  '🇬🇵',
  '🇬🇺',
  '🇬🇹',
  '🇬🇬',
  '🇬🇳',
  '🇬🇼',
  '🇬🇾',
  '🇭🇹',
  '🇭🇳',
  '🇭🇰',
  '🇭🇺',
  '🇮🇸',
  '🇮🇳',
  '🇮🇩',
  '🇮🇷',
  '🇮🇶',
  '🇮🇪',
  '🇮🇲',
  '🇮🇱',
  '🇮🇹',
  '🇯🇲',
  '🇯🇵',
  '🎌',
  '🇯🇪',
  '🇯🇴',
  '🇰🇿',
  '🇰🇪',
  '🇰🇮',
  '🇽🇰',
  '🇰🇼',
  '🇰🇬',
  '🇱🇦',
  '🇱🇻',
  '🇱🇧',
  '🇱🇸',
  '🇱🇷',
  '🇱🇾',
  '🇱🇮',
  '🇱🇹',
  '🇱🇺',
  '🇲🇴',
  '🇲🇰',
  '🇲🇬',
  '🇲🇼',
  '🇲🇾',
  '🇲🇻',
  '🇲🇱',
  '🇲🇹',
  '🇲🇭',
  '🇲🇶',
  '🇲🇷',
  '🇲🇺',
  '🇾🇹',
  '🇲🇽',
  '🇫🇲',
  '🇲🇩',
  '🇲🇨',
  '🇲🇳',
  '🇲🇪',
  '🇲🇸',
  '🇲🇦',
  '🇲🇿',
  '🇲🇲',
  '🇳🇦',
  '🇳🇷',
  '🇳🇵',
  '🇳🇱',
  '🇳🇨',
  '🇳🇿',
  '🇳🇮',
  '🇳🇪',
  '🇳🇬',
  '🇳🇺',
  '🇳🇫',
  '🇲🇵',
  '🇰🇵',
  '🇳🇴',
  '🇴🇲',
  '🇵🇰',
  '🇵🇼',
  '🇵🇸',
  '🇵🇦',
  '🇵🇬',
  '🇵🇾',
  '🇵🇪',
  '🇵🇭',
  '🇵🇳',
  '🇵🇱',
  '🇵🇹',
  '🇵🇷',
  '🇶🇦',
  '🇷🇪',
  '🇷🇴',
  '🇷🇺',
  '🇷🇼',
  '🇧🇱',
  '🇸🇭',
  '🇰🇳',
  '🇱🇨',
  '🇵🇲',
  '🇻🇨',
  '🇼🇸',
  '🇸🇲',
  '🇸🇹',
  '🇸🇦',
  '🇸🇳',
  '🇷🇸',
  '🇸🇨',
  '🇸🇱',
  '🇸🇬',
  '🇸🇽',
  '🇸🇰',
  '🇸🇮',
  '🇸🇧',
  '🇸🇴',
  '🇿🇦',
  '🇬🇸',
  '🇰🇷',
  '🇸🇸',
  '🇪🇸',
  '🇱🇰',
  '🇸🇩',
  '🇸🇷',
  '🇸🇿',
  '🇸🇪',
  '🇨🇭',
  '🇸🇾',
  '🇹🇼',
  '🇹🇯',
  '🇹🇿',
  '🇹🇭',
  '🇹🇱',
  '🇹🇬',
  '🇹🇰',
  '🇹🇴',
  '🇹🇹',
  '🇹🇳',
  '🇹🇷',
  '🇹🇲',
  '🇹🇨',
  '🇹🇻',
  '🇺🇬',
  '🇺🇦',
  '🇦🇪',
  '🇬🇧',
  '🇺🇸',
  '🇻🇮',
  '🇺🇾',
  '🇺🇿',
  '🇻🇺',
  '🇻🇦',
  '🇻🇪',
  '🇻🇳',
  '🇼🇫',
  '🇪🇭',
  '🇾🇪',
  '🇿🇲',
  '🇿🇼',
];
// 图标与图标base64的映射关系
export const EMOJIMAP = new Map([
  ['JUYwJTlGJTk4JTgw', '😀'],
  ['JUYwJTlGJTk4JTgz', '😃'],
  ['JUYwJTlGJTk4JTg0', '😄'],
  ['JUYwJTlGJTk4JTgx', '😁'],
  ['JUYwJTlGJTk4JTg2', '😆'],
  ['JUYwJTlGJTk4JTg1', '😅'],
  ['JUYwJTlGJTk4JTgy', '😂'],
  ['JUYwJTlGJUE0JUEz', '🤣'],
  ['JUYwJTlGJTk4JThD', '😌'],
  ['JUYwJTlGJTk4JThB', '😊'],
  ['JUYwJTlGJTk4JTg3', '😇'],
  ['JUYwJTlGJTk5JTgy', '🙂'],
  ['JUYwJTlGJTk5JTgz', '🙃'],
  ['JUYwJTlGJTk4JTg5', '😉'],
  ['JUYwJTlGJTk4JThE', '😍'],
  ['JUYwJTlGJTk4JTk4', '😘'],
  ['JUYwJTlGJTk4JTk3', '😗'],
  ['JUYwJTlGJTk4JTk5', '😙'],
  ['JUYwJTlGJTk4JTlB', '😚'],
  ['JUYwJTlGJTk4JThC', '😋'],
  ['JUYwJTlGJTk4JTlD', '😜'],
  ['JUYwJTlGJTk4JTlE', '😝'],
  ['JUYwJTlGJTk4JTlC', '😛'],
  ['JUYwJTlGJUE0JTkx', '🤑'],
  ['JUYwJTlGJUE0JTk3', '🤗'],
  ['JUYwJTlGJUE0JTkz', '🤓'],
  ['JUYwJTlGJTk4JThF', '😎'],
  ['JUYwJTlGJUE0JUEx', '🤡'],
  ['JUYwJTlGJUE0JUEw', '🤠'],
  ['JUYwJTlGJTk4JThG', '😏'],
  ['JUYwJTlGJTk4JTky', '😒'],
  ['JUYwJTlGJTk4JTlF', '😞'],
  ['JUYwJTlGJTk4JTk0', '😔'],
  ['JUYwJTlGJTk4JTlG', '😟'],
  ['JUYwJTlGJTk4JTk1', '😕'],
  ['JUYwJTlGJTk5JTgx', '🙁'],
  ['JUUyJTk4JUI5JUVGJUI4JThG', '☹️'],
  ['JUYwJTlGJTk4JUEz', '😣'],
  ['JUYwJTlGJTk4JTk2', '😖'],
  ['JUYwJTlGJTk4JUFC', '😫'],
  ['JUYwJTlGJTk4JUE5', '😩'],
  ['JUYwJTlGJTk4JUE0', '😤'],
  ['JUYwJTlGJTk4JUEw', '😠'],
  ['JUYwJTlGJTk4JUEx', '😡'],
  ['JUYwJTlGJTk4JUI2', '😶'],
  ['JUYwJTlGJTk4JTkw', '😐'],
  ['JUYwJTlGJTk4JTkx', '😑'],
  ['JUYwJTlGJTk4JUFG', '😯'],
  ['JUYwJTlGJTk4JUE2', '😦'],
  ['JUYwJTlGJTk4JUE3', '😧'],
  ['JUYwJTlGJTk4JUFF', '😮'],
  ['JUYwJTlGJTk4JUIy', '😲'],
  ['JUYwJTlGJTk4JUI1', '😵'],
  ['JUYwJTlGJTk4JUIz', '😳'],
  ['JUYwJTlGJTk4JUIx', '😱'],
  ['JUYwJTlGJTk4JUE4', '😨'],
  ['JUYwJTlGJTk4JUIw', '😰'],
  ['JUYwJTlGJTk4JUEy', '😢'],
  ['JUYwJTlGJTk4JUE1', '😥'],
  ['JUYwJTlGJUE0JUE0', '🤤'],
  ['JUYwJTlGJTk4JUFE', '😭'],
  ['JUYwJTlGJTk4JTkz', '😓'],
  ['JUYwJTlGJTk4JUFB', '😪'],
  ['JUYwJTlGJTk4JUI0', '😴'],
  ['JUYwJTlGJTk5JTg0', '🙄'],
  ['JUYwJTlGJUE0JTk0', '🤔'],
  ['JUYwJTlGJUE0JUE1', '🤥'],
  ['JUYwJTlGJTk4JUFD', '😬'],
  ['JUYwJTlGJUE0JTkw', '🤐'],
  ['JUYwJTlGJUE0JUEy', '🤢'],
  ['JUYwJTlGJUE0JUE3', '🤧'],
  ['JUYwJTlGJTk4JUI3', '😷'],
  ['JUYwJTlGJUE0JTky', '🤒'],
  ['JUYwJTlGJUE0JTk1', '🤕'],
  ['JUYwJTlGJTk4JTg4', '😈'],
  ['JUYwJTlGJTkxJUJG', '👿'],
  ['JUYwJTlGJTkxJUI5', '👹'],
  ['JUYwJTlGJTkxJUJB', '👺'],
  ['JUYwJTlGJTkyJUE5', '💩'],
  ['JUYwJTlGJTkxJUJC', '👻'],
  ['JUYwJTlGJTkyJTgw', '💀'],
  ['JUUyJTk4JUEwJUVGJUI4JThG', '☠️'],
  ['JUYwJTlGJTkxJUJE', '👽'],
  ['JUYwJTlGJTkxJUJF', '👾'],
  ['JUYwJTlGJUE0JTk2', '🤖'],
  ['JUYwJTlGJThFJTgz', '🎃'],
  ['JUYwJTlGJTk4JUJB', '😺'],
  ['JUYwJTlGJTk4JUI4', '😸'],
  ['JUYwJTlGJTk4JUI5', '😹'],
  ['JUYwJTlGJTk4JUJC', '😻'],
  ['JUYwJTlGJTk4JUJD', '😼'],
  ['JUYwJTlGJTk4JUJE', '😽'],
  ['JUYwJTlGJTk5JTgw', '🙀'],
  ['JUYwJTlGJTk4JUJG', '😿'],
  ['JUYwJTlGJTk4JUJF', '😾'],
  ['JUYwJTlGJTkxJTkw', '👐'],
  ['JUYwJTlGJTk5JThD', '🙌'],
  ['JUYwJTlGJTkxJThG', '👏'],
  ['JUYwJTlGJTk5JThG', '🙏'],
  ['JUYwJTlGJUE0JTlE', '🤝'],
  ['JUYwJTlGJTkxJThE', '👍'],
  ['JUYwJTlGJTkxJThF', '👎'],
  ['JUYwJTlGJTkxJThB', '👊'],
  ['JUUyJTlDJThB', '✊'],
  ['JUYwJTlGJUE0JTlC', '🤛'],
  ['JUYwJTlGJUE0JTlD', '🤜'],
  ['JUYwJTlGJUE0JTlF', '🤞'],
  ['JUUyJTlDJThDJUVGJUI4JThG', '✌️'],
  ['JUYwJTlGJUE0JTk4', '🤘'],
  ['JUYwJTlGJTkxJThD', '👌'],
  ['JUYwJTlGJTkxJTg4', '👈'],
  ['JUYwJTlGJTkxJTg5', '👉'],
  ['JUYwJTlGJTkxJTg2', '👆'],
  ['JUYwJTlGJTkxJTg3', '👇'],
  ['JUUyJTk4JTlEJUVGJUI4JThG', '☝️'],
  ['JUUyJTlDJThC', '✋'],
  ['JUYwJTlGJUE0JTlB', '🤚'],
  ['JUYwJTlGJTk2JTkw', '🖐'],
  ['JUYwJTlGJTk2JTk2', '🖖'],
  ['JUYwJTlGJTkxJThC', '👋'],
  ['JUYwJTlGJUE0JTk5', '🤙'],
  ['JUYwJTlGJTkyJUFB', '💪'],
  ['JUYwJTlGJTk2JTk1', '🖕'],
  ['JUUyJTlDJThEJUVGJUI4JThG', '✍️'],
  ['JUYwJTlGJUE0JUIz', '🤳'],
  ['JUYwJTlGJTkyJTg1', '💅'],
  ['JUYwJTlGJTkyJThE', '💍'],
  ['JUYwJTlGJTkyJTg0', '💄'],
  ['JUYwJTlGJTkyJThC', '💋'],
  ['JUYwJTlGJTkxJTg0', '👄'],
  ['JUYwJTlGJTkxJTg1', '👅'],
  ['JUYwJTlGJTkxJTgy', '👂'],
  ['JUYwJTlGJTkxJTgz', '👃'],
  ['JUYwJTlGJTkxJUEz', '👣'],
  ['JUYwJTlGJTkxJTgx', '👁'],
  ['JUYwJTlGJTkxJTgw', '👀'],
  ['JUYwJTlGJTk3JUEz', '🗣'],
  ['JUYwJTlGJTkxJUE0', '👤'],
  ['JUYwJTlGJTkxJUE1', '👥'],
  ['JUYwJTlGJTkxJUI2', '👶'],
  ['JUYwJTlGJTkxJUE2', '👦'],
  ['JUYwJTlGJTkxJUE3', '👧'],
  ['JUYwJTlGJTkxJUE4', '👨'],
  ['JUYwJTlGJTkxJUE5', '👩'],
  ['JUYwJTlGJTkxJUIxJUUyJTgwJThEJUUyJTk5JTgw', '👱‍♀'],
  ['JUYwJTlGJTkxJUIx', '👱'],
  ['JUYwJTlGJTkxJUI0', '👴'],
  ['JUYwJTlGJTkxJUI1', '👵'],
  ['JUYwJTlGJTkxJUIy', '👲'],
  ['JUYwJTlGJTkxJUIzJUUyJTgwJThEJUUyJTk5JTgw', '👳‍♀'],
  ['JUYwJTlGJTkxJUIz', '👳'],
  ['JUYwJTlGJTkxJUFFJUUyJTgwJThEJUUyJTk5JTgw', '👮‍♀'],
  ['JUYwJTlGJTkxJUFF', '👮'],
  ['JUYwJTlGJTkxJUI3JUUyJTgwJThEJUUyJTk5JTgw', '👷‍♀'],
  ['JUYwJTlGJTkxJUI3', '👷'],
  ['JUYwJTlGJTkyJTgyJUUyJTgwJThEJUUyJTk5JTgw', '💂‍♀'],
  ['JUYwJTlGJTkyJTgy', '💂'],
  ['JUYwJTlGJTkxJUE5JUUyJTgwJThEJUUyJTlBJTk1', '👩‍⚕'],
  ['JUYwJTlGJTkxJUE4JUUyJTgwJThEJUUyJTlBJTk1', '👨‍⚕'],
  ['JUYwJTlGJTkxJUE5JUUyJTgwJThEJUYwJTlGJThDJUJF', '👩‍🌾'],
  ['JUYwJTlGJTkxJUE4JUUyJTgwJThEJUYwJTlGJThDJUJF', '👨‍🌾'],
  ['JUYwJTlGJTkxJUE5JUUyJTgwJThEJUYwJTlGJThEJUIz', '👩‍🍳'],
  ['JUYwJTlGJTkxJUE4JUUyJTgwJThEJUYwJTlGJThEJUIz', '👨‍🍳'],
  ['JUYwJTlGJTkxJUE5JUUyJTgwJThEJUYwJTlGJThFJTkz', '👩‍🎓'],
  ['JUYwJTlGJTkxJUE4JUUyJTgwJThEJUYwJTlGJThFJTkz', '👨‍🎓'],
  ['JUYwJTlGJTkxJUE5JUUyJTgwJThEJUYwJTlGJThFJUE0', '👩‍🎤'],
  ['JUYwJTlGJTkxJUE4JUUyJTgwJThEJUYwJTlGJThFJUE0', '👨‍🎤'],
  ['JUYwJTlGJTkxJUE5JUUyJTgwJThEJUYwJTlGJThGJUFC', '👩‍🏫'],
  ['JUYwJTlGJTkxJUE4JUUyJTgwJThEJUYwJTlGJThGJUFC', '👨‍🏫'],
  ['JUYwJTlGJTkxJUE5JUUyJTgwJThEJUYwJTlGJThGJUFE', '👩‍🏭'],
  ['JUYwJTlGJTkxJUE4JUUyJTgwJThEJUYwJTlGJThGJUFE', '👨‍🏭'],
  ['JUYwJTlGJTkxJUE5JUUyJTgwJThEJUYwJTlGJTkyJUJC', '👩‍💻'],
  ['JUYwJTlGJTkxJUE4JUUyJTgwJThEJUYwJTlGJTkyJUJC', '👨‍💻'],
  ['JUYwJTlGJTkxJUE5JUUyJTgwJThEJUYwJTlGJTkyJUJD', '👩‍💼'],
  ['JUYwJTlGJTkxJUE4JUUyJTgwJThEJUYwJTlGJTkyJUJD', '👨‍💼'],
  ['JUYwJTlGJTkxJUE5JUUyJTgwJThEJUYwJTlGJTk0JUE3', '👩‍🔧'],
  ['JUYwJTlGJTkxJUE4JUUyJTgwJThEJUYwJTlGJTk0JUE3', '👨‍🔧'],
  ['JUYwJTlGJTkxJUE5JUUyJTgwJThEJUYwJTlGJTk0JUFD', '👩‍🔬'],
  ['JUYwJTlGJTkxJUE4JUUyJTgwJThEJUYwJTlGJTk0JUFD', '👨‍🔬'],
  ['JUYwJTlGJTkxJUE5JUUyJTgwJThEJUYwJTlGJThFJUE4', '👩‍🎨'],
  ['JUYwJTlGJTkxJUE4JUUyJTgwJThEJUYwJTlGJThFJUE4', '👨‍🎨'],
  ['JUYwJTlGJTkxJUE5JUUyJTgwJThEJUYwJTlGJTlBJTky', '👩‍🚒'],
  ['JUYwJTlGJTkxJUE4JUUyJTgwJThEJUYwJTlGJTlBJTky', '👨‍🚒'],
  ['JUYwJTlGJTkxJUE5JUUyJTgwJThEJUYwJTlGJTlBJTgw', '👩‍🚀'],
  ['JUYwJTlGJTkxJUE4JUUyJTgwJThEJUYwJTlGJTlBJTgw', '👨‍🚀'],
  ['JUYwJTlGJUE0JUI2', '🤶'],
  ['JUYwJTlGJThFJTg1', '🎅'],
  ['JUYwJTlGJTkxJUI4', '👸'],
  ['JUYwJTlGJUE0JUI0', '🤴'],
  ['JUYwJTlGJTkxJUIw', '👰'],
  ['JUYwJTlGJUE0JUI1', '🤵'],
  ['JUYwJTlGJTkxJUJD', '👼'],
  ['JUYwJTlGJUE0JUIw', '🤰'],
  ['JUYwJTlGJTk5JTg3JUUyJTgwJThEJUUyJTk5JTgw', '🙇‍♀'],
  ['JUYwJTlGJTk5JTg3', '🙇'],
  ['JUYwJTlGJTkyJTgx', '💁'],
  ['JUYwJTlGJTkyJTgxJUUyJTgwJThEJUUyJTk5JTgy', '💁‍♂'],
  ['JUYwJTlGJTk5JTg1', '🙅'],
  ['JUYwJTlGJTk5JTg1JUUyJTgwJThEJUUyJTk5JTgy', '🙅‍♂'],
  ['JUYwJTlGJTk5JTg2', '🙆'],
  ['JUYwJTlGJTk5JTg2JUUyJTgwJThEJUUyJTk5JTgy', '🙆‍♂'],
  ['JUYwJTlGJTk5JThC', '🙋'],
  ['JUYwJTlGJTk5JThCJUUyJTgwJThEJUUyJTk5JTgy', '🙋‍♂'],
  ['JUYwJTlGJUE0JUE2JUUyJTgwJThEJUUyJTk5JTgw', '🤦‍♀'],
  ['JUYwJTlGJUE0JUE2JUUyJTgwJThEJUUyJTk5JTgy', '🤦‍♂'],
  ['JUYwJTlGJUE0JUI3JUUyJTgwJThEJUUyJTk5JTgw', '🤷‍♀'],
  ['JUYwJTlGJUE0JUI3JUUyJTgwJThEJUUyJTk5JTgy', '🤷‍♂'],
  ['JUYwJTlGJTk5JThF', '🙎'],
  ['JUYwJTlGJTk5JThFJUUyJTgwJThEJUUyJTk5JTgy', '🙎‍♂'],
  ['JUYwJTlGJTk5JThE', '🙍'],
  ['JUYwJTlGJTk5JThEJUUyJTgwJThEJUUyJTk5JTgy', '🙍‍♂'],
  ['JUYwJTlGJTkyJTg3', '💇'],
  ['JUYwJTlGJTkyJTg3JUUyJTgwJThEJUUyJTk5JTgy', '💇‍♂'],
  ['JUYwJTlGJTkyJTg2', '💆'],
  ['JUYwJTlGJTkyJTg2JUUyJTgwJThEJUUyJTk5JTgy', '💆‍♂'],
  ['JUYwJTlGJTk1JUI0', '🕴'],
  ['JUYwJTlGJTkyJTgz', '💃'],
  ['JUYwJTlGJTk1JUJB', '🕺'],
  ['JUYwJTlGJTkxJUFG', '👯'],
  ['JUYwJTlGJTkxJUFGJUUyJTgwJThEJUUyJTk5JTgy', '👯‍♂'],
  ['JUYwJTlGJTlBJUI2JUUyJTgwJThEJUUyJTk5JTgw', '🚶‍♀'],
  ['JUYwJTlGJTlBJUI2', '🚶'],
  ['JUYwJTlGJThGJTgzJUUyJTgwJThEJUUyJTk5JTgw', '🏃‍♀'],
  ['JUYwJTlGJThGJTgz', '🏃'],
  ['JUYwJTlGJTkxJUFC', '👫'],
  ['JUYwJTlGJTkxJUFE', '👭'],
  ['JUYwJTlGJTkxJUFD', '👬'],
  ['JUYwJTlGJTkyJTkx', '💑'],
  [
    'JUYwJTlGJTkxJUE5JUUyJTgwJThEJUUyJTlEJUE0JUVGJUI4JThGJUUyJTgwJThEJUYwJTlGJTkxJUE5',
    '👩‍❤️‍👩',
  ],
  [
    'JUYwJTlGJTkxJUE4JUUyJTgwJThEJUUyJTlEJUE0JUVGJUI4JThGJUUyJTgwJThEJUYwJTlGJTkxJUE4',
    '👨‍❤️‍👨',
  ],
  ['JUYwJTlGJTkyJThG', '💏'],
  [
    'JUYwJTlGJTkxJUE5JUUyJTgwJThEJUUyJTlEJUE0JUVGJUI4JThGJUUyJTgwJThEJUYwJTlGJTkyJThCJUUyJTgwJThEJUYwJTlGJTkxJUE5',
    '👩‍❤️‍💋‍👩',
  ],
  [
    'JUYwJTlGJTkxJUE4JUUyJTgwJThEJUUyJTlEJUE0JUVGJUI4JThGJUUyJTgwJThEJUYwJTlGJTkyJThCJUUyJTgwJThEJUYwJTlGJTkxJUE4',
    '👨‍❤️‍💋‍👨',
  ],
  ['JUYwJTlGJTkxJUFB', '👪'],
  [
    'JUYwJTlGJTkxJUE4JUUyJTgwJThEJUYwJTlGJTkxJUE5JUUyJTgwJThEJUYwJTlGJTkxJUE3',
    '👨‍👩‍👧',
  ],
  [
    'JUYwJTlGJTkxJUE4JUUyJTgwJThEJUYwJTlGJTkxJUE5JUUyJTgwJThEJUYwJTlGJTkxJUE3JUUyJTgwJThEJUYwJTlGJTkxJUE2',
    '👨‍👩‍👧‍👦',
  ],
  [
    'JUYwJTlGJTkxJUE4JUUyJTgwJThEJUYwJTlGJTkxJUE5JUUyJTgwJThEJUYwJTlGJTkxJUE2JUUyJTgwJThEJUYwJTlGJTkxJUE2',
    '👨‍👩‍👦‍👦',
  ],
  [
    'JUYwJTlGJTkxJUE4JUUyJTgwJThEJUYwJTlGJTkxJUE5JUUyJTgwJThEJUYwJTlGJTkxJUE3JUUyJTgwJThEJUYwJTlGJTkxJUE3',
    '👨‍👩‍👧‍👧',
  ],
  [
    'JUYwJTlGJTkxJUE5JUUyJTgwJThEJUYwJTlGJTkxJUE5JUUyJTgwJThEJUYwJTlGJTkxJUE2',
    '👩‍👩‍👦',
  ],
  [
    'JUYwJTlGJTkxJUE5JUUyJTgwJThEJUYwJTlGJTkxJUE5JUUyJTgwJThEJUYwJTlGJTkxJUE3',
    '👩‍👩‍👧',
  ],
  [
    'JUYwJTlGJTkxJUE5JUUyJTgwJThEJUYwJTlGJTkxJUE5JUUyJTgwJThEJUYwJTlGJTkxJUE3JUUyJTgwJThEJUYwJTlGJTkxJUE2',
    '👩‍👩‍👧‍👦',
  ],
  [
    'JUYwJTlGJTkxJUE5JUUyJTgwJThEJUYwJTlGJTkxJUE5JUUyJTgwJThEJUYwJTlGJTkxJUE2JUUyJTgwJThEJUYwJTlGJTkxJUE2',
    '👩‍👩‍👦‍👦',
  ],
  [
    'JUYwJTlGJTkxJUE5JUUyJTgwJThEJUYwJTlGJTkxJUE5JUUyJTgwJThEJUYwJTlGJTkxJUE3JUUyJTgwJThEJUYwJTlGJTkxJUE3',
    '👩‍👩‍👧‍👧',
  ],
  [
    'JUYwJTlGJTkxJUE4JUUyJTgwJThEJUYwJTlGJTkxJUE4JUUyJTgwJThEJUYwJTlGJTkxJUE2',
    '👨‍👨‍👦',
  ],
  [
    'JUYwJTlGJTkxJUE4JUUyJTgwJThEJUYwJTlGJTkxJUE4JUUyJTgwJThEJUYwJTlGJTkxJUE3',
    '👨‍👨‍👧',
  ],
  [
    'JUYwJTlGJTkxJUE4JUUyJTgwJThEJUYwJTlGJTkxJUE4JUUyJTgwJThEJUYwJTlGJTkxJUE3JUUyJTgwJThEJUYwJTlGJTkxJUE2',
    '👨‍👨‍👧‍👦',
  ],
  [
    'JUYwJTlGJTkxJUE4JUUyJTgwJThEJUYwJTlGJTkxJUE4JUUyJTgwJThEJUYwJTlGJTkxJUE2JUUyJTgwJThEJUYwJTlGJTkxJUE2',
    '👨‍👨‍👦‍👦',
  ],
  [
    'JUYwJTlGJTkxJUE4JUUyJTgwJThEJUYwJTlGJTkxJUE4JUUyJTgwJThEJUYwJTlGJTkxJUE3JUUyJTgwJThEJUYwJTlGJTkxJUE3',
    '👨‍👨‍👧‍👧',
  ],
  ['JUYwJTlGJTkxJUE5JUUyJTgwJThEJUYwJTlGJTkxJUE2', '👩‍👦'],
  ['JUYwJTlGJTkxJUE5JUUyJTgwJThEJUYwJTlGJTkxJUE3', '👩‍👧'],
  [
    'JUYwJTlGJTkxJUE5JUUyJTgwJThEJUYwJTlGJTkxJUE3JUUyJTgwJThEJUYwJTlGJTkxJUE2',
    '👩‍👧‍👦',
  ],
  [
    'JUYwJTlGJTkxJUE5JUUyJTgwJThEJUYwJTlGJTkxJUE2JUUyJTgwJThEJUYwJTlGJTkxJUE2',
    '👩‍👦‍👦',
  ],
  [
    'JUYwJTlGJTkxJUE5JUUyJTgwJThEJUYwJTlGJTkxJUE3JUUyJTgwJThEJUYwJTlGJTkxJUE3',
    '👩‍👧‍👧',
  ],
  ['JUYwJTlGJTkxJUE4JUUyJTgwJThEJUYwJTlGJTkxJUE2', '👨‍👦'],
  ['JUYwJTlGJTkxJUE4JUUyJTgwJThEJUYwJTlGJTkxJUE3', '👨‍👧'],
  [
    'JUYwJTlGJTkxJUE4JUUyJTgwJThEJUYwJTlGJTkxJUE3JUUyJTgwJThEJUYwJTlGJTkxJUE2',
    '👨‍👧‍👦',
  ],
  [
    'JUYwJTlGJTkxJUE4JUUyJTgwJThEJUYwJTlGJTkxJUE2JUUyJTgwJThEJUYwJTlGJTkxJUE2',
    '👨‍👦‍👦',
  ],
  [
    'JUYwJTlGJTkxJUE4JUUyJTgwJThEJUYwJTlGJTkxJUE3JUUyJTgwJThEJUYwJTlGJTkxJUE3',
    '👨‍👧‍👧',
  ],
  ['JUYwJTlGJTkxJTlB', '👚'],
  ['JUYwJTlGJTkxJTk1', '👕'],
  ['JUYwJTlGJTkxJTk2', '👖'],
  ['JUYwJTlGJTkxJTk0', '👔'],
  ['JUYwJTlGJTkxJTk3', '👗'],
  ['JUYwJTlGJTkxJTk5', '👙'],
  ['JUYwJTlGJTkxJTk4', '👘'],
  ['JUYwJTlGJTkxJUEw', '👠'],
  ['JUYwJTlGJTkxJUEx', '👡'],
  ['JUYwJTlGJTkxJUEy', '👢'],
  ['JUYwJTlGJTkxJTlF', '👞'],
  ['JUYwJTlGJTkxJTlG', '👟'],
  ['JUYwJTlGJTkxJTky', '👒'],
  ['JUYwJTlGJThFJUE5', '🎩'],
  ['JUYwJTlGJThFJTkz', '🎓'],
  ['JUYwJTlGJTkxJTkx', '👑'],
  ['JUUyJTlCJTkx', '⛑'],
  ['JUYwJTlGJThFJTky', '🎒'],
  ['JUYwJTlGJTkxJTlE', '👝'],
  ['JUYwJTlGJTkxJTlC', '👛'],
  ['JUYwJTlGJTkxJTlD', '👜'],
  ['JUYwJTlGJTkyJUJD', '💼'],
  ['JUYwJTlGJTkxJTkz', '👓'],
  ['JUYwJTlGJTk1JUI2', '🕶'],
  ['JUYwJTlGJThDJTgy', '🌂'],
  ['JUUyJTk4JTgyJUVGJUI4JThG', '☂️'],
  ['JUYwJTlGJTkwJUI2', '🐶'],
  ['JUYwJTlGJTkwJUIx', '🐱'],
  ['JUYwJTlGJTkwJUFE', '🐭'],
  ['JUYwJTlGJTkwJUI5', '🐹'],
  ['JUYwJTlGJTkwJUIw', '🐰'],
  ['JUYwJTlGJUE2JThB', '🦊'],
  ['JUYwJTlGJTkwJUJC', '🐻'],
  ['JUYwJTlGJTkwJUJD', '🐼'],
  ['JUYwJTlGJTkwJUE4', '🐨'],
  ['JUYwJTlGJTkwJUFG', '🐯'],
  ['JUYwJTlGJUE2JTgx', '🦁'],
  ['JUYwJTlGJTkwJUFF', '🐮'],
  ['JUYwJTlGJTkwJUI3', '🐷'],
  ['JUYwJTlGJTkwJUJE', '🐽'],
  ['JUYwJTlGJTkwJUI4', '🐸'],
  ['JUYwJTlGJTkwJUI1', '🐵'],
  ['JUYwJTlGJTk5JTg4', '🙈'],
  ['JUYwJTlGJTk5JTg5', '🙉'],
  ['JUYwJTlGJTk5JThB', '🙊'],
  ['JUYwJTlGJTkwJTky', '🐒'],
  ['JUYwJTlGJTkwJTk0', '🐔'],
  ['JUYwJTlGJTkwJUE3', '🐧'],
  ['JUYwJTlGJTkwJUE2', '🐦'],
  ['JUYwJTlGJTkwJUE0', '🐤'],
  ['JUYwJTlGJTkwJUEz', '🐣'],
  ['JUYwJTlGJTkwJUE1', '🐥'],
  ['JUYwJTlGJUE2JTg2', '🦆'],
  ['JUYwJTlGJUE2JTg1', '🦅'],
  ['JUYwJTlGJUE2JTg5', '🦉'],
  ['JUYwJTlGJUE2JTg3', '🦇'],
  ['JUYwJTlGJTkwJUJB', '🐺'],
  ['JUYwJTlGJTkwJTk3', '🐗'],
  ['JUYwJTlGJTkwJUI0', '🐴'],
  ['JUYwJTlGJUE2JTg0', '🦄'],
  ['JUYwJTlGJTkwJTlE', '🐝'],
  ['JUYwJTlGJTkwJTlC', '🐛'],
  ['JUYwJTlGJUE2JThC', '🦋'],
  ['JUYwJTlGJTkwJThD', '🐌'],
  ['JUYwJTlGJTkwJTlB', '🐚'],
  ['JUYwJTlGJTkwJTlF', '🐞'],
  ['JUYwJTlGJTkwJTlD', '🐜'],
  ['JUYwJTlGJTk1JUI3', '🕷'],
  ['JUYwJTlGJTk1JUI4', '🕸'],
  ['JUYwJTlGJTkwJUEy', '🐢'],
  ['JUYwJTlGJTkwJThE', '🐍'],
  ['JUYwJTlGJUE2JThF', '🦎'],
  ['JUYwJTlGJUE2JTgy', '🦂'],
  ['JUYwJTlGJUE2JTgw', '🦀'],
  ['JUYwJTlGJUE2JTkx', '🦑'],
  ['JUYwJTlGJTkwJTk5', '🐙'],
  ['JUYwJTlGJUE2JTkw', '🦐'],
  ['JUYwJTlGJTkwJUEw', '🐠'],
  ['JUYwJTlGJTkwJTlG', '🐟'],
  ['JUYwJTlGJTkwJUEx', '🐡'],
  ['JUYwJTlGJTkwJUFD', '🐬'],
  ['JUYwJTlGJUE2JTg4', '🦈'],
  ['JUYwJTlGJTkwJUIz', '🐳'],
  ['JUYwJTlGJTkwJThC', '🐋'],
  ['JUYwJTlGJTkwJThB', '🐊'],
  ['JUYwJTlGJTkwJTg2', '🐆'],
  ['JUYwJTlGJTkwJTg1', '🐅'],
  ['JUYwJTlGJTkwJTgz', '🐃'],
  ['JUYwJTlGJTkwJTgy', '🐂'],
  ['JUYwJTlGJTkwJTg0', '🐄'],
  ['JUYwJTlGJUE2JThD', '🦌'],
  ['JUYwJTlGJTkwJUFB', '🐪'],
  ['JUYwJTlGJTkwJUFC', '🐫'],
  ['JUYwJTlGJTkwJTk4', '🐘'],
  ['JUYwJTlGJUE2JThG', '🦏'],
  ['JUYwJTlGJUE2JThE', '🦍'],
  ['JUYwJTlGJTkwJThF', '🐎'],
  ['JUYwJTlGJTkwJTk2', '🐖'],
  ['JUYwJTlGJTkwJTkw', '🐐'],
  ['JUYwJTlGJTkwJThG', '🐏'],
  ['JUYwJTlGJTkwJTkx', '🐑'],
  ['JUYwJTlGJTkwJTk1', '🐕'],
  ['JUYwJTlGJTkwJUE5', '🐩'],
  ['JUYwJTlGJTkwJTg4', '🐈'],
  ['JUYwJTlGJTkwJTkz', '🐓'],
  ['JUYwJTlGJUE2JTgz', '🦃'],
  ['JUYwJTlGJTk1JThB', '🕊'],
  ['JUYwJTlGJTkwJTg3', '🐇'],
  ['JUYwJTlGJTkwJTgx', '🐁'],
  ['JUYwJTlGJTkwJTgw', '🐀'],
  ['JUYwJTlGJTkwJUJG', '🐿'],
  ['JUYwJTlGJTkwJUJF', '🐾'],
  ['JUYwJTlGJTkwJTg5', '🐉'],
  ['JUYwJTlGJTkwJUIy', '🐲'],
  ['JUYwJTlGJThDJUI1', '🌵'],
  ['JUYwJTlGJThFJTg0', '🎄'],
  ['JUYwJTlGJThDJUIy', '🌲'],
  ['JUYwJTlGJThDJUIz', '🌳'],
  ['JUYwJTlGJThDJUI0', '🌴'],
  ['JUYwJTlGJThDJUIx', '🌱'],
  ['JUYwJTlGJThDJUJG', '🌿'],
  ['JUUyJTk4JTk4JUVGJUI4JThG', '☘️'],
  ['JUYwJTlGJThEJTgw', '🍀'],
  ['JUYwJTlGJThFJThE', '🎍'],
  ['JUYwJTlGJThFJThC', '🎋'],
  ['JUYwJTlGJThEJTgz', '🍃'],
  ['JUYwJTlGJThEJTgy', '🍂'],
  ['JUYwJTlGJThEJTgx', '🍁'],
  ['JUYwJTlGJThEJTg0', '🍄'],
  ['JUYwJTlGJThDJUJF', '🌾'],
  ['JUYwJTlGJTkyJTkw', '💐'],
  ['JUYwJTlGJThDJUI3', '🌷'],
  ['JUYwJTlGJThDJUI5', '🌹'],
  ['JUYwJTlGJUE1JTgw', '🥀'],
  ['JUYwJTlGJThDJUJC', '🌻'],
  ['JUYwJTlGJThDJUJD', '🌼'],
  ['JUYwJTlGJThDJUI4', '🌸'],
  ['JUYwJTlGJThDJUJB', '🌺'],
  ['JUYwJTlGJThDJThF', '🌎'],
  ['JUYwJTlGJThDJThE', '🌍'],
  ['JUYwJTlGJThDJThG', '🌏'],
  ['JUYwJTlGJThDJTk1', '🌕'],
  ['JUYwJTlGJThDJTk2', '🌖'],
  ['JUYwJTlGJThDJTk3', '🌗'],
  ['JUYwJTlGJThDJTk4', '🌘'],
  ['JUYwJTlGJThDJTkx', '🌑'],
  ['JUYwJTlGJThDJTky', '🌒'],
  ['JUYwJTlGJThDJTkz', '🌓'],
  ['JUYwJTlGJThDJTk0', '🌔'],
  ['JUYwJTlGJThDJTlB', '🌚'],
  ['JUYwJTlGJThDJTlE', '🌝'],
  ['JUYwJTlGJThDJTlF', '🌞'],
  ['JUYwJTlGJThDJTlC', '🌛'],
  ['JUYwJTlGJThDJTlD', '🌜'],
  ['JUYwJTlGJThDJTk5', '🌙'],
  ['JUYwJTlGJTkyJUFC', '💫'],
  ['JUUyJUFEJTkwJUVGJUI4JThG', '⭐️'],
  ['JUYwJTlGJThDJTlG', '🌟'],
  ['JUUyJTlDJUE4', '✨'],
  ['JUUyJTlBJUExJUVGJUI4JThG', '⚡️'],
  ['JUYwJTlGJTk0JUE1', '🔥'],
  ['JUYwJTlGJTkyJUE1', '💥'],
  ['JUUyJTk4JTg0', '☄'],
  ['JUUyJTk4JTgwJUVGJUI4JThG', '☀️'],
  ['JUYwJTlGJThDJUE0', '🌤'],
  ['JUUyJTlCJTg1JUVGJUI4JThG', '⛅️'],
  ['JUYwJTlGJThDJUE1', '🌥'],
  ['JUYwJTlGJThDJUE2', '🌦'],
  ['JUYwJTlGJThDJTg4', '🌈'],
  ['JUUyJTk4JTgxJUVGJUI4JThG', '☁️'],
  ['JUYwJTlGJThDJUE3', '🌧'],
  ['JUUyJTlCJTg4', '⛈'],
  ['JUYwJTlGJThDJUE5', '🌩'],
  ['JUYwJTlGJThDJUE4', '🌨'],
  ['JUUyJTk4JTgzJUVGJUI4JThG', '☃️'],
  ['JUUyJTlCJTg0JUVGJUI4JThG', '⛄️'],
  ['JUUyJTlEJTg0JUVGJUI4JThG', '❄️'],
  ['JUYwJTlGJThDJUFD', '🌬'],
  ['JUYwJTlGJTkyJUE4', '💨'],
  ['JUYwJTlGJThDJUFB', '🌪'],
  ['JUYwJTlGJThDJUFC', '🌫'],
  ['JUYwJTlGJThDJThB', '🌊'],
  ['JUYwJTlGJTkyJUE3', '💧'],
  ['JUYwJTlGJTkyJUE2', '💦'],
  ['JUUyJTk4JTk0JUVGJUI4JThG', '☔️'],
  ['JUYwJTlGJThEJThG', '🍏'],
  ['JUYwJTlGJThEJThF', '🍎'],
  ['JUYwJTlGJThEJTkw', '🍐'],
  ['JUYwJTlGJThEJThB', '🍊'],
  ['JUYwJTlGJThEJThC', '🍋'],
  ['JUYwJTlGJThEJThD', '🍌'],
  ['JUYwJTlGJThEJTg5', '🍉'],
  ['JUYwJTlGJThEJTg3', '🍇'],
  ['JUYwJTlGJThEJTkz', '🍓'],
  ['JUYwJTlGJThEJTg4', '🍈'],
  ['JUYwJTlGJThEJTky', '🍒'],
  ['JUYwJTlGJThEJTkx', '🍑'],
  ['JUYwJTlGJThEJThE', '🍍'],
  ['JUYwJTlGJUE1JTlE', '🥝'],
  ['JUYwJTlGJUE1JTkx', '🥑'],
  ['JUYwJTlGJThEJTg1', '🍅'],
  ['JUYwJTlGJThEJTg2', '🍆'],
  ['JUYwJTlGJUE1JTky', '🥒'],
  ['JUYwJTlGJUE1JTk1', '🥕'],
  ['JUYwJTlGJThDJUJE', '🌽'],
  ['JUYwJTlGJThDJUI2', '🌶'],
  ['JUYwJTlGJUE1JTk0', '🥔'],
  ['JUYwJTlGJThEJUEw', '🍠'],
  ['JUYwJTlGJThDJUIw', '🌰'],
  ['JUYwJTlGJUE1JTlD', '🥜'],
  ['JUYwJTlGJThEJUFG', '🍯'],
  ['JUYwJTlGJUE1JTkw', '🥐'],
  ['JUYwJTlGJThEJTlF', '🍞'],
  ['JUYwJTlGJUE1JTk2', '🥖'],
  ['JUYwJTlGJUE3JTgw', '🧀'],
  ['JUYwJTlGJUE1JTlB', '🥚'],
  ['JUYwJTlGJThEJUIz', '🍳'],
  ['JUYwJTlGJUE1JTkz', '🥓'],
  ['JUYwJTlGJUE1JTlF', '🥞'],
  ['JUYwJTlGJThEJUE0', '🍤'],
  ['JUYwJTlGJThEJTk3', '🍗'],
  ['JUYwJTlGJThEJTk2', '🍖'],
  ['JUYwJTlGJThEJTk1', '🍕'],
  ['JUYwJTlGJThDJUFE', '🌭'],
  ['JUYwJTlGJThEJTk0', '🍔'],
  ['JUYwJTlGJThEJTlG', '🍟'],
  ['JUYwJTlGJUE1JTk5', '🥙'],
  ['JUYwJTlGJThDJUFF', '🌮'],
  ['JUYwJTlGJThDJUFG', '🌯'],
  ['JUYwJTlGJUE1JTk3', '🥗'],
  ['JUYwJTlGJUE1JTk4', '🥘'],
  ['JUYwJTlGJThEJTlE', '🍝'],
  ['JUYwJTlGJThEJTlD', '🍜'],
  ['JUYwJTlGJThEJUIy', '🍲'],
  ['JUYwJTlGJThEJUE1', '🍥'],
  ['JUYwJTlGJThEJUEz', '🍣'],
  ['JUYwJTlGJThEJUIx', '🍱'],
  ['JUYwJTlGJThEJTlC', '🍛'],
  ['JUYwJTlGJThEJTlB', '🍚'],
  ['JUYwJTlGJThEJTk5', '🍙'],
  ['JUYwJTlGJThEJTk4', '🍘'],
  ['JUYwJTlGJThEJUEy', '🍢'],
  ['JUYwJTlGJThEJUEx', '🍡'],
  ['JUYwJTlGJThEJUE3', '🍧'],
  ['JUYwJTlGJThEJUE4', '🍨'],
  ['JUYwJTlGJThEJUE2', '🍦'],
  ['JUYwJTlGJThEJUIw', '🍰'],
  ['JUYwJTlGJThFJTgy', '🎂'],
  ['JUYwJTlGJThEJUFF', '🍮'],
  ['JUYwJTlGJThEJUFE', '🍭'],
  ['JUYwJTlGJThEJUFD', '🍬'],
  ['JUYwJTlGJThEJUFC', '🍫'],
  ['JUYwJTlGJThEJUJG', '🍿'],
  ['JUYwJTlGJThEJUE5', '🍩'],
  ['JUYwJTlGJThEJUFB', '🍪'],
  ['JUYwJTlGJUE1JTlC', '🥛'],
  ['JUYwJTlGJThEJUJD', '🍼'],
  ['JUUyJTk4JTk1JUVGJUI4JThG', '☕️'],
  ['JUYwJTlGJThEJUI1', '🍵'],
  ['JUYwJTlGJThEJUI2', '🍶'],
  ['JUYwJTlGJThEJUJB', '🍺'],
  ['JUYwJTlGJThEJUJC', '🍻'],
  ['JUYwJTlGJUE1JTgy', '🥂'],
  ['JUYwJTlGJThEJUI3', '🍷'],
  ['JUYwJTlGJUE1JTgz', '🥃'],
  ['JUYwJTlGJThEJUI4', '🍸'],
  ['JUYwJTlGJThEJUI5', '🍹'],
  ['JUYwJTlGJThEJUJF', '🍾'],
  ['JUYwJTlGJUE1JTg0', '🥄'],
  ['JUYwJTlGJThEJUI0', '🍴'],
  ['JUYwJTlGJThEJUJE', '🍽'],
  ['JUUyJTlBJUJEJUVGJUI4JThG', '⚽️'],
  ['JUYwJTlGJThGJTgw', '🏀'],
  ['JUYwJTlGJThGJTg4', '🏈'],
  ['JUUyJTlBJUJFJUVGJUI4JThG', '⚾️'],
  ['JUYwJTlGJThFJUJF', '🎾'],
  ['JUYwJTlGJThGJTkw', '🏐'],
  ['JUYwJTlGJThGJTg5', '🏉'],
  ['JUYwJTlGJThFJUIx', '🎱'],
  ['JUYwJTlGJThGJTkz', '🏓'],
  ['JUYwJTlGJThGJUI4', '🏸'],
  ['JUYwJTlGJUE1JTg1', '🥅'],
  ['JUYwJTlGJThGJTky', '🏒'],
  ['JUYwJTlGJThGJTkx', '🏑'],
  ['JUYwJTlGJThGJThG', '🏏'],
  ['JUUyJTlCJUIzJUVGJUI4JThG', '⛳️'],
  ['JUYwJTlGJThGJUI5', '🏹'],
  ['JUYwJTlGJThFJUEz', '🎣'],
  ['JUYwJTlGJUE1JThB', '🥊'],
  ['JUYwJTlGJUE1JThC', '🥋'],
  ['JUUyJTlCJUI4', '⛸'],
  ['JUYwJTlGJThFJUJG', '🎿'],
  ['JUUyJTlCJUI3', '⛷'],
  ['JUYwJTlGJThGJTgy', '🏂'],
  ['JUYwJTlGJThGJThCJUVGJUI4JThGJUUyJTgwJThEJUUyJTk5JTgwJUVGJUI4JThG', '🏋️‍♀️'],
  ['JUYwJTlGJThGJThC', '🏋'],
  ['JUYwJTlGJUE0JUJB', '🤺'],
  ['JUYwJTlGJUE0JUJDJUUyJTgwJThEJUUyJTk5JTgw', '🤼‍♀'],
  ['JUYwJTlGJUE0JUJDJUUyJTgwJThEJUUyJTk5JTgy', '🤼‍♂'],
  ['JUYwJTlGJUE0JUI4JUUyJTgwJThEJUUyJTk5JTgw', '🤸‍♀'],
  ['JUYwJTlGJUE0JUI4JUUyJTgwJThEJUUyJTk5JTgy', '🤸‍♂'],
  ['JUUyJTlCJUI5JUVGJUI4JThGJUUyJTgwJThEJUUyJTk5JTgwJUVGJUI4JThG', '⛹️‍♀️'],
  ['JUUyJTlCJUI5', '⛹'],
  ['JUYwJTlGJUE0JUJFJUUyJTgwJThEJUUyJTk5JTgw', '🤾‍♀'],
  ['JUYwJTlGJUE0JUJFJUUyJTgwJThEJUUyJTk5JTgy', '🤾‍♂'],
  ['JUYwJTlGJThGJThDJUVGJUI4JThGJUUyJTgwJThEJUUyJTk5JTgwJUVGJUI4JThG', '🏌️‍♀️'],
  ['JUYwJTlGJThGJThD', '🏌'],
  ['JUYwJTlGJThGJTg0JUUyJTgwJThEJUUyJTk5JTgw', '🏄‍♀'],
  ['JUYwJTlGJThGJTg0', '🏄'],
  ['JUYwJTlGJThGJThBJUUyJTgwJThEJUUyJTk5JTgw', '🏊‍♀'],
  ['JUYwJTlGJThGJThB', '🏊'],
  ['JUYwJTlGJUE0JUJEJUUyJTgwJThEJUUyJTk5JTgw', '🤽‍♀'],
  ['JUYwJTlGJUE0JUJEJUUyJTgwJThEJUUyJTk5JTgy', '🤽‍♂'],
  ['JUYwJTlGJTlBJUEzJUUyJTgwJThEJUUyJTk5JTgw', '🚣‍♀'],
  ['JUYwJTlGJTlBJUEz', '🚣'],
  ['JUYwJTlGJThGJTg3', '🏇'],
  ['JUYwJTlGJTlBJUI0JUUyJTgwJThEJUUyJTk5JTgw', '🚴‍♀'],
  ['JUYwJTlGJTlBJUI0', '🚴'],
  ['JUYwJTlGJTlBJUI1JUUyJTgwJThEJUUyJTk5JTgw', '🚵‍♀'],
  ['JUYwJTlGJTlBJUI1', '🚵'],
  ['JUYwJTlGJThFJUJE', '🎽'],
  ['JUYwJTlGJThGJTg1', '🏅'],
  ['JUYwJTlGJThFJTk2', '🎖'],
  ['JUYwJTlGJUE1JTg3', '🥇'],
  ['JUYwJTlGJUE1JTg4', '🥈'],
  ['JUYwJTlGJUE1JTg5', '🥉'],
  ['JUYwJTlGJThGJTg2', '🏆'],
  ['JUYwJTlGJThGJUI1', '🏵'],
  ['JUYwJTlGJThFJTk3', '🎗'],
  ['JUYwJTlGJThFJUFC', '🎫'],
  ['JUYwJTlGJThFJTlG', '🎟'],
  ['JUYwJTlGJThFJUFB', '🎪'],
  ['JUYwJTlGJUE0JUI5JUUyJTgwJThEJUUyJTk5JTgw', '🤹‍♀'],
  ['JUYwJTlGJUE0JUI5JUUyJTgwJThEJUUyJTk5JTgy', '🤹‍♂'],
  ['JUYwJTlGJThFJUFE', '🎭'],
  ['JUYwJTlGJThFJUE4', '🎨'],
  ['JUYwJTlGJThFJUFD', '🎬'],
  ['JUYwJTlGJThFJUE0', '🎤'],
  ['JUYwJTlGJThFJUE3', '🎧'],
  ['JUYwJTlGJThFJUJD', '🎼'],
  ['JUYwJTlGJThFJUI5', '🎹'],
  ['JUYwJTlGJUE1JTgx', '🥁'],
  ['JUYwJTlGJThFJUI3', '🎷'],
  ['JUYwJTlGJThFJUJB', '🎺'],
  ['JUYwJTlGJThFJUI4', '🎸'],
  ['JUYwJTlGJThFJUJC', '🎻'],
  ['JUYwJTlGJThFJUIy', '🎲'],
  ['JUYwJTlGJThFJUFG', '🎯'],
  ['JUYwJTlGJThFJUIz', '🎳'],
  ['JUYwJTlGJThFJUFF', '🎮'],
  ['JUYwJTlGJThFJUIw', '🎰'],
  ['JUYwJTlGJTlBJTk3', '🚗'],
  ['JUYwJTlGJTlBJTk1', '🚕'],
  ['JUYwJTlGJTlBJTk5', '🚙'],
  ['JUYwJTlGJTlBJThD', '🚌'],
  ['JUYwJTlGJTlBJThF', '🚎'],
  ['JUYwJTlGJThGJThF', '🏎'],
  ['JUYwJTlGJTlBJTkz', '🚓'],
  ['JUYwJTlGJTlBJTkx', '🚑'],
  ['JUYwJTlGJTlBJTky', '🚒'],
  ['JUYwJTlGJTlBJTkw', '🚐'],
  ['JUYwJTlGJTlBJTlB', '🚚'],
  ['JUYwJTlGJTlBJTlC', '🚛'],
  ['JUYwJTlGJTlBJTlD', '🚜'],
  ['JUYwJTlGJTlCJUI0', '🛴'],
  ['JUYwJTlGJTlBJUIy', '🚲'],
  ['JUYwJTlGJTlCJUI1', '🛵'],
  ['JUYwJTlGJThGJThE', '🏍'],
  ['JUYwJTlGJTlBJUE4', '🚨'],
  ['JUYwJTlGJTlBJTk0', '🚔'],
  ['JUYwJTlGJTlBJThE', '🚍'],
  ['JUYwJTlGJTlBJTk4', '🚘'],
  ['JUYwJTlGJTlBJTk2', '🚖'],
  ['JUYwJTlGJTlBJUEx', '🚡'],
  ['JUYwJTlGJTlBJUEw', '🚠'],
  ['JUYwJTlGJTlBJTlG', '🚟'],
  ['JUYwJTlGJTlBJTgz', '🚃'],
  ['JUYwJTlGJTlBJThC', '🚋'],
  ['JUYwJTlGJTlBJTlF', '🚞'],
  ['JUYwJTlGJTlBJTlE', '🚝'],
  ['JUYwJTlGJTlBJTg0', '🚄'],
  ['JUYwJTlGJTlBJTg1', '🚅'],
  ['JUYwJTlGJTlBJTg4', '🚈'],
  ['JUYwJTlGJTlBJTgy', '🚂'],
  ['JUYwJTlGJTlBJTg2', '🚆'],
  ['JUYwJTlGJTlBJTg3', '🚇'],
  ['JUYwJTlGJTlBJThB', '🚊'],
  ['JUYwJTlGJTlBJTg5', '🚉'],
  ['JUYwJTlGJTlBJTgx', '🚁'],
  ['JUYwJTlGJTlCJUE5', '🛩'],
  ['JUUyJTlDJTg4JUVGJUI4JThG', '✈️'],
  ['JUYwJTlGJTlCJUFC', '🛫'],
  ['JUYwJTlGJTlCJUFD', '🛬'],
  ['JUYwJTlGJTlBJTgw', '🚀'],
  ['JUYwJTlGJTlCJUIw', '🛰'],
  ['JUYwJTlGJTkyJUJB', '💺'],
  ['JUYwJTlGJTlCJUI2', '🛶'],
  ['JUUyJTlCJUI1JUVGJUI4JThG', '⛵️'],
  ['JUYwJTlGJTlCJUE1', '🛥'],
  ['JUYwJTlGJTlBJUE0', '🚤'],
  ['JUYwJTlGJTlCJUIz', '🛳'],
  ['JUUyJTlCJUI0', '⛴'],
  ['JUYwJTlGJTlBJUEy', '🚢'],
  ['JUUyJTlBJTkzJUVGJUI4JThG', '⚓️'],
  ['JUYwJTlGJTlBJUE3', '🚧'],
  ['JUUyJTlCJUJEJUVGJUI4JThG', '⛽️'],
  ['JUYwJTlGJTlBJThG', '🚏'],
  ['JUYwJTlGJTlBJUE2', '🚦'],
  ['JUYwJTlGJTlBJUE1', '🚥'],
  ['JUYwJTlGJTk3JUJB', '🗺'],
  ['JUYwJTlGJTk3JUJG', '🗿'],
  ['JUYwJTlGJTk3JUJE', '🗽'],
  ['JUUyJTlCJUIyJUVGJUI4JThG', '⛲️'],
  ['JUYwJTlGJTk3JUJD', '🗼'],
  ['JUYwJTlGJThGJUIw', '🏰'],
  ['JUYwJTlGJThGJUFG', '🏯'],
  ['JUYwJTlGJThGJTlG', '🏟'],
  ['JUYwJTlGJThFJUEx', '🎡'],
  ['JUYwJTlGJThFJUEy', '🎢'],
  ['JUYwJTlGJThFJUEw', '🎠'],
  ['JUUyJTlCJUIx', '⛱'],
  ['JUYwJTlGJThGJTk2', '🏖'],
  ['JUYwJTlGJThGJTlE', '🏝'],
  ['JUUyJTlCJUIw', '⛰'],
  ['JUYwJTlGJThGJTk0', '🏔'],
  ['JUYwJTlGJTk3JUJC', '🗻'],
  ['JUYwJTlGJThDJThC', '🌋'],
  ['JUYwJTlGJThGJTlD', '🏜'],
  ['JUYwJTlGJThGJTk1', '🏕'],
  ['JUUyJTlCJUJBJUVGJUI4JThG', '⛺️'],
  ['JUYwJTlGJTlCJUE0', '🛤'],
  ['JUYwJTlGJTlCJUEz', '🛣'],
  ['JUYwJTlGJThGJTk3', '🏗'],
  ['JUYwJTlGJThGJUFE', '🏭'],
  ['JUYwJTlGJThGJUEw', '🏠'],
  ['JUYwJTlGJThGJUEx', '🏡'],
  ['JUYwJTlGJThGJTk4', '🏘'],
  ['JUYwJTlGJThGJTlB', '🏚'],
  ['JUYwJTlGJThGJUEy', '🏢'],
  ['JUYwJTlGJThGJUFD', '🏬'],
  ['JUYwJTlGJThGJUEz', '🏣'],
  ['JUYwJTlGJThGJUE0', '🏤'],
  ['JUYwJTlGJThGJUE1', '🏥'],
  ['JUYwJTlGJThGJUE2', '🏦'],
  ['JUYwJTlGJThGJUE4', '🏨'],
  ['JUYwJTlGJThGJUFB', '🏪'],
  ['JUYwJTlGJThGJUFC', '🏫'],
  ['JUYwJTlGJThGJUE5', '🏩'],
  ['JUYwJTlGJTkyJTky', '💒'],
  ['JUYwJTlGJThGJTlC', '🏛'],
  ['JUUyJTlCJUFBJUVGJUI4JThG', '⛪️'],
  ['JUYwJTlGJTk1JThD', '🕌'],
  ['JUYwJTlGJTk1JThE', '🕍'],
  ['JUYwJTlGJTk1JThC', '🕋'],
  ['JUUyJTlCJUE5', '⛩'],
  ['JUYwJTlGJTk3JUJF', '🗾'],
  ['JUYwJTlGJThFJTkx', '🎑'],
  ['JUYwJTlGJThGJTlF', '🏞'],
  ['JUYwJTlGJThDJTg1', '🌅'],
  ['JUYwJTlGJThDJTg0', '🌄'],
  ['JUYwJTlGJThDJUEw', '🌠'],
  ['JUYwJTlGJThFJTg3', '🎇'],
  ['JUYwJTlGJThFJTg2', '🎆'],
  ['JUYwJTlGJThDJTg3', '🌇'],
  ['JUYwJTlGJThDJTg2', '🌆'],
  ['JUYwJTlGJThGJTk5', '🏙'],
  ['JUYwJTlGJThDJTgz', '🌃'],
  ['JUYwJTlGJThDJThD', '🌌'],
  ['JUYwJTlGJThDJTg5', '🌉'],
  ['JUYwJTlGJThDJTgx', '🌁'],
  ['JUUyJThDJTlBJUVGJUI4JThG', '⌚️'],
  ['JUYwJTlGJTkzJUIx', '📱'],
  ['JUYwJTlGJTkzJUIy', '📲'],
  ['JUYwJTlGJTkyJUJC', '💻'],
  ['JUUyJThDJUE4JUVGJUI4JThG', '⌨️'],
  ['JUYwJTlGJTk2JUE1', '🖥'],
  ['JUYwJTlGJTk2JUE4', '🖨'],
  ['JUYwJTlGJTk2JUIx', '🖱'],
  ['JUYwJTlGJTk2JUIy', '🖲'],
  ['JUYwJTlGJTk1JUI5', '🕹'],
  ['JUYwJTlGJTk3JTlD', '🗜'],
  ['JUYwJTlGJTkyJUJE', '💽'],
  ['JUYwJTlGJTkyJUJF', '💾'],
  ['JUYwJTlGJTkyJUJG', '💿'],
  ['JUYwJTlGJTkzJTgw', '📀'],
  ['JUYwJTlGJTkzJUJD', '📼'],
  ['JUYwJTlGJTkzJUI3', '📷'],
  ['JUYwJTlGJTkzJUI4', '📸'],
  ['JUYwJTlGJTkzJUI5', '📹'],
  ['JUYwJTlGJThFJUE1', '🎥'],
  ['JUYwJTlGJTkzJUJE', '📽'],
  ['JUYwJTlGJThFJTlF', '🎞'],
  ['JUYwJTlGJTkzJTlF', '📞'],
  ['JUUyJTk4JThFJUVGJUI4JThG', '☎️'],
  ['JUYwJTlGJTkzJTlG', '📟'],
  ['JUYwJTlGJTkzJUEw', '📠'],
  ['JUYwJTlGJTkzJUJB', '📺'],
  ['JUYwJTlGJTkzJUJC', '📻'],
  ['JUYwJTlGJThFJTk5', '🎙'],
  ['JUYwJTlGJThFJTlB', '🎚'],
  ['JUYwJTlGJThFJTlC', '🎛'],
  ['JUUyJThGJUIx', '⏱'],
  ['JUUyJThGJUIy', '⏲'],
  ['JUUyJThGJUIw', '⏰'],
  ['JUYwJTlGJTk1JUIw', '🕰'],
  ['JUUyJThDJTlCJUVGJUI4JThG', '⌛️'],
  ['JUUyJThGJUIz', '⏳'],
  ['JUYwJTlGJTkzJUEx', '📡'],
  ['JUYwJTlGJTk0JThC', '🔋'],
  ['JUYwJTlGJTk0JThD', '🔌'],
  ['JUYwJTlGJTkyJUEx', '💡'],
  ['JUYwJTlGJTk0JUE2', '🔦'],
  ['JUYwJTlGJTk1JUFG', '🕯'],
  ['JUYwJTlGJTk3JTkx', '🗑'],
  ['JUYwJTlGJTlCJUEy', '🛢'],
  ['JUYwJTlGJTkyJUI4', '💸'],
  ['JUYwJTlGJTkyJUI1', '💵'],
  ['JUYwJTlGJTkyJUI0', '💴'],
  ['JUYwJTlGJTkyJUI2', '💶'],
  ['JUYwJTlGJTkyJUI3', '💷'],
  ['JUYwJTlGJTkyJUIw', '💰'],
  ['JUYwJTlGJTkyJUIz', '💳'],
  ['JUYwJTlGJTkyJThF', '💎'],
  ['JUUyJTlBJTk2JUVGJUI4JThG', '⚖️'],
  ['JUYwJTlGJTk0JUE3', '🔧'],
  ['JUYwJTlGJTk0JUE4', '🔨'],
  ['JUUyJTlBJTky', '⚒'],
  ['JUYwJTlGJTlCJUEw', '🛠'],
  ['JUUyJTlCJThG', '⛏'],
  ['JUYwJTlGJTk0JUE5', '🔩'],
  ['JUUyJTlBJTk5JUVGJUI4JThG', '⚙️'],
  ['JUUyJTlCJTkz', '⛓'],
  ['JUYwJTlGJTk0JUFC', '🔫'],
  ['JUYwJTlGJTkyJUEz', '💣'],
  ['JUYwJTlGJTk0JUFB', '🔪'],
  ['JUYwJTlGJTk3JUEx', '🗡'],
  ['JUUyJTlBJTk0JUVGJUI4JThG', '⚔️'],
  ['JUYwJTlGJTlCJUEx', '🛡'],
  ['JUYwJTlGJTlBJUFD', '🚬'],
  ['JUUyJTlBJUIwJUVGJUI4JThG', '⚰️'],
  ['JUUyJTlBJUIxJUVGJUI4JThG', '⚱️'],
  ['JUYwJTlGJThGJUJB', '🏺'],
  ['JUYwJTlGJTk0JUFF', '🔮'],
  ['JUYwJTlGJTkzJUJG', '📿'],
  ['JUYwJTlGJTkyJTg4', '💈'],
  ['JUUyJTlBJTk3JUVGJUI4JThG', '⚗️'],
  ['JUYwJTlGJTk0JUFE', '🔭'],
  ['JUYwJTlGJTk0JUFD', '🔬'],
  ['JUYwJTlGJTk1JUIz', '🕳'],
  ['JUYwJTlGJTkyJThB', '💊'],
  ['JUYwJTlGJTkyJTg5', '💉'],
  ['JUYwJTlGJThDJUEx', '🌡'],
  ['JUYwJTlGJTlBJUJE', '🚽'],
  ['JUYwJTlGJTlBJUIw', '🚰'],
  ['JUYwJTlGJTlBJUJG', '🚿'],
  ['JUYwJTlGJTlCJTgx', '🛁'],
  ['JUYwJTlGJTlCJTgw', '🛀'],
  ['JUYwJTlGJTlCJThF', '🛎'],
  ['JUYwJTlGJTk0JTkx', '🔑'],
  ['JUYwJTlGJTk3JTlE', '🗝'],
  ['JUYwJTlGJTlBJUFB', '🚪'],
  ['JUYwJTlGJTlCJThC', '🛋'],
  ['JUYwJTlGJTlCJThG', '🛏'],
  ['JUYwJTlGJTlCJThD', '🛌'],
  ['JUYwJTlGJTk2JUJD', '🖼'],
  ['JUYwJTlGJTlCJThE', '🛍'],
  ['JUYwJTlGJTlCJTky', '🛒'],
  ['JUYwJTlGJThFJTgx', '🎁'],
  ['JUYwJTlGJThFJTg4', '🎈'],
  ['JUYwJTlGJThFJThG', '🎏'],
  ['JUYwJTlGJThFJTgw', '🎀'],
  ['JUYwJTlGJThFJThB', '🎊'],
  ['JUYwJTlGJThFJTg5', '🎉'],
  ['JUYwJTlGJThFJThF', '🎎'],
  ['JUYwJTlGJThGJUFF', '🏮'],
  ['JUYwJTlGJThFJTkw', '🎐'],
  ['JUUyJTlDJTg5JUVGJUI4JThG', '✉️'],
  ['JUYwJTlGJTkzJUE5', '📩'],
  ['JUYwJTlGJTkzJUE4', '📨'],
  ['JUYwJTlGJTkzJUE3', '📧'],
  ['JUYwJTlGJTkyJThD', '💌'],
  ['JUYwJTlGJTkzJUE1', '📥'],
  ['JUYwJTlGJTkzJUE0', '📤'],
  ['JUYwJTlGJTkzJUE2', '📦'],
  ['JUYwJTlGJThGJUI3', '🏷'],
  ['JUYwJTlGJTkzJUFB', '📪'],
  ['JUYwJTlGJTkzJUFC', '📫'],
  ['JUYwJTlGJTkzJUFD', '📬'],
  ['JUYwJTlGJTkzJUFE', '📭'],
  ['JUYwJTlGJTkzJUFF', '📮'],
  ['JUYwJTlGJTkzJUFG', '📯'],
  ['JUYwJTlGJTkzJTlD', '📜'],
  ['JUYwJTlGJTkzJTgz', '📃'],
  ['JUYwJTlGJTkzJTg0', '📄'],
  ['JUYwJTlGJTkzJTkx', '📑'],
  ['JUYwJTlGJTkzJThB', '📊'],
  ['JUYwJTlGJTkzJTg4', '📈'],
  ['JUYwJTlGJTkzJTg5', '📉'],
  ['JUYwJTlGJTk3JTky', '🗒'],
  ['JUYwJTlGJTk3JTkz', '🗓'],
  ['JUYwJTlGJTkzJTg2', '📆'],
  ['JUYwJTlGJTkzJTg1', '📅'],
  ['JUYwJTlGJTkzJTg3', '📇'],
  ['JUYwJTlGJTk3JTgz', '🗃'],
  ['JUYwJTlGJTk3JUIz', '🗳'],
  ['JUYwJTlGJTk3JTg0', '🗄'],
  ['JUYwJTlGJTkzJThC', '📋'],
  ['JUYwJTlGJTkzJTgx', '📁'],
  ['JUYwJTlGJTkzJTgy', '📂'],
  ['JUYwJTlGJTk3JTgy', '🗂'],
  ['JUYwJTlGJTk3JTlF', '🗞'],
  ['JUYwJTlGJTkzJUIw', '📰'],
  ['JUYwJTlGJTkzJTkz', '📓'],
  ['JUYwJTlGJTkzJTk0', '📔'],
  ['JUYwJTlGJTkzJTky', '📒'],
  ['JUYwJTlGJTkzJTk1', '📕'],
  ['JUYwJTlGJTkzJTk3', '📗'],
  ['JUYwJTlGJTkzJTk4', '📘'],
  ['JUYwJTlGJTkzJTk5', '📙'],
  ['JUYwJTlGJTkzJTlB', '📚'],
  ['JUYwJTlGJTkzJTk2', '📖'],
  ['JUYwJTlGJTk0JTk2', '🔖'],
  ['JUYwJTlGJTk0JTk3', '🔗'],
  ['JUYwJTlGJTkzJThF', '📎'],
  ['JUYwJTlGJTk2JTg3', '🖇'],
  ['JUYwJTlGJTkzJTkw', '📐'],
  ['JUYwJTlGJTkzJThG', '📏'],
  ['JUYwJTlGJTkzJThD', '📌'],
  ['JUYwJTlGJTkzJThE', '📍'],
  ['JUUyJTlDJTgyJUVGJUI4JThG', '✂️'],
  ['JUYwJTlGJTk2JThB', '🖊'],
  ['JUYwJTlGJTk2JThC', '🖋'],
  ['JUUyJTlDJTkyJUVGJUI4JThG', '✒️'],
  ['JUYwJTlGJTk2JThD', '🖌'],
  ['JUYwJTlGJTk2JThE', '🖍'],
  ['JUYwJTlGJTkzJTlE', '📝'],
  ['JUUyJTlDJThGJUVGJUI4JThG', '✏️'],
  ['JUYwJTlGJTk0JThE', '🔍'],
  ['JUYwJTlGJTk0JThF', '🔎'],
  ['JUYwJTlGJTk0JThG', '🔏'],
  ['JUYwJTlGJTk0JTkw', '🔐'],
  ['JUYwJTlGJTk0JTky', '🔒'],
  ['JUYwJTlGJTk0JTkz', '🔓'],
  ['JUUyJTlEJUE0JUVGJUI4JThG', '❤️'],
  ['JUYwJTlGJTkyJTlC', '💛'],
  ['JUYwJTlGJTkyJTlB', '💚'],
  ['JUYwJTlGJTkyJTk5', '💙'],
  ['JUYwJTlGJTkyJTlD', '💜'],
  ['JUYwJTlGJTk2JUE0', '🖤'],
  ['JUYwJTlGJTkyJTk0', '💔'],
  ['JUUyJTlEJUEzJUVGJUI4JThG', '❣️'],
  ['JUYwJTlGJTkyJTk1', '💕'],
  ['JUYwJTlGJTkyJTlF', '💞'],
  ['JUYwJTlGJTkyJTkz', '💓'],
  ['JUYwJTlGJTkyJTk3', '💗'],
  ['JUYwJTlGJTkyJTk2', '💖'],
  ['JUYwJTlGJTkyJTk4', '💘'],
  ['JUYwJTlGJTkyJTlE', '💝'],
  ['JUYwJTlGJTkyJTlG', '💟'],
  ['JUUyJTk4JUFFJUVGJUI4JThG', '☮️'],
  ['JUUyJTlDJTlEJUVGJUI4JThG', '✝️'],
  ['JUUyJTk4JUFBJUVGJUI4JThG', '☪️'],
  ['JUYwJTlGJTk1JTg5', '🕉'],
  ['JUUyJTk4JUI4JUVGJUI4JThG', '☸️'],
  ['JUUyJTlDJUExJUVGJUI4JThG', '✡️'],
  ['JUYwJTlGJTk0JUFG', '🔯'],
  ['JUYwJTlGJTk1JThF', '🕎'],
  ['JUUyJTk4JUFGJUVGJUI4JThG', '☯️'],
  ['JUUyJTk4JUE2JUVGJUI4JThG', '☦️'],
  ['JUYwJTlGJTlCJTkw', '🛐'],
  ['JUUyJTlCJThF', '⛎'],
  ['JUUyJTk5JTg4JUVGJUI4JThG', '♈️'],
  ['JUUyJTk5JTg5JUVGJUI4JThG', '♉️'],
  ['JUUyJTk5JThBJUVGJUI4JThG', '♊️'],
  ['JUUyJTk5JThCJUVGJUI4JThG', '♋️'],
  ['JUUyJTk5JThDJUVGJUI4JThG', '♌️'],
  ['JUUyJTk5JThEJUVGJUI4JThG', '♍️'],
  ['JUUyJTk5JThFJUVGJUI4JThG', '♎️'],
  ['JUUyJTk5JThGJUVGJUI4JThG', '♏️'],
  ['JUUyJTk5JTkwJUVGJUI4JThG', '♐️'],
  ['JUUyJTk5JTkxJUVGJUI4JThG', '♑️'],
  ['JUUyJTk5JTkyJUVGJUI4JThG', '♒️'],
  ['JUUyJTk5JTkzJUVGJUI4JThG', '♓️'],
  ['JUYwJTlGJTg2JTk0', '🆔'],
  ['JUUyJTlBJTlCJUVGJUI4JThG', '⚛️'],
  ['JUYwJTlGJTg5JTkx', '🉑'],
  ['JUUyJTk4JUEyJUVGJUI4JThG', '☢️'],
  ['JUUyJTk4JUEzJUVGJUI4JThG', '☣️'],
  ['JUYwJTlGJTkzJUI0', '📴'],
  ['JUYwJTlGJTkzJUIz', '📳'],
  ['JUYwJTlGJTg4JUI2', '🈶'],
  ['JUYwJTlGJTg4JTlBJUVGJUI4JThG', '🈚️'],
  ['JUYwJTlGJTg4JUI4', '🈸'],
  ['JUYwJTlGJTg4JUJB', '🈺'],
  ['JUYwJTlGJTg4JUI3JUVGJUI4JThG', '🈷️'],
  ['JUUyJTlDJUI0JUVGJUI4JThG', '✴️'],
  ['JUYwJTlGJTg2JTlB', '🆚'],
  ['JUYwJTlGJTkyJUFF', '💮'],
  ['JUYwJTlGJTg5JTkw', '🉐'],
  ['JUUzJThBJTk5JUVGJUI4JThG', '㊙️'],
  ['JUUzJThBJTk3JUVGJUI4JThG', '㊗️'],
  ['JUYwJTlGJTg4JUI0', '🈴'],
  ['JUYwJTlGJTg4JUI1', '🈵'],
  ['JUYwJTlGJTg4JUI5', '🈹'],
  ['JUYwJTlGJTg4JUIy', '🈲'],
  ['JUYwJTlGJTg1JUIwJUVGJUI4JThG', '🅰️'],
  ['JUYwJTlGJTg1JUIxJUVGJUI4JThG', '🅱️'],
  ['JUYwJTlGJTg2JThF', '🆎'],
  ['JUYwJTlGJTg2JTkx', '🆑'],
  ['JUYwJTlGJTg1JUJFJUVGJUI4JThG', '🅾️'],
  ['JUYwJTlGJTg2JTk4', '🆘'],
  ['JUUyJTlEJThD', '❌'],
  ['JUUyJUFEJTk1JUVGJUI4JThG', '⭕️'],
  ['JUYwJTlGJTlCJTkx', '🛑'],
  ['JUUyJTlCJTk0JUVGJUI4JThG', '⛔️'],
  ['JUYwJTlGJTkzJTlC', '📛'],
  ['JUYwJTlGJTlBJUFC', '🚫'],
  ['JUYwJTlGJTkyJUFG', '💯'],
  ['JUYwJTlGJTkyJUEy', '💢'],
  ['JUUyJTk5JUE4JUVGJUI4JThG', '♨️'],
  ['JUYwJTlGJTlBJUI3', '🚷'],
  ['JUYwJTlGJTlBJUFG', '🚯'],
  ['JUYwJTlGJTlBJUIz', '🚳'],
  ['JUYwJTlGJTlBJUIx', '🚱'],
  ['JUYwJTlGJTk0JTlF', '🔞'],
  ['JUYwJTlGJTkzJUI1', '📵'],
  ['JUYwJTlGJTlBJUFE', '🚭'],
  ['JUUyJTlEJTk3JUVGJUI4JThG', '❗️'],
  ['JUUyJTlEJTk1', '❕'],
  ['JUUyJTlEJTkz', '❓'],
  ['JUUyJTlEJTk0', '❔'],
  ['JUUyJTgwJUJDJUVGJUI4JThG', '‼️'],
  ['JUUyJTgxJTg5JUVGJUI4JThG', '⁉️'],
  ['JUYwJTlGJTk0JTg1', '🔅'],
  ['JUYwJTlGJTk0JTg2', '🔆'],
  ['JUUzJTgwJUJEJUVGJUI4JThG', '〽️'],
  ['JUUyJTlBJUEwJUVGJUI4JThG', '⚠️'],
  ['JUYwJTlGJTlBJUI4', '🚸'],
  ['JUYwJTlGJTk0JUIx', '🔱'],
  ['JUUyJTlBJTlDJUVGJUI4JThG', '⚜️'],
  ['JUYwJTlGJTk0JUIw', '🔰'],
  ['JUUyJTk5JUJCJUVGJUI4JThG', '♻️'],
  ['JUUyJTlDJTg1', '✅'],
  ['JUYwJTlGJTg4JUFGJUVGJUI4JThG', '🈯️'],
  ['JUYwJTlGJTkyJUI5', '💹'],
  ['JUUyJTlEJTg3JUVGJUI4JThG', '❇️'],
  ['JUUyJTlDJUIzJUVGJUI4JThG', '✳️'],
  ['JUUyJTlEJThF', '❎'],
  ['JUYwJTlGJThDJTkw', '🌐'],
  ['JUYwJTlGJTkyJUEw', '💠'],
  ['JUUyJTkzJTgyJUVGJUI4JThG', 'Ⓜ️'],
  ['JUYwJTlGJThDJTgw', '🌀'],
  ['JUYwJTlGJTkyJUE0', '💤'],
  ['JUYwJTlGJThGJUE3', '🏧'],
  ['JUYwJTlGJTlBJUJF', '🚾'],
  ['JUUyJTk5JUJGJUVGJUI4JThG', '♿️'],
  ['JUYwJTlGJTg1JUJGJUVGJUI4JThG', '🅿️'],
  ['JUYwJTlGJTg4JUIz', '🈳'],
  ['JUYwJTlGJTg4JTgyJUVGJUI4JThG', '🈂️'],
  ['JUYwJTlGJTlCJTgy', '🛂'],
  ['JUYwJTlGJTlCJTgz', '🛃'],
  ['JUYwJTlGJTlCJTg0', '🛄'],
  ['JUYwJTlGJTlCJTg1', '🛅'],
  ['JUYwJTlGJTlBJUI5', '🚹'],
  ['JUYwJTlGJTlBJUJB', '🚺'],
  ['JUYwJTlGJTlBJUJD', '🚼'],
  ['JUYwJTlGJTlBJUJC', '🚻'],
  ['JUYwJTlGJTlBJUFF', '🚮'],
  ['JUYwJTlGJThFJUE2', '🎦'],
  ['JUYwJTlGJTkzJUI2', '📶'],
  ['JUYwJTlGJTg4JTgx', '🈁'],
  ['JUYwJTlGJTk0JUEz', '🔣'],
  ['JUUyJTg0JUI5JUVGJUI4JThG', 'ℹ️'],
  ['JUYwJTlGJTk0JUE0', '🔤'],
  ['JUYwJTlGJTk0JUEx', '🔡'],
  ['JUYwJTlGJTk0JUEw', '🔠'],
  ['JUYwJTlGJTg2JTk2', '🆖'],
  ['JUYwJTlGJTg2JTk3', '🆗'],
  ['JUYwJTlGJTg2JTk5', '🆙'],
  ['JUYwJTlGJTg2JTky', '🆒'],
  ['JUYwJTlGJTg2JTk1', '🆕'],
  ['JUYwJTlGJTg2JTkz', '🆓'],
  ['MCVFRiVCOCU4RiVFMiU4MyVBMw==', '0️⃣'],
  ['MSVFRiVCOCU4RiVFMiU4MyVBMw==', '1️⃣'],
  ['MiVFRiVCOCU4RiVFMiU4MyVBMw==', '2️⃣'],
  ['MyVFRiVCOCU4RiVFMiU4MyVBMw==', '3️⃣'],
  ['NCVFRiVCOCU4RiVFMiU4MyVBMw==', '4️⃣'],
  ['NSVFRiVCOCU4RiVFMiU4MyVBMw==', '5️⃣'],
  ['NiVFRiVCOCU4RiVFMiU4MyVBMw==', '6️⃣'],
  ['NyVFRiVCOCU4RiVFMiU4MyVBMw==', '7️⃣'],
  ['OCVFRiVCOCU4RiVFMiU4MyVBMw==', '8️⃣'],
  ['OSVFRiVCOCU4RiVFMiU4MyVBMw==', '9️⃣'],
  ['JUYwJTlGJTk0JTlG', '🔟'],
  ['JUYwJTlGJTk0JUEy', '🔢'],
  ['JTIzJUVGJUI4JThGJUUyJTgzJUEz', '#️⃣'],
  ['KiVFRiVCOCU4RiVFMiU4MyVBMw==', '*️⃣'],
  ['JUUyJTk2JUI2JUVGJUI4JThG', '▶️'],
  ['JUUyJThGJUI4', '⏸'],
  ['JUUyJThGJUFG', '⏯'],
  ['JUUyJThGJUI5', '⏹'],
  ['JUUyJThGJUJB', '⏺'],
  ['JUUyJThGJUFE', '⏭'],
  ['JUUyJThGJUFF', '⏮'],
  ['JUUyJThGJUE5', '⏩'],
  ['JUUyJThGJUFB', '⏪'],
  ['JUUyJThGJUFC', '⏫'],
  ['JUUyJThGJUFD', '⏬'],
  ['JUUyJTk3JTgwJUVGJUI4JThG', '◀️'],
  ['JUYwJTlGJTk0JUJD', '🔼'],
  ['JUYwJTlGJTk0JUJE', '🔽'],
  ['JUUyJTlFJUExJUVGJUI4JThG', '➡️'],
  ['JUUyJUFDJTg1JUVGJUI4JThG', '⬅️'],
  ['JUUyJUFDJTg2JUVGJUI4JThG', '⬆️'],
  ['JUUyJUFDJTg3JUVGJUI4JThG', '⬇️'],
  ['JUUyJTg2JTk3JUVGJUI4JThG', '↗️'],
  ['JUUyJTg2JTk4JUVGJUI4JThG', '↘️'],
  ['JUUyJTg2JTk5JUVGJUI4JThG', '↙️'],
  ['JUUyJTg2JTk2JUVGJUI4JThG', '↖️'],
  ['JUUyJTg2JTk1JUVGJUI4JThG', '↕️'],
  ['JUUyJTg2JTk0JUVGJUI4JThG', '↔️'],
  ['JUUyJTg2JUFBJUVGJUI4JThG', '↪️'],
  ['JUUyJTg2JUE5JUVGJUI4JThG', '↩️'],
  ['JUUyJUE0JUI0JUVGJUI4JThG', '⤴️'],
  ['JUUyJUE0JUI1JUVGJUI4JThG', '⤵️'],
  ['JUYwJTlGJTk0JTgw', '🔀'],
  ['JUYwJTlGJTk0JTgx', '🔁'],
  ['JUYwJTlGJTk0JTgy', '🔂'],
  ['JUYwJTlGJTk0JTg0', '🔄'],
  ['JUYwJTlGJTk0JTgz', '🔃'],
  ['JUYwJTlGJThFJUI1', '🎵'],
  ['JUYwJTlGJThFJUI2', '🎶'],
  ['JUUyJTlFJTk1', '➕'],
  ['JUUyJTlFJTk2', '➖'],
  ['JUUyJTlFJTk3', '➗'],
  ['JUUyJTlDJTk2JUVGJUI4JThG', '✖️'],
  ['JUYwJTlGJTkyJUIy', '💲'],
  ['JUYwJTlGJTkyJUIx', '💱'],
  ['JUUyJTg0JUEyJUVGJUI4JThG', '™️'],
  ['JUMyJUE5JUVGJUI4JThG', '©️'],
  ['JUMyJUFFJUVGJUI4JThG', '®️'],
  ['JUUzJTgwJUIwJUVGJUI4JThG', '〰️'],
  ['JUUyJTlFJUIw', '➰'],
  ['JUUyJTlFJUJG', '➿'],
  ['JUYwJTlGJTk0JTlB', '🔚'],
  ['JUYwJTlGJTk0JTk5', '🔙'],
  ['JUYwJTlGJTk0JTlC', '🔛'],
  ['JUYwJTlGJTk0JTlE', '🔝'],
  ['JUYwJTlGJTk0JTlD', '🔜'],
  ['JUUyJTlDJTk0JUVGJUI4JThG', '✔️'],
  ['JUUyJTk4JTkxJUVGJUI4JThG', '☑️'],
  ['JUYwJTlGJTk0JTk4', '🔘'],
  ['JUUyJTlBJUFBJUVGJUI4JThG', '⚪️'],
  ['JUUyJTlBJUFCJUVGJUI4JThG', '⚫️'],
  ['JUYwJTlGJTk0JUI0', '🔴'],
  ['JUYwJTlGJTk0JUI1', '🔵'],
  ['JUYwJTlGJTk0JUJB', '🔺'],
  ['JUYwJTlGJTk0JUJC', '🔻'],
  ['JUYwJTlGJTk0JUI4', '🔸'],
  ['JUYwJTlGJTk0JUI5', '🔹'],
  ['JUYwJTlGJTk0JUI2', '🔶'],
  ['JUYwJTlGJTk0JUI3', '🔷'],
  ['JUYwJTlGJTk0JUIz', '🔳'],
  ['JUYwJTlGJTk0JUIy', '🔲'],
  ['JUUyJTk2JUFBJUVGJUI4JThG', '▪️'],
  ['JUUyJTk2JUFCJUVGJUI4JThG', '▫️'],
  ['JUUyJTk3JUJFJUVGJUI4JThG', '◾️'],
  ['JUUyJTk3JUJEJUVGJUI4JThG', '◽️'],
  ['JUUyJTk3JUJDJUVGJUI4JThG', '◼️'],
  ['JUUyJTk3JUJCJUVGJUI4JThG', '◻️'],
  ['JUUyJUFDJTlCJUVGJUI4JThG', '⬛️'],
  ['JUUyJUFDJTlDJUVGJUI4JThG', '⬜️'],
  ['JUYwJTlGJTk0JTg4', '🔈'],
  ['JUYwJTlGJTk0JTg3', '🔇'],
  ['JUYwJTlGJTk0JTg5', '🔉'],
  ['JUYwJTlGJTk0JThB', '🔊'],
  ['JUYwJTlGJTk0JTk0', '🔔'],
  ['JUYwJTlGJTk0JTk1', '🔕'],
  ['JUYwJTlGJTkzJUEz', '📣'],
  ['JUYwJTlGJTkzJUEy', '📢'],
  ['JUYwJTlGJTkxJTgxJUUyJTgwJThEJUYwJTlGJTk3JUE4', '👁‍🗨'],
  ['JUYwJTlGJTkyJUFD', '💬'],
  ['JUYwJTlGJTkyJUFE', '💭'],
  ['JUYwJTlGJTk3JUFG', '🗯'],
  ['JUUyJTk5JUEwJUVGJUI4JThG', '♠️'],
  ['JUUyJTk5JUEzJUVGJUI4JThG', '♣️'],
  ['JUUyJTk5JUE1JUVGJUI4JThG', '♥️'],
  ['JUUyJTk5JUE2JUVGJUI4JThG', '♦️'],
  ['JUYwJTlGJTgzJThG', '🃏'],
  ['JUYwJTlGJThFJUI0', '🎴'],
  ['JUYwJTlGJTgwJTg0JUVGJUI4JThG', '🀄️'],
  ['JUYwJTlGJTk1JTkw', '🕐'],
  ['JUYwJTlGJTk1JTkx', '🕑'],
  ['JUYwJTlGJTk1JTky', '🕒'],
  ['JUYwJTlGJTk1JTkz', '🕓'],
  ['JUYwJTlGJTk1JTk0', '🕔'],
  ['JUYwJTlGJTk1JTk1', '🕕'],
  ['JUYwJTlGJTk1JTk2', '🕖'],
  ['JUYwJTlGJTk1JTk3', '🕗'],
  ['JUYwJTlGJTk1JTk4', '🕘'],
  ['JUYwJTlGJTk1JTk5', '🕙'],
  ['JUYwJTlGJTk1JTlB', '🕚'],
  ['JUYwJTlGJTk1JTlC', '🕛'],
  ['JUYwJTlGJTk1JTlD', '🕜'],
  ['JUYwJTlGJTk1JTlE', '🕝'],
  ['JUYwJTlGJTk1JTlF', '🕞'],
  ['JUYwJTlGJTk1JTlG', '🕟'],
  ['JUYwJTlGJTk1JUEw', '🕠'],
  ['JUYwJTlGJTk1JUEx', '🕡'],
  ['JUYwJTlGJTk1JUEy', '🕢'],
  ['JUYwJTlGJTk1JUEz', '🕣'],
  ['JUYwJTlGJTk1JUE0', '🕤'],
  ['JUYwJTlGJTk1JUE1', '🕥'],
  ['JUYwJTlGJTk1JUE2', '🕦'],
  ['JUYwJTlGJTk1JUE3', '🕧'],
  ['JUYwJTlGJThGJUIzJUVGJUI4JThG', '🏳️'],
  ['JUYwJTlGJThGJUI0', '🏴'],
  ['JUYwJTlGJThGJTgx', '🏁'],
  ['JUYwJTlGJTlBJUE5', '🚩'],
  ['JUYwJTlGJThGJUIzJUVGJUI4JThGJUUyJTgwJThEJUYwJTlGJThDJTg4', '🏳️‍🌈'],
  ['JUYwJTlGJTg3JUE2JUYwJTlGJTg3JUFC', '🇦🇫'],
  ['JUYwJTlGJTg3JUE2JUYwJTlGJTg3JUJE', '🇦🇽'],
  ['JUYwJTlGJTg3JUE2JUYwJTlGJTg3JUIx', '🇦🇱'],
  ['JUYwJTlGJTg3JUE5JUYwJTlGJTg3JUJG', '🇩🇿'],
  ['JUYwJTlGJTg3JUE2JUYwJTlGJTg3JUI4', '🇦🇸'],
  ['JUYwJTlGJTg3JUE2JUYwJTlGJTg3JUE5', '🇦🇩'],
  ['JUYwJTlGJTg3JUE2JUYwJTlGJTg3JUI0', '🇦🇴'],
  ['JUYwJTlGJTg3JUE2JUYwJTlGJTg3JUFF', '🇦🇮'],
  ['JUYwJTlGJTg3JUE2JUYwJTlGJTg3JUI2', '🇦🇶'],
  ['JUYwJTlGJTg3JUE2JUYwJTlGJTg3JUFD', '🇦🇬'],
  ['JUYwJTlGJTg3JUE2JUYwJTlGJTg3JUI3', '🇦🇷'],
  ['JUYwJTlGJTg3JUE2JUYwJTlGJTg3JUIy', '🇦🇲'],
  ['JUYwJTlGJTg3JUE2JUYwJTlGJTg3JUJD', '🇦🇼'],
  ['JUYwJTlGJTg3JUE2JUYwJTlGJTg3JUJB', '🇦🇺'],
  ['JUYwJTlGJTg3JUE2JUYwJTlGJTg3JUI5', '🇦🇹'],
  ['JUYwJTlGJTg3JUE2JUYwJTlGJTg3JUJG', '🇦🇿'],
  ['JUYwJTlGJTg3JUE3JUYwJTlGJTg3JUI4', '🇧🇸'],
  ['JUYwJTlGJTg3JUE3JUYwJTlGJTg3JUFE', '🇧🇭'],
  ['JUYwJTlGJTg3JUE3JUYwJTlGJTg3JUE5', '🇧🇩'],
  ['JUYwJTlGJTg3JUE3JUYwJTlGJTg3JUE3', '🇧🇧'],
  ['JUYwJTlGJTg3JUE3JUYwJTlGJTg3JUJF', '🇧🇾'],
  ['JUYwJTlGJTg3JUE3JUYwJTlGJTg3JUFB', '🇧🇪'],
  ['JUYwJTlGJTg3JUE3JUYwJTlGJTg3JUJG', '🇧🇿'],
  ['JUYwJTlGJTg3JUE3JUYwJTlGJTg3JUFG', '🇧🇯'],
  ['JUYwJTlGJTg3JUE3JUYwJTlGJTg3JUIy', '🇧🇲'],
  ['JUYwJTlGJTg3JUE3JUYwJTlGJTg3JUI5', '🇧🇹'],
  ['JUYwJTlGJTg3JUE3JUYwJTlGJTg3JUI0', '🇧🇴'],
  ['JUYwJTlGJTg3JUE3JUYwJTlGJTg3JUI2', '🇧🇶'],
  ['JUYwJTlGJTg3JUE3JUYwJTlGJTg3JUE2', '🇧🇦'],
  ['JUYwJTlGJTg3JUE3JUYwJTlGJTg3JUJD', '🇧🇼'],
  ['JUYwJTlGJTg3JUE3JUYwJTlGJTg3JUI3', '🇧🇷'],
  ['JUYwJTlGJTg3JUFFJUYwJTlGJTg3JUI0', '🇮🇴'],
  ['JUYwJTlGJTg3JUJCJUYwJTlGJTg3JUFD', '🇻🇬'],
  ['JUYwJTlGJTg3JUE3JUYwJTlGJTg3JUIz', '🇧🇳'],
  ['JUYwJTlGJTg3JUE3JUYwJTlGJTg3JUFD', '🇧🇬'],
  ['JUYwJTlGJTg3JUE3JUYwJTlGJTg3JUFC', '🇧🇫'],
  ['JUYwJTlGJTg3JUE3JUYwJTlGJTg3JUFF', '🇧🇮'],
  ['JUYwJTlGJTg3JUE4JUYwJTlGJTg3JUJC', '🇨🇻'],
  ['JUYwJTlGJTg3JUIwJUYwJTlGJTg3JUFE', '🇰🇭'],
  ['JUYwJTlGJTg3JUE4JUYwJTlGJTg3JUIy', '🇨🇲'],
  ['JUYwJTlGJTg3JUE4JUYwJTlGJTg3JUE2', '🇨🇦'],
  ['JUYwJTlGJTg3JUFFJUYwJTlGJTg3JUE4', '🇮🇨'],
  ['JUYwJTlGJTg3JUIwJUYwJTlGJTg3JUJF', '🇰🇾'],
  ['JUYwJTlGJTg3JUE4JUYwJTlGJTg3JUFC', '🇨🇫'],
  ['JUYwJTlGJTg3JUI5JUYwJTlGJTg3JUE5', '🇹🇩'],
  ['JUYwJTlGJTg3JUE4JUYwJTlGJTg3JUIx', '🇨🇱'],
  ['JUYwJTlGJTg3JUE4JUYwJTlGJTg3JUIz', '🇨🇳'],
  ['JUYwJTlGJTg3JUE4JUYwJTlGJTg3JUJE', '🇨🇽'],
  ['JUYwJTlGJTg3JUE4JUYwJTlGJTg3JUE4', '🇨🇨'],
  ['JUYwJTlGJTg3JUE4JUYwJTlGJTg3JUI0', '🇨🇴'],
  ['JUYwJTlGJTg3JUIwJUYwJTlGJTg3JUIy', '🇰🇲'],
  ['JUYwJTlGJTg3JUE4JUYwJTlGJTg3JUFD', '🇨🇬'],
  ['JUYwJTlGJTg3JUE4JUYwJTlGJTg3JUE5', '🇨🇩'],
  ['JUYwJTlGJTg3JUE4JUYwJTlGJTg3JUIw', '🇨🇰'],
  ['JUYwJTlGJTg3JUE4JUYwJTlGJTg3JUI3', '🇨🇷'],
  ['JUYwJTlGJTg3JUE4JUYwJTlGJTg3JUFF', '🇨🇮'],
  ['JUYwJTlGJTg3JUFEJUYwJTlGJTg3JUI3', '🇭🇷'],
  ['JUYwJTlGJTg3JUE4JUYwJTlGJTg3JUJB', '🇨🇺'],
  ['JUYwJTlGJTg3JUE4JUYwJTlGJTg3JUJD', '🇨🇼'],
  ['JUYwJTlGJTg3JUE4JUYwJTlGJTg3JUJF', '🇨🇾'],
  ['JUYwJTlGJTg3JUE4JUYwJTlGJTg3JUJG', '🇨🇿'],
  ['JUYwJTlGJTg3JUE5JUYwJTlGJTg3JUIw', '🇩🇰'],
  ['JUYwJTlGJTg3JUE5JUYwJTlGJTg3JUFG', '🇩🇯'],
  ['JUYwJTlGJTg3JUE5JUYwJTlGJTg3JUIy', '🇩🇲'],
  ['JUYwJTlGJTg3JUE5JUYwJTlGJTg3JUI0', '🇩🇴'],
  ['JUYwJTlGJTg3JUFBJUYwJTlGJTg3JUE4', '🇪🇨'],
  ['JUYwJTlGJTg3JUFBJUYwJTlGJTg3JUFD', '🇪🇬'],
  ['JUYwJTlGJTg3JUI4JUYwJTlGJTg3JUJC', '🇸🇻'],
  ['JUYwJTlGJTg3JUFDJUYwJTlGJTg3JUI2', '🇬🇶'],
  ['JUYwJTlGJTg3JUFBJUYwJTlGJTg3JUI3', '🇪🇷'],
  ['JUYwJTlGJTg3JUFBJUYwJTlGJTg3JUFB', '🇪🇪'],
  ['JUYwJTlGJTg3JUFBJUYwJTlGJTg3JUI5', '🇪🇹'],
  ['JUYwJTlGJTg3JUFBJUYwJTlGJTg3JUJB', '🇪🇺'],
  ['JUYwJTlGJTg3JUFCJUYwJTlGJTg3JUIw', '🇫🇰'],
  ['JUYwJTlGJTg3JUFCJUYwJTlGJTg3JUI0', '🇫🇴'],
  ['JUYwJTlGJTg3JUFCJUYwJTlGJTg3JUFG', '🇫🇯'],
  ['JUYwJTlGJTg3JUFCJUYwJTlGJTg3JUFF', '🇫🇮'],
  ['JUYwJTlGJTg3JUFCJUYwJTlGJTg3JUI3', '🇫🇷'],
  ['JUYwJTlGJTg3JUFDJUYwJTlGJTg3JUFC', '🇬🇫'],
  ['JUYwJTlGJTg3JUI1JUYwJTlGJTg3JUFC', '🇵🇫'],
  ['JUYwJTlGJTg3JUI5JUYwJTlGJTg3JUFC', '🇹🇫'],
  ['JUYwJTlGJTg3JUFDJUYwJTlGJTg3JUE2', '🇬🇦'],
  ['JUYwJTlGJTg3JUFDJUYwJTlGJTg3JUIy', '🇬🇲'],
  ['JUYwJTlGJTg3JUFDJUYwJTlGJTg3JUFB', '🇬🇪'],
  ['JUYwJTlGJTg3JUE5JUYwJTlGJTg3JUFB', '🇩🇪'],
  ['JUYwJTlGJTg3JUFDJUYwJTlGJTg3JUFE', '🇬🇭'],
  ['JUYwJTlGJTg3JUFDJUYwJTlGJTg3JUFF', '🇬🇮'],
  ['JUYwJTlGJTg3JUFDJUYwJTlGJTg3JUI3', '🇬🇷'],
  ['JUYwJTlGJTg3JUFDJUYwJTlGJTg3JUIx', '🇬🇱'],
  ['JUYwJTlGJTg3JUFDJUYwJTlGJTg3JUE5', '🇬🇩'],
  ['JUYwJTlGJTg3JUFDJUYwJTlGJTg3JUI1', '🇬🇵'],
  ['JUYwJTlGJTg3JUFDJUYwJTlGJTg3JUJB', '🇬🇺'],
  ['JUYwJTlGJTg3JUFDJUYwJTlGJTg3JUI5', '🇬🇹'],
  ['JUYwJTlGJTg3JUFDJUYwJTlGJTg3JUFD', '🇬🇬'],
  ['JUYwJTlGJTg3JUFDJUYwJTlGJTg3JUIz', '🇬🇳'],
  ['JUYwJTlGJTg3JUFDJUYwJTlGJTg3JUJD', '🇬🇼'],
  ['JUYwJTlGJTg3JUFDJUYwJTlGJTg3JUJF', '🇬🇾'],
  ['JUYwJTlGJTg3JUFEJUYwJTlGJTg3JUI5', '🇭🇹'],
  ['JUYwJTlGJTg3JUFEJUYwJTlGJTg3JUIz', '🇭🇳'],
  ['JUYwJTlGJTg3JUFEJUYwJTlGJTg3JUIw', '🇭🇰'],
  ['JUYwJTlGJTg3JUFEJUYwJTlGJTg3JUJB', '🇭🇺'],
  ['JUYwJTlGJTg3JUFFJUYwJTlGJTg3JUI4', '🇮🇸'],
  ['JUYwJTlGJTg3JUFFJUYwJTlGJTg3JUIz', '🇮🇳'],
  ['JUYwJTlGJTg3JUFFJUYwJTlGJTg3JUE5', '🇮🇩'],
  ['JUYwJTlGJTg3JUFFJUYwJTlGJTg3JUI3', '🇮🇷'],
  ['JUYwJTlGJTg3JUFFJUYwJTlGJTg3JUI2', '🇮🇶'],
  ['JUYwJTlGJTg3JUFFJUYwJTlGJTg3JUFB', '🇮🇪'],
  ['JUYwJTlGJTg3JUFFJUYwJTlGJTg3JUIy', '🇮🇲'],
  ['JUYwJTlGJTg3JUFFJUYwJTlGJTg3JUIx', '🇮🇱'],
  ['JUYwJTlGJTg3JUFFJUYwJTlGJTg3JUI5', '🇮🇹'],
  ['JUYwJTlGJTg3JUFGJUYwJTlGJTg3JUIy', '🇯🇲'],
  ['JUYwJTlGJTg3JUFGJUYwJTlGJTg3JUI1', '🇯🇵'],
  ['JUYwJTlGJThFJThD', '🎌'],
  ['JUYwJTlGJTg3JUFGJUYwJTlGJTg3JUFB', '🇯🇪'],
  ['JUYwJTlGJTg3JUFGJUYwJTlGJTg3JUI0', '🇯🇴'],
  ['JUYwJTlGJTg3JUIwJUYwJTlGJTg3JUJG', '🇰🇿'],
  ['JUYwJTlGJTg3JUIwJUYwJTlGJTg3JUFB', '🇰🇪'],
  ['JUYwJTlGJTg3JUIwJUYwJTlGJTg3JUFF', '🇰🇮'],
  ['JUYwJTlGJTg3JUJEJUYwJTlGJTg3JUIw', '🇽🇰'],
  ['JUYwJTlGJTg3JUIwJUYwJTlGJTg3JUJD', '🇰🇼'],
  ['JUYwJTlGJTg3JUIwJUYwJTlGJTg3JUFD', '🇰🇬'],
  ['JUYwJTlGJTg3JUIxJUYwJTlGJTg3JUE2', '🇱🇦'],
  ['JUYwJTlGJTg3JUIxJUYwJTlGJTg3JUJC', '🇱🇻'],
  ['JUYwJTlGJTg3JUIxJUYwJTlGJTg3JUE3', '🇱🇧'],
  ['JUYwJTlGJTg3JUIxJUYwJTlGJTg3JUI4', '🇱🇸'],
  ['JUYwJTlGJTg3JUIxJUYwJTlGJTg3JUI3', '🇱🇷'],
  ['JUYwJTlGJTg3JUIxJUYwJTlGJTg3JUJF', '🇱🇾'],
  ['JUYwJTlGJTg3JUIxJUYwJTlGJTg3JUFF', '🇱🇮'],
  ['JUYwJTlGJTg3JUIxJUYwJTlGJTg3JUI5', '🇱🇹'],
  ['JUYwJTlGJTg3JUIxJUYwJTlGJTg3JUJB', '🇱🇺'],
  ['JUYwJTlGJTg3JUIyJUYwJTlGJTg3JUI0', '🇲🇴'],
  ['JUYwJTlGJTg3JUIyJUYwJTlGJTg3JUIw', '🇲🇰'],
  ['JUYwJTlGJTg3JUIyJUYwJTlGJTg3JUFD', '🇲🇬'],
  ['JUYwJTlGJTg3JUIyJUYwJTlGJTg3JUJD', '🇲🇼'],
  ['JUYwJTlGJTg3JUIyJUYwJTlGJTg3JUJF', '🇲🇾'],
  ['JUYwJTlGJTg3JUIyJUYwJTlGJTg3JUJC', '🇲🇻'],
  ['JUYwJTlGJTg3JUIyJUYwJTlGJTg3JUIx', '🇲🇱'],
  ['JUYwJTlGJTg3JUIyJUYwJTlGJTg3JUI5', '🇲🇹'],
  ['JUYwJTlGJTg3JUIyJUYwJTlGJTg3JUFE', '🇲🇭'],
  ['JUYwJTlGJTg3JUIyJUYwJTlGJTg3JUI2', '🇲🇶'],
  ['JUYwJTlGJTg3JUIyJUYwJTlGJTg3JUI3', '🇲🇷'],
  ['JUYwJTlGJTg3JUIyJUYwJTlGJTg3JUJB', '🇲🇺'],
  ['JUYwJTlGJTg3JUJFJUYwJTlGJTg3JUI5', '🇾🇹'],
  ['JUYwJTlGJTg3JUIyJUYwJTlGJTg3JUJE', '🇲🇽'],
  ['JUYwJTlGJTg3JUFCJUYwJTlGJTg3JUIy', '🇫🇲'],
  ['JUYwJTlGJTg3JUIyJUYwJTlGJTg3JUE5', '🇲🇩'],
  ['JUYwJTlGJTg3JUIyJUYwJTlGJTg3JUE4', '🇲🇨'],
  ['JUYwJTlGJTg3JUIyJUYwJTlGJTg3JUIz', '🇲🇳'],
  ['JUYwJTlGJTg3JUIyJUYwJTlGJTg3JUFB', '🇲🇪'],
  ['JUYwJTlGJTg3JUIyJUYwJTlGJTg3JUI4', '🇲🇸'],
  ['JUYwJTlGJTg3JUIyJUYwJTlGJTg3JUE2', '🇲🇦'],
  ['JUYwJTlGJTg3JUIyJUYwJTlGJTg3JUJG', '🇲🇿'],
  ['JUYwJTlGJTg3JUIyJUYwJTlGJTg3JUIy', '🇲🇲'],
  ['JUYwJTlGJTg3JUIzJUYwJTlGJTg3JUE2', '🇳🇦'],
  ['JUYwJTlGJTg3JUIzJUYwJTlGJTg3JUI3', '🇳🇷'],
  ['JUYwJTlGJTg3JUIzJUYwJTlGJTg3JUI1', '🇳🇵'],
  ['JUYwJTlGJTg3JUIzJUYwJTlGJTg3JUIx', '🇳🇱'],
  ['JUYwJTlGJTg3JUIzJUYwJTlGJTg3JUE4', '🇳🇨'],
  ['JUYwJTlGJTg3JUIzJUYwJTlGJTg3JUJG', '🇳🇿'],
  ['JUYwJTlGJTg3JUIzJUYwJTlGJTg3JUFF', '🇳🇮'],
  ['JUYwJTlGJTg3JUIzJUYwJTlGJTg3JUFB', '🇳🇪'],
  ['JUYwJTlGJTg3JUIzJUYwJTlGJTg3JUFD', '🇳🇬'],
  ['JUYwJTlGJTg3JUIzJUYwJTlGJTg3JUJB', '🇳🇺'],
  ['JUYwJTlGJTg3JUIzJUYwJTlGJTg3JUFC', '🇳🇫'],
  ['JUYwJTlGJTg3JUIyJUYwJTlGJTg3JUI1', '🇲🇵'],
  ['JUYwJTlGJTg3JUIwJUYwJTlGJTg3JUI1', '🇰🇵'],
  ['JUYwJTlGJTg3JUIzJUYwJTlGJTg3JUI0', '🇳🇴'],
  ['JUYwJTlGJTg3JUI0JUYwJTlGJTg3JUIy', '🇴🇲'],
  ['JUYwJTlGJTg3JUI1JUYwJTlGJTg3JUIw', '🇵🇰'],
  ['JUYwJTlGJTg3JUI1JUYwJTlGJTg3JUJD', '🇵🇼'],
  ['JUYwJTlGJTg3JUI1JUYwJTlGJTg3JUI4', '🇵🇸'],
  ['JUYwJTlGJTg3JUI1JUYwJTlGJTg3JUE2', '🇵🇦'],
  ['JUYwJTlGJTg3JUI1JUYwJTlGJTg3JUFD', '🇵🇬'],
  ['JUYwJTlGJTg3JUI1JUYwJTlGJTg3JUJF', '🇵🇾'],
  ['JUYwJTlGJTg3JUI1JUYwJTlGJTg3JUFB', '🇵🇪'],
  ['JUYwJTlGJTg3JUI1JUYwJTlGJTg3JUFE', '🇵🇭'],
  ['JUYwJTlGJTg3JUI1JUYwJTlGJTg3JUIz', '🇵🇳'],
  ['JUYwJTlGJTg3JUI1JUYwJTlGJTg3JUIx', '🇵🇱'],
  ['JUYwJTlGJTg3JUI1JUYwJTlGJTg3JUI5', '🇵🇹'],
  ['JUYwJTlGJTg3JUI1JUYwJTlGJTg3JUI3', '🇵🇷'],
  ['JUYwJTlGJTg3JUI2JUYwJTlGJTg3JUE2', '🇶🇦'],
  ['JUYwJTlGJTg3JUI3JUYwJTlGJTg3JUFB', '🇷🇪'],
  ['JUYwJTlGJTg3JUI3JUYwJTlGJTg3JUI0', '🇷🇴'],
  ['JUYwJTlGJTg3JUI3JUYwJTlGJTg3JUJB', '🇷🇺'],
  ['JUYwJTlGJTg3JUI3JUYwJTlGJTg3JUJD', '🇷🇼'],
  ['JUYwJTlGJTg3JUE3JUYwJTlGJTg3JUIx', '🇧🇱'],
  ['JUYwJTlGJTg3JUI4JUYwJTlGJTg3JUFE', '🇸🇭'],
  ['JUYwJTlGJTg3JUIwJUYwJTlGJTg3JUIz', '🇰🇳'],
  ['JUYwJTlGJTg3JUIxJUYwJTlGJTg3JUE4', '🇱🇨'],
  ['JUYwJTlGJTg3JUI1JUYwJTlGJTg3JUIy', '🇵🇲'],
  ['JUYwJTlGJTg3JUJCJUYwJTlGJTg3JUE4', '🇻🇨'],
  ['JUYwJTlGJTg3JUJDJUYwJTlGJTg3JUI4', '🇼🇸'],
  ['JUYwJTlGJTg3JUI4JUYwJTlGJTg3JUIy', '🇸🇲'],
  ['JUYwJTlGJTg3JUI4JUYwJTlGJTg3JUI5', '🇸🇹'],
  ['JUYwJTlGJTg3JUI4JUYwJTlGJTg3JUE2', '🇸🇦'],
  ['JUYwJTlGJTg3JUI4JUYwJTlGJTg3JUIz', '🇸🇳'],
  ['JUYwJTlGJTg3JUI3JUYwJTlGJTg3JUI4', '🇷🇸'],
  ['JUYwJTlGJTg3JUI4JUYwJTlGJTg3JUE4', '🇸🇨'],
  ['JUYwJTlGJTg3JUI4JUYwJTlGJTg3JUIx', '🇸🇱'],
  ['JUYwJTlGJTg3JUI4JUYwJTlGJTg3JUFD', '🇸🇬'],
  ['JUYwJTlGJTg3JUI4JUYwJTlGJTg3JUJE', '🇸🇽'],
  ['JUYwJTlGJTg3JUI4JUYwJTlGJTg3JUIw', '🇸🇰'],
  ['JUYwJTlGJTg3JUI4JUYwJTlGJTg3JUFF', '🇸🇮'],
  ['JUYwJTlGJTg3JUI4JUYwJTlGJTg3JUE3', '🇸🇧'],
  ['JUYwJTlGJTg3JUI4JUYwJTlGJTg3JUI0', '🇸🇴'],
  ['JUYwJTlGJTg3JUJGJUYwJTlGJTg3JUE2', '🇿🇦'],
  ['JUYwJTlGJTg3JUFDJUYwJTlGJTg3JUI4', '🇬🇸'],
  ['JUYwJTlGJTg3JUIwJUYwJTlGJTg3JUI3', '🇰🇷'],
  ['JUYwJTlGJTg3JUI4JUYwJTlGJTg3JUI4', '🇸🇸'],
  ['JUYwJTlGJTg3JUFBJUYwJTlGJTg3JUI4', '🇪🇸'],
  ['JUYwJTlGJTg3JUIxJUYwJTlGJTg3JUIw', '🇱🇰'],
  ['JUYwJTlGJTg3JUI4JUYwJTlGJTg3JUE5', '🇸🇩'],
  ['JUYwJTlGJTg3JUI4JUYwJTlGJTg3JUI3', '🇸🇷'],
  ['JUYwJTlGJTg3JUI4JUYwJTlGJTg3JUJG', '🇸🇿'],
  ['JUYwJTlGJTg3JUI4JUYwJTlGJTg3JUFB', '🇸🇪'],
  ['JUYwJTlGJTg3JUE4JUYwJTlGJTg3JUFE', '🇨🇭'],
  ['JUYwJTlGJTg3JUI4JUYwJTlGJTg3JUJF', '🇸🇾'],
  ['JUYwJTlGJTg3JUI5JUYwJTlGJTg3JUJD', '🇹🇼'],
  ['JUYwJTlGJTg3JUI5JUYwJTlGJTg3JUFG', '🇹🇯'],
  ['JUYwJTlGJTg3JUI5JUYwJTlGJTg3JUJG', '🇹🇿'],
  ['JUYwJTlGJTg3JUI5JUYwJTlGJTg3JUFE', '🇹🇭'],
  ['JUYwJTlGJTg3JUI5JUYwJTlGJTg3JUIx', '🇹🇱'],
  ['JUYwJTlGJTg3JUI5JUYwJTlGJTg3JUFD', '🇹🇬'],
  ['JUYwJTlGJTg3JUI5JUYwJTlGJTg3JUIw', '🇹🇰'],
  ['JUYwJTlGJTg3JUI5JUYwJTlGJTg3JUI0', '🇹🇴'],
  ['JUYwJTlGJTg3JUI5JUYwJTlGJTg3JUI5', '🇹🇹'],
  ['JUYwJTlGJTg3JUI5JUYwJTlGJTg3JUIz', '🇹🇳'],
  ['JUYwJTlGJTg3JUI5JUYwJTlGJTg3JUI3', '🇹🇷'],
  ['JUYwJTlGJTg3JUI5JUYwJTlGJTg3JUIy', '🇹🇲'],
  ['JUYwJTlGJTg3JUI5JUYwJTlGJTg3JUE4', '🇹🇨'],
  ['JUYwJTlGJTg3JUI5JUYwJTlGJTg3JUJC', '🇹🇻'],
  ['JUYwJTlGJTg3JUJBJUYwJTlGJTg3JUFD', '🇺🇬'],
  ['JUYwJTlGJTg3JUJBJUYwJTlGJTg3JUE2', '🇺🇦'],
  ['JUYwJTlGJTg3JUE2JUYwJTlGJTg3JUFB', '🇦🇪'],
  ['JUYwJTlGJTg3JUFDJUYwJTlGJTg3JUE3', '🇬🇧'],
  ['JUYwJTlGJTg3JUJBJUYwJTlGJTg3JUI4', '🇺🇸'],
  ['JUYwJTlGJTg3JUJCJUYwJTlGJTg3JUFF', '🇻🇮'],
  ['JUYwJTlGJTg3JUJBJUYwJTlGJTg3JUJF', '🇺🇾'],
  ['JUYwJTlGJTg3JUJBJUYwJTlGJTg3JUJG', '🇺🇿'],
  ['JUYwJTlGJTg3JUJCJUYwJTlGJTg3JUJB', '🇻🇺'],
  ['JUYwJTlGJTg3JUJCJUYwJTlGJTg3JUE2', '🇻🇦'],
  ['JUYwJTlGJTg3JUJCJUYwJTlGJTg3JUFB', '🇻🇪'],
  ['JUYwJTlGJTg3JUJCJUYwJTlGJTg3JUIz', '🇻🇳'],
  ['JUYwJTlGJTg3JUJDJUYwJTlGJTg3JUFC', '🇼🇫'],
  ['JUYwJTlGJTg3JUFBJUYwJTlGJTg3JUFE', '🇪🇭'],
  ['JUYwJTlGJTg3JUJFJUYwJTlGJTg3JUFB', '🇾🇪'],
  ['JUYwJTlGJTg3JUJGJUYwJTlGJTg3JUIy', '🇿🇲'],
  ['JUYwJTlGJTg3JUJGJUYwJTlGJTg3JUJD', '🇿🇼'],
]);
