export default {
  appDEFields: [
    {
      codeName: 'dyna_dashboard_id',
      logicName: '动态数据看板标识',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 200,
      name: 'DYNADASHBOARDID',
      id: 'dyna_dashboard_id',
    },
    {
      codeName: 'dyna_dashboard_name',
      logicName: '名称',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 200,
      enableQuickSearch: true,
      name: 'DYNADASHBOARDNAME',
      id: 'dyna_dashboard_name',
    },
    {
      codeName: 'ps_dev_sln_sys_id',
      logicName: '开发系统标识',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 100,
      name: 'PSDEVSLNSYSID',
      id: 'ps_dev_sln_sys_id',
    },
    {
      codeName: 'type',
      logicName: '看板类型',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 100,
      name: 'TYPE',
      id: 'type',
    },
    {
      codeName: 'app_id',
      logicName: '应用标识',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 100,
      name: 'APPID',
      id: 'app_id',
    },
    {
      codeName: 'model_id',
      logicName: '模型标识',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 100,
      name: 'MODELID',
      id: 'model_id',
    },
    {
      codeName: 'user_id',
      logicName: '用户标识',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 100,
      name: 'USERID',
      id: 'user_id',
    },
    {
      codeName: 'create_man',
      logicName: '建立人',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 60,
      name: 'CREATEMAN',
      id: 'create_man',
    },
    {
      codeName: 'create_date',
      logicName: '建立时间',
      predefinedType: 'NONE',
      stdDataType: 5,
      valueFormat: 'YYYY-MM-DD HH:mm:ss',
      name: 'CREATEDATE',
      id: 'create_date',
    },
    {
      codeName: 'update_man',
      logicName: '更新人',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 60,
      name: 'UPDATEMAN',
      id: 'update_man',
    },
    {
      codeName: 'update_date',
      logicName: '更新时间',
      predefinedType: 'NONE',
      stdDataType: 5,
      valueFormat: 'YYYY-MM-DD HH:mm:ss',
      name: 'UPDATEDATE',
      id: 'update_date',
    },
    {
      codeName: 'model',
      logicName: '模型',
      predefinedType: 'NONE',
      stdDataType: 21,
      stringLength: 1048576,
      name: 'MODEL',
      id: 'model',
    },
  ],
  appDEMethodDTOs: [
    {
      codeName: 'dyna_dashboard_dto',
      appDEMethodDTOFields: [
        {
          codeName: 'dyna_dashboard_id',
          logicName: '动态数据看板标识',
          appDEFieldId: 'dyna_dashboard_id',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          id: 'dyna_dashboard_id',
        },
        {
          codeName: 'dyna_dashboard_name',
          logicName: '名称',
          appDEFieldId: 'dyna_dashboard_name',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'dyna_dashboard_name',
        },
        {
          codeName: 'ps_dev_sln_sys_id',
          logicName: '开发系统标识',
          appDEFieldId: 'ps_dev_sln_sys_id',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'ps_dev_sln_sys_id',
        },
        {
          codeName: 'type',
          logicName: '看板类型',
          appDEFieldId: 'type',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'type',
        },
        {
          codeName: 'app_id',
          logicName: '应用标识',
          appDEFieldId: 'app_id',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'app_id',
        },
        {
          codeName: 'model_id',
          logicName: '模型标识',
          appDEFieldId: 'model_id',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'model_id',
        },
        {
          codeName: 'user_id',
          logicName: '用户标识',
          appDEFieldId: 'user_id',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'user_id',
        },
        {
          codeName: 'create_man',
          logicName: '建立人',
          appDEFieldId: 'create_man',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          id: 'create_man',
        },
        {
          codeName: 'create_date',
          jsonFormat: 'yyyy-MM-dd HH:mm:ss',
          logicName: '建立时间',
          appDEFieldId: 'create_date',
          sourceType: 'DEFIELD',
          stdDataType: 5,
          type: 'SIMPLE',
          id: 'create_date',
        },
        {
          codeName: 'update_man',
          logicName: '更新人',
          appDEFieldId: 'update_man',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          id: 'update_man',
        },
        {
          codeName: 'update_date',
          jsonFormat: 'yyyy-MM-dd HH:mm:ss',
          logicName: '更新时间',
          appDEFieldId: 'update_date',
          sourceType: 'DEFIELD',
          stdDataType: 5,
          type: 'SIMPLE',
          id: 'update_date',
        },
        {
          codeName: 'model',
          logicName: '模型',
          appDEFieldId: 'model',
          sourceType: 'DEFIELD',
          stdDataType: 21,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'model',
        },
      ],
      sourceType: 'DE',
      type: 'DEFAULT',
      id: 'dyna_dashboard_dto',
    },
    {
      codeName: 'dyna_dashboard_filter_dto',
      appDEMethodDTOFields: [
        {
          codeName: 'n_dynadashboardid_eq',
          logicName: '动态数据看板标识',
          appDEFieldId: 'dyna_dashboard_id',
          sourceType: 'DEFSEARCHMODE',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'n_dynadashboardid_eq',
        },
        {
          codeName: 'n_dynadashboardname_like',
          logicName: '名称',
          appDEFieldId: 'dyna_dashboard_name',
          sourceType: 'DEFSEARCHMODE',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'n_dynadashboardname_like',
        },
        {
          codeName: 'n_type_eq',
          logicName: '看板类型',
          appDEFieldId: 'type',
          sourceType: 'DEFSEARCHMODE',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'n_type_eq',
        },
      ],
      sourceType: 'DE',
      type: 'DEFILTER',
      id: 'dyna_dashboard_filter_dto',
    },
  ],
  appDEMethods: [
    {
      codeName: 'check_key',
      methodType: 'DEACTION',
      appDEMethodInput: {
        appDEMethodDTOId: 'dyna_dashboard_dto',
        type: 'DTO',
        id: '输入对象',
      },
      appDEMethodReturn: {
        stdDataType: 9,
        type: 'SIMPLE',
        id: '返回对象',
      },
      requestMethod: 'POST',
      requestParamType: 'ENTITY',
      requestPath: '/check_key',
      actionMode: 'CHECKKEY',
      actionTag: 'CheckKey',
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'CheckKey',
      id: 'check_key',
    },
    {
      codeName: 'create',
      methodType: 'DEACTION',
      appDEMethodInput: {
        appDEMethodDTOId: 'dyna_dashboard_dto',
        type: 'DTO',
        output: true,
        id: '输入对象',
      },
      appDEMethodReturn: {
        appDEMethodDTOId: 'dyna_dashboard_dto',
        type: 'DTO',
        id: '返回对象',
      },
      requestMethod: 'POST',
      requestParamType: 'ENTITY',
      noServiceCodeName: true,
      actionMode: 'CREATE',
      actionTag: 'Create',
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'Create',
      id: 'create',
    },
    {
      codeName: 'get',
      methodType: 'DEACTION',
      appDEMethodInput: {
        keyAppDEFieldId: 'dyna_dashboard_id',
        type: 'KEYFIELD',
        id: '输入对象',
      },
      appDEMethodReturn: {
        appDEMethodDTOId: 'dyna_dashboard_dto',
        type: 'DTO',
        id: '返回对象',
      },
      requestField: 'DYNADASHBOARDID',
      requestMethod: 'GET',
      requestParamType: 'FIELD',
      needResourceKey: true,
      noServiceCodeName: true,
      actionMode: 'READ',
      actionTag: 'Get',
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'Get',
      id: 'get',
    },
    {
      codeName: 'get_draft',
      methodType: 'DEACTION',
      appDEMethodInput: {
        appDEMethodDTOId: 'dyna_dashboard_dto',
        type: 'DTO',
        id: '输入对象',
      },
      appDEMethodReturn: {
        appDEMethodDTOId: 'dyna_dashboard_dto',
        type: 'DTO',
        id: '返回对象',
      },
      requestMethod: 'GET',
      requestParamType: 'NONE',
      requestPath: '/get_draft',
      actionMode: 'GETDRAFT',
      actionTag: 'GetDraft',
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'GetDraft',
      id: 'get_draft',
    },
    {
      codeName: 'remove',
      methodType: 'DEACTION',
      appDEMethodInput: {
        keyAppDEFieldId: 'dyna_dashboard_id',
        type: 'KEYFIELDS',
        id: '输入对象',
      },
      appDEMethodReturn: {
        type: 'VOID',
        id: '返回对象',
      },
      requestField: 'DYNADASHBOARDID',
      requestMethod: 'DELETE',
      requestParamType: 'FIELD',
      needResourceKey: true,
      noServiceCodeName: true,
      actionMode: 'DELETE',
      actionTag: 'Remove',
      actionType: 'REMOTE',
      batchActionMode: 1,
      enableBatchAction: true,
      dataSetType: 'REMOTE',
      name: 'Remove',
      id: 'remove',
    },
    {
      codeName: 'save',
      methodType: 'DEACTION',
      appDEMethodInput: {
        appDEMethodDTOId: 'dyna_dashboard_dto',
        type: 'DTO',
        output: true,
        id: '输入对象',
      },
      appDEMethodReturn: {
        appDEMethodDTOId: 'dyna_dashboard_dto',
        type: 'DTO',
        id: '返回对象',
      },
      requestMethod: 'POST',
      requestParamType: 'ENTITY',
      requestPath: '/save',
      actionMode: 'SAVE',
      actionTag: 'Save',
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'Save',
      id: 'save',
    },
    {
      codeName: 'update',
      methodType: 'DEACTION',
      appDEMethodInput: {
        appDEMethodDTOId: 'dyna_dashboard_dto',
        type: 'DTO',
        output: true,
        id: '输入对象',
      },
      appDEMethodReturn: {
        appDEMethodDTOId: 'dyna_dashboard_dto',
        type: 'DTO',
        id: '返回对象',
      },
      requestMethod: 'PUT',
      requestParamType: 'ENTITY',
      needResourceKey: true,
      noServiceCodeName: true,
      actionMode: 'UPDATE',
      actionTag: 'Update',
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'Update',
      id: 'update',
    },
    {
      codeName: 'fetch_default',
      methodType: 'FETCH',
      appDEMethodInput: {
        appDEMethodDTOId: 'dyna_dashboard_filter_dto',
        type: 'DTO',
        id: '输入对象',
      },
      appDEMethodReturn: {
        appDEMethodDTOId: 'dyna_dashboard_dto',
        type: 'PAGE',
        id: '返回对象',
      },
      requestMethod: 'POST',
      requestParamType: 'ENTITY',
      requestPath: '/fetch_default',
      actionType: 'REMOTE',
      dataSetName: 'DEFAULT',
      dataSetTag: 'Default',
      dataSetType: 'REMOTE',
      id: 'fetch_default',
    },
    {
      codeName: 'FilterCreate',
      methodType: 'FILTERACTION',
      builtinMethod: true,
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'FILTERCREATE',
      id: 'filtercreate',
    },
    {
      codeName: 'FilterFetch',
      methodType: 'FILTERACTION',
      builtinMethod: true,
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'FILTERFETCH',
      id: 'filterfetch',
    },
    {
      codeName: 'FilterGet',
      methodType: 'FILTERACTION',
      builtinMethod: true,
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'FILTERGET',
      id: 'filterget',
    },
    {
      codeName: 'FilterGetDraft',
      methodType: 'FILTERACTION',
      builtinMethod: true,
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'FILTERGETDRAFT',
      id: 'filtergetdraft',
    },
    {
      codeName: 'FilterRemove',
      methodType: 'FILTERACTION',
      builtinMethod: true,
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'FILTERREMOVE',
      id: 'filterremove',
    },
    {
      codeName: 'FilterSearch',
      methodType: 'FILTERACTION',
      builtinMethod: true,
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'FILTERSEARCH',
      id: 'filtersearch',
    },
    {
      codeName: 'FilterUpdate',
      methodType: 'FILTERACTION',
      builtinMethod: true,
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'FILTERUPDATE',
      id: 'filterupdate',
    },
  ],
  deopprivs: [
    {
      logicName: '建立',
      name: 'CREATE',
      id: 'create',
    },
    {
      logicName: '删除',
      name: 'DELETE',
      id: 'delete',
    },
    {
      logicName: '读取',
      name: 'READ',
      id: 'read',
    },
    {
      logicName: '更新',
      name: 'UPDATE',
      id: 'update',
    },
  ],
  codeName: 'dyna_dashboard',
  deapicodeName: 'dyna_dashboard',
  deapicodeName2: 'dyna_dashboards',
  deapitag: 'DYNADASHBOARD',
  decodeName: 'DynaDashboard',
  dataAccCtrlArch: 1,
  dataAccCtrlMode: 1,
  enableUIActions: 15,
  keyAppDEFieldId: 'dyna_dashboard_id',
  lnlanguageRes: {
    lanResTag: 'DE.LNAME.DYNADASHBOARD',
  },
  logicName: '动态数据看板',
  majorAppDEFieldId: 'dyna_dashboard_name',
  quickSearchAppDEFieldIds: ['dyna_dashboard_name'],
  sysAPITag: 'api',
  defaultMode: true,
  enableFilterActions: true,
  major: true,
  name: 'DYNADASHBOARD',
  id: 'web.dyna_dashboard',
  codeName2: 'dyna_dashboards',
  requestPaths: [],
};
