export default {
  deviewCodeName: 'child_appc_view3',
  deviewId: '24f530061cc5cd54e3844018fdcd6ad8',
  accUserMode: 2,
  capLanguageRes: {
    lanResTag: 'DE.LNAME.MASTER',
  },
  caption: '子应用C视图3',
  codeName: 'master_child_appc_view3',
  appDataEntityId: 'web.master',
  viewLayoutPanel: {
    layoutBodyOnly: true,
    viewProxyMode: true,
    layoutMode: 'FLEX',
    layout: {
      layout: 'FLEX',
    },
    rootPanelItems: [
      {
        actionGroupExtractMode: 'ITEM',
        panelItems: [
          {
            rawItem: {
              caption: '子应用C分页3',
              halign: 'LEFT',
              renderMode: 'TEXT',
              valign: 'MIDDLE',
              wrapMode: 'NOWRAP',
              contentType: 'RAW',
              sysCss: {
                cssName: 'large_white_bold_front',
              },
              predefinedType: 'STATIC_TEXT',
              id: 'static_text',
            },
            caption: '子应用C分页3',
            itemStyle: 'DEFAULT',
            itemType: 'RAWITEM',
            layoutPos: {
              shrink: 1,
              layout: 'FLEX',
            },
            sysCss: {
              cssName: 'large_white_bold_front',
            },
            showCaption: true,
            id: 'static_text',
          },
        ],
        layout: {
          align: 'center',
          dir: 'row',
          layout: 'FLEX',
          valign: 'center',
        },
        dataRegionType: 'INHERIT',
        caption: '容器',
        contentHeight: 400,
        cssStyle: 'background: deepskyblue;',
        height: 400,
        itemStyle: 'DEFAULT',
        itemType: 'CONTAINER',
        layoutPos: {
          shrink: 1,
          height: 400,
          heightMode: 'PX',
          layout: 'FLEX',
          widthMode: 'FULL',
        },
        id: 'container',
      },
    ],
    layoutPanel: true,
    controls: [
      {
        capLanguageRes: {
          lanResTag: 'DE.LNAME.MASTER',
        },
        caption: '子应用C视图3',
        codeName: 'child_appc_view3_captionbar',
        controlType: 'CAPTIONBAR',
        appDataEntityId: 'web.master',
        controlParam: {},
        name: 'captionbar',
        id: 'child_appc_view3_captionbar',
      },
    ],
    codeName: 'layoutpanel',
    controlType: 'VIEWLAYOUTPANEL',
    logicName: 'child_appc_view3',
    appDataEntityId: 'web.master',
    controlParam: {},
    modelId: '12c87cd817d7bf6ca0d78ab7387b1677',
    modelType: 'PSSYSVIEWLAYOUTPANEL',
    id: 'layoutpanel',
  },
  title: '子应用C视图3',
  viewStyle: 'DEFAULT',
  viewType: 'DECUSTOMVIEW',
  enableDP: true,
  showCaptionBar: true,
  modelId: 'f61392b0d3bfe5e173f894add302c0d1',
  modelType: 'PSAPPDEVIEW',
  name: 'MASTERchild_appc_view3',
  id: 'web.master_child_appc_view3',
};
