export default {
  deviewCodeName: 'child_appc_view2',
  deviewId: '1913c5c4d99435e6660e91ecb8f7ca06',
  accUserMode: 2,
  capLanguageRes: {
    lanResTag: 'DE.LNAME.MASTER',
  },
  caption: '子应用C视图2',
  codeName: 'master_child_appc_view2',
  appDataEntityId: 'web.master',
  viewLayoutPanel: {
    layoutBodyOnly: true,
    viewProxyMode: true,
    layoutMode: 'FLEX',
    layout: {
      layout: 'FLEX',
    },
    rootPanelItems: [
      {
        actionGroupExtractMode: 'ITEM',
        panelItems: [
          {
            rawItem: {
              caption: '子应用C关系界面2',
              halign: 'LEFT',
              renderMode: 'TEXT',
              valign: 'MIDDLE',
              wrapMode: 'NOWRAP',
              contentType: 'RAW',
              sysCss: {
                cssName: 'large_white_bold_front',
              },
              predefinedType: 'STATIC_TEXT',
              id: 'static_text',
            },
            caption: '子应用C关系界面2',
            itemStyle: 'DEFAULT',
            itemType: 'RAWITEM',
            layoutPos: {
              shrink: 1,
              layout: 'FLEX',
            },
            sysCss: {
              cssName: 'large_white_bold_front',
            },
            showCaption: true,
            id: 'static_text',
          },
        ],
        layout: {
          align: 'center',
          dir: 'row',
          layout: 'FLEX',
          valign: 'center',
        },
        dataRegionType: 'INHERIT',
        caption: '容器',
        contentHeight: 400,
        cssStyle: 'background: deepskyblue;',
        height: 400,
        itemStyle: 'DEFAULT',
        itemType: 'CONTAINER',
        layoutPos: {
          shrink: 1,
          height: 400,
          heightMode: 'PX',
          layout: 'FLEX',
          widthMode: 'FULL',
        },
        id: 'container',
      },
    ],
    layoutPanel: true,
    controls: [
      {
        capLanguageRes: {
          lanResTag: 'DE.LNAME.MASTER',
        },
        caption: '子应用C视图2',
        codeName: 'child_appc_view2_captionbar',
        controlType: 'CAPTIONBAR',
        appDataEntityId: 'web.master',
        controlParam: {},
        name: 'captionbar',
        id: 'child_appc_view2_captionbar',
      },
    ],
    codeName: 'auto61647987',
    controlType: 'VIEWLAYOUTPANEL',
    logicName: 'child_appc_view2',
    appDataEntityId: 'web.master',
    controlParam: {},
    modelId: '0a8943e4ae2fa571c5cf512a863f4663',
    modelType: 'PSSYSVIEWLAYOUTPANEL',
    name: 'layoutpanel',
    id: 'auto61647987',
  },
  title: '子应用C视图2',
  viewStyle: 'DEFAULT',
  viewType: 'DECUSTOMVIEW',
  enableDP: true,
  showCaptionBar: true,
  modelId: '5225bed1cd03d28dd1d5f4ef609670bc',
  modelType: 'PSAPPDEVIEW',
  name: 'MASTERchild_appc_view2',
  id: 'web.master_child_appc_view2',
};
