export default {
  deviewCodeName: 'child_appc_view',
  deviewId: '9b454595d6a19b21392a8f48e1d4c3ee',
  accUserMode: 2,
  capLanguageRes: {
    lanResTag: 'DE.LNAME.MASTER',
  },
  caption: '子应用C视图',
  codeName: 'master_child_appc_view',
  appDataEntityId: 'web.master',
  viewLayoutPanel: {
    layoutBodyOnly: true,
    viewProxyMode: true,
    layoutMode: 'FLEX',
    layout: {
      layout: 'FLEX',
    },
    rootPanelItems: [
      {
        actionGroupExtractMode: 'ITEM',
        panelItems: [
          {
            rawItem: {
              caption: '子应用C视图',
              halign: 'LEFT',
              renderMode: 'TEXT',
              valign: 'MIDDLE',
              wrapMode: 'NOWRAP',
              contentType: 'RAW',
              sysCss: {
                cssName: 'large_white_bold_front',
              },
              predefinedType: 'STATIC_TEXT',
              id: 'static_text',
            },
            caption: '子应用C视图',
            itemStyle: 'DEFAULT',
            itemType: 'RAWITEM',
            layoutPos: {
              shrink: 1,
              layout: 'FLEX',
            },
            sysCss: {
              cssName: 'large_white_bold_front',
            },
            showCaption: true,
            id: 'static_text',
          },
        ],
        layout: {
          align: 'center',
          dir: 'row',
          layout: 'FLEX',
          valign: 'center',
        },
        dataRegionType: 'INHERIT',
        caption: '容器',
        cssStyle: 'background: deepskyblue;',
        itemStyle: 'DEFAULT',
        itemType: 'CONTAINER',
        layoutPos: {
          shrink: 1,
          heightMode: 'FULL',
          layout: 'FLEX',
          widthMode: 'FULL',
        },
        id: 'container',
      },
    ],
    layoutPanel: true,
    controls: [
      {
        capLanguageRes: {
          lanResTag: 'DE.LNAME.MASTER',
        },
        caption: '子应用C视图',
        codeName: 'child_appc_view_captionbar',
        controlType: 'CAPTIONBAR',
        appDataEntityId: 'web.master',
        controlParam: {},
        name: 'captionbar',
        id: 'child_appc_view_captionbar',
      },
    ],
    codeName: 'auto75065297',
    controlType: 'VIEWLAYOUTPANEL',
    logicName: 'child_appc_view',
    appDataEntityId: 'web.master',
    controlParam: {},
    modelId: 'bc4c20714f464aa733dd40aa08de0d67',
    modelType: 'PSSYSVIEWLAYOUTPANEL',
    name: 'layoutpanel',
    id: 'auto75065297',
  },
  title: '子应用C视图',
  viewStyle: 'DEFAULT',
  viewType: 'DECUSTOMVIEW',
  enableDP: true,
  showCaptionBar: true,
  modelId: 'c8a166a211716d873c397a121f61667a',
  modelType: 'PSAPPDEVIEW',
  name: 'MASTERchild_appc_view',
  id: 'web.master_child_appc_view',
};
