export const predefineThemeVars = [
  {
    caption: '应用',
    labelLang: 'app',
    children: [
      {
        caption: '字体',
        labelLang: 'font',
        vars: [
          {
            label: '字号',
            value: '--ibiz-font-size-regular',
            labelLang: 'fontSize',
            descLang: 'fontSizeDesc',
            unit: 'px',
            type: 'size',
            kindVars: {
              '--ibiz-font-size-small': -2,
              '--ibiz-font-size-header-6': 2,
              '--ibiz-font-size-header-5': 4,
              '--ibiz-font-size-header-4': 6,
              '--ibiz-font-size-header-3': 8,
              '--ibiz-font-size-header-2': 10,
              '--ibiz-font-size-header-1': 12,
            },
          },
          {
            label: '字重',
            value: '--ibiz-font-weight-regular',
            labelLang: 'fontWeight',
            descLang: 'fontWeightDesc',
            type: 'size',
            kindVars: {
              '--ibiz-font-weight-light': -200,
              '--ibiz-font-weight-bold': 200,
            },
          },
        ],
      },
      {
        caption: '颜色',
        labelLang: 'color',
        children: [
          {
            caption: '主要颜色',
            labelLang: 'primaryColor',
            vars: [
              {
                label: '主要颜色',
                description: '主要颜色,仅在需要非常强调的情况下使用',
                labelLang: 'primaryColor',
                descLang: 'primaryColorDesc',
                value: '--ibiz-color-primary',
              },
              {
                label: '主要文本颜色',
                description: '主要颜色文字色，和背景色形成对比',
                labelLang: 'primaryTextColor',
                descLang: 'primaryTextColorDesc',
                value: '--ibiz-color-primary-text',
              },
              {
                label: '主要悬浮颜色',
                description: '主要颜色悬浮态',
                labelLang: 'primaryHoverColor',
                descLang: 'primaryHoverColorDesc',
                value: '--ibiz-color-primary-hover',
              },
              {
                label: '主要悬浮文本颜色',
                description: '主要颜色悬浮态文字色，和背景色形成对比',
                labelLang: 'primaryHoverTextColor',
                descLang: 'primaryHoverTextColorDesc',
                value: '--ibiz-color-primary-hover-text',
              },
              {
                label: '主要激活颜色',
                description: '主要颜色激活态',
                labelLang: 'primaryActiveColor',
                descLang: 'primaryActiveColorDesc',
                value: '--ibiz-color-primary-active',
              },
              {
                label: '主要激活文本颜色',
                description: '主要颜色激活态文字色，和背景色形成对比',
                labelLang: 'primaryActiveTextColor',
                descLang: 'primaryActiveTextColorDesc',
                value: '--ibiz-color-primary-active-text',
              },
              {
                label: '主要禁用颜色',
                description: '主要颜色禁用态',
                labelLang: 'primaryDisabledColor',
                descLang: 'primaryDisabledColorDesc',
                value: '--ibiz-color-primary-disabled',
              },
              {
                label: '主要禁用文本颜色',
                description: '主要颜色禁用态文字色，和背景色形成对比',
                labelLang: 'primaryDisabledTextColor',
                descLang: 'primaryDisabledTextColorDesc',
                value: '--ibiz-color-primary-disabled-text',
              },
              {
                label: '主要浅版颜色',
                description:
                  '浅版主要颜色（多用于背景）。仅在需要非常强调的情况下使用',
                labelLang: 'primaryLightDefaultColor',
                descLang: 'primaryLightDefaultColorDesc',
                value: '--ibiz-color-primary-light-default',
              },
              {
                label: '主要浅版悬浮色',
                description: '浅版主要颜色悬浮态',
                labelLang: 'primaryLightHoverColor',
                descLang: 'primaryLightHoverColorDesc',
                value: '--ibiz-color-primary-light-hover',
              },
              {
                label: '主要浅版激活色',
                description: '浅版主要颜色激活态',
                labelLang: 'primaryLightActiveColor',
                descLang: 'primaryLightActiveColorDesc',
                value: '--ibiz-color-primary-light-active',
              },
            ],
          },
          {
            caption: '文本颜色',
            labelLang: 'text',
            vars: [
              {
                label: '文本主色',
                description: '文本颜色 - 最主要',
                labelLang: 'mainTextColor',
                descLang: 'mianTextColorDesc',
                value: '--ibiz-color-text-0',
              },
              {
                label: '文本稍次色',
                description: '文本颜色 - 稍次要',
                labelLang: 'minorTextColor',
                descLang: 'minorTextColorDesc',
                value: '--ibiz-color-text-1',
              },
              {
                label: '文本次色',
                description: '文本颜色 - 次要',
                labelLang: 'secondaryTextColor',
                descLang: 'secondaryTextColorDesc',
                value: '--ibiz-color-text-2',
              },
              {
                label: '文本最次色',
                description: '文本颜色 - 最次要',
                labelLang: 'lastTextColor',
                descLang: 'lastTextColorDesc',
                value: '--ibiz-color-text-3',
              },
            ],
          },
          {
            caption: '链接颜色',
            labelLang: 'linkColor',
            vars: [
              {
                label: '文本链接色',
                description: '链接颜色 - 最主要',
                labelLang: 'textLinkColor',
                descLang: 'textLinkColorDesc',
                value: '--ibiz-color-link',
              },
              {
                label: '文本链接悬浮色',
                description: '链接颜色 - 悬浮态',
                labelLang: 'textLinkHoverColor',
                descLang: 'textLinkHoverColorDesc',
                value: '--ibiz-color-link-hover',
              },
              {
                label: '文本链接激活色',
                description: '链接颜色 - 激活态',
                labelLang: 'textLinkActiveColor',
                descLang: 'textLinkActiveColorDesc',
                value: '--ibiz-color-link-active',
              },
              {
                label: '文本链接已访问色',
                description: '链接颜色 - 已访问',
                labelLang: 'textLinkVisitedColor',
                descLang: 'textLinkVisitedColorDesc',
                value: '--ibiz-color-link-visited',
              },
            ],
          },
          {
            caption: '背景色',
            labelLang: 'bgColor',
            vars: [
              {
                label: '背景色最下层',
                description: '背景色 - 最下层（底部页面）',
                labelLang: 'bgColorLowestLayer',
                descLang: 'bgColorLowestLayerDesc',
                value: '--ibiz-color-bg-0',
              },
              {
                label: '背景色次下层',
                description: '背景色 - 次下层（页面中需要提升的内容）',
                labelLang: 'bgColorLowerLayer',
                descLang: 'bgColorLowerLayerDesc',
                value: '--ibiz-color-bg-1',
              },
              {
                label: '背景色中层',
                description: '背景色 - 中间层（模态等容器）',
                labelLang: 'bgColorCenterLayer',
                descLang: 'bgColorCenterLayerDesc',
                value: '--ibiz-color-bg-2',
              },
              {
                label: '背景色次上层',
                description: '背景色 - 次上层(通知,Toast等)',
                labelLang: 'bgColorSecondaryUpperLayer',
                descLang: 'bgColorSecondaryUpperLayerDesc',
                value: '--ibiz-color-bg-3',
              },
              {
                label: '背景色最上层',
                description: '背景色 - 最上层（特殊）',
                labelLang: 'bgColorTopLayer',
                descLang: 'bgColorTopLayerDesc',
                value: '--ibiz-color-bg-4',
              },
            ],
          },
          {
            caption: '填充色',
            labelLang: 'fillColor',
            vars: [
              {
                label: '默认填充色',
                description: '填充色 - 默认态',
                labelLang: 'fillDefault',
                descLang: 'fillDefaultDesc',
                value: '--ibiz-color-fill-0',
              },
              {
                label: '悬浮填充色',
                description: '填充色 - 悬浮态',
                labelLang: 'fillHover',
                descLang: 'fillHoverDesc',
                value: '--ibiz-color-fill-1',
              },
              {
                label: '激活填充色',
                description: '填充色 - 激活态',
                labelLang: 'fillActive',
                descLang: 'fillActiveDesc',
                value: '--ibiz-color-fill-2',
              },
            ],
          },
          {
            caption: '边框',
            labelLang: 'border',
            vars: [
              {
                label: '边框色',
                description: '默认描边颜色',
                labelLang: 'borderColor',
                descLang: 'borderColorDesc',
                value: '--ibiz-color-border',
              },
            ],
          },
          {
            caption: '禁用态',
            labelLang: 'disabledState',
            vars: [
              {
                label: '禁用文本色',
                description: '禁用态 - 文字',
                labelLang: 'disabledText',
                descLang: 'disabledTextDesc',
                value: '--ibiz-color-disabled-text',
              },
              {
                label: '禁用描边色',
                description: '禁用态 - 描边',
                labelLang: 'disabledTextBorder',
                descLang: 'disabledTextBorderDesc',
                value: '--ibiz-color-disabled-border',
              },
              {
                label: '禁用背景色',
                description: '禁用态 - 背景',
                labelLang: 'disabledBg',
                descLang: 'disabledBgDesc',
                value: '--ibiz-color-disabled-bg',
              },
              {
                label: '禁用填充色',
                description: '禁用态 - 填充',
                labelLang: 'disabledFill',
                descLang: 'disabledFillDesc',
                value: '--ibiz-color-disabled-fill',
              },
            ],
          },
        ],
      },
      {
        caption: '其他',
        labelLang: 'other',
        vars: [
          {
            label: '间距',
            value: '--ibiz-spacing-base',
            labelLang: 'spacing',
            descLang: 'spacingDesc',
            unit: 'px',
            type: 'size',
            kindVars: {
              '--ibiz-spacing-super-tight': -14,
              '--ibiz-spacing-extra-tight': -12,
              '--ibiz-spacing-tight': -8,
              '--ibiz-spacing-base-tight': -4,
              '--ibiz-spacing-base-loose': 4,
              '--ibiz-spacing-loose': 8,
              '--ibiz-spacing-extra-loose': 16,
              '--ibiz-spacing-super-loose': 24,
            },
          },
          {
            label: '圆角',
            value: '--ibiz-border-radius-medium',
            labelLang: 'borderRadius',
            descLang: 'borderRadiusDesc',
            unit: 'px',
            type: 'size',
            kindVars: {
              '--ibiz-border-radius-extra-small': -6,
              '--ibiz-border-radius-small': -4,
              '--ibiz-border-radius-large': 4,
            },
          },
          {
            label: '图标尺寸',
            value: '--ibiz-width-icon-medium',
            labelLang: 'widthIcon',
            descLang: 'widthIconDesc',
            unit: 'px',
            type: 'size',
            kindVars: {
              '--ibiz-width-icon-extra-small': -16,
              '--ibiz-width-icon-small': -4,
              '--ibiz-width-icon-large': 4,
              '--ibiz-width-icon-extra-large': 8,
            },
          },
        ],
      },
    ],
  },
  // 导航栏中菜单激活色和悬浮色相反
  {
    caption: '顶部导航栏',
    labelLang: 'top',
    vars: [
      {
        label: '字体主要颜色',
        value: '--ibiz-panel-app-header-horizontal-color',
        defaultValue: '--ibiz-color-primary-text',
        labelLang: 'mainColor',
        descLang: 'mainColorDesc',
        className: 'ibiz-panel-app-header',
      },
      {
        label: '字体次要颜色',
        value: '--ibiz-panel-app-header-horizontal-color-1',
        defaultValue: '--ibiz-color-text-5',
        labelLang: 'secondaryColor',
        descLang: 'secondaryColorDesc',
        className: 'ibiz-panel-app-header',
      },
      {
        label: '背景主要颜色',
        value: '--ibiz-panel-app-header-horizontal-bg-color',
        defaultValue: '--ibiz-color-primary',
        labelLang: 'mainBgColor',
        descLang: 'mainBgColorDesc',
        className: 'ibiz-panel-app-header',
      },
      {
        label: '背景次要颜色',
        value: '--ibiz-panel-app-header-horizontal-bg-color-1',
        defaultValue: '--ibiz-color-bg-5',
        labelLang: 'secondaryBgColor',
        descLang: 'secondaryBgColorDesc',
        className: 'ibiz-panel-app-header',
      },
      {
        label: '图标主要颜色',
        value: '--ibiz-panel-app-header-horizontal-color-icon-0',
        defaultValue: '--ibiz-color-icon-0',
        labelLang: 'iconMainColor',
        descLang: 'iconMainColorDesc',
        className: 'ibiz-panel-app-header',
      },
      {
        label: '图标次要颜色',
        value: '--ibiz-panel-app-header-horizontal-color-icon-1',
        defaultValue: '--ibiz-color-icon-1',
        labelLang: 'iconSecondaryColor',
        descLang: 'iconSecondaryColorDesc',
        className: 'ibiz-panel-app-header',
      },
      {
        label: '应用菜单字体颜色',
        value: '--ibiz-panel-app-header-horizontal-menu-color',
        defaultValue: '--ibiz-color-text-menu',
        labelLang: 'appMenuColor',
        descLang: 'appMenuColorDesc',
        className: 'ibiz-panel-app-header',
      },
      {
        label: '应用菜单悬浮字体色',
        value: '--ibiz-panel-app-header-horizontal-active-color',
        defaultValue: '--ibiz-color-primary-active-text',
        labelLang: 'appMenuHoverColor',
        descLang: 'appMenuHoverColorDesc',
        className: 'ibiz-panel-app-header',
      },
      {
        label: '应用菜单悬浮背景色',
        value: '--ibiz-panel-app-header-horizontal-active-bg-color',
        defaultValue: '--ibiz-color-primary-active',
        labelLang: 'appMenuHoverBgColor',
        descLang: 'appMenuHoverBgColorDesc',
        className: 'ibiz-panel-app-header',
      },
      {
        label: '应用菜单选中字体色',
        value: '--ibiz-panel-app-header-horizontal-hover-color',
        defaultValue: '--ibiz-color-primary-hover-text',
        labelLang: 'appMenuActiveColor',
        descLang: 'appMenuActiveColorDesc',
        className: 'ibiz-panel-app-header',
      },
      {
        label: '应用菜单选中背景色',
        value: '--ibiz-panel-app-header-horizontal-hover-bg-color',
        defaultValue: '--ibiz-color-primary-hover',
        labelLang: 'appMenuActiveBgColor',
        descLang: 'appMenuActiveBgColorDesc',
        className: 'ibiz-panel-app-header',
      },
    ],
  },
  {
    caption: '侧边导航栏',
    labelLang: 'sidebar',
    vars: [
      {
        label: '字体主要颜色',
        value: '--ibiz-panel-app-header-color',
        defaultValue: '--ibiz-color-primary-text',
        labelLang: 'mainColor',
        descLang: 'mainColorDesc',
        className: 'ibiz-panel-app-header',
      },
      {
        label: '字体次要颜色',
        value: '--ibiz-panel-app-header-color-1',
        defaultValue: '--ibiz-color-text-5',
        labelLang: 'secondaryColor',
        descLang: 'secondaryColorDesc',
        className: 'ibiz-panel-app-header',
      },
      {
        label: '背景主要颜色',
        value: '--ibiz-panel-app-header-bg-color',
        defaultValue: '--ibiz-color-primary',
        labelLang: 'mainBgColor',
        descLang: 'mainBgColorDesc',
        className: 'ibiz-panel-app-header',
      },
      {
        label: '背景次要颜色',
        value: '--ibiz-panel-app-header-bg-color-1',
        defaultValue: '--ibiz-color-bg-5',
        labelLang: 'secondaryBgColor',
        descLang: 'secondaryBgColorDesc',
        className: 'ibiz-panel-app-header',
      },
      {
        label: '图标主要颜色',
        value: '--ibiz-panel-app-header-color-icon-0',
        defaultValue: '--ibiz-color-icon-0',
        labelLang: 'iconMainColor',
        descLang: 'iconMainColorDesc',
        className: 'ibiz-panel-app-header',
      },
      {
        label: '图标次要颜色',
        value: '--ibiz-panel-app-header-color-icon-1',
        defaultValue: '--ibiz-color-icon-1',
        labelLang: 'iconSecondaryColor',
        descLang: 'iconSecondaryColorDesc',
        className: 'ibiz-panel-app-header',
      },
      {
        label: '应用菜单字体颜色',
        value: '--ibiz-panel-app-header-menu-color',
        defaultValue: '--ibiz-color-text-menu',
        labelLang: 'appMenuColor',
        descLang: 'appMenuColorDesc',
        className: 'ibiz-panel-app-header',
      },
      {
        label: '应用菜单悬浮字体色',
        value: '--ibiz-panel-app-header-active-color',
        defaultValue: '--ibiz-color-primary-active-text',
        labelLang: 'appMenuHoverColor',
        descLang: 'appMenuHoverColorDesc',
        className: 'ibiz-panel-app-header',
      },
      {
        label: '应用菜单悬浮背景色',
        value: '--ibiz-panel-app-header-active-bg-color',
        defaultValue: '--ibiz-color-primary-active',
        labelLang: 'appMenuHoverBgColor',
        descLang: 'appMenuHoverBgColorDesc',
        className: 'ibiz-panel-app-header',
      },
      {
        label: '应用菜单选中字体色',
        value: '--ibiz-panel-app-header-hover-color',
        defaultValue: '--ibiz-color-primary-hover-text',
        labelLang: 'appMenuActiveColor',
        descLang: 'appMenuActiveColorDesc',
        className: 'ibiz-panel-app-header',
      },
      {
        label: '应用菜单选中背景色',
        value: '--ibiz-panel-app-header-hover-bg-color',
        defaultValue: '--ibiz-color-primary-hover',
        labelLang: 'appMenuActiveBgColor',
        descLang: 'appMenuActiveBgColorDesc',
        className: 'ibiz-panel-app-header',
      },
    ],
  },
  {
    caption: '控件',
    labelLang: 'ctrl',
    children: [
      {
        caption: '表格',
        labelLang: 'grid',
        vars: [
          {
            label: '表格头字体色',
            value: '--ibiz-control-grid-header-text-color',
            defaultValue: '--ibiz-color-text-2',
            labelLang: 'gridHeaderColor',
            descLang: 'gridHeaderColorDesc',
            className: 'ibiz-control-grid',
          },
          {
            label: '表格头背景色',
            value: '--ibiz-control-grid-header-bg-color',
            defaultValue: '--ibiz-color-fill-1',
            labelLang: 'gridHeaderBg',
            descLang: 'gridHeaderBgDesc',
            className: 'ibiz-control-grid',
          },
          {
            label: '表格行字体色',
            value: '--ibiz-control-grid-text-color',
            defaultValue: '--ibiz-color-text-0',
            labelLang: 'gridRowColor',
            descLang: 'gridRowColorDesc',
            className: 'ibiz-control-grid',
          },
          {
            label: '表格行背景色亮色',
            value: '--ibiz-control-grid-row-bg-color',
            defaultValue: '--ibiz-color-bg-1',
            labelLang: 'gridRowBg',
            descLang: 'gridRowBgDesc',
            className: 'ibiz-control-grid',
          },
          {
            label: '表格行背景色暗色',
            value: '--ibiz-control-grid-row-bg-color-2',
            defaultValue: '--ibiz-color-bg-0',
            labelLang: 'gridRowBg2',
            descLang: 'gridRowBg2Desc',
            className: 'ibiz-control-grid',
          },
          {
            label: '表格行悬浮色',
            value: '--ibiz-control-grid-row-hover-color',
            defaultValue: '--ibiz-grey-1',
            labelLang: 'gridRowHover',
            descLang: 'gridRowHoverDesc',
            className: 'ibiz-control-grid',
          },
          {
            label: '表格行选中色',
            value: '--ibiz-control-grid-row-select-color',
            defaultValue: '--ibiz-color-primary-light-default',
            labelLang: 'gridRowSelect',
            descLang: 'gridRowSelectDesc',
            className: 'ibiz-control-grid',
          },
        ],
      },
      {
        caption: '树',
        labelLang: 'tree',
        vars: [
          {
            label: '树视图文本色',
            value: '--ibiz-control-treeview-text-color',
            defaultValue: '--ibiz-color-text-0',
            labelLang: 'treeTextColor',
            descLang: 'treeTextColorDesc',
            className: 'ibiz-control-treeview',
          },
          {
            label: '树视图背景色',
            value: '--ibiz-control-treeview-bg-color',
            defaultValue: '#00000000',
            labelLang: 'treeBgColor',
            descLang: 'treeBgColorDesc',
            className: 'ibiz-control-treeview',
          },
          {
            label: '树视图禁用色',
            value: '--ibiz-control-treeview-disabled-color',
            defaultValue: '--ibiz-color-disabled-text',
            labelLang: 'treeDisabledColor',
            descLang: 'treeDisabledColorDesc',
            className: 'ibiz-control-treeview',
          },
          {
            label: '树视图悬浮色',
            value: '--ibiz-control-treeview-row-hover-color',
            defaultValue: '--ibiz-color-text-0',
            labelLang: 'treeHoverColor',
            descLang: 'treeHoverColorDesc',
            className: 'ibiz-control-treeview',
          },
          {
            label: '树视图悬浮背景色',
            value: '--ibiz-control-treeview-row-hover-bg-color',
            defaultValue: '--ibiz-color-fill-0',
            labelLang: 'treeHoverBgColor',
            descLang: 'treeHoverBgColorDesc',
            className: 'ibiz-control-treeview',
          },
          {
            label: '树视图选中色',
            value: '--ibiz-control-treeview-row-select-color',
            defaultValue: '--ibiz-color-text-0',
            labelLang: 'treeSelectColor',
            descLang: 'treeSelectColorDesc',
            className: 'ibiz-control-treeview',
          },
          {
            label: '树视图选中背景色',
            value: '--ibiz-control-treeview-row-select-bg-color',
            defaultValue: '--ibiz-color-primary-light-default',
            labelLang: 'treeSelectBgColor',
            descLang: 'treeSelectBgColorDesc',
            className: 'ibiz-control-treeview',
          },
        ],
      },
    ],
  },
];
